<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use RZP\Constants\Table;
use RZP\Models\Merchant\Account;
use RZP\Models\Tax\Gst\GstTaxIdMap;

class TaxGroupAndTaxSeeder extends Seeder
{
    public function run()
    {
        //Eloquent::unguard();

        DB::transaction(function() {
            $this->seedTaxGroups();
            $this->seedTaxes();
            $this->seedTaxGroupTaxMap();
        });
    }

    private function seedTaxGroups()
    {
        DB::table(Table::TAX_GROUP)->insert(
            [
                [
                    'id'          => '00000000000001',
                    'merchant_id' => '10000000000000',
                    'name'        => 'Tax Group #1',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => '00000000000002',
                    'merchant_id' => '10000000000000',
                    'name'        => 'Tax Group #2',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
            ]);
    }

    private function seedTaxes()
    {
        DB::table(Table::TAX)->insert(
            [
                [
                    'id'          => '00000000000001',
                    'merchant_id' => '10000000000000',
                    'name'        => 'Tax #1',
                    'rate_type'   => 'percentage',
                    'rate'        => '100000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => '00000000000002',
                    'merchant_id' => '10000000000000',
                    'name'        => 'Tax #2',
                    'rate_type'   => 'percentage',
                    'rate'        => '200000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => '00000000000003',
                    'merchant_id' => '10000000000000',
                    'name'        => 'Tax #3',
                    'rate_type'   => 'percentage',
                    'rate'        => '150000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => '00000000000004',
                    'merchant_id' => '10000000000000',
                    'name'        => 'Flat Tax #4',
                    'rate_type'   => 'flat',
                    'rate'        => '100',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],

                //
                // GST Taxes
                //

                // IGST
                [
                    'id'          => GstTaxIdMap::IGST_0,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'IGST 0%',
                    'rate_type'   => 'percentage',
                    'rate'        => '0',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::IGST_1000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'IGST 0.1%',
                    'rate_type'   => 'percentage',
                    'rate'        => '1000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::IGST_2500,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'IGST 0.25%',
                    'rate_type'   => 'percentage',
                    'rate'        => '2500',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::IGST_30000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'IGST 3%',
                    'rate_type'   => 'percentage',
                    'rate'        => '30000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::IGST_50000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'IGST 5%',
                    'rate_type'   => 'percentage',
                    'rate'        => '50000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::IGST_120000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'IGST 12%',
                    'rate_type'   => 'percentage',
                    'rate'        => '120000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::IGST_180000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'IGST 18%',
                    'rate_type'   => 'percentage',
                    'rate'        => '180000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::IGST_280000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'IGST 28%',
                    'rate_type'   => 'percentage',
                    'rate'        => '280000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],

                // CGST
                [
                    'id'          => GstTaxIdMap::CGST_0,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 0%',
                    'rate_type'   => 'percentage',
                    'rate'        => '0',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_500,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 0.05%',
                    'rate_type'   => 'percentage',
                    'rate'        => '500',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_1000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 0.1%',
                    'rate_type'   => 'percentage',
                    'rate'        => '1000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_1250,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 0.125%',
                    'rate_type'   => 'percentage',
                    'rate'        => '1250',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_2500,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 0.25%',
                    'rate_type'   => 'percentage',
                    'rate'        => '2500',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_15000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 1.5%',
                    'rate_type'   => 'percentage',
                    'rate'        => '15000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_25000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 2.5%',
                    'rate_type'   => 'percentage',
                    'rate'        => '25000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_30000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 3%',
                    'rate_type'   => 'percentage',
                    'rate'        => '30000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_50000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 5%',
                    'rate_type'   => 'percentage',
                    'rate'        => '50000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_60000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 6%',
                    'rate_type'   => 'percentage',
                    'rate'        => '60000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_90000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 9%',
                    'rate_type'   => 'percentage',
                    'rate'        => '90000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_120000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 12%',
                    'rate_type'   => 'percentage',
                    'rate'        => '120000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_140000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 14%',
                    'rate_type'   => 'percentage',
                    'rate'        => '140000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_180000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 18%',
                    'rate_type'   => 'percentage',
                    'rate'        => '180000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::CGST_280000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'CGST 28%',
                    'rate_type'   => 'percentage',
                    'rate'        => '280000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],

                // SGST
                [
                    'id'          => GstTaxIdMap::SGST_0,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 0%',
                    'rate_type'   => 'percentage',
                    'rate'        => '0',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_500,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 0.05%',
                    'rate_type'   => 'percentage',
                    'rate'        => '500',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_1000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 0.1%',
                    'rate_type'   => 'percentage',
                    'rate'        => '1000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_1250,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 0.125%',
                    'rate_type'   => 'percentage',
                    'rate'        => '1250',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_2500,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 0.25%',
                    'rate_type'   => 'percentage',
                    'rate'        => '2500',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_15000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 1.5%',
                    'rate_type'   => 'percentage',
                    'rate'        => '15000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_25000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 2.5%',
                    'rate_type'   => 'percentage',
                    'rate'        => '25000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_30000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 3%',
                    'rate_type'   => 'percentage',
                    'rate'        => '30000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_50000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 5%',
                    'rate_type'   => 'percentage',
                    'rate'        => '50000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_60000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 6%',
                    'rate_type'   => 'percentage',
                    'rate'        => '60000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_90000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 9%',
                    'rate_type'   => 'percentage',
                    'rate'        => '90000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_120000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 12%',
                    'rate_type'   => 'percentage',
                    'rate'        => '120000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_140000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 14%',
                    'rate_type'   => 'percentage',
                    'rate'        => '140000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_180000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 18%',
                    'rate_type'   => 'percentage',
                    'rate'        => '180000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::SGST_280000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'SGST 28%',
                    'rate_type'   => 'percentage',
                    'rate'        => '280000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],

                // UTGST
                [
                    'id'          => GstTaxIdMap::UTGST_0,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 0%',
                    'rate_type'   => 'percentage',
                    'rate'        => '0',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_500,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 0.05%',
                    'rate_type'   => 'percentage',
                    'rate'        => '500',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_1000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 0.1%',
                    'rate_type'   => 'percentage',
                    'rate'        => '1000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_1250,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 0.125%',
                    'rate_type'   => 'percentage',
                    'rate'        => '1250',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_2500,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 0.25%',
                    'rate_type'   => 'percentage',
                    'rate'        => '2500',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_15000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 1.5%',
                    'rate_type'   => 'percentage',
                    'rate'        => '15000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_25000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 2.5%',
                    'rate_type'   => 'percentage',
                    'rate'        => '25000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_30000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 3%',
                    'rate_type'   => 'percentage',
                    'rate'        => '30000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_50000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 5%',
                    'rate_type'   => 'percentage',
                    'rate'        => '50000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_60000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 6%',
                    'rate_type'   => 'percentage',
                    'rate'        => '60000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_90000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 9%',
                    'rate_type'   => 'percentage',
                    'rate'        => '90000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_120000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 12%',
                    'rate_type'   => 'percentage',
                    'rate'        => '120000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_140000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 14%',
                    'rate_type'   => 'percentage',
                    'rate'        => '140000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_180000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 18%',
                    'rate_type'   => 'percentage',
                    'rate'        => '180000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
                [
                    'id'          => GstTaxIdMap::UTGST_280000,
                    'merchant_id' => Account::SHARED_ACCOUNT,
                    'name'        => 'UTGST 28%',
                    'rate_type'   => 'percentage',
                    'rate'        => '280000',
                    'created_at'  => time(),
                    'updated_at'  => time(),
                    'deleted_at'  => null,
                ],
            ]);
    }

    private function seedTaxGroupTaxMap()
    {
        DB::table(Table::TAX_GROUP_TAX_MAP)->insert(
            [
                [
                    'tax_group_id' => '00000000000001',
                    'tax_id'       => '00000000000001',
                    'created_at'   => time(),
                    'updated_at'   => time(),
                ],
                [
                    'tax_group_id' => '00000000000001',
                    'tax_id'       => '00000000000002',
                    'created_at'   => time(),
                    'updated_at'   => time(),
                ],
                [
                    'tax_group_id' => '00000000000002',
                    'tax_id'       => '00000000000001',
                    'created_at'   => time(),
                    'updated_at'   => time(),
                ],
                [
                    'tax_group_id' => '00000000000002',
                    'tax_id'       => '00000000000004',
                    'created_at'   => time(),
                    'updated_at'   => time(),
                ],
            ]);
    }
}
