<?php

return [
    'testGetGlobalCustomerDetailsForCheckoutService' => [
        'request' => [
            'url' => '/internal/customers/checkout',
            'method' => 'GET',
        ],
        'response' => [
            'content' => [
                'email' => 'test@razorpay.com',
                'contact' => '+919988776655',
                'is_global_customer' => true,
                'has_saved_card_tokens' => false,
                'has_saved_addresses' => false,
            ],
        ],
    ],

    'testGetGlobalCustomerDetailsForCheckoutServiceUsingPassportJWT' => [
        'request' => [
            'url' => '/internal/customers/checkout',
            'method' => 'GET',
            'headers' => [
                'X-Passport-JWT-V1' => '', // Filled by the test
            ],
        ],
        'response' => [
            'content' => [
                'email' => 'test@razorpay.com',
                'contact' => '+919988776655',
                'is_global_customer' => true,
                'has_saved_card_tokens' => false,
                'has_saved_addresses' => false,
            ],
        ],
    ],

    'testGetLocalCustomerDetailsForCheckoutService' => [
        'request' => [
            'url' => '/internal/customers/checkout',
            'method' => 'GET',
            'content' => [
                'customer_id' => 'cust_zMRVsGfjoQyc9w', // Filled by the Test
            ],
        ],
        'response' => [
            'content' => [
                'email' => 'testlocalcustomer@razorpay.com',
                'contact' => '+919876543210',
                'is_global_customer' => false,
                'has_saved_card_tokens' => true,
                'has_saved_addresses' => false,
            ],
        ],
    ],

    'testFindOrCreateGlobalCustomerForANewCustomerOnStandardCheckout' => [
        'request' => [
            'url' => '/checkout/global_customers',
            'method' => 'POST',
            'content' => [
                'contact' => '+919876543210',
                'email' => 'testglobalcustomer@razorpay.com',
            ],
        ],
        'response' => [
            'content' => [
                'customer' => [
                    'email' => 'testglobalcustomer@razorpay.com',
                    'contact' => '+919876543210',
                ],
            ],
        ],
    ],

    'testFindOrCreateGlobalCustomerForAnExistingCustomerOnStandardCheckout' => [
        'request' => [
            'url' => '/checkout/global_customers',
            'method' => 'POST',
            'content' => [
                'contact' => '+919878543210',
                'email' => 'testexistingglobalcustomer@razorpay.com',
            ],
        ],
        'response' => [
            'content' => [
                'customer' => [
                    'id' => 'zMRVsEqPxuwiGl',
                    'email' => 'testexistingglobalcustomer@razorpay.com',
                    'contact' => '+919878543210',
                ],
                'tokens' => [
                    'entity' => 'collection',
                    'count' => 1,
                    'items' => [
                        0 => [
                            'id' => 'token_M9EQ5OztDvu5oh',
                            'entity' => 'token',
                            'token' => '1000lcardtoken',
                            'bank' => 'ICIC',
                            'wallet' => 'paytm',
                            'method' => 'card',
                            'card' => [
                                'entity' => 'card',
                                'name' => '',
                                'last4' => '1111',
                                'network' => 'Visa',
                                'type' => 'credit',
                                'issuer' => 'HDFC',
                                'international' => false,
                                'emi' => true,
                                'sub_type' => null,
                                'token_iin' => null,
                                'expiry_month' => '01',
                                'expiry_year' => '2099',
                                'flows' => [
                                    'recurring' => true,
                                ],
                                'cobranding_partner' => null,
                            ],
                            'recurring' => false,
                            'recurring_details' => [
                                'status' => null,
                                'failure_reason' => null,
                            ],
                            'auth_type' => null,
                            'mrn' => null,
                            'used_at' => 1688365852,
                            'created_at' => 1688365852,
                            'expired_at' => 1706725799,
                            'consent_taken' => true,
                            'status' => 'active',
                            'notes' => [],
                            'error_description' => null,
                            'source' => 'business',
                            'dcc_enabled' => false,
                            'max_amount' => null,
                            'error_code' => null,
                            'compliant_with_tokenisation_guidelines' => true,
                        ],
                    ],
                ],
            ],
        ],
    ],

    'testFindOrCreateGlobalCustomerForAnExistingCustomerOnOneClickCheckout' => [
        'request' => [
            'url' => '/checkout/global_customers',
            'method' => 'POST',
            'content' => [
                'contact' => '+919878543210',
                'email' => 'testexistingglobalcustomer@razorpay.com',
                'address_consent' => [
                    'device_id' => 'qwertyuiop1234567',
                ],
                'is_one_cc' => 1,
            ],
        ],
        'response' => [
            'content' => [
                'customer' => [
                    'id' => 'zMRVsEqPxuwiGl',
                    'email' => 'testexistingglobalcustomer@razorpay.com',
                    'contact' => '+919878543210',
                ],
                'tokens' => [
                    'entity' => 'collection',
                    'count' => 1,
                    'items' => [
                        [
                            'id' => 'token_M9EQ5OztDvu5oh',
                            'entity' => 'token',
                            'token' => '1000lcardtoken',
                            'bank' => 'ICIC',
                            'wallet' => 'paytm',
                            'method' => 'card',
                            'card' => [
                                'entity' => 'card',
                                'name' => '',
                                'last4' => '1111',
                                'network' => 'Visa',
                                'type' => 'credit',
                                'issuer' => 'HDFC',
                                'international' => false,
                                'emi' => true,
                                'sub_type' => null,
                                'token_iin' => null,
                                'expiry_month' => '01',
                                'expiry_year' => '2099',
                                'flows' => [
                                    'recurring' => true,
                                ],
                                'cobranding_partner' => null,
                            ],
                            'recurring' => false,
                            'recurring_details' => [
                                'status' => null,
                                'failure_reason' => null,
                            ],
                            'auth_type' => null,
                            'mrn' => null,
                            'used_at' => 1688365852,
                            'created_at' => 1688365852,
                            'expired_at' => 1706725799,
                            'consent_taken' => true,
                            'status' => 'active',
                            'notes' => [],
                            'error_description' => null,
                            'source' => 'business',
                            'dcc_enabled' => false,
                            'max_amount' => null,
                            'error_code' => null,
                            'compliant_with_tokenisation_guidelines' => true,
                        ],
                    ],
                ],
                'one_cc_addresses' => [
                    [
                        'id' => 'M9ICOyJ139iODr',
                        'entity_id' => 'zMRVsEqPxuwiGl',
                        'entity_type' => 'customer',
                        'line1' => 'billing address line 1',
                        'line2' => 'some line two',
                        'city' => 'Bengaluru',
                        'zipcode' => '560030',
                        'state' => 'Karnataka',
                        'country' => 'in',
                        'type' => 'billing_address',
                        'primary' => true,
                        'contact' => null,
                        'name' => null,
                        'tag' => null,
                        'landmark' => null,
                        'deleted_at' => null,
                        'created_at' => 1688365852,
                        'source_id' => null,
                        'source_type' => 'shopify',
                    ],
                    [
                        'id' => 'M9ICOzBhiakey8',
                        'entity_id' => 'zMRVsEqPxuwiGl',
                        'entity_type' => 'customer',
                        'line1' => 'shipping address line 1',
                        'line2' => 'some line two',
                        'city' => 'Bengaluru',
                        'zipcode' => '560029',
                        'state' => 'Karnataka',
                        'country' => 'in',
                        'type' => 'shipping_address',
                        'primary' => true,
                        'contact' => null,
                        'name' => null,
                        'tag' => null,
                        'landmark' => null,
                        'deleted_at' => null,
                        'created_at' => 1688365852,
                        'source_id' => null,
                        'source_type' => 'payment_pages',
                    ],
                ],
                'one_cc_consent_banner_views' => 0,
                'one_cc_customer_consent' => 1,
            ],
        ],
    ],

    'testFindOrCreateGlobalCustomerForAnExistingCustomerOnOneClickCheckoutForNoTripleConsent' => [
        'request' => [
            'url' => '/checkout/global_customers',
            'method' => 'POST',
            'content' => [
                'contact' => '+919878543210',
                'email' => 'testexistingglobalcustomer@razorpay.com',
                'address_consent' => [
                    'device_id' => 'qwertyuiop1234567',
                ],
                'is_one_cc' => 1,
            ],
        ],
        'response' => [
            'content' => [
                'customer' => [
                    'id' => 'zMRVsEqPxuwiGl',
                    'email' => 'testexistingglobalcustomer@razorpay.com',
                    'contact' => '+919878543210',
                ],
                'tokens' => [
                    'entity' => 'collection',
                    'count' => 1,
                    'items' => [
                        [
                            'id' => 'token_M9EQ5OztDvu5oh',
                            'entity' => 'token',
                            'token' => '1000lcardtoken',
                            'bank' => 'ICIC',
                            'wallet' => 'paytm',
                            'method' => 'card',
                            'card' => [
                                'entity' => 'card',
                                'name' => '',
                                'last4' => '1111',
                                'network' => 'Visa',
                                'type' => 'credit',
                                'issuer' => 'HDFC',
                                'international' => false,
                                'emi' => true,
                                'sub_type' => null,
                                'token_iin' => null,
                                'expiry_month' => '01',
                                'expiry_year' => '2099',
                                'flows' => [
                                    'recurring' => true,
                                ],
                                'cobranding_partner' => null,
                            ],
                            'recurring' => false,
                            'recurring_details' => [
                                'status' => null,
                                'failure_reason' => null,
                            ],
                            'auth_type' => null,
                            'mrn' => null,
                            'used_at' => 1688365852,
                            'created_at' => 1688365852,
                            'expired_at' => 1706725799,
                            'consent_taken' => true,
                            'status' => 'active',
                            'notes' => [],
                            'error_description' => null,
                            'source' => 'business',
                            'dcc_enabled' => false,
                            'max_amount' => null,
                            'error_code' => null,
                            'compliant_with_tokenisation_guidelines' => true,
                        ],
                    ],
                ],
                'one_cc_addresses' => [
                    [
                        'id' => 'M9ICOyJ139iODr',
                        'entity_id' => 'zMRVsEqPxuwiGl',
                        'entity_type' => 'customer',
                        'line1' => 'billing address line 1',
                        'line2' => 'some line two',
                        'city' => 'Bengaluru',
                        'zipcode' => '560030',
                        'state' => 'Karnataka',
                        'country' => 'in',
                        'type' => 'billing_address',
                        'primary' => true,
                        'contact' => null,
                        'name' => null,
                        'tag' => null,
                        'landmark' => null,
                        'deleted_at' => null,
                        'created_at' => 1688365852,
                        'source_id' => null,
                        'source_type' => 'shopify',
                    ],
                    [
                        'id' => 'M9ICOzBhiakey8',
                        'entity_id' => 'zMRVsEqPxuwiGl',
                        'entity_type' => 'customer',
                        'line1' => 'shipping address line 1',
                        'line2' => 'some line two',
                        'city' => 'Bengaluru',
                        'zipcode' => '560029',
                        'state' => 'Karnataka',
                        'country' => 'in',
                        'type' => 'shipping_address',
                        'primary' => true,
                        'contact' => null,
                        'name' => null,
                        'tag' => null,
                        'landmark' => null,
                        'deleted_at' => null,
                        'created_at' => 1688365852,
                        'source_id' => null,
                        'source_type' => 'payment_pages',
                    ],
                ],
                'one_cc_consent_banner_views' => 0,
                'one_cc_customer_consent' => 1,
            ],
        ],
    ],

    'testFindOrCreateGlobalCustomerForAnExistingCustomerOnOneClickCheckoutForTripleConsent' => [
        'request' => [
            'url' => '/checkout/global_customers',
            'method' => 'POST',
            'content' => [
                'contact' => '+919878543210',
                'email' => 'testexistingglobalcustomer@razorpay.com',
                'address_consent' => [
                    'device_id' => 'qwertyuiop1234567',
                ],
                'is_one_cc' => 1,
            ],
        ],
        'response' => [
            'content' => [
                'customer' => [
                    'id' => 'zMRVsEqPxuwiGl',
                    'email' => 'testexistingglobalcustomer@razorpay.com',
                    'contact' => '+919878543210',
                ],
                'tokens' => [
                    'entity' => 'collection',
                    'count' => 1,
                    'items' => [
                        [
                            'id' => 'token_M9EQ5OztDvu5oh',
                            'entity' => 'token',
                            'token' => '1000lcardtoken',
                            'bank' => 'ICIC',
                            'wallet' => 'paytm',
                            'method' => 'card',
                            'card' => [
                                'entity' => 'card',
                                'name' => '',
                                'last4' => '1111',
                                'network' => 'Visa',
                                'type' => 'credit',
                                'issuer' => 'HDFC',
                                'international' => false,
                                'emi' => true,
                                'sub_type' => null,
                                'token_iin' => null,
                                'expiry_month' => '01',
                                'expiry_year' => '2099',
                                'flows' => [
                                    'recurring' => true,
                                ],
                                'cobranding_partner' => null,
                            ],
                            'recurring' => false,
                            'recurring_details' => [
                                'status' => null,
                                'failure_reason' => null,
                            ],
                            'auth_type' => null,
                            'mrn' => null,
                            'used_at' => 1688365852,
                            'created_at' => 1688365852,
                            'expired_at' => 1706725799,
                            'consent_taken' => true,
                            'status' => 'active',
                            'notes' => [],
                            'error_description' => null,
                            'source' => 'business',
                            'dcc_enabled' => false,
                            'max_amount' => null,
                            'error_code' => null,
                            'compliant_with_tokenisation_guidelines' => true,
                        ],
                    ],
                ],
                'one_cc_addresses' => [
                    [
                        'id' => 'M9ICOyJ139iODr',
                        'entity_id' => 'zMRVsEqPxuwiGl',
                        'entity_type' => 'customer',
                        'line1' => 'billing address line 1',
                        'line2' => 'some line two',
                        'city' => 'Bengaluru',
                        'zipcode' => '560030',
                        'state' => 'Karnataka',
                        'country' => 'in',
                        'type' => 'billing_address',
                        'primary' => true,
                        'contact' => null,
                        'name' => null,
                        'tag' => null,
                        'landmark' => null,
                        'deleted_at' => null,
                        'created_at' => 1688365852,
                        'source_id' => null,
                        'source_type' => 'shopify',
                    ],
                    [
                        'id' => 'M9ICOzBhiakey8',
                        'entity_id' => 'zMRVsEqPxuwiGl',
                        'entity_type' => 'customer',
                        'line1' => 'shipping address line 1',
                        'line2' => 'some line two',
                        'city' => 'Bengaluru',
                        'zipcode' => '560029',
                        'state' => 'Karnataka',
                        'country' => 'in',
                        'type' => 'shipping_address',
                        'primary' => true,
                        'contact' => null,
                        'name' => null,
                        'tag' => null,
                        'landmark' => null,
                        'deleted_at' => null,
                        'created_at' => 1688365852,
                        'source_id' => null,
                        'source_type' => 'payment_pages',
                    ],
                ],
                'one_cc_consent_banner_views' => 0,
                'one_cc_customer_consent' => 1,
                'one_cc_email_customer_consent' => 1,
                'one_cc_whatsapp_customer_consent' => 0,
            ],
        ],
    ],
];
