export const DASHBOARD_TEAMS = {
  AFFORDABILITY: 'Affordability',
  APPS: 'Apps',
  AVAILABILITY_AND_DOWNTIME: 'Availability And Downtime',
  BANKING: 'Banking',
  BILLME: 'BillMe',
  CAPITAL: 'Capital',
  CARE: 'Care',
  CHECKOUT: 'Checkout',
  COMMON: 'Common',
  CROSS_BORDER: 'Cross Border',
  DATAHUB: 'DATAHUB',
  DEV_EXP: 'Developer Experience',
  GROWTH: 'Growth',
  MAGIC_CHECKOUT: 'Magic Checkout',
  MAGIC_KONNECT: 'Konnect',
  MERCHANT_REPORTING: 'Merchant Reporting',
  OMNI_CHANNEL: 'OMNI_CHANNEL',
  PARTNERSHIP: 'Partnership',
  PG_DASHBOARD: 'PG Dashboard',
  PLATFORM: 'Platform',
  PLATFORM_GROWTH: 'Platform Growth',
  RAY: 'Ray',
  RAZORPAY_WALLET: 'Razorpay Wallet',
  RAZORPAY_X: 'RazorpayX',
  RECON_SAAS: 'recon-saas',
  RISK: 'Risk',
  RIZE: 'Rize',
  ROUTING: 'Routing',
  TERMINAL: 'Terminal',
  XPAYROLL: 'XPayroll',
} as const;

export type DASHBOARD_TEAMS = (typeof DASHBOARD_TEAMS)[keyof typeof DASHBOARD_TEAMS];
