name: Identify Affected Projects with NX
outputs:
  affected:
    description: "Affected Projects with NX"
    value: ${{ steps.action_output.outputs.affected }}
runs:
  using: composite
  steps:
    - name: Fetch base branch
      shell: bash
      run: |
        git fetch origin master

    - name: Extract current branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Log info for debugging
      shell: bash
      run: |
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "branch: ${{ steps.extract_branch.outputs.branch }}"
        echo "Git ref: ${{ github.ref }}"
        echo "Contains master: ${{ contains(github.ref, 'master') }}"

    - name: Identify Affected Projects for Master
      if: contains(github.ref, 'master')
      id: affected-master
      shell: bash
      run: |
        echo "AFFECTED=$(npx nx show projects --json | jq -r 'join(",")')" >> $GITHUB_ENV

    - name: Identify Affected Projects for PRs
      if: "!contains(github.ref, 'master')"
      id: affected
      shell: bash
      run: |
        echo "AFFECTED=$(npx nx show projects --affected --json --base=origin/master --head=origin/${{ steps.extract_branch.outputs.branch }} | jq -r 'join(",")')" >> $GITHUB_ENV

    - name: Echo Affected Projects
      shell: bash
      run: echo "$AFFECTED"

    - name: Add Affected Projects In Output For Downstream Jobs
      id: action_output
      shell: bash
      run: echo "affected=$AFFECTED" >> $GITHUB_OUTPUT

    # - name: Remove .git
    #   shell: bash
    #   run: rm -rf .git
