<?php

use EE\Error\ErrorCode;
use EE\Error\PublicErrorCode;
use EE\Error\PublicErrorDescription;

return [
    'testPayment' => [
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'method' => 'netbanking',
        'status' => 'captured',
        'amount_authorized' => 50000,
        'amount_refunded' => 0,
        'refund_status' => null,
        'currency' => 'INR',
        'description' => 'random description',
        'bank' => 'SBIN',
        'error_code' => null,
        'error_description' => null,
        'email' => 'a@b.com',
        'contact' => '9918899029',
        'notes' => [
            'merchant_order_id' => 'random order id',
        ],
        'gateway' => 'sbiepay',
        'terminal_id' => '10000SbiEpayTl',
        'signed' => false,
        'verified' => null,
        'entity' => 'payment',
    ],

    'testPaymentSbiepayEntity' => [
        'action' => 'authorize',
        'method' => 'netbanking',
        'received' => true,
        'MerchantId'=> '1000109',
        'OperatingMode'=> 'DOM',
        'MerchantCountry'=> 'IN',
        'MerchantCurrency'=> 'INR',
        'PostingAmount'=> '5.00',
        'OtherDetails'=> 'NA',
        'AggregatorId'=> 'SBIEPAY',
//        'MerchantOrderNo'=> null,
        'MerchantCustomerID'=> 'a@b.com',
        'Paymode'=> 'NB',
        'Accesmedium'=> 'ONLINE',
        'TransactionSource'=> 'ONLINE',
//        'SBIePayReferenceID'=> null,
        'Status'=> 'SUCCESS',
//        'Reason'=> null,
//        'BankCode'=> null,
//        'BankReferenceNumber'=> null,
//        'TransactionDate'=> null,
//        'CIN'=> null,
//        'refund_id'=> null,
    ],

    'testPaymentRefund' => [
//        'id'=> '76',
//        'payment_id'=> '3PgPULSRMSgExV',
        'action'=> 'refund',
        'received' => true,
//        'MerchantID'=> 'random',
//        'CustomerID'=> '3PgPULSRMSgExV',
        'TxnAmount'=> '5.00',
        'BankID'=> null,
        'CurrencyType'=> 'INR',
        'ItemCode'=> null,
        'TypeField1'=> null,
        'TypeField2'=> null,
        'AdditionalInfo1'=> null,
//        'TxnReferenceNo'=> 'trbqkfizxs',
        'BankReferenceNo'=> null,
        'BankMerchantID'=> null,
        'SecurityType'=> null,
//        'TxnDate'=> '20-06-2015 00:00:00',
        'AuthStatus'=> null,
        'SettlementType'=> null,
        'ErrorStatus'=> null,
        'ErrorDescription'=> null,
        'RequestType'=> '0410',
        'RefAmount'=> '500.00',
//        'RefDateTime'=> '201506200040838',
        'RefStatus'=> '0799',
//        'RefundId'=> 'hlbdtgwnofsxmcj',
        'ErrorCode'=> 'NA',
        'ErrorReason'=> 'NA',
        'ProcessStatus'=> 'Y',
        // 'refund_id'=> '3PgPUT2YOO6htv',
        // 'created_at'=> 1434753518,
        // 'updated_at'=> 1434753518,
        'entity'=> 'billdesk',
    ],

    'testGetPaymentMethodsRoute' => [
        'request' => [
            'url' => '/methods',
            'method' => 'get',
        ],
        'response' => [
            'content' => [
                'entity' => 'methods',
                'card' => true,
                'netbanking' => [
                    'UTIB' => 'Axis Bank',
//                    'BARB' => 'Bank of Baroda',
                    'YESB' => 'Yes Bank',
                ],
                'wallet' => [
                    'paytm' => false,
                ],
            ],
        ],
    ],
];