export const NON_3DS_CARDS_ACTIVATION_FETCH = 'NON_3DS_CARDS_ACTIVATION_FETCH';
export const NON_3DS_CARDS_ACTIVATION_ENABLE = 'NON_3DS_CARDS_ACTIVATION_ENABLE';
export const NON_3DS_CARDS_ACTIVATION_DISABLE = 'NON_3DS_CARDS_ACTIVATION_DISABLE';
export const NON_3DS_CARDS_ACTIVATION_REMOVE_ERROR = 'NON_3DS_CARDS_ACTIVATION_REMOVE_ERROR';

export const NON_3DS_CARDS_ACTIVATION_STATUS = {
  ENABLED: 'Enabled',
  DISABLED: 'Disabled',
  REQUESTED: 'Requested',
};

export const NON_3DS_CARDS_ACTIVATION_STATUS_MAPPING = {
  open: NON_3DS_CARDS_ACTIVATION_STATUS.REQUESTED,
  approved: NON_3DS_CARDS_ACTIVATION_STATUS.ENABLED,
  closed: NON_3DS_CARDS_ACTIVATION_STATUS.DISABLED,
  failed: NON_3DS_CARDS_ACTIVATION_STATUS.DISABLED,
  rejected: NON_3DS_CARDS_ACTIVATION_STATUS.DISABLED,
  executed: NON_3DS_CARDS_ACTIVATION_STATUS.ENABLED,
};

export const NON_3DS_CARD_WORKFLOW_STATUS = {
  OPEN: 'open',
  APPROVED: 'approved',
  CLOSED: 'closed',
  FAILED: 'failed',
  REJECTED: 'rejected',
  EXECUTED: 'executed',
};

export const EVENTS = {
  ENABLE_NON_3DS_MODAL: 'NON 3DS ENABLE MODAL',
  ENABLE_NON_3DS_CONSENT: 'NON 3DS ENABLE CONSENT',
  LEARN_MORE_MODAL: 'NON 3DS LEARN MORE MODAL',
  NON_3DS_ENABLE: 'NON 3DS ENABLE',
  NON_3DS_DISABLE: 'NON 3DS DISABLE',
  NON_3DS: 'NON 3DS',
};
