<?php

namespace RZP\Tests\Unit\Request\Helpers;

/**
 * For various request cases, lists expected request context vars set
 * by the application.
 */
return [
    'publicRouteWithKeyInHeaders' => [
        'expected' => [
            'route'            => 'invoice_get_status',
            'key'              => 'rzp_test_TheTestAuthKey',
            'secret'           => null,
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'public',
            'keyWithoutPrefix' => 'TheTestAuthKey',
            'keyId'            => 'TheTestAuthKey',
            'mid'              => '10000000000000',
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'publicRouteWithKeyInQuery' => [
        'expected' => [
            'route'            => 'invoice_get_status',
            'key'              => 'rzp_test_TheTestAuthKey',
            'secret'           => null,
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'public',
            'keyWithoutPrefix' => 'TheTestAuthKey',
            'keyId'            => 'TheTestAuthKey',
            'mid'              => '10000000000000',
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'publicRouteWithKeyInInput' => [
        'expected' => [
            'route'            => 'payment_create',
            'key'              => 'rzp_test_TheTestAuthKey',
            'secret'           => null,
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'public',
            'keyWithoutPrefix' => 'TheTestAuthKey',
            'keyId'            => 'TheTestAuthKey',
            'mid'              => '10000000000000',
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'publicCallbackRoute' => [
        'expected' => [
            'route'            => 'payment_callback_with_key_get',
            'key'              => 'rzp_test_TheTestAuthKey',
            'secret'           => null,
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'public',
            'keyWithoutPrefix' => 'TheTestAuthKey',
            'keyId'            => 'TheTestAuthKey',
            'mid'              => '10000000000000',
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'publicRouteWithOAuthPublicToken' => [
        'expected' => [
            'route'            => 'invoice_get_status',
            'key'              => 'rzp_test_oauth_100OAuthPublic',
            'secret'           => null,
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'public',
            'keyWithoutPrefix' => 'oauth_100OAuthPublic',
            'keyId'            => null,
            'mid'              => null,
            'oauthClientId'    => null,
            'oauthPublicToken' => '100OAuthPublic',
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'publicCallbackRouteWithOAuthPublicToken' => [
        'expected' => [
            'route'            => 'payment_callback_with_key_get',
            'key'              => 'rzp_test_oauth_100OAuthPublic',
            'secret'           => null,
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'public',
            'keyWithoutPrefix' => 'oauth_100OAuthPublic',
            'keyId'            => null,
            'mid'              => null,
            'oauthClientId'    => null,
            'oauthPublicToken' => '100OAuthPublic',
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'privateRoute' => [
        'expected' => [
            'route'            => 'invoice_fetch_multiple',
            'key'              => 'rzp_test_TheTestAuthKey',
            'secret'           => 'TheKeySecretForTests',
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'private',
            'keyWithoutPrefix' => 'TheTestAuthKey',
            'keyId'            => 'TheTestAuthKey',
            'mid'              => '10000000000000',
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'privateRouteWithLiveMode' => [
        'expected' => [
            'route'            => 'invoice_fetch_multiple',
            'key'              => 'rzp_live_TheLiveAuthKey',
            'secret'           => 'TheKeySecretForTestsLive',
            'bearerToken'      => null,
            'mode'             => 'live',
            'auth'             => 'private',
            'keyWithoutPrefix' => 'TheLiveAuthKey',
            'keyId'            => 'TheLiveAuthKey',
            'mid'              => '10000000000000',
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'privateRouteWithOAuthBearerToken' => [
        'expected' => [
            'route'            => 'invoice_fetch_multiple',
            'key'              => null,
            'secret'           => null,
            'bearerToken'      => null,
            'mode'             => null,
            'auth'             => 'private',
            'keyWithoutPrefix' => null,
            'keyId'            => null,
            'mid'              => '10000000000000',
            'oauthClientId'    => '100OAuthClient',
            'oauthPublicToken' => null,
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'privateRouteWithProxyAuth' => [
        'expected' => [
            'route'            => 'invoice_create',
            'key'              => 'rzp_test_10000000000000',
            'secret'           => 'RANDOM_DASH_PASSWORD_MERCHANT',
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'private',
            'keyWithoutPrefix' => '10000000000000',
            'keyId'            => null,
            'mid'              => '10000000000000',
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => 'merchant_dashboard',
            'adminEmail'       => null,
            'proxy'            => true,
        ],
    ],

    'privateRouteWithInvalidKey' => [
        'expected' => [
            'route'            => 'invoice_fetch_multiple',
            'key'              => null,
            'secret'           => null,
            'bearerToken'      => null,
            'mode'             => null,
            'auth'             => 'private',
            'keyWithoutPrefix' => null,
            'keyId'            => null,
            'mid'              => null,
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'privateRouteWithInvalidSecret' => [
        'expected' => [
            'route'            => 'invoice_fetch_multiple',
            'key'              => 'rzp_test_TheTestAuthKey',
            'secret'           => 'invalidsecret',
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'private',
            'keyWithoutPrefix' => 'TheTestAuthKey',
            'keyId'            => 'TheTestAuthKey',
            'mid'              => '10000000000000',
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'proxyRoute' => [
        'expected' => [
            'route'            => 'batch_create',
            'key'              => 'rzp_test_10000000000000',
            'secret'           => 'RANDOM_DASH_PASSWORD_MERCHANT',
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'private',
            'keyWithoutPrefix' => '10000000000000',
            'keyId'            => null,
            'mid'              => '10000000000000',
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => 'merchant_dashboard',
            'adminEmail'       => null,
            'proxy'            => true,
        ],
    ],

    'privilegeRouteWithInternalAppAuth' => [
        'expected' => [
            'route'            => 'invoice_expire_bulk',
            'key'              => 'rzp_test',
            'secret'           => 'RANDOM_DASH_PASSWORD_MERCHANT',
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'privilege',
            'keyWithoutPrefix' => null,
            'keyId'            => null,
            'mid'              => null,
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => 'merchant_dashboard',
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    'privilegeRouteWithAdminAuth' => [
        'expected' => [
            'route'            => 'dummy_route',
            'key'              => 'rzp_test',
            'secret'           => 'RANDOM_DASH_PASSWORD_ADMIN',
            'bearerToken'      => null,
            'mode'             => 'test',
            'auth'             => 'privilege',
            'keyWithoutPrefix' => null,
            'keyId'            => null,
            'mid'              => null,
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => 'admin_dashboard',
            'adminEmail'       => 'test@test.com',
            'proxy'            => false,
        ],
    ],

    'directRoute' => [
        'expected' => [
            'route'            => 'checkout_public',
            'key'              => null,
            'secret'           => null,
            'bearerToken'      => null,
            'mode'             => null,
            'auth'             => 'direct',
            'keyWithoutPrefix' => null,
            'keyId'            => null,
            'mid'              => null,
            'oauthClientId'    => null,
            'oauthPublicToken' => null,
            'internalAppName'  => null,
            'adminEmail'       => null,
            'proxy'            => false,
        ],
    ],

    // 'deviceRoute' => [
    //     'expected' => [
    //         'route'            => 'vpa_create',
    //         'key'              => 'rzp_test_TheTestAuthKey',
    //         'secret'           => 'authentication_token',
    //         'bearerToken'      => null,
    //         'mode'             => 'test',
    //         'auth'             => 'device',
    //         'keyWithoutPrefix' => 'TheTestAuthKey',
    //         'keyId'            => 'TheTestAuthKey',
    //         'mid'              => '10000000000000',
    //         'oauthClientId'    => null,
    //         'oauthPublicToken' => null,
    //         'internalAppName'  => null,
    //         'adminEmail'       => null,
    //         'proxy'            => false,
    //     ],
    // ],
];
