name: Waiting Build for Dashoard

inputs:
  commit_id:
    required: true
  workflow_name:
    required: true
  github_token:
    required: true

runs:
  using: composite
  steps:
    - name: Use Node v18.12.1
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1

    # Not required for now, will use in future
    # - name: Wait for fetching Affected Projects
    #   uses: lewagon/wait-on-check-action@v1.3.1
    #   with:
    #     ref: ${{ inputs.commit_id }}
    #     running-workflow-name: ${{ inputs.workflow_name }}
    #     check-name: "Identify Affected Projects"
    #     repo-token: ${{ inputs.github_token }}
    #     allowed-conclusions: success
    #     wait-interval: 45

    - name: Wait for dashboard's docker image to be built
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ inputs.commit_id }}
        running-workflow-name: ${{ inputs.workflow_name }}
        # TODO: Keeping this for now, fix in separate PR
        check-name: "Build Dashboard"
        repo-token: ${{ inputs.github_token }}
        allowed-conclusions: success,skipped
        wait-interval: 45