const getStorageStatePath = (BASE_PATH) => ({
  // NOTE: Please use ACTIVATED_RZP_MERCHANT for all the new tests unless you need to test a specific scenario which requires a different user.
  ACTIVATED_RZP_MERCHANT: `${BASE_PATH}/activated-rzp-merchant.json`,
  ACTIVATED_NOT_IE_STATE: `${BASE_PATH}/activated-not-ie-login.json`,
  CAPITAL_RESELLER_PARTNER_TEST_LOGIN_STATE: `${BASE_PATH}/capital-reseller-partner-desktop-test-mode-login.json`,
  RESELLER_PARTNER_TEST_LOGIN_STATE: `${BASE_PATH}/reseller-partner-desktop-test-mode-login.json`,
  AGGREGATOR_PARTNER_TEST_LOGIN_STATE: `${BASE_PATH}/aggregator-partner-desktop-test-mode-login.json`,
  PLATFORM_PARTNER_TEST_LOGIN_STATE: `${BASE_PATH}/platform-partner-desktop-test-mode-login.json`,
  POS_LOGIN_STATE: `${BASE_PATH}/pos-login.json`,
  POS_ORDER_DETAILS_LOGIN_STATE: `${BASE_PATH}/pos-login-order-details.json`,
  // POS_KYC_STATUS_NC: `${BASE_PATH}/pos-kyc-status-nc.json`,
  OPTIMIZER_V1_LOGIN_STATE: `${BASE_PATH}/desktop-optimizer-v1-login.json`,
  POS_SALES_AGENT: `${BASE_PATH}/pos-sales-agent.json`,
});

const routes = {
  SIGN_IN_PATH: '/?screen=sign_in&isTestEnv=true',
  DASHBOARD: '/app/dashboard',
  ACCOUNT_SETTINGS: '/app/account-settings',
  STREAKS_REWARDS: '/app/streak-reward',
  BALANCES: '/app/payments-and-refunds-settings/balances',
  CREDITS: '/app/payments-and-refunds-settings/credits',
  REMINDERS: '/app/payments-and-refunds-settings/reminders',
  CAPTURE_AND_REFUND_SETTINGS: '/app/payments-and-refunds-settings/capture-refund-settings',
  TRANSACTION_LIMITS: '/app/payments-and-refunds-settings/transaction-limits',
  MANAGE_TEAM: '/app/business-settings/team',
  SETTLEMENTS: '/app/settlements',
  GST_DETAILS: '/app/business-settings/gst',
  SMS_NOTIFICATIONS: '/app/notification-settings/sms',
  API_KEYS: '/app/website-app-settings/api-keys',
  WEBHOOKS: '/app/website-app-settings/webhooks',
  CUSTOMERS: '/app/customers',
  CUSTOMER_SUPPORT_DETAILS: '/app/business-settings/customer-support',
  BUSINESS_DETAILS: '/app/business-settings/business',
  PAYMENT_LINKS: '/app/paymentlinks',
  ROUTE_PAYMENTS: '/app/route/payments',
  TRANSACTIONS_PAYMENTS: '/app/payments',
  ITEMS: '/app/items',
  INVOICES: '/app/invoices',
  PAYMENTS: 'app/payments',
  DISPUTES: 'app/disputes',
  FAILED_PAYMENTS: 'app/failed-payments',
  ORDERS: 'app/orders',
  REFUNDS: 'app/refunds',
  BATCH_REFUNDS: 'app/refunds/batchuploads',
  BATCH_REFUNDS_UPLOAD: 'app/refunds/batchupload',
  SUCCESS_RATE: 'app/success-rate',
  PAYMENT_PAGES: 'app/paymentpages',
  MAGIC_CHECKOUT: 'app/magic/settings',
  FIRS: 'app/international-settings/firs',
  PARTNER_DASHBOARD: '/app/partners',
  PARTNER_PLAYBOOK: '/app/partners/playbook',
  PARTNER_PRICING_PLANS: '/app/partner-pricing-plans',
  CLIENT_ACCOUNTS: '/app/partners/submerchants',
  CLIENT_ACCOUNTS_CAPITAL: '/app/partners/submerchants/capital',
  CLIENT_ACCOUNTS_POS: '/app/partners/submerchants/pos',
  OPTIMIZER: 'app/optimizer/rules',
  POS: '/app/pos',
  BATCH_PAYMENT_PAGES: '/app/paymentpages/batchpaymentpages',
  WHATSAPP_ACCOUNT_SETUP: 'app/payments-and-refunds-settings/whatsapp-account-setup',
  PAYMENT_METRICS: '/app/payment-metrics',
  INTERNATIONAL_PAYMENTS: '/app/payment-methods/international-payments',
  WALLET_REPORTS: '/app/wallet/reports',
};

module.exports = {
  getStorageStatePath,
  routes,
};
