<?php

use Carbon\Carbon;

return [
    'testZestMoneySuccessRecon' => [
        'transaction_type'              => 'FORWARD',
        'accountholdername'             => 'Abc De',
        'accountholderid'               => '131067211',
        'accountid'                     =>  '8J2OK5538Z5F',
        'refund_id'                     =>  'nan',
        'partner_order_id'              =>  'HUKokpZxHJGHG',
        'merchantid'                    =>  '28ee3c61-de08-4bc2-8df1-b76fd5fd33a6',
        'merchantname'                  =>  'Demo',
        'downpaymentmode'               =>  'CashOnDelivery',
        'basket_amount'                 =>  '500.00',
        'processingfee'                 =>  '0',
        'downpaymentamount'             =>  '0',
        'loanamount'                    =>  '1000',
        'refundamount'                  =>  '0',
        'activation_date'               =>  '2021-07-03 00:00:00',
        'numberofinstallments'          =>  '6',
        'interestrate'                  =>  '22',
        'merchantdiscountrate'          =>  '1',
        'mdr_wo_gst_amount'             =>  '7.5',
        'mdr_gst_amount'                =>  '1.35',
        'subventionrate'                =>  '0',
        'subventionamount'              =>  '0',
        'subventiongstamount'           =>  '0',
        'cashbacktype'                  =>  'SubventionInterestCashback',
        'settlementtype'                =>  'Gross',
        'cancellationcharges'           =>  '0',
        'processingfeeinfirstemi'       =>  '0',
        'skipnonzerodp'                 =>  '1',
        'settlemententity'              =>  'RAZORPAY SOFTWARE PRIVATE LIMITED',
        'Email Entity'                  =>  'RazorpayPG',
        'settlementamount'              =>  '1000',
        'transactionreferenceid'        =>  'HUKokpZxHJGHG',
        'merchantsettledon'             =>  Carbon::today()->format("Y-m-d h:m:s"),
        'merchantutr'                   =>  'N188210657124222',
        'Mambu name'                    =>  'RazorPay Decimal FIXED EMI RB',
        'Transaction id'                =>  'FIXED EMI BR',
    ],
];
