<?php

namespace RZP\Models\Payout;

use RZP\Trace\TraceCode;

class ErrorCodeMapping
{
    protected static $failureReasonMapping = [
        'YB_NS_E400'                     => 'Payout failed. Contact support for help',
        'YB_NS_E402'                     => 'Payout failed. Contact support for help',
        'YB_NS_E405'                     => 'Payout failed. Contact support for help',
        'YB_NS_E429'                     => 'Payout failed. Please reinitiate transfer after 30 min',
        'YB_NS_E406'                     => 'Issue with Beneficiary Account. Check Beneficiary Account before reinitiating transfer',
        'YB_NS_E502'                     => 'Payout failed. Please reinitiate transfer after 30 min',
        'YB_NS_E504'                     => 'Payout failed. Please reinitiate transfer after 30 min',
        'YB_NS_E1001'                    => 'Transaction amount exceeds IMPS maximum limit',
        'YB_NS_E1002'                    => 'Transfer currency is not supported. Contact support for help',
        'YB_NS_E1004'                    => 'Transfer amount is less than minimum RTGS limit',
        'YB_NS_E1005'                    => 'Payout failed. Contact support for help',
        'YB_NS_E1006'                    => 'Payout failed. Contact support for help',
        'YB_NS_E1028'                    => 'IMPS is not enabled on Beneficiary Account',
        'YB_NS_E2000'                    => 'Invalid Beneficiary details ',
        'YB_NS_E6000'                    => 'Payout failed. Contact support for help',
        'YB_NS_E6001'                    => 'Payout failed. Contact support for help',
        'YB_NS_E6002'                    => 'Payout failed. Contact support for help',
        'YB_NS_E6003'                    => 'Payout failed. Reinitiate transfer after 60 min',
        'YB_NS_E6005'                    => 'Invalid Beneficiary IFSC for GST payment',
        'YB_NS_E6006'                    => 'Beneficiary account no length is invalid for GST payment. Allowed length is 14',
        'YB_NS_E6007'                    => 'Payout failed. Contact support for help',
        'YB_NS_E6008'                    => 'Payout failed. Contact support for help',
        'YB_FLEX_E18'                    => 'Payout failed. Reinitiate transfer after 60 min',
        'YB_FLEX_E307'                   => 'Issue at partner bank. Reinitiate transfer after 30 min',
        'YB_FLEX_E404'                   => 'Payout failed. Contact support for help',
        'YB_FLEX_E449'                   => 'Invalid Beneficiary details',
        'YB_FLEX_E8036'                  => 'Payout failed. Reinitiate transfer after 60 min',
        'YB_FLEX_E8087'                  => 'Beneficiary Account number is invalid',
        'YB_FLEX_E9072'                  => 'Beneficiary bank branch could not be resolved. Retry after correcting beneficiary IFSC Code ',
        'YB_NPCI_E08'                    => 'NPCI or Beneficiary bank systems are offline. Reinitiate transfer after 30 min',
        'YB_NPCI_EM1'                    => 'Invalid Beneficiary MMID/Mobile Number',
        'YB_NPCI_EM2'                    => 'Transaction Amount exceeds IMPS Maximum Limit',
        'YB_NPCI_EM3'                    => 'Beneficiary account is blocked or frozen',
        'YB_NPCI_EM4'                    => 'Beneficiary account is not enabled for Foreign Inward Remittance',
        'YB_NPCI_EM5'                    => 'Beneficiary account is closed',
        'YB_NPCI_E307'                   => 'Failure/Rejection at beneficiary bank',
        'YB_NPCI_E308'                   => 'Failure/Rejection at beneficiary bank',
        'YB_NPCI_E449'                   => 'Rejected by beneficiary bank. Check beneficiary account details',
        'YB_ATOM_E307'                   => 'IMPS service issue at bank. Reinitiate transfer after 30 min',
        'YB_ATOM_E404'                   => 'Payout failed. Reinitiate transfer after 60 min',
        'YB_ATOM_E449'                   => 'Rejected by beneficiary bank. Check beneficiary account details',
        'YB_SFMS_E99'                    => 'Payout failed. Contact support for help',
        'YB_SFMS_E70'                    => 'Payout failed. Contact support for help',
        'YB_SFMS_E18'                    => 'Payout failed. Reinitiate transfer after 60 min',
        'YB_NS_E1029'                    => 'Payout failed. Contact support for help',
        'YB_NS_E2005'                    => 'Payout failed. Reinitiate transfer after 30 min',
        'YB_NS_E404'                     => 'Payout failed. Contact support for help',
        'YB_SFMS_E62'                    => 'Beneficiary bank could not credit beneficiary account. Check beneficiary account details',
        'YB_NPCI_E68'                    => 'Beneficiary bank is offline. Reinitiate transfer after 30 min',
        'YB_SFMS_EREJ'                   => 'Payout failed. Contact support for help',
        'YB_NS_E500'                     => 'Internal server error at bank. Reinitiate transfer after 30 min',
        'YB_NS_E403'                     => 'Payout failed. Contact support for help',
        'YB_FLEX_E11'                    => 'Payout failed. Contact support for help',
        'YB_FLEX_E2853'                  => 'Payout failed. Contact support for help',
        'YB_NPCI_E450'                   => 'Rejected by beneficiary bank. Check beneficiary account details',
        'YB_FLEX_E3403'                  => 'Payout failed. Reinitiate transfer after 30 min',
        'YB_ATOM_E11'                    => 'Payout failed. Reinitiate transfer after 30 min',
        'YB_FLEX_E8086'                  => 'Payout failed. Contact support for help',
        'YB_HTTP_STATUS_500'             => 'Bank is facing issues. Reinitiate transfer after 30 min',
        'YB_HTTP_STATUS_404'             => 'Payout failed. Contact support for help',
        'YB_NPCI_E52'                    => 'Payout failed. Contact support for help',
        'YB_NPCI_E13'                    => 'Payout failed. Contact support for help',
        'YB_FLEX_E2435'                  => 'Beneficiary account is Dormant',
        'YB_FLEX_E6833'                  => 'Payout failed. Contact support for help',
        'YB_NPCI_E91'                    => 'Payout failed. Contact support for help',
        'YB_FLEX_E8035'                  => 'Mobile number is not valid',
        'YB_NPCI_E0'                     => 'Payout failed. Contact support for help',
        'YB_NPCI_E80'                    => 'Payout failed. Contact support for help',
        'YB_NS_404'                      => 'Payout failed. Contact support for help',
        'YB_FLEX_E9074'                  => 'Narration is not valid. Contact support for help',
        'YB_NPCI_ECE'                    => 'Payout failed. Reinitiate transfer after 30 min',
        'YB_ATOM_EA19'                   => 'Payout failed. Reinitiate transfer after 30 min',
        'YB_FLEX_E8037'                  => 'Payout failed. Reinitiate transfer after 60 min',
        'YB_FLEX_E7585'                  => 'Internal Server Error at Partner Bank. Reinitiate transfer after 30 min',
        'YB_NPCI_E01'                    => 'Internal Server Error at Partner Bank. Reinitiate transfer after 30 min',
        'YB_NPCI_E96'                    => 'Internal Server Error at Partner Bank. Reinitiate transfer after 30 min',
        'YB_NPCI_E20'                    => 'Internal Server Error at Partner Bank. Reinitiate transfer after 30 min',
        'YB_NPCI_E12'                    => 'Internal Server Error at Partner Bank. Reinitiate transfer after 30 min',
        'YB_NPCI_E92'                    => 'Internal Server Error at Partner Bank. Reinitiate transfer after 30 min',
        'YB_NPCI_E22'                    => 'Internal Server Error at Partner Bank. Reinitiate transfer after 30 min',
        'YB_NS_E8000'                    => 'Payout failed. Contact support for help',
        'YB_NS_E410'                     => 'Payout failed. Contact support for help',
        'YB_NS_E9001'                    => 'Payout failed. Contact support for help',
        'YB_NS_E9002'                    => 'Failed while processing at the bank. Reinitiate transfer after 30 Minutes',
        'YB_ATOM_E4_50'                  => 'Bank rejected transaction due to incorrect format or beneficiary details.',
        'YB_FLEX_E11_017'                => 'Bank rejected transaction due to incorrect format or beneficiary details.',
        'YB_NPCI_E02'                    => 'Connectivity issue with NPCI. Reinitiate transfer after 30 min',
        'YB_SFMS_99'                     => 'Payout failed. Contact support for help',
        'YB_SFMS_E55'                    => 'Transaction is pending at beneficiary bank',
        'YB_SFMS_E59'                    => 'Beneficiary bank\'s systems are down. Please retry after some time.',
        'YB_NPCI_ENA'                    => 'Payout failed. Contact support for help.',
        'YB_NPCI_EMP'                    => 'Partner bank facing issue. Reinitiate the transaction after some time. ',
        'YB_NPCI_E30'                    => 'Payout failed. Contact support for help',
        'VALIDATION_ERROR'               => 'Payout failed. Contact support for help.',
        'FAILURE'                        => 'Payout failed. Reinitiate transfer after 30 min.',
        'INSUFFICIENT_FUND'              => 'Payout failed. Contact support for help.',
        'INVALID_REQUEST'                => 'Payout failed. Contact support for help.',
        'TXN_LIMIT_EXCEEDED'             => 'Payout failed. Contact support for help.',
        'BAD_GATEWAY'                    => 'Payout failed. Contact support for help.',
        'TECHNICAL_ERROR'                => 'Payout failed. Contact support for help.',
        'TXN_REJECTED'                   => 'Payout failed. Contact support for help.',
        'MERCHANT_VALIDATION_ERROR'      => 'Invalid beneficiary details.',
        'EXCEEDED_AMOUNT_LIMIT'          => 'Payout failed. Contact support for help.',
        'DUPLICATE_TXN_PENDING'          => 'Payout failed. Contact support for help.',
        'TXN_TIMEOUT'                    => 'Payout failed. Please reinitiate transfer after 30 min.',
        'TXN_REJECTED_BENE_BANK'         => 'Transaction not permitted to beneficiary account.',
        'BANK_CBS_OFFLINE_FAILURE'       => 'Partner Bank is experiencing downtime. Reinitiate transfer after 30 min.',
        'DORMANT_ACCOUNT'                => 'Beneficiary account is dormant.',
        'CLOSED_ACCOUNT'                 => 'Beneficiary account is closed.',
        'IMPS_NOT_ENABLED'               => 'IMPS is not enabled on Beneficiary Account',
        'FUNDS_ON_HOLD'                  => 'Payout failed. Reinitiate transfer after 60 min.',
        'BENEFICIARY_MERCHANT'           => 'Payout failed. Contact support for help.',
        'TXN_ON_HOLD'                    => 'Payout failed. Reinitiate transfer after 60 min.',
        'GATEWAY_DOWNTIME'               => 'Payout failed. Contact support for help.',
        'BENE_BANK_OFFLINE'              => 'Beneficiary bank is offline. Reinitiate transfer after 30 min.',
        'AUTHORIZATION_ISSUE_PENDING'    => 'Payout failed. Contact support for help.',
        'BANK_CBS_ISSUE_PENDING'         => 'Partner Bank is experiencing downtime. Reinitiate transfer after 30 min.',
        'NPCI_RESPONSE_ISSUE'            => 'Payout failed. Contact support for help.',
        'BENE_BANK_RESPONSE_AWAITED'     => 'Beneficiary bank\'s systems are down. Please retry after some time.',
        'AUTHORIZATION_FAILED'           => 'Payout failed. Contact support for help.',
        'FROZEN_ACCOUNT'                 => 'Beneficiary account is frozen.',
        'INVALID_AMOUNT'                 => 'Payout failed. Contact support for help.',
        'INVALID_VPA'                    => 'Invalid beneficiary VPA/UPI address',
        'COLLECT_REQUEST_REJECTED'       => 'Payout failed. Contact support for help.',
        'FRAUD_DECLINE'                  => 'Payout failed. Contact support for help.',
        'CARD_VALIDATION_FAILED'         => 'Payout failed. Contact support for help.',
        'TXN_NOT_ALLOWED'                => 'Payout failed. Contact support for help.',
        'INVALID_BENEFICIARY_DETAILS'    => 'Invalid beneficiary details.',
        'INVALID_ACCOUNT_NUMBER'         => 'Invalid beneficiary account number',
        'TXN_TIMEOUT_PENDING'            => 'Payout failed. Contact support for help.',
        'TECHNICAL_ERROR_PENDING'        => 'Payout failed. Contact support for help.',
        'VALIDATION_ERROR_PENDING'       => 'Payout failed. Contact support for help.',
        'AUTHENTICATION_FAILED'          => 'Payout failed. Contact support for help.',
        'RETURNED'                       => 'Payout failed. Contact support for help.',
        'REQUEST_NOT_FOUND'              => 'Payout failed. Contact support for help.',
        'PBANK_CBS_REJECTED'             => 'Issue at partner bank. Reinitiate transfer after 30 min',
    ];

    public static function getErrorMessageFromBankResponseCode(Entity $payout, string $bankStatusCode = null)
    {
        $errorMessage = self::$failureReasonMapping[$bankStatusCode] ?? null;

        if (is_null($errorMessage) === true)
        {
            app('trace')->error(TraceCode::PAYOUT_PUBLIC_ERROR_CODE_UNKNOWN_BANK_STATUS_CODE,
                [
                    'bank_status_code'  => $bankStatusCode,
                    'payout_id'         => $payout->getId(),
                ]);

            $errorMessage = 'Payout failed. Contact support for help';
        }

        return $errorMessage;
    }
}
