name: Push Browser Artifacts - S3 (Canary)
inputs:
  targetEnvironment:
    required: true
  targetProject:
    required: true
  prodCacheBucket:
    required: true
  buildDir:
    required: true
  awsRegion:
    required: true
  prodAwsAccessKeyId:
    required: true
  prodAwsSecretAccessKey:
    required: true
runs:
  using: composite
  steps:
    - name: Configure AWS Credentials For Actions Cache - (canary)
      uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.targetEnvironment == 'canary' }}
      with:
        aws-access-key-id: ${{ inputs.prodAwsAccessKeyId }}
        aws-secret-access-key: ${{ inputs.prodAwsSecretAccessKey }}
        aws-region: ${{ inputs.awsRegion }}

    - name: Push Browser Artifacts to Action Cache (S3) for ${{ inputs.targetProject }} - (canary)
      if: ${{ inputs.targetEnvironment == 'canary' }}
      shell: bash
      run: |
        node .github/scripts/s3-sync.js ${{ inputs.buildDir }} ${{ inputs.targetProject }} ${{ inputs.prodCacheBucket }}
      env:
        ENVIRONMENT: canary
