#!/bin/bash

EXIT_CODE=0

TMP_STAGING=".staging"

rm -rf $TMP_STAGING

printf "Running Linter\n"

while read FILE; do
if [[ -f $FILE ]]; then
    mkdir -p "$TMP_STAGING/$(dirname $FILE)"
    git show :$FILE > "$TMP_STAGING/$FILE"
    php -l "$TMP_STAGING/$FILE" 1> /dev/null
    if [ $? -ne 0 ]; then
        EXIT_CODE=1
    fi
fi
done < <(git diff --cached --name-only | grep -i ".php$")

rm -rf $TMP_STAGING

if [[ $EXIT_CODE -eq 1 ]];then
  printf "\e[1;31m\tAborting commit due to syntax errors in staged files.\e[0m\n" >&2;
  exit 1
fi

printf "\e[1;92m\tNo syntax error found.\e[0m\n" >&2;

# printf "Validating Coding Standards\n"
# bash ./scripts/bin/phpcs