<?php

use RZP\Error\ErrorCode;
use RZP\Error\PublicErrorCode;
use RZP\Error\PublicErrorDescription;

return [
    'testPayment' => [
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'method' => 'wallet',
        'wallet' => 'payzapp',
        'status' => 'captured',
        'amount_authorized' => 50000,
        'amount_refunded' => 0,
        'refund_status' => null,
        'currency' => 'INR',
        'description' => 'random description',
        'error_code' => null,
        'error_description' => null,
        'email' => 'a@b.com',
        'contact' => '+919918899029',
        'notes' => [
            'merchant_order_id' => 'random order id',
        ],
        'gateway' => 'wallet_payzapp',
        'terminal_id' => '100PayzappTmnl',
        'signed' => false,
        'verified' => null,
        'entity' => 'payment',
    ],

    'testTransactionAfterAuthorize' => [
        'type' => 'payment',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 1438,
        'pricing_rule_id' => null,
        'debit' => 0,
        'credit' => 48562,
        'currency' => 'INR',
        'balance' => 0,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'escrow_balance' => 1048562,
        'channel' => 'kotak',
        'settled' => false,
        'settled_at' => null,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testTransactionAfterCapture' => [
        'type' => 'payment',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 1438,
        'debit' => 0,
        'credit' => 48562,
        'currency' => 'INR',
        'balance' => 1048562,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'escrow_balance' => 1048562,
        'channel' => 'kotak',
        'settled' => false,
//        'settled_at' => 1437589800,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testTransactionAfterRefund' => [
        'type' => 'refund',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 0,
        'debit' => 50000,
        'credit' => 0,
        'currency' => 'INR',
        'balance' => 998562,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'escrow_balance' => 998562,
        'channel' => 'kotak',
        'settled' => false,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testPartialRefund' => [
        // 'id' => 'pay_4skOcfZVNmBfcs',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'method' => 'wallet',
        'status' => 'refunded',
        'amount_authorized' => 50000,
        'amount_refunded' => 50000,
        'refund_status' => 'full',
        'currency' => 'INR',
        'description' => 'random description',
        'card_id' => NULL,
        'bank' => NULL,
        'wallet' => 'payzapp',
        'emi_plan_id' => NULL,
        'error_code' => NULL,
        'internal_error_code' => NULL,
        'error_description' => NULL,
        'email' => 'a@b.com',
        'contact' => '+919918899029',
        'notes' =>
        array (
          'merchant_order_id' => 'random order id',
        ),
        // 'transaction_id' => '4skOd1CTA8C3hl',
        // 'authorized_at' => 1454636505,
        // 'captured_at' => 1454636505,
        'gateway' => 'wallet_payzapp',
        // 'terminal_id' => '100PayzappTmnl',
        // 'signed' => false,
        // 'verified' => NULL,
        // 'callback_url' => NULL,
        'fee' => 1438,
        'service_tax' => 188,
        // 'created_at' => 1454636504,
        // 'updated_at' => 1454636505,
        // 'public_id' => 'pay_4skOcfZVNmBfcs',
        'captured' => true,
        'entity' => 'payment',
        'admin' => true,
    ],
    'testPaymentPayzappEntity' => [
//        'id' => '1',
//        'payment_id' => '4W2hONlUrw0Pka',
        'action' => 'authorize',
        'amount' => 50000,
        'wallet' => 'payzapp',
        'received' => true,
        'email' => 'a@b.com',
        'contact' => '+919918899029',
//        'gateway_merchant_id' => '29837498237498723433',
//        'gateway_payment_id' => 'hr8mncd5bqygokfs14w29',
//        'gateway_payment_id_2' => '65657627',
        'gateway_refund_id' => null,
        'response_code' => '000',
        'response_description' => 'SUCCESS',
        'status_code' => null,
        'error_message' => null,
//        'reference1' => '201512091604066125oW33aC8:2jG2cS5gT9',
        'reference2' => '0',
        'date' => null,
        'refund_id' => null,
        'entity' => 'wallet',
        'admin' => true,
    ],
    'testRefundPayment' => [
          // 'id' => 'pay_4skOcfZVNmBfcs',
          'merchant_id' => '10000000000000',
          'amount' => 50000,
          'method' => 'wallet',
          'status' => 'refunded',
          'amount_authorized' => 50000,
          'amount_refunded' => 50000,
          'refund_status' => 'full',
          'currency' => 'INR',
          'description' => 'random description',
          'card_id' => NULL,
          'bank' => NULL,
          'wallet' => 'payzapp',
          'emi_plan_id' => NULL,
          'error_code' => NULL,
          'internal_error_code' => NULL,
          'error_description' => NULL,
          'email' => 'a@b.com',
          'contact' => '+919918899029',
          'notes' =>
          array (
            'merchant_order_id' => 'random order id',
          ),
          // 'transaction_id' => '4skOd1CTA8C3hl',
          // 'authorized_at' => 1454636505,
          // 'captured_at' => 1454636505,
          'gateway' => 'wallet_payzapp',
          // 'terminal_id' => '100PayzappTmnl',
          // 'signed' => false,
          // 'verified' => NULL,
          // 'callback_url' => NULL,
          'fee' => 1438,
          'service_tax' => 188,
          // 'created_at' => 1454636504,
          // 'updated_at' => 1454636505,
          // 'public_id' => 'pay_4skOcfZVNmBfcs',
          'captured' => true,
          'entity' => 'payment',
          'admin' => true,
    ],
    'testPaymentPayzappEntityAfterRefund' => [
          // 'id'                      => '55',
          // 'payment_id'              => '4skOcfZVNmBfcs',
          'action'                  => 'refund',
          'amount'                  => 50000,
          'wallet'                  => 'payzapp',
          'received'                => true,
          'email'                   => 'a@b.com',
          'contact'                 => '+919918899029',
          'gateway_merchant_id'     => '3456',
          'gateway_payment_id'      => NULL,
          // 'gateway_payment_id_2'    => NULL,
          // 'gateway_refund_id'       => NULL,
          'response_code'           => '0',
          'response_description'    => 'No Error',
          'status_code'             => '50020',
          'error_message'           => 'No Error',
          'reference1'              => NULL,
          'reference2'              => NULL,
          'date'                    => NULL,
          // 'refund_id'               => '4skOdgniaTvw0S',
          // 'created_at'              => 1454636505,
          // 'updated_at'              => 1454636505,
          'entity'                  => 'wallet',
          'admin'                   => true,
    ],
];
