<?php

use Rzp\Exception;
use RZP\Error\ErrorCode;
use RZP\Error\PublicErrorCode;
use RZP\Error\PublicErrorDescription;

return [
    'testPayment' => [
        'merchant_id'       => '10000000000000',
        'amount'            => 50000,
        'method'            => 'wallet',
        'wallet'            => 'payzapp',
        'status'            => 'captured',
        'two_factor_auth'   => 'passed',
        'amount_authorized' => 50000,
        'amount_refunded'   => 0,
        'refund_status'     => null,
        'currency'          => 'INR',
        'description'       => 'random description',
        'error_code'        => null,
        'error_description' => null,
        'email'             => 'a@b.com',
        'contact'           => '+919918899029',
        'notes'             => [
            'merchant_order_id' => 'random order id',
        ],
        'gateway'           => 'wallet_payzapp',
        'terminal_id'       => '100PayzappTmnl',
        'signed'            => false,
        'verified'          => null,
        'entity'            => 'payment',
    ],

     'testInvalidCallbackResponse' => [
        'response'  => [
            'content'     => [
                'error' => [
                    'code'          =>  PublicErrorCode::GATEWAY_ERROR,
                    'description'   => "Your payment didn't go through due to a temporary issue. Any debited amount will be refunded in 4-5 business days.",
                ],
            ],
            'status_code' => 502,
        ],
        'exception' => [
            'class'                 => Exception\GatewayErrorException::class,
            'internal_error_code'   => ErrorCode::GATEWAY_ERROR_CALLBACK_EMPTY_INPUT,
        ],
    ],

    'testTransactionAfterAuthorize' => [
        'type'            => 'payment',
        'merchant_id'     => '10000000000000',
        'amount'          => 50000,
        'fee'             => 0,
        'pricing_rule_id' => null,
        'debit'           => 0,
        'credit'          => 0,
        'currency'        => 'INR',
        'balance'         => 0,
        'gateway_fee'     => 0,
        'api_fee'         => 0,
        'channel'         => 'axis',
        'settled'         => false,
        'settled_at'      => null,
        'settlement_id'   => null,
        'reconciled_at'   => null,
        'entity'          => 'transaction',
        'admin'           => true,
    ],

    'testTransactionAfterCapture' => [
        'type'          => 'payment',
        'merchant_id'   => '10000000000000',
        'amount'        => 50000,
        'fee'           => 1476,
        'debit'         => 0,
        'credit'        => 48524,
        'currency'      => 'INR',
        'balance'       => 1048524,
        'gateway_fee'   => 0,
        'api_fee'       => 0,
        'channel'       => 'axis',
        'settled'       => false,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity'        => 'transaction',
        'admin'         => true,
    ],

    'testTransactionAfterRefund' => [
        'type'          => 'refund',
        'merchant_id'   => '10000000000000',
        'amount'        => 50000,
        'fee'           => 0,
        'debit'         => 50000,
        'credit'        => 0,
        'currency'      => 'INR',
        'balance'       => 998524,
        'gateway_fee'   => 0,
        'api_fee'       => 0,
        'channel'       => 'axis',
        'settled'       => false,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity'        => 'transaction',
        'admin'         => true,
    ],

    'testPartialRefund' => [
        'merchant_id'         => '10000000000000',
        'amount'              => 50000,
        'method'              => 'wallet',
        'status'              => 'refunded',
        'amount_authorized'   => 50000,
        'amount_refunded'     => 50000,
        'refund_status'       => 'full',
        'currency'            => 'INR',
        'description'         => 'random description',
        'card_id'             => NULL,
        'bank'                => NULL,
        'wallet'              => 'payzapp',
        'emi_plan_id'         => NULL,
        'error_code'          => NULL,
        'internal_error_code' => NULL,
        'error_description'   => NULL,
        'email'               => 'a@b.com',
        'contact'             => '+919918899029',
        'notes'               => [
            'merchant_order_id'   => 'random order id',
        ],
        'gateway'             => 'wallet_payzapp',
        'fee'                 => 1476,
        'tax'                 => 226,
        'captured'            => true,
        'entity'              => 'payment',
        'admin'               => true,
    ],
    'testPaymentPayzappEntity' => [
        'action'               => 'authorize',
        'amount'               => '50000',
        'wallet'               => 'payzapp',
        'received'             => true,
        'email'                => 'a@b.com',
        'contact'              => '+919918899029',
        'gateway_refund_id'    => null,
        'response_code'        => '000',
        'response_description' => 'SUCCESS',
        'status_code'          => null,
        'error_message'        => null,
        'reference2'           => '0',
        'date'                 => null,
        'refund_id'            => null,
        'entity'               => 'wallet',
        'admin'                => true,
    ],
    'testRefundPayment' => [
          'merchant_id'         => '10000000000000',
          'amount'              => 50000,
          'method'              => 'wallet',
          'status'              => 'refunded',
          'amount_authorized'   => 50000,
          'amount_refunded'     => 50000,
          'refund_status'       => 'full',
          'currency'            => 'INR',
          'description'         => 'random description',
          'card_id'             => NULL,
          'bank'                => NULL,
          'wallet'              => 'payzapp',
          'emi_plan_id'         => NULL,
          'error_code'          => NULL,
          'internal_error_code' => NULL,
          'error_description'   => NULL,
          'email'               => 'a@b.com',
          'contact'             => '+919918899029',
          'notes'               => [
                'merchant_order_id'   => 'random order id',
          ],
          'gateway'             => 'wallet_payzapp',
          'fee'                 => 1476,
          'tax'                 => 226,
          'captured'            => true,
          'entity'              => 'payment',
          'admin'               => true,
    ],
    'testPaymentPayzappEntityAfterRefund' => [
          'action'                  => 'refund',
          'amount'                  => '50000',
          'wallet'                  => 'payzapp',
          'received'                => true,
          'email'                   => 'a@b.com',
          'contact'                 => '+919918899029',
          'gateway_merchant_id'     => '3456',
          'gateway_payment_id'      => NULL,
          'response_code'           => '0',
          'response_description'    => 'No Error',
          'status_code'             => '50020',
          'error_message'           => 'No Error',
          'reference1'              => NULL,
          'reference2'              => NULL,
          'date'                    => NULL,
          'entity'                  => 'wallet',
          'admin'                   => true,
    ],
];
