<?php

namespace RZP\Models\Gateway\File;

class FailureCode
{
    const NO_DATA_FOR_FILE_GENERATION = 'NO_DATA_FOR_FILE_GENERATION';
    const ERROR_GENERATING_FILE_DATA = 'ERROR_GENERATING_FILE_DATA';
    const ERROR_CREATING_FILE = 'ERROR_CREATING_FILE';
    const ERROR_SENDING_MAIL = 'ERROR_SENDING_MAIL';
}
