pipeline:
  clone:
    image: plugins/git
    when:
      event:
        exclude: [deployment]
        include: [push]
  build:
    image: plugins/docker
    repo: razorpay/auth
    secrets: [docker_username, docker_password, git_token]
    build_args_from_env: [git_token]
    build_args:
     - GIT_COMMIT_HASH=${DRONE_COMMIT_SHA}
    tags: ${DRONE_COMMIT_SHA}
    when:
      status: [success]
      event:
        exclude: [deployment]
        include: [push]
