version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    links:
      - db_live
      - db_test
    ports:
      - "8090:80"
    depends_on:
      - db_live
      - db_test
    environment:
      DB_LIVE_HOST: db_live
      SLAVE_DB_LIVE_HOST: db_live
      DB_TEST_HOST: db_test
      SLAVE_DB_TEST_HOST: db_test
  db_live:
    image: mysql:5.6
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: api_live
      MYSQL_USER: api_live
      MYSQL_PASSWORD: 123
  db_test:
    image: mysql:5.6
    ports:
      - 13307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: api_test
      MYSQL_USER: api_test
      MYSQL_PASSWORD: 123
