FROM mcr.microsoft.com/playwright:v1.31.1-focal

ARG INCLUDE_GROUPS
ARG EXCLUDE_GROUPS

ENV INCLUDE_GROUPS=$INCLUDE_GROUPS
ENV EXCLUDE_GROUPS=$EXCLUDE_GROUPS

WORKDIR /app

RUN mkdir web

# Copy dependencies files so we can have better caching as these don't change often
COPY --chown=node:node .npmrc package.json yarn.lock ./
COPY --chown=node:node ./plugins ./plugins

# Copy dependencies files so we can have better caching as these don't change often
COPY --chown=node:node ./web/.npmrc ./web/package.json ./web/yarn.lock ./web

RUN --mount=type=secret,id=github_access_token set -eux && \
  echo "$(cat /run/secrets/github_access_token)" >> ~/.GITHUB_ACCESS_TOKEN

RUN --mount=type=secret,id=npm_razorpay_token set -eux && \
  echo "$(cat /run/secrets/npm_razorpay_token)">> ~/.NPM_RAZORPAY_TOKEN

RUN export GITHUB_ACCESS_TOKEN="$(cat ~/.GITHUB_ACCESS_TOKEN)" && \
  export NPM_RAZORPAY_TOKEN="$(cat ~/.NPM_RAZORPAY_TOKEN)" && \
  yarn config set unsafe-perm true && \
  HUSKY=0 yarn --frozen-lockfile

RUN rm -f ~/.GITHUB_ACCESS_TOKEN && \
  rm -f ~/.NPM_RAZORPAY_TOKEN

RUN cd web && npx playwright install --with-deps

COPY . .

RUN rm -f .npmrc && \
  rm -f ./web/.npmrc

CMD cd web && INCLUDE_GROUPS=$INCLUDE_GROUPS EXCLUDE_GROUPS=$EXCLUDE_GROUPS yarn test:e2e
