ARG API_BASE_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:php-8.1-api-web-v2
ARG OPENCENSUS_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:php-8.1-opencensus
ARG CURL_CLI_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:curl-7.82

FROM ${OPENCENSUS_IMAGE} as opencensus-ext
FROM ${CURL_CLI_IMAGE} as curl-cli

FROM ${API_BASE_IMAGE}

ARG GIT_COMMIT_HASH
ARG GIT_USERNAME
ARG CACHEBUST
ENV GIT_COMMIT_HASH=${GIT_COMMIT_HASH}

WORKDIR /app

COPY --from=curl-cli /usr/bin/curl /usr/bin/

COPY composer.json composer.lock /app/

RUN --mount=type=secret,id=git_token set -eu && \
    composer --version && \
    git config --global user.name ${GIT_USERNAME} && \
    composer config -g "github-oauth.github.com" $(cat /run/secrets/git_token) && \
    composer config -g repos.packagist composer "https://packagist.rzp.io" && \
    composer install --no-dev --no-interaction --no-autoloader --no-scripts && \
    rm -rf /root/.composer && \
    composer clear-cache && \
    pear81 config-set php_ini /etc/php81/php.ini && \
    pecl81 install opencensus-alpha && \
    mkdir -p public && echo "${GIT_COMMIT_HASH}" > public/commit.txt

ENV PHP_MEMORY_LIMIT=4096M

COPY --from=opencensus-ext /usr/lib/php81/modules/opencensus.so /usr/lib/php81/modules

COPY --chown=apache:www-data . /app/

RUN cp dockerconf/default.conf dockerconf/mpm.conf /etc/apache2/conf.d/ && \
    composer dump-autoload -o

ADD Makefile /app
ADD error_modules /app
RUN echo ${CACHEBUST}

RUN --mount=type=secret,id=git_token set -eux && \
    echo "machine github.com login ${GIT_USERNAME} password $(cat /run/secrets/git_token)" > ~/.netrc && \
    make error-module-clean && \
    rm -f ~/.netrc

RUN --mount=type=secret,id=git_token set -eux && \
    echo "machine github.com login ${GIT_USERNAME} password $(cat /run/secrets/git_token)" > ~/.netrc && \
    make error-module-fetch && \
    rm -f ~/.netrc

EXPOSE 80

ENTRYPOINT [ "/usr/bin/dumb-init", "--single-child", "/app/dockerconf/entrypoint.web.sh"]
