ARG API_BASE_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:php-8.1-api-worker-v2

FROM ${API_BASE_IMAGE}

ARG GIT_COMMIT_HASH
ARG GIT_USERNAME
ARG CACHEBUST

WORKDIR /app

COPY composer.json composer.lock /app/

RUN --mount=type=secret,id=git_token set -eu && \
    composer --version && \
    git config --global user.name ${GIT_USERNAME} && \
    composer config -g "github-oauth.github.com" $(cat /run/secrets/git_token) && \
    composer config -g repos.packagist composer "https://packagist.rzp.io" && \
    composer install --no-dev --no-interaction --no-autoloader --no-scripts && \
    rm -rf /root/.composer && \
    composer clear-cache && \
    pear81 config-set php_ini /etc/php81/php.ini && \
    mkdir -p public && echo "${GIT_COMMIT_HASH}" > public/commit.txt

COPY . /app/

RUN composer dump-autoload -o

ADD Makefile /app
ADD error_modules /app
RUN echo ${CACHEBUST}

RUN --mount=type=secret,id=git_token set -eux && \
    echo "machine github.com login ${GIT_USERNAME} password $(cat /run/secrets/git_token)" > ~/.netrc && \
    make error-module-clean && \
    rm -f ~/.netrc

RUN --mount=type=secret,id=git_token set -eux && \
    echo "machine github.com login ${GIT_USERNAME} password $(cat /run/secrets/git_token)" > ~/.netrc && \
    make error-module-fetch && \
    rm -f ~/.netrc

RUN apk add font-noto font-noto-thai font-noto-tibetan font-ipa font-sony-misc font-jis-misc && \
    fc-cache -f

ENTRYPOINT [ "/usr/bin/dumb-init", "--single-child", "/app/dockerconf/entrypoint.worker.sh"]
