version: '2'
services:

  jaeger:
    image: jaegertracing/all-in-one:1.18
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 16686:16686
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 14268:14268
      - 14250:14250
      - 9411:9411

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: razorpay:dashboard
    volumes:
     - .:/app
    networks:
     - api_default
     - default
    links:
      - dashboard_db
      - dashboard_cache
      - jaeger
    ports:
      - 38080:80
    depends_on:
      - dashboard_db
      - dashboard_cache
    environment:
     DB_MYSQL_HOST: dashboard_db
     DB_MYSQL_PORT: 3306
     DB_MYSQL_DATABASE: dashboard
     DB_MYSQL_USERNAME: dashboard_user
     DB_MYSQL_PASSWORD: 123
     REDIS_HOST: dashboard_cache
     BASE_URL: http://dashboard.razorpay.in:38080
     API_URL: "http://razorpay-api/v1/"
     APP_CONTEXT: dev
     APP_MODE: dev
  dashboard_db:
    image: mysql:5.6
    ports:
      - 33306:3306
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: dashboard
      MYSQL_USER: dashboard_user
      MYSQL_PASSWORD: 123
  dashboard_cache:
    image: redis:2.8
    networks:
     - default
    ports:
      - 36379:6379
networks:
  api_default:
    external: true
