version: '2'
services:
  dashboard:
    build:
      context: .
      args:
        GIT_TOKEN:
    image: razorpay:dashboard
    links:
      - dashboard_cache
    ports:
      - 38080:80
    depends_on:
      - dashboard_cache
    environment:
     REDIS_HOST: dashboard_cache
     BASE_URL: http://dashboard.razorpay.in:38080
     API_URL: "https://beta-api.razorpay.in/v1/"
  dashboard_cache:
    image: redis:7.0.4
    ports:
      - 36379:6379
