version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: razorpay:api
    volumes:
      - .:/app
    links:
      - db_live
      - db_test
    ports:
      - 28080:80
    depends_on:
      - db_live
      - db_test
    environment:
      DB_LIVE_HOST: db_live
      SLAVE_DB_LIVE_HOST: db_live
      DB_TEST_HOST: db_test
      SLAVE_DB_TEST_HOST: db_test
      REDIS_HOST: cache
      SECURE_REDIS_HOST: cache
      QUEUE_REDIS_HOST: cache
  db_live:
    image: mysql:5.6
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: api_live
      MYSQL_USER: api_live
      MYSQL_PASSWORD: 123
  db_test:
    image: mysql:5.6
    ports:
      - 23307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: api_test
      MYSQL_USER: api_test
      MYSQL_PASSWORD: 123
  cache:
    image: redis:2.8
    ports:
      - 26379:6379
  es:
    image: elasticsearch:5.2-alpine
    container_name: razorpay-es
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - 29200:9200
