ARG ONGGI_IMAGE=razorpay/onggi:php-7.2-api
ARG OPENRESTY_IMAGE=openresty/openresty:1.17.8.2-0-alpine-fat-nosse42

FROM $ONGGI_IMAGE as php-builder

ARG GIT_COMMIT_HASH
ARG GIT_USERNAME

COPY composer.json composer.lock /app/

WORKDIR /app

COPY  . /app/

RUN --mount=type=secret,id=git_token set -eu && \
    composer --version && \
    git config --global user.name ${GIT_USERNAME} && \
    composer config -g "github-oauth.github.com" $(cat /run/secrets/git_token) && \
    composer config -g repos.packagist composer "https://packagist.rzp.io" && \
    composer install --no-dev --no-interaction --no-autoloader --no-scripts && \
    rm -rf /root/.composer && \
    composer clear-cache && \
    composer dump-autoload -o && \
    php artisan rzp:write_routes_meta


# Usage specific image which has luarocks compiled.
FROM $OPENRESTY_IMAGE

RUN apk update && \
    apk upgrade && \
    apk add git

RUN git config --global url.https://github.com/.insteadOf git://github.com/

RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-jwt \
    && /usr/local/openresty/luajit/bin/luarocks install lua-resty-redis \
    && /usr/local/openresty/luajit/bin/luarocks install lua-resty-lock \
    && git clone https://github.com/steve0511/resty-redis-cluster.git \
    && cd resty-redis-cluster/ \
    && git checkout 8d7b96d002337c38d71859e5f04f76b413aa5c29 \
    && luarocks make \
    && gcc -fPIC -shared -I/usr/local/openresty/luajit -o /usr/local/openresty/luajit/lib/lua/5.1/librestyredisslot.so src/redis_slot.c \
    && rm -Rf /src

RUN echo "* Installing deps" && \
    apk add --no-cache \
    bash \
    build-base \
    ca-certificates \
    coreutils \
    curl \
    dumb-init \
    git \
    libxml2-dev \
    libxslt-dev \
    libffi-dev \
    linux-headers \
    openssl \
    openssl-dev \
    py-pip \
    python \
    python-dev && \
    echo "* Installing Alohomora==0.4.7" && \
    pip install --upgrade pip && \
    pip install --no-cache-dir "razorpay.alohomora==0.4.7" && \
    rm -rf ~/.cache/pip/* &&\
    echo "* Installing gosu" && \
    curl --location --output /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$ARCH" && \
    chmod +x /usr/local/bin/gosu && \
    addgroup -S nginx && \
    adduser -S nginx -G nginx

COPY --from=php-builder --chown=nginx:nginx /app/dockerconf/openresty/openresty.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY --from=php-builder --chown=nginx:nginx /app/dockerconf/openresty/*.lua  /usr/local/openresty/nginx/lua/
COPY --from=php-builder --chown=nginx:nginx /app/dockerconf/openresty/api.openresty.conf.j2 /usr/local/openresty/nginx/sites/
COPY --from=php-builder --chown=nginx:nginx /app/dockerconf/openresty/routes_meta.lua /usr/local/openresty/nginx/lua/
COPY --from=php-builder --chown=nginx:nginx /app/dockerconf/entrypoint.openresty.sh /app/entrypoint.openresty.sh

EXPOSE 8080

ENTRYPOINT [ "/usr/bin/dumb-init", "--single-child", "/app/entrypoint.openresty.sh"]

