ARG NGINX_IMAGE=nginx:alpine
FROM $NGINX_IMAGE

ARG GIT_COMMIT_HASH
ENV GIT_COMMIT_HASH=${GIT_COMMIT_HASH}

COPY resources/views/checkout/checkout.*.html /app/
COPY --chown=nginx:nginx dockerconf/nginx-checkout.conf /etc/nginx/conf.d/default.conf

WORKDIR /app

RUN echo "${GIT_COMMIT_HASH}" > /app/commit.txt

ENTRYPOINT ["nginx", "-g", "daemon off;"]
