FROM razorpay/armory:wkhtmltopdf-v182 as wkhtmltopdf

FROM razorpay/onggi:php-7.2-api-worker

ARG GIT_COMMIT_HASH
ARG GIT_TOKEN
ARG GIT_USERNAME

WORKDIR /app

COPY --from=wkhtmltopdf /bin/wkhtmltopdf /usr/bin/wkhtmltopdf

COPY composer.json composer.lock /app/

RUN set -eu && \
    composer --version && \
    git config --global user.name ${GIT_USERNAME} && \
    composer config -g "github-oauth.github.com" ${GIT_TOKEN} && \
    composer config -g repos.packagist composer "https://packagist.rzp.io" && \
    composer install --no-dev --no-interaction --no-autoloader --no-scripts && \
    rm -rf /root/.composer && \
    composer clear-cache && \
    pear config-set php_ini /etc/php7/php.ini && \
    mkdir -p public && echo "${GIT_COMMIT_HASH}" > public/commit.txt

COPY . /app/

RUN composer dump-autoload -o && \
    php artisan optimize

ENTRYPOINT [ "/usr/bin/dumb-init", "--single-child", "/app/dockerconf/entrypoint.worker.sh"]
