FROM razorpay/armory:wkhtmltopdf-v182 as wkhtmltopdf

FROM razorpay/onggi:php-7.2-api-web

COPY --from=wkhtmltopdf /bin/wkhtmltopdf /usr/bin/wkhtmltopdf

RUN pear config-set php_ini /etc/php7/php.ini

VOLUME ['/app']

WORKDIR /app

EXPOSE 80

ENTRYPOINT ["/usr/bin/dumb-init", "--single-child", "/app/dockerconf/entrypoint.dev.sh"]
