ARG ONGGI_IMAGE=c.rzp.io/razorpay/onggi_testing:php81-fpm-nginxphp-8.1-nginx

FROM c.rzp.io/razorpay/onggi:php-8.1-api-web as opencensus-ext


FROM $ONGGI_IMAGE as opencensus-ext

WORKDIR /
ARG OPENCENSUS_VERSION_TAG=v0.8.0-beta
RUN set -eux && \
    wget -O - https://github.com/razorpay/opencensus-php/tarball/"${OPENCENSUS_VERSION_TAG}" | tar zx --strip=1
RUN cd /ext && phpize81 && ./configure --enable-opencensus --with-php-config=/usr/bin/php-config81 && make install

FROM $ONGGI_IMAGE

ARG GIT_COMMIT_HASH
ARG GIT_USERNAME

COPY composer.json composer.lock /app/

WORKDIR /app

RUN --mount=type=secret,id=git_token set -eu && \
    composer --version && \
    git config --global user.name ${GIT_USERNAME} && \
    composer config -g "github-oauth.github.com" $(cat /run/secrets/git_token) && \
    composer config -g repos.packagist composer "https://packagist.rzp.io" && \
    composer install --no-dev --no-interaction --no-autoloader --no-scripts && \
    rm -rf /root/.composer && \
    composer clear-cache && \
    pear81 config-set php_ini /etc/php81/php.ini && \
    pecl81 install opencensus-alpha

RUN mkdir -p public && \
    echo ${GIT_COMMIT_HASH} > public/commit.txt

COPY --from=opencensus-ext /usr/lib/php81/modules/opencensus.so /usr/lib/php81/modules

COPY --chown=nginx:nginx . /app/

COPY --chown=nginx:nginx ./public/dist/sw-utils/sw-merchant.js ./public/sw-merchant.js
COPY --chown=nginx:nginx ./public/dist/sw-utils/sw-merchantLA.js ./public/sw-merchantLA.js

COPY --chown=nginx:nginx ./public/dist/merchant-preload.blade.php ./resources/views/partials/preload/merchant-preload.blade.php
COPY --chown=nginx:nginx ./public/dist/merchantLA-preload.blade.php ./resources/views/partials/preload/merchantLA-preload.blade.php

# This step can't run without some classes from above step
RUN composer dump-autoload -o

RUN cd /app/ && php artisan optimize

EXPOSE 80

STOPSIGNAL SIGQUIT

ENTRYPOINT ["/entrypoint.sh"]
