FROM mcr.microsoft.com/playwright:v1.31.0-focal

ARG GITHUB_ACCESS_TOKEN
ARG NPM_RAZORPAY_TOKEN

ENV GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN
ENV NPM_RAZORPAY_TOKEN=$NPM_RAZORPAY_TOKEN

WORKDIR /app

RUN mkdir web

# Copy dependencies files so we can have better caching as these don't change often
COPY --chown=node:node .npmrc package.json yarn.lock ./

# Copy dependencies files so we can have better caching as these don't change often
COPY --chown=node:node ./web/.npmrc ./web/package.json ./web/yarn.lock ./web

RUN yarn config set unsafe-perm true \
    && HUSKY=0 yarn --frozen-lockfile

RUN cd web && npx playwright install --with-deps

COPY . .

RUN chmod +x /app/run-e2e.sh

ENTRYPOINT ["/app/run-e2e.sh"]
