# Required metadata
sonar.projectKey=dashboard
sonar.projectName=dashboard

# Path to the parent source code directory.
# sonar.sources=app
# sonar.tests=Tests
sonar.sources=web/js
sonar.tests=web/js
sonar.test.inclusions=**/__test__/**,**/__tests__/**

# Language
# We've commented this out, because we want to analyse both PHP and Javascript
#sonar.language=php

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Reusing PHPUnit reports
# sonar.php.coverage.reportPath=ci/codeCoverage/codeCoverage.xml
# sonar.php.tests.reportPath=ci/codeCoverage/tests-junit.xml

# Jest UT report
sonar.testExecutionReportPaths=web/js/coverage/sonar-report.xml
sonar.javascript.lcov.reportPaths=web/js/coverage/lcov.info

# Here, you can exclude all the directories that you don't want to analyse.
# As an example, I'm excluding the Providers directory
sonar.exclusions=vendor,node_modules,public/dist,**/__test__/**,tests/**,**/__tests__/**

# Eslint reports
sonar.externalIssuesReportPaths=eslint_report.json
# Additional parameters
#sonar.my.property=value
