<?php

namespace RZP\Reconciliator\UpiIcici;

use RZP\Reconciliator\Base;

class RefundReconciliate extends Base\RefundReconciliate
{
    const REFUND_ID = 'merchanttranid';

    const COLUMN_REFUND_AMOUNT = 'refund_amount';

    const ORIGINAL_BANK_RRN = 'original_bank_rrn';

    protected function getRefundId(array $row)
    {
        return $row[self::REFUND_ID];
    }

    protected function getPaymentId(array $row)
    {
        $rrn = $row[self::ORIGINAL_BANK_RRN];

        $upiEntity = $this->repo->upi->fetchByGatewayPaymentIdAndAction($rrn);

        return $upiEntity->getPaymentId();
    }

    protected function getGatewaySettledAt(array $row)
    {
        // TODO: Look into this
        return parent::getGatewaySettledAt($row); // TODO: Change the autogenerated stub
    }

    // TODO: Need to discuss this
    protected function getArn(array $row)
    {
        return null;
    }
}