import React from 'react';
import {
  APP_ENV,
  APP_NAME,
  BANKING_SERVICE_URL,
  BANK_DETAILS_URL,
  CDN_BASE_URL,
  CDN_DASHBOARD_ASSETS_URL,
  CDN_DASHBOARD_URL,
  CHECKBOX_CAPTCHA_SITE_KEY,
  CURLEC_LINKED_ACCOUNT_ONBOARDING_URL,
  EASY_ONBOARDING_URL,
  EASY_DASHBOARD_CURLEC_URL,
  EASY_DASHBOARD_SG_URL,
  EASY_DASHBOARD_US_URL,
  INSTANCE_TYPE,
  INVISIBLE_CAPTCHA_SITE_KEY,
  LUMBERJACK_API_KEY,
  LUMBERJACK_API_URL,
  LUMBERJACK_METRICS_API_URL,
  OAUTH_CLIENT_ID,
  PP_ECOMMERCE_URL,
  INSIGHTS_SUPERSET_URL,
  PUBLIC_API_URL,
  RAZORPAY_WEBSITE,
  RECAPTCHA_V3_SITE_KEY,
  REFINER_PROJECT_ID,
  SEGMENT_API_KEY,
  SHIELD_STAGE,
  STREAKS_REWARDS,
  WEBSITE_SEGMENT_API_KEY,
  X_WEBSITE_SEGMENT_API_KEY,
  RAZORPAY_ACCOUNTS_URL,
  X_BANKING_REMOTE_ENTRY,
} from '@apps/shell/src/env';

export const generateEnvironmentKeysGetterScriptElement = () => {
  return (
    <script
      key="env-keys"
      dangerouslySetInnerHTML={{
        __html: `
        window.SHELL_SERVER = true;
        window.LUMBERJACK_API_KEY = "${LUMBERJACK_API_KEY}";
        window.LUMBERJACK_API_URL = "${LUMBERJACK_API_URL}";
        window.SEGMENT_API_KEY = "${SEGMENT_API_KEY}";
        window.WEBSITE_SEGMENT_API_KEY = "${WEBSITE_SEGMENT_API_KEY}";
        window.X_WEBSITE_SEGMENT_API_KEY = "${X_WEBSITE_SEGMENT_API_KEY}";
        window.SHIELD_STAGE = "${SHIELD_STAGE}";
        window.cdnDashboardUrl = "${CDN_DASHBOARD_URL}";
        window.cdnBaseUrl = "${CDN_BASE_URL}";
        window.cdnDashboardAssetsUrl = "${CDN_DASHBOARD_ASSETS_URL}";
        window.bankingServiceUrl = "${BANKING_SERVICE_URL}";
        window.OAUTH_CLIENT_ID = "${OAUTH_CLIENT_ID}";
        window.INVISIBLE_CAPTCHA_SITE_KEY = "${INVISIBLE_CAPTCHA_SITE_KEY}";
        window.CHECKBOX_CAPTCHA_SITE_KEY = "${CHECKBOX_CAPTCHA_SITE_KEY}";
        window.RECAPTCHA_V3_SITE_KEY = "${RECAPTCHA_V3_SITE_KEY}";
        window.STREAKS_REWARDS = "${STREAKS_REWARDS}";
        window.REFINER_PROJECT_ID = "${REFINER_PROJECT_ID}";
        window.EASY_ONBOARDING_URL = "${EASY_ONBOARDING_URL}";
        window.EASY_DASHBOARD_CURLEC_URL = "${EASY_DASHBOARD_CURLEC_URL}";
        window.EASY_DASHBOARD_SG_URL = "${EASY_DASHBOARD_SG_URL}";
        window.EASY_DASHBOARD_US_URL = "${EASY_DASHBOARD_US_URL}";
        window.PP_ECOMMERCE_URL = "${PP_ECOMMERCE_URL}";
        window.INSIGHTS_SUPERSET_URL = "${INSIGHTS_SUPERSET_URL}";
        window.BANK_DETAILS_URL = "${BANK_DETAILS_URL}";
        window.APP_NAME = "${APP_NAME}";
        window.LUMBERJACK_METRICS_API_URL = "${LUMBERJACK_METRICS_API_URL}";
        window.RAZORPAY_WEBSITE = "${RAZORPAY_WEBSITE}";
        window.CURLEC_LINKED_ACCOUNT_ONBOARDING_URL = "${CURLEC_LINKED_ACCOUNT_ONBOARDING_URL}";
        window.RAZORPAY_ACCOUNTS_URL = "${RAZORPAY_ACCOUNTS_URL}";
        window.X_BANKING_REMOTE_ENTRY = "${X_BANKING_REMOTE_ENTRY}";

        // Sentry related configs
        window.APP_ENV = "${APP_ENV}";
        window.INSTANCE_TYPE = "${INSTANCE_TYPE}";
    
        // Public API URL
        window.PUBLIC_API_URL = "${PUBLIC_API_URL}";
          `,
      }}
    />
  );
};
