export enum DashboardGraphQLAadhaarOtpVerifyErrorTypeEnum {
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
  INCORRECT_OTP = 'INCORRECT_OTP',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  INVALID_SESSION_ID = 'INVALID_SESSION_ID',
  NO_PROVIDER_ERROR = 'NO_PROVIDER_ERROR',
  OTP_LIMIT_EXCEEDED = 'OTP_LIMIT_EXCEEDED',
  TIME_OUT_ERROR = 'TIME_OUT_ERROR',
  UIDAI_DOWNTIME_ERROR = 'UIDAI_DOWNTIME_ERROR',
  VALID_RESPONSE = 'VALID_RESPONSE',
}