export enum DashboardGraphQLMerchantSelfServeGstinPermissionEnum {
  EDIT_MERCHANT_BANK_ACCOUNT_DETAIL = 'EDIT_MERCHANT_BANK_ACCOUNT_DETAIL',
  EDIT_MERCHANT_GSTIN_DETAIL = 'EDIT_MERCHANT_GSTIN_DETAIL',
  UPDATE_MERCHANT_GSTIN_DETAIL = 'UPDATE_MERCHANT_GSTIN_DETAIL',
}