import { DashboardGraphQLMerchantWebsitePublishFailureResponse, DashboardGraphQLMerchantWebsitePublishSuccessResponse } from './index';
export type DashboardGraphQLMerchantWebsitePublishResponse =
  | DashboardGraphQLMerchantWebsitePublishFailureResponse
  | DashboardGraphQLMerchantWebsitePublishSuccessResponse;