export enum DashboardGraphQLPayoutStatusEnum {
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  PROCESSING = 'PROCESSING',
  QUEUED = 'QUEUED',
  REJECTED = 'REJECTED',
  REVERSED = 'REVERSED',
  SCHEDULED = 'SCHEDULED',
}