export enum DashboardGraphQLPayoutBatchTypeEnum {
  AMAZON_PAY_DETAILS = 'AMAZON_PAY_DETAILS',
  AMAZON_PAY_ID = 'AMAZON_PAY_ID',
  BANK_ACCOUNT_DETAILS = 'BANK_ACCOUNT_DETAILS',
  BANK_ACCOUNT_ID = 'BANK_ACCOUNT_ID',
  PAYOUT = 'PAYOUT',
  UPI_DETAILS = 'UPI_DETAILS',
  UPI_ID = 'UPI_ID',
}