export enum DashboardGraphQLSendEmailVerificationOtpEnum {
  BAD_REQUEST_EMAIL_VERIFICATION_OTP_SEND_THRESHOLD_EXHAUSTED = 'BAD_REQUEST_EMAIL_VERIFICATION_OTP_SEND_THRESHOLD_EXHAUSTED',
  BAD_REQUEST_PASSWORD_ALREADY_SET = 'BAD_REQUEST_PASSWORD_ALREADY_SET',
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
}