import { DashboardGraphQLMerchantContactTypeCreateResponseDuplicate, DashboardGraphQLMerchantContactTypeCreateResponseSuccess } from './index';
export type DashboardGraphQLMerchantContactTypeCreateResponse =
  | DashboardGraphQLMerchantContactTypeCreateResponseDuplicate
  | DashboardGraphQLMerchantContactTypeCreateResponseSuccess;