import { DashboardGraphQLMerchantPaymentHandleUpdateFailureResponse, DashboardGraphQLMerchantPaymentHandleUpdateSuccessResponse } from './index';
export type DashboardGraphQLMerchantPaymentHandleUpdateResponse =
  | DashboardGraphQLMerchantPaymentHandleUpdateFailureResponse
  | DashboardGraphQLMerchantPaymentHandleUpdateSuccessResponse;