import { DashboardGraphQLTwoFactorPasswordEnabledErrorResponse, DashboardGraphQLTwoFactorPasswordEnabledSuccessResponse } from './index';
export type DashboardGraphQLTwoFactorPasswordEnabledResponse =
  | DashboardGraphQLTwoFactorPasswordEnabledErrorResponse
  | DashboardGraphQLTwoFactorPasswordEnabledSuccessResponse;