export enum DashboardGraphQLLoginOtpErrorCodeEnum {
  BAD_REQUEST_CONTACT_MOBILE_NOT_VERIFIED = 'BAD_REQUEST_CONTACT_MOBILE_NOT_VERIFIED',
  BAD_REQUEST_EMAIL_LOGIN_OTP_SEND_THRESHOLD_EXHAUSTED = 'BAD_REQUEST_EMAIL_LOGIN_OTP_SEND_THRESHOLD_EXHAUSTED',
  BAD_REQUEST_EMAIL_NOT_VERIFIED = 'BAD_REQUEST_EMAIL_NOT_VERIFIED',
  BAD_REQUEST_MAXIMUM_SMS_LIMIT_REACHED = 'BAD_REQUEST_MAXIMUM_SMS_LIMIT_REACHED',
  BAD_REQUEST_MOBILE_OTP_LOGIN_NOT_ALLOWED = 'BAD_REQUEST_MOBILE_OTP_LOGIN_NOT_ALLOWED',
  BAD_REQUEST_MULTIPLE_ACCOUNTS_ASSOCIATED = 'BAD_REQUEST_MULTIPLE_ACCOUNTS_ASSOCIATED',
  BAD_REQUEST_NO_ACCOUNTS_ASSOCIATED = 'BAD_REQUEST_NO_ACCOUNTS_ASSOCIATED',
  BAD_REQUEST_NO_RECORDS_FOUND = 'BAD_REQUEST_NO_RECORDS_FOUND',
  BAD_REQUEST_OTP_LOGIN_LOCKED = 'BAD_REQUEST_OTP_LOGIN_LOCKED',
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
}