export enum DashboardGraphQLMerchantActivationStatusEnum {
  ACTIVATED = 'ACTIVATED',
  ACTIVATED_KYC_PENDING = 'ACTIVATED_KYC_PENDING',
  ACTIVATED_MCC_PENDING = 'ACTIVATED_MCC_PENDING',
  INSTANTLY_ACTIVATED = 'INSTANTLY_ACTIVATED',
  KYC_QUALIFIED_UNACTIVATED = 'KYC_QUALIFIED_UNACTIVATED',
  NEEDS_CLARIFICATION = 'NEEDS_CLARIFICATION',
  P2PM_ACTIVATED = 'P2PM_ACTIVATED',
  REJECTED = 'REJECTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
}