import { DashboardGraphQLScalars, DashboardGraphQLInputMaybe, DashboardGraphQLTransactionTypeEnum, DashboardGraphQLPayoutModeEnum, DashboardGraphQLTransactionSourceTypeEnum } from './index';
export type DashboardGraphQLQueryTransactionsArgs = {
  accountNumber: DashboardGraphQLScalars['String'];
  action?: DashboardGraphQLInputMaybe<DashboardGraphQLTransactionTypeEnum>;
  contactEmail?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['String']>;
  contactId?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['String']>;
  contactName?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['String']>;
  contactPhone?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['String']>;
  contactType?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['String']>;
  fromDate?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['DateTime']>;
  fundAccountId?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['String']>;
  limit: DashboardGraphQLScalars['PositiveInt'];
  mode?: DashboardGraphQLInputMaybe<DashboardGraphQLPayoutModeEnum>;
  offset: DashboardGraphQLScalars['NonNegativeInt'];
  payoutId?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['String']>;
  payoutPurpose?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['String']>;
  toDate?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['DateTime']>;
  transactionId?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['ID']>;
  type?: DashboardGraphQLInputMaybe<DashboardGraphQLTransactionSourceTypeEnum>;
  utr?: DashboardGraphQLInputMaybe<DashboardGraphQLScalars['String']>;
};