import { DashboardGraphQLMerchantPaymentHandleCreateFailureResponse, DashboardGraphQLMerchantPaymentHandleCreateSuccessResponse } from './index';
export type DashboardGraphQLMerchantPaymentHandleCreateResponse =
  | DashboardGraphQLMerchantPaymentHandleCreateFailureResponse
  | DashboardGraphQLMerchantPaymentHandleCreateSuccessResponse;