export enum DashboardGraphQLTransactionSourceTypeEnum {
  ADJUSTMENT = 'ADJUSTMENT',
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  EXTERNAL = 'EXTERNAL',
  FUND_ACCOUNT_VALIDATION = 'FUND_ACCOUNT_VALIDATION',
  PAYOUT = 'PAYOUT',
  REVERSAL = 'REVERSAL',
}