export enum DashboardGraphQLMerchantIdentityTypeEnum {
  COMPANY_IDENTIFICATION_NUMBER = 'COMPANY_IDENTIFICATION_NUMBER',
  LIMITED_LIABILITY_PARTNERSHIP_IDENTIFICATION_NUMBER = 'LIMITED_LIABILITY_PARTNERSHIP_IDENTIFICATION_NUMBER',
}