import { DashboardGraphQLTwoFactorEmailOtpVerifyFailureResponse, DashboardGraphQLTwoFactorEmailOtpVerifySuccessResponse } from './index';
export type DashboardGraphQLTwoFactorEmailOtpVerifyResponse =
  | DashboardGraphQLTwoFactorEmailOtpVerifyFailureResponse
  | DashboardGraphQLTwoFactorEmailOtpVerifySuccessResponse;