import { DashboardGraphQLAadhaarDigilockerRedirectionVerificationFailureResponse, DashboardGraphQLAadhaarDigilockerRedirectionVerificationSuccessResponse } from './index';
export type DashboardGraphQLAadhaarDigilockerRedirectionUrlVerifyResponse =
  | DashboardGraphQLAadhaarDigilockerRedirectionVerificationFailureResponse
  | DashboardGraphQLAadhaarDigilockerRedirectionVerificationSuccessResponse;