export enum DashboardGraphQLAadhaarDigilockerRedirectionVerificationErrorTypeEnum {
  BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  SERVER_ERROR = 'SERVER_ERROR',
  TIME_OUT_ERROR = 'TIME_OUT_ERROR',
  VENDOR_NOT_AVAILABLE = 'VENDOR_NOT_AVAILABLE',
}