export enum DashboardGraphQLMerchantBankVerificationErrorCodeEnum {
  ACCOUNT_BLOCKED_OR_FROZEN = 'ACCOUNT_BLOCKED_OR_FROZEN',
  ACCOUNT_CLOSED = 'ACCOUNT_CLOSED',
  INVALID_ACCOUNT = 'INVALID_ACCOUNT',
  INVALID_BENEFICIARY_IFSC_CODE_OR_NBIN = 'INVALID_BENEFICIARY_IFSC_CODE_OR_NBIN',
  INVALID_BENEFICIARY_NUMBER_OR_IFSC = 'INVALID_BENEFICIARY_NUMBER_OR_IFSC',
  NOT_MATCHED = 'NOT_MATCHED',
  NRE_ACCOUNT = 'NRE_ACCOUNT',
}