export enum DashboardGraphQLMerchantActivationMilestoneEnum {
  ACTIVATION_FLOW_COMPLETED = 'ACTIVATION_FLOW_COMPLETED',
  FUNDS_ON_HOLD_REMINDER = 'FUNDS_ON_HOLD_REMINDER',
  HARD_LIMIT_LEVEL_1 = 'HARD_LIMIT_LEVEL_1',
  HARD_LIMIT_LEVEL_2 = 'HARD_LIMIT_LEVEL_2',
  HARD_LIMIT_LEVEL_4 = 'HARD_LIMIT_LEVEL_4',
  L1_COMPLETED = 'L1_COMPLETED',
  L2_COMPLETED = 'L2_COMPLETED',
  P2PM = 'P2PM',
  SOFT_LIMIT = 'SOFT_LIMIT',
  SOFT_LIMIT_LEVEL_1 = 'SOFT_LIMIT_LEVEL_1',
}