import { DashboardGraphQLOnboardingPaymentOrderCreateFailureResponse, DashboardGraphQLOnboardingPaymentOrderCreateSuccessResponse } from './index';
export type DashboardGraphQLOnboardingPaymentOrderCreateResponse =
  | DashboardGraphQLOnboardingPaymentOrderCreateFailureResponse
  | DashboardGraphQLOnboardingPaymentOrderCreateSuccessResponse;