import { DashboardGraphQLNotificationEmailUpdateFailureResponse, DashboardGraphQLNotificationEmailUpdateSuccessResponse } from './index';
export type DashboardGraphQLNotificationEmailUpdateResponse =
  | DashboardGraphQLNotificationEmailUpdateFailureResponse
  | DashboardGraphQLNotificationEmailUpdateSuccessResponse;