export enum DashboardGraphQLMerchantInstrumentStatusEnum {
  ACCOUNT_LINKABLE = 'ACCOUNT_LINKABLE',
  ACTION_REQUIRED = 'ACTION_REQUIRED',
  ACTIVATED = 'ACTIVATED',
  ACTIVATED_ACTION_REQUIRED = 'ACTIVATED_ACTION_REQUIRED',
  CANCELLED = 'CANCELLED',
  GREYED = 'GREYED',
  PENDING = 'PENDING',
  REINITATED = 'REINITATED',
  REJECTED = 'REJECTED',
  REQUESTABLE = 'REQUESTABLE',
  REQUESTED = 'REQUESTED',
}