export enum DashboardGraphQLPayoutBatchStatusEnum {
  CREATED = 'CREATED',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  PROCESSING = 'PROCESSING',
  REJECTED = 'REJECTED',
  VALIDATED = 'VALIDATED',
  VALIDATING = 'VALIDATING',
}