export enum DashboardGraphQLAuthErrorCodeEnum {
  BAD_REQUEST_2FA_LOGIN_INCORRECT_PASSWORD = 'BAD_REQUEST_2FA_LOGIN_INCORRECT_PASSWORD',
  BAD_REQUEST_2FA_LOGIN_PASSWORD_SUSPENDED = 'BAD_REQUEST_2FA_LOGIN_PASSWORD_SUSPENDED',
  BAD_REQUEST_INCORRECT_OTP = 'BAD_REQUEST_INCORRECT_OTP',
  BAD_REQUEST_LOGIN_OTP_VERIFICATION_THRESHOLD_EXHAUSTED = 'BAD_REQUEST_LOGIN_OTP_VERIFICATION_THRESHOLD_EXHAUSTED',
  BAD_REQUEST_NO_ACCOUNTS_ASSOCIATED = 'BAD_REQUEST_NO_ACCOUNTS_ASSOCIATED',
  BAD_REQUEST_OTP_LOGIN_LOCKED = 'BAD_REQUEST_OTP_LOGIN_LOCKED',
  BAD_REQUEST_OTP_MAXIMUM_ATTEMPTS_REACHED = 'BAD_REQUEST_OTP_MAXIMUM_ATTEMPTS_REACHED',
  BAD_REQUEST_VERIFICATION_OTP_VERIFICATION_THRESHOLD_EXHAUSTED = 'BAD_REQUEST_VERIFICATION_OTP_VERIFICATION_THRESHOLD_EXHAUSTED',
  LOGIN_UNAUTHENTICATED = 'LOGIN_UNAUTHENTICATED',
}