export enum DashboardGraphQLPettyCashStatusEnum {
  CANCELLED = 'CANCELLED',
  CREATED = 'CREATED',
  FAILED = 'FAILED',
  IN_APPROVAL = 'IN_APPROVAL',
  PROCESSED = 'PROCESSED',
  PROCESSING = 'PROCESSING',
  REJECTED = 'REJECTED',
  REVERSED = 'REVERSED',
}