export enum DashboardGraphQLUserRoleBankingEnum {
  ADMIN = 'ADMIN',
  CHARTERED_ACCOUNTANT = 'CHARTERED_ACCOUNTANT',
  FINANCE_L1 = 'FINANCE_L1',
  FINANCE_L2 = 'FINANCE_L2',
  FINANCE_L3 = 'FINANCE_L3',
  OPERATIONS = 'OPERATIONS',
  OWNER = 'OWNER',
  VENDOR = 'VENDOR',
  VIEW_ONLY = 'VIEW_ONLY',
}