export enum DashboardGraphQLAadhaarCaptchaErrorTypeEnum {
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  NO_PROVIDER_ERROR = 'NO_PROVIDER_ERROR',
  TIME_OUT_ERROR = 'TIME_OUT_ERROR',
  UIDAI_DOWNTIME_ERROR = 'UIDAI_DOWNTIME_ERROR',
}