import { DashboardGraphQLPointOfSalePaymentUpdateFailureResponse, DashboardGraphQLPointOfSalePaymentUpdateSuccessResponse } from './index';
export type DashboardGraphQLPointOfSalePaymentUpdateResponse =
  | DashboardGraphQLPointOfSalePaymentUpdateFailureResponse
  | DashboardGraphQLPointOfSalePaymentUpdateSuccessResponse;