import { DashboardGraphQLMerchantModularOnboardingDetailsFailureResponse, DashboardGraphQLMerchantModularOnboardingDetailsSuccessResponse } from './index';
export type DashboardGraphQLMerchantModularOnboardingDetailsUpdateResponse =
  | DashboardGraphQLMerchantModularOnboardingDetailsFailureResponse
  | DashboardGraphQLMerchantModularOnboardingDetailsSuccessResponse;