import { DashboardGraphQLTwoFactorPasswordCreateErrorResponse, DashboardGraphQLTwoFactorPasswordCreateSuccessResponse } from './index';
export type DashboardGraphQLTwoFactorPasswordCreateResponse =
  | DashboardGraphQLTwoFactorPasswordCreateErrorResponse
  | DashboardGraphQLTwoFactorPasswordCreateSuccessResponse;