import { DashboardGraphQLMerchantInstrumentCreateFailureResponse, DashboardGraphQLMerchantInstrumentCreateSuccessResponse } from './index';
export type DashboardGraphQLMerchantInstrumentCreateResponse =
  | DashboardGraphQLMerchantInstrumentCreateFailureResponse
  | DashboardGraphQLMerchantInstrumentCreateSuccessResponse;