export enum DashboardGraphQLMerchantVerificationStatusEnum {
  FAILED = 'FAILED',
  INCORRECT_DETAILS = 'INCORRECT_DETAILS',
  INITIATED = 'INITIATED',
  NOT_INITIATED = 'NOT_INITIATED',
  NOT_MATCHED = 'NOT_MATCHED',
  NOT_VERIFIED = 'NOT_VERIFIED',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
}