import { DashboardGraphQLModularOnboardingStepWithModularComponents, DashboardGraphQLModularOnboardingStepWithSteps } from './index';
export type DashboardGraphQLModularOnboardingStep =
  | DashboardGraphQLModularOnboardingStepWithModularComponents
  | DashboardGraphQLModularOnboardingStepWithSteps;