import { DashboardGraphQLOauthTokenAppleWatchResponseError, DashboardGraphQLOauthTokenAppleWatchResponseSuccess } from './index';
export type DashboardGraphQLOauthTokenAppleWatchResponse =
  | DashboardGraphQLOauthTokenAppleWatchResponseError
  | DashboardGraphQLOauthTokenAppleWatchResponseSuccess;