export enum DashboardGraphQLMerchantEddStatusEnum {
  APPROVED = 'APPROVED',
  FAILED = 'FAILED',
  INITIATED = 'INITIATED',
  NOT_VERIFIED = 'NOT_VERIFIED',
  REJECTED = 'REJECTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  UN_INITIATED = 'UN_INITIATED',
}