import { DashboardGraphQLSendEmailVerificationOtpErrorResponse, DashboardGraphQLSendEmailVerificationOtpSuccessResponse } from './index';
export type DashboardGraphQLSendEmailVerificationOtpResponse =
  | DashboardGraphQLSendEmailVerificationOtpErrorResponse
  | DashboardGraphQLSendEmailVerificationOtpSuccessResponse;