import { DashboardGraphQLPointOfSalePaymentCreateFailureResponse, DashboardGraphQLPointOfSalePaymentCreateSuccessResponse } from './index';
export type DashboardGraphQLPointOfSalePaymentCreateResponse =
  | DashboardGraphQLPointOfSalePaymentCreateFailureResponse
  | DashboardGraphQLPointOfSalePaymentCreateSuccessResponse;