export enum DashboardGraphQLVerifyEmailOtpEnum {
  BAD_REQUEST_EMAIL_OTP_VERIFICATION_THRESHOLD_EXHAUSTED = 'BAD_REQUEST_EMAIL_OTP_VERIFICATION_THRESHOLD_EXHAUSTED',
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
}