import { DashboardGraphQLWorkflowConfigStateRulePayoutTypeBetween, DashboardGraphQLWorkflowConfigStateRulePayoutTypeChecker, DashboardGraphQLWorkflowConfigStateRulePayoutTypeMergeStates } from './index';
export type DashboardGraphQLWorkflowConfigStateRulePayout =
  | DashboardGraphQLWorkflowConfigStateRulePayoutTypeBetween
  | DashboardGraphQLWorkflowConfigStateRulePayoutTypeChecker
  | DashboardGraphQLWorkflowConfigStateRulePayoutTypeMergeStates;