import { DashboardGraphQLMerchantStoreActivateFailureResponse, DashboardGraphQLMerchantStoreActivateSuccessResponse } from './index';
export type DashboardGraphQLMerchantStoreActivateResponse =
  | DashboardGraphQLMerchantStoreActivateFailureResponse
  | DashboardGraphQLMerchantStoreActivateSuccessResponse;