import { DashboardGraphQLMerchantPaymentHandleFailureResponse, DashboardGraphQLMerchantPaymentHandleSuccessResponse } from './index';
export type DashboardGraphQLMerchantPaymentHandleResponse =
  | DashboardGraphQLMerchantPaymentHandleFailureResponse
  | DashboardGraphQLMerchantPaymentHandleSuccessResponse;