import { DashboardGraphQLMerchantBankAccountDocumentUploadFailureResponse, DashboardGraphQLMerchantBankAccountDocumentUploadSuccessResponse } from './index';
export type DashboardGraphQLMerchantBankAccountDocumentUploadResponse =
  | DashboardGraphQLMerchantBankAccountDocumentUploadFailureResponse
  | DashboardGraphQLMerchantBankAccountDocumentUploadSuccessResponse;