import { DashboardGraphQLRegisterMobileVerifyResponseFailure, DashboardGraphQLRegisterMobileVerifyResponseSuccess } from './index';
export type DashboardGraphQLRegisterMobileVerifyResponse =
  | DashboardGraphQLRegisterMobileVerifyResponseFailure
  | DashboardGraphQLRegisterMobileVerifyResponseSuccess;