import { DashboardGraphQLMerchantModularOnboardingDetailsFailureResponse, DashboardGraphQLMerchantModularOnboardingDetailsSuccessResponse } from './index';
export type DashboardGraphQLMerchantModularOnboardingDetailsResponse =
  | DashboardGraphQLMerchantModularOnboardingDetailsFailureResponse
  | DashboardGraphQLMerchantModularOnboardingDetailsSuccessResponse;