import { DashboardGraphQLMerchantWebsiteVerificationFailureResponse, DashboardGraphQLMerchantWebsiteVerificationSuccessResponse } from './index';
export type DashboardGraphQLMerchantWebsiteVerificationResponse =
  | DashboardGraphQLMerchantWebsiteVerificationFailureResponse
  | DashboardGraphQLMerchantWebsiteVerificationSuccessResponse;