import { DashboardGraphQLMerchantInstrumentCancelRequestMutationFailureResponse, DashboardGraphQLMerchantInstrumentCancelRequestMutationSucessResponse } from './index';
export type DashboardGraphQLMerchantInstrumentCancelRequestMutationResponse =
  | DashboardGraphQLMerchantInstrumentCancelRequestMutationFailureResponse
  | DashboardGraphQLMerchantInstrumentCancelRequestMutationSucessResponse;