export enum DashboardGraphQLMerchantMonthlyRevenueEnum {
  FIFTY_LAKHS_TO_ONE_CRORE = 'FIFTY_LAKHS_TO_ONE_CRORE',
  FIVE_LACS_TO_TWENTY_FIVE_LAKHS = 'FIVE_LACS_TO_TWENTY_FIVE_LAKHS',
  LESS_THAN_FIVE_LAKHS = 'LESS_THAN_FIVE_LAKHS',
  MORE_THAN_ONE_CRORE = 'MORE_THAN_ONE_CRORE',
  NOT_PROCESSING = 'NOT_PROCESSING',
  TWENTY_FIVE_LAKHS_TO_FIFTY_LAKHS = 'TWENTY_FIVE_LAKHS_TO_FIFTY_LAKHS',
}