export enum DashboardGraphQLRegisterMerchantErrorEnum {
  BAD_REQUEST_CONTACT_MOBILE_ALREADY_EXISTS = 'BAD_REQUEST_CONTACT_MOBILE_ALREADY_EXISTS',
  BAD_REQUEST_MAXIMUM_SMS_LIMIT_REACHED = 'BAD_REQUEST_MAXIMUM_SMS_LIMIT_REACHED',
}