import { DashboardGraphQLMerchantPolicyEmptyPreviewResponse, DashboardGraphQLMerchantPolicyPreviewFailureResponse, DashboardGraphQLMerchantPolicyPreviewSuccessResponse } from './index';
export type DashboardGraphQLMerchantPolicyPreviewResponse =
  | DashboardGraphQLMerchantPolicyEmptyPreviewResponse
  | DashboardGraphQLMerchantPolicyPreviewFailureResponse
  | DashboardGraphQLMerchantPolicyPreviewSuccessResponse;