export enum DashboardGraphQLAadhaarOtpDigilockerErrorEnum {
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  INCORRECT_OTP = 'INCORRECT_OTP',
  INVALID_INPUT_DETAILS = 'INVALID_INPUT_DETAILS',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  NO_PROVIDER_ERROR = 'NO_PROVIDER_ERROR',
}