export enum DashboardGraphQLSalesMerchantActivationStatusEnum {
  ACTIVATED = 'ACTIVATED',
  KYC_QUALIFIED_STB = 'KYC_QUALIFIED_STB',
  NEEDS_CLARIFICATION = 'NEEDS_CLARIFICATION',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
}