import { DashboardGraphQLMoney, DashboardGraphQLMaybe, DashboardGraphQLMerchantBankingAccount, DashboardGraphQLScalars, DashboardGraphQLUser, DashboardGraphQLPayoutDate, DashboardGraphQLPayoutFee, DashboardGraphQLMerchantContactFundAccount, DashboardGraphQLPayoutInternalStatusEnum, DashboardGraphQLPayoutModeEnum, DashboardGraphQLPayoutSource, DashboardGraphQLPayoutStatusEnum, DashboardGraphQLTransaction, DashboardGraphQLPayoutWorkflow } from './index';
export type DashboardGraphQLPayout = {
  __typename?: 'DashboardGraphQLPayout';
  amount: DashboardGraphQLMoney;
  bankingAccount?: DashboardGraphQLMaybe<DashboardGraphQLMerchantBankingAccount>;
  batchId?: DashboardGraphQLMaybe<DashboardGraphQLScalars['String']>;
  cancelledBy?: DashboardGraphQLMaybe<DashboardGraphQLUser>;
  dates?: DashboardGraphQLMaybe<DashboardGraphQLPayoutDate>;
  failureReason?: DashboardGraphQLMaybe<DashboardGraphQLScalars['String']>;
  fee?: DashboardGraphQLMaybe<DashboardGraphQLPayoutFee>;
  fundAccount?: DashboardGraphQLMaybe<DashboardGraphQLMerchantContactFundAccount>;
  id: DashboardGraphQLScalars['ID'];
  internalStatus?: DashboardGraphQLMaybe<DashboardGraphQLPayoutInternalStatusEnum>;
  isPendingOnMe: DashboardGraphQLScalars['Boolean'];
  mode: DashboardGraphQLPayoutModeEnum;
  narration?: DashboardGraphQLMaybe<DashboardGraphQLScalars['String']>;
  notes?: DashboardGraphQLMaybe<DashboardGraphQLScalars['JSONObject']>;
  pendingReason?: DashboardGraphQLMaybe<DashboardGraphQLScalars['String']>;
  purpose: DashboardGraphQLScalars['String'];
  referenceId?: DashboardGraphQLMaybe<DashboardGraphQLScalars['String']>;
  remark?: DashboardGraphQLMaybe<DashboardGraphQLScalars['String']>;
  sources: Array<DashboardGraphQLPayoutSource>;
  status: DashboardGraphQLPayoutStatusEnum;
  statusDetails?: DashboardGraphQLMaybe<DashboardGraphQLScalars['JSONObject']>;
  tax?: DashboardGraphQLMaybe<DashboardGraphQLMoney>;
  transaction?: DashboardGraphQLMaybe<DashboardGraphQLTransaction>;
  user?: DashboardGraphQLMaybe<DashboardGraphQLUser>;
  utr?: DashboardGraphQLMaybe<DashboardGraphQLScalars['String']>;
  workflow?: DashboardGraphQLMaybe<DashboardGraphQLPayoutWorkflow>;
};