import { DashboardGraphQLMerchantSendMobileOtpResponseFailure, DashboardGraphQLMerchantSendMobileOtpResponseSuccess } from './index';
export type DashboardGraphQLMerchantSendMobileOtpResponse =
  | DashboardGraphQLMerchantSendMobileOtpResponseFailure
  | DashboardGraphQLMerchantSendMobileOtpResponseSuccess;