import { DashboardGraphQLMerchantSupportDetailsFailureResponse, DashboardGraphQLMerchantSupportDetailsSuccessResponse } from './index';
export type DashboardGraphQLMerchantSupportDetailsResponse =
  | DashboardGraphQLMerchantSupportDetailsFailureResponse
  | DashboardGraphQLMerchantSupportDetailsSuccessResponse;