export enum DashboardGraphQLPaymentsWidgetTypeEnum {
  ACCEPT_PAYMENTS = 'ACCEPT_PAYMENTS',
  ONBOARDING_CARD = 'ONBOARDING_CARD',
  PAYMENT_ANALYTICS = 'PAYMENT_ANALYTICS',
  PAYMENT_HANDLE = 'PAYMENT_HANDLE',
  RECENT_TRANSACTIONS = 'RECENT_TRANSACTIONS',
  SETTLEMENTS = 'SETTLEMENTS',
}