import { DashboardGraphQLMerchantInstrumentReInitiateFailureResponse, DashboardGraphQLMerchantInstrumentReInitiateSuccessResponse } from './index';
export type DashboardGraphQLMerchantInstrumentReInitiateResponse =
  | DashboardGraphQLMerchantInstrumentReInitiateFailureResponse
  | DashboardGraphQLMerchantInstrumentReInitiateSuccessResponse;