import { DashboardGraphQLMerchantContactEmailOtpSendFailureResponse, DashboardGraphQLMerchantContactEmailOtpSendSuccessResponse } from './index';
export type DashboardGraphQLMerchantContactEmailOtpSendResponse =
  | DashboardGraphQLMerchantContactEmailOtpSendFailureResponse
  | DashboardGraphQLMerchantContactEmailOtpSendSuccessResponse;