export enum DashboardGraphQLOnboardingPaymentStatusEnum {
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  CREATED = 'CREATED',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  UNINITIALIZED = 'UNINITIALIZED',
}