import { DashboardGraphQLAadhaarDigilockerRedirectionUrlFailureResponse, DashboardGraphQLAadhaarDigilockerRedirectionUrlSuccessResponse } from './index';
export type DashboardGraphQLAadhaarDigilockerRedirectionUrlResponse =
  | DashboardGraphQLAadhaarDigilockerRedirectionUrlFailureResponse
  | DashboardGraphQLAadhaarDigilockerRedirectionUrlSuccessResponse;