import { DashboardGraphQLInputMaybe, DashboardGraphQLMerchantDocumentInputField } from './index';
export type DashboardGraphQLMerchantDocumentInput = {
  aadharBack?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  aadharFront?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  affiliationCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  amfiCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  ayushCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  bankStatement?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  bankVerificationLetter?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  barCouncilCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  bbpsDocument?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  bisCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  boardResolutionLetter?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  brandTieUpDocument?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  businessCorrespondentDocument?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  businessPan?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  businessRegistration?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  cancelledCheque?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  cancelledChequeVideo?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  copywriteLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  cpvReport?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  dealershipRightsCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  dgcaCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  domainOwnershipDocument?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  dotCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  driverLicenseBack?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  driverLicenseFront?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  epfSchemeCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  fdaCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  fdaLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  ffmcLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  form8a?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  form10ac?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  form12a?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  form80g?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  form2020b2121b?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  fssaiCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  fssaiLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  giaCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  giiCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  govtAuthorisationLetter?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  gstCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  iataCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  iatoLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  iecLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  invoice?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  irctcAgentAgreement?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  irdaCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  irdaiRegistrationCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  legalOpinionDocument?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  liquorLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  manufacturingLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  merchantServiceAgreement?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  mmtcPampLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  msmeCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  msoDocument?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  nationalHousingBankCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  nbfcRegistrationCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  passportBack?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  passportFront?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  pciDssCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  personalPan?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  /**
   * pescoLicense is deprecated use pesoLicense instead,
   * not deprecating using @deprecate because in type input
   * deprecation does not generate types for the deprecated
   * input field
   */
  pescoLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  pesoLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  pgiCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  pharmacyDrugLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  pmWaniCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  ppiLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  proofOfProfession?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  rbiCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  reraLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  resellerAgreement?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  safegoldPartnershipDocument?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  sebiRegistrationCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  shopEstablishmentCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  shopFront?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  shopInterior?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  slaAmfiCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  slaDealershipAgreement?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  slaDocument?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  slaFfmcLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  slaIataCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  slaIrdaiRegistrationCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  slaNbfcRegistrationCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  slaSebiRegistrationCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  tradeLicense?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  traiCertificate?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  undertaking?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  undertakingDocument?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  voterIdBack?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
  voterIdFront?: DashboardGraphQLInputMaybe<DashboardGraphQLMerchantDocumentInputField>;
};