import { DashboardGraphQLAadhaarDigilockerOtpVerifyFailureResponse, DashboardGraphQLAadhaarDigilockerOtpVerifySuccessResponse } from './index';
export type DashboardGraphQLAadhaarDigilockerOtpVerifyResponse =
  | DashboardGraphQLAadhaarDigilockerOtpVerifyFailureResponse
  | DashboardGraphQLAadhaarDigilockerOtpVerifySuccessResponse;