import { DashboardGraphQLAadhaarDigilockerOtpFailureResponse, DashboardGraphQLAadhaarDigilockerOtpSuccessResponse } from './index';
export type DashboardGraphQLAadhaarDigilockerOtpResponse =
  | DashboardGraphQLAadhaarDigilockerOtpFailureResponse
  | DashboardGraphQLAadhaarDigilockerOtpSuccessResponse;