import { DashboardGraphQLMerchantKycPartnerAccessUpdateFailureResponse, DashboardGraphQLMerchantKycPartnerAccessUpdateSuccessResponse } from './index';
export type DashboardGraphQLMerchantKycPartnerAccessStatusUpdateResponse =
  | DashboardGraphQLMerchantKycPartnerAccessUpdateFailureResponse
  | DashboardGraphQLMerchantKycPartnerAccessUpdateSuccessResponse;