export enum DashboardGraphQLUserOtpVerifyErrorTypeEnum {
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
  INVALID_OTP = 'INVALID_OTP',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  LOGIN_UNAUTHENTICATED = 'LOGIN_UNAUTHENTICATED',
  VALID_RESPONSE = 'VALID_RESPONSE',
}