import { DashboardGraphQLMerchantSelfServeWorkflowStatusFailureResponse, DashboardGraphQLMerchantSelfServeWorkflowStatusSuccessResponse } from './index';
export type DashboardGraphQLMerchantSelfServeWorkflowStatusResponse =
  | DashboardGraphQLMerchantSelfServeWorkflowStatusFailureResponse
  | DashboardGraphQLMerchantSelfServeWorkflowStatusSuccessResponse;