import { DashboardGraphQLMerchantPolicyPublishFailureResponse, DashboardGraphQLMerchantPolicyPublishSuccessResponse } from './index';
export type DashboardGraphQLMerchantPolicyPublishResponse =
  | DashboardGraphQLMerchantPolicyPublishFailureResponse
  | DashboardGraphQLMerchantPolicyPublishSuccessResponse;