export enum DashboardGraphQLSetEmailPasswordEnum {
  BAD_REQUEST_PASSWORD_ALREADY_SET = 'BAD_REQUEST_PASSWORD_ALREADY_SET',
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
}