export enum DashboardGraphQLVendorPaymentStatusEnum {
  CANCELLED = 'CANCELLED',
  DRAFT = 'DRAFT',
  IN_APPROVAL = 'IN_APPROVAL',
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PROCESSING = 'PROCESSING',
  REJECTED = 'REJECTED',
  SCHEDULED = 'SCHEDULED',
  UNPAID = 'UNPAID',
}