export enum DashboardGraphQLUserSignupCampaignEnum {
  ASSISTED_ONBOARDING = 'ASSISTED_ONBOARDING',
  EASY_ONBOARDING = 'EASY_ONBOARDING',
  I18N_MY_SIGNUP = 'I18N_MY_SIGNUP',
  /** @deprecated use I18N_MY_SIGNUP instead, this is deprecated */
  INTERNATIONAL = 'INTERNATIONAL',
  P2PM_ONBOARDING = 'P2PM_ONBOARDING',
  PHANTOM_ONBOARDING = 'PHANTOM_ONBOARDING',
}