import { DashboardGraphQLMerchantPaymentHandleEncryptedAmountFailureResponse, DashboardGraphQLMerchantPaymentHandleEncryptedAmountSuccessResponse } from './index';
export type DashboardGraphQLMerchantPaymentHandleEncryptedAmountResponse =
  | DashboardGraphQLMerchantPaymentHandleEncryptedAmountFailureResponse
  | DashboardGraphQLMerchantPaymentHandleEncryptedAmountSuccessResponse;