export enum DashboardGraphQLAadhaarCaptchaVerifyErrorTypeEnum {
  EMPTY_RESPONSE = 'EMPTY_RESPONSE',
  INVALID_AADHAAR_NUMBER = 'INVALID_AADHAAR_NUMBER',
  INVALID_CAPTCHA = 'INVALID_CAPTCHA',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  INVALID_SESSION_ID = 'INVALID_SESSION_ID',
  MOBILE_NOT_LINKED = 'MOBILE_NOT_LINKED',
  NO_PROVIDER_ERROR = 'NO_PROVIDER_ERROR',
  TIME_OUT_ERROR = 'TIME_OUT_ERROR',
  UIDAI_DOWNTIME_ERROR = 'UIDAI_DOWNTIME_ERROR',
  VALID_RESPONSE = 'VALID_RESPONSE',
}