export enum DashboardGraphQLPayoutsQueuedReasonEnum {
  BENEFICIARY_BANK_DOWN = 'BENEFICIARY_BANK_DOWN',
  LOW_BALANCE = 'LOW_BALANCE',
  NEFT_LIMIT_EXHAUSTED = 'NEFT_LIMIT_EXHAUSTED',
  NEFT_WINDOW_CLOSED = 'NEFT_WINDOW_CLOSED',
  NPCI_DOWN = 'NPCI_DOWN',
}