import { DashboardGraphQLMerchantActivationEscalationsBreached, DashboardGraphQLMerchantActivationEscalationsNotBreached } from './index';
export type DashboardGraphQLMerchantEscalations =
  | DashboardGraphQLMerchantActivationEscalationsBreached
  | DashboardGraphQLMerchantActivationEscalationsNotBreached;