import { DashboardGraphQLPayoutsScheduledSummaryAllTime, DashboardGraphQLPayoutsScheduledSummaryNextMonth, DashboardGraphQLPayoutsScheduledSummaryNextTwoDays, DashboardGraphQLPayoutsScheduledSummaryNextWeek, DashboardGraphQLPayoutsScheduledSummaryToday } from './index';
export type DashboardGraphQLPayoutsScheduledSummary =
  | DashboardGraphQLPayoutsScheduledSummaryAllTime
  | DashboardGraphQLPayoutsScheduledSummaryNextMonth
  | DashboardGraphQLPayoutsScheduledSummaryNextTwoDays
  | DashboardGraphQLPayoutsScheduledSummaryNextWeek
  | DashboardGraphQLPayoutsScheduledSummaryToday;