import { DashboardGraphQLMerchantOnboardingQuestionDetailsFailureResponse, DashboardGraphQLMerchantOnboardingQuestionDetailsSuccessResponse } from './index';
export type DashboardGraphQLMerchantOnboardingQuestionDetailsResponse =
  | DashboardGraphQLMerchantOnboardingQuestionDetailsFailureResponse
  | DashboardGraphQLMerchantOnboardingQuestionDetailsSuccessResponse;