import { DashboardGraphQLMerchantWebsiteDocumentUploadFailureResponse, DashboardGraphQLMerchantWebsiteDocumentUploadSuccessResponse } from './index';
export type DashboardGraphQLMerchantWebsiteDocumentUploadResponse =
  | DashboardGraphQLMerchantWebsiteDocumentUploadFailureResponse
  | DashboardGraphQLMerchantWebsiteDocumentUploadSuccessResponse;