import { DashboardGraphQLTwoFactorAddMobileOtpVerifyErrorResponse, DashboardGraphQLTwoFactorAddMobileOtpVerifySuccessResponse } from './index';
export type DashboardGraphQLTwoFactorAddMobileOtpVerifyResponse =
  | DashboardGraphQLTwoFactorAddMobileOtpVerifyErrorResponse
  | DashboardGraphQLTwoFactorAddMobileOtpVerifySuccessResponse;