<?php

use Carbon\Carbon;

return [
    'testIndusindDebitEmiSuccessRecon' => [
        'EMI ID'                            => 'Klqebu9VYpipL6',
        'IBL_Txn_Ref_Number'                => '261129221735483202',
        'IBL_Loan_E_Agreement_Number'       => '2000885110',
        'Card Hash'                         => 'nan',
        'Loan Amount'                       => 15000,
        'EMI Amount'                        => '5133',
        'Tx Time'                           => '29/11/2022',
        'Issuer'                            => 'Indusind Debit',
        'RRN'                               => 'nan',
        'Auth Code'                         => 'nan',
        'Tx Amount'                         => 15000,
        'EMI_Offer'                         => '3 Months',
        'Manufacturer'                      => 'nan',
        'Acquirer'                          => 'nan',
        'MID'                               => 'nan',
        'TID'                               => 'nan',
        'Settlement Time'                   => '29/11/2022',
        'Customer Processing Fee'           => 'nan',
        'Customer Processing Amount (Rs.)'  => 'nan',
        'Other Discount %'                  => 'nan',
        'Other discount Amount'             => 'nan',
        'Interest Rate'                     => '16',
        'Tx Status'                         => 'Settled',
        'Product Category'                  => 'nan',
        'Product Sub-Category 1'            => 'nan',
        'Product Sub-Category 2'            => 'nan',
        'Model Name'                        => 'nan',
        'Discount / Cashback %'             => '0',
        'Discount / Cashback Amount'        => '0',
        'Is New Model'                      => 'nan',
        'Offers / Additional Cashbacks'     => 'nan',
        'Reward Point'                      => 'nan',
        'Merchant Name'                     => 'Test brand',
        'Address1'                          => 'nan',
        'Store City'                        => 'nan',
        'Store State'                       => 'nan',
        'Card Pan'                          => 'nan',
        'Payments ref. No'                  => 'Klqebu9VYpipL6',
    ],
];
