<?php

use EE\Error\ErrorCode;
use EE\Error\PublicErrorCode;
use EE\Error\PublicErrorDescription;

return [
    'testPayment' => [
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'method' => 'wallet',
        'wallet' => 'payzapp',
        'status' => 'captured',
        'amount_authorized' => 50000,
        'amount_refunded' => 0,
        'refund_status' => null,
        'currency' => 'INR',
        'description' => 'random description',
        'error_code' => null,
        'error_description' => null,
        'email' => 'a@b.com',
        'contact' => '9918899029',
        'notes' => [
            'merchant_order_id' => 'random order id',
        ],
        'gateway' => 'wallet_payzapp',
        'terminal_id' => '100PayzappTmnl',
        'signed' => false,
        'verified' => null,
        'entity' => 'payment',
    ],

    'testTransactionAfterAuthorize' => [
        'type' => 'payment',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 1432,
        'pricing_rule_id' => '1zE3CYqf1zbyrD',
        'debit' => 0,
        'credit' => 48568,
        'currency' => 'INR',
        'balance' => 0,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'escrow_balance' => 1048568,
        'channel' => 'kotak',
        'settled' => false,
        'settled_at' => null,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testTransactionAfterCapture' => [
        'type' => 'payment',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 1432,
        'debit' => 0,
        'credit' => 48568,
        'currency' => 'INR',
        'balance' => 1048568,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'escrow_balance' => 1048568,
        'channel' => 'kotak',
        'settled' => false,
//        'settled_at' => 1437589800,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testPaymentPayzappEntity' => [
        //'id' => '1',
//        'payment_id' => '4W2hONlUrw0Pka',
        'action' => 'authorize',
        'amount' => 50000,
        'wallet' => 'payzapp',
        'received' => true,
        'email' => 'a@b.com',
        'contact' => '9918899029',
//        'gateway_merchant_id' => '29837498237498723433',
//        'gateway_payment_id' => 'hr8mncd5bqygokfs14w29',
//        'gateway_payment_id_2' => '65657627',
        'gateway_refund_id' => null,
        'response_code' => '000',
        'response_description' => 'SUCCESS',
        'status_code' => null,
        'error_message' => null,
//        'reference1' => '201512091604066125oW33aC8:2jG2cS5gT9',
        'reference2' => '0',
        'date' => null,
        'refund_id' => null,
        'entity' => 'wallet',
        'admin' => true,
    ],
];