<?php

namespace RZP\Models\Batch\Processor;

/*
 * IrctcRefund can process both c type and R type refunds. This class is created to support both old and
 * new Irctc recon flow.
 * 1. C type refunds file is processed through IrctcRefund
 * Delta refunds are processed just like R type refunds
 */

class IrctcDeltaRefund extends IrctcRefund
{
    protected $delimiter = ',';

    protected function processEntry(array &$entry)
    {
        parent::processEntry($entry); // TODO: Change the autogenerated stub
    }

    protected function postProcessEntries(array &$entries)
    {
        parent::postProcessEntries($entries); // TODO: Change the autogenerated stub
    }
}
