<?php

namespace RZP\Gateway\Base\ErrorCodes\Cards;

use RZP\Gateway\Base;

class ErrorCodeDescriptions extends Base\ErrorCodes\BaseCodeDescriptions
{
    public static $errorDescriptionMap = [
        '01' => 'Refer to Issuer',
        '02' => 'Refer to Issuer, special',
        '03' => 'No Merchant',
        '04' => 'Pick Up Card',
        '05' => 'Do Not Honour',
        '06' => 'Error',
        '07' => 'Pick Up Card, Special',
        '08' => 'Honour With Identification',
        '09' => 'Request In Progress',
        '10' => 'Approved For Partial Amount',
        '11' => 'Approved, VIP',
        '12' => 'Invalid Transaction',
        '13' => 'Invalid Amount',
        '14' => 'Invalid Card Number',
        '15' => 'No Issuer',
        '16' => 'Approved, Update Track 3',
        '17' => 'Customer cancellation',
        '19' => 'Re-enter Last Transaction',
        '20' => 'Invalid response',
        '21' => 'No action taken (unable to back out prior transaction)',
        '22' => 'Suspected Malfunction',
        '23' => 'Unacceptable Transaction Fee',
        '25' => 'Unable to Locate Record On File',
        '28' => 'File is temporarily unavailable',
        '30' => 'Format Error',
        '31' => 'Bank Not Supported By Switch',
        '33' => 'Expired Card, Capture',
        '34' => 'Suspected Fraud, Retain Card',
        '35' => 'Card Acceptor, Contact Acquirer, Retain Card',
        '36' => 'Restricted Card, Retain Card',
        '37' => 'Contact Acquirer Security Department, Retain Card',
        '39' => 'No Credit Account',
        '41' => 'Lost Card',
        '42' => 'No Universal Account',
        '43' => 'Stolen Card',
        '51' => 'Insufficient Funds',
        '52' => 'No checking account',
        '53' => 'No savings account',
        '54' => 'Expired Card',
        '55' => 'Incorrect PIN',
        '56' => 'No Card Record',
        '57' => 'Function Not Permitted to Cardholder',
        '58' => 'Transaction not allowed at terminal',
        '59' => 'Suspected Fraud',
        '60' => 'DECLINED (contact acquirer)',
        '61' => 'Activity amount limit exceeded',
        '62' => 'Restricted Card',
        '63' => 'Security Violation',
        '64' => 'Original Amount Incorrect',
        '65' => 'Activity count limit exceeded',
        '66' => 'Acceptor Contact Acquirer, Security',
        '67' => 'Capture Card',
        '68' => 'Response received too late',
        '69' => 'Cardholder/Issuer Not Enrolled with 3D Secure',
        '70' => '3D Secure Authentication Failure',
        '75' => 'Allowable number of PIN-entry tries exceeded',
        '76' => 'Unable to locate previous message (no match on Retrieval Reference number)',
        '77' => 'Previous message located for a repeat or reversal, but repeat or reversal data are
        inconsistent with original message',
        '78' => '’Blocked, first used’—The transaction is from a new cardholder, and the card has not been
        properly unblocked.',
        '80' => 'Visa transactions: credit issuer unavailable. Private label and check acceptance: Invalid
        date',
        '81' => 'PIN cryptographic error found (error found by VIC security module during PIN decryption)',
        '82' => 'CVV Validation Error',
        '83' => 'Unable to verify PIN',
        '85' => 'No reason to decline a request for account number verification, address verification, CVV2
        verification, or a credit voucher or merchandise return',
        '90' => 'Cutoff In Progress',
        '91' => 'Card Issuer Unavailable',
        '92' => 'Unable To Route Transaction',
        '93' => 'Cannot Complete, Violation Of The Law',
        '94' => 'Duplicate Transaction',
        '95' => 'Reconcile error',
        '96' => 'System Error',
        'B1' => 'Surcharge amount not permitted on Visa cards (U.S. acquirers only)',
        'N0' => 'Force STIP',
        'N3' => 'Cash service not available',
        'N4' => 'Cashback request exceeds issuer limit',
        'N7' => 'Decline for CVV2 failure',
        'P2' => 'Invalid biller information',
        'P5' => 'PIN Change/Unblock request declined',
        'P6' => 'Unsafe PIN',
        'Q1' => 'Card Authentication failed',
        'R0' => 'Stop Payment Order',
        'R1' => 'Revocation of Authorization Order',
        'R3' => 'Revocation of All Authorizations Order',
        'XA' => 'Forward to issuer',
        'XD' => 'Forward to issuer',
        'Z3' => 'Unable to go online',
    ];
}
