<?php

namespace RZP\Gateway\Base\ErrorCodes\Cards;

use RZP\Gateway\Base;
use RZP\Error\ErrorCode;

class ErrorCodes extends Base\ErrorCodes\BaseCodes
{
    public static $errorCodeMap = [
        '01' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK,
        '02' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_NUMBER_POSSIBLY_INVALID,
        '03' => ErrorCode::GATEWAY_ERROR_REQUEST_ERROR,
        '04' => ErrorCode::BAD_REQUEST_PAYMENT_BLOCKED_DUE_TO_FRAUD,
        '05' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK,
        '06' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK,
        '07' => ErrorCode::BAD_REQUEST_PAYMENT_BLOCKED_DUE_TO_FRAUD,
        //'08' => 'Honour With Identification',
        '09' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_NUMBER_NOT_LEGITIMATE,
        '10' => ErrorCode::BAD_REQUEST_PAYMENT_PARTIAL_AMOUNT_APPROVED,
//        '11' => 'Approved, VIP',
        '12' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_FORMAT,
        '13' => ErrorCode::BAD_REQUEST_INVALID_TRANSACTION_AMOUNT,
        '14' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_NUMBER_POSSIBLY_INVALID,
        '15' => ErrorCode::GATEWAY_ERROR_BANK_NOT_SUPPORTED_BY_SWITCH,
//        '16' => 'Approved, Update Track 3',
        '19' => ErrorCode::GATEWAY_ERROR_INVALID_RESPONSE,
        '21' => ErrorCode::GATEWAY_ERROR_REQUEST_ERROR,
        '22' => ErrorCode::BAD_REQUEST_PAYMENT_POSSIBLE_FRAUD,
        '23' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '25' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID,
        '30' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_FORMAT,
        '31' => ErrorCode::GATEWAY_ERROR_BANK_NOT_SUPPORTED_BY_SWITCH,
        '33' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_EXPIRED,
        '34' => ErrorCode::BAD_REQUEST_PAYMENT_POSSIBLE_FRAUD,
        '35' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK, // GATEWAY_ERROR_TRANSACTION_DECLINED
        '36' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_HOLDER_NOT_PERMITTED_TXN, // GATEWAY_ERROR_TRANSACTION_DECLINED
        '37' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK, // GATEWAY_ERROR_TRANSACTION_DECLINED
        '39' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_ACCOUNT,
        '41' => ErrorCode::BAD_REQUEST_CARD_STOLEN_OR_LOST, // GATEWAY_ERROR_TRANSACTION_DECLINED
        '42' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_ACCOUNT,
        '43' => ErrorCode::BAD_REQUEST_CARD_STOLEN_OR_LOST, // GATEWAY_ERROR_TRANSACTION_DECLINED
        '51' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INSUFFICIENT_BALANCE,
        '54' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_EXPIRED,
        '56' => ErrorCode::GATEWAY_ERROR_CARD_INVALID_NUMBER,
        '57' => ErrorCode::BAD_REQUEST_ACTION_NOT_APPROVED,
        '59' => ErrorCode::BAD_REQUEST_PAYMENT_POSSIBLE_FRAUD,
        '60' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK,
        '62' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_HOLDER_NOT_PERMITTED_TXN,
        '63' => ErrorCode::BAD_REQUEST_PAYMENT_BLOCKED_DUE_TO_FRAUD,
        '64' => ErrorCode::BAD_REQUEST_TRANSACTION_AMOUT_GREATER_THAN_REGISTERED_AMOUNT, // GATEWAY_ERROR_AMOUNT_TAMPERED
        '66' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK,
        '67' => ErrorCode::BAD_REQUEST_PAYMENT_POSSIBLE_FRAUD,  // BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK
        '82' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INVALID_CVV,
        '90' => ErrorCode::GATEWAY_ERROR_PROCESSING_DECLINED, // BAD_REQUEST_UNABLE_TO_AUTHORIZE_PAYMENT
        '91' => ErrorCode::BAD_REQUEST_CARD_ISSUING_BANK_UNAVAILABLE, // should be GATEWAY_ERROR_CARD_ISSUING_BANK_UNAVAILABLE
        '92' => ErrorCode::BAD_REQUEST_OPERATION_NOT_ALLOWED_FOR_TEST_ACCOUNT,
        '93' => ErrorCode::BAD_REQUEST_PAYMENT_BLOCKED_DUE_TO_FRAUD,
        '94' => ErrorCode::GATEWAY_ERROR_PAYMENT_DUPLICATE_REQUEST,
        '96' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
    ];
}