<?php

namespace RZP\Gateway\Base\ErrorCodes\Cards;

use RZP\Gateway\Base;
use RZP\Error\ErrorCode;

class ErrorCodes extends Base\ErrorCodes\BaseCodes
{
    public static $errorCodeMap = [
        '01' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK,
        '02' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK,
        '03' => ErrorCode::GATEWAY_ERROR_INVALID_MERCHANT,
        '04' => ErrorCode::BAD_REQUEST_CARD_STOLEN_OR_LOST,
        '05' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK,
        '06' => ErrorCode::GATEWAY_ERROR_INTERNAL_SERVER_ERROR,
        '07' => ErrorCode::BAD_REQUEST_PAYMENT_BLOCKED_DUE_TO_FRAUD,
        //'08' => 'Honour With Identification',
        '09' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_NUMBER_NOT_LEGITIMATE,
        '10' => ErrorCode::BAD_REQUEST_PAYMENT_PARTIAL_AMOUNT_APPROVED,
        '11' => ErrorCode::GATEWAY_ERROR_APPROVED_VIP,
        '12' => ErrorCode::GATEWAY_ERROR_INVALID_TRANSACTION,
        '13' => ErrorCode::SERVER_ERROR_INVALID_ARGUMENT,
        '14' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_NUMBER_POSSIBLY_INVALID,
        '15' => ErrorCode::BAD_REQUEST_CARD_ISSUER_INVALID,
//        '16' => 'Approved, Update Track 3',
        '17' => ErrorCode::BAD_REQUEST_PAYMENT_CANCELLED_BY_USER,
        '19' => ErrorCode::GATEWAY_ERROR_TRANSACTION_NOT_PRESENT,
        '20' => ErrorCode::GATEWAY_ERROR_INVALID_RESPONSE,
        '21' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK,
        '22' => ErrorCode::GATEWAY_ERROR_ISSUER_DOWN,
        '23' => ErrorCode::GATEWAY_ERROR_UNACCEPTABLE_TRANSACTION_FEE,
        '25' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID,
        '28' => ErrorCode::GATEWAY_ERROR_FILE_ERROR,
        '30' => ErrorCode::SERVER_ERROR_INVALID_FORMAT,
        '31' => ErrorCode::BAD_REQUEST_CARD_PAYMENT_DECLINED_MODE_NOT_SUPPORTED,
        '33' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_EXPIRED,
        '34' => ErrorCode::BAD_REQUEST_PAYMENT_POSSIBLE_FRAUD,
        '35' => ErrorCode::BAD_REQUEST_CARD_STOLEN_OR_LOST, // GATEWAY_ERROR_TRANSACTION_DECLINED
        '36' => ErrorCode::BAD_REQUEST_CARD_STOLEN_OR_LOST, // GATEWAY_ERROR_TRANSACTION_DECLINED
        '37' => ErrorCode::BAD_REQUEST_CARD_STOLEN_OR_LOST, // GATEWAY_ERROR_TRANSACTION_DECLINED
        '39' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_ACCOUNT,
        '41' => ErrorCode::BAD_REQUEST_CARD_STOLEN_OR_LOST, // GATEWAY_ERROR_TRANSACTION_DECLINED
        '42' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_ACCOUNT,
        '43' => ErrorCode::BAD_REQUEST_CARD_STOLEN_OR_LOST, // GATEWAY_ERROR_TRANSACTION_DECLINED
        '51' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INSUFFICIENT_BALANCE,
        '52' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_ACCOUNT,
        '53' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_ACCOUNT,
        '54' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_EXPIRED,
        '55' => ErrorCode::BAD_REQUEST_PAYMENT_PIN_INCORRECT,
        '56' => ErrorCode::BAD_REQUEST_CARD_INVALID_NUMBER,
        '57' => ErrorCode::GATEWAY_ERROR_TRANSACTION_NOT_PERMITTED,
        '58' => ErrorCode::GATEWAY_ERROR_TERMINAL_NOT_ALLOWED,
        '59' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK,
        '60' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK,
        '61' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_WITHDRAWAL_AMOUNT_LIMITS_EXCEEDED,
        '62' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_HOLDER_NOT_PERMITTED_TXN,
        '63' => ErrorCode::BAD_REQUEST_PAYMENT_BLOCKED_DUE_TO_FRAUD,
        '64' => ErrorCode::BAD_REQUEST_TRANSACTION_AMOUT_GREATER_THAN_REGISTERED_AMOUNT, //GATEWAY_ERROR_AMOUNT_TAMPERED
        '65' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_DAILY_WITHDRAWAL_FREQUENCY_LIMITS_EXCEEDED,
        '66' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK,
        '67' => ErrorCode::BAD_REQUEST_CARD_STOLEN_OR_LOST, // BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK
        '68' => ErrorCode::BAD_REQUEST_PAYMENT_NO_RESPONSE_RECEIVED_FROM_BANK,
        '69' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_NOT_ENROLLED_FOR_3DSECURE,
        '70' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_3DSECURE_AUTH_FAILED,
        '75' => ErrorCode::BAD_REQUEST_PAYMENT_PIN_ATTEMPTS_EXCEEDED,
        '76' => ErrorCode::GATEWAY_ERROR_UNABLE_TO_LOCATE_PREVIOUS_RECORD,
        '77' => ErrorCode::SERVER_ERROR_INVALID_ARGUMENT,
        '78' => ErrorCode::BAD_REQUEST_CARD_INACTIVE,
        '80' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_ISSUING_BANK_NOT_PERMITTING_PAYMENT,
        '81' => ErrorCode::GATEWAY_ERROR_PIN_CRYPTOGRAPHY_ERROR,
        '82' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INVALID_CVV,
        '83' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INVALID_PIN,
        '85' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK,
        '90' => ErrorCode::GATEWAY_ERROR_PROCESSING_DECLINED, // BAD_REQUEST_UNABLE_TO_AUTHORIZE_PAYMENT
        '91' => ErrorCode::BAD_REQUEST_CARD_ISSUING_BANK_UNAVAILABLE, // GATEWAY_ERROR_CARD_ISSUING_BANK_UNAVAILABLE
        '92' => ErrorCode::GATEWAY_ERROR_CARD_NETWORK_UNABLE_TO_ROUTE,
        '93' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_HOLDER_NOT_PERMITTED_TXN,
        '94' => ErrorCode::GATEWAY_ERROR_PAYMENT_DUPLICATE_REQUEST,
        '95' => ErrorCode::GATEWAY_ERROR_RECONCILE_ERROR,
        '96' => ErrorCode::GATEWAY_ERROR_CARD_ISSUING_BANK_SYSTEM_ERROR,
        'N3' => ErrorCode::BAD_REQUEST_CARD_ISSUING_BANK_UNAVAILABLE,
        'N4' => ErrorCode::BAD_REQUEST_CASHBACK_EXCEEDS_ISSUER_LIMIT,
        'N7' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INVALID_CVV,
        'P2' => ErrorCode::SERVER_ERROR_INVALID_ARGUMENT,
        'Q1' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_HOLDER_AUTHENTICATION_FAILED,
        'R0' => ErrorCode::BAD_REQUEST_CARDHOLDER_STOPPED_WITHDRAWALS,
        'R1' => ErrorCode::BAD_REQUEST_CARDHOLDER_STOPPED_WITHDRAWALS,
        'R3' => ErrorCode::BAD_REQUEST_CARDHOLDER_STOPPED_WITHDRAWALS,
        'XA' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK,
        'XD' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK,
        'Z3' => ErrorCode::GATEWAY_ERROR_CARD_NETWORK_UNABLE_TO_ROUTE,
    ];
}


