<?php

namespace RZP\Models\Risk;

class RiskCode
{
    const PAYMENT_SUSPECTED_FRAUD_BY_MAXMIND    = 'PAYMENT_SUSPECTED_FRAUD_BY_MAXMIND';

    const PAYMENT_FAILED_DUE_TO_BLOCKED_CARD    = 'PAYMENT_FAILED_DUE_TO_BLOCKED_CARD';

    const PAYMENT_DECLINED_DUE_TO_RISK          = 'PAYMENT_DECLINED_DUE_TO_RISK';

    const PAYMENT_FAILED_DUE_TO_STOLEN_CARD     = 'PAYMENT_FAILED_DUE_TO_STOLEN_CARD';
}
