name: Package installer with caching

inputs:
  github_access_token:
    required: true

runs:
  using: composite
  steps:
    - name: Use Node v18.12.1
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1

    - name: Package installer cache setup
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ./node_modules
          ./web/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pnpm config set unsafe-perm true
        HUSKY=0 pnpm i --ignore-scripts --frozen-lockfile # Automatically installs modules in all packages too
      shell: bash
      env:
        GITHUB_ACCESS_TOKEN: ${{ inputs.github_access_token }}
