export const TICKET_STATUS_LABELS = {
  ACTIVE: 'Active',
  BEING_PROCESSED: 'Being Processed',
  IN_PROGRESS: 'In Progress',
  RESOLVED: 'Resolved',
  CLOSED: 'Closed',
  ACTION_REQUIRED: 'Action required',
  DELAYED: 'Delayed',
  REJECTED: 'Rejected',
  FAILED: 'Failed',
  ESCALATED: 'Escalated',
};
export const statuses = {
  '2': {
    name: TICKET_STATUS_LABELS.ACTIVE,
    class: 'active',
  },
  '3': {
    name: TICKET_STATUS_LABELS.IN_PROGRESS,
    class: 'pending',
  },
  '4': {
    name: TICKET_STATUS_LABELS.RESOLVED,
    class: 'active',
  },
  '5': {
    name: TICKET_STATUS_LABELS.CLOSED,
    class: 'danger',
  },
  '6': {
    name: TICKET_STATUS_LABELS.ACTION_REQUIRED,
    class: 'info',
  },
  '8': {
    name: TICKET_STATUS_LABELS.IN_PROGRESS,
    class: 'pending',
  },
  '9': {
    name: TICKET_STATUS_LABELS.IN_PROGRESS,
    class: 'pending',
  },
  '10': {
    name: TICKET_STATUS_LABELS.IN_PROGRESS,
    class: 'pending',
  },
  '11': {
    name: TICKET_STATUS_LABELS.IN_PROGRESS,
    class: 'pending',
  },
  '14': {
    name: TICKET_STATUS_LABELS.IN_PROGRESS,
    class: 'pending',
  },
  '100': {
    name: 'Loading..',
    class: 'pending',
  },
};

export const cssClassToBadgeVariant = {
  pending: 'notice',
  active: 'positive',
  resolved: 'neutral',
  danger: 'negative',
  info: 'information',
};

export const workflowStatusClass = {
  [TICKET_STATUS_LABELS.BEING_PROCESSED]: 'pending',
  [TICKET_STATUS_LABELS.IN_PROGRESS]: 'pending',
  [TICKET_STATUS_LABELS.ACTIVE]: 'active',
  [TICKET_STATUS_LABELS.RESOLVED]: 'resolved',
  [TICKET_STATUS_LABELS.CLOSED]: 'danger',
  [TICKET_STATUS_LABELS.ACTION_REQUIRED]: 'info',
  [TICKET_STATUS_LABELS.DELAYED]: 'danger',
  [TICKET_STATUS_LABELS.REJECTED]: 'pending',
  [TICKET_STATUS_LABELS.FAILED]: 'danger',
};

export const param_to_qs = (params) => {
  const esc = encodeURIComponent;
  return Object.keys(params)
    .map((k) => `${esc(k)}=${esc(params[k])}`)
    .join('&');
};

export const ACTIVE_TICKETS = [
  {
    cc_emails: [],
    fwd_emails: [],
    reply_cc_emails: [],
    ticket_cc_emails: [],
    fr_escalated: false,
    spam: false,
    email_config_id: 11000002563,
    group_id: 11000003820,
    priority: 3,
    requester_id: 11014824425,
    responder_id: null,
    source: 1,
    company_id: null,
    status: 2,
    subject: '12313123 123 12 123 13 13 123 12312 3',
    association_type: null,
    to_emails: [],
    product_id: null,
    id: 3475092,
    type: null,
    due_by: '2020-07-07T21:18:52Z',
    fr_due_by: '2020-07-07T13:18:52Z',
    is_escalated: false,
    custom_fields: {},
    stats: {
      agent_responded_at: null,
      requester_responded_at: null,
      first_responded_at: null,
      status_updated_at: '2020-07-07T09:18:52Z',
      reopened_at: null,
      resolved_at: null,
      closed_at: null,
      pending_since: null,
    },
    nr_due_by: null,
    nr_escalated: false,
  },
  {
    cc_emails: [],
    fwd_emails: [],
    reply_cc_emails: [],
    ticket_cc_emails: [],
    fr_escalated: false,
    spam: false,
    email_config_id: 11000002563,
    group_id: 11000003820,
    priority: 3,
    requester_id: 11014824425,
    responder_id: null,
    source: 1,
    company_id: null,
    status: 2,
    subject: '12313123 123 12 123 13 13 123 12312 3',
    association_type: null,
    to_emails: [],
    product_id: null,
    id: 3475092,
    type: null,
    due_by: '2020-07-07T21:18:52Z',
    fr_due_by: '2020-07-07T13:18:52Z',
    is_escalated: false,
    custom_fields: {},
    stats: {
      agent_responded_at: null,
      requester_responded_at: null,
      first_responded_at: null,
      status_updated_at: '2020-07-07T09:18:52Z',
      reopened_at: null,
      resolved_at: null,
      closed_at: null,
      pending_since: null,
    },
    nr_due_by: null,
    nr_escalated: false,
  },
  {
    cc_emails: [],
    fwd_emails: [],
    reply_cc_emails: [],
    ticket_cc_emails: [],
    fr_escalated: false,
    spam: false,
    email_config_id: 11000002563,
    group_id: 11000003820,
    priority: 3,
    requester_id: 11014824425,
    responder_id: null,
    source: 1,
    company_id: null,
    status: 2,
    subject: '12313123 123 12 123 13 13 123 12312 3',
    association_type: null,
    to_emails: [],
    product_id: null,
    id: 3475092,
    type: null,
    due_by: '2020-07-07T21:18:52Z',
    fr_due_by: '2020-07-07T13:18:52Z',
    is_escalated: false,
    custom_fields: {},
    stats: {
      agent_responded_at: null,
      requester_responded_at: null,
      first_responded_at: null,
      status_updated_at: '2020-07-07T09:18:52Z',
      reopened_at: null,
      resolved_at: null,
      closed_at: null,
      pending_since: null,
    },
    nr_due_by: null,
    nr_escalated: false,
  },
  {
    cc_emails: [],
    fwd_emails: [],
    reply_cc_emails: [],
    ticket_cc_emails: [],
    fr_escalated: false,
    spam: false,
    email_config_id: 11000002563,
    group_id: 11000003820,
    priority: 3,
    requester_id: 11014824425,
    responder_id: null,
    source: 1,
    company_id: null,
    status: 2,
    subject: '12313123 123 12 123 13 13 123 12312 3',
    association_type: null,
    to_emails: [],
    product_id: null,
    id: 3475092,
    type: null,
    due_by: '2020-07-07T21:18:52Z',
    fr_due_by: '2020-07-07T13:18:52Z',
    is_escalated: false,
    custom_fields: {},
    stats: {
      agent_responded_at: null,
      requester_responded_at: null,
      first_responded_at: null,
      status_updated_at: '2020-07-07T09:18:52Z',
      reopened_at: null,
      resolved_at: null,
      closed_at: null,
      pending_since: null,
    },
    nr_due_by: null,
    nr_escalated: false,
  },
];

export const SAMPLE_TICKET = {
  cc_emails: [],
  fwd_emails: [],
  reply_cc_emails: [],
  ticket_cc_emails: [],
  fr_escalated: false,
  spam: false,
  email_config_id: 11000002563,
  group_id: 11000003820,
  priority: 3,
  requester_id: 11014824425,
  responder_id: null,
  source: 1,
  company_id: null,
  status: 100,
  association_type: null,
  to_emails: [],
  product_id: null,
  id: 'ID',
  type: null,
  due_by: '2020-07-07T21:18:52Z',
  fr_due_by: '2020-07-07T13:18:52Z',
  is_escalated: false,
  subject: 'Settlements are on hold',
  description_text:
    'Your settlements have been put on hold because of some issues with your bank account. We will not be able to process further settlements until the bank account details is updated from your en.. ',
  custom_fields: {},
  stats: {
    agent_responded_at: null,
    requester_responded_at: null,
    first_responded_at: null,
    status_updated_at: '2020-07-07T09:18:52Z',
    reopened_at: null,
    resolved_at: null,
    closed_at: null,
    pending_since: null,
  },
  tags: [],
  nr_due_by: null,
  nr_escalated: false,
};

export const MAX_SIZE_LIMIT = 15 * 1024 * 1024; // 15MB limit
export const MAX_PAGE_SIZE = 100;
export const MAX_CONVERSATION = 100;
export const MIN_TIME_TO_REFRESH = 2 * 60 * 60 * 1000; // 2 hours
export const PRERECORDED_RESPONSES = [
  "I didn't receive a satisfactory response",
  "I haven't received any response yet",
];

export const QUERY_ROUTE_LINK_MERCHANT = '/ticket-support/tickets/merchant';
export const QUERY_REQUEST_ROUTE_LINK__AGENT = '/ticket-support/tickets/agent';

export const QUERY_ROUTE_LINK_MERCHANT_NEW = `/business-settings${QUERY_ROUTE_LINK_MERCHANT}`;
export const QUERY_REQUEST_ROUTE_LINK__AGENT_NEW = `/business-settings${QUERY_REQUEST_ROUTE_LINK__AGENT}`;
