export const statuses = {
  '2': {
    name: 'Active',
    class: 'active',
  },
  '3': {
    name: 'Work In Progress',
    class: 'pending',
  },
  '4': {
    name: 'Resolved',
    class: 'active',
  },
  '5': {
    name: 'Closed',
    class: 'danger',
  },
  '6': {
    name: 'Awaiting Your Reply',
    class: 'info',
  },
  '8': {
    name: 'Work In Progress',
    class: 'pending',
  },
  '9': {
    name: 'Work In Progress',
    class: 'pending',
  },
  '10': {
    name: 'Work In Progress',
    class: 'pending',
  },
  '11': {
    name: 'Work In Progress',
    class: 'pending',
  },
  '100': {
    name: 'Loading..',
    class: 'pending',
  },
};

export const param_to_qs = (params) => {
  const esc = encodeURIComponent;
  return Object.keys(params)
    .map((k) => `${esc(k)}=${esc(params[k])}`)
    .join('&');
};

export const ACTIVE_TICKETS = [
  {
    cc_emails: [],
    fwd_emails: [],
    reply_cc_emails: [],
    ticket_cc_emails: [],
    fr_escalated: false,
    spam: false,
    email_config_id: 11000002563,
    group_id: 11000003820,
    priority: 3,
    requester_id: 11014824425,
    responder_id: null,
    source: 1,
    company_id: null,
    status: 2,
    subject: '12313123 123 12 123 13 13 123 12312 3',
    association_type: null,
    to_emails: [],
    product_id: null,
    id: 3475092,
    type: null,
    due_by: '2020-07-07T21:18:52Z',
    fr_due_by: '2020-07-07T13:18:52Z',
    is_escalated: false,
    custom_fields: {},
    stats: {
      agent_responded_at: null,
      requester_responded_at: null,
      first_responded_at: null,
      status_updated_at: '2020-07-07T09:18:52Z',
      reopened_at: null,
      resolved_at: null,
      closed_at: null,
      pending_since: null,
    },
    nr_due_by: null,
    nr_escalated: false,
  },
  {
    cc_emails: [],
    fwd_emails: [],
    reply_cc_emails: [],
    ticket_cc_emails: [],
    fr_escalated: false,
    spam: false,
    email_config_id: 11000002563,
    group_id: 11000003820,
    priority: 3,
    requester_id: 11014824425,
    responder_id: null,
    source: 1,
    company_id: null,
    status: 2,
    subject: '12313123 123 12 123 13 13 123 12312 3',
    association_type: null,
    to_emails: [],
    product_id: null,
    id: 3475092,
    type: null,
    due_by: '2020-07-07T21:18:52Z',
    fr_due_by: '2020-07-07T13:18:52Z',
    is_escalated: false,
    custom_fields: {},
    stats: {
      agent_responded_at: null,
      requester_responded_at: null,
      first_responded_at: null,
      status_updated_at: '2020-07-07T09:18:52Z',
      reopened_at: null,
      resolved_at: null,
      closed_at: null,
      pending_since: null,
    },
    nr_due_by: null,
    nr_escalated: false,
  },
  {
    cc_emails: [],
    fwd_emails: [],
    reply_cc_emails: [],
    ticket_cc_emails: [],
    fr_escalated: false,
    spam: false,
    email_config_id: 11000002563,
    group_id: 11000003820,
    priority: 3,
    requester_id: 11014824425,
    responder_id: null,
    source: 1,
    company_id: null,
    status: 2,
    subject: '12313123 123 12 123 13 13 123 12312 3',
    association_type: null,
    to_emails: [],
    product_id: null,
    id: 3475092,
    type: null,
    due_by: '2020-07-07T21:18:52Z',
    fr_due_by: '2020-07-07T13:18:52Z',
    is_escalated: false,
    custom_fields: {},
    stats: {
      agent_responded_at: null,
      requester_responded_at: null,
      first_responded_at: null,
      status_updated_at: '2020-07-07T09:18:52Z',
      reopened_at: null,
      resolved_at: null,
      closed_at: null,
      pending_since: null,
    },
    nr_due_by: null,
    nr_escalated: false,
  },
  {
    cc_emails: [],
    fwd_emails: [],
    reply_cc_emails: [],
    ticket_cc_emails: [],
    fr_escalated: false,
    spam: false,
    email_config_id: 11000002563,
    group_id: 11000003820,
    priority: 3,
    requester_id: 11014824425,
    responder_id: null,
    source: 1,
    company_id: null,
    status: 2,
    subject: '12313123 123 12 123 13 13 123 12312 3',
    association_type: null,
    to_emails: [],
    product_id: null,
    id: 3475092,
    type: null,
    due_by: '2020-07-07T21:18:52Z',
    fr_due_by: '2020-07-07T13:18:52Z',
    is_escalated: false,
    custom_fields: {},
    stats: {
      agent_responded_at: null,
      requester_responded_at: null,
      first_responded_at: null,
      status_updated_at: '2020-07-07T09:18:52Z',
      reopened_at: null,
      resolved_at: null,
      closed_at: null,
      pending_since: null,
    },
    nr_due_by: null,
    nr_escalated: false,
  },
];

export const SAMPLE_TICKET = {
  cc_emails: [],
  fwd_emails: [],
  reply_cc_emails: [],
  ticket_cc_emails: [],
  fr_escalated: false,
  spam: false,
  email_config_id: 11000002563,
  group_id: 11000003820,
  priority: 3,
  requester_id: 11014824425,
  responder_id: null,
  source: 1,
  company_id: null,
  status: 100,
  association_type: null,
  to_emails: [],
  product_id: null,
  id: 'ID',
  type: null,
  due_by: '2020-07-07T21:18:52Z',
  fr_due_by: '2020-07-07T13:18:52Z',
  is_escalated: false,
  subject: 'Settlements are on hold',
  description_text:
    'Your settlements have been put on hold because of some issues with your bank account. We will not be able to process further settlements until the bank account details is updated from your en.. ',
  custom_fields: {},
  stats: {
    agent_responded_at: null,
    requester_responded_at: null,
    first_responded_at: null,
    status_updated_at: '2020-07-07T09:18:52Z',
    reopened_at: null,
    resolved_at: null,
    closed_at: null,
    pending_since: null,
  },
  tags: [],
  nr_due_by: null,
  nr_escalated: false,
};

export const MAX_SIZE_LIMIT = 15 * 1024 * 1024; // 15MB limit
export const MAX_PAGE_SIZE = 100;
export const MAX_CONVERSATION = 100;
export const MIN_TIME_TO_REFRESH = 2 * 60 * 60 * 1000; // 2 hours
export const PRERECORDED_RESPONSES = [
  "I didn't receive a satisfactory response",
  "I haven't received any response yet",
];
