<?php

use EE\Error\ErrorCode;
use EE\Error\PublicErrorCode;
use EE\Error\PublicErrorDescription;

return [
    'testPayment' => [
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'method' => 'card',
        'status' => 'captured',
        'amount_authorized' => 50000,
        'amount_refunded' => 0,
        'refund_status' => null,
        'currency' => 'INR',
        'description' => 'random description',
        'bank' => null,
        'error_code' => null,
        'error_description' => null,
        'email' => 'a@b.com',
        'contact' => '9918899029',
        'notes' => [
            'merchant_order_id' => 'random order id',
        ],
        'gateway' => 'hdfc',
        'signed' => false,
        'verified' => null,
        'entity' => 'payment',
    ],

    'testTransactionAfterCapture' => [
        'type' => 'payment',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 1140,
        'debit' => 0,
        'credit' => 48860,
        'currency' => 'INR',
        'balance' => 1048860,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'escrow_balance' => 1048860,
        'channel' => 'kotak',
        'settled' => false,
        'settled_at' => 1437589800,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testHdfcEntityAfterPaymentRefund' => [
        // 'id' => '3',
        // 'payment_id' => '3bUZ9YystH0Ib0',
        // 'refund_id' => '3bUZ9cW3h3AEy4',
        // 'gateway_transaction_id' => '777700659480931',
        'action' => '2',
        'amount' => '500',
        'enroll_result' => null,
        'status' => 'refunded',
        'result' => 'CAPTURED',
        'eci' => null,
        // 'auth' => '999999',
        // 'ref' => '373790441251',
        'avr' => 'N',
        // 'postdate' => '0720',
        'error_code' => null,
        'error_text' => null,
        'entity' => 'hdfc',
        'admin' => true,
    ],

    'testHdfcPaymentEntity' => [
        'refund_id' => null,
//        'gateway_transaction_id' => '663191662573200',
        'action' => '5',
        'amount' => '500',
        'enroll_result' => null,
        'status' => 'captured',
        'result' => 'CAPTURED',
        'eci' => null,
        'auth' => '999999',
//        'ref' => '789071669515',
        'avr' => 'N',
//        'postdate' => '0719',
        'error_code' => null,
        'error_text' => null,
        'entity' => 'hdfc',
    ],
];
