<?php

use EE\Error\ErrorCode;
use EE\Error\PublicErrorCode;
use EE\Error\PublicErrorDescription;
use Gateway\Hdfc;

return [
    'testPayment' => [
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'method' => 'netbanking',
        'status' => 'captured',
        'amount_authorized' => 50000,
        'amount_refunded' => 0,
        'refund_status' => null,
        'currency' => 'INR',
        'description' => 'random description',
        'bank' => 'HDFC',
        'error_code' => null,
        'error_description' => null,
        'email' => 'a@b.com',
        'contact' => '9918899029',
        'notes' => [
            'merchant_order_id' => 'random order id',
        ],
        'gateway' => 'billdesk',
        'terminal_id' => '1000BdeskTrmnl',
        'signed' => false,
        'verified' => null,
        'entity' => 'payment',
    ],

    'testPaymentBilldeskEntity' => [
        'action'=> 'authorize',
        'BankID'=> 'HDFC',
        'CurrencyType'=> 'INR',
        'ItemCode'=> 'DIRECT',
        'TypeField1'=> 'R',
        'TypeField2'=> 'F',
        'RefAmount'=> null,
        'RefDateTime'=> null,
        'RefStatus'=> null,
        'RefundId'=> null,
        'ErrorCode'=> null,
        'ErrorReason'=> null,
        'ProcessStatus'=> null,
        'refund_id'=> null,
        'entity'=> 'billdesk',
    ],

    'testPaymentRefund' => [
//        'id'=> "76",
//        'payment_id'=> "3PgPULSRMSgExV",
        'action'=> "refund",
//        'MerchantID'=> "random",
//        'CustomerID'=> "3PgPULSRMSgExV",
        'TxnAmount'=> "5.00",
        'BankID'=> null,
        'CurrencyType'=> "INR",
        'ItemCode'=> null,
        'TypeField1'=> null,
        'TypeField2'=> null,
        'AdditionalInfo1'=> null,
//        'TxnReferenceNo'=> "trbqkfizxs",
        'BankReferenceNo'=> null,
        'BankMerchantID'=> null,
        'SecurityType'=> null,
//        'TxnDate'=> "20-06-2015 00:00:00",
        'AuthStatus'=> null,
        'SettlementType'=> null,
        'ErrorStatus'=> null,
        'ErrorDescription'=> null,
        'RequestType'=> "0410",
        'RefAmount'=> "500",
//        'RefDateTime'=> "201506200040838",
        'RefStatus'=> "0799",
//        'RefundId'=> "hlbdtgwnofsxmcj",
        'ErrorCode'=> "NA",
        'ErrorReason'=> "NA",
        'ProcessStatus'=> "Y",
        // 'refund_id'=> "3PgPUT2YOO6htv",
        // 'created_at'=> 1434753518,
        // 'updated_at'=> 1434753518,
        'entity'=> "billdesk",
    ],
];