<?php

use EE\Error\ErrorCode;
use EE\Error\PublicErrorCode;
use EE\Error\PublicErrorDescription;

return [
    'testPayment' => [
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'method' => 'netbanking',
        'status' => 'captured',
        'amount_authorized' => 50000,
        'amount_refunded' => 0,
        'refund_status' => null,
        'currency' => 'INR',
        'description' => 'random description',
        'bank' => 'ICIC',
        'error_code' => null,
        'error_description' => null,
        'email' => 'a@b.com',
        'contact' => '9918899029',
        'notes' => [
            'merchant_order_id' => 'random order id',
        ],
        'gateway' => 'billdesk',
        'terminal_id' => '1000BdeskTrmnl',
        'signed' => false,
        'verified' => null,
        'entity' => 'payment',
    ],

    'testTransactionAfterAuthorize' => [
        'type'=> 'payment',
        'merchant_id'=> '10000000000000',
        'amount'=> 50000,
        'fee'=> 1425,
        'pricing_rule_id'=> '1zD0BXpeOyaqpB',
        'debit'=> 0,
        'credit'=> 48575,
        'currency'=> 'INR',
        'balance'=> 0,
        'gateway_fee'=> 0,
        'api_fee'=> 0,
        'escrow_balance'=> 1048575,
        'channel'=> 'kotak',
        'settled'=> false,
        'settled_at'=> null,
        'settlement_id'=> null,
        'reconciled_at'=> null,
        'entity'=> 'transaction',
        'admin'=> true,
    ],

    'testTransactionAfterCapture' => [
        'type'=> 'payment',
        'merchant_id'=> '10000000000000',
        'amount'=> 50000,
        'fee'=> 1425,
        'debit'=> 0,
        'credit'=> 48575,
        'currency'=> 'INR',
        'balance'=> 1048575,
        'gateway_fee'=> 0,
        'api_fee'=> 0,
        'escrow_balance'=> 1048575,
        'channel'=> 'kotak',
        'settled'=> false,
        'settled_at'=> 1437589800,
        'settlement_id'=> null,
        'reconciled_at'=> null,
        'entity'=> 'transaction',
        'admin'=> true,
    ],

    'testPaymentBilldeskEntity' => [
        'action'=> 'authorize',
        'BankID'=> 'ICI',
        'CurrencyType'=> 'INR',
        'ItemCode'=> 'DIRECT',
        'TypeField1'=> 'R',
        'TypeField2'=> 'F',
        'RefAmount'=> null,
        'RefDateTime'=> null,
        'RefStatus'=> null,
        'RefundId'=> null,
        'ErrorCode'=> null,
        'ErrorReason'=> null,
        'ProcessStatus'=> null,
        'refund_id'=> null,
        'entity'=> 'billdesk',
    ],

    'testPaymentRefund' => [
//        'id'=> '76',
//        'payment_id'=> '3PgPULSRMSgExV',
        'action'=> 'refund',
//        'MerchantID'=> 'random',
//        'CustomerID'=> '3PgPULSRMSgExV',
        'TxnAmount'=> '5.00',
        'BankID'=> null,
        'CurrencyType'=> 'INR',
        'ItemCode'=> null,
        'TypeField1'=> null,
        'TypeField2'=> null,
        'AdditionalInfo1'=> null,
//        'TxnReferenceNo'=> 'trbqkfizxs',
        'BankReferenceNo'=> null,
        'BankMerchantID'=> null,
        'SecurityType'=> null,
//        'TxnDate'=> '20-06-2015 00:00:00',
        'AuthStatus'=> null,
        'SettlementType'=> null,
        'ErrorStatus'=> null,
        'ErrorDescription'=> null,
        'RequestType'=> '0410',
        'RefAmount'=> '500.00',
//        'RefDateTime'=> '201506200040838',
        'RefStatus'=> '0799',
//        'RefundId'=> 'hlbdtgwnofsxmcj',
        'ErrorCode'=> 'NA',
        'ErrorReason'=> 'NA',
        'ProcessStatus'=> 'Y',
        // 'refund_id'=> '3PgPUT2YOO6htv',
        // 'created_at'=> 1434753518,
        // 'updated_at'=> 1434753518,
        'entity'=> 'billdesk',
    ],

    'testGetPaymentMethodsRoute' => [
        'request' => [
            'url' => '/methods',
            'method' => 'get',
        ],
        'response' => [
            'content' => [
                'entity' => 'methods',
                'card' => true,
                'netbanking' => [
                    'UTIB' => 'Axis Bank',
//                    'BARB' => 'Bank of Baroda',
                    'YESB' => 'Yes Bank',
                ],
                'wallet' => [
                    'paytm' => false,
                ],
            ],
        ],
    ],
];