export enum SINGLE_INVITE_STEPS {
  SINGLE_INVITE_FORM = 'SINGLE_INVITE_FORM',
  KYC_ACCESS_FORM = 'KYC_ACCESS_FORM',
  SUCCESS_SCREEN_OPT_IN = 'SUCCESS_SCREEN_OPT_IN',
  SUCCESS_SCREEN_OPT_OUT = 'SUCCESS_SCREEN_OPT_OUT',
}
