<?php

namespace RZP\Gateway\AxisMigs\ErrorCodes;

use RZP\Error\ErrorCode;
use RZP\Gateway\Base\ErrorCodes\Cards;

class ErrorCodes extends Cards\ErrorCodes
{
    public static $vpcErrorCodeMap = [
        '5000' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5001' => ErrorCode::BAD_REQUEST_ORDER_DOES_NOT_EXIST,
        '5002' => ErrorCode::BAD_REQUEST_INVALID_PARAMETERS,
        '5003' => ErrorCode::BAD_REQUEST_INVALID_PARAMETERS,
        '5004' => ErrorCode::BAD_REQUEST_INVALID_STATE,
        '5005' => ErrorCode::BAD_REQUEST_MERCHANT_INVALID,
        '5006' => ErrorCode::GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT,
        '5007' => ErrorCode::GATEWAY_ERROR_CARD_INVALID_ZIP,
        '5008' => ErrorCode::GATEWAY_ERROR_VERSION_ERROR,
        '5009' => ErrorCode::BAD_REQUEST_INVALID_PARAMETERS,
        '5010' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_AMOUNT_OR_CURRENCY,
        '5011' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_AMOUNT_OR_CURRENCY,
        '5012' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_AMOUNT_OR_CURRENCY,
        '5013' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_AMOUNT_OR_CURRENCY,
        '5014' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_AMOUNT_OR_CURRENCY,
        '5015' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_AMOUNT_OR_CURRENCY,
        '5016' => ErrorCode::BAD_REQUEST_MERCHANT_INVALID,
        '5020' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5021' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5022' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5023' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5024' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5025' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5026' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5027' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5028' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5029' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5030' => ErrorCode::GATEWAY_ERROR_INVALID_TXN_LOG_STRING,
        '5031' => ErrorCode::GATEWAY_ERROR_INVALID_TXN_LOG_STRING,
        '5032' => ErrorCode::GATEWAY_ERROR_INVALID_TXN_LOG_STRING,
        '5033' => ErrorCode::GATEWAY_ERROR_INVALID_TXN_LOG_STRING,
        '5034' => ErrorCode::GATEWAY_ERROR_INVALID_TXN_LOG_STRING,
        '5035' => ErrorCode::GATEWAY_ERROR_INVALID_TXN_LOG_STRING,
        '5040' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5041' => ErrorCode::GATEWAY_ERROR_UNSUPPORTED_ACQUIRER,
        '5042' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5043' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_FORMAT,
        '5044' => ErrorCode::BAD_REQUEST_MERCHANT_ACTION_NOT_SUPPORTED,
        '5045' => ErrorCode::GATEWAY_ERROR_PAYMENT_TRANSACTION_NOT_FOUND,
        '5046' => ErrorCode::GATEWAY_ERROR_SIGNATURE_VALIDATION_FAILED,
        '5047' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5048' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5049' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5050' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_HOLDER_NOT_PERMITTED_TXN,
        '5051' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5052' => ErrorCode::BAD_REQUEST_MERCHANT_INVALID,
        '5053' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5054' => ErrorCode::GATEWAY_ERROR_PARSE_ERROR,
        '5055' => ErrorCode::GATEWAY_ERROR_INVALID_RESPONSE,
        '5056' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5057' => ErrorCode::BAD_REQUEST_FORBIDDEN,
        '5058' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5059' => ErrorCode::BAD_REQUEST_PAYMENT_FAILED_BECAUSE_SESSION_EXPIRED,
        '5060' => ErrorCode::BAD_REQUEST_INVALID_LOCALE,
        '5061' => ErrorCode::BAD_REQUEST_INVALID_PAYMENT_METHOD,
        '5065' => ErrorCode::SERVER_ERROR_RUNTIME_ERROR,
        '5066' => ErrorCode::GATEWAY_ERROR_CARD_INVALID_NAME,
        '5070' => ErrorCode::GATEWAY_ERROR_FILE_ERROR,
        '5071' => ErrorCode::GATEWAY_ERROR_FILE_ERROR,
        '5072' => ErrorCode::GATEWAY_ERROR_FILE_ERROR,
        '5073' => ErrorCode::GATEWAY_ERROR_FILE_ERROR,
        '5074' => ErrorCode::GATEWAY_ERROR_FILE_ERROR,
        '5080' => ErrorCode::GATEWAY_ERROR_SQL_ERROR,
        '5081' => ErrorCode::GATEWAY_ERROR_SQL_ERROR,
        '5082' => ErrorCode::GATEWAY_ERROR_SQL_ERROR,
        '5083' => ErrorCode::GATEWAY_ERROR_SQL_ERROR,
        '5084' => ErrorCode::GATEWAY_ERROR_SQL_ERROR,
        '5085' => ErrorCode::GATEWAY_ERROR_SQL_ERROR,
        '5086' => ErrorCode::GATEWAY_ERROR_PAYMENT_DUPLICATE_REQUEST,
        '5087' => ErrorCode::GATEWAY_ERROR_SQL_ERROR,
        '5090' => ErrorCode::BAD_REQUEST_INVALID_ACCOUNT_HOLDER_NAME,
        '5091' => ErrorCode::BAD_REQUEST_INVALID_PASSWORD,
        '5101' => ErrorCode::BAD_REQUEST_PAYMENT_BANK_SYSTEM_ERROR,
        '5103' => ErrorCode::BAD_REQUEST_PAYMENT_BANK_SYSTEM_ERROR,
        '5104' => ErrorCode::BAD_REQUEST_INVALID_PARAMETERS,
        '5106' => ErrorCode::BAD_REQUEST_INVALID_PARAMETERS,
        '5108' => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_FORMAT,
        '5109' => ErrorCode::GATEWAY_ERROR_SIGNATURE_VALIDATION_FAILED,
        '5110' => ErrorCode::GATEWAY_ERROR_SIGNATURE_VALIDATION_FAILED,
        '5175' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID,
        '5120' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5121' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5122' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5123' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5124' => ErrorCode::GATEWAY_ERROR_INVALID_FORMAT,
        '5125' => ErrorCode::GATEWAY_ERROR_SIGNATURE_VALIDATION_FAILED,
        '5126' => ErrorCode::GATEWAY_ERROR_TRANSACTION_TYPE_NOT_SUPPORTED,
        '5127' => ErrorCode::BAD_REQUEST_USER_NOT_AUTHENTICATED,
        '5128' => ErrorCode::BAD_REQUEST_UNAUTHORIZED_INVALID_API_KEY,
        '5129' => ErrorCode::GATEWAY_ERROR_CREDIT_CARD_NUMBER_DECRYPTION_FAILED,
        '5130' => ErrorCode::GATEWAY_ERROR_CREDIT_CARD_ENCRYPTION_FAILED,
        '5131' => ErrorCode::GATEWAY_ERROR_CRYPTO_ALOGRITHM_ERROR,
        '5132' => ErrorCode::BAD_REQUEST_UNAUTHORIZED_INVALID_API_KEY,
        '5133' => ErrorCode::BAD_REQUEST_UNAUTHORIZED_INVALID_API_KEY,
        '5134' => ErrorCode::GATEWAY_ERROR_RSA_DECRYPTION_FAILED,
        '5135' => ErrorCode::GATEWAY_ERROR_RSA_ENCRYPTION_FAILED,
        '5136' => ERRORCODE::BAD_REQUEST_SECURE_CGI_PARAM_KEY_CORRUPT_INVALID,
        '5137' => ErrorCode::BAD_REQUEST_SECURE_CGI_PARAM_PRIVATE_KEY_CORRUPT_INVALID,
        '5138' => ErrorCode::BAD_REQUEST_SECURE_CGI_PARAM_PUBLIC_KEY_CORRUPT_INVALID,
        '5140' => ErrorCode::GATEWAY_ERROR_UNSUPPORTED_ACQUIRER,
        '5141' => ErrorCode::BAD_REQUEST_ERROR,
        '5142' => ErrorCode::BAD_REQUEST_RECONCILIATION,
        '5143' => ErrorCode::BAD_REQUEST_TRANSACTIONS_LIMIT_REACHED,
        '5144' => ErrorCode::BAD_REQUEST_SHARED_TERMINAL_ERROR,
        '5145' => ErrorCode::BAD_REQUEST_TERMINAL_ERROR,
        '5146' => 'Terminal near full',
        '5147' => ErrorCode::BAD_REQUEST_TERMINAL_ERROR,
        '5148' => ErrorCode::BAD_REQUEST_RECON_NOT_IN_PROGRESS,
        '5150' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_NUMBER_POSSIBLY_INVALID,
        '5151' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID,
        '5152' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID,
        '5153' => ErrorCode::GATEWAY_ERROR_CARD_NUMBER_INVALID_LENGTH,
        '5154' => ErrorCode::GATEWAY_ERROR_CARD_INVALID_NUMBER,
        '5155' => ErrorCode::GATEWAY_ERROR_INVALID_CARD_NUMBER_PREFIX,
        '5156' => ErrorCode::GATEWAY_ERROR_CARD_INVALID_CVV,
        '5157' => ErrorCode::GATEWAY_ERROR_CARD_INVALID_EXPIRY_DATE,
        '5158' => ErrorCode::GATEWAY_ERROR_CARD_INVALID_EXPIRY_DATE,
        '5162' => ErrorCode::GATEWAY_ERROR_FILE_ERROR,
        '5166' => ErrorCode::GATEWAY_ERROR_CARD_INVALID_CVV,
        '5170' => ErrorCode::GATEWAY_ERROR_DELETING_TERMINAL,
        '5171' => ErrorCode::GATEWAY_ERROR_CREATING_TERMINAL,
        '5161' => ErrorCode::GATEWAY_ERROR_PAYMENT_INVALID_REFERENCE_NO,
        '5176' => ErrorCode::BAD_REQUEST_INVALID_CARD_DETAILS,
        '5185' => ErrorCode::GATEWAY_ERROR_INVALID_ACKNOWLEDGMENT,
        '5200' => ErrorCode::GATEWAY_ERROR_PAYMENT_CREATION_FAILED,
        '5201' => ErrorCode::GATEWAY_ERROR_ORDER_CREATION_FAILED,
        '5202' => ErrorCode::GATEWAY_ERROR_RECEIPT_CREATION_FAILED,
        '5204' => ErrorCode::GATEWAY_ERROR_PAYMENT_CAPTURE_FAILED,
        '5205' => ErrorCode::GATEWAY_ERROR_PAYMENT_REFUND_FAILED,
        '5206' => ErrorCode::GATEWAY_ERROR_PAYMENT_VOID_FAILED,
        '5207' => ErrorCode::GATEWAY_ERROR_PAYMENT_REFUND_FAILED,
        '5208' => ErrorCode::GATEWAY_ERROR_FINANCIAL_TRANSACTION_HISTORY_FAILED,
        '5209' => ErrorCode::GATEWAY_ERROR_SHOPPING_TRANSACTION_HISTORY_FAILED,
        '5210' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5220' => ErrorCode::BAD_REQUEST_RECONCILIATION,
        '5221' => ErrorCode::BAD_REQUEST_RECONCILIATION,
        '5222' => ErrorCode::BAD_REQUEST_RECONCILIATION,
        '5230' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5231' => ErrorCode::GATEWAY_ERROR_INVALID_DIGITAL_RECEIPT,
        '5232' => ErrorCode::GATEWAY_ERROR_DIGITAL_ORDER_ERROR,
        '5233' => ErrorCode::GATEWAY_ERROR_DIGITAL_ORDER_ERROR,
        '5234' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5235' => ErrorCode::GATEWAY_ERROR_DIGITAL_RECEIPT_ERROR,
        '5336' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5400' => ErrorCode::GATEWAY_ERROR_DIGITAL_ORDER_ERROR,
        '5401' => ErrorCode::BAD_REQUEST_INVALID_PARAMETERS,
        '5402' => ErrorCode::GATEWAY_ERROR_REQUEST_ERROR,
        '5403' => ErrorCode::GATEWAY_ERROR_DIGITAL_ORDER_ERROR,
        '5410' => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        '5411' => ErrorCode::GATEWAY_ERROR_REQUEST_ERROR,
        '5412' => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        '5413' => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        '5414' => ErrorCode::GATEWAY_ERROR_CAPTURE_GREATER_THAN_AUTH,
        '5415' => ErrorCode::BAD_REQUEST_REFUND_FAILED,
        '5416' => ErrorCode::GATEWAY_ERROR_PAYMENT_VOID_FAILED,
        '5417' => ErrorCode::BAD_REQUEST_REFUND_FAILED,
        '5418' => ErrorCode::GATEWAY_ERROR_FINANCIAL_TRANSACTION_HISTORY_FAILED,
        '5419' => ErrorCode::GATEWAY_ERROR_SHOPPING_TRANSACTION_HISTORY_FAILED,
        '5420' => ErrorCode::BAD_REQUEST_RECONCILIATION,
        '5421' => ErrorCode::BAD_REQUEST_RECONCILIATION,
        '5422' => ErrorCode::BAD_REQUEST_RECONCILIATION,
        '5423' => ErrorCode::BAD_REQUEST_USER_NOT_AUTHENTICATED,
        '5424' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5425' => ErrorCode::GATEWAY_ERROR_RECURRING_PAYMENT_NOT_FOUND,
        '5426' => ErrorCode::BAD_REQUEST_INVALID_PERMISSIONS_USAGE,
        '5427' => ErrorCode::BAD_REQUEST_PURCHASE_ERROR,
        '5428' => ErrorCode::BAD_REQUEST_PURCHASE_ERROR,
        '5429' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5430' => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        '5431' => ErrorCode::GATEWAY_ERROR_PAYMENT_TRANSACTION_NOT_FOUND,
        '5432' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5433' => ErrorCode::BAD_REQUEST_PERMISSION_ERROR,
        '5434' => ErrorCode::GATEWAY_ERROR_DEFERRED_PAYMENT_SERVICE_UNAVAILABLE,
        '5435' => ErrorCode::BAD_REQUEST_MAX_DEFERRED_PAYMENT_REACHED,
        '5436' => ErrorCode::GATEWAY_ERROR_PAYMENT_TRANSACTION_NOT_FOUND,
        '5450' => ErrorCode::GATEWAY_ERROR_DIGITAL_ORDER_ERROR,
        '5451' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        '5500' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID,
        '5501' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID,
        '5600' => ErrorCode::BAD_REQUEST_RETRY_ATTEMPT_LIMIT_EXCEEDED,
        '5601' => ErrorCode::GATEWAY_ERROR_INSTANTIATION_ACQUIRER_CONTROLLER_FAILED,
        '5602' => ErrorCode::GATEWAY_ERROR_IO_ERROR,
        '5603' => ErrorCode::GATEWAY_ERROR_INVALID_TERMINAL_ID,
        '5604' => ErrorCode::BAD_REQUEST_RECONCILIATION,
        '5661' => ErrorCode::GATEWAY_ERROR_UNSUPPORTED_ACQUIRER,
        '5670' => ErrorCode::GATEWAY_ERROR_MESSAGE_ERROR,
        '5671' => ErrorCode::GATEWAY_ERROR_MESSAGE_ERROR,
        '5672' => ErrorCode::GATEWAY_ERROR_MESSAGE_ERROR,
        '5680' => ErrorCode::GATEWAY_ERROR_TRANSPORT_ERROR,
        '5681' => ErrorCode::GATEWAY_ERROR_TRANSPORT_ERROR,
        '5682' => ErrorCode::GATEWAY_ERROR_TRANSPORT_ERROR,
        '5683' => ErrorCode::GATEWAY_ERROR_TRANSPORT_ERROR,
        '5684' => ErrorCode::GATEWAY_ERROR_TRANSPORT_ERROR,
        '5690' => ErrorCode::GATEWAY_ERROR_SOCKET_ERROR,
        '5691' => ErrorCode::GATEWAY_ERROR_SOCKET_ERROR,
        '5692' => ErrorCode::GATEWAY_ERROR_SOCKET_ERROR,
        '5693' => ErrorCode::GATEWAY_ERROR_SOCKET_ERROR,
        '5694' => ErrorCode::GATEWAY_ERROR_SOCKET_ERROR,
        '5695' => ErrorCode::GATEWAY_ERROR_SOCKET_ERROR,
        '5696' => ErrorCode::GATEWAY_ERROR_CONNECTION_ERROR,
        '5730' => ErrorCode::GATEWAY_ERROR_SOCKET_ERROR,
        '5750' => ErrorCode::BAD_REQUEST_INVALID_PARAMETERS,
        '5751' => ErrorCode::BAD_REQUEST_INVALID_PARAMETERS,
        '5752' => ErrorCode::BAD_REQUEST_INVALID_PARAMETERS,
        '5753' => ErrorCode::BAD_REQUEST_INVALID_PARAMETERS,
        '5754' => ErrorCode::GATEWAY_ERROR_CHECKSUM_MATCH_FAILED,
        '5800' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5801' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5802' => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        '5803' => ErrorCode::GATEWAY_ERROR_PAYMENT_DUPLICATE_REQUEST,
        '5804' => ErrorCode::GATEWAY_ERROR_PARSE_ERROR,
        '5805' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5806' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5807' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5808' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5809' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5810' => ErrorCode::GATEWAY_ERROR_FATAL_ERROR,
        '5811' => 'Cron service stopped',
        '5812' => 'Parse error',
        '5813' => 'Invalid entry',
        '5910' => 'Null pointer caught',
        '5911' => 'URL Decode Exception occurred',
        '5930' => 'Invalid card type for excessive refunds',
        '5931' => 'Agent not authorized to perform excessive refunds for this amount',
        '5932' => 'Too many excessive refunds apply to this shopping transaction already',
        '5933' => 'Merchant agent is not authorized to perform excessive refunds',
        '5934' => 'Merchant is not authorized to perform excessive refunds',
        '5935' => 'Merchant cannot perform excessive refunds due to its transaction type',
        '6010' => 'Bad format in Rulefile',
        '6100' => 'Invalid host name',
        '7000' => 'XML parser [Fatal Error]',
        '7001' => 'XML parser [Error]',
        '7002' => 'XML parser [Warning]',
        '7003' => 'XML Parameter is invalid',
        '7004' => 'XML Parameter had an invalid index. Check input .html file',
        '7005' => 'XML [Bad Provider Class]',
        '7050' => 'SleepTimer: Time value is not in a valid format (ignored this time value)',
        '7100' => 'No valid times and/or interval specified in StatementProcessing.properties file. 
                   Execution terminated',
        '7101' => 'Status file for this data file was never created – deleting',
        '7102' => 'Error loading Statement.properties file',
        '7104' => 'Can’t find file',
        '7106' => 'IOException thrown attempting to create or write to file',
        '7107' => 'Overwriting file',
        '7108' => 'SecurityException thrown when attempting to create output file',
        '7109' => 'Invalid Merchant Id. This Advice element will not be processed',
        '7110' => 'Can’t create file name from the given date string',
        '7111' => 'Duplicate Advice element found in input document and skipped. Check input document',
        '7112' => 'Invalid payment type specified. This file will be skipped',
        '7113' => 'Null directory: can’t create output file',
        '7114' => 'Validation of input file provided by host failed',
        '7120' => 'IOException thrown attempting to create or write to file',
        '7121' => 'IOException thrown while attempting to create a ZIP archive',
        '7122' => 'An inaccessible output directory was specified in the configuration file',
        '7200' => 'PRE Issue Id Error',
        '7201' => 'No Login User Object stored in session.',
        '7202' => 'Error Occurred while creating the merchant on the Payment Server.',
        '7203' => 'Logging out',
        '7204' => 'Error occurred while instantiating Payment.',
        '7205' => 'Error occurred while instantiating SSL Payment',
        '7207' => 'Error occurred while sending email',
        '7208' => 'Invalid Access. User is trying to access a page illegally.',
        '7209' => 'Invalid User Input.',
        '7300' => 'Error parsing meta data file',
        '7301' => 'Invalid field',
        '7302' => 'Field validator not present',
        '7303' => 'Validation of field failed',
        '7304' => 'Field not present in arbitrary data',
        '7305' => 'Mandatory field missing',
        '7306' => 'Date mask is invalid',
        '7307' => 'Error creating field validator',
        '7308' => 'Failed to update arbitrary data',
        '7400' => 'Invalid transaction type',
        '7500' => 'Record has changed since last read',
        '8000' => 'Invalid Local Tax Flag',
        '8001' => 'Local Tax Amount Equal to or Greater then Initial Transaction Amount',
        '8002' => 'Purchaser Postcode Too Long',
        '8003' => 'Invalid Local Tax Flag and Local Tax Flag Amount Combination',
        '8004' => 'Invalid Local Tax Amount',
        '8015' => 'Payment method must be EBT for a balance inquiry or Invalid Digital Order: Invalid PaymentMethod',
        '8016' => 'Invalid Digital Order: Invalid PIN field',
        '8017' => 'Invalid Digital Order: Invalid KSN field',
        '8019' => 'Invalid Digital Order: Invalid PhysicalTerminalID field',
        '8020' => 'Invalid Digital Order: Invalid POSEntryMode field',
        '8021' => 'Invalid Digital Order: Invalid AdditionalAmount field',
        '9000' => 'Acquirer did not respond',
        '9150' => 'Missing or Invalid Secure Hash',
        '9151' => 'Invalid Secure Hash Type, or Secure Hash Type not allowed for this merchant',
        '9152' => 'Missing or Invalid Access Code',
        '9153' => 'Request contains more than one instance of the same field',
        '9154' => 'General merchant configuration error preventing request from being processed',
        '9200' => 'Missing or Invalid Template Number',
        'Timed out' => ErrorCode::BAD_REQUEST_PAYMENT_NO_RESPONSE_RECEIVED_FROM_BANK,
        'Pending' => ErrorCode::BAD_REQUEST_PAYMENT_PENDING,
    ];

    public static $txnErrorCodeMap = [
        '1' => ErrorCode::BAD_REQUEST_PAYMENT_FAILED,
        '2' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK,
        '3' => ErrorCode::BAD_REQUEST_PAYMENT_NO_RESPONSE_RECEIVED_FROM_BANK,
        '4' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_EXPIRED,
        '5' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INSUFFICIENT_BALANCE,
        '6' => ErrorCode::BAD_REQUEST_PAYMENT_BANK_SYSTEM_ERROR,
        '7' => [
            'E5000'   => ErrorCode::GATEWAY_ERROR_INVALID_TERMINAL,
            'E5159'   => ErrorCode::GATEWAY_ERROR_UNSUPPORTED_CARD_NETWORK,
            'E5408'   => ErrorCode::GATEWAY_ERROR_TRANSACTION_TYPE_NOT_SUPPORTED,
            'E5414'   => [
                'no payments identified' => ErrorCode::GATEWAY_ERROR_PAYMENT_CAPTURE_FAILED,
                'requested capture amount exceeds outstanding authorized amount' =>
                    ErrorCode::GATEWAY_ERROR_CAPTURE_GREATER_THAN_AUTH,
            ],
            'E5415'   => ErrorCode::GATEWAY_ERROR_REFUND_AMOUNT_GREATER_THAN_CAPTURED,
            'I5154'   => ErrorCode::BAD_REQUEST_PAYMENT_CARD_NUMBER_NOT_LEGITIMATE,
            'I5166'   => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INVALID_CVV,
            'I5426'   => ErrorCode::GATEWAY_ERROR_INVALID_TERMINAL,
            'W9520'   => ErrorCode::SERVER_ERROR_RUNTIME_ERROR,
            'default' => ErrorCode::SERVER_ERROR_RUNTIME_ERROR,
        ],
        '8' => ErrorCode::GATEWAY_ERROR_TRANSACTION_TYPE_NOT_SUPPORTED,
        '9' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK,
        'A' => ErrorCode::SERVER_ERROR_PAYMENT_ABORTED,
        'B' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK,
        'C' => ErrorCode::BAD_REQUEST_PAYMENT_CANCELLED,
        'D' => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        'E' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK,
        'F' => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_3DSECURE_AUTH_FAILED,
        'I' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INVALID_CVV,
        'L' => ErrorCode::SERVER_ERROR,
        'N' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_NOT_ENROLLED_FOR_3DSECURE,
//        'P' => '',
        'R' => ErrorCode::BAD_REQUEST_RETRY_ATTEMPT_LIMIT_EXCEEDED,
        'S' => ErrorCode::SERVER_ERROR_DUPLICATE_SESSION_ID,
        'T' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'U' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INVALID_CVV,
        'V' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INVALID_CVV,
        '?' => ErrorCode::BAD_REQUEST_PAYMENT_FAILED,

        'Aborted' => ErrorCode::BAD_REQUEST_PAYMENT_ABORTED,
    ];

    public static $avsErrorCodeMap = [
        'A' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'B' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'C' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'D' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'E' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'F' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'G' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'I' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'K' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'L' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'M' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'N' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'O' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'P' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'R' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'S' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'U' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'W' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'X' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'Y' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
        'Z' => ErrorCode::BAD_REQUEST_CARD_AVS_FAILED,
    ];

    public static $cscErrorCodeMap = [
        'S' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_NOT_PROVIDED,
        'P' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INVALID_CVV,
        'U' => ErrorCode::BAD_REQUEST_CARD_ISSUER_INVALID,
        'N' => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INVALID_CVV,
    ];

    public static function getRelevantGatewayErrorCode($errorFieldName, $content)
    {
        if ($errorFieldName === ErrorFields::VPC_MESSAGE)
        {
            return static::getVpcMessageErrorCode($content[$errorFieldName]);
        }

        return parent::getRelevantGatewayErrorCode($errorFieldName, $content);
    }

    public static function getVpcMessageErrorCode($code)
    {
        $gatewayCode = null;

        if (in_array($code, ['Pending', 'Timed out']) === true)
        {
            return $code;
        }

        $isMatched = preg_match('/[0-9]{4}/', $code, $matches);

        if ($isMatched == 1)
        {
            $gatewayCode = $matches[0];
        }

        return $gatewayCode;
    }
}
