<?php

namespace RZP\Reconciliator\Base;

class InfoCode
{
    const AMOUNT_MISMATCH                               = 'AMOUNT_MISMATCH';

    const PAYMENT_ABSENT                                = 'PAYMENT_ABSENT';

    const PAYMENT_TRANSACTION_ABSENT                    = 'PAYMENT_TRANSACTION_ABSENT';

    const REFUND_ABSENT                                 = 'REFUND_ABSENT';

    const CARD_TYPE_ABSENT                              = 'CARD_TYPE_ABSENT';

    const CURRENCY_MISMATCH                             = 'CURRENCY_MISMATCH';

    const UNKNOWN_CARD_TYPE                             = 'UNKNOWN_CARD_TYPE';

    const UNKNOWN_RECON_TYPE                            = 'UNKNOWN_RECON_TYPE';

    const RECON_TYPE_NOT_FOUND                          = 'RECON_TYPE_NOT_FOUND';

    const GATEWAY_PAYMENT_ABSENT                        = 'GATEWAY_PAYMENT_ABSENT';

    const COLUMN_HEADER_MISMATCH                        = 'COLUMN_HEADER_MISMATCH';

    const DATA_MISMATCH                                 = 'DATA_MISMATCH';

    const DUPLICATE_ROW                                 = 'DUPLICATE_ROW';

    const UNEXPECTED_PAYMENT                            = 'UNEXPECTED_PAYMENT';

    const VPA_MISMATCH                                  = 'VPA_MISMATCH';

    const RECON_UNEXPECTED_REFUND                       = 'RECON_UNEXPECTED_REFUND';

    const RECON_PAYMENT_GATEWAY_MISMATCH                = 'RECON_PAYMENT_GATEWAY_MISMATCH';

    const RECON_ROW_INVALID_FORMAT_FOUND                = 'RECON_ROW_INVALID_FORMAT_FOUND';

    const RAZORPAY_FAILED_PAYMENT_RECON                 = 'RAZORPAY_FAILED_PAYMENT_RECON';

    const UNPROCESSED_REFUND_ARN_ABSENT                 = 'UNPROCESSED_REFUND_ARN_ABSENT';

    const MIS_FILE_REFUND_FAILED                        = 'MIS_FILE_REFUND_FAILED';

    const INCORRECT_DATE_FORMAT                         = 'INCORRECT_DATE_FORMAT';

    const PAYMENT_FORCE_AUTHORIZED                      = 'PAYMENT_FORCE_AUTHORIZED';

    const PAYMENT_FORCE_AUTHORIZE_FAILED                = 'PAYMENT_FORCE_AUTHORIZE_FAILED';

    const RECON_BATCH_MARK_PROCESSED                    = 'RECON_BATCH_MARK_PROCESSED';

    const RECON_BATCH_NOT_LAST_CHUNK                    = 'RECON_BATCH_NOT_LAST_CHUNK';

    const REFUND_RECON_SCROOGE_BATCH_EMPTY              = 'REFUND_RECON_SCROOGE_BATCH_EMPTY';

    const REFUND_RECON_SCROOGE_JOB_FAILURE_EXCEPTION    = 'REFUND_RECON_SCROOGE_JOB_FAILURE_EXCEPTION';

    const REFUND_RECON_SCROOGE_JOB_PROCESSING_FAILURE   = 'REFUND_RECON_SCROOGE_JOB_PROCESSING_FAILURE';

    const REFUND_RECON_SCROOGE_NOT_RECONCILED           = 'REFUND_RECON_SCROOGE_NOT_RECONCILED';

    const REFUND_RECON_SCROOGE_NO_REFUNDS               = 'REFUND_RECON_SCROOGE_NO_REFUNDS';

    const API_SCROOGE_RECONCILED_AT_MISMATCH            = 'API_SCROOGE_RECONCILED_AT_MISMATCH';

    const RECON_GATEWAY_ENTITY_CREATED                  = 'RECON_GATEWAY_ENTITY_CREATED';

    const RECON_INSUFFICIENT_DATA_FOR_ENTITY_CREATION   = 'RECON_INSUFFICIENT_DATA_FOR_ENTITY_CREATION';

    const RECON_GATEWAY_ENTITY_CREATION_FAILED          = 'RECON_GATEWAY_ENTITY_CREATION_FAILED';

    const UNEXPECTED_TERMINAL_GATEWAY                   = 'UNEXPECTED_TERMINAL_GATEWAY';

    const UNEXPECTED_TERMINAL_GATEWAY_ACQUIRER          = 'UNEXPECTED_TERMINAL_GATEWAY_ACQUIRER';

    const UNEXPECTED_PAYMENT_ALREADY_EXISTS             = 'UNEXPECTED_PAYMENT_ALREADY_EXISTS';

    const RECON_UNEXPECTED_PAYMENT_CREATED              = 'RECON_UNEXPECTED_PAYMENT_CREATED';

    const RECON_UNEXPECTED_PAYMENT_CREATE_INITIATED     = 'RECON_UNEXPECTED_PAYMENT_CREATE_INITIATED';

    const RECON_UNEXPECTED_PAYMENT_CREATION_FAILED      = 'RECON_UNEXPECTED_PAYMENT_CREATION_FAILED';
}
