<?php

namespace RZP\Reconciliator\Base;

class InfoCode
{
    const AMOUNT_MISMATCH                   = 'AMOUNT_MISMATCH';

    const PAYMENT_ABSENT                    = 'PAYMENT_ABSENT';

    const PAYMENT_TRANSACTION_ABSENT        = 'PAYMENT_TRANSACTION_ABSENT';

    const REFUND_ABSENT                     = 'REFUND_ABSENT';

    const CARD_TYPE_ABSENT                  = 'CARD_TYPE_ABSENT';

    const CURRENCY_MISMATCH                 = 'CURRENCY_MISMATCH';

    const UNKNOWN_CARD_TYPE                 = 'UNKNOWN_CARD_TYPE';

    const UNKNOWN_RECON_TYPE                = 'UNKNOWN_RECON_TYPE';

    const RECON_TYPE_NOT_FOUND              = 'RECON_TYPE_NOT_FOUND';

    const GATEWAY_PAYMENT_ABSENT            = 'GATEWAY_PAYMENT_ABSENT';

    const COLUMN_HEADER_MISMATCH            = 'COLUMN_HEADER_MISMATCH';

    const DATA_MISMATCH                     = 'DATA_MISMATCH';

    const UNEXPECTED_PAYMENT                = 'UNEXPECTED_PAYMENT';

    const VPA_MISMATCH                      = 'VPA_MISMATCH';

    const RAZORPAY_FAILED_PAYMENT_RECON     = 'RAZORPAY_FAILED_PAYMENT_RECON';

    const FAILED_REFUND_ARN_ABSENT          = 'FAILED_REFUND_ARN_ABSENT';

    const MIS_FILE_REFUND_FAILED            = 'MIS_FILE_REFUND_FAILED';

    const INCORRECT_DATE_FORMAT             = 'INCORRECT_DATE_FORMAT';

    const PAYMENT_FORCE_AUTHORIZED          = 'PAYMENT_FORCE_AUTHORIZED';

    const PAYMENT_FORCE_AUTHORIZE_FAILED    = 'PAYMENT_FORCE_AUTHORIZE_FAILED';

    const UNEXPECTED_PAYMENT_ALREADY_EXISTS        = 'UNEXPECTED_PAYMENT_ALREADY_EXISTS';

    const RECON_UNEXPECTED_PAYMENT_CREATED         = 'RECON_UNEXPECTED_PAYMENT_CREATED';

    const RECON_UNEXPECTED_PAYMENT_CREATION_FAILED = 'RECON_UNEXPECTED_PAYMENT_CREATION_FAILED';
}
