<?php

namespace RZP\Models\Admin\Group;

class Constant
{
    const SALESFORCE_CLAIMED_MERCHANTS_GROUP_ID = 'SALESFORCE_CLAIMED_MERCHANTS_GROUP_ID';
    const SALESFORCE_CLAIMED_SME_GROUP_ID       = 'SALESFORCE_CLAIMED_SME_GROUP_ID';
    const SALESFORCE_UNCLAIMED_GROUP_ID         = 'SALESFORCE_UNCLAIMED_GROUP_ID';

    //prod
    const SF_CLAIMED_MERCHANTS_GROUP_ID = 'E15FKNaXgALD6Y';
    const SF_CLAIMED_SME_GROUP_ID       = 'E34ct85lm9wLEz';
    const SF_UNCLAIMED_GROUP_ID         = 'E15BhsdMSofcUJ';
}
