export const B2B_EXPORTS_TRANSACTIONS_FETCH = 'B2B_EXPORTS_TRANSACTIONS_FETCH';
export const B2B_EXPORTS_UPLOAD_INVOICE = 'B2B_EXPORTS_UPLOAD_INVOICE';
export const B2B_EXPORTS_FETCH_ACCOUNTS = 'B2B_EXPORTS_FETCH_ACCOUNTS';
export const B2B_EXPORTS_ACTIVATE_ACCOUNTS = 'B2B_EXPORTS_ACTIVATE_ACCOUNTS';
export const B2B_EXPORTS_SET_FEATURE = 'B2B_EXPORTS_SET_FEATURE';
export const B2B_EXPORTS_GET_INVOICE_DETAILS = 'B2B_EXPORTS_GET_INVOICE_DETAILS';
export const B2B_EXPORTS_GET_BALANCE = 'B2B_EXPORTS_GET_BALANCE';
export const B2B_EXPORTS_GET_BENEFICIARY = 'B2B_EXPORTS_GET_BENEFICIARY';
export const B2B_EXPORTS_CREATE_PAYOUT = 'B2B_EXPORTS_CREATE_PAYOUT';
export const B2B_PURPOSE_CODE_INELIGIBLE_ERROR_KEY = 'b2b_purpose_code_ineligible_error';
export const B2B_CLOSE_PURPOSE_CODE_INELIGIBLE_MODAL = 'B2B_SET_PURPOSE_CODE_INELIGIBLE';
export const B2B_PUBLIC_PAYMENT_LINK = 'B2B_PUBLIC_PAYMENT_LINK';

export const B2B_ACCOUNT_STATUS = {
  deactivated: 'deactivated',
};

export const PURPOSE_CODE_NOT_ELIGIBLE_ERROR = 'purpose code is not eligible';
