import { getDefaultPaymentFilter } from 'common/utils/pokedex';

const paymentMethodsColumns = ['method', 'bank', 'issuer', 'network', 'wallet', 'type'];

const aggTypes = [
  {
    value: 'sum',
    text: 'By Payment Volume',
    isCurrency: true,
  },
  {
    value: 'count',
    text: 'By Number of Payments',
  },
];

const getQuery = ({
  startTime,
  endTime,
  aggType = aggTypes[0].value,
  groupBy = paymentMethodsColumns,
}) => ({
  filters: {
    default: [getDefaultPaymentFilter(startTime, endTime)],
  },
  aggregations: {
    agg: {
      agg_type: aggType,
      details: {
        index: 'payments',
        column: 'base_amount',
        group_by: groupBy,
      },
    },
  },
});

const bankNames = {
  ABHY: 'Abhyudaya Co-operative Bank',
  ABNA: 'Royal Bank of Scotland N.V.',
  ABPB: 'Aditya Birla Idea Payments Bank',
  AIRP: 'Airtel Payments Bank',
  ALLA: 'Allahabad Bank',
  ANDB: 'Andhra Bank',
  ANDB_C: 'Andhra Bank - Corporate Banking',
  AUBL: 'AU Small Finance Bank',
  BACB: 'Bassein Catholic Co-operative Bank',
  BARB_C: 'Bank of Baroda - Corporate Banking',
  BARB_R: 'Bank of Baroda - Retail Banking',
  BBKM: 'Bank of Bahrein and Kuwait',
  BDBL: 'Bandhan Bank',
  BKDN: 'Dena Bank',
  BKID: 'Bank of India',
  CBIN: 'Central Bank of India',
  CITI: 'Citibank',
  CIUB: 'City Union Bank',
  CNRB: 'Canara Bank',
  CORP: 'Union Bank of India (Erstwhile Corporation Bank)',
  COSB: 'Cosmos Co-operative Bank',
  CSBK: 'Catholic Syrian Bank',
  DBSS: 'Development Bank of Singapore',
  DCBL: 'DCB Bank',
  DEUT: 'Deutsche Bank',
  DLXB: 'Dhanlaxmi Bank',
  DLXB_C: 'Dhanlaxmi Bank - Corporate Banking',
  ESAF: 'ESAF Small Finance Bank',
  ESFB: 'Equitas Small Finance Bank',
  FDRL: 'Federal Bank',
  FSFB: 'Fincare Small Finance Bank',
  HDFC: 'HDFC Bank',
  HDFC_C: 'HDFC Bank - Corporate Banking',
  HSBC: 'HSBC',
  IBKL: 'IDBI',
  IBKL_C: 'IDBI - Corporate Banking',
  ICIC: 'ICICI Bank',
  ICIC_C: 'ICICI Bank - Corporate Banking',
  IDFB: 'IDFC FIRST Bank',
  IDIB: 'Indian Bank',
  INDB: 'Indusind Bank',
  IOBA: 'Indian Overseas Bank',
  JAKA: 'Jammu and Kashmir Bank',
  JSBP: 'Janata Sahakari Bank (Pune)',
  JSFB: 'Jana Small Finance Bank',
  KARB: 'Karnataka Bank',
  KCCB: 'Kalupur Commercial Co-operative Bank',
  KJSB: 'Kalyan Janata Sahakari Bank',
  KKBK: 'Kotak Mahindra Bank',
  KKBK_C: 'Kotak Mahindra Bank - Corporate Banking',
  KVBL: 'Karur Vysya Bank',
  LAVB_C: 'Lakshmi Vilas Bank - Corporate Banking',
  LAVB_R: 'Lakshmi Vilas Bank - Retail Banking',
  MAHB: 'Bank of Maharashtra',
  MSNU: 'Mehsana Urban Co-operative Bank',
  NESF: 'North East Small Finance Bank',
  NKGS: 'NKGSB Co-operative Bank',
  ORBC: 'PNB (Erstwhile-Oriental Bank of Commerce)',
  PSIB: 'Punjab & Sind Bank',
  PUNB_R: 'Punjab National Bank - Retail Banking',
  PUNB: 'Punjab National Bank',
  PYTM: 'Paytm Payments Bank',
  RATN: 'RBL Bank',
  RATN_C: 'RBL Bank - Corporate Banking',
  SBBJ: 'State Bank of Bikaner and Jaipur',
  SBHY: 'State Bank of Hyderabad',
  SBIN: 'State Bank of India',
  SBMY: 'State Bank of Mysore',
  SBTR: 'State Bank of Travancore',
  SCBL: 'Standard Chartered Bank',
  SIBL: 'South Indian Bank',
  SRCB: 'Saraswat Co-operative Bank',
  STBP: 'State Bank of Patiala',
  SURY: 'Suryoday Small Finance Bank',
  SVCB: 'SVC Co-Operative Bank Ltd.',
  SVCB_C: 'SVC Co-Operative Bank Ltd. - Corporate Banking',
  SYNB: 'Syndicate Bank',
  TBSB: 'Thane Bharat Sahakari Bank',
  TJSB: 'Thane Janata Sahakari Bank',
  TMBL: 'Tamilnadu Mercantile Bank',
  TNSC: 'Tamilnadu State Apex Co-operative Bank',
  UBIN: 'Union Bank of India',
  UCBA: 'UCO Bank',
  USFB: 'Ujjivan Small Finance Bank',
  UTBI: 'PNB (Erstwhile-United Bank of India)',
  UTIB: 'Axis Bank',
  UTIB_C: 'Axis Bank - Corporate Banking',
  VARA: 'Varachha Co-operative Bank',
  VIJB: 'Bank of Baroda - Retail Banking (Erstwhile Vijaya Bank)',
  YESB: 'Yes Bank',
  YESB_C: 'Yes Bank - Corporate Banking',
  ZCBL: 'Zoroastrian Co-operative Bank',
  PHBM: 'Affin Bank',
  PHBM_C: 'AFFINMAX',
  PMCB: 'Punjab & Maharashtra Co-operative Bank',
  MFBB_C: 'Alliance Bank (Business)',
  MFBB: 'Alliance Bank (Personal)',
  ARBK: 'AmBank',
  ARBK_C: 'AmBank',
  AGOB: 'AGRONet',
  AGOB_C: 'AGRONetBIZ',
  BNPA_C: 'BNP Paribas',
  BIMB_C: 'Bank Islam',
  BIMB: 'Bank Islam',
  BKRM_C: 'Bank Rakyat',
  BKRM: 'Bank Rakyat',
  BMMB_C: 'Bank Muamalat',
  BMMB: 'Bank Muamalat',
  BKCH: 'Bank Of China',
  BSNA: 'BSN',
  CIBB_C: 'CIMB Clicks',
  CIBB: 'CIMB Clicks',
  CITI_C: 'Citibank Corporate Banking',
  DEUT_C: 'Deutsche Bank',
  HSBC_C: 'HSBC Bank',
  HLBB_C: 'Hong Leong Bank',
  HLBB: 'Hong Leong Bank',
  KFHO_C: 'KFH',
  KFHO: 'KFH',
  MBBE_C: 'Maybank2E',
  MBBE: 'Maybank2E',
  MB2U: 'Maybank2U',
  OCBC_C: 'OCBC Bank',
  OCBC: 'OCBC Bank',
  PBBE_C: 'Public Bank',
  PBBE: 'Public Bank',
  PBBN_C: 'PB Enterprise',
  RHBB: 'RHB Bank',
  RHBB_C: 'RHB Bank',
  SCBL_C: 'Standard Chartered',
  UOVB: 'UOB Bank',
  UOVB_C: 'UOB Regional',
};

const getBankName = (bankCode) => bankNames[bankCode] || 'Unknown';

export { getQuery, aggTypes, bankNames, getBankName, paymentMethodsColumns };
