/**
 * Converts an array of items into an object, where the keys and values are generated by the provided iterator function.
 *
 * @template T - The type of elements in the input array.
 * @template K - The type for keys of the returned object.
 * @template V - The type for values of the returned object.
 *
 * @param {T[]} array - The input array to be transformed into an object.
 * @param {(item: T) => { key: K; value: V }} iterator - A function that takes an item and returns an object with 'key' and 'value' properties.
 * @returns {Record<K, V>} - An object constructed from the array using the keys and values returned by the iterator.
 *
 * @example
 * const array = [{ id: 1, name: 'apple' }, { id: 2, name: 'banana' }];
 * const result = arrayToObject(array, item => ({ key: item.id, value: item.name }));
 * console.log(result);
 * // Output: { 1: 'apple', 2: 'banana' }
 */
export const arrayToObject = <T, K extends keyof any, V>(
  array: T[] = [],
  iterator: (item: T) => { key: K; value: V }
): Record<K, V> => {
  return array.reduce((accumulator, currentItem) => {
    const { key, value } = iterator(currentItem);
    return {
      ...accumulator,
      [key]: value,
    };
  }, {} as Record<K, V>);
};
