<?php

namespace EE\Error;

class ErrorCode
{
    /**
     * The error codes are named such that the first word
     * tells where the error is supposed to originate.
     * Right now it can be GATEWAY, API, EE, Trace.
     *
     * The second word tells us what the error is related to.
     * Which can be either CARD, TRANSACTION, etc.
     */

    /**
     * General gateway specific error codes
     * Isn't specific to one particular gateway and
     * should be generally valid for gateways that
     * are added in future
     */
    const GATEWAY_ERROR_FATAL_ERROR                                 = 'GATEWAY_ERROR_FATAL_ERROR';

    const GATEWAY_ERROR_REQUEST_TIMEOUT                             = 'GATEWAY_ERROR_REQUEST_TIMEOUT';
    const GATEWAY_ERROR_AUTHENTICATION_NOT_AVAILABLE                = 'GATEWAY_ERROR_AUTHENTICATION_NOT_AVAILABLE';
    const GATEWAY_ERROR_INVALID_TERMINAL_ID                         = 'GATEWAY_ERROR_INVALID_TERMINAL_ID';
    const GATEWAY_ERROR_CERTIFICATE_VALIDATION_FAILED               = 'GATEWAY_ERROR_CERTIFICATE_VALIDATION_FAILED';
    const GATEWAY_ERROR_SIGNATURE_VALIDATION_FAILED                 = 'GATEWAY_ERROR_SIGNATURE_VALIDATION_FAILED';
    const GATEWAY_ERROR_INVALID_SUBSEQUENT_TRANSACTION              = 'GATEWAY_ERROR_INVALID_SUBSEQUENT_TRANSACTION';
    const GATEWAY_ERROR_SUPPORT_FAILED                              = 'GATEWAY_ERROR_SUPPORT_FAILED';
    const GATEWAY_ERROR_SUPPORT_AUTH_NOT_FOUND                      = 'GATEWAY_ERROR_SUPPORT_AUTH_NOT_FOUND';
    const GATEWAY_ERROR_CAPTURE_GREATER_THAN_AUTH                   = 'GATEWAY_ERROR_CAPTURE_GREATER_THAN_AUTH';
    const GATEWAY_ERROR_PARES_NOT_SUCCESFUL                         = 'GATEWAY_ERROR_PARES_NOT_SUCCESFUL';
    const GATEWAY_ERROR_NOT_UNDERSTOOD_ERROR                        = 'GATEWAY_ERROR_NOT_UNDERSTOOD_ERROR';
    const GATEWAY_ERROR_UNKNOWN_ERROR                               = 'GATEWAY_ERROR_UNKNOWN_ERROR';

    const GATEWAY_ERROR_SUPPORT_GREATER_THAN_AUTH                   = 'GATEWAY_ERROR_SUPPORT_GREATER_THAN_AUTH';

    const GATEWAY_ERROR_TRANSACTION_DUPLICATE_REQUEST               = 'GATEWAY_ERROR_TRANSACTION_DUPLICATE_REQUEST';
    const GATEWAY_ERROR_TRANSACTION_INVALID_AMOUNT                  = 'GATEWAY_ERROR_TRANSACTION_INVALID_AMOUNT';
    const GATEWAY_ERROR_TRANSACTION_MISSING_DATA                    = 'GATEWAY_ERROR_TRANSACTION_MISSING_DATA';
    const GATEWAY_ERROR_TRANSACTION_INVALID_ACTION                  = 'GATEWAY_ERROR_TRANSACTION_INVALID_ACTION';
    const GATEWAY_ERROR_TRANSACTION_INVALID_ID                      = 'GATEWAY_ERROR_TRANSACTION_INVALID_ID';
    const GATEWAY_ERROR_TRANSACTION_DENIED_NEGATIVE_BIN             = 'GATEWAY_ERROR_TRANSACTION_DENIED_NEGATIVE_BIN';
    const GATEWAY_ERROR_TRANSACTION_INVALID_CURRENCY                = 'GATEWAY_ERROR_TRANSACTION_INVALID_CURRENCY';
    const GATEWAY_ERROR_TRANSACTION_INVALID_UDF                     = 'GATEWAY_ERROR_TRANSACTION_INVALID_UDF';
    const GATEWAY_ERROR_TRANSACTION_CREDIT_LESS_THAN_DEBIT          = 'GATEWAY_ERROR_TRANSACTION_CREDIT_LESS_THAN_DEBIT';
    const GATEWAY_ERROR_TRANSACTION_SUPPORT_FAILED                  = 'GATEWAY_ERROR_TRANSACTION_SUPPORT_FAILED';
    const GATEWAY_ERROR_TRANSACTION_SUPPORT_AUTH_NOT_FOUND          = 'GATEWAY_ERROR_TRANSACTION_SUPPORT_AUTH_NOT_FOUND';
    const GATEWAY_ERROR_TRANSACTION_PARES_NOT_SUCCESFUL             = 'GATEWAY_ERROR_TRANSACTION_PARES_NOT_SUCCESFUL';

    const GATEWAY_ERROR_CARD_INVALID_NAME                           = 'GATEWAY_ERROR_CARD_INVALID_NAME';
    const GATEWAY_ERROR_CARD_INVALID_NUMBER                         = 'GATEWAY_ERROR_CARD_INVALID_NUMBER';
    const GATEWAY_ERROR_CARD_INVALID_EXPIRY_DATE                    = 'GATEWAY_ERROR_CARD_INVALID_EXPIRY_DATE';
    const GATEWAY_ERROR_CARD_INVALID_BRAND                          = 'GATEWAY_ERROR_CARD_INVALID_BRAND';
    const GATEWAY_ERROR_CARD_INVALID_AMOUNT                         = 'GATEWAY_ERROR_CARD_INVALID_AMOUNT';
    const GATEWAY_ERROR_CARD_INVALID_ADDRESS                        = 'GATEWAY_ERROR_CARD_INVALID_ADDRESS';
    const GATEWAY_ERROR_CARD_INVALID_ZIP                            = 'GATEWAY_ERROR_CARD_INVALID_ZIP';
    const GATEWAY_ERROR_CARD_INVALID_CVV                            = 'GATEWAY_ERROR_CARD_INVALID_CVV';
    const GATEWAY_ERROR_CARD_MISSING_CVV                            = 'GATEWAY_ERROR_CARD_MISSING_CVV';

    /**
     * Card errors catchable in the app
     */
    const CARD_ERROR_INVALID_NAME                                   = 'CARD_ERROR_INVALID_NAME';
    const CARD_ERROR_INVALID_EXPIRY_MONTH                           = 'CARD_ERROR_INVALID_EXPIRY_MONTH';
    const CARD_ERROR_INVALID_EXPIRY_YEAR                            = 'CARD_ERROR_INVALID_EXPIRY_YEAR';
    const CARD_ERROR_INVALID_EXPIRY_DATE                            = 'CARD_ERROR_INVALID_EXPIRY_DATE';
    const CARD_ERROR_INVALID_CVV                                    = 'CARD_ERROR_INVALID_CVV';
    const CARD_ERROR_INVALID_BRAND                                  = 'CARD_ERROR_INVALID_BRAND';
    const CARD_ERROR_INVALID_NUMBER                                 = 'CARD_ERROR_INVALID_NUMBER';
    const CARD_ERROR_CARD_DECLINED                                  = 'CARD_ERROR_CARD_DECLINED';
    const CARD_ERROR_INSUFFICIENT_BALANCE                           = 'CARD_ERROR_INSUFFICIENT_BALANCE';
    const CARD_ERROR_NOT_SUPPORTED                                  = 'CARD_ERROR_NOT_SUPPORTED';

    const FIELD_ERROR_INVALID_EMAIL                                 = 'FIELD_ERROR_INVALID_EMAIL';
    const FIELD_ERROR_INVALID_CONTACT                               = 'FIELD_ERROR_INVALID_CONTACT';

    const BAD_REQUEST_EXTRA_FIELDS_PROVIDED                         = 'BAD_REQUEST_EXTRA_FIELDS_PROVIDED';
    const BAD_REQUEST_TRANSACTION_ALREADY_CAPTURED                  = 'BAD_REQUEST_TRANSACTION_ALREADY_CAPTURED';
    const BAD_REQUEST_TRANSACTION_ALREADY_REFUNDED                  = 'BAD_REQUEST_TRANSACTION_ALREADY_REFUNDED';
    const BAD_REQUEST_INVALID_ID                                    = 'BAD_REQUEST_INVALID_ID';
    const BAD_REQUEST_TRANSACTION_CAPTURE_ONLY_AUTHORIZED           = 'BAD_REQUEST_TRANSACTION_CAPTURE_ONLY_AUTHORIZED';
    const BAD_REQUEST_CAPTURE_AMOUNT_GREATER_THAN_AUTH              = 'BAD_REQUEST_CAPTURE_AMOUNT_GREATER_THAN_AUTH';
    const BAD_REQUEST_URL_NOT_FOUND                                 = 'BAD_REQUEST_URL_NOT_FOUND';

    const BAD_REQUEST_ERROR                                         = 'BAD_REQUEST_ERROR';

    const BAD_REQUEST_KEY_EXPIRED                                   = 'BAD_REQUEST_KEY_EXPIRED';
    const BAD_REQUEST_KEY_EXPIRING_SOON                             = 'BAD_REQUEST_KEY_EXPIRING_SOON';

    const SERVER_ERROR_INVALID_ARGUMENT                             = 'SERVER_ERROR_INVALID_ARGUMENT';
    const SERVER_ERROR_DB_QUERY_FAILED                              = 'SERVER_ERROR_DB_QUERY_FAILED';

    const LOGICAL_ERROR_UNIDENTIFIED_CARD_NETWORK                   = 'LOGICAL_ERROR_UNIDENTIFIED_CARD_NETWORK';
    const LOGICAL_ERROR_TRANSACTION_NOT_CAPTURED                    = 'LOGICAL_ERROR_TRANSACTION_NOT_CAPTURED';
}