import { getCustomURL } from 'merchant/components/DocsLink';
import { SAMPLE_BATCH_REFUND_FILE_WITH_SPEED } from 'merchant/views/Transactions/v1/BatchRefunds/List';

export const mock_batch_data = {
  created_at: 1647074528,
  updated_at: 1647074576,
  id: 'batch_J67Dx0WyiY80FW',
  entity_id: '10000000000000',
  name: 'testing',
  batch_type_id: 'refund',
  mode: 'test',
  creator_id: null,
  creator_type: null,
  is_scheduled: false,
  upload_count: 0,
  processed_count: 1,
  failure_count: 0,
  total_count: 1,
  success_count: 1,
  attempts: 0,
  status: 'processed',
  amount: 0,
  processed_amount: 0,
  schedule_time: null,
  type: 'refund',
  entity: 'batch',
  config: null,
};

export const mock_refund_items = [
  {
    id: 'batch_83Gwbilr4Fzm5s',
    entity: 'batch',
    name: null,
    type: 'refund',
    status: 'created',
    total_count: 1,
    success_count: 0,
    failure_count: 1,
    attempts: 1,
    amount: 100000,
    processed_amount: 0,
    processed_at: 1556009054,
    created_at: 1497545788,
  },
  {
    id: 'batch_6T5mcGutwjMw8m',
    entity: 'batch',
    name: null,
    type: 'payment_link',
    status: 'processed',
    total_count: 3,
    success_count: 2,
    failure_count: 1,
    attempts: 3,
    amount: 300,
    processed_amount: 200,
    processed_at: 1476441568,
    created_at: 1476109152,
  },
  {
    id: 'batch_6T5a0K5i6uVqkb',
    entity: 'batch',
    name: null,
    type: 'refund',
    status: 'processed',
    total_count: 4,
    success_count: 3,
    failure_count: 1,
    attempts: 3,
    amount: 2300,
    processed_amount: 300,
    processed_at: 1476441469,
    created_at: 1476108435,
  },
];

export const batchListInitProps = {
  form: 'batchListFilter',
  count: 25,
  skip: '0',
  batchType: 'refund',
  paginate: () => {},
  onSubmit: () => {},
  sampleUrl: SAMPLE_BATCH_REFUND_FILE_WITH_SPEED,
  docUrl: getCustomURL('https://razorpay.com/docs/payments/refunds/batch/'),
  uploadUrl: '/refunds/batchupload',
  items: mock_refund_items,
};
