<?php

use EE\Error\ErrorCode;
use EE\Error\PublicErrorCode;
use EE\Error\PublicErrorDescription;

return [
    'testPayment' => [
        'merchant_id' => '10000000000000',
        'amount' => 500,
        'method' => 'netbanking',
        'status' => 'captured',
        'amount_authorized' => 500,
        'amount_refunded' => 0,
        'refund_status' => null,
        'currency' => 'INR',
        'description' => 'random description',
        'bank' => 'SBIN',
        'error_code' => null,
        'error_description' => null,
        'email' => 'a@b.com',
        'contact' => '9918899029',
        'notes' => [
            'merchant_order_id' => 'random order id',
        ],
        'gateway' => 'sbiepay',
        'terminal_id' => '10000SbiEpayTl',
        'signed' => false,
        'verified' => null,
        'entity' => 'payment',
    ],

    'testPaymentSbiepayEntity' => [
        'action' => 'authorize',
        'method' => 'netbanking',
        'received' => true,
        'MerchantId'=> '1000109',
        'OperatingMode'=> 'DOM',
        'MerchantCountry'=> 'IN',
        'MerchantCurrency'=> 'INR',
        'PostingAmount'=> '5.00',
        'OtherDetails'=> 'NA',
        'AggregatorId'=> 'SBIEPAY',
//        'MerchantOrderNo'=> null,
        'MerchantCustomerID'=> 'a@b.com',
        'Paymode'=> 'NB',
        'Accesmedium'=> 'ONLINE',
        'TransactionSource'=> 'ONLINE',
//        'SBIePayReferenceID'=> null,
        'Status'=> 'SUCCESS',
//        'Reason'=> null,
//        'BankCode'=> null,
//        'BankReferenceNumber'=> null,
//        'TransactionDate'=> null,
//        'CIN'=> null,
//        'refund_id'=> null,
    ],

    'testPaymentRefund' => [
        'action' => 'refund',
        'method' => 'netbanking',
        'received' => true,
        'MerchantId'=> '1000109',
//        'OperatingMode'=> 'DOM',
//        'MerchantCountry'=> 'IN',
        'MerchantCurrency'=> 'INR',
        'PostingAmount'=> '5.00',
//        'OtherDetails'=> 'NA',
        'AggregatorId'=> 'SBIEPAY',
//        'MerchantOrderNo'=> null,
//        'MerchantCustomerID'=> 'a@b.com',
//        'Paymode'=> 'NB',
//        'Accesmedium'=> 'ONLINE',
//        'TransactionSource'=> 'ONLINE',
//        'SBIePayReferenceID'=> null,
        'Status'=> 'SUCCESS',
//        'Reason'=> null,
//        'BankCode'=> null,
//        'BankReferenceNumber'=> null,
//        'TransactionDate'=> null,
//        'CIN'=> null,
//        'refund_id'=> null,
    ],

];