<?php

use RZP\Reconciliator\Base;

// TODO: Work on this for Sbi Upi

class Reconciliate extends Base\Reconciliate
{
    public function inExcludeList(array $fileDetails)
    {
        return parent::inExcludeList($fileDetails); // TODO: Change the autogenerated stub
    }

    public function getStartRow($fileDetails)
    {
        return parent::getStartRow($fileDetails); // TODO: Change the autogenerated stub
    }

    protected function getTypeName($fileName)
    {
        return parent::getTypeName($fileName); // TODO: Change the autogenerated stub
    }


}