<?php

namespace RZP\Gateway\Upi\Base;

use RZP\Error\ErrorCode;

class UpiErrorCodes
{
    protected static $errorCodes = [
        // Error Codes
        'U28'   => 'PSP NOT AVAILABLE',
        'U88'   => 'CONNECTION TIMEOUT IN REQPAY CREDIT',
        'U68'   => 'CREDIT TIMEOUT',
        'U31'   => 'CREDIT HAS BEEN FAILED',
        // Response Codes
        'BT'    => 'Transaction is pending (BT).',
        'XY'    => 'REMITTER CBS OFFLINE',
        'XC'    => 'INVALID TRANSACTION OR IF MEMBER IS NOT ABLE TO FIND ANY APPROPRIATE RESPONSE CODE (BENEFICIARY)',
        'ZY'    => 'INACTIVE OR DORMANT ACCOUNT (BENEFICIARY)',
        'XI'    => 'ACCOUNT DOES NOT EXIST (BENEFICIARY)',
        'Z5'    => 'INVALID BENEFICIARY CREDENTIALS',
        'YF'    => 'BENEFICIARY ACCOUNT BLOCKED/FROZEN',
        'Y1'    => 'BENEFICIARY CBS OFFLINE',
        'UB'    => 'UNABLE TO PROCESS DUE TO INTERNAL EXCEPTION AT SERVER/CBS/ETC ON BENEFICIARY SIDE',
        'XW'    => 'TRANSACTION CANNOT BE COMPLETED. COMPLIANCE VIOLATION (BENEFICIARY)',
        'XQ'    => 'TRANSACTION NOT PERMITTED TO CARDHOLDER (BENEFICIARY)',
        'XM'    => 'EXPIRED CARD, DECLINE (BENEFICIARY)',
        'XB'    => 'INVALID TRANSACTION OR IF MEMBER IS NOT ABLE TO FIND ANY APPROPRIATE RESPONSE CODE (REMITTER)',
        'RB'    => 'CREDIT REVERSAL TIMEOUT(REVERSAL)',
        'ZD'    => 'VALIDATION ERROR',
        'NO'    => 'NO ORIGINAL REQUEST FOUND DURING DEBIT/CREDIT',
        'B3'    => 'TRANSACTION NOT PERMITTED TO THE ACCOUNT',
        'Z9'    => 'INSUFFICIENT FUNDS IN CUSTOMER (REMITTER) ACCOUNT',
        'ZI'    => 'SUSPECTED FRAUD, DECLINE / TRANSACTIONS DECLINED BASED ON RISK SCORE BY BENEFICIARY',
        'XU'    => 'CUT-OFF IS IN PROCESS (BENEFICIARY)',
        'LC'    => 'UNABLE TO PROCESS CREDIT FROM BANK\'S POOL/BGL ACCOUNT',
        'DF'    => 'DUPLICATE RRN FOUND IN THE TRANSACTION. (BENEFICIARY)',
        'YD'    => 'DO NOT HONOUR (BENEFICIARY)',
        'K1'    => 'SUSPECTED FRAUD, DECLINE / TRANSACTIONS DECLINED BASED ON RISK SCORE BY REMITTER',
        'NA'    => 'TRANSACTION FAILED',
        'RNF'   => 'TRANSACTION FAILED',
    ];

    protected static $errorCodeMap = [
        // Error Codes
        'U28'   => ErrorCode::GATEWAY_ERROR_PSP_NOT_AVAILABLE,
        'U88'   => ErrorCode::GATEWAY_ERROR_CONNECTION_TIMEOUT_IN_REQPAY_CREDIT,
        'U68'   => ErrorCode::GATEWAY_ERROR_CREDIT_TIMEOUT,
        'U31'   => ErrorCode::GATEWAY_ERROR_CREDIT_FAILED,
        // Response codes
        'BT'    => ErrorCode::GATEWAY_ERROR_TRANSACTION_PENDING,
        'XY'    => ErrorCode::GATEWAY_ERROR_REMITTER_CBS_OFFLINE,
        'XC'    => ErrorCode::GATEWAY_ERROR_INVALID_TRANSACTION_INAPPROPRIATE_CODE_BENEFICIARY,
        'ZY'    => ErrorCode::GATEWAY_ERROR_INACTIVE_DORMANT_BENEFICIARY_ACCOUNT,
        'XI'    => ErrorCode::GATEWAY_ERROR_BENEFICIARY_ACCOUNT_DOES_NOT_EXIST,
        'Z5'    => ErrorCode::GATEWAY_ERROR_INVALID_BENEFICIARY_CREDENTIALS,
        'YF'    => ErrorCode::GATEWAY_ERROR_BENEFICIARY_ACCOUNT_BLOCKED,
        'Y1'    => ErrorCode::GATEWAY_ERROR_BENEFICIARY_CBS_OFFLINE,
        'UB'    => ErrorCode::GATEWAY_ERROR_BENEFICIARY_INTERNAL_EXCEPTION,
        'XW'    => ErrorCode::GATEWAY_ERROR_BENEFICIARY_COMPLIANCE_VIOLATION,
        'XQ'    => ErrorCode::GATEWAY_ERROR_BENEFICIARY_TRANSACTION_NOT_PERMITTED,
        'XM'    => ErrorCode::GATEWAY_ERROR_BENEFICIARY_EXPIRED_CARD,
        'XB'    => ErrorCode::GATEWAY_ERROR_INVALID_TRANSACTION_INAPPROPRIATE_CODE_REMITTER,
        'RB'    => ErrorCode::GATEWAY_ERROR_CREDIT_REVERSAL_TIMEOUT,
        'ZD'    => ErrorCode::GATEWAY_ERROR_VALIDATION_ERROR,
        'NO'    => ErrorCode::GATEWAY_ERROR_NO_ORIGINAL_DEBIT_CREDIT_REQUEST_FOUND,
        'B3'    => ErrorCode::GATEWAY_ERROR_TRANSACTION_NOT_PERMITTED,
        'Z9'    => ErrorCode::GATEWAY_ERROR_INSUFFICIENT_FUNDS_REMITTER_ACCOUNT,
        'ZI'    => ErrorCode::GATEWAY_ERROR_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK_BENEFICARY,
        'XU'    => ErrorCode::GATEWAY_ERROR_BENEFICIARY_CUTOFF_IN_PROGRESS,
        'LC'    => ErrorCode::GATEWAY_ERROR_BANK_ACCOUNT_CREDIT_PROCESS_FAILED,
        'DF'    => ErrorCode::GATEWAY_ERROR_BENEFICIARY_DUPLICATE_RRN_FOUND,
        'YD'    => ErrorCode::GATEWAY_ERROR_DO_NOT_HONOUR_BENEFICIARY,
        'K1'    => ErrorCode::GATEWAY_ERROR_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK_REMITTER,
        'NA'    => ErrorCode::BAD_REQUEST_REFUND_FAILED,
        'RNF'   => ErrorCode::BAD_REQUEST_REFUND_FAILED,
    ];

    public static function getApiErrorCode($code = null)
    {
        if (isset(self::$errorCodeMap[$code]))
        {
            return self::$errorCodeMap[$code];
        }

        return ErrorCode::GATEWAY_ERROR_FATAL_ERROR;
    }

    public static function getResponseCodeMessage($code)
    {
        return self::$errorCodes[$code] ?? 'Unknown Gateway Response Code';
    }
}
