<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width"></head><body style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; margin: 0; min-width: 100%; padding: 0; width: 100% !important; color: #222222; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 19px; text-align: left; font-size: 14px;">
    <link rel="stylesheet" type="text/css" href="ink.css"><link rel="stylesheet" type="text/css" href="welcome.css"><table class="row" style="border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="wrapper" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; color: #222222; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative;">

          <table class="four columns" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="center" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; color: #222222; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <img class="center" src="https://cdn.razorpay.com/logo.svg" style="-ms-interpolation-mode: bicubic; clear: both; display: block; float: none; max-width: 100%; outline: none; text-decoration: none; width: auto; margin: 0 auto;"></td>
              <td class="expander" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; color: #222222; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
            </tr></table></td>
      </tr></table><!-- Heading --><table class="row" style="border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="wrapper last" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; color: #222222; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative; padding-right: 0px;">

          <table class="twelve columns" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="center" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; color: #222222; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <hr style="background-color: #d9d9d9; border: none; color: #E5E5E5; height: 2px;"><br><h1 style="color: #444333; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: bold; line-height: 24px; margin: 0; padding: 0; text-align: center; word-break: normal; font-size: 36px; margin-top: 40px;"><center style="min-width: 580px; width: 100%;">
                  Welcome Onboard
                </center></h1>
              </td>
              <td class="expander" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; color: #222222; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
            </tr></table></td>
      </tr></table><!-- Contact Us --><table class="container" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; color: #222222; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
          <table class="row" style="border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="wrapper offset-by-one" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; color: #222222; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative; padding-left: 50px;">
                <table class="ten columns" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 480px;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="center welcome" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; color: #2d2d2d; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 24px; margin: 10px 0px 10px 0px; font-size: 16px; background: white;">
<p style="margin: 10px 0px 10px 0px; color: #2d2d2d; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 24px; padding: 0; text-align: justify; font-size: 16px; margin-bottom: 20px; background: white;">Hi {{{$name}}},</p>

<p style="margin: 10px 0px 10px 0px; color: #2d2d2d; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 24px; padding: 0; text-align: justify; font-size: 16px; margin-bottom: 20px; background: white;">
  Welcome to the Razorpay family.
  <br>
  In order for us to take you live, here are the next steps and timelines:
</p>

<h3 style="color: #1aace5; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: bold; line-height: 24px; margin: 0; padding: 0; text-align: left; word-break: normal; font-size: 28px; margin-top: 40px; margin-bottom: 20px;">KYC Process</h3>

<p style="margin: 10px 0px 10px 0px; color: #2d2d2d; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 24px; padding: 0; text-align: justify; font-size: 16px; margin-bottom: 20px; background: white;">The first step involves filling up the activation form on the <a href="https://dashboard.razorpay.com" style="color: #24bbea; text-decoration: none !important;">Razorpay Dashboard</a>. The list of documents and details required for us to take you live can be found then in the <a href="https://dashboard.razorpay.com/#/app/activation" style="color: #24bbea; text-decoration: none !important;">Activation</a> panel. All requirements have a basic explanation alongside to help you through the process.

</p><p style="margin: 10px 0px 10px 0px; color: #2d2d2d; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 24px; padding: 0; text-align: justify; font-size: 16px; margin-bottom: 20px; background: white;">This process is crucial as we share the same KYC with our partner banks who do their own due diligence. Also, signing up allows you to <a href="https://dashboard.razorpay.com/#/app/keys" style="color: #24bbea; text-decoration: none !important;">generate test keys</a> from our dashboard which can be used for integrating payments in your product. You can just swap your test keys with your live keys once your account is activated.</p>

<h3 style="color: #1aace5; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: bold; line-height: 24px; margin: 0; padding: 0; text-align: left; word-break: normal; font-size: 28px; margin-top: 40px; margin-bottom: 20px;">API Integration</h3>

<p style="margin: 10px 0px 10px 0px; color: #2d2d2d; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 24px; padding: 0; text-align: justify; font-size: 16px; margin-bottom: 20px; background: white;">In parallel, you can start integrating our API with your product. Various integrations (including Mobile SDKs and Plugins) are available at <a href="https://razorpay.com/integrations" style="color: #24bbea; text-decoration: none !important;">razorpay.com/integrations</a>. The API documentation is available at <a href="https://razorpay.com/docs/" style="color: #24bbea; text-decoration: none !important;">razorpay.com/docs</a>. Feel free to reach out to us <a href="https://dashboard.razorpay.com/#/app/dashboard#request" style="color: #24bbea; text-decoration: none !important;">here</a> in case of any queries.</p>

<h3 style="color: #1aace5; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: bold; line-height: 24px; margin: 0; padding: 0; text-align: left; word-break: normal; font-size: 28px; margin-top: 40px; margin-bottom: 20px;">Activation Timeline</h3>

<p style="margin: 10px 0px 10px 0px; color: #2d2d2d; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 24px; padding: 0; text-align: justify; font-size: 16px; margin-bottom: 20px; background: white;">As soon as the KYC Process in completed by you, depending on the business segment, we will take you live in the upcoming 2-3 days.</p>

<p style="margin: 10px 0px 10px 0px; color: #2d2d2d; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 24px; padding: 0; text-align: justify; font-size: 16px; margin-bottom: 20px; background: white;">
  Cheers,
  <br>
  Team Razorpay
</p>
                    </td>
                    <td class="expander" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; color: #222222; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                  </tr></table></td>
            </tr></table></td>
      </tr></table><table class="row footer" style="border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="wrapper last" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; color: #aaa; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 18px; margin: 0; font-size: 12px; position: relative; padding-right: 0px;">

          <table class="twelve columns" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="center" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; color: #aaa; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 18px; margin: 0; font-size: 12px;">
                <center style="min-width: 580px; width: 100%;">
                  <hr style="background-color: #d9d9d9; border: none; color: #E5E5E5; height: 2px;"><a href="https://razorpay.com/terms/" style="color: #aaa !important; text-decoration: none; display: inline-block;">Terms &amp; Conditions</a>
                  |
                  <a href="https://razorpay.com/privacy/" style="color: #aaa !important; text-decoration: none; display: inline-block;">Privacy Policy</a>
                  |
                  <a href="https://razorpay.com/refund/" style="color: #aaa !important; text-decoration: none; display: inline-block;">Refund Policy</a>
                </center>
              </td>
              <td class="expander" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; color: #aaa; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 18px; margin: 0; font-size: 12px; visibility: hidden; width: 0px;"></td>
            </tr></table></td>
      </tr></table><table class="row footer" style="border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="wrapper last" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; color: #aaa; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 18px; margin: 0; font-size: 12px; position: relative; padding-right: 0px;">

          <table class="three columns offset-by-six" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 130px;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="center" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; color: #aaa; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 18px; margin: 0; font-size: 12px;">
                <center style="min-width: 130px; width: 100%;">
                  <a href="https://facebook.com/razorpay" class="logo" style="color: #aaa !important; text-decoration: none; display: inline-block; float: left !important; height: 22px; padding: 0px 5px 0px 5px; width: 22px;">
                    <img height="22" width="22" src="https://cdn.razorpay.com/facebook.png" alt="Facebook Icon" title="Razorpay on Facebook" style="-ms-interpolation-mode: bicubic; clear: both; display: block; float: none; max-width: 100%; outline: none; text-decoration: none; width: auto; border: none;"></a>
                  <a href="https://twitter.com/razorpay" class="logo" style="color: #aaa !important; text-decoration: none; display: inline-block; float: left !important; height: 22px; padding: 0px 5px 0px 5px; width: 22px;">
                    <img height="22" width="22" src="https://cdn.razorpay.com/twitter.png" alt="Twitter Icon" title="Razorpay on Twitter" style="-ms-interpolation-mode: bicubic; clear: both; display: block; float: none; max-width: 100%; outline: none; text-decoration: none; width: auto; border: none;"></a>
                  <a href="https://github.com/razorpay" class="logo" style="color: #aaa !important; text-decoration: none; display: inline-block; float: left !important; height: 22px; padding: 0px 5px 0px 5px; width: 22px;">
                    <img height="22" width="22" src="https://cdn.razorpay.com/github.png" alt="GitHub Icon" title="Razorpay on GitHub" style="-ms-interpolation-mode: bicubic; clear: both; display: block; float: none; max-width: 100%; outline: none; text-decoration: none; width: auto; border: none;"></a>
                </center>
              </td>
              <td class="expander" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; color: #aaa; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 18px; margin: 0; font-size: 12px; visibility: hidden; width: 0px;"></td>
            </tr></table></td>
      </tr></table><table class="row footer" style="border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="wrapper last" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; color: #aaa; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 18px; margin: 0; font-size: 12px; position: relative; padding-right: 0px;">

          <table class="seven columns" style="border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 330px;"><tr style="padding: 0; text-align: left; vertical-align: top;"><td class="center" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; color: #aaa; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 18px; margin: 0; font-size: 12px;">
                <center style="min-width: 330px; width: 100%;">
                  This message was sent to <a href="mailto:{{$email}}" style="color: #aaa !important; text-decoration: none; display: inline-block;">
                  {{{$email}}}</a>. @include('emails.partials.support')
                </center>
              </td>
              <td class="expander" style="-moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; color: #aaa; font-family: -apple-system,'.SFNSDisplay','Oxygen','Ubuntu','Roboto','Segoe UI','Helvetica Neue','Lucida Grande',sans-serif; font-weight: normal; line-height: 18px; margin: 0; font-size: 12px; visibility: hidden; width: 0px;"></td>
            </tr></table></td>
      </tr></table></body></html>
