<?php

namespace RZP\Models\Payment\Downtime;

final class Metric
{
    const ECO_SYSTEM_CACHE_REFRESH_DURATION      = 'ECO_SYSTEM_CACHE_REFRESH_DURATION';
    const ECO_SYSTEM_CACHE_REFRESH_COUNT         = 'ECO_SYSTEM_CACHE_REFRESH_COUNT';

    // Webhooks
    const DOWNTIME_WEBHOOK_ATTEMPTED_COUNT       = 'DOWNTIME_WEBHOOK_ATTEMPTED_COUNT';
    const DOWNTIME_WEBHOOK_FAILED_COUNT          = 'DOWNTIME_WEBHOOK_FAILED_COUNT';

    // PAYMENT DOWNTIME EVENT JOB
    const PAYMENT_DOWNTIME_EVENT_JOB_COUNT          = 'PAYMENT_DOWNTIME_EVENT_JOB_COUNT';
    const PAYMENT_DOWNTIME_EVENT_JOB_DURATION       = 'PAYMENT_DOWNTIME_EVENT_JOB_DURATION';

    // PG AVAILABILITY
    const PG_AVAILABILITY_WEBHOOK_RECEIVED = 'PG_AVAILABILITY_WEBHOOK_RECEIVED';
}
