<?php

namespace RZP\Models\EMandate;

class Constants
{
    const EMANDATE_MERCHANT_CONFIGURATIONS = "emandate_merchant_configurations";
    
    const RETRY_ATTEMPTS = "retry_attempts";
    
    const COOLDOWN_PERIOD = "cooldown_period";
    
    const TEMPORARY_ERRORS_ENABLE_FLAG = "temporary_errors_enable_flag";
    
    const PERMANENT_ERRORS_ENABLE_FLAG = "permanent_errors_enable_flag";
    
    const EMANDATE_CONFIG_FIELDS = [
        self::RETRY_ATTEMPTS,
        self::COOLDOWN_PERIOD,
        self::TEMPORARY_ERRORS_ENABLE_FLAG,
        self::PERMANENT_ERRORS_ENABLE_FLAG
    ];
    
    const EMANDATE_DEBIT_COOLDOWN = 3;
    
    const EMANDATE_DEBIT_ATTEMPTS = 3;
    
    const NR_FLOW = "nr_flow";
    
    const ACH_RETURNS_FLOW = "ach_returns_flow";
    
    const MERCHANT_IDS = "merchant_ids";

    const MATCH_PERCENT = 75;
    
    const CITI_SDN_BLACKLISTED_NAMES = [
        "aurum ship management fzc",
        "bushra ship management private limited",
        "dawood ibrahim organization",
        "elvegard shipping ltd",
        "global relief foundation, inc.",
        "harakat-ul jihad islami",
        "indian mujahideen",
        "iran petrochemical commercial company",
        "khadija ship management private limited",
        "korea computer center",
        "maiwand beverages limited",
        "maiwand exim private limited",
        "maiwand tobacco limited",
        "mehdi group",
        "peridot shipping and trading llc",
        "petrochemical commercial company fze",
        "tibalaji petrochem private limited",
        "vaniya ship management private limited",
        "rajesh gupta",
        "ajay gupta",
        "atul gupta",
        "jasmeet singh",
        "akhilesh kumar",
        "shakeel ahmed",
        "mohammed shaheed ruknooddin bhore",
        "deepak jadhav",
        "ibrahim abdul razaaq memon",
        "chhota shakeel",
        "chiranjeev kumar singh",
        "dawood ibrahim",
        "aurum ship management pte. ltd.",
        "bushra ship management pvt ltd",
        "d company",
        "fondation secours mondial a.s.b.l.",
        "huji-b",
        "indian mujahedeen",
        "sherkate bazargani petrchemie",
        "khadija ship management pvt ltd",
        "korea computer company",
        "mehdi bros ship services pvt ltd",
        "peridot ship management",
        "pcc fze",
        "tibalaji petrochem pvt. ltd.",
        "vaniya ship management ltd",
        "rajesh kumar gupta",
        "ajay kumar gupta",
        "atul kumar gupta",
        "hakimzada jasmeet",
        "chota shakeel",
        "deepak subhash jadhav",
        "ibrahim abdul razak memon",
        "cheeranjeev kumar singh",
        "dawood ebrahim",
        "aurum ship management",
        "fondation secours mondial-belgique a.s.b.l.",
        "islami dawat-e-kafela",
        "indian mujahidin",
        "sherkate basargani petrochemie (sahami khass)",
        "khadija ship management pvt",
        "choson computer center",
        "mehdi bros ship serv. pvt. ltd.",
        "peridot shipping & trading llc",
        "tiba petrochem private limited",
        "vaniya ship management pvt ltd",
        "tony gupta",
        "chhota shakil",
        "tiger memon",
        "dawood hassan",
        "fondation secours mondial-kosova",
        "idek",
        "islamic security force-indian mujahideen (isf-im)",
        "petrochemical commercial company",
        "chung sun computer center",
        "mehdi bros. ship services private limited",
        "vaniya ship management",
        "shaikh shakil babu mohiddin",
        "mushtaw",
        "dawood sheik ibrahim",
        "fondation secours mondial vzw",
        "harakat ul-jihad e islami bangladesh",
        "ipcc",
        "mehdi brothers ship services pvt. ltd.",
        "sheikh shakeel ahmed",
        "mustaq",
        "dawood ibrahim kaskar",
        "fondation secours mondial 'world relief'",
        "harkatul jihad al islam",
        "pcc",
        "mehdi shipping limited",
        "sikander",
        "dawood sabri",
        "fsm",
        "harkatul jihad",
        "mehdi offshore and ship management pte. ltd.",
        "amir saheb",
        "stichting wereldhulp-belgie, v.z.w.",
        "harakat ul jihad al islami",
        "mehdi group offshore",
        "iqbal seth",
        "secours mondial de france",
        "harkat ul jihad al islami",
        "mehdi offshore and ship management",
        "shaikh ismail abdul rehman",
        "harkat-ul-jehad-al-islami",
        "abdul hamid abdul aziz",
        "harakat ul jihad islami bangladesh",
        "aziz dilip",
        "huji",
        "ibrahim shaikh mohd anis",
        "movement of islamic holy war",
        "shaikh daud hasan",
        "harkat-ul-jihad-al islami",
        "anis ibrahim",
        "harkat-al-jihad-ul islami",
        "harakat ul jihad-e-islami",
        "mohammad haji baz",
        "kumar akhilesh",
        "ahmed sheikh shakeel",
        "sing har mohan",
        "gupta ajay",
        "aziz abdul",
        "khan abdul qadeer",
        "gupta rajesh kumar",
        "gupta rajesh",
        "mazhar mohammad",
        "singh jasmeet",
        "gupta ajay kumar",
        "mazhar mohammed",
        "azhar mohammad",
        "gupta atul kumar",
        "alam mohammad jahangir",
        "aziz abdul hamid abdul",
        "amir khan",
        "ibrahim mohammed hassan",
        "santos hilarion del rosario",
        "majeed abdul",
        "ranjeet singh",
        "ali mohammed",
        "nasrallah mohammad jawad",
        "jabir mohammad",
        "sani samad",
        "khader abdel",
        "shahbaz khan",
        "ahmad najmuddin faraj",
        "hassan dawood",
        "jadhav deepak",
        "shah syed mohammed yusuf",
        "haq abdul",
        "maruf muhammad",
        "ahmed sheikh shakeel",
        "shah mohd yousuf",
        "subramaniam sharda",
        "shah mohammad yusuf",
        "chang chi fu",
        "bhardwaj anuj",
        "umar asim",
        "haq sanaul",
        "singh chiranjeev kumar",
        "dutta surya visesh",
        "shah mohd yusuf",
        "satsa",
        "vishnu inc",
        "sunshine",
        "seth iqbal",
        "afrin",
        "raza syed ali",
        "a'raj sami",
        "mohammad baz",
        "shakeel chota",
        "hakimzada harmohan singh",
        "zamani aziz shah",
        "zaman hayder",
        "gupta tony",
        "gupta atul",
        "ebrahim dawood",
        "ghulam nabi khan",
        "uways hassan tahir",
        "hilarion santos iii (third)",
        "majid abdul",
        "neeta",
        "ali mohammad labolo",
        "nasrallah juad",
        "jabir muhammad mahruz",
        "haji nika",
        "salem abdarrahmane ould mohamed el houcein ould mohamed",
        "al shahboz khan general trading llc.",
        "krekar mullah",
        "jadhav deepak subhash",
        "heq abdul",
        "musanna maulana",
        "khun sa",
        "umer asim",
        "shah mohammad yousuf",
        "servicios aduanales y transitarios sa",
        "raza zaidi syed ali",
        "al-'ajuz sami jasim muhammad",
        "shakil chhota",
        "baloch abdul aziz",
        "mahazar maulawi mohammad",
        "saifullah khalid",
        "sheikh aweys",
        "ahmed islam",
        "majeed chaudhry abdul",
        "otim kapere",
        "nasrallah jawad",
        "jabir muhammad muhraz",
        "haji nika ishaqzai",
        "al-mauritani yunis",
        "farraj fateh najm eddine",
        "ibrahim dawood sheik",
        "abuduhake",
        "ubaidullah maulana",
        "chan changtrakul",
        "singh cheeranjeev kumar",
        "muhammad sami jasim",
        "mohiddin shaikh shakil babu",
        "mazhar maulana hakim mohammad",
        "jawaad",
        "hassan tahir oais",
        "abu hamsa",
        "ali mohammed salongo",
        "ja far abu",
        "haji salani",
        "al-mauritani younis",
        "najmuddin faraj ahmad",
        "kaskar dawood ibrahim",
        "jundullah abdulheq",
        "hamzah ali",
        "shah mohd yosuf",
        "chang shi-fu",
        "al-'ajuz sami jasim",
        "mazar maulana",
        "mazhar molavi muhammad",
        "sabri dawood",
        "mohammed hassan ibrahim",
        "lakay",
        "ali mohammed kony",
        "jabir muhammad",
        "sani abdul samad",
        "the mauritanian shaykh yunis",
        "saheb amir",
        "shah mohammed yusaf",
        "maimaiti maimaitiming",
        "changtrakul chan",
        "asiya abu",
        "mazhar molana",
        "dahir aweys hassan",
        "hilarion del rosario santos iii",
        "ali lalobo bashir",
        "ja'far abu",
        "the mauritanian salih",
        "salahuddin syed",
        "memeti memetiming",
        "samiyah abu",
        "mazhar hakim",
        "ali sheikh hassan dahir aweys",
        "aqi",
        "kony ali",
        "jaber mohammad",
        "salem mohamed",
        "rehman shaikh ismail abdul",
        "salahudin syed",
        "aximu memetiming",
        "sumayyah abu",
        "mazhar hakeem mohammad",
        "aweys hassan dahir",
        "abu abdullah santos",
        "bashir",
        "jelil youssef ould abdel",
        "salahudeen sayeed",
        "qekeman memetiming",
        "hamad hajji",
        "mazar hakim muhammed",
        "dilip aziz",
        "aweys sheikh",
        "ahmad islam santos",
        "one-p",
        "ghader el hadj ould abdel",
        "peer sahib",
        "iman maimaiti",
        "hamid hajji",
        "anis ibrahim shaikh mohd",
        "hassansheikh",
        "akmad santos",
        "ali mohammed lalobo",
        "souleimane abou",
        "salauddin",
        "maimaiti maiumaitimin",
        "hamid ustadh",
        "hasan shaikh daud",
        "awes shaykh hassan dahir",
        "aki",
        "ali bashir lalobo",
        "chingheity",
        "saimaiti abdul",
        "al-jaburi sami jasim muhammad",
        "ibrahim anis",
        "sheikh hassan",
        "1-p",
        "salim 'abd al-rahman ould muhammad al-husayn ould muhammad",
        "khaliq muhammad ahmed",
        "ibrahim dawood",
        "awes hassan dahir",
        "ali lalobo",
        "muhelisi",
        "sheikh hassan dahir aweys",
        "caesar",
        "qerman",
        "hassan dahir awes",
        "saifuding",
        "hassen dahir aweyes",
        "oais hassan tahir",
        "aweyes hassen dahir",
        "aweys sheikh hassan dahir",
        "aweys ahmed dahir",
        "hassan tahir uways"
    ];
}
