package linked_account_activation

type LinkedAccountCreateResponse struct {
	Id                string `json:"id"`
	Entity            string `json:"entity"`
	Name              string `json:"name"`
	Email             string `json:"email"`
	Live              string `json:"live"`
	Managed           string `json:"managed"`
	TncAccepted       string `json:"tnc_accepted"`
	ActivationDetails struct {
		Status                       string `json:"status"`
		ActivatedAt                  int    `json:"activated_at"`
		CanSubmit                    bool   `json:"can_submit"`
		BankDetailsVerificationError string `json:"bank_details_verification_error"`
	} `json:"activation_details"`
}

type MerchantActivationDetails struct {
	ContactName                           interface{}   `json:"contact_name"`
	ContactEmail                          string        `json:"contact_email"`
	ContactMobile                         interface{}   `json:"contact_mobile"`
	ContactLandline                       interface{}   `json:"contact_landline"`
	BusinessType                          string        `json:"business_type"`
	BusinessName                          string        `json:"business_name"`
	BusinessDescription                   interface{}   `json:"business_description"`
	PromoterPan                           interface{}   `json:"promoter_pan"`
	PromoterPanName                       interface{}   `json:"promoter_pan_name"`
	ActivationProgress                    int           `json:"activation_progress"`
	Locked                                bool          `json:"locked"`
	ActivationStatus                      string        `json:"activation_status"`
	BankDetailsVerificationStatus         string        `json:"bank_details_verification_status"`
	PoaVerificationStatus                 interface{}   `json:"poa_verification_status"`
	PoiVerificationStatus                 interface{}   `json:"poi_verification_status"`
	ClarificationMode                     interface{}   `json:"clarification_mode"`
	Archived                              int           `json:"archived"`
	AllowedNextActivationStatuses         []interface{} `json:"allowed_next_activation_statuses"`
	MarketplaceActivationStatus           interface{}   `json:"marketplace_activation_status"`
	VirtualAccountsActivationStatus       interface{}   `json:"virtual_accounts_activation_status"`
	SubscriptionsActivationStatus         interface{}   `json:"subscriptions_activation_status"`
	Submitted                             bool          `json:"submitted"`
	SubmittedAt                           int           `json:"submitted_at"`
	TransactionReportEmail                interface{}   `json:"transaction_report_email"`
	BankAccountNumber                     string        `json:"bank_account_number"`
	BankAccountName                       string        `json:"bank_account_name"`
	BankAccountType                       interface{}   `json:"bank_account_type"`
	BankBranch                            interface{}   `json:"bank_branch"`
	BankBranchIfsc                        string        `json:"bank_branch_ifsc"`
	BankBeneficiaryAddress1               interface{}   `json:"bank_beneficiary_address1"`
	BankBeneficiaryAddress2               interface{}   `json:"bank_beneficiary_address2"`
	BankBeneficiaryAddress3               interface{}   `json:"bank_beneficiary_address3"`
	BankBeneficiaryCity                   interface{}   `json:"bank_beneficiary_city"`
	BankBeneficiaryState                  interface{}   `json:"bank_beneficiary_state"`
	BankBeneficiaryPin                    interface{}   `json:"bank_beneficiary_pin"`
	Role                                  interface{}   `json:"role"`
	Department                            interface{}   `json:"department"`
	CreatedAt                             int           `json:"created_at"`
	UpdatedAt                             int           `json:"updated_at"`
	ActivationFlow                        interface{}   `json:"activation_flow"`
	InternationalActivationFlow           interface{}   `json:"international_activation_flow"`
	LiveTransactionDone                   int           `json:"live_transaction_done"`
	KycClarificationReasons               interface{}   `json:"kyc_clarification_reasons"`
	KycAdditionalDetails                  interface{}   `json:"kyc_additional_details"`
	AdditionalWebsites                    []interface{} `json:"additional_websites"`
	EstdYear                              interface{}   `json:"estd_year"`
	AuthorizedSignatoryResidentialAddress interface{}   `json:"authorized_signatory_residential_address"`
	AuthorizedSignatoryDob                interface{}   `json:"authorized_signatory_dob"`
	Platform                              interface{}   `json:"platform"`
	FundAccountValidationID               interface{}   `json:"fund_account_validation_id"`
	GstinVerificationStatus               interface{}   `json:"gstin_verification_status"`
	DateOfEstablishment                   interface{}   `json:"date_of_establishment"`
	ActivationFormMilestone               string        `json:"activation_form_milestone"`
	CompanyPanVerificationStatus          interface{}   `json:"company_pan_verification_status"`
	CinVerificationStatus                 interface{}   `json:"cin_verification_status"`
	CompanyPanDocVerificationStatus       interface{}   `json:"company_pan_doc_verification_status"`
	PersonalPanDocVerificationStatus      interface{}   `json:"personal_pan_doc_verification_status"`
	BankDetailsDocVerificationStatus      interface{}   `json:"bank_details_doc_verification_status"`
	MsmeDocVerificationStatus             interface{}   `json:"msme_doc_verification_status"`
	ShopEstablishmentNumber               interface{}   `json:"shop_establishment_number"`
	ShopEstablishmentVerificationStatus   interface{}   `json:"shop_establishment_verification_status"`
	ClientApplications                    []interface{} `json:"client_applications"`
	BusinessSuggestedPin                  interface{}   `json:"business_suggested_pin"`
	BusinessSuggestedAddress              interface{}   `json:"business_suggested_address"`
	FraudType                             interface{}   `json:"fraud_type"`
	BasBusinessID                         interface{}   `json:"bas_business_id"`
	IecCode                               interface{}   `json:"iec_code"`
	NeedKyc                               int           `json:"need_kyc"`
	LinkedAccount                         bool          `json:"linked_account"`
	MarketplaceMerchantName               string        `json:"marketplace_merchant_name"`
	MarketplaceMerchantID                 string        `json:"marketplace_merchant_id"`
	BankDetailsVerificationError          string        `json:"bank_details_verification_error"`
	Documents                             []interface{} `json:"documents"`
	ShopEstablishmentVerifiableZone       bool          `json:"shop_establishment_verifiable_zone"`
	Verification                          struct {
		Status             string `json:"status"`
		ActivationProgress int    `json:"activation_progress"`
	} `json:"verification"`
	CanSubmit                  bool          `json:"can_submit"`
	Activated                  int           `json:"activated"`
	Live                       bool          `json:"live"`
	International              bool          `json:"international"`
	MerchantVerificationDetail []interface{} `json:"merchant_verification_detail"`
	Dedupe                     struct {
		IsMatch       bool `json:"isMatch"`
		IsUnderReview bool `json:"isUnderReview"`
	} `json:"dedupe"`
	IsDedupe                   bool          `json:"isDedupe"`
	IsAutoKycDone              bool          `json:"isAutoKycDone"`
	IsHardLimitReached         bool          `json:"isHardLimitReached"`
	ActivationStatusChangeLogs []string      `json:"activationStatusChangeLogs"`
	MerchantBusinessDetail     interface{}   `json:"merchant_business_detail"`
	BusinessParentCategory     interface{}   `json:"business_parent_category"`
	PlaystoreURL               string        `json:"playstore_url"`
	AppstoreURL                string        `json:"appstore_url"`
	ShowMtuPopup               bool          `json:"showMtuPopup"`
	IsSubMerchant              bool          `json:"isSubMerchant"`
	CreditBalance              []interface{} `json:"credit_balance"`
	VerificationErrorCodes     []interface{} `json:"verification_error_codes"`
}
