<?php

use RZP\Models\Batch\Header;

return [
    'testBulkTerminalCreation'          => [
        'request'  => [
            'url'     => '/admin/batches',
            'method'  => 'post',
            'content' => [
                'type'     => 'terminal_creation',
            ],
        ],
        'response' => [
            'content' => [
                'entity'        => 'batch',
                'type'          => 'terminal_creation',
                'status'        => 'created',
                'total_count'   => 1,
                'success_count' => 0,
                'failure_count' => 0,
                'attempts'      => 0,
            ],
        ],
    ],
    'testBulkTerminalCreationValidateFile' => [
        'request'  => [
            'url'     => '/batches/validate',
            'method'  => 'post',
            'content' => [
                'type'     => 'terminal_creation',
            ],
        ],
        'response' => [
            'content' => [
                'processable_count' => 1,
                'error_count'       => 0,
                'parsed_entries'    => [
                    [
                        Header::TERMINAL_CREATION_MERCHANT_ID          => '10NodalAccount',
                        Header::TERMINAL_CREATION_GATEWAY              => 'BILLDESK',
                        Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => '1253',
                        Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => null,
                        Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => null,
                        Header::TERMINAL_CREATION_MC_MPAN              => null,
                        Header::TERMINAL_CREATION_VISA_MPAN            => null,
                        Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                        Header::TERMINAL_CREATION_VPA                  => null,
                        Header::TERMINAL_CREATION_CATEGORY             => '8211',
                        Header::TERMINAL_CREATION_CARD                 => null,
                        Header::TERMINAL_CREATION_NETBANKING           => null,
                        Header::TERMINAL_CREATION_EMANDATE             => null,
                        Header::TERMINAL_CREATION_EMI                  => null,
                        Header::TERMINAL_CREATION_UPI                  => null,
                        Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                        Header::TERMINAL_CREATION_AEPS                 => null,
                        Header::TERMINAL_CREATION_EMI_DURATION         => null,
                        Header::TERMINAL_CREATION_TYPE                 => 'non_recurring, pay',
                        Header::TERMINAL_CREATION_MODE                 => null,
                        Header::TERMINAL_CREATION_TPV                  => null,
                        Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                        Header::TERMINAL_CREATION_CORPORATE            => null,
                        Header::TERMINAL_CREATION_EXPECTED             => null,
                        Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                        Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => null,
                        Header::TERMINAL_CREATION_NETWORK_CATEGORY     => null,
                        Header::TERMINAL_CREATION_CURRENCY             => null,
                        Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => '33153078043',
                        Header::TERMINAL_CREATION_IFSC_CODE            => null,
                        Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                        Header::TERMINAL_CREATION_PAYLATER             => null,
                        Header::TERMINAL_CREATION_ENABLED              => null,
                        Header::TERMINAL_CREATION_CAPABILITY           => null,
                        Header::TERMINAL_CREATION_PLAN_NAME            => null,
                    ],
                ],
            ],
        ],
    ],

    'testBulkTerminalCreationValidateInvalidFile' => [
        'request'  => [
            'url'     => '/admin/batches/validate',
            'method'  => 'post',
            'content' => [
                'type'     => 'terminal_creation',
            ],
        ],
        'response' => [
            'content' => [],
            'status_code'   => 400,
        ],
        'exception' => [
            'class'               => 'RZP\Exception\BadRequestValidationFailureException',
            'internal_error_code' => 'BAD_REQUEST_VALIDATION_FAILURE',
        ],
    ],

    'testBulkTerminalCreationCompletelyMigratedBatchUpload'          => [
        'request'  => [
            'url'     => '/admin/batches',
            'method'  => 'post',
            'content' => [
                'type'     => 'terminal_creation',
            ],
        ],
        'response' => [
            'content' => [
                'created_at'        =>  1590521524,
                'updated_at'        =>  1590521524,
                'id'                =>  'Be6Ob5J8kaMV6o',
                'entity_id'         =>  '100000Razorpay',
                'name'              =>  null,
                'batch_type_id'     => 'terminal_creation',
                'type'              =>  'terminal_creation',
                'is_scheduled'      =>  false,
                'upload_count'      =>  0,
                'entity'            => 'batch',
                'failure_count'     =>  0,
                'total_count'       =>  1,
                'success_count'     =>  0,
                'attempts'          =>  0,
                'status'            =>  'created',
                'amount'            =>  0,
                'processed_amount'  =>  0,
            ],
        ],
        'encrypted_file_data'   =>  [
            [
                "Merchant Id",
                "Gateway",
                "Gateway Merchant ID",
                "Gateway Merchant ID2",
                "Gateway Terminal ID",
                "Gateway Access Code",
                "Gateway Terminal Password",
                "Gateway Terminal Password2",
                "Gateway Secure Secret",
                "Gateway Secure Secret2",
                "Gateway Recon Password",
                "Gateway Client Certificate",
                "Mastercard MPAN",
                "Visa MPAN",
                "Rupay MPAN",
                "VPA",
                "Category",
                "Card",
                "Netbanking",
                "Emandate",
                "EMI",
                "UPI",
                "Omnichannel",
                "Bank Transfer",
                "AEPS",
                "EMI Duration",
                "Type",
                "Mode",
                "TPV",
                "International",
                "Corporate",
                "Expected",
                "EMI Subvention",
                "Gateway Acquirer",
                "Network Category",
                "Currency",
                "Account Number",
                "IFSC Code",
                "Cardless EMI",
                "Paylater",
                "Enabled",
                "Status",
                "Capability",
                "Buy Pricing Plan Name",
            ],
            [
                "10NodalAccount",
                "BILLDESK",
                "1253",
                "",
                "",
                "",
                "",
                "",
                "be503616b06286c1ca26fcd6fc22c776", // encrypted gatewway secure secret
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "8211", //  category
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "non_recurring, pay",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "9c93de1726e152d34794751fb8d95700", // encrypted A/c no.
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            ]
        ],
    ],

    'testBulkTerminalCreationForBatchService' => [
        'request'  => [
            'url'     => '/terminals/bulk',
            'method'  => 'post',
            'content' => [
                [
                    'idempotency_key'                              => 'randomIdempotencyKey',
                    Header::TERMINAL_CREATION_MERCHANT_ID          => '10NodalAccount',
                    Header::TERMINAL_CREATION_GATEWAY              => 'BILLDESK',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => '1253',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => null,
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  'be503616b06286c1ca26fcd6fc22c776', // batch service will send this encrypted, its decrypted value = randomsecret123
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                    Header::TERMINAL_CREATION_MC_MPAN              => null,
                    Header::TERMINAL_CREATION_VISA_MPAN            => null,
                    Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                    Header::TERMINAL_CREATION_VPA                  => null,
                    Header::TERMINAL_CREATION_CATEGORY             => '8211',
                    Header::TERMINAL_CREATION_CARD                 => null,
                    Header::TERMINAL_CREATION_NETBANKING           => null,
                    Header::TERMINAL_CREATION_EMANDATE             => null,
                    Header::TERMINAL_CREATION_EMI                  => null,
                    Header::TERMINAL_CREATION_UPI                  => null,
                    Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                    Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                    Header::TERMINAL_CREATION_AEPS                 => null,
                    Header::TERMINAL_CREATION_EMI_DURATION         => null,
                    Header::TERMINAL_CREATION_TYPE                 => "non_recurring, pay",
                    Header::TERMINAL_CREATION_MODE                 => null,
                    Header::TERMINAL_CREATION_TPV                  => null,
                    Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                    Header::TERMINAL_CREATION_CORPORATE            => null,
                    Header::TERMINAL_CREATION_EXPECTED             => null,
                    Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => null,
                    Header::TERMINAL_CREATION_NETWORK_CATEGORY     => null,
                    Header::TERMINAL_CREATION_CURRENCY             => null,
                    Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                    Header::TERMINAL_CREATION_IFSC_CODE            => null,
                    Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                    Header::TERMINAL_CREATION_PAYLATER             => null,
                    Header::TERMINAL_CREATION_ENABLED              => null,
                    Header::TERMINAL_CREATION_STATUS               => null,
                    Header::TERMINAL_CREATION_CAPABILITY           => null,
                    Header::TERMINAL_CREATION_PLAN_NAME            => null,
                ],
            ]
        ],
        'response' => [
            'content' => [
                'items' =>
                [
                    '0' => [
                        'idempotency_key'    => 'randomIdempotencyKey',
                        'success'           => true,
                        'http_status_code'  => 201,
                        'error'             =>  [
                            'code'        =>  '',
                            'description' =>  ''
                        ],
                        'Merchant Id'           =>  '10NodalAccount',
                        'Gateway'               =>  'BILLDESK',
                        'Gateway Secure Secret' =>  'redacted', // would be written in output file
                    ]

                ]
            ]
        ],
    ],

    'testBulkTerminalCreationUpiAxis' => [
        'request'  => [
            'url'     => '/terminals/bulk',
            'method'  => 'post',
            'content' => [
                [
                    'idempotency_key'                              => 'randomIdempotencyKey',
                    Header::TERMINAL_CREATION_MERCHANT_ID          => '10000000000000',
                    Header::TERMINAL_CREATION_GATEWAY              => 'upi_axis',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => 'UNITEDPROD0093559',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => null,
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => 'UNITEDPRODAPP0093559',
                    Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                    Header::TERMINAL_CREATION_MC_MPAN              => null,
                    Header::TERMINAL_CREATION_VISA_MPAN            => null,
                    Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                    Header::TERMINAL_CREATION_VPA                  => 'unitedinternationalschool.rzp@axisbank',
                    Header::TERMINAL_CREATION_CATEGORY             => '8211',
                    Header::TERMINAL_CREATION_CARD                 => null,
                    Header::TERMINAL_CREATION_NETBANKING           => null,
                    Header::TERMINAL_CREATION_EMANDATE             => null,
                    Header::TERMINAL_CREATION_EMI                  => null,
                    Header::TERMINAL_CREATION_UPI                  => 1,
                    Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                    Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                    Header::TERMINAL_CREATION_AEPS                 => null,
                    Header::TERMINAL_CREATION_EMI_DURATION         => null,
                    Header::TERMINAL_CREATION_TYPE                 => "non_recurring, pay, collect",
                    Header::TERMINAL_CREATION_MODE                 => null,
                    Header::TERMINAL_CREATION_TPV                  => null,
                    Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                    Header::TERMINAL_CREATION_CORPORATE            => null,
                    Header::TERMINAL_CREATION_EXPECTED             => null,
                    Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => 'axis',
                    Header::TERMINAL_CREATION_NETWORK_CATEGORY     => null,
                    Header::TERMINAL_CREATION_CURRENCY             => null,
                    Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                    Header::TERMINAL_CREATION_IFSC_CODE            => null,
                    Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                    Header::TERMINAL_CREATION_PAYLATER             => null,
                    Header::TERMINAL_CREATION_ENABLED              => null,
                    Header::TERMINAL_CREATION_STATUS               => null,
                    Header::TERMINAL_CREATION_CAPABILITY           => null,
                    Header::TERMINAL_CREATION_PLAN_NAME            => null,
                ],
            ]
        ],
        'response' => [
            'content' => [
                'items' =>
                [
                    '0' => [
                        'idempotency_key'    => 'randomIdempotencyKey',
                        'success'           => true,
                        'http_status_code'  => 201,
                        'error'             =>  [
                            'code'        =>  '',
                            'description' =>  ''
                        ],
                        'Merchant Id'           =>  '10000000000000',
                        'Gateway'               =>  'upi_axis',
                    ]

                ]
            ]
        ],
    ],

    'testBulkTerminalCreationUpiIcici' => [
        'request' => [
            'url'       => '/terminals/bulk',
            'method'    => 'post',
            'content'   => [
                [
                    'idempotency_key'                               => 'randomIdempotencyKey',
                    Header::TERMINAL_CREATION_MERCHANT_ID           => '10000000000000',
                    Header::TERMINAL_CREATION_GATEWAY               => 'upi_icici',
                    Header::TERMINAL_CREATION_TYPE                  => 'non_recurring, bharat_qr',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID   => '1234567',
                    Header::TERMINAL_CREATION_VPA                   => 'thisisatestterminalforupiicici@icici',
                    Header::TERMINAL_CREATION_CARD                  => '0',
                    Header::TERMINAL_CREATION_NETBANKING            => '0',
                    Header::TERMINAL_CREATION_EMANDATE              => '0',
                    Header::TERMINAL_CREATION_UPI                   => '1',
                    Header::TERMINAL_CREATION_GATEWAY_ACQUIRER      => 'icic',
                ],
            ],
        ],
        'response' => [
            'content' => [
                'count' => 1,
                'items' => [
                    [
                        'Merchant Id'   => '10000000000000',
                        'Gateway'       => 'upi_icici',
                        'VPA'           => 'thisisatestterminalforupiicici@icici',
                    ],
                ],
            ],
        ],
    ],

    'testBulkTerminalCreationUpiIciciNegative' => [
        'request' => [
            'url'       => '/terminals/bulk',
            'method'    => 'post',
            'content'   => [
                [
                    'idempotency_key'                               => 'randomIdempotencyKey',
                    Header::TERMINAL_CREATION_MERCHANT_ID           => '10000000000000',
                    Header::TERMINAL_CREATION_GATEWAY               => 'upi_icici',
                    Header::TERMINAL_CREATION_TYPE                  => 'non_recurring, bharat_qr',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID   => '1234567',
                    Header::TERMINAL_CREATION_VPA                   => 'thisisatestterminalforupiicicigateway@icici',
                    Header::TERMINAL_CREATION_CARD                  => '0',
                    Header::TERMINAL_CREATION_NETBANKING            => '0',
                    Header::TERMINAL_CREATION_EMANDATE              => '0',
                    Header::TERMINAL_CREATION_UPI                   => '1',
                    Header::TERMINAL_CREATION_GATEWAY_ACQUIRER      => 'icic',
                ],
            ],
        ],
        'response' => [
            'content' => [
                'count' => 1,
                'items' => [
                    [
                        'terminal_id'   => '',
                        'error'         => [
                            'description'   => 'The vpa may not be greater than 40 characters.',
                        ],
                        'Merchant Id'   => '10000000000000',
                        'Gateway'       => 'upi_icici',
                        'VPA'           => 'thisisatestterminalforupiicicigateway@icici',
                    ],
                ],
            ],
        ],
    ],

    'testBulkTerminalNetbankingCub' => [
        'request'  => [
            'url'     => '/terminals/bulk',
            'method'  => 'post',
            'content' => [
                [
                    'idempotency_key'                              => 'randomIdempotencyKey',
                    Header::TERMINAL_CREATION_MERCHANT_ID          => '10000000000000',
                    Header::TERMINAL_CREATION_GATEWAY              => 'netbanking_cub',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => 'RPAY00000907',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => null,
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => 'PAYGATE986',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                    Header::TERMINAL_CREATION_MC_MPAN              => null,
                    Header::TERMINAL_CREATION_VISA_MPAN            => null,
                    Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                    Header::TERMINAL_CREATION_VPA                  => null,
                    Header::TERMINAL_CREATION_CATEGORY             => '8211',
                    Header::TERMINAL_CREATION_CARD                 => null,
                    Header::TERMINAL_CREATION_NETBANKING           => 1,
                    Header::TERMINAL_CREATION_EMANDATE             => null,
                    Header::TERMINAL_CREATION_EMI                  => null,
                    Header::TERMINAL_CREATION_UPI                  => null,
                    Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                    Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                    Header::TERMINAL_CREATION_AEPS                 => null,
                    Header::TERMINAL_CREATION_EMI_DURATION         => null,
                    Header::TERMINAL_CREATION_TYPE                 => null,
                    Header::TERMINAL_CREATION_MODE                 => null,
                    Header::TERMINAL_CREATION_TPV                  => null,
                    Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                    Header::TERMINAL_CREATION_CORPORATE            => null,
                    Header::TERMINAL_CREATION_EXPECTED             => null,
                    Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => null,
                    Header::TERMINAL_CREATION_NETWORK_CATEGORY     => 'corporate',
                    Header::TERMINAL_CREATION_CURRENCY             => null,
                    Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                    Header::TERMINAL_CREATION_IFSC_CODE            => null,
                    Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                    Header::TERMINAL_CREATION_PAYLATER             => null,
                    Header::TERMINAL_CREATION_ENABLED              => null,
                    Header::TERMINAL_CREATION_STATUS               => null,
                    Header::TERMINAL_CREATION_CAPABILITY           => null,
                    Header::TERMINAL_CREATION_PLAN_NAME            => null,
                ],
            ]
        ],
        'response' => [
            'content' => [
                'items' =>
                [
                    '0' => [
                        'idempotency_key'    => 'randomIdempotencyKey',
                        'success'           => true,
                        'http_status_code'  => 201,
                        'error'             =>  [
                            'code'        =>  '',
                            'description' =>  ''
                        ],
                        Header::TERMINAL_CREATION_MERCHANT_ID          => '10000000000000',
                        Header::TERMINAL_CREATION_GATEWAY              => 'netbanking_cub',
                        Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => 'RPAY00000907',
                        Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => null,
                        Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => null,
                        Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => 'PAYGATE986',
                        Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                        Header::TERMINAL_CREATION_MC_MPAN              => null,
                        Header::TERMINAL_CREATION_VISA_MPAN            => null,
                        Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                        Header::TERMINAL_CREATION_VPA                  => null,
                        Header::TERMINAL_CREATION_CATEGORY             => '8211',
                        Header::TERMINAL_CREATION_CARD                 => null,
                        Header::TERMINAL_CREATION_NETBANKING           => 1,
                        Header::TERMINAL_CREATION_EMANDATE             => null,
                        Header::TERMINAL_CREATION_EMI                  => null,
                        Header::TERMINAL_CREATION_UPI                  => null,
                        Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                        Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                        Header::TERMINAL_CREATION_AEPS                 => null,
                        Header::TERMINAL_CREATION_EMI_DURATION         => null,
                        Header::TERMINAL_CREATION_TYPE                 => null,
                        Header::TERMINAL_CREATION_MODE                 => null,
                        Header::TERMINAL_CREATION_TPV                  => null,
                        Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                        Header::TERMINAL_CREATION_CORPORATE            => null,
                        Header::TERMINAL_CREATION_EXPECTED             => null,
                        Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                        Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => null,
                        Header::TERMINAL_CREATION_NETWORK_CATEGORY     => 'corporate',
                        Header::TERMINAL_CREATION_CURRENCY             => null,
                        Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                        Header::TERMINAL_CREATION_IFSC_CODE            => null,
                        Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                        Header::TERMINAL_CREATION_PAYLATER             => null,
                        Header::TERMINAL_CREATION_ENABLED              => null,
                        Header::TERMINAL_CREATION_STATUS               => null,
                        Header::TERMINAL_CREATION_CAPABILITY           => null,
                        Header::TERMINAL_CREATION_PLAN_NAME            => null,
                    ]
                ]
            ]
        ],
    ],

    'testBulkTerminalPaytm' => [
        'request'  => [
            'url'     => '/terminals/bulk',
            'method'  => 'post',
            'content' => [
                [
                    'idempotency_key'                              => 'randomIdempotencyKey',
                    Header::TERMINAL_CREATION_MERCHANT_ID          => '10000000000000',
                    Header::TERMINAL_CREATION_GATEWAY              => 'paytm',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => 'RPAY00000907',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => 'test',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => 'PAYGATE986',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  'e9e1795303fdf0483c823a34a5972331',
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                    Header::TERMINAL_CREATION_MC_MPAN              => null,
                    Header::TERMINAL_CREATION_VISA_MPAN            => null,
                    Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                    Header::TERMINAL_CREATION_VPA                  => null,
                    Header::TERMINAL_CREATION_CATEGORY             => '8211',
                    Header::TERMINAL_CREATION_CARD                 => 0,
                    Header::TERMINAL_CREATION_NETBANKING           => 1,
                    Header::TERMINAL_CREATION_EMANDATE             => null,
                    Header::TERMINAL_CREATION_EMI                  => null,
                    Header::TERMINAL_CREATION_UPI                  => null,
                    Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                    Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                    Header::TERMINAL_CREATION_AEPS                 => null,
                    Header::TERMINAL_CREATION_EMI_DURATION         => null,
                    Header::TERMINAL_CREATION_TYPE                 => null,
                    Header::TERMINAL_CREATION_MODE                 => null,
                    Header::TERMINAL_CREATION_TPV                  => null,
                    Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                    Header::TERMINAL_CREATION_CORPORATE            => null,
                    Header::TERMINAL_CREATION_EXPECTED             => null,
                    Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => null,
                    Header::TERMINAL_CREATION_NETWORK_CATEGORY     => 'corporate',
                    Header::TERMINAL_CREATION_CURRENCY             => null,
                    Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                    Header::TERMINAL_CREATION_IFSC_CODE            => null,
                    Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                    Header::TERMINAL_CREATION_PAYLATER             => null,
                    Header::TERMINAL_CREATION_ENABLED              => null,
                    Header::TERMINAL_CREATION_STATUS               => null,
                    Header::TERMINAL_CREATION_CAPABILITY           => null,
                    Header::TERMINAL_CREATION_PLAN_NAME            => null,
                ],
            ]
        ],
        'response' => [
            'content' => [
                'items' =>
                    [
                        '0' => [
                            'idempotency_key'    => 'randomIdempotencyKey',
                            'success'           => true,
                            'http_status_code'  => 201,
                            'error'             =>  [
                                'code'        =>  '',
                                'description' =>  ''
                            ],
                            Header::TERMINAL_CREATION_MERCHANT_ID          => '10000000000000',
                            Header::TERMINAL_CREATION_GATEWAY              => 'paytm',
                            Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => 'RPAY00000907',
                            Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => 'test',
                            Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => null,
                            Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => 'PAYGATE986',
                            Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  null,
                            Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  null,
                            Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  'redacted',
                            Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  null,
                            Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                            Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                            Header::TERMINAL_CREATION_MC_MPAN              => null,
                            Header::TERMINAL_CREATION_VISA_MPAN            => null,
                            Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                            Header::TERMINAL_CREATION_VPA                  => null,
                            Header::TERMINAL_CREATION_CATEGORY             => '8211',
                            Header::TERMINAL_CREATION_CARD                 => 0,
                            Header::TERMINAL_CREATION_NETBANKING           => 1,
                            Header::TERMINAL_CREATION_EMANDATE             => null,
                            Header::TERMINAL_CREATION_EMI                  => null,
                            Header::TERMINAL_CREATION_UPI                  => null,
                            Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                            Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                            Header::TERMINAL_CREATION_AEPS                 => null,
                            Header::TERMINAL_CREATION_EMI_DURATION         => null,
                            Header::TERMINAL_CREATION_TYPE                 => null,
                            Header::TERMINAL_CREATION_MODE                 => null,
                            Header::TERMINAL_CREATION_TPV                  => null,
                            Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                            Header::TERMINAL_CREATION_CORPORATE            => null,
                            Header::TERMINAL_CREATION_EXPECTED             => null,
                            Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                            Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => null,
                            Header::TERMINAL_CREATION_NETWORK_CATEGORY     => 'corporate',
                            Header::TERMINAL_CREATION_CURRENCY             => null,
                            Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                            Header::TERMINAL_CREATION_IFSC_CODE            => null,
                            Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                            Header::TERMINAL_CREATION_PAYLATER             => null,
                            Header::TERMINAL_CREATION_ENABLED              => null,
                            Header::TERMINAL_CREATION_STATUS               => null,
                            Header::TERMINAL_CREATION_CAPABILITY           => null,
                            Header::TERMINAL_CREATION_PLAN_NAME            => null,
                        ]
                    ]
            ]
        ],
    ],


    'testBulkTerminalAtom' => [
        'request'  => [
            'url'     => '/terminals/bulk',
            'method'  => 'post',
            'content' => [
                [
                    'idempotency_key'                              => 'randomIdempotencyKey',
                    Header::TERMINAL_CREATION_MERCHANT_ID          => '10000000000000 ', // testing for trailing spaces, terminal should get created
                    Header::TERMINAL_CREATION_GATEWAY              => '  atom ',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => '900000000002 ',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => null,
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => 'random',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  'e9e1795303fdf0483c823a34a5972331', // decrypted value = random
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  'e9e1795303fdf0483c823a34a5972331',
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  'e9e1795303fdf0483c823a34a5972331',
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  'e9e1795303fdf0483c823a34a5972331',
                    Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                    Header::TERMINAL_CREATION_MC_MPAN              => null,
                    Header::TERMINAL_CREATION_VISA_MPAN            => null,
                    Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                    Header::TERMINAL_CREATION_VPA                  => null,
                    Header::TERMINAL_CREATION_CATEGORY             => null,
                    Header::TERMINAL_CREATION_CARD                 => null,
                    Header::TERMINAL_CREATION_NETBANKING           => null,
                    Header::TERMINAL_CREATION_EMANDATE             => null,
                    Header::TERMINAL_CREATION_EMI                  => null,
                    Header::TERMINAL_CREATION_UPI                  => null,
                    Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                    Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                    Header::TERMINAL_CREATION_AEPS                 => null,
                    Header::TERMINAL_CREATION_EMI_DURATION         => null,
                    Header::TERMINAL_CREATION_TYPE                 => null,
                    Header::TERMINAL_CREATION_MODE                 => null,
                    Header::TERMINAL_CREATION_TPV                  => null,
                    Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                    Header::TERMINAL_CREATION_CORPORATE            => null,
                    Header::TERMINAL_CREATION_EXPECTED             => null,
                    Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => null,
                    Header::TERMINAL_CREATION_NETWORK_CATEGORY     => null,
                    Header::TERMINAL_CREATION_CURRENCY             => null,
                    Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                    Header::TERMINAL_CREATION_IFSC_CODE            => null,
                    Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                    Header::TERMINAL_CREATION_PAYLATER             => null,
                    Header::TERMINAL_CREATION_ENABLED              => null,
                    Header::TERMINAL_CREATION_STATUS               => null,
                    Header::TERMINAL_CREATION_CAPABILITY           => null,
                    Header::TERMINAL_CREATION_PLAN_NAME            => null,
                ],
            ]
        ],
        'response' => [
            'content' => [
                'items' =>
                [
                    '0' => [
                        'idempotency_key'    => 'randomIdempotencyKey',
                        'success'           => true,
                        'http_status_code'  => 201,
                        'error'             =>  [
                            'code'        =>  '',
                            'description' =>  ''
                        ],
                        Header::TERMINAL_CREATION_MERCHANT_ID          => '10000000000000 ', // output file would still have trailing spaces
                        Header::TERMINAL_CREATION_GATEWAY              => '  atom ',
                        Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => '900000000002 ',
                        Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => null,
                        Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => null,
                        Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => 'random',
                        Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  'redacted',
                        Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  'redacted',
                        Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  'redacted',
                        Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  'redacted',
                        Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                        Header::TERMINAL_CREATION_MC_MPAN              => null,
                        Header::TERMINAL_CREATION_VISA_MPAN            => null,
                        Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                        Header::TERMINAL_CREATION_VPA                  => null,
                        Header::TERMINAL_CREATION_CATEGORY             => null,
                        Header::TERMINAL_CREATION_CARD                 => null,
                        Header::TERMINAL_CREATION_NETBANKING           => null,
                        Header::TERMINAL_CREATION_EMANDATE             => null,
                        Header::TERMINAL_CREATION_EMI                  => null,
                        Header::TERMINAL_CREATION_UPI                  => null,
                        Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                        Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                        Header::TERMINAL_CREATION_AEPS                 => null,
                        Header::TERMINAL_CREATION_EMI_DURATION         => null,
                        Header::TERMINAL_CREATION_TYPE                 => null,
                        Header::TERMINAL_CREATION_MODE                 => null,
                        Header::TERMINAL_CREATION_TPV                  => null,
                        Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                        Header::TERMINAL_CREATION_CORPORATE            => null,
                        Header::TERMINAL_CREATION_EXPECTED             => null,
                        Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                        Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => null,
                        Header::TERMINAL_CREATION_NETWORK_CATEGORY     => null,
                        Header::TERMINAL_CREATION_CURRENCY             => null,
                        Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                        Header::TERMINAL_CREATION_IFSC_CODE            => null,
                        Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                        Header::TERMINAL_CREATION_PAYLATER             => null,
                        Header::TERMINAL_CREATION_ENABLED              => null,
                        Header::TERMINAL_CREATION_STATUS               => null,
                        Header::TERMINAL_CREATION_CAPABILITY           => null,
                        Header::TERMINAL_CREATION_PLAN_NAME            => null,
                    ]
                ]
            ]
        ],
    ],

    'testBulkTerminalWorldline' => [
        'request'  => [
            'url'     => '/terminals/bulk',
            'method'  => 'post',
            'content' => [
                [
                    'idempotency_key'                              => 'randomIdempotencyKey',
                    Header::TERMINAL_CREATION_MERCHANT_ID          => '10000000000000',
                    Header::TERMINAL_CREATION_GATEWAY              => 'worldline',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => '900000000001',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => '12380001',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                    Header::TERMINAL_CREATION_MC_MPAN              => '11ca7a33bb4084ad5d59f835fcf4d05a118d4b07080204913ed216c4fa30440b', // decrypted value = 5434123412341234
                    Header::TERMINAL_CREATION_VISA_MPAN            => '78103203bbf48086583d6a56aa222b2eeb58a28a5b872f9557430cdbdf4232dd', // decrypted value = 4343123412341234
                    Header::TERMINAL_CREATION_RUPAY_MPAN           => 'cdb66b20c18b7dd2774794f494ba1710cfc0a53d85d41abc94140219bed5b37e', // decrypted value = 6334123412341234
                    Header::TERMINAL_CREATION_VPA                  => null,
                    Header::TERMINAL_CREATION_CATEGORY             =>  '7011',
                    Header::TERMINAL_CREATION_CARD                 => null,
                    Header::TERMINAL_CREATION_NETBANKING           => null,
                    Header::TERMINAL_CREATION_EMANDATE             => null,
                    Header::TERMINAL_CREATION_EMI                  => null,
                    Header::TERMINAL_CREATION_UPI                  => null,
                    Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                    Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                    Header::TERMINAL_CREATION_AEPS                 => null,
                    Header::TERMINAL_CREATION_EMI_DURATION         => null,
                    Header::TERMINAL_CREATION_TYPE                 => "direct_settlement_with_refund, non_recurring, bharat_qr",
                    Header::TERMINAL_CREATION_MODE                 => null,
                    Header::TERMINAL_CREATION_TPV                  => null,
                    Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                    Header::TERMINAL_CREATION_CORPORATE            => null,
                    Header::TERMINAL_CREATION_EXPECTED             => 1,
                    Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => 'axis',
                    Header::TERMINAL_CREATION_NETWORK_CATEGORY     => null,
                    Header::TERMINAL_CREATION_CURRENCY             => null,
                    Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                    Header::TERMINAL_CREATION_IFSC_CODE            => null,
                    Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                    Header::TERMINAL_CREATION_PAYLATER             => null,
                    Header::TERMINAL_CREATION_ENABLED              => null,
                    Header::TERMINAL_CREATION_STATUS               => null,
                    Header::TERMINAL_CREATION_CAPABILITY           => null,
                    Header::TERMINAL_CREATION_PLAN_NAME            => null,
                ],
            ]
        ],
        'response' => [
            'content' => [
                'items' =>
                [
                    '0' => [
                        'idempotency_key'    => 'randomIdempotencyKey',
                        'success'           => true,
                        'http_status_code'  => 201,
                        'error'             =>  [
                            'code'        =>  '',
                            'description' =>  ''
                        ],
                        Header::TERMINAL_CREATION_MERCHANT_ID          => '10000000000000',
                        Header::TERMINAL_CREATION_GATEWAY              => 'worldline',
                        Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => '900000000001',
                        Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => '12380001',
                        Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => null,
                        Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => null,
                        Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                        Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                        Header::TERMINAL_CREATION_MC_MPAN              => 'redacted',
                        Header::TERMINAL_CREATION_VISA_MPAN            => 'redacted',
                        Header::TERMINAL_CREATION_RUPAY_MPAN           => 'redacted',
                        Header::TERMINAL_CREATION_VPA                  => null,
                        Header::TERMINAL_CREATION_CATEGORY             => '7011',
                        Header::TERMINAL_CREATION_CARD                 => null,
                        Header::TERMINAL_CREATION_NETBANKING           => null,
                        Header::TERMINAL_CREATION_EMANDATE             => null,
                        Header::TERMINAL_CREATION_EMI                  => null,
                        Header::TERMINAL_CREATION_UPI                  => null,
                        Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                        Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                        Header::TERMINAL_CREATION_AEPS                 => null,
                        Header::TERMINAL_CREATION_EMI_DURATION         => null,
                        Header::TERMINAL_CREATION_TYPE                 => 'direct_settlement_with_refund, non_recurring, bharat_qr',
                        Header::TERMINAL_CREATION_MODE                 => null,
                        Header::TERMINAL_CREATION_TPV                  => null,
                        Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                        Header::TERMINAL_CREATION_CORPORATE            => null,
                        Header::TERMINAL_CREATION_EXPECTED             => 1,
                        Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                        Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => 'axis',
                        Header::TERMINAL_CREATION_NETWORK_CATEGORY     => null,
                        Header::TERMINAL_CREATION_CURRENCY             => null,
                        Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                        Header::TERMINAL_CREATION_IFSC_CODE            => null,
                        Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                        Header::TERMINAL_CREATION_PAYLATER             => null,
                        Header::TERMINAL_CREATION_ENABLED              => null,
                        Header::TERMINAL_CREATION_STATUS               => null,
                        Header::TERMINAL_CREATION_CAPABILITY           => null,
                        Header::TERMINAL_CREATION_PLAN_NAME            => null,
                    ]
                ]
            ]
        ],
    ],

    'testBulkTerminalCreationInvalidInput' => [
        'request'  => [
            'url'     => '/terminals/bulk',
            'method'  => 'post',
            'content' => [
                [
                    'idempotency_key'                              => 'randomIdempotencyKey2',
                    Header::TERMINAL_CREATION_MERCHANT_ID          => '10NodalAccount',
                    Header::TERMINAL_CREATION_GATEWAY              => 'mpgs',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => '9387723',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => null,
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                    Header::TERMINAL_CREATION_MC_MPAN              => null,
                    Header::TERMINAL_CREATION_VISA_MPAN            => null,
                    Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                    Header::TERMINAL_CREATION_VPA                  => null,
                    Header::TERMINAL_CREATION_CATEGORY             => null,
                    Header::TERMINAL_CREATION_CARD                 => null,
                    Header::TERMINAL_CREATION_NETBANKING           => null,
                    Header::TERMINAL_CREATION_EMANDATE             => null,
                    Header::TERMINAL_CREATION_EMI                  => null,
                    Header::TERMINAL_CREATION_UPI                  => null,
                    Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                    Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                    Header::TERMINAL_CREATION_AEPS                 => null,
                    Header::TERMINAL_CREATION_EMI_DURATION         => null,
                    Header::TERMINAL_CREATION_TYPE                 => "non_recurring, pay",
                    Header::TERMINAL_CREATION_MODE                 => null,
                    Header::TERMINAL_CREATION_TPV                  => null,
                    Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                    Header::TERMINAL_CREATION_CORPORATE            => null,
                    Header::TERMINAL_CREATION_EXPECTED             => null,
                    Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => null,
                    Header::TERMINAL_CREATION_NETWORK_CATEGORY     => null,
                    Header::TERMINAL_CREATION_CURRENCY             => null,
                    Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                    Header::TERMINAL_CREATION_IFSC_CODE            => null,
                    Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                    Header::TERMINAL_CREATION_PAYLATER             => null,
                    Header::TERMINAL_CREATION_ENABLED              => null,
                    Header::TERMINAL_CREATION_STATUS               => null,
                    Header::TERMINAL_CREATION_CAPABILITY           => null,
                    Header::TERMINAL_CREATION_PLAN_NAME            => null,
                ],
                [
                    'idempotency_key'                              => 'randomIdempotencyKey3',
                    Header::TERMINAL_CREATION_MERCHANT_ID          => '10000000000000',
                    Header::TERMINAL_CREATION_GATEWAY              => 'upi_axis',
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID  => 'TSTMERCHI',
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_ID  => null,
                    Header::TERMINAL_CREATION_GATEWAY_MERCHANT_ID2 => 'TSTMERCHIAPP',
                    Header::TERMINAL_CREATION_GATEWAY_ACCESS_CODE  => null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD   =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_TERMINAL_PASSWORD2  =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET       =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_SECURE_SECRET2      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_RECON_PASSWORD      =>  null,
                    Header::TERMINAL_CREATION_GATEWAY_CLIENT_CERTIFICATE  =>  null,
                    Header::TERMINAL_CREATION_MC_MPAN              => null,
                    Header::TERMINAL_CREATION_VISA_MPAN            => null,
                    Header::TERMINAL_CREATION_RUPAY_MPAN           => null,
                    Header::TERMINAL_CREATION_VPA                  => 'umesh@okhdfc',
                    Header::TERMINAL_CREATION_CATEGORY             => null,
                    Header::TERMINAL_CREATION_CARD                 => null,
                    Header::TERMINAL_CREATION_NETBANKING           => null,
                    Header::TERMINAL_CREATION_EMANDATE             => null,
                    Header::TERMINAL_CREATION_EMI                  => null,
                    Header::TERMINAL_CREATION_UPI                  => true,
                    Header::TERMINAL_CREATION_OMNICHANNEL          => null,
                    Header::TERMINAL_CREATION_BANK_TRANSFER        => null,
                    Header::TERMINAL_CREATION_AEPS                 => null,
                    Header::TERMINAL_CREATION_EMI_DURATION         => null,
                    Header::TERMINAL_CREATION_TYPE                 => "non_recurring",
                    Header::TERMINAL_CREATION_MODE                 => null,
                    Header::TERMINAL_CREATION_TPV                  => null,
                    Header::TERMINAL_CREATION_INTERNATIONAL        => null,
                    Header::TERMINAL_CREATION_CORPORATE            => null,
                    Header::TERMINAL_CREATION_EXPECTED             => null,
                    Header::TERMINAL_CREATION_EMI_SUBVENTION       => null,
                    Header::TERMINAL_CREATION_GATEWAY_ACQUIRER     => null,
                    Header::TERMINAL_CREATION_NETWORK_CATEGORY     => null,
                    Header::TERMINAL_CREATION_CURRENCY             => null,
                    Header::TERMINAL_CREATION_ACCOUNT_NUMBER       => null,
                    Header::TERMINAL_CREATION_IFSC_CODE            => null,
                    Header::TERMINAL_CREATION_CARDLESS_EMI         => null,
                    Header::TERMINAL_CREATION_PAYLATER             => null,
                    Header::TERMINAL_CREATION_ENABLED              => null,
                    Header::TERMINAL_CREATION_STATUS               => null,
                    Header::TERMINAL_CREATION_CAPABILITY           => null,
                    Header::TERMINAL_CREATION_PLAN_NAME            => null,
                ],

            ]
        ],
        'response' => [
            'content' => [
                'items' =>
                [
                    '0' => [
                        'idempotency_key'   =>  'randomIdempotencyKey2',
                        'success' => false,
                        'http_status_code' => 'BAD_REQUEST_VALIDATION_FAILURE',
                        'terminal_id'      =>  '',
                        'error' =>  [
                            'code' =>  null,
                            'description' =>  'The gateway terminal password field is required.'
                        ],
                    ],
                    '1' => [
                        'idempotency_key'   =>  'randomIdempotencyKey3',
                        'success' => false,
                        'http_status_code' => 'BAD_REQUEST_TERMINAL_WITH_SAME_FIELD_ALREADY_EXISTS',
                        'terminal_id'      =>  '',
                        'error' =>  [
                            'code' =>  null,
                            'description' =>  'A terminal with the same field exists - 100UPIAXISTmnl'
                        ],
                    ]
                ]
            ]
        ],
    ],
];
