export const mockWidgetsData = {
  couponEligibility: {
    customerGroup: 'allCustomers',
    customerList: [],
    customerDetailsType: '',
    customerDisplayList: {},
  },
  couponValidity: {
    startDate: '2025-01-28',
    endDate: '2025-01-29',
    startTime: '4:46 am',
    endTime: '11:59 pm',
    maxBudget: '20',
    isLimitedUsage: false,
  },
  discountDetails: {
    discountType: 'fixedAmount',
    discountValue: 0,
    minimumType: 'no_min_qty',
    minimumValue: 0,
    discountApplicableTo: 'products',
    discountedItemsList: [],
    discountedItemsDisplayList: [],
    maxDiscountValue: '',
    hasLimitedUseagePerOrder: false,
  },
  usageRestriction: {
    isLimitedUsage: false,
    isRestrictedTotalUsage: false,
    maxUsage: 1,
    limitBy: 'phone',
    total: 1,
  },
  productsPurchased: {
    minimumType: 'min_qty',
    minimumValue: 1,
    discountApplicableTo: 'products',
    discountedItemsList: [],
    discountedItemsDisplayList: [],
  },
  discountOffered: {
    discountType: 'monetary-discount',
    discountValue: 0,
    discountApplicableTo: 'products',
    discountedItemsList: [],
    productsOffered: 1,
    hasLimitedUseagePerOrder: false,
    maxUsagePerOrder: 1,
    discountedItemsDisplayList: [],
    discountSubType: 'fixedAmount',
  },
  couponDetails: {
    code: '',
    description: '',
    display: true,
    autoapply: false,
    prepaidMethodsOnly: false,
    couponDiscoveryEnabled: false,
  },
  bulkDiscountDetails: {
    discountSubType: 'fixedAmount',
    discountValue: 0,
    discountType: 'discountOnAll',
    maxUsagePerOrder: 1,
    hasLimitedUseagePerOrder: false,
  },
  combineCoupons: {
    shouldCombineFreeShippingCoupon: false,
    shouldCombineOtherAmountOffProductCoupons: false,
    shouldCombineAmountOffOrderCoupon: false,
    shouldCombineBulkDiscountCoupon: false,
    shouldCombineBxGyDiscountCoupon: false,
  },
  status: 'published',
  source: null,
};
