<?php

namespace RZP\Models\Merchant\Acs\AsvRouter\AsvMaps;
final class AsvFlows
{

    public const WRITE_FLOW_MAP = array(
        /* Save routes */
        'account_create_v2' => true,
        'account_delete_v2' => true,
        'account_edit_v2' => true,
        'action_checker_create' => true,
        'action_request_execute' => true,
        'add_additional_website' => true,
        'admin_patch_purpose_code' => true,
        'admin_website_section_save' => true,
        'balance_fetch' => true,
        'banking_account_activate' => true,
        'banking_account_service_lms_routes_all' => true,
        'banking_account_service_routes' => true,
        'banking_accounts_list' => true,
        'bas_archive_banking_account_dependencies' => true,
        'bas_banking_accounts_create' => true,
        'bas_internal_admin_routes' => true,
        'bas_unarchive_banking_account_dependencies' => true,
        'beta_account_create' => true,
        'cac_role_fetch_all' => true,
        'chargeback_poc' => true,
        'collect_info_merchant_details_internal' => true,
        'consume_typeform_webhook' => true,
        'create_exec_risk_action' => true,
        'create_international_virtual_accounts' => true,
        'credits_fetch_multiple' => true,
        'currency_fetch_all_proxy' => true,
        'dark_bas_business_id' => true,
        'db_meta_query' => true,
        'delete_additional_websites' => true,
        'dispute_fetch_multiple' => true,
        'dispute_fetch_multiple_aggregate' => true,
        'enable_es_scheduled' => true,
        'es_disabled_dark_route' => true,
        'feature_add' => true,
        'feature_bulk_assign' => true,
        'feature_delete' => true,
        'feature_delete_internal' => true,
        'feature_get_status' => true,
        'fetch_merchant_balance_configs' => true,
        'fetch_merchant_escalation' => true,
        'fetch_payment_merchant_actions' => true,
        'fetch_product_details_for_order' => true,
        'fetch_product_status' => true,
        'fetch_trusted_badge_status' => true,
        'fund_addition_tpv' => true,
        'get_instant_refunds_pricing_merchant' => true,
        'get_merchant_data_for_segment' => true,
        'growth_get_asset_details' => true,
        'growth_pricing_bundle_assign_pricing_rule' => true,
        'internal_merchant_fetch' => true,
        'link_account_documents_v2' => true,
        'link_stakeholder_documents_v2' => true,
        'linked_account_create_batch' => true,
        'los_service' => true,
        'm2m_referral_link_get' => true,
        'merchant_2fa_change_setting' => true,
        'merchant_actions' => true,
        'merchant_activation_archive' => true,
        'merchant_activation_business_categories_v2' => true,
        'merchant_activation_clarifications_save' => true,
        'merchant_activation_clarifications_save_admin' => true,
        'merchant_activation_details' => true,
        'merchant_activation_otp_send' => true,
        'merchant_activation_save' => true,
        'merchant_activation_status' => true,
        'merchant_activation_update' => true,
        'merchant_activation_update_website' => true,
        'merchant_analytics' => true,
        'merchant_assign_pricing' => true,
        'merchant_bank_account_change_status' => true,
        'merchant_bank_account_file_upload' => true,
        'merchant_bank_account_update' => true,
        'merchant_billing_label_update' => true,
        'merchant_bmc_response_fetch' => true,
        'merchant_bmc_response_save' => true,
        'merchant_bulk_onboarding_admin' => true,
        'merchant_business_detail_fetch' => true,
        'merchant_business_detail_save' => true,
        'merchant_create_additional_email' => true,
        'merchant_create_lead_to_salesforce' => true,
        'merchant_data_fix' => true,
        'merchant_delete_additional_email' => true,
        'merchant_delete_config_logo' => true,
        'merchant_details_patch' => true,
        'merchant_document_admin_upload' => true,
        'merchant_document_delete' => true,
        'merchant_document_upload' => true,
        'merchant_edit' => true,
        'merchant_edit_config' => true,
        'merchant_edit_config_logo' => true,
        'merchant_edit_email' => true,
        'merchant_edit_email_create_user' => true,
        'merchant_edit_email_la' => true,
        'merchant_edit_pre_signup_details' => true,
        'merchant_features_fetch' => true,
        'merchant_fetch_config' => true,
        'merchant_fetch_keys' => true,
        'merchant_fetch_payment_failure_analysis' => true,
        'merchant_fetch_schedule_tasks' => true,
        'merchant_get_preferences' => true,
        'merchant_get_tags' => true,
        'merchant_gst_fetch' => true,
        'merchant_gstin_self_serve_update' => true,
        'merchant_international_enablement_submit' => true,
        'merchant_international_toggle' => true,
        'merchant_mtu_update_dashboard' => true,
        'merchant_nc_revamp_eligibility' => true,
        'merchant_onboarding_crons' => true,
        'merchant_onboarding_escalations' => true,
        'merchant_patch_purpose_code' => true,
        'merchant_post_preferences' => true,
        'merchant_pricing_bulk' => true,
        'merchant_product_international_request' => true,
        'merchant_product_switch' => true,
        'merchant_product_switch_dark' => true,
        'merchant_razorx_bulk_evaluate' => true,
        'merchant_razorx_evaluate' => true,
        'merchant_requests_create' => true,
        'merchant_requests_update' => true,
        'merchant_sub_create' => true,
        'merchant_sub_create_batch' => true,
        'merchant_submit_internal' => true,
        'merchant_tags_bulk' => true,
        'merchant_toggle_fee_bearer' => true,
        'merchant_update_activation_flow' => true,
        'merchant_update_key_access' => true,
        'merchant_upload_miq_admin' => true,
        'merchant_website_plugin_save' => true,
        'merchant_website_section_action' => true,
        'merchant_website_section_fetch' => true,
        'merchant_website_section_save' => true,
        'merchant_workflow_details' => true,
        'mir_instruments_get' => true,
        'order_fetch_by_id' => true,
        'partner_activation_save' => true,
        'payment_create_checkout' => true,
        'payment_fetch_by_id' => true,
        'payment_fetch_multiple' => true,
        'payment_links_create' => true,
        'payment_links_fetch_multiple' => true,
        'payment_page_cds_domain_create' => true,
        'payment_page_cds_domain_delete' => true,
        'payout_fetch_by_id' => true,
        'payout_fetch_multiple' => true,
        'payout_links_merchant_settings_get' => true,
        'pricing_add_plan_rule_bulk' => true,
        'product_config_create_v2' => true,
        'product_config_update_v2' => true,
        'proxy_for_activation_status' => true,
        'proxy_merchant_edit_support_details' => true,
        'proxy_merchant_get_support_details' => true,
        'refund_fetch_multiple' => true,
        'reminder_service' => true,
        'rollback_free_payouts' => true,
        'setl_amount' => true,
        'setl_fetch_multiple' => true,
        'setl_holidays' => true,
        'setl_merchant_dashboard_config_get' => true,
        'settlement_ondemand_feature_enable' => true,
        'settlement_ondemand_fees_dashboard' => true,
        'smart_dashboard_merchant_details_patch' => true,
        'splitz_evaluate_bulk_proxy' => true,
        'stakeholder_create_v2' => true,
        'stakeholder_update_v2' => true,
        'submerchant_partner_feature_check' => true,
        'switch_merchant_token' => true,
        'tax_payments_get_all_settings' => true,
        'ufh_get_file_signed_url' => true,
        'update_partner_type' => true,
        'user_add_email_verify' => true,
        'user_contact_mobile_datafix' => true,
        'user_fetch' => true,
        'user_merchant_upgrade' => true,
        'user_mobile_oauth_logout' => true,
        'user_oauth_login' => true,
        'user_oauth_register' => true,
        'user_opt_in_whatsapp' => true,
        'user_otp_create' => true,
        'user_register' => true,
        'user_verify_and_update_mobile_otp' => true,
        'user_verify_email' => true,
        'verify_user_otp_register' => true,
        'webhook_create' => true,
        'workflow_config_delete' => true,
        'worker:add_ondemand_pricing_if_absent_for_merchant' => true,
        'worker:auto_linked_account_creation' => true,
        'worker:auto_update_merchant_products' => true,
        'worker:batch' => true,
        'worker:bvs_validation_job' => true,
        'worker:cross_border_common_use_cases' => true,
        'worker:free_payout_migration_for_payouts_service' => true,
        'worker:linked_account_bank_verification_status_backfill' => true,
        'worker:mcc_categorisation_consumer' => true,
        'worker:merchant_firs_documents' => true,
        'worker:merchant_hold_funds_sync' => true,
        'worker:migrate_reseller_to_pure_platform_partner_job' => true,
        'worker:negative_keywords_consumer' => true,
        'worker:pgos_cdc_events_job' => true,
        'worker:sub_merchant_support_entities_create_job' => true,
        'worker:update_merchant_context' => true,
        'worker:website_policy_consumer' => true,
        'worker:website_update_processor' => true,
    );

    public const MAP = array(
        // TOP Read Routes To be Excluded
        'order_payments' => true,
        'payment_verify_new' => true,
        // 'payment_fetch_multiple' => true,  // Already Present Above
        'payment_fetch_by_id' => true,
        'order_fetch_by_id' => true,
        'payment_get_status' => true,
        'payment_create_ajax' => true,
        'gateway_payment_callback_post' => true,
        'order_create' => true,
        'payout_fetch_by_id' => true,
        'payment_create_upi' => true,
        'payment_notify' => true,
        'payment_links_get' => true,
        '1cc_merchant_preferences' => true,
        'payment_create_checkout' => true,
        // 'merchant_activation_details' => true, // Already Present Above
        'payments_downtime' => true,
        'admin_fetch_entity_multiple' => true,
        'account_features_get' => true,
        'merchant_methods_offers_checkout_internal' => true,
        'invoice_create' => true,
        'customer_fetch_internal_for_checkout' => true,
        'internal_merchant_fetch' => true,
        'payment_capture' => true,
        'worker:bucket' => true,
        'checkout_personalisation_internal' => true,
        'payment_timeout_new' => true,
        'update_fts_fund_transfer' => true,
        'payment_validate_vpa' => true,
        'customer_fetch_tokens_internal' => true,
        'payment_create_jsonp' => true,
        'payment_create_private_json' => true,
        'payment_callback_with_key_get' => true,
        'payment_refund' => true,
        'refund_create' => true,
        'scrooge_entities_fetch' => true,
        'refund_scrooge_transaction_create' => true,
        'refund_scrooge_fetch_fee' => true,
        'refund_fetch_fee' => true,
        'refund_fetch_by_id' => true,
        'refund_fetch_creation_data' => true,
        'adj_add' => true,
        'payment_callback_with_key_post'=> true,
        'payment_verify'=>true,
        'internal_payment_pricing'=>true,
        'api_entity_fetch'=>true,
        'internal_merchant_risk_notification'=>true,
        'payment_otp_submit' => true,
        'payment_otp_generate' => true,
        'customer_add_bank_account' => true,
        'customer_delete_bank_account' => true,
        'p2p_turbo_preferences' =>  true,
        'p2p_turbo_gateway_config' =>  true,
        'customer_create'=> true,
    );

    public static function isExclusionFLow(string $flow): bool
    {
        if (array_key_exists($flow, self::MAP)) {
            return true;
        }

        return false;
    }

    public static function isWriteFLow(string $flow): bool
    {
        if (array_key_exists($flow, self::WRITE_FLOW_MAP)) {
            return true;
        }

        return false;
    }

}
