<?php

namespace RZP\Models\Merchant\Acs\AsvRouter\AsvMaps;
final class FunctionConstant
{
    const FIND_OR_FAIL = 'FIND_OR_FAIL';
    const FIND_OR_FAIL_PUBLIC = 'FIND_OR_FAIL_PUBLIC';
    const FIND_FOR_IMPLICIT_JOIN = 'FIND_FOR_IMPLICIT_JOIN';

    const GET_BY_MERCHANT_ID = 'GET_BY_MERCHANT_ID';
    const GET_BY_MERCHANT_ID_FOR_IMPLICIT_JOIN = 'GET_BY_MERCHANT_ID_FOR_IMPLICIT_JOIN';

    const GET_BY_TYPE_AND_MERCHANT_ID = 'GET_BY_TYPE_AND_MERCHANT_ID';
    const GET_BY_ID = 'GET_BY_ID';

    const GET_BY_STAKEHOLDER_ID = 'GET_BY_STAKEHOLDER_ID';

    const SAVE_OR_FAIL = 'SAVE_OR_FAIL';
    const DELETE_OR_FAIL =  'DELETE_OR_FAIL';
}
