<?php

namespace RZP\Models\Merchant\Acs\AsvRouter\AsvMaps;
final class MerchantSaveFlows {

    public const MAP = array(
        /* routes */
        'merchant_mtu_update_dashboard' => true,
        'merchant_billing_label_update' => true,
        'merchant_activation_update' => true,
        'user_add_email_verify' => true,
        'stakeholder_update_v2' => true,
        'product_config_update_v2' => true,
        'merchant_bank_account_update' => true,
        'merchant_edit_email_create_user' => true,
        'merchant_activation_update_website' => true,
        'user_verify_and_update_mobile_otp' => true,
        'update_partner_type' => true,
        'merchant_razorx_bulk_evaluate' => true,
        'merchant_activation_status' => true,
        'merchant_activation_clarifications_save' => true,
        'merchant_activation_save' => true,
        'action_checker_create' => true,
        'user_register' => true,
        'merchant_product_switch' => true,
        'merchant_document_upload' => true,
        'user_oauth_register' => true,
        'merchant_edit_pre_signup_details' => true,
        'linked_account_create_batch' => true,
        'beta_account_create' => true,
        'add_additional_website' => true,
        'verify_user_otp_register' => true,
        'merchant_website_section_save' => true,
        'merchant_activation_clarifications_save_admin' => true,
        'merchant_activation_otp_send' => true,
        'link_account_documents_v2' => true,
        'merchant_details_patch' => true,
        'stakeholder_create_v2' => true,
        'merchant_update_key_access' => true,
        'merchant_sub_create' => true,
        'merchant_edit' => true,
        'account_create_v2' => true,
        'merchant_gstin_self_serve_update' => true,
        'merchant_tags_bulk' => true,
        'product_config_create_v2' => true,
        'collect_info_merchant_details_internal' => true,
        'merchant_onboarding_crons' => true,
        'user_oauth_login' => true,
        'link_stakeholder_documents_v2' => true,
        'merchant_website_section_action' => true,
        'merchant_sub_create_batch' => true,
        'merchant_data_fix_activation' => true,
        'merchant_international_enablement_submit' => true,
        'settlement_ondemand_feature_enable' => true,
        'action_request_execute' => true,
        'merchant_product_international_request' => true,
        'user_merchant_upgrade' => true,
        'feature_bulk_assign' => true,
        'linked_account_update_bank_account' => true,
        'payout_service_idempotency_key_feature_remove' => true,
        'create_exec_risk_action' => true,
        'merchant_features_fetch' => true,
        'user_fetch' => true,
        'account_edit_v2' => true,
        'merchant_edit_config' => true,
        'merchant_activation_details' => true,
        'merchant_edit_config_logo' => true,
        'merchant_requests_create' => true,
        'growth_get_asset_details' => true,
        'banking_accounts_list' => true,
        'merchant_get_tags' => true,
        'credits_fetch_multiple' => true,
        'merchant_get_preferences' => true,
        'account_delete_v2' => true,
        'user_opt_in_whatsapp' => true,
        'merchant_nc_revamp_eligibility' => true,
        'enable_es_scheduled' => true,
        'merchant_2fa_change_setting' => true,
        'feature_delete' => true,
        'account_edit' => true,
        'accounting_payouts_integration_status' => true,
        'accounts_receivable_all_routes' => true,
        'balance_fetch' => true,
        'banking_account_activate' => true,
        'banking_account_service_lms_routes_all' => true,
        'banking_account_service_routes' => true,
        'bas_internal_admin_routes' => true,
        'bvs_service_dashboard' => true,
        'chargeback_poc' => true,
        'consume_typeform_webhook' => true,
        'delete_additional_websites' => true,
        'emerchantpay_apm_onboard_maf_bulk' => true,
        'feature_add' => true,
        'feature_delete_internal' => true,
        'fetch_product_status' => true,
        'fund_addition_tpv' => true,
        'linked_account_reference_data_update' => true,
        'mailmodo_l1_form_submission' => true,
        'merchant_actions' => true,
        'merchant_analytics' => true,
        'merchant_assign_pricing' => true,
        'merchant_balance_fetch' => true,
        'merchant_bank_account_file_upload' => true,
        'merchant_bulk_onboarding_admin' => true,
        'merchant_create_additional_email' => true,
        'merchant_delete_config_logo' => true,
        'merchant_document_admin_upload' => true,
        'merchant_document_delete' => true,
        'merchant_edit_email_la' => true,
        'merchant_gst_fetch' => true,
        'merchant_international_toggle' => true,
        'merchant_mtu_update' => true,
        'merchant_onboarding_escalations' => true,
        'merchant_patch_purpose_code' => true,
        'merchant_post_preferences' => true,
        'merchant_pricing_bulk' => true,
        'merchant_razorx_evaluate' => true,
        'merchant_toggle_fee_bearer' => true,
        'partner_activation_save' => true,
        'payment_fetch_multiple' => true,
        'payment_page_list' => true,
        'pricing_add_plan_rule_bulk' => true,
        'proxy_merchant_edit_support_details' => true,
        'Razorpay_Slack_Jobs_SlackJob' => true,
        'setl_amount' => true,
        'setl_fetch_multiple' => true,
        'settlement_ondemand_fees_dashboard' => true,
        'smart_dashboard_merchant_details_patch' => true,
        'splitz_evaluate_bulk_proxy' => true,
        'user_otp_create' => true,
        'whitelisted_domain' => true,
        'worker:update_merchant_context' => true,
        'worker:bvs_validation_job' => true,
        'worker:merchant_hold_funds_sync' => true,
        'worker:auto_update_merchant_products' => true,
        'worker:add_ondemand_pricing_if_absent_for_merchant' => true,
        'worker:add_ondemand_restricted_feature_for_merchant' => true,
        'worker:what_c_m_s_processor' => true,
        'worker:auto_linked_account_creation' => true,
        'worker:linked_account_bank_verification_status_backfill' => true,
        'RZP_Jobs_EsSync' => true,
        'rzp_jobs_gstinvalidation' => true,
        'RZP_Jobs_MerchantFirsDocuments' => true,
        'rzp_jobs_merchantfirsdocumentszip' => true,
        'RZP_Jobs_MerchantHoldFundsSync' => true,
        'RZP_Jobs_ProductConfig_AutoUpdateMerchantProducts' => true,
        'rzp_jobs_segmentrequestjob' => true,
        'rzp_jobs_sendsubmerchantactivatedevents' => true,
        'rzp_jobs_settlementondemand_addondemandpricingifabsentformerchant' => true,
        'rzp_jobs_settlementondemand_addondemandrestrictedfeatureformerchant' => true,
        'RZP_Jobs_SubMerchantBatchUploadValidationStatusUpdater' => true,
        'rzp_jobs_triggeracssync' => true,
        'RZP_Mail_Merchant_MerchantDashboardEmail' => true,
        'rzp_mail_user_otp' => true,
    );

    public static function isSaveFlow(string $flow) {
        if (array_key_exists($flow, self::MAP)) {
            return true;
        }

        return false;
    }

}
