export default {
  plans: [
    {
      id: 'string',
      product_type: 'PRODUCT_TYPE_LOANS',
      credit_id: 'string',
      product_entity_type: 'PRODUCT_ENTITY_TYPE_DISBURSAL',
      product_entity_reference_id: 'string',
      merchant_id: 'string',
      allow_over_repayment: true,
      allow_prepayment: true,
      collection_amount: 0,
      prioritization: ['string'],
      interest_config: {
        type: 'TYPE_FLAT',
        rate: 0,
      },
      due_config: {
        label: 'string',
        dpd_days: 0,
        percent_of: 'PERCENT_OF_TOTAL_PAYABLE',
        percent_rate: 0,
        flat_rate: 0,
        frequency: 'FREQUENCY_DAILY',
        prioritization: ['BALANCE_TYPE_PRINCIPAL'],
        actions: ['string'],
      },
      installments_config: {
        start_date: 0,
        end_date: 0,
        frequency: 'FREQUENCY_DAILY',
        minimum_amount: 0,
        minimum_amount_unit: 'MINIMUM_AMOUNT_UNIT_PERCENT',
      },
      auto_collection_config: {
        enable_auto_collections: true,
        collection_preference: [
          {
            balance_account_type: 'BALANCE_ACCOUNT_TYPE_PRIMARY',
            breakup_percentage: 0,
          },
        ],
        strategy: 'STRATEGY_SEQUENTIAL_FIRST',
        days_past_installment: 0,
        total_breakdown_days: 0,
        frequency: 'FREQUENCY_DAILY',
        auto_collection_amount_type: 'AUTO_COLLECTION_AMOUNT_TYPE_TOTAL',
      },
      status: 'STATUS_CREATED',
      created_at: 0,
      updated_at: 0,
    },
  ],
  installments: {
    installments: [
      {
        id: 'string',
        plan_id: 'string',
        merchant_id: 'string',
        start_date: 0,
        end_date: 0,
        epi_amount: 18600000,
        interest_amount: 0,
        interest_collected_amount: 0,
        principal_amount: 0,
        principal_collected_amount: 0,
        status: 'STATUS_CREATED',
        currency: 'string',
        created_at: 0,
        updated_at: 0,
        outstanding_interest: 0,
      },
      {
        id: 'string',
        plan_id: 'string',
        merchant_id: 'string',
        start_date: 0,
        end_date: 0,
        epi_amount: 0,
        interest_amount: 0,
        interest_collected_amount: 0,
        principal_amount: 0,
        principal_collected_amount: 0,
        status: 'STATUS_COMPLETED',
        currency: 'string',
        created_at: 0,
        updated_at: 0,
        outstanding_interest: 0,
      },
      {
        id: 'string',
        plan_id: 'string',
        merchant_id: 'string',
        start_date: 0,
        end_date: 0,
        epi_amount: 0,
        interest_amount: 0,
        interest_collected_amount: 0,
        principal_amount: 0,
        principal_collected_amount: 0,
        status: 'STATUS_COMPLETED',
        currency: 'string',
        created_at: 0,
        updated_at: 0,
        outstanding_interest: 0,
      },
    ],
    amount_collected: {
      principal: 9830000,
      interest: 1230000,
    },
  },
  repayments: [
    {
      amount: 200,
      currency: 'INR',
      created_at: 1625126577,
      credit_id: 'string',
      payment_mode: 'PAYMENT_MODE_MANUAL',
      payment_meta: {
        method: 'string',
        bank: 'bank',
        vpa: 'vpa',
      },
      status: 'STATUS_COLLECTED',
      product_type: 'PRODUCT_TYPE_LOANS',
      product_entity_type: 'PRODUCT_ENTITY_TYPE_DISBURSAL',
      product_entity_reference_id: 'string',
      payment_reference_type: 'PAYMENT_REFERENCE_TYPE_ORDER',
    },
    {
      amount: 2000,
      currency: 'INR',
      created_at: 1625115777,
      credit_id: 'string',
      payment_mode: 'PAYMENT_MODE_AUTOCOLLECTION',
      product_type: 'PRODUCT_TYPE_LOANS',
      status: 'STATUS_COLLECTED',
      product_entity_type: 'PRODUCT_ENTITY_TYPE_DISBURSAL',
      product_entity_reference_id: 'string',
      payment_reference_type: 'PAYMENT_REFERENCE_TYPE_ORDER',
    },
    {
      amount: 5000,
      currency: 'INR',
      created_at: 1619845377,
      credit_id: 'string',
      payment_mode: 'PAYMENT_MODE_AUTOCOLLECTION',
      product_type: 'PRODUCT_TYPE_LOANS',
      status: 'STATUS_COLLECTED',
      product_entity_type: 'PRODUCT_ENTITY_TYPE_DISBURSAL',
      product_entity_reference_id: 'string',
      payment_reference_type: 'PAYMENT_REFERENCE_TYPE_ORDER',
    },
    {
      amount: 3000,
      currency: 'INR',
      created_at: 1619863377,
      credit_id: 'string',
      payment_mode: 'PAYMENT_MODE_AUTOCOLLECTION',
      status: 'STATUS_FAILED',
      payment_meta: {
        method: 'string',
        bank: 'bank',
        vpa: 'vpa',
      },
      product_type: 'PRODUCT_TYPE_LOANS',
      product_entity_type: 'PRODUCT_ENTITY_TYPE_DISBURSAL',
      product_entity_reference_id: 'string',
      payment_reference_type: 'PAYMENT_REFERENCE_TYPE_ORDER',
    },
    {
      amount: 3000,
      currency: 'INR',
      created_at: 1625122977,
      credit_id: 'string',
      payment_mode: 'PAYMENT_MODE_MANUAL',
      status: 'STATUS_COLLECTED',
      payment_meta: {
        method: 'string',
        bank: 'bank',
        vpa: 'vpa',
      },
      product_type: 'PRODUCT_TYPE_LOANS',
      product_entity_type: 'PRODUCT_ENTITY_TYPE_DISBURSAL',
      product_entity_reference_id: 'string',
      payment_reference_type: 'PAYMENT_REFERENCE_TYPE_ORDER',
    },

    {
      amount: 9800,
      currency: 'INR',
      created_at: 1612087377,
      credit_id: 'string',
      payment_mode: 'PAYMENT_MODE_MANUAL',
      status: 'STATUS_COLLECTED',
      payment_meta: {
        method: 'string',
        bank: 'bank',
        vpa: 'vpa',
      },
      product_type: 'PRODUCT_TYPE_LOANS',
      product_entity_type: 'PRODUCT_ENTITY_TYPE_DISBURSAL',
      product_entity_reference_id: 'string',
      payment_reference_type: 'PAYMENT_REFERENCE_TYPE_ORDER',
    },
  ],
  upcomingPayments: {
    installment_id: 'string',
    schedule: [
      {
        date: 1522485800000,
        amount: 26400000008,
      },
      {
        date: 1222485800000,
        amount: 500000,
      },
    ],
    amount_expected_till_now: 0,
  },
};
