<?php

namespace RZP\Gateway\Paytm;

use RZP\Error;
use RZP\Error\ErrorCode;

class ResponseCodeMap
{
    public static $codes = array(
        3       => ErrorCode::GATEWAY_ERROR_REQUEST_TIMEOUT,
        4       => 'Sent to Mina.',
        5       => 'Open',
        6       => 'Pending',
        7       => 'Failure after 70 min status query in case of Hybrid txn.',
        8       => 'Failure to Success',
        9       => 'OTP sent to your registered phone.',
        100     => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK,
        101     => 'The maximum limit on the number of users allowed to use this card as been reached. Please use another card for your transaction.',
        102     => 'The user attempted the transaction with more cards than specified limit in the last 1 year. The transaction has been classified as suspicious and is blocked.',
        103     => 'The user has made 3 unsuccessful attempts with the same card. The transaction has been classified as suspicious and the card has been blocked.',
        105     => 'The user has made 3 unsuccessful attempts. The transaction has been classified as suspicious and user has been blocked.',
        106     => 'Max Txn amount is crossed for Cust Id.',
        107     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED,
        108     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED,
        109     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED,
        110     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_MAX_AMOUNT_LIMIT_CROSSED_FOR_CUSTOMER,
        1101    => 'Timeout from Wallet',
        111     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED,
        112     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED,
        113     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED,
        114     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED,
        115     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED,
        116     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED,
        117     => 'The user has breached the limit of maximum number of different cards allowed. The transaction can be completed with a previously used card.',
        119     => 'Perday Txn amount is crossed.',
        120     => 'Perday Txn count is crossed for Cust Id.',
        121     => 'PerWeek Txn count is crossed for Cust Id.',
        122     => 'PerMonth Txn count is crossed for Cust Id.',
        123     => 'Max Txn amount is crossed for NetBanking Transactions.',
        124     => 'PerDay Txn amount is crossed for NetBanking Transactions.',
        125     => 'PerWeek Txn amount is crossed for NetBanking Transactions.',
        126     => 'PerMonth Txn amount is crossed for NetBanking Transactions.',
        127     => 'Perday Txn count is crossed for NetBanking Transactions.',
        128     => 'PerWeek Txn count is crossed for NetBanking Transactions.',
        129     => 'PerMonth Txn count is crossed for NetBanking Transactions.',
        130     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_BLOCKED_CUSTOMER,
        131     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_BLOCKED_CARD,
        132     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_BLOCKED_IP_ADDRESS,
        133     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_BLOCKED_MOBILE_NUMBER,
        134     => 'Subscriber is blocked with the given DL Number',
        140     => 'Invalid Input Parameter from Merchant.',
        141     => ErrorCode::BAD_REQUEST_PAYMENT_CANCELLED_AT_LOGIN_SCREEN,
        142     => ErrorCode::BAD_REQUEST_PAYMENT_CANCELLED_AT_LOGIN_SCREEN,
        143     => 'Cancel Request by Customer before login screen is displayed properly',
        150     => 'Duplicate Transaction as similar transaction was seen in 30 sec.',
        151     => 'Transaction with the same order Id already exists.',
        152     => 'Merchant is not associated with channel.',
        153     => 'Channel is not configured with the Payment Mode',
        155     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_PAYMENT_AMOUNT_CROSSED,
        156     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED,
        157     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED,
        158     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED,
        159     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED,
        160     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED,
        161     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED,
        162     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_MAX_WRONG_ATTEMPT_LIMIT_CROSSED,
        163     => 'Could not pass velocity check for wallet.',
        164     => 'Wallet through put limit failure.',
        18      => 'Bank Failure in add money',
        180     => 'COD pending to be collected',
        19      => 'Bank Failure in add money withdraw',
        190     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED,
        191     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED,
        192     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED,
        196     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_MAX_AMOUNT_LIMIT_CROSSED_FOR_CUSTOMER,
        197     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED,
        198     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED,
        199     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED,
        200     => 'OTP request failed.',
        201     => 'Bank has blocked the card used to transact.',
        202     => ErrorCode::BAD_REQUEST_PAYMENT_CARD_INSUFFICIENT_BALANCE,
        203     => 'Card details entered by the user is/are invalid.',
        204     => 'Bank has declined the credit card used to transact.',
        205     => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_BY_BANK,
        206     => 'A duplicate transaction was being attempted at the bank.',
        207     => 'Card details entered by the user is/are invalid.',
        208     => 'Transaction has been declined by the acquirer bank.',
        209     => ErrorCode::BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID,
        210     => 'Lost Card received.',
        211     => 'Failure received from bank.',
        212     => 'Transaction is on hold by bank. Please check the status after some time.',
        213     => 'Encryption error at bank',
        214     => 'Suitable acquirer not found.',
        215     => 'Failure received from bank.',
        216     => 'Failure received from ICICI gateway.',
        217     => 'Gateway error.',
        218     => 'OTP Validated',
        219     => ErrorCode::BAD_REQUEST_PAYMENT_OTP_INCORRECT,
        220     => 'Bank communication error.',
        221     => Error\ErrorCode::GATEWAY_ERROR_CHECKSUM_MATCH_FAILED,
        222     => 'Transaction amount return by the gateway does not match with Paytm transaction amount.',
        223     => 'A duplicate transaction was being attempted at the bank. Transaction has been declined.',
        224     => Error\ErrorCode::GATEWAY_ERROR_REQUEST_TIMEOUT,
        225     => Error\ErrorCode::GATEWAY_ERROR_REQUEST_TIMEOUT,
        226     => 'some error at response parsing.',
        227     => ErrorCode::BAD_REQUEST_PAYMENT_FAILED,
        228     => 'Acquirer bank has been unable to authorize the transaction.',
        229     => ErrorCode::BAD_REQUEST_PAYMENT_DECLINED_3DSECURE_AUTH_FAILED,
        230     => '3D Secure Verification successful.',
        231     => 'Only Indian AMEX cards are allowed.',
        232     => 'Invalid account details.',
        233     => 'Authorization Failed.',
        234     => 'Invalid Username/Password.',
        235     => 'Insufficent balance.',
        236     => 'Wallet does not exist.',
        237     => 'Could not complete request. Please retry again.',
        238     => 'Invalid currency code.',
        239     => 'Merchant does not exist.',
        240     => 'Invalid total amount.',
        241     => 'First Txn Failed',
        242     => 'Child Txn auto refunded.',
        243     => 'Wallet Not Created',
        244     => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_NOT_ACTIVATED,
        245     => 'Redemption not allowed.',
        246     => ErrorCode::BAD_REQUEST_PAYMENT_OTP_VALIDATION_ATTEMPT_LIMIT_EXCEEDED,
        247     => 'Wallet under maintenance.',
        252     => 'Failure received from ICICI CC bank.',
        253     => 'Failure received from SBI CC bank.',
        301     => 'Invalid Json Request.',
        302     => 'Invalid Request type.',
        303     => 'Merchant Id can not be blank.',
        304     => 'App IP is blank.',
        305     => 'Merchant Id not registerd.',
        306     => 'Merchant Id expired.',
        307     => 'Security key expired.',
        308     => 'Invalid amount.',
        309     => 'Invalid order id.',
        310     => 'Invalid currency.',
        311     => 'Invalid device id.',
        312     => 'Invalid card number.',
        313     => 'Invalid stored card id.',
        314     => 'Invalid month.',
        315     => 'Invalid year.',
        316     => 'Invalid CVV.',
        317     => 'Invalid payment mode.',
        318     => 'Invalid customer id.',
        319     => 'Invalid industry type.',
        320     => 'Invalid card store flag.',
        321     => 'Invalid card delete flag.',
        322     => 'Card details not found.',
        323     => 'User is blocked.',
        324     => 'Duplicate customer id.',
        325     => 'Duplicate order id.',
        326     => 'Merchant is not associated.',
        327     => 'Channel is not associated.',
        328     => 'Invalid PaytmId.',
        329     => 'Invalid OTP.',
        330     => Error\ErrorCode::GATEWAY_ERROR_CHECKSUM_MATCH_FAILED,
        331     => 'Record not found.',
        332     => 'Order id can\'t be greater than 50 characters.',
        333     => 'Customer id can\'t be greater than 50 characters.',
        334     => 'Invalid Order Id.',
        335     => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        336     => 'Invalid transaction type.',
        337     => 'From Date is invalid.',
        338     => 'To Date is invalid.',
        339     => 'Invalid MMID.',
        340     => 'Invalid Mobile.',
        341     => 'EmailID is missing',
        343     => 'Invalid Token.',
        344     => 'Invalid Wallet Type.',
        345     => 'Request not unique',
        346     => 'Invalid request ID',
        347     => 'Invalid rewards member',
        348     => 'Invalid request',
        400     => 'Transaction status not confirmed yet.',
        401     => 'Abandoned transaction.',
        402     => 'Abondoned Transaction.',
        403     => 'Incorrect response from bank.',
        410     => 'Closed before page load',
        501     => 'System Error.',
        502     => 'Json Encoding error.',
        503     => 'Fee not configured for this card category type.',
        600     => ErrorCode::GATEWAY_ERROR_INVALID_REQUEST_BODY,
        601     => ErrorCode::GATEWAY_ERROR_TRANSACTION_PENDING,
        607     => ErrorCode::GATEWAY_ERROR_PAYMENT_REFUND_FAILED,
        610     => 'Transaction fully refunded already',
        617     => ErrorCode::GATEWAY_ERROR_REFUND_DUPLICATE_REQUEST,
        619     => ErrorCode::GATEWAY_ERROR_REFUND_INVALID_AMOUNT,
        626     => ErrorCode::GATEWAY_ERROR_ANOTHER_REFUND_IN_PROGRESS_FOR_SAME_PAYMENT,
        627     => ErrorCode::GATEWAY_ERROR_TRANSACTION_DETAILS_MISMATCH,
        628     => ErrorCode::GATEWAY_ERROR_TRANSACTION_PENDING,
        629     => ErrorCode::GATEWAY_ERROR_REFUND_DUPLICATE_REQUEST,
        635     => ErrorCode::GATEWAY_ERROR_REFUND_INVALID_AMOUNT,
        701     => 'Invalid Ref ID',
        8000    => 'Invalid Response Code',
        8001    => 'Beneficiary is non-reloadable card',
        8002    => 'Invalid MMID / IFSC',
        8003    => 'Payee is a merchant and not an individual',
        8005    => 'Subprogram error',
        8006    => 'CBS Offline',
        8007    => 'Invalid Transaction',
        8008    => 'Transaction Amount cannot be zero',
        8009    => 'OTP Not Present',
        8010    => 'Not sufficient funds',
        8011    => 'Transaction not permitted to account',
        8012    => 'Txn frequency exceeded',
        8013    => 'Invalid NBIN',
        8014    => 'Cutoff is in progress',
        8015    => Error\ErrorCode::GATEWAY_ERROR_REQUEST_TIMEOUT,
        8016    => 'Duplicate Transaction',
        8017    => 'Unable to process',
        8018    => 'Verification Successful but original credit transaction failed',
        8019    => 'Invalid Beneficiary Mobile Number/MMID',
        8020    => 'Invalid A/c Number or IFSC Code',
        8021    => 'Amount limit Exceeded',
        8022    => 'Account Blocked/Frozen',
        8023    => 'NRE Account',
        8024    => 'Account Closed',
        8025    => 'Limit exceeded for member bank',
        8026    => 'Transaction not permitted for this Account',
        8027    => 'Transaction limit exceeded for this Account',
        8028    => ErrorCode::BAD_REQUEST_PAYMENT_OTP_INCORRECT,
        8029    => 'Merchant Validation Fail',
        8030    => 'No response from merchant system',
        8031    => 'OTP Amount Limit Exceeded',
        8032    => 'Merchant Online Validation Required Not Available',
        8033    => 'OTP Expired',
        8034    => 'Merchant key Not configured',
        8035    => 'Payment Reference value is required.But value not present',
        8036    => Error\ErrorCode::GATEWAY_ERROR_CHECKSUM_MATCH_FAILED,
        8037    => 'Invalid Account Type',
        8038    => 'Functionality not suppored by Bank',
        8039    => 'Invalid IFSC',
        8040    => 'Invalid NBIN',
        8041    => 'Transaction Not permitted to Merchant a/c',
        8042    => 'Invalid Merchant Mobile Number/MMID',
        8043    => 'Merchant A/c is NRE Account',
        8044    => 'No connectivity with NPCI',
        8045    => 'No connectivity with NPCI',
        8046    => 'Invalid A/c Number or IFSC Code',
        8047    => 'Invalid Remittor Mobile Number/MMID',
        8048    => 'Remittor A/c is NRE Account',
        8049    => 'Transaction Not permitted to Remittor a/c',
        8050    => 'Payee is an individual and not a merchant',
        8051    => 'Invalid Service Request',
        8052    => 'Invalid Date Time',
        8053    => 'Invalid Merchant Id',
        8054    => 'Invalid Trace Number',
        8055    => 'Invalid Request Type',
        8056    => 'Invalid Bene Mobile Number',
        8057    => 'Invalid Bene MMID',
        8058    => 'Invalid Bene IFSC Code',
        8059    => 'Invalid Bene Account Number',
        8060    => 'Invalid Amount',
        8061    => Error\ErrorCode::GATEWAY_ERROR_CHECKSUM_MATCH_FAILED,
        8062    => 'Duplicate Trace Id',
        8063    => 'Invalid Message',
        8064    => 'Invalid Queryback Trace Number',
        8065    => 'No Such Transaction Request',
        8066    => 'Invalid Response Code',
        8067    => 'Invalid Status Query Flag',
        810     => 'Closed after page load',
        841     => 'Cancel Request by Customer(Before page load)',
        901     => 'Subscription ID not found.',
        902     => 'Saved Card ID not found.',
        903     => Error\ErrorCode::GATEWAY_ERROR_CHECKSUM_MATCH_FAILED,
        904     => 'SSO ID not found.',
        905     => 'MID not found.',
        906     => 'Frequency not found.',
        907     => 'Frequency unit not found.',
        908     => 'Amount not found.',
        909     => 'Grace Days not found.',
        910     => 'Service ID not found.',
        911     => 'Invalid subscription ID.',
        912     => 'Invalid Frequency.',
        913     => 'Invalid Subscription amount.',
        914     => 'Invalid Grace Days.',
        915     => 'Subscription not available.',
        916     => 'Renewal date invalid.',
        917     => ErrorCode::GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT,
        918     => 'Subscription expired.',
        919     => 'Subscription inactive.',
        920     => 'Merchant not configured for subscription.',
        921     => 'SSO Token not found.',
        922     => 'User authentication failed.',
        923     => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
    );

    protected static $success = array(
        1, 8,
    );

    public static function getResponseMessage($code)
    {
        $codes = ResponseCode::$codes;

        return $codes[(int) $code];
    }

    public static function getStatus($code)
    {
        ; // @todo
    }

    public static function getApiErrorCode($code)
    {
        $class = 'RZP\Error\ErrorCode::';

        if (isset(self::$codes[$code]) === false)
        {
            return ErrorCode::BAD_REQUEST_PAYMENT_FAILED;
        }

        $apiCode = self::$codes[$code];

        if (defined($class . $apiCode))
        {
            return $apiCode;
        }

        return ErrorCode::BAD_REQUEST_PAYMENT_FAILED;
    }
}
