<?php

namespace RZP\Gateway\Wallet\Freecharge;

use RZP\Error;
use RZP\Error\ErrorCode;
use RZP\Gateway\Base;

class ResponseCodeMap extends Base\ResponseCodeMap
{
    public static $codes = array(
        'E001'  => ErrorCode::GATEWAY_ERROR_INVALID_TERMINAL_ID,
        'E002'  => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        'E003'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E004'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E005'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E006'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E007'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E008'  => ErrorCode::GATEWAY_ERROR_NO_RECORDS_FOUND,
        # changing to bad request error to mute error emails
        'E018'  => ErrorCode::BAD_REQUEST_PAYMENT_FAILED,
        'E023'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E024'  => ErrorCode::GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT,
        'E026'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E027'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E100'  => ErrorCode::GATEWAY_ERROR_UNKNOWN_ERROR,
        'E101'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E102'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E104'  => ErrorCode::GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT,
        'E105'  => ErrorCode::GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT,
        'E108'  => ErrorCode::GATEWAY_ERROR_CARD_INVALID_CVV,
        'E109'  => ErrorCode::GATEWAY_ERROR_CARD_INVALID_NUMBER,
        'E113'  => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_BANK_CODE,
        'E114'  => ErrorCode::BAD_REQUEST_PAYMENT_INVALID_BANK_CODE,
        'E121'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E300'  => ErrorCode::GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT,
        'E301'  => ErrorCode::GATEWAY_ERROR_PAYMENT_REFUND_FAILED,
        'E600'  => ErrorCode::GATEWAY_ERROR_INVALID_TERMINAL_ID,
        'E601'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E603'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E604'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E617'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E618'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E619'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E620'  => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_INVALID_GATEWAY_TOKEN,
        'E621'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E622'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E623'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E624'  => ErrorCode::GATEWAY_ERROR_INVALID_PARAMETERS,
        'E625'  => ErrorCode::BAD_REQUEST_PAYMENT_WALLET_INSUFFICIENT_BALANCE,
        'E626'  => ErrorCode::GATEWAY_ERROR_PAYMENT_REFUND_FAILED,
        'E627'  => ErrorCode::BAD_REQUEST_PAYMENT_ALREADY_REFUND_INITIATED,
        'E628'  => ErrorCode::GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT,
        'E629'  => ErrorCode::BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_CAPTURED,
        'E701'  => ErrorCode::BAD_REQUEST_PAYMENT_OTP_EXPIRED,
        'E702'  => ErrorCode::BAD_REQUEST_PAYMENT_OTP_INCORRECT,
    );
}
