<?php

return [
    'airtel' => [
        'SNO'                      => '1',
        'DATE_AND_TIME'            => '06-NOV-22 02:13:08',
        'TRANSACTION_ID'           => 'PH211060222643709R',
        'CUSTOMER_MOBILE_NO'       => '9440728325',
        'PARTNER_TXN_ID'           => '',
        'ORIGINAL_INPUT_AMT'       => 500,
        'COMMISION_DR_'            => 0,
        'COMMISION_CR_'            => 0,
        'CGST_DR_'                 => 0,
        'CGST_CR_'                 => 0,
        'SGST_DR_'                 => 0,
        'SGST_CR_'                 => 0,
        'TDS_DR_'                  => 0,
        'TDS_CR_'                  => 0,
        'GDS_DR_'                  => 0,
        'GDS_CR_'                  => 0,
        'NET_AMOUNT_PAYABLE_CR_'   => '',
        'MERCHANT_STATE'           => 'KARNATAKA',
        'COUNTERPARTY_STATE'       => 'KARNATAKA',
        'STORE_ID'                 => '7.5',
        'TILL_ID'                  => 'RAZORPAY',
        'TRANSACTION_STATUS'       => 'Refund',
        'MERCHANT_MSISDN'          => '1000003303',
        'MERCHANT_ID'              => '11299660',
        'MERCHANT_ACCOUNT_NUMBER'  => '1012257321',
        'MERCHANT_NAME'            => 'RAZORPAY SOFTWARE PVT LTD',
        'MERCHANT_SETTLEMENT_TYPE' => '2',
        'NET_AMOUNT_PAYABLE_DR_'   => 500,
        'REF_TXN_NO_ORG'           => 'PH211022196633076',
    ],
];
