user www-data;
worker_processes  auto;
pid /run/openresty.pid;

events {
    worker_connections  1024;
}

# These environment variables(with defaults) are made available to lua module.
env RESTY_REDIS_TIMEOUT_MS;
env RESTY_REDIS_HOST;
env RESTY_REDIS_PORT;
env RESTY_REDIS_MAX_IDLE_MS;
env RESTY_REDIS_POOL_SIZE;

http {
    resolver 127.0.0.1;
    include mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    sendfile on;
    #tcp_nopush on;
    keepalive_timeout 65;
    #gzip on;

    include ../sites/*;
}
