const BASE_PATH = '../playwright/storageState';

// TODO: consume this from shared-utils in future
const getStorageStatePath = (BASE_PATH) => ({
  EMAIL_TEST_LOGIN_STATE: `${BASE_PATH}/desktop-test-mode-login.json`,
  EMAIL_LIVE_LOGIN_STATE: `${BASE_PATH}/desktop-live-mode-login.json`,
  TRANSACTIONS_LOGIN_STATE: `${BASE_PATH}/desktop-transactions-login.json`,
  SETTLEMENTS_LOGIN_STATE: `${BASE_PATH}/desktop-settlement-login.json`,
  INTERNATIONAL_LOGIN_STATE: `${BASE_PATH}/desktop-international-login.json`,
  ACTIVATED_NOT_IE_STATE: `${BASE_PATH}/activated-not-ie-login.json`,
  CAPITAL_RESELLER_PARTNER_TEST_LOGIN_STATE: `${BASE_PATH}/capital-reseller-partner-desktop-test-mode-login.json`,
  MAGIC_CHECKOUT_STATE: `${BASE_PATH}/magic-checkout.json`,
  RESELLER_PARTNER_TEST_LOGIN_STATE: `${BASE_PATH}/reseller-partner-desktop-test-mode-login.json`,
  RESELLER_PARTNER_POS_TEST_LOGIN_STATE: `${BASE_PATH}/reseller-partner-pos-desktop-test-mode-login.json`,
  RESELLER_PARTNER_AGENT_TEST_LOGIN_STATE: `${BASE_PATH}/reseller-partner-agent-desktop-test-mode-login.json`,
  AGGREGATOR_PARTNER_TEST_LOGIN_STATE: `${BASE_PATH}/aggregator-partner-desktop-test-mode-login.json`,
  PLATFORM_PARTNER_TEST_LOGIN_STATE: `${BASE_PATH}/platform-partner-desktop-test-mode-login.json`,
  OPTIMIZER_LOGIN_STATE: `${BASE_PATH}/desktop-optimizer-login.json`,
  POS_LOGIN_STATE: `${BASE_PATH}/pos-login.json`,
  POS_ORDER_DETAILS_LOGIN_STATE: `${BASE_PATH}/pos-login-order-details.json`,
  OPTIMIZER_V1_LOGIN_STATE: `${BASE_PATH}/desktop-optimizer-v1-login.json`,
  INTERNATIONAL_ACTIVATION_STATE: `${BASE_PATH}/international-activation.json`,
  WALLET_REPORTS_LOGIN_STATE: `${BASE_PATH}/mobile-wallet-reports-login.json`,
  MOBILE_TEST_GCMS_STATE: `${BASE_PATH}/mobile-test-mode-gcms.json`,
  CURLEC_TEST_LOGIN_STATE: `${BASE_PATH}/curlec-test-mode-login.json`,
});

const routes = {
  SIGN_IN_PATH: '/?screen=sign_in&isTestEnv=true',
  DASHBOARD: '/app/dashboard',
  ACCOUNT_SETTINGS: '/app/account-settings',
  STREAKS_REWARDS: '/app/streak-reward',
  BALANCES: '/app/payments-and-refunds-settings/balances',
  CREDITS: '/app/payments-and-refunds-settings/credits',
  REMINDERS: '/app/payments-and-refunds-settings/reminders',
  CAPTURE_AND_REFUND_SETTINGS: '/app/payments-and-refunds-settings/capture-refund-settings',
  TRANSACTION_LIMITS: '/app/payments-and-refunds-settings/transaction-limits',
  MANAGE_TEAM: '/app/business-settings/team',
  SETTLEMENTS: '/app/settlements',
  GST_DETAILS: '/app/business-settings/gst',
  SMS_NOTIFICATIONS: '/app/notification-settings/sms',
  API_KEYS: '/app/website-app-settings/api-keys',
  WEBHOOKS: '/app/website-app-settings/webhooks',
  CUSTOMERS: '/app/customers',
  CUSTOMER_SUPPORT_DETAILS: '/app/business-settings/customer-support',
  BUSINESS_DETAILS: '/app/business-settings/business',
  PAYMENT_LINKS: '/app/paymentlinks',
  PAYMENTS: 'app/payments',
  DISPUTES: 'app/disputes',
  FAILED_PAYMENTS: 'app/failed-payments',
  ORDERS: 'app/orders',
  REFUNDS: 'app/refunds',
  BATCH_REFUNDS: 'app/refunds/batchuploads',
  BATCH_REFUNDS_UPLOAD: 'app/refunds/batchupload',
  SUCCESS_RATE: 'app/success-rate',
  PAYMENT_PAGES: 'app/paymentpages',
  MAGIC_CHECKOUT: 'app/magic/settings',
  FIRS: 'app/international-settings/firs',
  PARTNER_DASHBOARD: '/app/partners',
  PARTNER_PLAYBOOK: '/app/partners/playbook',
  PARTNER_PRICING_PLANS: '/app/partner-pricing-plans',
  CLIENT_ACCOUNTS: '/app/partners/submerchants',
  CLIENT_ACCOUNTS_CAPITAL: '/app/partners/submerchants/capital',
  CLIENT_ACCOUNTS_POS: '/app/partners/submerchants/pos',
  AFFILIATE_ACCOUNTS: '/app/partners/submerchants',
  AFFILIATE_ACCOUNTS_CAPITAL: '/app/partners/submerchants/capital',
  OPTIMIZER: 'app/optimizer/rules',
  POS: '/app/pos',
  BATCH_PAYMENT_PAGES: '/app/paymentpages/batchpaymentpages',
  WHATSAPP_ACCOUNT_SETUP: 'app/payments-and-refunds-settings/whatsapp-account-setup',
  PAYMENT_METRICS: '/app/payment-metrics',
  INTERNATIONAL_PAYMENTS: '/app/payment-methods/international-payments',
  WALLET_REPORTS: '/app/wallet/reports',
  GCMS_PROGRAMS: '/app/gcms/programs',
  GCMS_FUNDS_RESELLER_ACCOUNTS: '/app/gcms/funds/reseller-account',
  GCMS_BRAND_TRANSACTIONS: '/app/gcms/funds/brand-account',
  GCMS_ORDERS: '/app/gcms/orders',
  GCMS_ORDERS_CREATE: '/app/gcms/orders/create',
  GCMS_RESELLERS: '/app/gcms/resellers',
  APP_STORE: '/app/app-store',
  RIZE_MARKETPLACE: '/app/rize-marketplace',
  RISK_AND_FRAUD: '/app/risk-and-fraud',
  RECON_DASHBOARD: '/app/reconciliations/dashboard',
};

module.exports = {
  getStorageStatePath,
  routes,
  BASE_PATH,
};
