/*
 * User level map to decide whether a module can be viewed by the give role.
 *
 * */
export default {
  home: ['owner', 'admin', 'manager', 'operations', 'finance'],
  payments: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'support',
    'rbl_supervisor',
    'rbl_agent',
    'agent',
  ],
  orders: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'support',
    'rbl_supervisor',
    'rbl_agent',
  ],
  refunds: ['owner', 'admin', 'manager', 'operations', 'finance', 'support'],
  payments_batch_uploads: ['owner', 'admin', 'manager', 'operations'],
  refunds_batch_uploads: ['owner', 'admin', 'manager', 'operations'],
  settlements: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'support',
    'rbl_supervisor',
    'agent',
  ],
  invoices: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'support',
    'sellerapp',
    'agent',
    'rbl_supervisor',
    'sellerapp_plus',
  ],
  items: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'support',
    'sellerapp',
    'sellerapp_plus',
    'agent',
  ],
  payment_links: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'sellerapp',
    'agent',
    'rbl_supervisor',
    'sellerapp_plus',
    'rbl_agent',
  ],
  payment_links_batch_uploads: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'agent',
    'rbl_supervisor',
  ],
  payment_pages: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'sellerapp',
  ],
  accounts: ['owner', 'admin', 'manager'],
  marketplace: ['owner', 'admin', 'manager', 'operations'],
  subscriptions: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'support',
  ],
  addons: ['owner', 'admin', 'manager', 'operations', 'finance', 'support'],
  virtual_accounts: ['owner', 'admin', 'manager', 'operations', 'finance'],
  customers: ['owner', 'admin', 'manager', 'operations', 'finance', 'support'],
  reports: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'rbl_supervisor',
    'agent',
    'support',
    'sellerapp_plus',
  ],
  api_keys: ['owner', 'admin'],
  profile: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'support',
    'sellerapp',
    'rbl_supervisor',
    'rbl_agent',
  ],
  add_funds: ['owner', 'admin', 'manager', 'operations'],
  profile_gst: [
    'owner',
    'admin',
    'manager',
    'operations',
    'finance',
    'support',
    'sellerapp',
    'agent',
  ],
  credits: ['owner', 'admin', 'manager', 'operations', 'finance'],
  activation: ['owner', 'admin', 'manager'],
  referrals: ['owner', 'admin', 'manager', 'operations', 'finance', 'support'],
  team: ['owner', 'admin', 'rbl_supervisor'],
  invitations: ['owner', 'rbl_supervisor'],
  webhooks: ['owner', 'admin', 'manager'],
  configuration: ['owner', 'admin', 'manager'],
  applications: ['owner'],

  // partner dashboard permissions
  submerchants: ['owner', 'admin', 'manager'],
  partner_settings: ['owner', 'admin', 'manager'],
  earnings: ['owner', 'admin', 'manager'],
  partner_applications: ['owner', 'manager', 'admin'],
};
