export enum BULK_INVITE_STEPS {
  BULK_INVITE_FORM = 'BULK_INVITE_FORM',
  KYC_ACCESS_FORM = 'KYC_ACCESS_FORM',
  SUCCESS_SCREEN_OPT_IN = 'SUCCESS_SCREEN_OPT_IN',
  SUCCESS_SCREEN_OPT_OUT = 'SUCCESS_SCREEN_OPT_OUT',
}
