export const SYNCHRONIZE_EMAIL_SETTINGS_ON_GRAPHQL_EMAIL_MUTATION_UPDATE_SUCCESS =
  'SYNCHRONIZE_EMAIL_SETTINGS_ON_GRAPHQL_MUTATION_UPDATE_SUCCESS';

export const updateEmailSettingsInStore = (reportEmails) => {
  return {
    type: SYNCHRONIZE_EMAIL_SETTINGS_ON_GRAPHQL_EMAIL_MUTATION_UPDATE_SUCCESS,
    payload: reportEmails,
  };
};
