import { SubmerchantPaymentMethod } from './types';

export const PAYMENT_METHODS_IN_ORDER: Array<SubmerchantPaymentMethod> = [
  'account',
  'aeps',
  'app',
  'bank_account',
  'bank_transfer',
  'card',
  'cardless_emi',
  'cod',
  'customer',
  'emandate',
  'emi',
  'fpx',
  'fund_transfer',
  'intl_bank_transfer',
  'nach',
  'netbanking',
  'offline',
  'paylater',
  'transfer',
  'upi',
  'vpa',
  'wallet',
];
export const PAYMENT_METHODS_MAP: Partial<Record<SubmerchantPaymentMethod, string>> = {
  account: 'Transfer: Account (Marketplace)',
  aeps: 'AEPS',
  app: 'App',
  bank_account: 'Bank Account (Fund Account Validation)',
  bank_transfer: 'Bank Transfer',
  card: 'Card',
  cardless_emi: 'Cardless EMI',
  cod: 'Cash on delivery',
  customer: 'Transfer: Customer (Openwallet)',
  emandate: 'e-Mandate',
  emi: 'EMI',
  fpx: 'FPX',
  fund_transfer: 'Payout: Fund Transfer',
  intl_bank_transfer: 'Intl Bank Transfer',
  nach: 'NACH',
  netbanking: 'Netbanking',
  offline: 'Offline',
  paylater: 'paylater',
  transfer: 'Transfer',
  upi: 'UPI',
  vpa: 'VPA (Fund Account Validation)',
  wallet: 'Wallet',
};
