<?php

return [
    'permissions' => [
        // All permissions in trimmed in down permissions
        'view_all_merchants',
        'view_merchant',
        'create_merchant_lock',
        'create_merchant_unlock',
        'edit_merchant',
        'edit_activate_merchant',
        'edit_merchant_enable_live',
        'edit_merchant_disable_live',
        'edit_merchant_archive',
        'edit_merchant_unarchive',
        'view_activation_form',
        'edit_merchant_confirm',
        'edit_merchant_lock_activation',
        'edit_merchant_unlock_activation',
        'edit_merchant_hold_funds',
        'edit_merchant_release_funds',
        'view_merchant_balance_test',
        'view_merchant_balance_live',
        'view_all_role',
        'view_role',
        'create_role',
        'edit_role',
        'delete_role',
        'view_all_group',
        'view_group',
        'create_group',
        'edit_group',
        'delete_group',
        'group_get_allowed_groups',
        'view_all_admin',
        'view_admin',
        'create_admin',
        'edit_admin',
        'delete_admin',
        'view_all_permission',
        'view_auditlog',
    ],

    'default_role_name' => 'SuperAdmin',
    'default_role_desc' => 'superadmin with all possible permissions',
];
