<?php

return [
    'experiments' => [

        // Add splitz experiment ids here.

        //project nitro campaign experiments
        'ANNOUNCEMENT_NITRO_HYDERABAD_SPLITZ' => env('ANNOUNCEMENT_NITRO_HYDERABAD_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_KOLKATA_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_KOLKATA_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CHENNAI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CHENNAI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_SURAT_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_SURAT_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_JAIPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_JAIPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_GANDHINAGAR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_GANDHINAGAR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_VADODARA_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_VADODARA_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_AHMEDABAD_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_AHMEDABAD_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_BANGALORE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_BANGALORE_V1_SPLITZ',''),
        'ANNOUNCEMENT_RETENTION1_APRIL2021_SPLITZ' => env('ANNOUNCEMENT_RETENTION1_APRIL2021_SPLITZ',''),

        // developer csat survey experiment
        'ANNOUNCEMENT_DX_CSAT_APRIL2021_SPLITZ' => env('ANNOUNCEMENT_DX_CSAT_APRIL2021_SPLITZ', ''),

        // checkout rewards campaign
        'ANNOUNCEMENT_CHECKOUT_REWARDS_ENABLED_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_ENABLED_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_LIVE_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_LIVE_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SEGMENT2_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SEGMENT2_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_GO_LIVE_READY_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_GO_LIVE_READY_SPLITZ', ''),

        // Announcement Text vs Icon vs What's New text experiment
        'ANNOUNCEMENT_TEXT_EXPERIMENT_SPLITZ' => env('ANNOUNCEMENT_TEXT_EXPERIMENT_SPLITZ', ''),
        'WHATSNEW_TEXT_EXPERIMENT_SPLITZ' => env('WHATSNEW_TEXT_EXPERIMENT_SPLITZ', ''),

        //QR Code campaign
        'ANNOUNCEMENT_QR_CODE_V1_SPLITZ' => env('ANNOUNCEMENT_QR_CODE_V1_SPLITZ', ''),

        //MTU Saver campaign
        'ANNOUNCEMENT_MTU_SAVER_V1_SPLITZ' => env('ANNOUNCEMENT_MTU_SAVER_V1_SPLITZ', ''),
    ]
];
