<?php

return [
    'experiments' => [

        // Add splitz experiment ids here.

        //project nitro campaign experiments
        'ANNOUNCEMENT_NITRO_HYDERABAD_SPLITZ' => env('ANNOUNCEMENT_NITRO_HYDERABAD_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_KOLKATA_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_KOLKATA_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CHENNAI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CHENNAI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_SURAT_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_SURAT_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_JAIPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_JAIPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_GANDHINAGAR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_GANDHINAGAR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_VADODARA_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_VADODARA_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_AHMEDABAD_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_AHMEDABAD_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_BANGALORE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_BANGALORE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_DELHI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_DELHI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_MUMBAI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_MUMBAI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_PUNE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_PUNE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_GURGAON_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_GURGAON_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_NAGPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_NAGPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_KOLHAPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_KOLHAPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_COIMBATORE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_COIMBATORE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_OTHER_CITIES_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_OTHER_CITIES_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_APP_SWITCHER_SPLITZ' => env('ANNOUNCEMENT_NITRO_APP_SWITCHER_SPLITZ',''),

        //project nitro and corporate cards campaign experiments
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_HYDERABAD_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_HYDERABAD_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_KOLKATA_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_KOLKATA_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_CHENNAI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_CHENNAI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_SURAT_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_SURAT_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_JAIPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_JAIPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_GANDHINAGAR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_GANDHINAGAR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_VADODARA_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_VADODARA_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_AHMEDABAD_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_AHMEDABAD_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_BANGALORE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_BANGALORE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_DELHI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_DELHI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_MUMBAI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_MUMBAI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_PUNE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_PUNE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_GURGAON_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_GURGAON_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_NAGPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_NAGPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_KOLHAPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_KOLHAPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_COIMBATORE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_COIMBATORE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_OTHER_CITIES_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_OTHER_CITIES_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_TEST_ACCOUNT_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_TEST_ACCOUNT_SPLITZ',''),

        'NITRO_FORM_AB_SPLITZ' => env('NITRO_FORM_AB_SPLITZ',''),

        'ANNOUNCEMENT_RETENTION1_APRIL2021_SPLITZ' => env('ANNOUNCEMENT_RETENTION1_APRIL2021_SPLITZ',''),

        // developer csat survey experiment
        'ANNOUNCEMENT_DX_CSAT_APRIL2021_SPLITZ' => env('ANNOUNCEMENT_DX_CSAT_APRIL2021_SPLITZ', ''),

        // checkout rewards campaign
        'ANNOUNCEMENT_CHECKOUT_REWARDS_ENABLED_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_ENABLED_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_LIVE_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_LIVE_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SEGMENT2_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SEGMENT2_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_GO_LIVE_READY_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_GO_LIVE_READY_SPLITZ', ''),

        // Announcement Text vs Icon vs What's New text experiment
        'ANNOUNCEMENT_TEXT_EXPERIMENT_SPLITZ' => env('ANNOUNCEMENT_TEXT_EXPERIMENT_SPLITZ', ''),
        'WHATSNEW_TEXT_EXPERIMENT_SPLITZ' => env('WHATSNEW_TEXT_EXPERIMENT_SPLITZ', ''),

        // partnership merchant validation
        'MERCHANT_VALIDATION' => env('MERCHANT_VALIDATION', ''),

        // Partnership Survey
        'PARTNERSHIP_NPS' => env('PARTNERSHIP_NPS', ''),

        // partnership for RazorpayX
        'PARTNERSHIP_FOR_RAZOARPAYX' => env('PARTNERSHIP_FOR_RAZOARPAYX', ''),
        'PARTNERSHIP_FOR_RAZOARPAYX_RAMP' => env('PARTNERSHIP_FOR_RAZOARPAYX_RAMP', ''),

        'SUBMERCHANT_KYC_RESELLER' => env('SUBMERCHANT_KYC_RESELLER', ''),
        'SUBMERCHANT_KYC_RESELLER_RAMP' => env('SUBMERCHANT_KYC_RESELLER_RAMP', ''),

        // partnership for Phantom
        'PARTNERSHIP_FOR_PHANTOM' => env('PARTNERSHIP_FOR_PHANTOM', ''),

        // partner onboarding resuming
        'SHOW_RESUME_ONBAORDING' => env('SHOW_RESUME_ONBAORDING', ''),

        //QR Code campaign
        'ANNOUNCEMENT_QR_CODE_V1_SPLITZ' => env('ANNOUNCEMENT_QR_CODE_V1_SPLITZ', ''),

        'WHATSNEW_LAZY_EXPERIMENT_SPLITZ' => env('WHATSNEW_LAZY_EXPERIMENT_SPLITZ', ''),

        'SSL_UPDATE_ANNOUNCEMENT_SPLITZ' => env('SSL_UPDATE_ANNOUNCEMENT_SPLITZ', ''),
        'SELF_SERVE_ANNOUNCEMENT_SPLITZ' => env('SELF_SERVE_ANNOUNCEMENT_SPLITZ', ''),
        'CATALYST_CAMPAIGN_SPLITZ' => env('CATALYST_CAMPAIGN_SPLITZ', ''),

        'PAYMENT_LINKS_PRIMARY_PRODUCT_SPLITZ' => env('PAYMENT_LINKS_PRIMARY_PRODUCT_SPLITZ', ''),
        'ULTRA_CAMPAIGN_ANNOUNCEMENT_SPLITZ' => env('ULTRA_CAMPAIGN_ANNOUNCEMENT_SPLITZ', ''),
        'ULTRA_CAMPAIGN_BANNER_SPLITZ' => env('ULTRA_CAMPAIGN_BANNER_SPLITZ', ''),
        'GS_ANNOUNCEMENTS_EXP' => env('GS_ANNOUNCEMENTS_EXP', ''),
        'GS_BANNERS_EXP' => env('GS_BANNERS_EXP', ''),

        // Moonshine
        'RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_0_SPLITZ' => env('RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_0_SPLITZ', ''),
        'RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_1_SPLITZ' => env('RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_1_SPLITZ', ''),
        'RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_2_SPLITZ' => env('RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_2_SPLITZ', ''),
        'RAZORPAYX_PAYROLL_EXPERIMENT_SPLITZ' => env('RAZORPAYX_PAYROLL_EXPERIMENT_SPLITZ', ''),

        // partnership for RazorpayX
        'INDEPENDENT_PARTNER_KYC' => env('INDEPENDENT_PARTNER_KYC', ''),

        // Payment Button Plugin
        'PLATFORM_PB_PLUGIN_GENERIC_MERCHANTS_ANNOUNCEMENT_SPLITZ' => env('PLATFORM_PB_PLUGIN_GENERIC_MERCHANTS_ANNOUNCEMENT_SPLITZ', ''),
        'PLATFORM_PB_PLUGIN_CHARITY_MERCHANTS_ANNOUNCEMENT_SPLITZ' => env('PLATFORM_PB_PLUGIN_CHARITY_MERCHANTS_ANNOUNCEMENT_SPLITZ', ''),
        'PLATFORM_PB_PLUGIN_LEARNING_MERCHANTS_ANNOUNCEMENT_SPLITZ' => env('PLATFORM_PB_PLUGIN_LEARNING_MERCHANTS_ANNOUNCEMENT_SPLITZ', ''),
        'PLATFORM_PB_PLUGIN_WEBDEV_MERCHANTS_ANNOUNCEMENT_SPLITZ' => env('PLATFORM_PB_PLUGIN_WEBDEV_MERCHANTS_ANNOUNCEMENT_SPLITZ', ''),

        // Failure Analysis Splitz
        'FAILURE_ANALYSIS_TEXT_EXP_SPLITZ' => env('FAILURE_ANALYSIS_TEXT_EXP_SPLITZ', ''),
        'FAILURE_ANALYSIS_PAYMENT_COUNT_EXP_SPLITZ' => env('FAILURE_ANALYSIS_PAYMENT_COUNT_EXP_SPLITZ', ''),
        'FAILURE_ANALYSIS_ROLLOUT_EXP_SPLITZ' => env('FAILURE_ANALYSIS_ROLLOUT_EXP_SPLITZ', ''),
        'FAILURE_ANALYSIS_MTV_EXP_SPLITZ' => env('FAILURE_ANALYSIS_MTV_EXP_SPLITZ', ''),
        // Keystone
        'KEYSTONE_CORPORATE_CARD_EXPERIMENT' => env('KEYSTONE_CORPORATE_CARD_EXPERIMENT', ''),
        'KEYSTONE_CASH_ADVANCE_EXPERIMENT' => env('KEYSTONE_CASH_ADVANCE_EXPERIMENT', ''),

        // EDX experiments
        'ZAPIER_ANNOUNCEMENT_SPLITZ' => env('ZAPIER_ANNOUNCEMENT_SPLITZ', ''),
        'AI_SENSY_BANNER_SPLITZ' => env('AI_SENSY_BANNER_SPLITZ', ''),
        'DEVELOPER_CONSOLE_SPLITZ' => env('DEVELOPER_CONSOLE_SPLITZ', ''),
        'DEVELOPER_CONSOLE_WEBHOOKS_TAB_SPLITZ' => env('DEVELOPER_CONSOLE_WEBHOOKS_TAB_SPLITZ', ''),

         //Razorpay Trusted Badge (RTB)
        'RTB_ANNOUNCEMENT' => env('RTB_ANNOUNCEMENT', ''),

        // Ultra phase 2
        'ULTRA_P2_CASH_ADVANCE_ANNOUNCEMENT_SPLITZ' => env('ULTRA_P2_CASH_ADVANCE_ANNOUNCEMENT_SPLITZ', ''),
        'ULTRA_P2_CASH_ADVANCE_BANNER_SPLITZ' => env('ULTRA_P2_CASH_ADVANCE_BANNER_SPLITZ', ''),

        // Cards Go Live
        'CARDS_GO_LIVE_SUBSCRIPTIONS_SPLITZ' => env('CARDS_GO_LIVE_SUBSCRIPTIONS_SPLITZ', ''),
        'CARDS_GO_LIVE_CAW_SPLITZ' => env('CARDS_GO_LIVE_CAW_SPLITZ', ''),

        // PP Zapier Banner
        'PP_ZAPIER_BANNER_SPLITZ' => env('PP_ZAPIER_BANNER_SPLITZ', ''),

        //Cross Border Payments Announcement
        'CROSS_BORDER_PAYMENTS_ANNOUNCEMENT' => env('CROSS_BORDER_PAYMENTS_ANNOUNCEMENT', ''),
        'NEOSTONE_EXPERIMENT' => env('NEOSTONE_EXPERIMENT', ''),
        'CONNECTED_BANKING_ICICI_EXP' => env('CONNECTED_BANKING_ICICI_EXP', ''),
        'SHOW_RAZORPAYX_WIDGET_EXP' => env('SHOW_RAZORPAYX_WIDGET_EXP', ''),

        //QR Code Announcement
        'QR_CODE_ANNOUNCEMENT' => env('QR_CODE_ANNOUNCEMENT', ''),

        //Nitro ICICI Campaign
        'NITRO_ICICI_BRANDED_CAMPAIGN' => env('NITRO_ICICI_BRANDED_CAMPAIGN', ''),
        'NITRO_ICICI_REMARKETING_CAMPAIGN' => env('NITRO_ICICI_REMARKETING_CAMPAIGN', ''),

        //Nitro CC Announcement
        'NITRO_CC_ANNOUNCEMENT' => env('NITRO_CC_ANNOUNCEMENT', ''),

        //Nitro CC Announcement
        'CATALYST_FL_BANNER' => env('CATALYST_FL_BANNER', ''),
        'CATALYST_EF_BANNER' => env('CATALYST_EF_BANNER', ''),
        'CATALYST_G_BANNER' => env('CATALYST_G_BANNER', ''),
        'AB_BANNER_CAROUSEL' => env('AB_BANNER_CAROUSEL', ''),

        //2FA Mobile Signup
        'ENABLE_2FA_MOBILE_SIGNUP_EXP_SPLITZ' => env('ENABLE_2FA_MOBILE_SIGNUP_EXP_SPLITZ', ''),

        //Digilocker EKYC
        'ENABLE_DIGILOCKER_EKYC_EXP_SPLITZ' => env('ENABLE_DIGILOCKER_EKYC_EXP_SPLITZ', ''),

        // New Nitro ICICI Experiment
        'NITRO_NEW_ICICI_BRANDED_EXP_SPLITZ' => env('NITRO_NEW_ICICI_BRANDED_EXP_SPLITZ', ''),
        'NITRO_NEW_ICICI_BASE_EXP_SPLITZ' => env('NITRO_NEW_ICICI_BASE_EXP_SPLITZ', ''),
        'NITRO_NEW_ICICI_CARDS_EXP_SPLITZ' => env('NITRO_NEW_ICICI_CARDS_EXP_SPLITZ', ''),

        // Nitro ICICI Mid Marketing Experiment
        'NITRO_ICICI_MID_MARKETING_EXPERIMENT' => env('NITRO_ICICI_MID_MARKETING_EXPERIMENT', ''),

        // Growth Services Integration with Exclusive Offer
        'GS_EXCLUSIVE_OFFER_SPLITZ' => env('GS_EXCLUSIVE_OFFER_SPLITZ', ''),

        // Show L1 form on Login
        'SHOW_L1_FORM_ON_LOGIN' => env('SHOW_L1_FORM_ON_LOGIN', ''),

        // Show Activation Form full view
        'SHOW_ACTIVATION_FORM_FULL_VIEW' => env('SHOW_ACTIVATION_FORM_FULL_VIEW', ''),

        // Ultra Campagin Experiment
        'ULTRA_CAMPAIGN_CAPITAL_CARDS_LOC_BOTH_EXP_SPLITZ' => env('ULTRA_CAMPAIGN_CAPITAL_CARDS_LOC_BOTH_EXP_SPLITZ', ''),
        'ULTRA_CAMPAIGN_CAPITAL_CARDS_ONLY_EXP_SPLITZ' => env('ULTRA_CAMPAIGN_CAPITAL_CARDS_ONLY_EXP_SPLITZ', ''),
        'ULTRA_CAMPAIGN_LOC_ONLY_EXP_SPLITZ' => env('ULTRA_CAMPAIGN_LOC_ONLY_EXP_SPLITZ', ''),

        // Cross Sell Subscriptions
        'CROSS_SELL_SUBSCRIPTIONS_EDUCATION_EXP_SPLITZ' => env('CROSS_SELL_SUBSCRIPTIONS_EDUCATION_EXP_SPLITZ', ''),
        'CROSS_SELL_SUBSCRIPTIONS_OTHER_BUSINESS_EXP_SPLITZ' => env('CROSS_SELL_SUBSCRIPTIONS_OTHER_BUSINESS_EXP_SPLITZ', ''),
        'ULTRA_EXCLUSIVEOFFER_CARD_A' => env('ULTRA_EXCLUSIVEOFFER_CARD_A', ''),
        'ULTRA_EXCLUSIVEOFFER_CARD_B' => env('ULTRA_EXCLUSIVEOFFER_CARD_B', ''),
        'ULTRA_EXCLUSIVEOFFER_CARD_LOC_TEST' => env('ULTRA_EXCLUSIVEOFFER_CARD_LOC_TEST', ''),

        // instant activation video enable
        'INSTANT_ACTIVATION_VIDEO_ENABLE_EXP_SPLITZ' => env('INSTANT_ACTIVATION_VIDEO_ENABLE_EXP_SPLITZ', ''),
        //new NC flow
        'ENABLE_EASY_DASHBOARD_NC' => env('ENABLE_EASY_DASHBOARD_NC', ''),
        // Onboarding all as resellers
        'PARTNERSHIP_ONBOARD_RESELLERS' => env('PARTNERSHIP_ONBOARD_RESELLERS', ''),
        'EASY_ONBOARDING_REDIRECT'      => env('EASY_ONBOARDING_REDIRECT', ''),
        'EASY_ONBOARDING_REFERRAL_LINK_REDIRECT_PARTNERSHIPS'      => env('EASY_ONBOARDING_REFERRAL_LINK_REDIRECT_PARTNERSHIPS', ''),

        'WEBSITE_COMPLIANCE_MODAL_EXP'      => env('WEBSITE_COMPLIANCE_MODAL_EXP', ''),
        'WEBSITE_COMPLIANCE_FLOW_EXP'      => env('WEBSITE_COMPLIANCE_FLOW_EXP', ''),

        // Cash Advance sidebar link position
        'CASH_ADVANCE_SIDEBAR_POSITION' => env('CASH_ADVANCE_SIDEBAR_POSITION', ''),

        // Experiment to enable status tracker for X Corporate Card product
        'X_CORPORATE_CARD_STATUS_TRACKER' => env('X_CORPORATE_CARD_STATUS_TRACKER', ''),
        // show invoices for current FY
        'INVOICE_CURRENT_FY' => env('INVOICE_CURRENT_FY', ''),

        //migrating apis to care ,this change is for adding reply api migration
        'ADD_REPLY_MIGRATION' => env('ADD_REPLY_MIGRATION', ''),

        // API Keys Page Revamp
        'API_KEYS_REVAMP' => env('API_KEYS_REVAMP', ''),

        // enable product led onboarding
        'PRODUCT_LED_ONBOARDING' => env('PRODUCT_LED_ONBOARDING', ''),

        // Left Nav revamp
        'LEFT_NAV_REVAMP' => env('LEFT_NAV_REVAMP', ''),

        // Reports Revamp
        'MERCHANT_REPORTS_REVAMP' => env('MERCHANT_REPORTS_REVAMP', ''),
        'PARTNER_REPORTS_REVAMP' => env('PARTNER_REPORTS_REVAMP', ''),
        'LA_REPORTS_REVAMP' => env('LA_REPORTS_REVAMP', ''),
        'REPORTS_REVAMP_RECENTS' => env('REPORTS_REVAMP_RECENTS', ''),

        // Account Settings Revamp
        'ACCOUNT_SETTINGS_REVAMP'  => env('ACCOUNT_SETTINGS_REVAMP', ''),

        // Universal Search V1
        'UNIVERSAL_SEARCH_ENABLED' => env('UNIVERSAL_SEARCH_ENABLED', ''),

         // Bank Account update Revamp
        'BANK_ACCOUNT_UPDATE_REVAMP'  => env('BANK_ACCOUNT_UPDATE_REVAMP', ''),

        // Settlement Revamp
        'SETTLEMENT_V3_REVAMP' => env('SETTLEMENT_V3_REVAMP', ''),

         // Payment Handle Onboarding
         'PAYMENT_HANDLE_ONBOARDING'  => env('PAYMENT_HANDLE_ONBOARDING', ''),

        // payroll wdiget on dashboard
        'SHOW_PAYROLL_WIDGET_EXP' => env('SHOW_PAYROLL_WIDGET_EXP', ''),

         // International enablement Revamp
        'INTERNATIONAL_ENABLEMENT_REVAMP'  => env('INTERNATIONAL_ENABLEMENT_REVAMP', ''),

        // get ticket api migrated to care service
        'GET_TICKET_MIGRATION' => env('GET_TICKET_MIGRATION', ''),

        // fetch all ticket api migrated to care service
        'FETCH_TICKETS_MIGRATION' => env('FETCH_TICKETS_MIGRATION', ''),

        // affordability widget on dashboard
        'SHOW_AFFORDABILITY_WIDGET_EXP' => env('SHOW_AFFORDABILITY_WIDGET_EXP', ''),
        'SHOW_AFF_WIDGET_SHOPIFY_WAIT_LIST' => env('SHOW_AFF_WIDGET_SHOPIFY_WAIT_LIST', ''),
        'SHOW_AFF_WIDGET_WOOC_WAIT_LIST' => env('SHOW_AFF_WIDGET_WOOC_WAIT_LIST', ''),

        // Partnership for Capital
        'PARTNERSHIP_CAPITAL' => env('PARTNERSHIP_CAPITAL', ''),

        // Partnership for Marketplace
        'ROUTE_PARTNERSHIPS' => env('ROUTE_PARTNERSHIPS', ''),

        // Revoke Application oauth
        'REVOKE_APPLICATION' => env('REVOKE_APPLICATION', ''),

        // Bundle Pricing
        'BUNDLE_PRICING' => env('BUNDLE_PRICING', ''),

        // settlement dashboard visibility
        'SETTLEMENT_DASHBOARD_VISIBILITY' => env('SETTLEMENT_DASHBOARD_VISIBILITY', ''),

        // FTUX for Onboarding
        'ONBOARDING_FTUX' => env('ONBOARDING_FTUX', ''),

         // MSME for Proprietership
         'COLLECT_MSME_CERTIFICATE_PROPRIETORSHIP' => env('COLLECT_MSME_CERTIFICATE_PROPRIETORSHIP', ''),

        // Payment Pages - Ecommerce
        'PP_ECOMMERCE_SPLITZ' => env('PP_ECOMMERCE_SPLITZ', ''),
        // Affordability Onboarding for SBI CC EMi and credit card segeration
        'SHOW_SEGREGATED_CREDIT_EMI_METHODS' => env('SHOW_SEGREGATED_CREDIT_EMI_METHODS', ''),
        'SHOW_INTERNATIONAL_PAYMENTS_BUTTON' => env('SHOW_INTERNATIONAL_PAYMENTS_BUTTON', ''),

        // Ecosystem Downtimes UI - Availability and Downtime
        'ECOSYSTEM_DOWNTIMES' => env('ECOSYSTEM_DOWNTIMES',''),

        // For showing Ternimal status banner on dashboard.
        'SHOW_TERMINAL_STATUS_BANNER' => env('SHOW_TERMINAL_STATUS_BANNER','')
    ]
];
