<?php

return [
    'experiments' => [

        // Add splitz experiment ids here.

        //project nitro campaign experiments
        'ANNOUNCEMENT_NITRO_HYDERABAD_SPLITZ' => env('ANNOUNCEMENT_NITRO_HYDERABAD_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_KOLKATA_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_KOLKATA_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CHENNAI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CHENNAI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_SURAT_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_SURAT_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_JAIPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_JAIPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_GANDHINAGAR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_GANDHINAGAR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_VADODARA_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_VADODARA_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_AHMEDABAD_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_AHMEDABAD_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_BANGALORE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_BANGALORE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_DELHI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_DELHI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_MUMBAI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_MUMBAI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_PUNE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_PUNE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_GURGAON_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_GURGAON_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_NAGPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_NAGPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_KOLHAPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_KOLHAPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_COIMBATORE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_COIMBATORE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_OTHER_CITIES_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_OTHER_CITIES_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_APP_SWITCHER_SPLITZ' => env('ANNOUNCEMENT_NITRO_APP_SWITCHER_SPLITZ',''),

        //project nitro and corporate cards campaign experiments
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_HYDERABAD_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_HYDERABAD_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_KOLKATA_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_KOLKATA_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_CHENNAI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_CHENNAI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_SURAT_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_SURAT_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_JAIPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_JAIPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_GANDHINAGAR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_GANDHINAGAR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_VADODARA_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_VADODARA_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_AHMEDABAD_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_AHMEDABAD_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_BANGALORE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_BANGALORE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_DELHI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_DELHI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_MUMBAI_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_MUMBAI_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_PUNE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_PUNE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_GURGAON_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_GURGAON_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_NAGPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_NAGPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_KOLHAPUR_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_KOLHAPUR_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_COIMBATORE_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_COIMBATORE_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_OTHER_CITIES_V1_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_OTHER_CITIES_V1_SPLITZ',''),
        'ANNOUNCEMENT_NITRO_CORPORATE_CARDS_TEST_ACCOUNT_SPLITZ' => env('ANNOUNCEMENT_NITRO_CORPORATE_CARDS_TEST_ACCOUNT_SPLITZ',''),

        'NITRO_FORM_AB_SPLITZ' => env('NITRO_FORM_AB_SPLITZ',''),

        'ANNOUNCEMENT_RETENTION1_APRIL2021_SPLITZ' => env('ANNOUNCEMENT_RETENTION1_APRIL2021_SPLITZ',''),

        // developer csat survey experiment
        'ANNOUNCEMENT_DX_CSAT_APRIL2021_SPLITZ' => env('ANNOUNCEMENT_DX_CSAT_APRIL2021_SPLITZ', ''),

        // checkout rewards campaign
        'ANNOUNCEMENT_CHECKOUT_REWARDS_ENABLED_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_ENABLED_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_LIVE_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_LIVE_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SEGMENT2_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_INTERESTED_SEGMENT2_SPLITZ', ''),
        'ANNOUNCEMENT_CHECKOUT_REWARDS_GO_LIVE_READY_SPLITZ' => env('ANNOUNCEMENT_CHECKOUT_REWARDS_GO_LIVE_READY_SPLITZ', ''),

        // Announcement Text vs Icon vs What's New text experiment
        'ANNOUNCEMENT_TEXT_EXPERIMENT_SPLITZ' => env('ANNOUNCEMENT_TEXT_EXPERIMENT_SPLITZ', ''),
        'WHATSNEW_TEXT_EXPERIMENT_SPLITZ' => env('WHATSNEW_TEXT_EXPERIMENT_SPLITZ', ''),

        // partnership for RazorpayX
        'PARTNERSHIP_FOR_RAZOARPAYX' => env('PARTNERSHIP_FOR_RAZOARPAYX', ''),

        'SUBMERCHANT_KYC_RESELLER' => env('SUBMERCHANT_KYC_RESELLER', ''),

        //QR Code campaign
        'ANNOUNCEMENT_QR_CODE_V1_SPLITZ' => env('ANNOUNCEMENT_QR_CODE_V1_SPLITZ', ''),

        'WHATSNEW_LAZY_EXPERIMENT_SPLITZ' => env('WHATSNEW_LAZY_EXPERIMENT_SPLITZ', ''),

        'SSL_UPDATE_ANNOUNCEMENT_SPLITZ' => env('SSL_UPDATE_ANNOUNCEMENT_SPLITZ', ''),
        'SELF_SERVE_ANNOUNCEMENT_SPLITZ' => env('SELF_SERVE_ANNOUNCEMENT_SPLITZ', ''),
        'CATALYST_CAMPAIGN_SPLITZ' => env('CATALYST_CAMPAIGN_SPLITZ', ''),

        'PAYMENT_LINKS_PRIMARY_PRODUCT_SPLITZ' => env('PAYMENT_LINKS_PRIMARY_PRODUCT_SPLITZ', ''),
        'ULTRA_CAMPAIGN_ANNOUNCEMENT_SPLITZ' => env('ULTRA_CAMPAIGN_ANNOUNCEMENT_SPLITZ', ''),
        'ULTRA_CAMPAIGN_BANNER_SPLITZ' => env('ULTRA_CAMPAIGN_BANNER_SPLITZ', ''),
        'GROWTH_SERVICE_ROLLOUT_EXP_SPLITZ' => env('GROWTH_SERVICE_ROLLOUT_EXP_SPLITZ', ''),
        'GROWTH_SERVICE_ROLLOUT_EXP_SPLITZ_KYC_DONE' => env('GROWTH_SERVICE_ROLLOUT_EXP_SPLITZ_KYC_DONE', ''),
        'GROWTH_SERVICE_ROLLOUT_EXP_SPLITZ_UNACTIVATED' => env('GROWTH_SERVICE_ROLLOUT_EXP_SPLITZ_UNACTIVATED', ''),

        // Moonshine
        'RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_0_SPLITZ' => env('RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_0_SPLITZ', ''),
        'RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_1_SPLITZ' => env('RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_1_SPLITZ', ''),
        'RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_2_SPLITZ' => env('RAZORPAYX_PAYROLL_EXPERIMENT_COHORT_2_SPLITZ', ''),
        'RAZORPAYX_PAYROLL_EXPERIMENT_SPLITZ' => env('RAZORPAYX_PAYROLL_EXPERIMENT_SPLITZ', ''),

        // partnership for RazorpayX
        'INDEPENDENT_PARTNER_KYC' => env('INDEPENDENT_PARTNER_KYC', ''),

        // Failure Analysis Splitz
        'FAILURE_ANALYSIS_TEXT_EXP_SPLITZ' => env('FAILURE_ANALYSIS_TEXT_EXP_SPLITZ', ''),
        'FAILURE_ANALYSIS_PAYMENT_COUNT_EXP_SPLITZ' => env('FAILURE_ANALYSIS_PAYMENT_COUNT_EXP_SPLITZ', ''),
        'FAILURE_ANALYSIS_ROLLOUT_EXP_SPLITZ' => env('FAILURE_ANALYSIS_ROLLOUT_EXP_SPLITZ', ''),
        // Keystone
        'KEYSTONE_CORPORATE_CARD_EXPERIMENT' => env('KEYSTONE_CORPORATE_CARD_EXPERIMENT', ''),
        'KEYSTONE_CASH_ADVANCE_EXPERIMENT' => env('KEYSTONE_CASH_ADVANCE_EXPERIMENT', ''),

        // EDX experiments
        'ZAPIER_ANNOUNCEMENT_SPLITZ' => env('ZAPIER_ANNOUNCEMENT_SPLITZ', ''),
        'AI_SENSY_BANNER_SPLITZ' => env('AI_SENSY_BANNER_SPLITZ', ''),
        
         //Razorpay Trusted Badge (RTB)
        'RTB_ANNOUNCEMENT' => env('RTB_ANNOUNCEMENT', ''),

        // Ultra phase 2
        'ULTRA_P2_CASH_ADVANCE_ANNOUNCEMENT_SPLITZ' => env('ULTRA_P2_CASH_ADVANCE_ANNOUNCEMENT_SPLITZ', ''),
        'ULTRA_P2_CASH_ADVANCE_BANNER_SPLITZ' => env('ULTRA_P2_CASH_ADVANCE_BANNER_SPLITZ', ''),

        // PP Zapier Banner
        'PP_ZAPIER_BANNER_SPLITZ' => env('PP_ZAPIER_BANNER_SPLITZ', ''),

    ]
];
