<?php

use RZP\Models\BankingAccount;
use RZP\Models\BankingAccountService\Constants as BasConstants;

return [
    'testApiToBasDtoAdapter' => [
        'apiInput' => [
            'account_ifsc'                    => 'SBIN01234',
            'account_number'                  => '12341678786950',
            'status'                          => 'doc_collection',
            'sub_status'                      => 'in_review',
            'beneficiary_pin'                 => '110093',
            'bank_internal_status'            => 'closed',
            'pincode'                         => '110093',
            'balance_id'                      => null,
            'bank_internal_reference_number'  => '203128886',
            'beneficiary_name'                => 'Y-AXIS GROUP OF INDUSTRIES',
            'account_currency'                => 'INR',
            'beneficiary_email'               => 'SENDMAIL4ADIL@GMAIL.COM',
            'beneficiary_mobile'              => '+91(0)9560569604',
            'beneficiary_city'                => 'NEWDE',
            'beneficiary_state'               => 'DLI',
            'beneficiary_country'             => 'IN',
            'beneficiary_address1'            => 'G F PLOT NO 12 KH NO 24 19 B 557',
            'beneficiary_address2'            => 'MAIN 33 FUTA ROAD RAJIV NAGAR',
            'beneficiary_address3'            => 'MANDOLI EXTN NEAR BUDH BAZAR DELHI',
            'bank_reference_number'           => '46436',
            'account_activation_date'         => 1678786950,
            'username'                        => 'ldap_id',
            'password'                        => 'ldap_password',
            'reference1'                      => 'corp_id',
            'details' => [
                'client_id' => 'CLIENT_ID',
                'client_secret' => 'CLIENT_SECRET',
                'merchant_email' => 'MERCHANT_EMAIL',
                'merchant_password' => 'MERCHANT_PASSWORD',
            ],
            'activation_detail' => [
                'merchant_poc_name' => 'MERCHANT_POC_NAME',
                'merchant_poc_email' => 'yaxisgroupofindustries@gmail.com',
                'merchant_poc_designation' => 'Proprietor',
                'merchant_poc_phone_number' => '+919560569604',
                'merchant_documents_address' => 'B-557, G/F PLOT NO-12 KH NO-24/19, MAIN 33FUTA ROAD RAJIV NAGAR MANDOLI EXTN NEAR BUDH BAZAR, DELHI, North East Delhi, Delhi, 110093',
                'merchant_city' => 'eastdelhi',
                'merchant_region' => 'north',
                'business_category' => 'sole_proprietorship',
                'average_monthly_balance' => 20000,
                'expected_monthly_gmv' => 500000,
                'initial_cheque_value' => 20000,
                'account_type' => 'business_plus',
                'is_documents_walkthrough_complete' => 0,
                'declaration_step' => 1,
                'sales_team' => 'sme',
                'created_at' => 1678187524,
                'sales_poc_phone_number' => '8882777606',
                'sales_poc_id' => 'admin_K6yvvIv3nxpcRQ',
                'ops_mx_poc_id' => 'admin_K6yvvIv3nxpcRR',
                'comment' => 'mx available at lcoation',
                'assignee_team' => 'ops',
                'rm_name' => 'Pankaj Mishra',
                'rm_phone_number' => '9315383526',
                'account_open_date' => 1678786950,
                'account_login_date' => 1678386600,
                'business_name' => 'Y-AXIS GROUP OF INDUSTRIES',
                'business_type' => 'default',
                'business_pan' => 'BESPA1234K',
                'merchant_state' => 'delhi',
                'contact_verified' => 0,
                'business_pan_validation' => null,
                'booking_date_and_time' => 1678873350,
                // 'application_type' => null, // unused
                'verification_date' => null,
                'bank_poc_user_id' => 'K6yvvIv3nxpcRp',

                'additional_details' => [

                    'calendly_slot_booking_completed' => 1,
                    'booking_id' => '12341',
                    'dwt_completed_timestamp' => 1678873350,
                    'dwt_scheduled_timestamp' => 1678873350,
                    'skip_mid_office_call' => true,
                    'appointment_source' => 'sales',
                    'sent_docket_automatically' => false,
                    'reasons_to_not_send_docket' => [
                        'PoE Not Verified',
                        'Entity Name Mismatch',
                        'Entity Type Mismatch',
                        'Unexpected State Change Log',
                        'Application with Duplicate Merchant Name',
                    ],
                    'docket_not_delivered_reason' => 'Wrong Setup Form',
                    'dwt_response' => 'What type is this even??',

                    'is_documents_walkthrough_complete' => 0,
                    'sales_pitch_completed' => 1,
                    'entity_mismatch_status' => 'entity_name_mismatch',
                    'green_channel' => true,
                    'cin' => 'CIN',
                    'gstin' => '07AYMPA5163E2ZL',
                    'llpin' => '',
                    'skip_dwt' => 1,
                    'feet_on_street' => true,
                    'api_onboarded_date' => null,
                    'mid_office_poc_name' => null,
                    'docket_delivered_date' => null,
                    'docket_estimated_delivery_date' => null,
                    'docket_requested_date' => '',
                    'courier_tracking_id' => '',
                    'courier_service_name' => '',
                    'gstin_prefilled_address' => 1,
                    'api_onboarding_login_date' => null,
                    'application_initiated_from' => 'X_DASHBOARD',
                    'account_opening_webhook_date' => 1678873350,
                    'agree_to_allocated_bank_and_amb' => 1,
                    'rbl_new_onboarding_flow_declarations' => [
                        'seal_available' => 1,
                        'signboard_available' => 1,
                        'signatories_available_at_preferred_address' => 1,
                        'available_at_preferred_address_to_collect_docs' => 1
                    ],
                    'business_details' => [
                        'model' => 'Fabric, Needlework, Piece Goods, and Sewing Stores',
                        'category' => 'ECOMMERCE',
                        'sub_category' => 'fabric_and_sewing_stores'
                    ],
                    'proof_of_entity' => ['source' => 'gstin', 'status' => 'verified'],
                    'proof_of_address' => ['source' => 'gstin', 'status' => 'verified'],

                    'verified_addresses' => [
                        [
                            'source' => 'gstin',
                            'address' => 'B-557, G/F PLOT NO-12 KH NO-24/19, MAIN 33FUTA ROAD RAJIV NAGAR MANDOLI EXTN NEAR BUDH BAZAR, DELHI, North East Delhi, Delhi, 110093',
                            'addressDetails' => [
                                'address_city' => null,
                                'address_state' => null,
                                'address_country' => null,
                                'address_email_id' => null,
                                'address_landmark' => null,
                                'address_locality' => null,
                                'address_pin_code' => '110093',
                                'address_street_name' => null,
                                'address_house_number' => null,
                                'address_building_name' => null,
                                'address_contact_number' => null
                            ]
                        ]
                    ],
                    'verified_constitutions' => [
                        ['constitution' => 'PUBLIC_LIMITED', 'source' => 'gstin']
                    ],
                    'entity_proof_documents' => [
                        [
                            'file_id' => 'file_LOckRD3Auj6ksw',
                            'document_type' => 'gst_certificate'
                        ]
                    ],
                    'ops_revived_lead' => true,
                ],
                'rbl_activation_details' => [
                    'revised_declaration' => false,
                    'office_different_locations' => false,
                    'lead_referred_by_rbl_staff' => true,
                    'bank_due_date' => 1678905000,
                    'lead_ir_number' => null,
                    'bank_poc_assigned_date' => 1678352209,
                    'ip_cheque_value' => null,
                    'api_docs_delay_reason' => '',
                    'api_docs_received_with_ca_docs' => true,
                    'sr_number' => null,
                    'account_opening_ir_number' => 'IR00022515189',
                    'case_login_different_locations' => false,
                    'api_ir_number' => null,
                    'upi_credential_not_done_remarks' => null,
                    'promo_code' => 'RZPAY',
                    'aof_shared_with_mo' => false,
                    'wa_message_sent_date' => null,
                    'first_calling_time' => '5 to 6',
                    'pcarm_manager_name' => 'Avijit Shrivastava ',
                    'wa_message_response_date' => null,
                    'aof_not_shared_reason' => 'Already Login',
                    'api_onboarding_tat_exception_reason' => null,
                    'account_opening_tat_exception_reason' => 'compliance Issue',
                    'ca_beyond_tat' => false,
                    'ca_beyond_tat_dependency' => '',
                    'lead_referred_by_rbl_staff' => false,
                    'api_onboarding_tat_exception' => null,
                    'account_opening_tat_exception' => true,
                    'aof_shared_discrepancy' => '',
                    'ca_service_first_query' => '1.on rrt high risk rating by compliance is not mentioned. APPLICANT FOUND IN NEGATIVE LIST ODG452595087230310202422178-ADIL',
                ],
                'branch_code' => '281',
                'customer_appointment_date' => 1678386600,
                'rm_employee_code' => '',
                'rm_assignment_type' => 'pcarm',
                'doc_collection_date' => 1678300200,
                'account_opening_ir_close_date' => null,
                'account_opening_ftnr' => 1,
                'account_opening_ftnr_reasons' => 'AO Negative List/Compliance/Legal/CIBIL',
                'api_ir_closed_date' => null,
                'ldap_id_mail_date' => null,
                'api_onboarding_ftnr' => null,
                'api_onboarding_ftnr_reasons' => null,
                'upi_credential_received_date' => null,
                'rzp_ca_activated_date' => null,
            ],
        ],
        'expectedBasInput' => [
            'banking_account' => [
                'ifsc' => 'SBIN01234',
                'account_number' => '12341678786950',
                // 'balance_id' => null, // not added as part of update
                'account_currency' => 'INR',
                'beneficiary_details' => [
                    'name' => 'Y-AXIS GROUP OF INDUSTRIES',
                    'pincode' => '110093',
                    'email' => 'SENDMAIL4ADIL@GMAIL.COM',
                    'mobile' => '+91(0)9560569604',
                    'city' => 'NEWDE',
                    'state' => 'DLI',
                    'country' => 'IN',
                    'address1' => 'G F PLOT NO 12 KH NO 24 19 B 557',
                    'address2' => 'MAIN 33 FUTA ROAD RAJIV NAGAR',
                    'address3' => 'MANDOLI EXTN NEAR BUDH BAZAR DELHI'
                ],
                'metadata' => [
                    'bank_account_open_date' => 1678786950
                ],
            ],
            'banking_account_application' => [
                'application_status' => 'doc_collection',
                'sub_status' => 'in_review',
                'bank_status' => 'closed',
                'application_number' => '203128886',
                'application_tracking_id' => '46436',
                'average_monthly_balance' => 20000,
                'expected_monthly_gmv' => 500000,
                'metadata' => [
                    'initial_cheque_value' => 20000,
                    'declaration_step' => 1,
                    'additional_details' => [
                        'calendly_slot_booking_completed' => 1,
                        'booking_id' => '12341',
                        'booking_date_and_time' => 1678873350,
                        'dwt_completed_timestamp' => 1678873350,
                        'dwt_scheduled_timestamp' => 1678873350,
                        // 'skip_mid_office_call' => true,
                        // 'appointment_source' => 'sales',
                        // 'sent_docket_automatically' => false,
                        // 'reasons_to_not_send_docket' => [
                        //     'PoE Not Verified',
                        //     'Entity Name Mismatch',
                        //     'Entity Type Mismatch',
                        //     'Unexpected State Change Log',
                        //     'Application with Duplicate Merchant Name',
                        // ],
                        'docket_not_delivered_reason' => 'Wrong Setup Form',
                        'dwt_response' => 'What type is this even??',

                        'is_documents_walkthrough_complete' => 0,
                        'sales_pitch_completed' => 1,
                        'entity_mismatch_status' => 'entity_name_mismatch',
                        'green_channel' => true,
                        'cin' => 'CIN',
                        'gstin' => '07AYMPA5163E2ZL',
                        'llpin' => '',
                        'skip_dwt' => 1,
                        'feet_on_street' => true,
                        'api_onboarded_date' => null,
                        'mid_office_poc_name' => null,
                        'docket_delivered_date' => null,
                        'docket_estimated_delivery_date' => null,
                        'docket_requested_date' => '',
                        'courier_tracking_id' => '',
                        'courier_service_name' => '',
                        'gstin_prefilled_address' => 1,
                        'api_onboarding_login_date' => null,
                        'application_initiated_from' => 'X_DASHBOARD',
                        'account_opening_webhook_date' => 1678873350,
                        'agree_to_allocated_bank_and_amb' => 1,
                        'rbl_new_onboarding_flow_declarations' => [
                            'seal_available' => 1,
                            'signboard_available' => 1,
                            'signatories_available_at_preferred_address' => 1,
                            'available_at_preferred_address_to_collect_docs' => 1
                        ],
                        'business_details' => [
                            'model' => 'Fabric, Needlework, Piece Goods, and Sewing Stores',
                            'category' => 'ECOMMERCE',
                            'sub_category' => 'fabric_and_sewing_stores'
                        ],
                        'proof_of_entity' => ['source' => 'gstin', 'status' => 'verified'],
                        'proof_of_address' => ['source' => 'gstin', 'status' => 'verified'],
                        'verified_addresses' => [
                            [
                                'source' => 'gstin',
                                'address' => 'B-557, G/F PLOT NO-12 KH NO-24/19, MAIN 33FUTA ROAD RAJIV NAGAR MANDOLI EXTN NEAR BUDH BAZAR, DELHI, North East Delhi, Delhi, 110093',
                                'addressDetails' => [
                                    'address_city' => null,
                                    'address_state' => null,
                                    'address_country' => null,
                                    'address_email_id' => null,
                                    'address_landmark' => null,
                                    'address_locality' => null,
                                    'address_pin_code' => '110093',
                                    'address_street_name' => null,
                                    'address_house_number' => null,
                                    'address_building_name' => null,
                                    'address_contact_number' => null
                                ]
                            ]
                        ],
                        'verified_constitutions' => [
                            ['constitution' => 'PUBLIC_LIMITED', 'source' => 'gstin']
                        ]
                    ],
                    'ops_revived_lead'  => true,
                    'verification_date' => null
                ],
                'bank_account_type' => 'business_plus',
                'sales_team' => 'SME',
                'assignee_team' => 'ops',
                'application_specific_fields' => [
                    'entity_proof_documents' => [
                        ['file_id' => 'file_LOckRD3Auj6ksw', 'document_type' => 'gst_certificate']
                    ]
                ]
            ],
            'business' => [
                'name' => 'Y-AXIS GROUP OF INDUSTRIES',
                'registered_address' => 'B-557, G/F PLOT NO-12 KH NO-24/19, MAIN 33FUTA ROAD RAJIV NAGAR MANDOLI EXTN NEAR BUDH BAZAR, DELHI, North East Delhi, Delhi, 110093',
                'constitution' => 'SOLE_PROPRIETORSHIP',
                'pan_number' => 'BESPA1234K',
                'industry_type' => 'default',
                'registered_address_details' => [
                    'address_pin_code' => '110093',
                    'address_city' => 'eastdelhi',
                    'address_region' => 'north',
                    'address_state' => 'delhi'
                ],
            ],
            'credentials' => [
                'auth_username' => 'ldap_id',
                'auth_password' => 'ldap_password',
                'corp_id' => 'corp_id',
                'client_id' => 'CLIENT_ID',
                'client_secret' => 'CLIENT_SECRET',
                'email' => 'MERCHANT_EMAIL',
                'dev_portal_password' => 'MERCHANT_PASSWORD'
            ],
            'person' => [
                'first_name' => 'MERCHANT_POC_NAME',
                'email_id' => 'yaxisgroupofindustries@gmail.com',
                'role_in_business' => 'Proprietor',
                'phone_number' => '+919560569604'
            ],
            'account_managers' => [
                'sales_poc' => ['phone_number' => '8882777606', 'rzp_admin_id' => 'K6yvvIv3nxpcRQ'],
                'ops_mx_poc' => ['rzp_admin_id' => 'K6yvvIv3nxpcRR'],
                'bank_poc' => ['rzp_admin_id' => 'K6yvvIv3nxpcRp']
            ],
            'partner_bank_application' => [
                'branch_code' => '281',
                'rm_details' => [
                    'rm_name' => 'Pankaj Mishra',
                    'rm_phone_number' => '9315383526',
                    'rm_employee_code' => '',
                    'rm_assignment_type' => 'pcarm',
                    'pcarm_manager_name' => 'Avijit Shrivastava '
                ],
                'lead_details' => [
                    'office_different_locations' => false,
                    'bank_due_date' => 1678905000,
                    'lead_ir_number' => null,
                    'bank_poc_assigned_date' => 1678352209,
                    'case_login_different_locations' => false
                ],
                'doc_collection_details' => [
                    'customer_appointment_date' => 1678386600,
                    'doc_collection_date' => 1678300200,
                    'ip_cheque_value' => null,
                    'api_docs_delay_reason' => '',
                    'api_docs_received_with_ca_docs' => true,
                    // 'customer_appointment_booking_date' => 1678683839 // Not added as input
                ],
                'account_opening_details' => [
                    'account_opening_ir_close_date' => null,
                    'account_open_date' => 1678786950,
                    'account_opening_ftnr' => 1,
                    'account_opening_ftnr_reasons' => 'AO Negative List/Compliance/Legal/CIBIL',
                    'sr_number' => null,
                    'account_opening_ir_number' => 'IR00022515189',
                    'account_opening_tat_exception' => true,
                    'account_opening_tat_exception_reason' => 'compliance Issue'
                ],
                'api_onboarding_details' => [
                    'api_ir_closed_date' => null,
                    'ldap_id_mail_date' => null,
                    'api_onboarding_ftnr' => null,
                    'api_onboarding_ftnr_reasons' => null,
                    'api_ir_number' => null,
                    'api_onboarding_tat_exception' => null,
                    'api_onboarding_tat_exception_reason' => null
                ],
                'account_activation_details' => [
                    'upi_credential_received_date' => null,
                    'rzp_ca_activated_date' => null,
                    'upi_credential_not_done_remarks' => null
                ],
                'auxiliary_details' => [
                    'revised_declaration' => false,
                    'promo_code' => 'RZPAY',
                    'lead_referred_by_rbl_staff' => true,
                    'aof_shared_with_mo' => false,
                    'wa_message_sent_date' => null,
                    'first_calling_time' => '5 to 6',
                    'wa_message_response_date' => null,
                    'aof_not_shared_reason' => 'Already Login',
                    'ca_beyond_tat' => false,
                    'ca_beyond_tat_dependency' => '',
                    'lead_referred_by_rbl_staff' => false,
                    'aof_shared_discrepancy' => '',
                    'ca_service_first_query' => '1.on rrt high risk rating by compliance is not mentioned. APPLICANT FOUND IN NEGATIVE LIST ODG452595087230310202422178-ADIL'
                ],
            ]
        ],
    ],

    'testBasResponseToApiResponseAdapter' => [
        'basResponse' => [
            'business' => [
                'id' => 'LVFoXUXt8aLGQt',
                'created_at' => 1679637455661,
                'updated_at' => 1682054894757,
                'AssociatedPeople' => null,
                'name' => 'Y-AXIS GROUP OF INDUSTRIES',
                'merchant_id' => '10000000000000',
                'email_id' => 'accountlinking00@test.com',
                'mobile_number' => '7652344566',
                'date_of_incorporation' => '',
                'country_of_incorporation' => '',
                'pan_number' => 'BESPA1234K',
                'form_60_number' => '',
                'gstin' => '',
                'constitution' => 'ONE_PERSON_COMPANY',
                'nature_of_business' => '',
                'industry_type' => 'WELL',
                'category' => '',
                'sector' => '',
                'sub_sector' => '',
                'source_of_funding' => '',
                'bsr' => '',
                'average_annual_turnover' => '',
                'preferred_mailing_address' => null,
                'preferred_mailing_address_details' => [
                    'address_house_number' => null,
                    'address_building_name' => null,
                    'address_street_name' => null,
                    'address_locality' => null,
                    'address_landmark' => null,
                    'address_city' => null,
                    'address_state' => null,
                    'address_country' => null,
                    'address_pin_code' => null,
                    'address_contact_number' => null,
                    'address_email_id' => null,
                    'address_region' => null
                ],
                'registered_address' => 'eastdelhi, delhi, 110092',
                'registered_address_details' => [
                    'address_house_number' => null,
                    'address_building_name' => null,
                    'address_street_name' => null,
                    'address_locality' => null,
                    'address_landmark' => null,
                    'address_city' => 'eastdelhi',
                    'address_state' => 'delhi',
                    'address_country' => null,
                    'address_pin_code' => '110093',
                    'address_contact_number' => null,
                    'address_email_id' => null,
                    'address_region' => 'north'
                ],
                'nominee' => [
                    'name' => '',
                    'address' => '',
                    'relationship' => '',
                    'age' => 0
                ],
                'minor_nominee' => [
                    'name' => '',
                    'address' => '',
                    'relationship' => '',
                    'age' => 0
                ],
                'region' => null,
                'associated_people' => null,
                'associated_documents' => null,
                'application_id' => ''
            ],
            'person' => [
                'id' => 'LVFoXUXt8aLGQt',
                'created_at' => 0,
                'updated_at' => 1682054894763,
                'associated_business_id' => 'LVFoXUXt8aLGQt',
                'AssociatedDocuments' => null,
                'title' => '',
                'first_name' => 'aditya',
                'middle_name' => '',
                'last_name' => '',
                'email_id' => 'yaxisgroupofindustries@gmail.com',
                'phone_number' => '+919560569604',
                'religion' => '',
                'religion_category' => '',
                'father_name' => '',
                'spouse_name' => '',
                'mother_name' => '',
                'maiden_name' => '',
                'date_of_birth' => '',
                'marital_status' => '',
                'gender' => '',
                'nationality' => '',
                'resident_of_india' => false,
                'fatca_crs' => [
                    'tax_identification_number' => '',
                    'country_of_jurisdiction_of_residence' => '',
                    'city_of_birth' => '',
                    'country_of_birth' => ''
                ],
                'permanent_residential_address' => '',
                'permanent_residential_address_details' => [
                    'address_house_number' => null,
                    'address_building_name' => null,
                    'address_street_name' => null,
                    'address_locality' => null,
                    'address_landmark' => null,
                    'address_city' => null,
                    'address_state' => null,
                    'address_country' => null,
                    'address_pin_code' => null,
                    'address_contact_number' => null,
                    'address_email_id' => null
                ],
                'current_residential_address' => '',
                'current_residential_address_details' => [
                    'address_house_number' => null,
                    'address_building_name' => null,
                    'address_street_name' => null,
                    'address_locality' => null,
                    'address_landmark' => null,
                    'address_city' => null,
                    'address_state' => null,
                    'address_country' => null,
                    'address_pin_code' => null,
                    'address_contact_number' => null,
                    'address_email_id' => null
                ],
                'preferred_mailing_address' => '',
                'preferred_mailing_address_details' => [
                    'address_house_number' => null,
                    'address_building_name' => null,
                    'address_street_name' => null,
                    'address_locality' => null,
                    'address_landmark' => null,
                    'address_city' => null,
                    'address_state' => null,
                    'address_country' => null,
                    'address_pin_code' => null,
                    'address_contact_number' => null,
                    'address_email_id' => null
                ],
                'address_outside_india' => '',
                'address_outside_india_details' => [
                    'address_house_number' => null,
                    'address_building_name' => null,
                    'address_street_name' => null,
                    'address_locality' => null,
                    'address_landmark' => null,
                    'address_city' => null,
                    'address_state' => null,
                    'address_country' => null,
                    'address_pin_code' => null,
                    'address_contact_number' => null,
                    'address_email_id' => null
                ],
                'education_qualification' => '',
                'employment_type' => '',
                'employed_with' => '',
                'occupation' => '',
                'source_of_income' => '',
                'gross_annual_income' => '',
                'type_of_company' => '',
                'industry_type' => '',
                'role_in_business' => 'Proprietor',
                'contact_verified' => false
            ],
            'banking_account' => [
                'id' => 'Ji8Osy16V60siZ',
                'created_at' => 1655375595507,
                'updated_at' => 1682054894768,
                'beneficiary_name' => '',
                'beneficiary_email' => '',
                'beneficiary_mobile' => '',
                'associated_account_managers' => null,
                'business_id' => 'LVFoXUXt8aLGQt',
                'account_number' => '401509080395',
                'account_type' => '',
                'partner_bank' => '',
                'balance_id' => '',
                'fts_fund_account_id' => '',
                'account_currency' => '',
                'ifsc' => 'RATN0000281',
                'urn' => '',
                'alias_id' => '',
                'status' => 'IN_PROGRESS',
                'preference' => null,
                'beneficiary_details' => [
                    'name' => 'Z-AXIS GROUP OF INDUSTRIES',
                    'email' => 'SENDMAIL4ADIL@GMAIL.COM',
                    'mobile' => '+91(0)9560569604',
                    'city' => 'NEWDE',
                    'state' => 'DLI',
                    'country' => 'IN',
                    'address1' => 'G F PLOT NO 12 KH NO 24 19 B 557',
                    'address2' => 'MAIN 33 FUTA ROAD RAJIV NAGAR',
                    'address3' => 'MANDOLI EXTN NEAR BUDH BAZAR DELHI'
                ],
                'metadata' => [
                    'bank_account_open_date' => 1678873351,
                    'stp_fcrm_date' => '',
                    'stp_sr_number' => '',
                    'stp_sr_status' => '',
                    'stp_closed_date' => '',
                    'stp_remarks' => '123',
                    'stp_connected_banking' => '',
                    'stp_t3_date' => '',
                    'stp_helpdesk_sr' => '',
                    'stp_helpdesk_sr_status' => '',
                    'stp_rzp_intervention' => ''
                ]
            ],
            'banking_account_application' => [
                'id' => 'JuLWj2OnFAcg72',
                'created_at' => 1658041903068,
                'updated_at' => 1682054894775,
                'business_id' => 'LVFoXUXt8aLGQt',
                'banking_account_id' => 'Ji8Osy16V60siZ',
                'application_number' => '203128886',
                'application_status' => 'created',
                'sub_status' => 'none',
                'bank_status' => '',
                'bank_sub_status' => '',
                'workflow_version_number' => '',
                'combined_application_status' => '',
                'application_type' => 'RBL_ONBOARDING_APPLICATION',
                'person_details' => [
                    'first_name' => '',
                    'email_id' => '',
                    'phone_number' => '',
                    'role_in_business' => ''
                ],
                'pincode' => '',
                'application_specific_fields' => [
                    'EntityProofDocuments' => [
                        [
                            'document_type' => 'gst_certificate',
                            'file_id' => 'file_LOckRD3Auj6ksw'
                        ]
                    ]
                ],
                'sales_team' => 'SME',
                'metadata' => [
                    'additional_details' => [
                        'sales_pitch_completed' => 1,
                        'calendly_slot_booking_completed' => 1,
                        'entity_mismatch_status' => 'entity_name_mismatch',
                        'green_channel' => true,
                        'is_documents_walkthrough_complete' => 0,
                        'booking_id' => '12341',
                        'booking_date_and_time' => 1678873350,
                        'cin' => 'CIN',
                        'gstin' => '07AYMPA5163E2ZL',
                        'llpin' => '',
                        'skip_dwt' => 1,
                        'dwt_completed_timestamp' => '1678873350',
                        'dwt_scheduled_timestamp' => '1678873350',
                        'mid_office_poc_name' => null,
                        'docket_delivered_date' => null,
                        'docket_estimated_delivery_date' => null,
                        'docket_requested_date' => '',
                        'courier_tracking_id' => '',
                        'courier_service_name' => '',
                        'gstin_prefilled_address' => 1,
                        'api_onboarded_date' => null,
                        'api_onboarding_login_date' => null,
                        'application_initiated_from' => 'X_DASHBOARD',
                        'account_opening_webhook_date' => 1678873350,
                        'agree_to_allocated_bank_and_amb' => 1,
                        'feet_on_street' => true,
                        'skip_mid_office_call' => true,
                        'appointment_source' => 'sales',
                        'sent_docket_automatically' => false,
                        'reasons_to_not_send_docket' => [
                            'PoE Not Verified',
                            'Entity Name Mismatch',
                            'Entity Type Mismatch',
                            'Unexpected State Change Log',
                            'Application with Duplicate Merchant Name'
                        ],
                        'docket_not_delivered_reason' => 'Wrong Setup Form',
                        'dwt_response' => [
                            'cc_od' => 0,
                            'stamp_available' => 1,
                            'agree_to_20k_ICV' => 1,
                            'proof_of_entity_available' => 1,
                            'document_for_poa_available' => 'COI',
                            'proof_of_address_available' => 1
                        ],
                        'business_details' => [
                            'model' => 'Fabric, Needlework, Piece Goods, and Sewing Stores',
                            'category' => 'ECOMMERCE',
                            'sub_category' => 'fabric_and_sewing_stores'
                        ],
                        'proof_of_entity' => [
                            'source' => 'gstin',
                            'status' => 'verified'
                        ],
                        'proof_of_address' => [
                            'source' => 'gstin',
                            'status' => 'verified'
                        ],
                        'verified_addresses' => [
                            [
                                'source' => 'gstin',
                                'address' => 'B-557, G/F PLOT NO-12 KH NO-24/19, MAIN 33FUTA ROAD RAJIV NAGAR MANDOLI EXTN NEAR BUDH BAZAR, DELHI, North East Delhi, Delhi, 110093',
                                'addressDetails' => [
                                    'address_house_number' => null,
                                    'address_building_name' => null,
                                    'address_street_name' => null,
                                    'address_locality' => null,
                                    'address_landmark' => null,
                                    'address_city' => null,
                                    'address_state' => null,
                                    'address_country' => null,
                                    'address_pin_code' => '110093',
                                    'address_contact_number' => null,
                                    'address_email_id' => null
                                ]
                            ]
                        ],
                        'verified_constitutions' => [
                            [
                                'source' => 'gstin',
                                'constitution' => 'PUBLIC_LIMITED'
                            ]
                        ],
                        'rbl_new_onboarding_flow_declarations' => [
                            'available_at_preferred_address_to_collect_docs' => 1,
                            'seal_available' => 1,
                            'signatories_available_at_preferred_address' => 1,
                            'signboard_available' => 1
                        ]
                    ],
                    'drop_off_reason' => '',
                    'ca_channel' => '',
                    'campaign_id' => '',
                    'lead_sent_to_bank_date' => '',
                    'date_on_which_1st_appointment_was_fixed' => '',
                    'docs_collected_date' => '',
                    'case_initiation_date' => '',
                    'account_opened_date' => '',
                    'multi_location' => '',
                    'contacted_by_sales' => false,
                    'follow_up_date' => '',
                    'is_stp_doc_collected' => '',
                    'is_account_number_change' => '',
                    'ops_follow_up_date' => '',
                    'fresh_desk_ticket_created' => false,
                    'comment' => 'Some comment',
                    'initial_cheque_value' => 20000,
                    'verification_date' => '',
                    'is_allowed_on_partner_lms' => true,
                    'account_open_date' => 1678786950,
                    'account_login_date' => 0,
                    'declaration_step' => 1,
                    'ops_revived_lead'  => true,
                ],
                'registration_status' => '',
                'average_monthly_balance' => 20000,
                'expected_monthly_gmv' => 500000,
                'bank_account_type' => 'business_plus',
                'assignee_team' => 'ops',
                // 'sales_poc_name' => '',
                // 'sales_poc_email' => '',
                // 'sales_poc_id' => '',
                // 'sales_poc_phone_number' => '',
                // 'spocs' => null,
                // 'reviewers' => null,
                // 'comment' => ''
            ],
            'partner_bank_application' => [
                'id' => 'JuLWj2OnFAcg73',
                'banking_account_application_id' => '',
                'branch_code' => '213',
                'lead_details' => [
                    'lead_ir_number' => 'IR 01234',
                    'assigned_rm_date' => 0,
                    'case_login_different_locations' => false,
                    'office_different_locations' => true,
                    'bank_poc_assigned_date' => 1678352209,
                    'bank_due_date' => 1678905000,
                    'revived_lead' => false
                ],
                'rm_details' => [
                    'rm_name' => 'Pankaj Mishra',
                    'rm_phone_number' => '9315383526',
                    'rm_employee_code' => '12345',
                    'rm_assignment_type' => 'pcarm',
                    'pcarm_manager_name' => 'Avijit Shrivastava'
                ],
                'doc_collection_details' => [
                    'ip_cheque_value' => 20000,
                    'doc_collection_date' => 1678300200,
                    'api_docs_delay_reason' => 'That\'s how we roll.',
                    'customer_appointment_date' => 1678386600,
                    'customer_appointment_booking_date' => 1678683839,
                    'api_docs_received_with_ca_docs' => true
                ],
                'account_opening_details' => [
                    'sr_number' => 'SR_NUMBER',
                    'account_open_date' => 1678786950,
                    'account_opening_ftnr' => true,
                    'account_opening_ftnr_reasons' => 'AO Negative List/Compliance/Legal/CIBIL',
                    'account_opening_ir_number' => 'IR00022515189',
                    'account_opening_ir_close_date' => 1678352209,
                    'account_opening_tat_exception' => false,
                    'account_opening_tat_exception_reason' => 'compliance Issue'
                ],
                'api_onboarding_details' => [
                    'api_ir_number' => 'API_IR_1234',
                    'ldap_id_mail_date' => 1678352209,
                    'api_ir_closed_date' => 1678352209,
                    'api_onboarding_ftnr' => true,
                    'api_onboarding_ftnr_reasons' => 'Reason 1, Reason 2, ',
                    'api_onboarding_tat_exception' => false,
                    'api_onboarding_tat_exception_reason' => 'This time for Africa'
                ],
                'account_activation_details' => [
                    'drop_off_date' => 0,
                    'rzp_ca_activated_date' => 1678352209,
                    'upi_credential_received_date' => 1678352209,
                    'upi_credential_not_done_remarks' => 'Something'
                ],
                'auxiliary_details' => [
                    'promo_code' => 'RZPAY',
                    'revised_declaration' => false,
                    'lead_referred_by_rbl_staff' => true,
                    'aof_shared_with_mo' => false,
                    'aof_not_shared_reason' => 'Already Login',
                    'aof_shared_discrepancy' => '',
                    'wa_message_sent_date' => 1678352209,
                    'wa_message_response_date' => 1678352209,
                    'first_calling_time' => '5 to 6',
                    'ca_beyond_tat' => false,
                    'ca_beyond_tat_dependency' => '',
                    'ca_service_first_query' => '1.on rrt high risk rating by compliance is not mentioned. APPLICANT FOUND IN NEGATIVE LIST ODG452595087230310202422178-ADIL'
                ],
                'created_at' => 0,
                'updated_at' => 1682054894780
            ],
            'account_managers' => [
                'sales_poc' => [
                    'id' => 'LXdkSkoN4qea1i',
                    'name' => 'Prathush Nair',
                    'email' => 'prathush.nair@razorpay.com',
                    'created_at' => 1680158423081,
                    'updated_at' => 1682054894784,
                    'rzp_admin_id' => 'Hj0NhxCidSM6Vl',
                    'team' => 'RAZORPAY_SALES',
                    'phone_number' => '8989898989',
                    'booking_count' => 0
                ],
                'ops_poc' => [
                    'id' => 'EKtsv1zkV26gmc',
                    'created_at' => 1680158423081,
                    'updated_at' => 1682054894784,
                    'rzp_admin_id' => 'EKtsv1zkV26gmc',
                    'team' => '',
                    'email' => 'bennet.varghese@razorpay.com',
                    'name' => 'Bennet Varghese',
                    'phone_number' => '',
                    'booking_count' => 0
                ],
                'bank_poc' => [
                    'id' => 'EKtsv1zkV269mc',
                    'created_at' => 1680158423081,
                    'updated_at' => 1682054894784,
                    'team' => '',
                    'rzp_admin_id' => 'EKtsv1zkV269mc',
                    'name' => 'RBL Bank POC',
                    'email' => 'bank_poc@rbl.com',
                    'phone_number' => '',
                    'booking_count' => 0
                ],
                'ops_mx_poc' => [
                    'id' => 'Iqi43Gendn3nF9',
                    'created_at' => 1680158423081,
                    'updated_at' => 1682054894784,
                    'rzp_admin_id' => 'Iqi43Gendn3nF9',
                    'team' => 'RAZORPAY_OPS_MX',
                    'email' => 'abhishek.sriram@cnx.razorpay.com',
                    'name' => 'abhishek sriram',
                    'phone_number' => '',
                    'booking_count' => 0
                ],
            ],
            'credentials' => [
                'bank_reference_number' => '11111111',
                'auth_username' => 'ldap_id',
                'auth_password' => 'LDAP_PASSWORD_TOKENIZED',
                'corp_id' => 'corp_id',
                'client_id' => 'client_id',
                'client_secret' => 'CLIENT_SECRET_TOKENIZED',
                'email' => 'email',
                'dev_portal_password' => 'DEV_PORTAL_PASSWORD_TOKENIZED',
            ]
        ],
        'expectedApiResponse' => [
            'id' => 'bacc_JuLWj2OnFAcg72',
            'merchant_id' => '10000000000000',
            'fts_fund_account_id' => '',
            'created_at' => 1658041903,
            'updated_at' => 1682054894,
            'pincode' => '110093',
            'account_currency' => '',
            'status' => 'created',
            'sub_status' => 'none',
            'account_ifsc' => 'RATN0000281',
            'account_number' => '401509080395',
            'bank_internal_status' => '',
            'bank_internal_reference_number' => '203128886',
            'beneficiary_name' => 'Z-AXIS GROUP OF INDUSTRIES',
            'beneficiary_email' => 'SENDMAIL4ADIL@GMAIL.COM',
            'beneficiary_mobile' => '+91(0)9560569604',
            'beneficiary_city' => 'NEWDE',
            'beneficiary_state' => 'DLI',
            'beneficiary_country' => 'IN',
            'beneficiary_address1' => 'G F PLOT NO 12 KH NO 24 19 B 557',
            'beneficiary_address2' => 'MAIN 33 FUTA ROAD RAJIV NAGAR',
            'beneficiary_address3' => 'MANDOLI EXTN NEAR BUDH BAZAR DELHI',
            'account_activation_date' => 1678873351,
            'balance_id' => '',
            'username' => 'ldap_id',
            'password' => 'LDAP_PASSWORD_TOKENIZED',

            'banking_account_activation_details' => [
                'id' => 'bacc_JuLWj2OnFAcg72',
                'banking_account_id' => 'bacc_JuLWj2OnFAcg72',
                'created_at' => 1658041903,
                'updated_at' => 1682054894,
                'merchant_city' => 'eastdelhi',
                'merchant_region' => 'north',
                'business_category' => 'one_person_company',
                'is_documents_walkthrough_complete' => 0,
                'sales_team' => 'sme',
                'assignee_team' => 'ops',
                'business_type' => 'WELL',
                'merchant_state' => 'delhi',
                'merchant_poc_email' => 'yaxisgroupofindustries@gmail.com',
                'merchant_poc_phone_number' => '+919560569604',
                'merchant_documents_address' => 'eastdelhi, delhi, 110092',
                'business_name' => 'Y-AXIS GROUP OF INDUSTRIES',
                'merchant_poc_name' => 'aditya',
                'merchant_poc_designation' => 'Proprietor',
                'average_monthly_balance' => 20000,
                'expected_monthly_gmv' => 500000,
                'initial_cheque_value' => 20000,
                'account_type' => 'business_plus',
                'sales_poc_phone_number' => '8989898989',
                'comment' => 'Some comment',
                'rm_assignment_type' => 'pcarm',
                'rm_employee_code' => '12345',
                'rm_name' => 'Pankaj Mishra',
                'rm_phone_number' => '9315383526',
                'branch_code' => '213',
                'account_login_date' => 0,
                'account_open_date' => 1678786950,
                'account_opening_ftnr_reasons' => 'AO Negative List/Compliance/Legal/CIBIL',
                'account_opening_ftnr' => true,
                'api_onboarding_ftnr_reasons' => 'Reason 1, Reason 2, ',
                'api_onboarding_ftnr' => true,
                'ldap_id_mail_date' => 1678352209,
                'drop_off_date' => 0,
                'rzp_ca_activated_date' => 1678352209,
                'api_ir_closed_date' => 1678352209,
                'bank_poc_user_id' => 'EKtsv1zkV269mc',
                'bank_poc_name' => 'RBL Bank POC',
                'additional_details' => [
                    'cin' => 'CIN',
                    'llpin' => '',
                    'green_channel' => true,
                    'gstin_prefilled_address' => 1,
                    'application_initiated_from' => 'X_DASHBOARD',
                    'gstin' => '07AYMPA5163E2ZL',
                    'skip_dwt' => 1,
                    'proof_of_entity' => [ 'source' => 'gstin', 'status' => 'verified' ],
                    'proof_of_address' => [ 'source' => 'gstin', 'status' => 'verified' ],
                    'appointment_source' => 'sales',
                    'verified_addresses' => [
                        [
                            'source' => 'gstin',
                            'address' => 'B-557, G/F PLOT NO-12 KH NO-24/19, MAIN 33FUTA ROAD RAJIV NAGAR MANDOLI EXTN NEAR BUDH BAZAR, DELHI, North East Delhi, Delhi, 110093',
                            'addressDetails' => [
                            'address_house_number' => null,
                            'address_building_name' => null,
                            'address_street_name' => null,
                            'address_locality' => null,
                            'address_landmark' => null,
                            'address_city' => null,
                            'address_state' => null,
                            'address_country' => null,
                            'address_pin_code' => '110093',
                            'address_contact_number' => null,
                            'address_email_id' => null
                            ]
                        ]
                    ],
                    'skip_mid_office_call' => true,
                    'verified_constitutions' => [
                        [ 'source' => 'gstin', 'constitution' => 'PUBLIC_LIMITED' ]
                    ],
                    'agree_to_allocated_bank_and_amb' => 1,
                    'rbl_new_onboarding_flow_declarations' => [
                        'available_at_preferred_address_to_collect_docs' => 1,
                        'seal_available' => 1,
                        'signatories_available_at_preferred_address' => 1,
                        'signboard_available' => 1
                    ],
                    'entity_mismatch_status' => 'entity_name_mismatch',
                    'business_details' => [
                        'model' => 'Fabric, Needlework, Piece Goods, and Sewing Stores',
                        'category' => 'ECOMMERCE',
                        'sub_category' => 'fabric_and_sewing_stores'
                    ],
                    'sales_pitch_completed' => 1,
                    'sent_docket_automatically' => false,
                    'reasons_to_not_send_docket' => [
                        'PoE Not Verified',
                        'Entity Name Mismatch',
                        'Entity Type Mismatch',
                        'Unexpected State Change Log',
                        'Application with Duplicate Merchant Name'
                    ],
                    'feet_on_street' => true,
                    'dwt_response' => [
                        'cc_od' => 0,
                        'stamp_available' => 1,
                        'agree_to_20k_ICV' => 1,
                        'proof_of_entity_available' => 1,
                        'document_for_poa_available' => 'COI',
                        'proof_of_address_available' => 1
                    ],
                    'dwt_completed_timestamp' => '1678873350',
                    'dwt_scheduled_timestamp' => '1678873350',
                    'docket_requested_date' => '',
                    'courier_service_name' => '',
                    'courier_tracking_id' => '',
                    'docket_estimated_delivery_date' => null,
                    'docket_delivered_date' => null,
                    'ops_follow_up_date' => '',
                    'docket_not_delivered_reason' => 'Wrong Setup Form',
                    'api_onboarding_login_date' => null,
                    'account_opening_webhook_date' => 1678873350,
                    'mid_office_poc_name' => null,
                    'api_onboarded_date' => null,
                    'ops_revived_lead'  => true,
                ],
                'rbl_activation_details' => [
                    'pcarm_manager_name' => 'Avijit Shrivastava',
                    'bank_due_date' => 1678905000,
                    'bank_poc_assigned_date' => 1678352209,
                    'lead_ir_number' => 'IR 01234',
                    'account_opening_ir_number' => 'IR00022515189',
                    'case_login_different_locations' => false,
                    'account_opening_tat_exception_reason' => 'compliance Issue',
                    'api_onboarding_tat_exception_reason' => 'This time for Africa',
                    'api_ir_number' => 'API_IR_1234',
                    'sr_number' => 'SR_NUMBER',
                    'upi_credential_not_done_remarks' => 'Something',
                    'aof_shared_with_mo' => false,
                    'aof_not_shared_reason' => 'Already Login',
                    'aof_shared_discrepancy' => '',
                    'wa_message_sent_date' => 1678352209,
                    'wa_message_response_date' => 1678352209,
                    'first_calling_time' => '5 to 6',
                    'ca_beyond_tat' => false,
                    'ca_beyond_tat_dependency' => '',
                    'ca_service_first_query' => '1.on rrt high risk rating by compliance is not mentioned. APPLICANT FOUND IN NEGATIVE LIST ODG452595087230310202422178-ADIL'
                ]
            ],

            'reviewers' => [
                'entity' => 'collection',
                'count' => 1,
                'items' => [
                    [
                        'id' => 'admin_EKtsv1zkV26gmc',
                        'email' => 'bennet.varghese@razorpay.com',
                        'name' => 'Bennet Varghese',
                    ]
                ]
            ],
            'spocs' => [
                'entity' => 'collection',
                'count' => 1,
                'items' => [
                    [
                        'id' => 'admin_Hj0NhxCidSM6Vl',
                        'name' => 'Prathush Nair',
                        'email' => 'prathush.nair@razorpay.com',
                    ]
                ]
            ],
            'ops_mx_pocs' => [
                'entity' => 'collection',
                'count' => 1,
                'items' => [
                    [
                        'id' => 'admin_Iqi43Gendn3nF9',
                        'email' => 'abhishek.sriram@cnx.razorpay.com',
                        'name' => 'abhishek sriram',
                    ]
                ]
            ],

            'banking_account_details' => [
                'entity' => 'collection',
                'count' => 5,
                'items' => [
                    [
                        BankingAccount\Detail\Entity::BANKING_ACCOUNT_ID => 'JuLWj2OnFAcg72',
                        BankingAccount\Detail\Entity::MERCHANT_ID => '10000000000000',
                        BankingAccount\Detail\Entity::GATEWAY_KEY => BasConstants::CORP_ID_CRED,
                        BankingAccount\Detail\Entity::GATEWAY_VALUE => 'corp_id',
                        BankingAccount\Detail\Entity::ID => '',
                        BankingAccount\Detail\Entity::ENTITY => 'banking_account_detail',
                    ],
                    [
                        BankingAccount\Detail\Entity::BANKING_ACCOUNT_ID => 'JuLWj2OnFAcg72',
                        BankingAccount\Detail\Entity::MERCHANT_ID => '10000000000000',
                        BankingAccount\Detail\Entity::GATEWAY_KEY => BasConstants::CLIENT_ID,
                        BankingAccount\Detail\Entity::GATEWAY_VALUE => 'client_id',
                        BankingAccount\Detail\Entity::ID => '',
                        BankingAccount\Detail\Entity::ENTITY => 'banking_account_detail',
                    ],
                    [
                        BankingAccount\Detail\Entity::BANKING_ACCOUNT_ID => 'JuLWj2OnFAcg72',
                        BankingAccount\Detail\Entity::MERCHANT_ID => '10000000000000',
                        BankingAccount\Detail\Entity::GATEWAY_KEY => BasConstants::CLIENT_SECRET,
                        BankingAccount\Detail\Entity::GATEWAY_VALUE => 'CLIENT_SECRET_TOKENIZED',
                        BankingAccount\Detail\Entity::ID => '',
                        BankingAccount\Detail\Entity::ENTITY => 'banking_account_detail',
                    ],
                    [
                        BankingAccount\Detail\Entity::BANKING_ACCOUNT_ID => 'JuLWj2OnFAcg72',
                        BankingAccount\Detail\Entity::MERCHANT_ID => '10000000000000',
                        BankingAccount\Detail\Entity::GATEWAY_KEY => BasConstants::EMAIL,
                        BankingAccount\Detail\Entity::GATEWAY_VALUE => 'email',
                        BankingAccount\Detail\Entity::ID => '',
                        BankingAccount\Detail\Entity::ENTITY => 'banking_account_detail',
                    ],
                    [
                        BankingAccount\Detail\Entity::BANKING_ACCOUNT_ID => 'JuLWj2OnFAcg72',
                        BankingAccount\Detail\Entity::MERCHANT_ID => '10000000000000',
                        BankingAccount\Detail\Entity::GATEWAY_KEY => BasConstants::DEV_PORTAL_PASSWORD,
                        BankingAccount\Detail\Entity::GATEWAY_VALUE => 'DEV_PORTAL_PASSWORD_TOKENIZED',
                        BankingAccount\Detail\Entity::ID => '',
                        BankingAccount\Detail\Entity::ENTITY => 'banking_account_detail',
                    ],
                ]
            ]
        ]
    ]
];
