<?php
use RZP\Error\ErrorCode;
use RZP\Error\PublicErrorCode;
use RZP\Error\PublicErrorDescription;

return [
    'testPayment' => [
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'method' => 'netbanking',
        'status' => 'captured',
        'amount_authorized' => 50000,
        'amount_refunded' => 0,
        'refund_status' => null,
        'currency' => 'INR',
        'description' => 'random description',
        'bank' => 'ICIC',
        'error_code' => null,
        'error_description' => null,
        'email' => 'a@b.com',
        'contact' => '+919918899029',
        'notes' => [
            'merchant_order_id' => 'random order id',
        ],
        'gateway' => 'ebs',
        'terminal_id' => '100000EbsTrmnl',
        'signed' => false,
        'verified' => null,
        'fee' => 1438,
        'service_tax' => 188,
        'entity' => 'payment',
    ],

    'testTransactionAfterAuthorize' => [
        'type' => 'payment',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 1438,
        'service_tax' => 188,
        'pricing_rule_id' => '1zD0BXpeOyaqpB',
        'debit' => 0,
        'credit' => 48562,
        'currency' => 'INR',
        'balance' => 0,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'escrow_balance' => 1048562,
        'channel' => 'kotak',
        'settled' => false,
        'settled_at' => null,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testTransactionAfterCapture' => [
        'type' => 'payment',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 1438,
        'debit' => 0,
        'credit' => 48562,
        'currency' => 'INR',
        'balance' => 1048562,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'escrow_balance' => 1048562,
        'channel' => 'kotak',
        'settled' => false,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testPaymentEbsEntity' => [
        'action' => 'authorize',
        'received' => true,
        'currency'=> 'INR',
        "TxnAmount" => "50000",
        'refund_id'=> null,
        'entity'=> 'ebs',
        'refund_status' => null,
        'refund_id' => null,
        'ErrorCode' => null,
        'mode' => 'TEST',

    ],
];
