<?php

namespace RZP\Error;

class ErrorCode
{
    /**
     * The error codes are named such that the first and the second word
     * tells the error category.
     */

    /**
     * All internal un-explained and sudden errors are encapsulated
     * by the following error code.
     */
    const SERVER_ERROR                                                              = 'SERVER_ERROR';

    /**
     * General gateway specific error codes
     * Isn't specific to one particular gateway and
     * should be generally valid for gateways that
     * are added in future
     */
    const GATEWAY_ERROR_FATAL_ERROR                                                 = 'GATEWAY_ERROR_FATAL_ERROR';
    const GATEWAY_ERROR_REQUEST_ERROR                                               = 'GATEWAY_ERROR_REQUEST_ERROR';

    const GATEWAY_ERROR_REQUEST_TIMEOUT                                             = 'GATEWAY_ERROR_REQUEST_TIMEOUT';
    const GATEWAY_ERROR_DENIED_BY_RISK                                              = 'GATEWAY_ERROR_DENIED_BY_RISK';
    const GATEWAY_ERROR_PROCESSING_DECLINED                                         = 'GATEWAY_ERROR_PROCESSING_DECLINED';
    const GATEWAY_ERROR_AUTHENTICATION_NOT_AVAILABLE                                = 'GATEWAY_ERROR_AUTHENTICATION_NOT_AVAILABLE';
    const GATEWAY_ERROR_INVALID_TERMINAL_ID                                         = 'GATEWAY_ERROR_INVALID_TERMINAL_ID';
    const GATEWAY_ERROR_INVALID_TERMINAL_SECRET                                     = 'GATEWAY_ERROR_INVALID_TERMINAL_SECRET';
    const GATEWAY_ERROR_CERTIFICATE_VALIDATION_FAILED                               = 'GATEWAY_ERROR_CERTIFICATE_VALIDATION_FAILED';
    const GATEWAY_ERROR_SIGNATURE_VALIDATION_FAILED                                 = 'GATEWAY_ERROR_SIGNATURE_VALIDATION_FAILED';
    const GATEWAY_ERROR_INVALID_SUBSEQUENT_PAYMENT                                  = 'GATEWAY_ERROR_INVALID_SUBSEQUENT_PAYMENT';
    const GATEWAY_ERROR_SUPPORT_FAILED                                              = 'GATEWAY_ERROR_SUPPORT_FAILED';
    const GATEWAY_ERROR_SUPPORT_AUTH_NOT_FOUND                                      = 'GATEWAY_ERROR_SUPPORT_AUTH_NOT_FOUND';
    const GATEWAY_ERROR_CAPTURE_GREATER_THAN_AUTH                                   = 'GATEWAY_ERROR_CAPTURE_GREATER_THAN_AUTH';
    const GATEWAY_ERROR_PAYMENT_CAPTURE_FAILED                                      = 'GATEWAY_ERROR_PAYMENT_CAPTURE_FAILED';
    const GATEWAY_ERROR_PARES_NOT_SUCCESSFUL                                        = 'GATEWAY_ERROR_PARES_NOT_SUCCESSFUL';
    const GATEWAY_ERROR_NOT_UNDERSTOOD_ERROR                                        = 'GATEWAY_ERROR_NOT_UNDERSTOOD_ERROR';
    const GATEWAY_ERROR_CHECKSUM_MATCH_FAILED                                       = 'GATEWAY_ERROR_CHECKSUM_MATCH_FAILED';
    const GATEWAY_ERROR_TRANSACTION_TYPE_NOT_SUPPORTED                              = 'GATEWAY_ERROR_TRANSACTION_TYPE_NOT_SUPPORTED';
    const GATEWAY_ERROR_PAYMENT_VERIFICATION_ERROR                                  = 'GATEWAY_ERROR_PAYMENT_VERIFICATION_ERROR';
    const GATEWAY_ERROR_UNSUPPORTED_CARD_NETWORK                                    = 'GATEWAY_ERROR_UNSUPPORTED_CARD_NETWORK';
    const GATEWAY_ERROR_FALSE_AUTHORIZE                                             = 'GATEWAY_ERROR_FALSE_AUTHORIZE';
    const GATEWAY_ERROR_UNKNOWN_ERROR                                               = 'GATEWAY_ERROR_UNKNOWN_ERROR';
    const GATEWAY_ERROR_INVALID_TERMINAL                                            = 'GATEWAY_ERROR_INVALID_TERMINAL';
    const GATEWAY_ERROR_INVALID_RESPONSE                                            = 'GATEWAY_ERROR_INVALID_RESPONSE';
    const GATEWAY_ERROR_PAYMENT_ALREADY_SETTLED                                     = 'GATEWAY_ERROR_PAYMENT_ALREADY_SETTLED';
    const GATEWAY_ERROR_PAYMENT_VOID_FAILED                                         = 'GATEWAY_ERROR_PAYMENT_VOID_FAILED';
    const GATEWAY_ERROR_PAYMENT_REFUND_FAILED                                       = 'GATEWAY_ERROR_PAYMENT_REFUND_FAILED';
    const GATEWAY_ERROR_REFUND_AMOUNT_GREATER_THAN_CAPTURED                         = 'GATEWAY_ERROR_REFUND_AMOUNT_GREATER_THAN_CAPTURED';
    const GATEWAY_ERROR_TIMED_OUT                                                   = 'GATEWAY_ERROR_TIMED_OUT';
    const GATEWAY_ERROR_INVALID_DATE_FORMAT                                         = 'GATEWAY_ERROR_INVALID_DATE_FORMAT';
    const GATEWAY_ERROR_SYSTEM_BUSY                                                 = 'GATEWAY_ERROR_SYSTEM_BUSY';
    const GATEWAY_ERROR_COMMUNICATION_ERROR                                         = 'GATEWAY_ERROR_COMMUNICATION_ERROR';
    const GATEWAY_ERROR_INVALID_CONFIGURATION                                       = 'GATEWAY_ERROR_INVALID_CONFIGURATION';
    const GATEWAY_ERROR_USER_INACTIVE                                               = 'GATEWAY_ERROR_USER_INACTIVE';
    const GATEWAY_ERROR_CARD_NOT_ENROLLED                                           = 'GATEWAY_ERROR_CARD_NOT_ENROLLED';
    const GATEWAY_ERROR_CARD_RUPAY_MAESTRO_NOT_ENABLED                              = 'GATEWAY_ERROR_CARD_RUPAY_MAESTRO_NOT_ENABLED';
    const GATEWAY_ERROR_SOAP_ERROR                                                  = 'GATEWAY_ERROR_SOAP_ERROR';
    const GATEWAY_ERROR_DECRYPTION_FAILED                                           = 'GATEWAY_ERROR_DECRYPTION_FAILED';
    const GATEWAY_ERROR_AMOUNT_TAMPERED                                            = 'GATEWAY_ERROR_AMOUNT_TAMPERED';

    const GATEWAY_ERROR_SUPPORT_GREATER_THAN_AUTH                                   = 'GATEWAY_ERROR_SUPPORT_GREATER_THAN_AUTH';

    const GATEWAY_ERROR_PIN_CRYPTOGRAPHY_ERROR                                      = 'GATEWAY_ERROR_PIN_CRYPTOGRAPHY_ERROR';
    const GATEWAY_ERROR_PIN_CHANGE_FAILED                                           = 'GATEWAY_ERROR_PIN_CHANGE_FAILED';
    const GATEWAY_ERROR_SWITCH_UNOPERATIVE                                          = 'GATEWAY_ERROR_SWITCH_UNOPERATIVE';

    const GATEWAY_ERROR_PAYMENT_DUPLICATE_REQUEST                                   = 'GATEWAY_ERROR_PAYMENT_DUPLICATE_REQUEST';
    const GATEWAY_ERROR_REFUND_DUPLICATE_REQUEST                                    = 'GATEWAY_ERROR_REFUND_DUPLICATE_REQUEST';
    const GATEWAY_ERROR_REFUND_NOT_ALLOWED_ON_THE_WALLET                            = 'GATEWAY_ERROR_REFUND_NOT_ALLOWED_ON_THE_WALLET';
    const GATEWAY_ERROR_PAYMENT_INVALID_REFERENCE_NO                                = 'GATEWAY_ERROR_PAYMENT_INVALID_REFERENCE_NO';
    const GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT                                      = 'GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT';
    const GATEWAY_ERROR_PAYMENT_INVALID_ACTION                                      = 'GATEWAY_ERROR_PAYMENT_INVALID_ACTION';
    const GATEWAY_ERROR_PAYMENT_INVALID_ID                                          = 'GATEWAY_ERROR_PAYMENT_INVALID_ID';
    const GATEWAY_ERROR_PAYMENT_CANNOT_BE_RETRIEVED                                 = 'GATEWAY_ERROR_PAYMENT_CANNOT_BE_RETRIEVED';
    const GATEWAY_ERROR_PAYMENT_DENIED_NEGATIVE_BIN                                 = 'GATEWAY_ERROR_PAYMENT_DENIED_NEGATIVE_BIN';
    const GATEWAY_ERROR_PAYMENT_BIN_CHECK_FAILED                                    = 'GATEWAY_ERROR_PAYMENT_BIN_CHECK_FAILED';
    const GATEWAY_ERROR_PAYMENT_INVALID_CURRENCY                                    = 'GATEWAY_ERROR_PAYMENT_INVALID_CURRENCY';
    const GATEWAY_ERROR_PAYMENT_INVALID_UDF                                         = 'GATEWAY_ERROR_PAYMENT_INVALID_UDF';
    const GATEWAY_ERROR_PAYMENT_CREDIT_LESS_THAN_DEBIT                              = 'GATEWAY_ERROR_PAYMENT_CREDIT_LESS_THAN_DEBIT';
    const GATEWAY_ERROR_PAYMENT_SUPPORT_FAILED                                      = 'GATEWAY_ERROR_PAYMENT_SUPPORT_FAILED';
    const GATEWAY_ERROR_PAYMENT_SUPPORT_AUTH_NOT_FOUND                              = 'GATEWAY_ERROR_PAYMENT_SUPPORT_AUTH_NOT_FOUND';
    const GATEWAY_ERROR_PAYMENT_INVALID_MOBILE                                      = 'GATEWAY_ERROR_PAYMENT_INVALID_MOBILE';
    const GATEWAY_ERROR_PAYMENT_INVALID_EMAIL                                       = 'GATEWAY_ERROR_PAYMENT_INVALID_EMAIL';
    const GATEWAY_ERROR_PAYMENT_AUTHENTICATION_ERROR                                = 'GATEWAY_ERROR_PAYMENT_AUTHENTICATION_ERROR';

    const GATEWAY_ERROR_CARD_INVALID_NAME                                           = 'GATEWAY_ERROR_CARD_INVALID_NAME';
    const GATEWAY_ERROR_CARD_INVALID_NUMBER                                         = 'GATEWAY_ERROR_CARD_INVALID_NUMBER';
    const GATEWAY_ERROR_CARD_INVALID_EXPIRY_DATE                                    = 'GATEWAY_ERROR_CARD_INVALID_EXPIRY_DATE';
    const GATEWAY_ERROR_CARD_INVALID_BRAND                                          = 'GATEWAY_ERROR_CARD_INVALID_BRAND';
    const GATEWAY_ERROR_CARD_INVALID_AMOUNT                                         = 'GATEWAY_ERROR_CARD_INVALID_AMOUNT';
    const GATEWAY_ERROR_CARD_INVALID_ADDRESS                                        = 'GATEWAY_ERROR_CARD_INVALID_ADDRESS';
    const GATEWAY_ERROR_CARD_INVALID_ZIP                                            = 'GATEWAY_ERROR_CARD_INVALID_ZIP';
    const GATEWAY_ERROR_CARD_INVALID_CVV                                            = 'GATEWAY_ERROR_CARD_INVALID_CVV';
    const GATEWAY_ERROR_CARD_MISSING_CVV                                            = 'GATEWAY_ERROR_CARD_MISSING_CVV';

    const GATEWAY_ERROR_PAYMENT_MISSING_DATA                                        = 'GATEWAY_ERROR_PAYMENT_MISSING_DATA';
    const GATEWAY_ERROR_INVALID_PARAMETERS                                          = 'GATEWAY_ERROR_INVALID_PARAMETERS';
    const GATEWAY_ERROR_INVALID_CALLBACK_URL                                        = 'GATEWAY_ERROR_INVALID_CALLBACK_URL';

    const GATEWAY_ERROR_PAYMENT_TRANSACTION_NOT_FOUND                               = 'GATEWAY_ERROR_PAYMENT_TRANSACTION_NOT_FOUND';

    const GATEWAY_ERROR_CALLBACK_EMPTY_INPUT                                        = 'GATEWAY_ERROR_CALLBACK_EMPTY_INPUT';

    const GATEWAY_ERROR_MERCHANT_NOT_ENABLED_FOR_STANDING_INSTRUCTION               = 'GATEWAY_ERROR_MERCHANT_NOT_ENABLED_FOR_STANDING_INSTRUCTION';
    const GATEWAY_ERROR_MERCHANT_IP_NOT_WHITELISTED                                 = 'GATEWAY_ERROR_MERCHANT_IP_NOT_WHITELISTED';
    const GATEWAY_ERROR_PREMATURE_SI_EXECUTION                                      = 'GATEWAY_ERROR_PREMATURE_SI_EXECUTION';
    const GATEWAY_ERROR_SI_EXECUTION_ALREADY_DONE                                   = 'GATEWAY_ERROR_SI_EXECUTION_ALREADY_DONE';

    const GATEWAY_ERROR_ISSUER_ACS_SYSTEM_FAILURE                                   = 'GATEWAY_ERROR_ISSUER_ACS_SYSTEM_FAILURE';

    // Generic bad requests
    const BAD_REQUEST_INVALID_ID                                                    = 'BAD_REQUEST_INVALID_ID';
    const BAD_REQUEST_INVALID_IDS                                                   = 'BAD_REQUEST_INVALID_IDS';
    const BAD_REQUEST_INVALID_PASSWORD_RESET_TOKEN                                  = 'BAD_REQUEST_INVALID_PASSWORD_RESET_TOKEN';
    const BAD_REQUEST_NO_RECORDS_FOUND                                              = 'BAD_REQUEST_NO_RECORDS_FOUND';
    const BAD_REQUEST_CHANGE_PASSWORD_NOT_ALLOWED                                   = 'BAD_REQUEST_CHANGE_PASSWORD_NOT_ALLOWED';
    const BAD_REQUEST_ONLY_HTTPS_ALLOWED                                            = 'BAD_REQUEST_ONLY_HTTPS_ALLOWED';
    const BAD_REQUEST_FORBIDDEN                                                     = 'BAD_REQUEST_FORBIDDEN';
    const BAD_REQUEST_HTTP_METHOD_NOT_ALLOWED                                       = 'BAD_REQUEST_HTTP_METHOD_NOT_ALLOWED';
    const BAD_REQUEST_RATE_LIMIT_EXCEEDED                                           = 'BAD_REQUEST_RATE_LIMIT_EXCEEDED';
    const BAD_REQUEST_ERROR                                                         = 'BAD_REQUEST_ERROR';
    const BAD_REQUEST_EXTRA_FIELDS_PROVIDED                                         = 'BAD_REQUEST_EXTRA_FIELDS_PROVIDED';
    const BAD_REQUEST_VALIDATION_FAILURE                                            = 'BAD_REQUEST_VALIDATION_FAILURE';
    const BAD_REQUEST_PERMISSION_ERROR                                              = 'BAD_REQUEST_PERMISSION_ERROR';
    const BAD_REQUEST_APP_TOKEN_NOT_GLOBAL                                          = 'BAD_REQUEST_APP_TOKEN_NOT_GLOBAL';

    const BAD_REQUEST_CUSTOMER_ID_MISSING                                           = 'BAD_REQUEST_CUSTOMER_ID_MISSING';
    const BAD_REQUEST_BANK_ACCOUNT_ID_MISSING                                       = 'BAD_REQUEST_BANK_ACCOUNT_ID_MISSING';
    const BAD_REQUEST_DUPLICATE_VPA                                                 = 'BAD_REQUEST_DUPLICATE_VPA';
    const BAD_REQUEST_UNMAPPED_VPA                                                  = 'BAD_REQUEST_UNMAPPED_VPA';
    const BAD_REQUEST_INVALID_P2P                                                   = 'BAD_REQUEST_INVALID_P2P';
    const BAD_REQUEST_VPA_DOESNT_EXIST                                              = 'BAD_REQUEST_VPA_DOESNT_EXIST';

    // Unauthorized bad requests
    const BAD_REQUEST_UNAUTHORIZED_BASICAUTH_EXPECTED                               = 'BAD_REQUEST_UNAUTHORIZED_BASICAUTH_EXPECTED';
    const BAD_REQUEST_UNAUTHORIZED_INVALID_API_KEY                                  = 'BAD_REQUEST_UNAUTHORIZED_INVALID_API_KEY';
    const BAD_REQUEST_UNAUTHORIZED_INVALID_API_SECRET                               = 'BAD_REQUEST_UNAUTHORIZED_INVALID_API_SECRET';
    const BAD_REQUEST_UNAUTHORIZED_INVALID_ACCOUNT_ID                               = 'BAD_REQUEST_UNAUTHORIZED_INVALID_ACCOUNT_ID';
    const BAD_REQUEST_UNAUTHORIZED_INVALID_HASH                                     = 'BAD_REQUEST_UNAUTHORIZED_INVALID_HASH';
    const BAD_REQUEST_UNABLE_TO_AUTHORIZE_PAYMENT                                   = 'BAD_REQUEST_UNABLE_TO_AUTHORIZE_PAYMENT';
    const BAD_REQUEST_UNAUTHORIZED_SECRET_NOT_PROVIDED                              = 'BAD_REQUEST_UNAUTHORIZED_SECRET_NOT_PROVIDED';
    const BAD_REQUEST_UNAUTHORIZED_SECRET_SENT_ON_PUBLIC_ROUTE                      = 'BAD_REQUEST_UNAUTHORIZED_SECRET_SENT_ON_PUBLIC_ROUTE';
    const BAD_REQUEST_UNAUTHORIZED_API_KEY_NOT_PROVIDED                             = 'BAD_REQUEST_UNAUTHORIZED_API_KEY_NOT_PROVIDED';
    const BAD_REQUEST_UNAUTHORIZED_API_KEY_EXPIRED                                  = 'BAD_REQUEST_UNAUTHORIZED_API_KEY_EXPIRED';
    const BAD_REQUEST_UNAUTHORIZED                                                  = 'BAD_REQUEST_UNAUTHORIZED';

    // OAuth Authorization errors
    const BAD_REQUEST_UNAUTHORIZED_OAUTH_TOKEN_INVALID                              = 'BAD_REQUEST_UNAUTHORIZED_OAUTH_TOKEN_INVALID';
    const BAD_REQUEST_UNAUTHORIZED_OAUTH_SCOPE_INVALID                              = 'BAD_REQUEST_UNAUTHORIZED_OAUTH_SCOPE_INVALID';

    // Payment bad requests
    const BAD_REQUEST_PAYMENT_FAILED                                                = 'BAD_REQUEST_PAYMENT_FAILED';
    const BAD_REQUEST_PAYMENT_CANCELLED_BY_USER                                     = 'BAD_REQUEST_PAYMENT_CANCELLED_BY_USER';
    const BAD_REQUEST_PAYMENT_CANCELLED_BY_PRESSING_BACK_ON_ANDROID                 = 'BAD_REQUEST_PAYMENT_CANCELLED_BY_PRESSING_BACK_ON_ANDROID';
    const BAD_REQUEST_PAYMENT_CANCELLED_AT_LOGIN_SCREEN                             = 'BAD_REQUEST_PAYMENT_CANCELLED_AT_LOGIN_SCREEN';
    const BAD_REQUEST_PAYMENT_CANCELLED_AT_WALLET_PAYMENT_PAGE                      = 'BAD_REQUEST_PAYMENT_CANCELLED_AT_WALLET_PAYMENT_PAGE';
    const BAD_REQUEST_PAYMENT_CANCELLED_AT_NETBANKING_PAYMENT_PAGE                  = 'BAD_REQUEST_PAYMENT_CANCELLED_AT_NETBANKING_PAYMENT_PAGE';
    const BAD_REQUEST_PAYMENT_ALREADY_PROCESSED                                     = 'BAD_REQUEST_PAYMENT_ALREADY_PROCESSED';
    const BAD_REQUEST_PAYMENT_ALREADY_CAPTURED                                      = 'BAD_REQUEST_PAYMENT_ALREADY_CAPTURED';
    const BAD_REQUEST_PAYMENT_ALREADY_REFUNDED                                      = 'BAD_REQUEST_PAYMENT_ALREADY_REFUNDED';
    const BAD_REQUEST_PAYMENT_ALREADY_REFUND_INITIATED                              = 'BAD_REQUEST_PAYMENT_ALREADY_REFUND_INITIATED';
    const BAD_REQUEST_PAYMENT_INVALID_CAPTURE                                       = 'BAD_REQUEST_PAYMENT_INVALID_CAPTURE';
    const BAD_REQUEST_PAYMENT_ANOTHER_OPERATION_IN_PROGRESS                         = 'BAD_REQUEST_PAYMENT_ANOTHER_OPERATION_IN_PROGRESS';
    const BAD_REQUEST_PAYMENT_CURRENCY_NOT_SUPPORTED                                = 'BAD_REQUEST_PAYMENT_CURRENCY_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_VOID_NOT_SUPPORTED                                    = 'BAD_REQUEST_PAYMENT_VOID_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_INVALID_AMOUNT_OR_CURRENCY                            = 'BAD_REQUEST_PAYMENT_INVALID_AMOUNT_OR_CURRENCY';
    const BAD_REQUEST_PAYMENT_INVALID_FORMAT                                        = 'BAD_REQUEST_PAYMENT_INVALID_FORMAT';
    const BAD_REQUEST_PAYMENT_INVALID_STATUS                                        = 'BAD_REQUEST_PAYMENT_INVALID_STATUS';
    const BAD_REQUEST_PAYMENT_CARD_IS_NOT_ARRAY                                     = 'BAD_REQUEST_PAYMENT_CARD_IS_NOT_ARRAY';
    const BAD_REQUEST_PAYMENT_CAPTURE_ONLY_AUTHORIZED                               = 'BAD_REQUEST_PAYMENT_CAPTURE_ONLY_AUTHORIZED';
    const BAD_REQUEST_PAYMENT_CANCEL_ONLY_CREATED                                   = 'BAD_REQUEST_PAYMENT_CANCEL_ONLY_CREATED';
    const BAD_REQUEST_PAYMENT_CARD_NOT_PROVIDED                                     = 'BAD_REQUEST_PAYMENT_CARD_NOT_PROVIDED';
    const BAD_REQUEST_PAYMENT_CARD_CVV_NOT_PROVIDED                                 = 'BAD_REQUEST_PAYMENT_CARD_CVV_NOT_PROVIDED';
    const BAD_REQUEST_PAYMENT_CARD_INVALID_PIN                                      = 'BAD_REQUEST_PAYMENT_CARD_INVALID_PIN';
    const BAD_REQUEST_PAYMENT_CARD_INVALID_CVV                                      = 'BAD_REQUEST_PAYMENT_CARD_INVALID_CVV';
    const BAD_REQUEST_PAYMENT_CARD_HOLDER_AUTHENTICATION_FAILED                     = 'BAD_REQUEST_PAYMENT_CARD_HOLDER_AUTHENTICATION_FAILED';
    const BAD_REQUEST_PAYMENT_CARD_AUTHENTICATION_NOT_AVAILABLE                     = 'BAD_REQUEST_PAYMENT_CARD_AUTHENTICATION_NOT_AVAILABLE';
    const BAD_REQUEST_PAYMENT_STATUS_NOT_CAPTURED                                   = 'BAD_REQUEST_PAYMENT_STATUS_NOT_CAPTURED';
    const BAD_REQUEST_PAYMENT_METHOD_NOT_TRANSFER                                   = 'BAD_REQUEST_PAYMENT_METHOD_NOT_TRANSFER';
    const BAD_REQUEST_PAYMENT_STATUS_CAPTURE_NOT_PROCESSED                          = 'BAD_REQUEST_PAYMENT_STATUS_CAPTURE_NOT_PROCESSED';
    const BAD_REQUEST_PAYMENT_PAYOUT_BEFORE_SETTLEMENT                              = 'BAD_REQUEST_PAYMENT_PAYOUT_BEFORE_SETTLEMENT';
    const BAD_REQUEST_PAYMENT_PAYOUT_AMOUNT_GREATER_THAN_CAPTURED                   = 'BAD_REQUEST_PAYMENT_PAYOUT_AMOUNT_GREATER_THAN_CAPTURED';
    const BAD_REQUEST_PAYMENT_PAYOUT_AMOUNT_GREATER_THAN_PENDING                    = 'BAD_REQUEST_PAYMENT_PAYOUT_AMOUNT_GREATER_THAN_PENDING';
    const BAD_REQUEST_PAYMENT_FULLY_PAIDOUT                                         = 'BAD_REQUEST_PAYMENT_FULLY_PAIDOUT';
    const BAD_REQUEST_PAYMENT_FULLY_REFUNDED                                        = 'BAD_REQUEST_PAYMENT_FULLY_REFUNDED';
    const BAD_REQUEST_PAYMENT_REFUND_NOT_SUPPORTED                                  = 'BAD_REQUEST_PAYMENT_REFUND_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_PARTIAL_REFUND_NOT_SUPPORTED                          = 'BAD_REQUEST_PAYMENT_PARTIAL_REFUND_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_CAPTURED                   = 'BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_CAPTURED';
    const BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_UNREFUNDED                 = 'BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_UNREFUNDED';
    const BAD_REQUEST_PAYMENT_AMOUNT_GREATER_THAN_REFUNDED                          = 'BAD_REQUEST_PAYMENT_AMOUNT_GREATER_THAN_REFUNDED';
    const BAD_REQUEST_PAYMENT_UNDER_DISPUTE_CANNOT_BE_REFUNDED                      = 'BAD_REQUEST_PAYMENT_UNDER_DISPUTE_CANNOT_BE_REFUNDED';
    const BAD_REQUEST_PAYMENT_CAPTURE_AMOUNT_NOT_EQUAL_TO_AUTH                      = 'BAD_REQUEST_PAYMENT_CAPTURE_AMOUNT_NOT_EQUAL_TO_AUTH';
    const BAD_REQUEST_PAYMENT_CAPTURE_CURRENCY_MISMATCH                             = 'BAD_REQUEST_PAYMENT_CAPTURE_CURRENCY_MISMATCH';
    const BAD_REQUEST_PAYMENT_NET_BANKING_NOT_ENABLED                               = 'BAD_REQUEST_PAYMENT_NET_BANKING_NOT_ENABLED';
    const BAD_REQUEST_PAYMENT_TXN_NOT_PUSHED_TO_NET_BANKING                         = 'BAD_REQUEST_PAYMENT_TXN_NOT_PUSHED_TO_NET_BANKING';
    const BAD_REQUEST_PAYMENT_TXN_REJECTED_FROM_NET_BANKING                         = 'BAD_REQUEST_PAYMENT_TXN_REJECTED_FROM_NET_BANKING';
    const BAD_REQUEST_PAYMENT_INVALID_TRANSACTION_DATE                              = 'BAD_REQUEST_PAYMENT_INVALID_TRANSACTION_DATE';
    const BAD_REQUEST_PAYMENT_RECURRING_NOT_ENABLED                                 = 'BAD_REQUEST_PAYMENT_RECURRING_NOT_ENABLED';
    const BAD_REQUEST_PAYMENT_RECURRING_AUTH_NOT_SUPPORTED                          = 'BAD_REQUEST_PAYMENT_RECURRING_AUTH_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_AEPS_NOT_ENABLED_FOR_MERCHANT                         = 'BAD_REQUEST_PAYMENT_AEPS_NOT_ENABLED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_UPI_NOT_ENABLED_FOR_MERCHANT                          = 'BAD_REQUEST_PAYMENT_UPI_NOT_ENABLED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_UPI_INVALID_VPA                                       = 'BAD_REQUEST_PAYMENT_UPI_INVALID_VPA';
    const BAD_REQUEST_PAYMENT_UPI_APP_NOT_SUPPORTED                                 = 'BAD_REQUEST_PAYMENT_UPI_APP_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_BANK_TRANSFER_NOT_ENABLED_FOR_MERCHANT                = 'BAD_REQUEST_PAYMENT_BANK_TRANSFER_NOT_ENABLED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_BANK_NOT_PROVIDED                                     = 'BAD_REQUEST_PAYMENT_BANK_NOT_PROVIDED';
    const BAD_REQUEST_PAYMENT_INVALID_BANK_CODE                                     = 'BAD_REQUEST_PAYMENT_INVALID_BANK_CODE';
    const BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_MIN_AMOUNT                           = 'BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_MIN_AMOUNT';
    const BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_10_MIN_AMOUNT                        = 'BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_10_MIN_AMOUNT';
    const BAD_REQUEST_PAYMENT_ATOM_NET_BANKING_MIN_AMOUNT_FIFTY                     = 'BAD_REQUEST_PAYMENT_ATOM_NET_BANKING_MIN_AMOUNT_FIFTY';
    const BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_MIN_AMOUNT_FOR_EMI                   = 'BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_MIN_AMOUNT_FOR_EMI';
    const BAD_REQUEST_PAYMENT_AMOUNT_TOO_HIGH                                       = 'BAD_REQUEST_PAYMENT_AMOUNT_TOO_HIGH';
    const BAD_REQUEST_PAYMENT_CONTACT_INCORRECT_FORMAT                              = 'BAD_REQUEST_PAYMENT_CONTACT_INCORRECT_FORMAT';
    const BAD_REQUEST_PAYMENT_CONTACT_INVALID_COUNTRY_CODE                          = 'BAD_REQUEST_PAYMENT_CONTACT_INVALID_COUNTRY_CODE';
    const BAD_REQUEST_PAYMENT_CONTACT_TOO_SHORT                                     = 'BAD_REQUEST_PAYMENT_CONTACT_TOO_SHORT';
    const BAD_REQUEST_PAYMENT_CONTACT_TOO_LONG                                      = 'BAD_REQUEST_PAYMENT_CONTACT_TOO_LONG';
    const BAD_REQUEST_PAYMENT_CONTACT_ONLY_INDIAN_ALLOWED                           = 'BAD_REQUEST_PAYMENT_CONTACT_ONLY_INDIAN_ALLOWED';
    const BAD_REQUEST_PAYMENT_CARD_NETWORK_NOT_SUPPORTED                            = 'BAD_REQUEST_PAYMENT_CARD_NETWORK_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_CARD_TYPE_INVALID                                     = 'BAD_REQUEST_PAYMENT_CARD_TYPE_INVALID';
    const BAD_REQUEST_PAYMENT_CARD_HOLDER_NOT_PERMITTED_TXN                         = 'BAD_REQUEST_PAYMENT_CARD_HOLDER_NOT_PERMITTED_TXN';
    const BAD_REQUEST_PAYMENT_CARD_INSUFFICIENT_BALANCE                             = 'BAD_REQUEST_PAYMENT_CARD_INSUFFICIENT_BALANCE';
    const BAD_REQUEST_PAYMENT_CARD_DECLINED                                         = 'BAD_REQUEST_PAYMENT_CARD_DECLINED';
    const BAD_REQUEST_PAYMENT_CARD_EXPIRED                                          = 'BAD_REQUEST_PAYMENT_CARD_EXPIRED';
    const BAD_REQUEST_PAYMENT_CARD_INVALID_EXPIRY_DATE                              = 'BAD_REQUEST_PAYMENT_CARD_INVALID_EXPIRY_DATE';
    const BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID                                  = 'BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID';
    const BAD_REQUEST_PAYMENT_CARD_ISSUING_BANK_PREVENTED_AUTHORIZATION             = 'BAD_REQUEST_PAYMENT_CARD_ISSUING_BANK_PREVENTED_AUTHORIZATION';
    const BAD_REQUEST_PAYMENT_CARD_NUMBER_NOT_LEGITIMATE                            = 'BAD_REQUEST_PAYMENT_CARD_NUMBER_NOT_LEGITIMATE';
    const BAD_REQUEST_PAYMENT_CARD_NUMBER_POSSIBLY_INVALID                          = 'BAD_REQUEST_PAYMENT_CARD_NUMBER_POSSIBLY_INVALID';
    const BAD_REQUEST_PAYMENT_CARD_WITHDRAWAL_LIMITS_EXCEEDED                       = 'BAD_REQUEST_PAYMENT_CARD_WITHDRAWAL_LIMITS_EXCEEDED';
    const BAD_REQUEST_PAYMENT_CARD_ISSUING_BANK_NOT_PERMITTING_PAYMENT              = 'BAD_REQUEST_PAYMENT_CARD_ISSUING_BANK_NOT_PERMITTING_PAYMENT';
    const BAD_REQUEST_PAYMENT_CARD_CVV_LENGTH_MUST_BE_THREE                         = 'BAD_REQUEST_PAYMENT_CARD_CVV_LENGTH_MUST_BE_THREE';
    const BAD_REQUEST_PAYMENT_CARD_AMEX_CVV_LENGTH_MUST_BE_FOUR                     = 'BAD_REQUEST_PAYMENT_CARD_AMEX_CVV_LENGTH_MUST_BE_FOUR';
    const BAD_REQUEST_PAYMENT_TERMINAL_STATE_CODE_EXCEEDED_LENGTH                   = 'BAD_REQUEST_PAYMENT_TERMINAL_STATE_CODE_EXCEEDED_LENGTH';
    const BAD_REQUEST_PAYMENT_CARD_INTERNATIONAL_NOT_ALLOWED                        = 'BAD_REQUEST_PAYMENT_CARD_INTERNATIONAL_NOT_ALLOWED';
    const BAD_REQUEST_PAYMENT_INTERNATIONAL_RECURRING_NOT_ALLOWED_FOR_MERCHANT      = 'BAD_REQUEST_PAYMENT_INTERNATIONAL_RECURRING_NOT_ALLOWED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_CARD_AUTHENTICATION_INVALID                           = 'BAD_REQUEST_PAYMENT_CARD_AUTHENTICATION_INVALID';
    const BAD_REQUEST_PAYMENT_CARD_RECURRING_NOT_SUPPORTED                          = 'BAD_REQUEST_PAYMENT_CARD_RECURRING_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_BANK_RECURRING_NOT_SUPPORTED                          = 'BAD_REQUEST_PAYMENT_BANK_RECURRING_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_AMOUNT_GREATER_THAN_TOKEN_MAX_AMOUNT                  = 'BAD_REQUEST_PAYMENT_AMOUNT_GREATER_THAN_TOKEN_MAX_AMOUNT';
    const BAD_REQUEST_PAYMENT_BLOCKED_DUE_TO_FRAUD                                  = 'BAD_REQUEST_PAYMENT_BLOCKED_DUE_TO_FRAUD';
    const BAD_REQUEST_PAYMENT_TIMED_OUT                                             = 'BAD_REQUEST_PAYMENT_TIMED_OUT';
    const BAD_REQUEST_PAYMENT_TIMED_OUT_AT_GATEWAY                                  = 'BAD_REQUEST_PAYMENT_TIMED_OUT_AT_GATEWAY';
    const BAD_REQUEST_PAYMENT_TIMED_OUT_AT_WALLET_PAYMENT_PAGE                      = 'BAD_REQUEST_PAYMENT_TIMED_OUT_AT_WALLET_PAYMENT_PAGE';
    const BAD_REQUEST_PAYMENT_BANK_NOT_ENABLED_FOR_MERCHANT                         = 'BAD_REQUEST_PAYMENT_BANK_NOT_ENABLED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_WALLET_NOT_SUPPORTED                                  = 'BAD_REQUEST_PAYMENT_WALLET_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_WALLET_NOT_PROVIDED                                   = 'BAD_REQUEST_PAYMENT_WALLET_NOT_PROVIDED';
    const BAD_REQUEST_PAYMENT_WALLET_NOT_ENABLED_FOR_MERCHANT                       = 'BAD_REQUEST_PAYMENT_WALLET_NOT_ENABLED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_CARD_NOT_ENABLED_FOR_MERCHANT                         = 'BAD_REQUEST_PAYMENT_CARD_NOT_ENABLED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_EMI_NOT_ENABLED_FOR_MERCHANT                          = 'BAD_REQUEST_PAYMENT_EMI_NOT_ENABLED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_EMI_NOT_AVAILABLE_ON_CARD                             = 'BAD_REQUEST_PAYMENT_EMI_NOT_AVAILABLE_ON_CARD';
    const BAD_REQUEST_PAYMENT_DECLINED_BY_CLICKING_CANCEL                           = 'BAD_REQUEST_PAYMENT_DECLINED_BY_CLICKING_CANCEL';
    const BAD_REQUEST_PAYMENT_DECLINED_BY_GATEWAY                                   = 'BAD_REQUEST_PAYMENT_DECLINED_BY_GATEWAY';
    const BAD_REQUEST_PAYMENT_DECLINED_BY_BANK                                      = 'BAD_REQUEST_PAYMENT_DECLINED_BY_BANK';
    const BAD_REQUEST_PAYMENT_NO_RESPONSE_RECEIVED_FROM_BANK                        = 'BAD_REQUEST_PAYMENT_NO_RESPONSE_RECEIVED_FROM_BANK';
    const BAD_REQUEST_PAYMENT_BANK_SYSTEM_ERROR                                     = 'BAD_REQUEST_PAYMENT_BANK_SYSTEM_ERROR';
    const BAD_REQUEST_PAYMENT_FAILED_MAYBE_DUE_TO_INVALID_INPUT                     = 'BAD_REQUEST_PAYMENT_FAILED_MAYBE_DUE_TO_INVALID_INPUT';
    const BAD_REQUEST_PAYMENT_FAILED_DUE_TO_INVALID_BIN                             = 'BAD_REQUEST_PAYMENT_FAILED_DUE_TO_INVALID_BIN';
    const BAD_REQUEST_PAYMENT_FAILED_BECAUSE_SESSION_EXPIRED                        = 'BAD_REQUEST_PAYMENT_FAILED_BECAUSE_SESSION_EXPIRED';
    const BAD_REQUEST_PAYMENT_CANCELLED                                             = 'BAD_REQUEST_PAYMENT_CANCELLED';
    const BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK                         = 'BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK';
    const BAD_REQUEST_PAYMENT_DECLINED_3DSECURE_AUTH_FAILED                         = 'BAD_REQUEST_PAYMENT_DECLINED_3DSECURE_AUTH_FAILED';
    const BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK                          = 'BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK';
    const BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_BLOCKED_CARD                  = 'BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_BLOCKED_CARD';
    const BAD_REQUEST_PAYMENT_DECLINED_BY_GATEWAY_DUE_TO_RISK                       = 'BAD_REQUEST_PAYMENT_DECLINED_BY_GATEWAY_DUE_TO_RISK';
    const BAD_REQUEST_PAYMENT_CARD_NOT_ENROLLED_FOR_3DSECURE                        = 'BAD_REQUEST_PAYMENT_CARDHOLDER_NOT_ENROLLED_IN_3DSECURE_AUTH';
    const BAD_REQUEST_PAYMENT_INVALID_MOBILE                                        = 'BAD_REQUEST_PAYMENT_INVALID_MOBILE';
    const BAD_REQUEST_PAYMENT_INVALID_EMAIL                                         = 'BAD_REQUEST_PAYMENT_INVALID_EMAIL';
    const BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED                         = 'BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED';
    const BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED                        = 'BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED';
    const BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED                       = 'BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED';
    const BAD_REQUEST_PAYMENT_WALLET_PER_PAYMENT_AMOUNT_CROSSED                     = 'BAD_REQUEST_PAYMENT_WALLET_PER_PAYMENT_AMOUNT_CROSSED';
    const BAD_REQUEST_PAYMENT_WALLET_BLOCKED_CARD                                   = 'BAD_REQUEST_PAYMENT_WALLET_BLOCKED_CARD';
    const BAD_REQUEST_PAYMENT_WALLET_BLOCKED_MOBILE_NUMBER                          = 'BAD_REQUEST_PAYMENT_WALLET_BLOCKED_MOBILE_NUMBER';
    const BAD_REQUEST_PAYMENT_WALLET_BLOCKED_IP_ADDRESS                             = 'BAD_REQUEST_PAYMENT_WALLET_BLOCKED_IP_ADDRESS';
    const BAD_REQUEST_PAYMENT_WALLET_BLOCKED_CUSTOMER                               = 'BAD_REQUEST_PAYMENT_WALLET_BLOCKED_CUSTOMER';
    const BAD_REQUEST_PAYMENT_WALLET_MAX_WRONG_ATTEMPT_LIMIT_CROSSED                = 'BAD_REQUEST_PAYMENT_WALLET_MAX_WRONG_ATTEMPT_LIMIT_CROSSED';
    const BAD_REQUEST_PAYMENT_WALLET_MAX_AMOUNT_LIMIT_CROSSED_FOR_CUSTOMER          = 'BAD_REQUEST_PAYMENT_WALLET_MAX_AMOUNT_LIMIT_CROSSED';
    const BAD_REQUEST_PAYMENT_WALLET_NOT_ACTIVATED                                  = 'BAD_REQUEST_PAYMENT_WALLET_NOT_ACTIVATED';
    const BAD_REQUEST_PAYMENT_WALLET_USER_DOES_NOT_EXIST                            = 'BAD_REQUEST_PAYMENT_WALLET_USER_DOES_NOT_EXIST';
    const BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_INVALID_MOBILE                         = 'BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_INVALID_MOBILE';
    const BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_INVALID_CREDENTIALS                    = 'BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_INVALID_CREDENTIALS';
    const BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_ALREADY_EXIST_WITH_EMAIL               = 'BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_ALREADY_EXIST_WITH_EMAIL';
    const BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_ALREADY_EXIST_WITH_CONTACT             = 'BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_ALREADY_EXIST_WITH_CONTACT';
    const BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_INACTIVE                               = 'BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_INACTIVE';
    const BAD_REQUEST_PAYMENT_WALLET_NO_USER_WITH_CELL                              = 'BAD_REQUEST_PAYMENT_WALLET_NO_USER_WITH_CELL';
    const BAD_REQUEST_PAYMENT_WALLET_AUTHENTICATION_FAILED                          = 'BAD_REQUEST_PAYMENT_WALLET_AUTHENTICATION_FAILED';
    const BAD_REQUEST_PAYMENT_WALLET_INSUFFICIENT_BALANCE                           = 'BAD_REQUEST_PAYMENT_WALLET_INSUFFICIENT_BALANCE';
    const BAD_REQUEST_PAYMENT_WALLET_CUSTOMER_TOKEN_NOT_FOUND                       = 'BAD_REQUEST_PAYMENT_WALLET_CUSTOMER_TOKEN_NOT_FOUND';
    const BAD_REQUEST_PAYMENT_WALLET_CONTACT_PAYUMONEY                              = 'BAD_REQUEST_PAYMENT_WALLET_CONTACT_PAYUMONEY';
    const BAD_REQUEST_AIRTEL_MONEY_ACCOUNT_BLOCKED                                  = 'BAD_REQUEST_AIRTEL_MONEY_ACCOUNT_BLOCKED';
    const BAD_REQUEST_AIRTEL_MONEY_RESET_MPIN                                       = 'BAD_REQUEST_AIRTEL_MONEY_RESET_MPIN';
    const BAD_REQUEST_CONTACT_AIRTEL_MONEY_CUSTOMER_CARE_FOR_REFUND                 = 'BAD_REQUEST_CONTACT_AIRTEL_MONEY_CUSTOMER_CARE_FOR_REFUND';
    const BAD_REQUEST_PAYMENT_TOPUP_INVALID_WALLET_TOKEN                            = 'BAD_REQUEST_PAYMENT_TOPUP_INVALID_WALLET_TOKEN';
    const BAD_REQUEST_PAYMENT_OTP_VALIDATION_ATTEMPT_LIMIT_EXCEEDED                 = 'BAD_REQUEST_PAYMENT_OTP_VALIDATION_ATTEMPT_LIMIT_EXCEEDED';
    const BAD_REQUEST_PAYMENT_OTP_INCORRECT                                         = 'BAD_REQUEST_PAYMENT_OTP_INCORRECT';
    const BAD_REQUEST_PAYMENT_OTP_EXPIRED                                           = 'BAD_REQUEST_PAYMENT_OTP_EXPIRED';
    const BAD_REQUEST_PAYMENT_PIN_INCORRECT                                         = 'BAD_REQUEST_PAYMENT_PIN_INCORRECT';
    const BAD_REQUEST_PAYMENT_PIN_ATTEMPTS_EXCEEDED                                 = 'BAD_REQUEST_PAYMENT_PIN_ATTEMPTS_EXCEEDED';
    const BAD_REQUEST_PAYMENT_MAX_TRANSACTIONS_PER_ORDER_EXCEEDED                   = 'BAD_REQUEST_PAYMENT_MAX_TRANSACTIONS_PER_ORDER_EXCEEDED';
    const BAD_REQUEST_ORDER_EXISTS                                                  = 'BAD_REQUEST_ORDER_EXISTS';
    const BAD_REQUEST_ORDER_DOES_NOT_EXIST                                          = 'BAD_REQUEST_ORDER_DOES_NOT_EXIST';
    const BAD_REQUEST_ORDER_INVALID_OFFER                                           = 'BAD_REQUEST_ORDER_INVALID_OFFER';
    const BAD_REQUEST_PAYMENT_ORDER_AMOUNT_MISMATCH                                 = 'BAD_REQUEST_PAYMENT_ORDER_AMOUNT_MISMATCH';
    const BAD_REQUEST_PAYMENT_AMOUNT_MORE_THAN_ORDER_AMOUNT_DUE                     = 'BAD_REQUEST_PAYMENT_AMOUNT_MORE_THAN_ORDER_AMOUNT_DUE';
    const BAD_REQUEST_PAYMENT_ORDER_CURRENCY_MISMATCH                               = 'BAD_REQUEST_PAYMENT_ORDER_CURRENCY_MISMATCH';
    const BAD_REQUEST_PAYMENT_ORDER_ALREADY_PAID                                    = 'BAD_REQUEST_PAYMENT_ORDER_ALREADY_PAID';
    const BAD_REQUEST_PAYMENT_XML_SIGNATURE_ERROR                                   = 'BAD_REQUEST_PAYMENT_XML_SIGNATURE_ERROR';
    const BAD_REQUEST_INVALID_XML_SCHEMA                                            = 'BAD_REQUEST_INVALID_XML_SCHEMA';
    const BAD_REQUEST_PAYMENT_ABORTED                                               = 'BAD_REQUEST_PAYMENT_ABORTED';
    const BAD_REQUEST_PAYMENT_MISSING_DATA                                          = 'BAD_REQUEST_PAYMENT_MISSING_DATA';
    const BAD_REQUEST_PAYMENT_PARTIAL_AMOUNT_APPROVED                               = 'BAD_REQUEST_PAYMENT_PARTIAL_AMOUNT_APPROVED';
    const BAD_REQUEST_PAYMENT_PROBLEM_IN_UPDATING                                   = 'BAD_REQUEST_PAYMENT_PROBLEM_IN_UPDATING';
    const BAD_REQUEST_PAYMENT_FEES_GREATER_THAN_AMOUNT                              = 'BAD_REQUEST_PAYMENT_FEES_GREATER_THAN_AMOUNT';
    const BAD_REQUEST_PAYMENT_CANNOT_BE_CANCELLED                                   = 'BAD_REQUEST_PAYMENT_CANNOT_BE_CANCELLED';
    const BAD_REQUEST_PAYMENT_ALREADY_UNDER_DISPUTE                                 = 'BAD_REQUEST_PAYMENT_ALREADY_UNDER_DISPUTE';
    const BAD_REQUEST_DISPUTE_AMOUNT_GREATER_THAN_PAYMENT_AMOUNT                    = 'BAD_REQUEST_DISPUTE_AMOUNT_GREATER_THAN_PAYMENT_AMOUNT';
    const BAD_REQUEST_CANNOT_UPDATE_CLOSED_DISPUTE                                  = 'BAD_REQUEST_CANNOT_UPDATE_CLOSED_DISPUTE';
    const BAD_REQUEST_PAYMENT_UPI_REQUEST_TIMED_OUT                                 = 'BAD_REQUEST_PAYMENT_UPI_REQUEST_TIMED_OUT';
    const BAD_REQUEST_GATEWAY_REFUND_ABSENT                                         = 'BAD_REQUEST_GATEWAY_REFUND_ABSENT';
    const BAD_REQUEST_INVALID_GATEWAY                                               = 'BAD_REQUEST_INVALID_GATEWAY';
    const BAD_REQUEST_APP_TOKEN_ABSENT                                              = 'BAD_REQUEST_APP_TOKEN_ABSENT';
    const BAD_REQUEST_PAYMENT_SUBSCRIPTION_NOT_RECURRING                            = 'BAD_REQUEST_PAYMENT_SUBSCRIPTION_NOT_RECURRING';
    const BAD_REQUEST_PAYMENT_NOT_AUTHORIZED                                        = 'BAD_REQUEST_PAYMENT_NOT_AUTHORIZED';
    const BAD_REQUEST_NOT_CARD_PAYMENT                                              = 'BAD_REQUEST_NOT_CARD_PAYMENT';
    const BAD_REQUEST_SUBSCRIPTION_TOKEN_ALREADY_ASSOCIATED                         = 'BAD_REQUEST_SUBSCRIPTION_TOKEN_ALREADY_ASSOCIATED';
    const BAD_REQUEST_SUBSCRIPTION_TOKEN_NOT_ASSOCIATED                             = 'BAD_REQUEST_SUBSCRIPTION_TOKEN_NOT_ASSOCIATED';
    const BAD_REQUEST_SUBSCRIPTION_TOTAL_COUNT_EXCEEDED                             = 'BAD_REQUEST_SUBSCRIPTION_TOTAL_COUNT_EXCEEDED';
    const BAD_REQUEST_BANK_REQUIRED_WITH_ACCOUNT_NUMBER                             = 'BAD_REQUEST_BANK_REQUIRED_WITH_ACCOUNT_NUMBER';
    const BAD_REQUEST_SUBSCRIPTION_IN_TERMINAL_STATE                                = 'BAD_REQUEST_SUBSCRIPTION_IN_TERMINAL_STATE';
    const BAD_REQUEST_SUBSCRIPTION_NOT_IN_ACTIVE_OR_HALTED_STATE                    = 'BAD_REQUEST_SUBSCRIPTION_NOT_IN_ACTIVE_OR_HALTED_STATE';
    const BAD_REQUEST_SUBSCRIPTION_NOT_IN_PENDING_STATE                             = 'BAD_REQUEST_SUBSCRIPTION_NOT_IN_PENDING_STATE';
    const BAD_REQUEST_OPERATION_NOT_ALLOWED_IN_LIVE                                 = 'BAD_REQUEST_OPERATION_NOT_ALLOWED_IN_LIVE';
    const BAD_REQUEST_SUBSCRIPTION_NOT_TEST_CHARGEABLE                              = 'BAD_REQUEST_SUBSCRIPTION_NOT_TEST_CHARGEABLE';
    const BAD_REQUEST_SUBSCRIPTION_INVOICE_CANNOT_BE_CHARGED                        = 'BAD_REQUEST_SUBSCRIPTION_INVOICE_CANNOT_BE_CHARGED';
    const BAD_REQUEST_SUBSCRIPTION_2FA_NOT_ALLOWED                                  = 'BAD_REQUEST_SUBSCRIPTION_2FA_NOT_ALLOWED';
    const BAD_REQUEST_SUBSCRIPTION_CARD_CHANGE_NOT_ALLOWED                          = 'BAD_REQUEST_SUBSCRIPTION_CARD_CHANGE_NOT_ALLOWED';
    const BAD_REQUEST_SUBSCRIPTION_CUSTOMER_NOT_FOUND                               = 'BAD_REQUEST_SUBSCRIPTION_CUSTOMER_NOT_FOUND';
    const BAD_REQUEST_SUBSCRIPTION_CUSTOMER_ID_SENT_IN_INPUT                        = 'BAD_REQUEST_SUBSCRIPTION_CUSTOMER_ID_SENT_IN_INPUT';
    const BAD_REQUEST_SUBSCRIPTION_SAVE_CARD_DISABLED                               = 'BAD_REQUEST_SUBSCRIPTION_SAVE_CARD_DISABLED';
    const BAD_REQUEST_SUBSCRIPTION_PAYMENT_WITHOUT_SAVING                           = 'BAD_REQUEST_SUBSCRIPTION_PAYMENT_WITHOUT_SAVING';
    const BAD_REQUEST_SUBSCRIPTION_ANOTHER_OPERATION_IN_PROGRESS                    = 'BAD_REQUEST_SUBSCRIPTION_ANOTHER_OPERATION_IN_PROGRESS';
    const BAD_REQUEST_SUBSCRIPTION_INVALID_STATUS                                   = 'BAD_REQUEST_SUBSCRIPTION_INVALID_STATUS';
    const BAD_REQUEST_SUBSCRIPTION_SCHEDULED_FAILURE                                = 'BAD_REQUEST_SUBSCRIPTION_SCHEDULED_FAILURE';
    const BAD_REQUEST_SUBSCRIPTION_CYCLE_NOT_RUNNING                                = 'BAD_REQUEST_SUBSCRIPTION_CYCLE_NOT_RUNNING';
    const BAD_REQUEST_SUBSCRIPTION_LAST_CYCLE_CANNOT_CANCEL                         = 'BAD_REQUEST_SUBSCRIPTION_LAST_CYCLE_CANNOT_CANCEL';
    const BAD_REQUEST_ADDON_DELETE_NOT_ALLOWED                                      = 'BAD_REQUEST_ADDON_DELETE_NOT_ALLOWED';
    const BAD_REQUEST_SUBSCRIPTION_ALREADY_AUTHENTICATED                            = 'BAD_REQUEST_SUBSCRIPTION_ALREADY_AUTHENTICATED';
    const BAD_REQUEST_SUBSCRIPTION_PAYMENT_PARAMS_MISSING                           = 'BAD_REQUEST_SUBSCRIPTION_PAYMENT_PARAMS_MISSING';

    const BAD_REQUEST_PAYMENT_POSSIBLE_FRAUD                                        = 'BAD_REQUEST_PAYMENT_POSSIBLE_FRAUD';
    const BAD_REQUEST_CARD_AVS_FAILED                                               = 'BAD_REQUEST_CARD_AVS_FAILED';
    const BAD_REQUEST_CARD_STOLEN_OR_LOST                                           = 'BAD_REQUEST_CARD_STOLEN_OR_LOST';
    const BAD_REQUEST_CARD_ISSUING_BANK_UNAVAILABLE                                 = 'BAD_REQUEST_CARD_ISSUING_BANK_UNAVAILABLE';
    const BAD_REQUEST_CARD_INACTIVE                                                 = 'BAD_REQUEST_CARD_INACTIVE';
    const BAD_REQUEST_CARD_CREDIT_LIMIT_REACHED                                     = 'BAD_REQUEST_CARD_CREDIT_LIMIT_REACHED';
    const BAD_REQUEST_CARD_FROZEN                                                   = 'BAD_REQUEST_CARD_FROZEN';
    const BAD_REQUEST_CARD_DAILY_LIMIT_REACHED                                      = 'BAD_REQUEST_CARD_DAILY_LIMIT_REACHED';
    const BAD_REQUEST_CARD_BILL_SHIP_MISMATCH                                       = 'BAD_REQUEST_CARD_BILL_SHIP_MISMATCH';
    const BAD_REQUEST_INVALID_PARAMETERS                                            = 'BAD_REQUEST_INVALID_PARAMETERS';
    const BAD_REQUEST_INVOICE_STATUS_UNAVAILABLE                                    = 'BAD_REQUEST_INVOICE_STATUS_UNAVAILABLE';
    const BAD_REQUEST_INVALID_MESSAGE_KEYWORD                                       = 'BAD_REQUEST_INVALID_MESSAGE_KEYWORD';
    const BAD_REQUEST_MISSING_FIELDS_MESSAGE                                        = 'BAD_REQUEST_MISSING_FIELDS_MESSAGE';
    const BAD_REQUEST_END_AT_AND_TOTAL_COUNT_SENT                                   = 'BAD_REQUEST_END_AT_AND_TOTAL_COUNT_SENT';
    const BAD_REQUEST_SUBSCRIPTION_CURRENT_TIME_PAST_START_TIME                     = 'BAD_REQUEST_SUBSCRIPTION_CURRENT_TIME_PAST_START_TIME';
    const BAD_REQUEST_INVOICE_CHARGE_FAILED                                         = 'BAD_REQUEST_INVOICE_CHARGE_FAILED';

    const BAD_REQUEST_UNSUPPORTED_CHARACTER_SET                                     = 'BAD_REQUEST_UNSUPPORTED_CHARACTER_SET';

    const BAD_REQUEST_PAYMENT_ORDER_ID_REQUIRED                                     = 'BAD_REQUEST_PAYMENT_ORDER_ID_REQUIRED';
    const BAD_REQUEST_ORDER_METHOD_REQUIRED_FOR_MERCHANT                            = 'BAD_REQUEST_ORDER_METHOD_REQUIRED_FOR_MERCHANT';
    const BAD_REQUEST_ORDER_ACCOUNT_NUMBER_REQUIRED_FOR_MERCHANT                    = 'BAD_REQUEST_ORDER_ACCOUNT_NUMBER_REQUIRED_FOR_MERCHANT';
    const BAD_REQUEST_ORDER_ACCOUNT_NUMBER_INCORRECT_LENGTH                         = 'BAD_REQUEST_ORDER_ACCOUNT_NUMBER_INCORRECT_LENGTH';
    const BAD_REQUEST_ORDER_BANK_INVALID                                            = 'BAD_REQUEST_ORDER_BANK_INVALID';

    const BAD_REQUEST_PAYMENT_NETBANKING_CANCELLED_BY_USER                          = 'BAD_REQUEST_PAYMENT_NETBANKING_CANCELLED_BY_USER';

    const BAD_REQUEST_REFUND_FAILED                                                 = 'BAD_REQUEST_REFUND_FAILED';
    const BAD_REQUEST_REFUND_NOT_ENOUGH_BALANCE                                     = 'BAD_REQUEST_REFUND_NOT_ENOUGH_BALANCE';

    const BAD_REQUEST_PAYOUT_NOT_ENOUGH_BALANCE                                     = 'BAD_REQUEST_PAYOUT_NOT_ENOUGH_BALANCE';
    const BAD_REQUEST_MERCHANT_FUNDS_ON_HOLD                                        = 'BAD_REQUEST_MERCHANT_FUNDS_ON_HOLD';
    const BAD_REQUEST_MERCHANT_FUNDS_ALREADY_ON_HOLD                                = 'BAD_REQUEST_MERCHANT_FUNDS_ALREADY_ON_HOLD';
    const BAD_REQUEST_MERCHANT_FUNDS_ALREADY_RELEASED                               = 'BAD_REQUEST_MERCHANT_FUNDS_ALREADY_RELEASED';
    const BAD_REQUEST_RECEIPT_EMAILS_ALREADY_ENABLED                                = 'BAD_REQUEST_RECEIPT_EMAILS_ALREADY_ENABLED';
    const BAD_REQUEST_RECEIPT_EMAILS_ALREADY_DISABLED                               = 'BAD_REQUEST_RECEIPT_EMAILS_ALREADY_DISABLED';
    const BAD_REQUEST_INTERNATIONAL_ALREADY_ENABLED                                 = 'BAD_REQUEST_INTERNATIONAL_ALREADY_ENABLED';
    const BAD_REQUEST_INTERNATIONAL_ALREADY_DISABLED                                = 'BAD_REQUEST_INTERNATIONAL_ALREADY_DISABLED';

    const BAD_REQUEST_BATCH_FILE_EXCEED_LIMIT                                       = 'BAD_REQUEST_BATCH_FILE_EXCEED_LIMIT';
    const BAD_REQUEST_BATCH_FILE_EMPTY                                              = 'BAD_REQUEST_BATCH_FILE_EMPTY';
    const BAD_REQUEST_BATCH_FILE_INVALID_TYPE                                       = 'BAD_REQUEST_BATCH_FILE_INVALID_TYPE';
    const BAD_REQUEST_BATCH_FILE_INVALID_PAYMENT_ID                                 = 'BAD_REQUEST_BATCH_FILE_INVALID_PAYMENT_ID';
    const BAD_REQUEST_BATCH_FILE_INVALID_AMOUNT                                     = 'BAD_REQUEST_BATCH_FILE_INVALID_AMOUNT';
    const BAD_REQUEST_BATCH_FILE_INVALID_HEADERS                                    = 'BAD_REQUEST_BATCH_FILE_INVALID_HEADERS';
    const BAD_REQUEST_BATCH_FILE_DUPLICATE_PAYMENT_ID                               = 'BAD_REQUEST_BATCH_FILE_DUPLICATE_PAYMENT_ID';
    const BAD_REQUEST_BATCH_PAYMENT_LINK_FILE_ERRORS                                = 'BAD_REQUEST_BATCH_PAYMENT_LINK_FILE_ERRORS';
    const BAD_REQUEST_BATCH_FILE_ALREADY_PROCESSED                                  = 'BAD_REQUEST_BATCH_FILE_ALREADY_PROCESSED';
    const BAD_REQUEST_BATCH_ANOTHER_OPERATION_IN_PROGRESS                           = 'BAD_REQUEST_BATCH_ANOTHER_OPERATION_IN_PROGRESS';

    const BAD_REQUEST_URL_NOT_FOUND                                                 = 'BAD_REQUEST_URL_NOT_FOUND';
    const BAD_REQUEST_ROUTE_DISABLED                                                = 'BAD_REQUEST_ROUTE_DISABLED';
    const BAD_REQUEST_NOTES_SHOULD_BE_ARRAY                                         = 'BAD_REQUEST_NOTES_SHOULD_BE_ARRAY';
    const BAD_REQUEST_NOTES_TOO_MANY_KEYS                                           = 'BAD_REQUEST_NOTES_TOO_MANY_KEYS';
    const BAD_REQUEST_NOTES_VALUE_CANNOT_BE_ARRAY                                   = 'BAD_REQUEST_NOTES_VALUE_CANNOT_BE_ARRAY';
    const BAD_REQUEST_NOTES_KEY_CANNOT_BE_ARRAY                                     = 'BAD_REQUEST_NOTES_KEY_CANNOT_BE_ARRAY';
    const BAD_REQUEST_NOTES_KEY_TOO_LARGE                                           = 'BAD_REQUEST_NOTES_KEY_TOO_LARGE';
    const BAD_REQUEST_NOTES_VALUE_TOO_LARGE                                         = 'BAD_REQUEST_NOTES_VALUE_TOO_LARGE';
    const BAD_REQUEST_INVALID_TRANSACTION_AMOUNT                                    = 'BAD_REQUEST_INVALID_TRANSACTION_AMOUNT';

    const BAD_REQUEST_UNKNOWN_SCHEDULE                                              = 'BAD_REQUEST_UNKNOWN_SCHEDULE';
    const BAD_REQUEST_INVALID_SCHEDULE                                              = 'BAD_REQUEST_INVALID_SCHEDULE';
    const BAD_REQUEST_SCHEDULE_REQUIRED                                             = 'BAD_REQUEST_SCHEDULE_REQUIRED';
    const BAD_REQUEST_SCHEDULE_INVALID_PERIOD                                       = 'BAD_REQUEST_SCHEDULE_INVALID_PERIOD';
    const BAD_REQUEST_SCHEDULE_ANCHOR_NOT_PERMITTED                                 = 'BAD_REQUEST_SCHEDULE_ANCHOR_NOT_PERMITTED';
    const BAD_REQUEST_SCHEDULE_HOURLY_HOUR_NOT_PERMITTED                            = 'BAD_REQUEST_SCHEDULE_HOURLY_HOUR_NOT_PERMITTED';
    const BAD_REQUEST_SCHEDULE_HOURLY_WITHOUT_INTERVAL                              = 'BAD_REQUEST_SCHEDULE_HOURLY_WITHOUT_INTERVAL';
    const BAD_REQUEST_SCHEDULE_IN_USE                                               = 'BAD_REQUEST_SCHEDULE_IN_USE';

    const BAD_REQUEST_VIRTUAL_ACCOUNT_INVALID_RECEIVER_TYPES                        = 'BAD_REQUEST_VIRTUAL_ACCOUNT_INVALID_RECEIVER_TYPES';
    const BAD_REQUEST_VIRTUAL_ACCOUNT_IDENTICAL_DESCRIPTOR                          = 'BAD_REQUEST_VIRTUAL_ACCOUNT_IDENTICAL_DESCRIPTOR';
    const BAD_REQUEST_VIRTUAL_ACCOUNT_INVALID_DESCRIPTOR_LENGTH                     = 'BAD_REQUEST_VIRTUAL_ACCOUNT_INVALID_DESCRIPTOR_LENGTH';
    const BAD_REQUEST_VIRTUAL_ACCOUNT_UNAVAILABLE                                   = 'BAD_REQUEST_VIRTUAL_ACCOUNT_UNAVAILABLE';
    const BAD_REQUEST_VIRTUAL_ACCOUNT_DESCRIPTOR_SANS_HANDLE                        = 'BAD_REQUEST_VIRTUAL_ACCOUNT_DESCRIPTOR_SANS_HANDLE';

    const BAD_REQUEST_PRICING_ID_REQURED                                            = 'BAD_REQUEST_PRICING_ID_REQURED';
    const BAD_REQUEST_PRICING_PLAN_ALREADY_EXISTS                                   = 'BAD_REQUEST_PRICING_PLAN_ALREADY_EXISTS';
    const BAD_REQUEST_PRICING_RATE_NOT_DEFINED                                      = 'BAD_REQUEST_PRICING_RATE_NOT_DEFINED';
    const BAD_REQUEST_PRICING_GATEWAY_REQUIRED                                      = 'BAD_REQUEST_PRICING_GATEWAY_REQUIRED';
    const BAD_REQUEST_PRICING_RULE_ALREADY_DEFINED                                  = 'BAD_REQUEST_PRICING_RULE_ALREADY_DEFINED';
    const BAD_REQUEST_PRICING_PLAN_WITH_SAME_NAME_EXISTS                            = 'BAD_REQUEST_PRICING_PLAN_WITH_SAME_NAME_EXISTS';
    const BAD_REQUEST_PRICING_NOT_DEFINED_FOR_MERCHANT                              = 'BAD_REQUEST_PRICING_NOT_DEFINED_FOR_MERCHANT';
    const BAD_REQUEST_PRICING_FIELD_NOT_REQUIRED_FOR_NB                             = 'BAD_REQUEST_PRICING_FIELD_NOT_REQUIRED_FOR_NB';
    const BAD_REQUEST_PRICING_RULE_FOR_AMEX_NOT_PRESENT                             = 'BAD_REQUEST_PRICING_RULE_FOR_AMEX_NOT_PRESENT';
    const BAD_REQUEST_PRICING_RULE_FOR_AMOUNT_RANGE_OVERLAP                         = 'BAD_REQUEST_PRICING_RULE_FOR_AMOUNT_RANGE_OVERLAP';

    const BAD_REQUEST_MERCHANT_RECURRING_PAYMENTS_NOT_SUPPORTED                     = 'BAD_REQUEST_MERCHANT_RECURRING_PAYMENTS_NOT_SUPPORTED';
    const BAD_REQUEST_MERCHANT_ALREADY_ACTIVATED                                    = 'BAD_REQUEST_MERCHANT_ALREADY_ACTIVATED';
    const BAD_REQUEST_MERCHANT_NOT_ACTIVATED                                        = 'BAD_REQUEST_MERCHANT_NOT_ACTIVATED';
    const BAD_REQUEST_MERCHANT_ALREADY_ARCHIVED                                     = 'BAD_REQUEST_MERCHANT_ALREADY_ARCHIVED';
    const BAD_REQUEST_MERCHANT_NOT_ARCHIVED                                         = 'BAD_REQUEST_MERCHANT_NOT_ARCHIVED';
    const BAD_REQUEST_MERCHANT_CANNOT_BE_ARCHIVED                                   = 'BAD_REQUEST_MERCHANT_CANNOT_BE_ARCHIVED';
    const BAD_REQUEST_MERCHANT_ALREADY_SUSPENDED                                    = 'BAD_REQUEST_MERCHANT_ALREADY_SUSPENDED';
    const BAD_REQUEST_MERCHANT_NOT_SUSPENDED                                        = 'BAD_REQUEST_MERCHANT_NOT_SUSPENDED';
    const BAD_REQUEST_MERCHANT_ACTION_NOT_SUPPORTED                                 = 'BAD_REQUEST_MERCHANT_ACTION_NOT_SUPPORTED';
    const BAD_REQUEST_MERCHANT_DETAIL_DOES_NOT_EXISTS                               = 'BAD_REQUEST_MERCHANT_DETAIL_DOES_NOT_EXISTS';
    const BAD_REQUEST_MERCHANT_NO_TERMINAL_ASSIGNED                                 = 'BAD_REQUEST_MERCHANT_NO_TERMINAL_ASSIGNED';
    const BAD_REQUEST_MERCHANT_KEY_ALREADY_CREATED                                  = 'BAD_REQUEST_MERCHANT_KEY_ALREADY_CREATED';
    const BAD_REQUEST_MERCHANT_NOT_ACTIVATED_KEY_CREATE_FAILED                      = 'BAD_REQUEST_MERCHANT_NOT_ACTIVATED_KEY_CREATE_FAILED';
    const BAD_REQUEST_MERCHANT_ALREADY_LIVE                                         = 'BAD_REQUEST_MERCHANT_ALREADY_LIVE';
    const BAD_REQUEST_MERCHANT_NOT_LIVE                                             = 'BAD_REQUEST_MERCHANT_NOT_LIVE';
    const BAD_REQUEST_MERCHANT_NOT_LIVE_ACTION_DENIED                               = 'BAD_REQUEST_MERCHANT_NOT_LIVE_ACTION_DENIED';
    const BAD_REQUEST_MERCHANT_TERMINAL_EXISTS_FOR_GATEWAY                          = 'BAD_REQUEST_MERCHANT_TERMINAL_EXISTS_FOR_GATEWAY';
    const BAD_REQUEST_MERCHANT_NO_BANK_ACCOUNT_FOUND                                = 'BAD_REQUEST_MERCHANT_NO_BANK_ACCOUNT_FOUND';
    const BAD_REQUEST_MERCHANT_BANK_ACCOUNT_ALREADY_PROVIDED                        = 'BAD_REQUEST_MERCHANT_BANK_ACCOUNT_ALREADY_PROVIDED';
    const BAD_REQUEST_MERCHANT_LOGO_TOO_BIG                                         = 'BAD_REQUEST_MERCHANT_LOGO_TOO_BIG';
    const BAD_REQUEST_MERCHANT_LOGO_NOT_SQUARE                                      = 'BAD_REQUEST_MERCHANT_LOGO_NOT_SQUARE';
    const BAD_REQUEST_MERCHANT_LOGO_NOT_IMAGE                                       = 'BAD_REQUEST_MERCHANT_LOGO_NOT_IMAGE';
    const BAD_REQUEST_LOGO_NOT_PRESENT                                              = 'BAD_REQUEST_LOGO_NOT_PRESENT';
    const BAD_REQUEST_MERCHANT_LOGO_TOO_SMALL                                       = 'BAD_REQUEST_MERCHANT_LOGO_TOO_SMALL';
    const BAD_REQUEST_MERCHANT_INVALID                                              = 'BAD_REQUEST_MERCHANT_INVALID';
    const BAD_REQUEST_MERCHANT_UNEDITABLE_FEATURE                                   = 'BAD_REQUEST_MERCHANT_UNEDITABLE_FEATURE';
    const BAD_REQUEST_MERCHANT_FEATURE_UNEDITABLE_IN_LIVE                           = 'BAD_REQUEST_MERCHANT_FEATURE_UNEDITABLE_IN_LIVE';
    const BAD_REQUEST_MERCHANT_FEATURE_ALREADY_ASSIGNED                             = 'BAD_REQUEST_MERCHANT_FEATURE_ALREADY_ASSIGNED';
    const BAD_REQUEST_MERCHANT_DETAIL_ALREADY_LOCKED                                = 'BAD_REQUEST_MERCHANT_DETAIL_ALREADY_LOCKED';
    const BAD_REQUEST_MERCHANT_DETAIL_FILE_TYPE                                     = 'BAD_REQUEST_MERCHANT_DETAIL_FILE_TYPE';
    const BAD_REQUEST_MERCHANT_HANDLE_UPPERCASE_ONLY                                = 'BAD_REQUEST_MERCHANT_HANDLE_UPPERCASE_ONLY';
    const BAD_REQUEST_MERCHANT_UNARCHIVE_BEFORE_ACTIVATION                          = 'BAD_REQUEST_MERCHANT_UNARCHIVE_BEFORE_ACTIVATION';

    const BAD_REQUEST_SHARED_TERMINAL_CANNOT_BE_COPIED                              = 'BAD_REQUEST_SHARED_TERMINAL_CANNOT_BE_COPIED';
    const BAD_REQUEST_SHARED_TERMINAL_MERCHANT_CANNOT_BE_CHANGED                    = 'BAD_REQUEST_SHARED_TERMINAL_MERCHANT_CANNOT_BE_CHANGED';
    const BAD_REQUEST_SUB_MERCHANT_ALREADY_ASSIGNED_TO_TERMINAL                     = 'BAD_REQUEST_SUB_MERCHANT_ALREADY_ASSIGNED_TO_TERMINAL';
    const BAD_REQUEST_SUB_MERCHANT_EMAIL_SAME_AS_PARENT_EMAIL                       = 'BAD_REQUEST_SUB_MERCHANT_EMAIL_SAME_AS_PARENT_EMAIL';

    const BAD_REQUEST_GATEWAY_TERMINAL_MAX_LIMIT_REACHED                            = 'BAD_REQUEST_GATEWAY_TERMINAL_MAX_LIMIT_REACHED';
    const BAD_REQUEST_GATEWAY_MERCHANT_ID_EXISTS                                    = 'BAD_REQUEST_GATEWAY_MERCHANT_ID_EXISTS';
    const BAD_REQUEST_GATEWAY_CANNOT_TOPUP                                          = 'BAD_REQUEST_GATEWAY_CANNOT_TOPUP';

    const BAD_REQUEST_KEY_EXPIRED                                                   = 'BAD_REQUEST_KEY_EXPIRED';
    const BAD_REQUEST_KEY_EXPIRING_SOON                                             = 'BAD_REQUEST_KEY_EXPIRING_SOON';
    const BAD_REQUEST_KEY_OF_DEMO_ACCOUNT                                           = 'BAD_REQUEST_KEY_OF_DEMO_ACCOUNT';

    const BAD_REQUEST_PAYMENT_VERIFICATION_FAILED                                   = 'BAD_REQUEST_PAYMENT_VERIFICATION_FAILED';

    const BAD_REQUEST_INVALID_CHECKOUT_ID                                           = 'BAD_REQUEST_INVALID_CHECKOUT_ID';
    const BAD_REQUEST_INVALID_PLATFORM                                              = 'BAD_REQUEST_INVALID_PLATFORM';
    const BAD_REQUEST_INVALID_LIBRARY                                               = 'BAD_REQUEST_INVALID_LIBRARY';
    const BAD_REQUEST_INVALID_BROWSER                                               = 'BAD_REQUEST_INVALID_BROWSER';
    const BAD_REQUEST_INVALID_OS                                                    = 'BAD_REQUEST_INVALID_OS';
    const BAD_REQUEST_INVALID_DEVICE                                                = 'BAD_REQUEST_INVALID_DEVICE';
    const BAD_REQUEST_INVALID_INTEGRATION                                           = 'BAD_REQUEST_INVALID_INTEGRATION';

    const SERVER_ERROR_INVALID_ARGUMENT                                             = 'SERVER_ERROR_INVALID_ARGUMENT';
    const SERVER_ERROR_DB_QUERY_FAILED                                              = 'SERVER_ERROR_DB_QUERY_FAILED';
    const SERVER_ERROR_LOGICAL_ERROR                                                = 'SERVER_ERROR_LOGICAL_ERROR';
    const SERVER_ERROR_AMOUNT_TAMPERED                                              = 'SERVER_ERROR_AMOUNT_TAMPERED';
    const SERVER_ERROR_INTEGRATION_ERROR                                            = 'SERVER_ERROR_INTEGRATION_ERROR';
    const SERVER_ERROR_SETTLEMENTS_FAILED                                           = 'SERVER_ERROR_SETTLEMENTS_FAILED';
    const SERVER_ERROR_RUNTIME_ERROR                                                = 'SERVER_ERROR_RUNTIME_ERROR';
    const SERVER_ERROR_ASSERTION_ERROR                                              = 'SERVER_ERROR_ASSERTION_ERROR';
    const SERVER_ERROR_PAYMENT_ABORTED                                              = 'SERVER_ERROR_PAYMENT_ABORTED';
    const SERVER_ERROR_TO_STRING_EXCEPTION                                          = 'SERVER_ERROR_TO_STRING_EXCEPTION';
    const SERVER_ERROR_MYSQL_ENTRY_NOT_FOUND                                        = 'SERVER_ERROR_MYSQL_ENTRY_NOT_FOUND';
    const SERVER_ERROR_AWS_FAILURE                                                  = 'SERVER_ERROR_AWS_FAILURE';
    const SERVER_ERROR_PRICING_RULE_ABSENT                                          = 'SERVER_ERROR_PRICING_RULE_ABSENT';
    const SERVER_ERROR_MISSING_HANDLER                                              = 'SERVER_ERROR_MISSING_HANDLER';
    const SERVER_ERROR_CARD_NUMBER_LOGGED                                           = 'SERVER_ERROR_CARD_NUMBER_LOGGED';
    const SERVER_ERROR_INVOICE_ID_EMPTY                                             = 'SERVER_ERROR_INVOICE_ID_EMPTY';
    const SERVER_ERROR_INVALID_DURATION                                             = 'SERVER_ERROR_INVALID_DURATION';
    const SERVER_ERROR_MULTIPLE_REFUNDS_FOUND                                       = 'SERVER_ERROR_MULTIPLE_REFUNDS_FOUND';
    const SERVER_ERROR_GATEWAY_NOT_REFUNDED                                         = 'SERVER_ERROR_GATEWAY_NOT_REFUNDED';
    const SERVER_ERROR_INCORRECT_NUMBER_OF_INVOICES_FOUND                           = 'SERVER_ERROR_INCORRECT_NUMBER_OF_INVOICES_FOUND';
    const SERVER_ERROR_REDIS_EXCEPTION                                              = 'SERVER_ERROR_REDIS_EXCEPTION';
    const SERVER_ERROR_SUBSCRIPTION_PAYMENT_NOT_CAPTURED                            = 'SERVER_ERROR_SUBSCRIPTION_PAYMENT_NOT_CAPTURED';
    const SERVER_ERROR_APP_TOKEN_NOT_PRESENT                                        = 'SERVER_ERROR_APP_TOKEN_NOT_PRESENT';
    const SERVER_ERROR_MULTIPLE_SUCCESS_TRANSACTIONS_IN_VERIFY                      = 'SERVER_ERROR_MULTIPLE_SUCCESS_TRANSACTIONS_IN_VERIFY';
    const SERVER_ERROR_GATEWAY_TOKENS_INVALID_COUNT                                 = 'SERVER_ERROR_GATEWAY_TOKENS_INVALID_COUNT';
    const SERVER_ERROR_PERIOD_NOT_UNANCHORED                                        = 'SERVER_ERROR_PERIOD_NOT_UNANCHORED';
    const SERVER_ERROR_PERIOD_NOT_ANCHORED                                          = 'SERVER_ERROR_PERIOD_NOT_ANCHORED';
    const SERVER_ERROR_LOG_RISK                                                     = 'SERVER_ERROR_LOG_RISK';
    const SERVER_ERROR_INVALID_RESPONSE                                             = 'SERVER_ERROR_INVALID_RESPONSE';
    const SERVER_ERROR_TOKEN_INVALID_RECURRING_STATUS                               = 'SERVER_ERROR_TOKEN_INVALID_RECURRING_STATUS';
    const SERVER_ERROR_ES_OPERATION_ERRORED                                         = 'SERVER_ERROR_ES_OPERATION_ERRORED';
    const SERVER_ERROR_GATEWAY_FILE_GENERATION_ERROR                                = 'SERVER_ERROR_GATEWAY_FILE_GENERATION_ERROR';
    const SERVER_ERROR_SUBSCRIPTION_NOT_PENDING                                     = 'SERVER_ERROR_SUBSCRIPTION_NOT_PENDING';
    const SERVER_ERROR_TOO_MANY_SUBSCRIPTION_INVOICES_FOUND                         = 'SERVER_ERROR_TOO_MANY_SUBSCRIPTION_INVOICES_FOUND';
    const SERVER_ERROR_SUBSCRIPTION_INVOICE_BAD_STATUS                              = 'SERVER_ERROR_SUBSCRIPTION_INVOICE_BAD_STATUS';
    const SERVER_ERROR_SUBSCRIPTION_WRONG_STATUS_UPDATE                             = 'SERVER_ERROR_SUBSCRIPTION_WRONG_STATUS_UPDATE';
    const SERVER_ERROR_SUBSCRIPTION_WRONG_STATUS_UPDATED_FROM                       = 'SERVER_ERROR_SUBSCRIPTION_WRONG_STATUS_UPDATED_FROM';
    const SERVER_ERROR_SUBSCRIPTION_INVOICE_COUNT_MISMATCH_TOTAL_COUNT              = 'SERVER_ERROR_SUBSCRIPTION_INVOICE_COUNT_MISMATCH_TOTAL_COUNT';

    const SERVER_ERROR_GATEWAY_FILE_NO_DATA_FOUND                                   = 'SERVER_ERROR_GATEWAY_FILE_NO_DATA_FOUND';
    const SERVER_ERROR_GATEWAY_FILE_ERROR_GENERATING_FILE                           = 'SERVER_ERROR_GATEWAY_FILE_ERROR_GENERATING_FILE';
    const SERVER_ERROR_GATEWAY_FILE_ERROR_SENDING_FILE                              = 'SERVER_ERROR_GATEWAY_FILE_ERROR_SENDING_FILE';
    const SERVER_ERROR_GATEWAY_FILE_CLAIMS_LESSER_THAN_REFUNDS                      = 'SERVER_ERROR_GATEWAY_FILE_CLAIMS_LESSER_THAN_REFUNDS';

    const SERVER_ERROR_AUTH_SERVICE_FAILURE                                         = 'SERVER_ERROR_AUTH_SERVICE_FAILURE';
    const SERVER_ERROR_WEBHOOK_IN_TRANSACTION                                       = 'SERVER_ERROR_WEBHOOK_IN_TRANSACTION';

    const BAD_REQUEST_CUSTOMER_ALREADY_EXISTS                                       = 'BAD_REQUEST_CUSTOMER_ALREADY_EXISTS';
    const BAD_REQUEST_CUSTOMER_CONTACT_REQUIRED                                     = 'BAD_REQUEST_CUSTOMER_CONTACT_REQUIRED';
    const BAD_REQUEST_CUSTOMER_CARD_ALREADY_EXISTS                                  = 'BAD_REQUEST_CUSTOMER_CARD_ALREADY_EXISTS';
    const BAD_REQUEST_CUSTOMER_BANK_ALREADY_EXISTS                                  = 'BAD_REQUEST_CUSTOMER_BANK_ALREADY_EXISTS';
    const BAD_REQUEST_CUSTOMER_WALLET_ALREADY_EXISTS                                = 'BAD_REQUEST_CUSTOMER_WALLET_ALREADY_EXISTS';
    const BAD_REQUEST_CUSTOMER_DUPLICATE_NOT_GLOBAL                                 = 'BAD_REQUEST_CUSTOMER_DUPLICATE_NOT_GLOBAL';
    const BAD_REQUEST_GLOBAL_CUSTOMER_MISMATCH                                      = 'BAD_REQUEST_GLOBAL_CUSTOMER_MISMATCH';
    const BAD_REQUEST_GATEWAY_TOKEN_EMPTY                                           = 'BAD_REQUEST_GATEWAY_TOKEN_EMPTY';
    const BAD_REQUEST_TOKEN_NOT_ENABLED_FOR_RECURRING                               = 'BAD_REQUEST_TOKEN_NOT_ENABLED_FOR_RECURRING';
    const BAD_REQUEST_NB_TOKEN_PASSED_IN_FIRST_RECURRING                            = 'BAD_REQUEST_NB_TOKEN_PASSED_IN_FIRST_RECURRING';
    const BAD_REQUEST_NB_UNCONFIRMED_TOKEN_PASSED_IN_SECOND_RECURRING               = 'BAD_REQUEST_NB_UNCONFIRMED_TOKEN_PASSED_IN_SECOND_RECURRING';

    const BAD_REQUEST_RECONCILIATION                                                = 'BAD_REQUEST_RECONCILIATION';
    const BAD_REQUEST_PAYMENT_ACCOUNT_INSUFFICIENT_BALANCE                          = 'BAD_REQUEST_PAYMENT_ACCOUNT_INSUFFICIENT_BALANCE';

    const BAD_REQUEST_MAXIMUM_SMS_LIMIT_REACHED                                     = 'BAD_REQUEST_MAXIMUM_SMS_LIMIT_REACHED';
    const BAD_REQUEST_OTP_MAXIMUM_ATTEMPTS_REACHED                                  = 'BAD_REQUEST_OTP_MAXIMUM_ATTEMPTS_REACHED';
    const BAD_REQUEST_INCORRECT_OTP                                                 = 'BAD_REQUEST_INCORRECT_OTP';
    const BAD_REQUEST_SMS_FAILED                                                    = 'BAD_REQUEST_SMS_FAILED';
    const BAD_REQUEST_INVALID_COUNTRY                                               = 'BAD_REQUEST_INVALID_COUNTRY';

    // Heimdall Error Codes
    const BAD_REQUEST_ACCESS_DENIED                                                 = 'BAD_REQUEST_ACCESS_DENIED';

    const BAD_REQUEST_ROLE_NOT_ASSIGNED                                             = 'BAD_REQUEST_ROLE_NOT_ASSIGNED';
    const BAD_REQUEST_MERCHANT_NOT_ASSIGNED                                         = 'BAD_REQUEST_MERCHANT_NOT_ASSIGNED';
    const BAD_REQUEST_PASSWORD_EXPIRED                                              = 'BAD_REQUEST_PASSWORD_EXPIRED';

    const BAD_REQUEST_SETTLEMENT_ANOTHER_OPERATION_IN_PROGRESS                      = 'BAD_REQUEST_SETTLEMENT_ANOTHER_OPERATION_IN_PROGRESS';
    const BAD_REQUEST_SETTLEMENT_RECONCILIATION_IN_PROGRESS                         = 'BAD_REQUEST_SETTLEMENT_RECONCILIATION_IN_PROGRESS';

    const BAD_REQUEST_INVALID_MERCHANT_INVOICE_NUMBER                               = 'BAD_REQUEST_INVALID_MERCHANT_INVOICE_NUMBER';

    const BAD_REQUEST_PAYOUT_ANOTHER_OPERATION_IN_PROGRESS                          = 'BAD_REQUEST_PAYOUT_ANOTHER_OPERATION_IN_PROGRESS';

    const BAD_REQUEST_INVALID_MAILGUN_WEBHOOK_TYPE                                  = 'BAD_REQUEST_INVALID_MAILGUN_WEBHOOK_TYPE';
    const BAD_REQUEST_INVALID_MAILGUN_SIGNATURE                                     = 'BAD_REQUEST_INVALID_MAILGUN_SIGNATURE';

    const BAD_REQUEST_DUPLICATE_INVOICE_RECEIPT                                     = 'BAD_REQUEST_DUPLICATE_INVOICE_RECEIPT';
    const BAD_REQUEST_INVOICE_EXPIRE_FAILED                                         = 'BAD_REQUEST_INVOICE_EXPIRE_FAILED';
    const BAD_REQUEST_API_KEY_NOT_PRESENT                                           = 'BAD_REQUEST_API_KEY_NOT_PRESENT';
    const BAD_REQUEST_INVOICE_FEE_BEARER_CUSTOMER                                   = 'BAD_REQUEST_INVOICE_FEE_BEARER_CUSTOMER';
    const BAD_REQUEST_PAYMENT_LINK_BATCH_ISSUED_ALREADY                             = 'BAD_REQUEST_PAYMENT_LINK_BATCH_ISSUED_ALREADY';

    const BAD_REQUEST_ITEM_INACTIVE                                                 = 'BAD_REQUEST_ITEM_INACTIVE';
    const BAD_REQUEST_ITEM_EDIT_NOT_ALLOWED                                         = 'BAD_REQUEST_ITEM_EDIT_NOT_ALLOWED';
    const BAD_REQUEST_INCOMPATIBLE_ITEM_TYPE                                        = 'BAD_REQUEST_INCOMPATIBLE_ITEM_TYPE';
    const BAD_REQUEST_INVALID_ITEM_TAX_DETAILS                                      = 'BAD_REQUEST_INVALID_ITEM_TAX_DETAILS';
    const BAD_REQUEST_LINK_TYPE_HAS_NO_TAXATION                                     = 'BAD_REQUEST_LINK_TYPE_HAS_NO_TAXATION';

    const BAD_REQUEST_PAYMENT_TRANSFER_AMOUNT_GREATER_THAN_CAPTURED                 = 'BAD_REQUEST_PAYMENT_TRANSFER_AMOUNT_GREATER_THAN_CAPTURED';
    const BAD_REQUEST_PAYMENT_TRANSFER_AMOUNT_GREATER_THAN_UNTRANSFERRED            = 'BAD_REQUEST_PAYMENT_TRANSFER_AMOUNT_GREATER_THAN_UNTRANSFERRED';
    const BAD_REQUEST_PAYMENT_TRANSFER_ENTITIES_NOT_SET                             = 'BAD_REQUEST_PAYMENT_TRANSFER_ENTITIES_NOT_SET';
    const BAD_REQUEST_PAYMENT_TRANSFER_MORE_THAN_ONE_CUSTOMER                       = 'BAD_REQUEST_PAYMENT_TRANSFER_MORE_THAN_ONE_CUSTOMER';
    const BAD_REQUEST_PAYMENT_TRANSFER_MULTIPLE_ENTITY_TYPES_GIVEN                  = 'BAD_REQUEST_PAYMENT_TRANSFER_MULTIPLE_ENTITY_TYPES_GIVEN';
    const BAD_REQUEST_PAYMENT_TRANSFER_NOT_ENOUGH_BALANCE                           = 'BAD_REQUEST_PAYMENT_TRANSFER_NOT_ENOUGH_BALANCE';
    const BAD_REQUEST_PAYMENT_TRANSFER_CURRENCY_MISMATCH                            = 'BAD_REQUEST_PAYMENT_TRANSFER_CURRENCY_MISMATCH';

    const BAD_REQUEST_TRANSFER_INVALID_ACCOUNT_ID                                   = 'BAD_REQUEST_TRANSFER_INVALID_ACCOUNT_ID';
    const BAD_REQUEST_TRANSFER_ACCOUNT_NOT_ACTIVATED                                = 'BAD_REQUEST_TRANSFER_ACCOUNT_NOT_ACTIVATED';
    const BAD_REQUEST_TRANSFER_REVERSAL_AMOUNT_GREATER_THAN_TRANSFERRED             = 'BAD_REQUEST_TRANSFER_REVERSAL_AMOUNT_GREATER_THAN_TRANSFERRED';
    const BAD_REQUEST_TRANSFER_REVERSAL_AMOUNT_GREATER_THAN_UNREVERSED              = 'BAD_REQUEST_TRANSFER_REVERSAL_AMOUNT_GREATER_THAN_UNREVERSED';
    const BAD_REQUEST_TRANSFER_REVERSAL_INSUFFICIENT_BALANCE                        = 'BAD_REQUEST_TRANSFER_REVERSAL_INSUFFICIENT_BALANCE';

    const BAD_REQUEST_UPDATE_ON_HOLD_ALREADY_SETTLED                                = 'BAD_REQUEST_UPDATE_ON_HOLD_ALREADY_SETTLED';

    const BAD_REQUEST_INVALID_ADMIN_EMAIL                                           = 'BAD_REQUEST_INVALID_ADMIN_EMAIL';
    const BAD_REQUEST_INVALID_ADMIN_EMAIL_HOSTNAME                                  = 'BAD_REQUEST_INVALID_ADMIN_EMAIL_HOSTNAME';
    const BAD_REQUEST_AUTHENTICATION_FAILED                                         = 'BAD_REQUEST_AUTHENTICATION_FAILED';
    const BAD_REQUEST_USER_ACCOUNT_LOCKED                                           = 'BAD_REQUEST_USER_ACCOUNT_LOCKED';
    const BAD_REQUEST_USER_ACCOUNT_DISABLED                                         = 'BAD_REQUEST_USER_ACCOUNT_DISABLED';
    const BAD_REQUEST_USER_NOT_AUTHENTICATED                                        = 'BAD_REQUEST_USER_NOT_AUTHENTICATED';
    const BAD_REQUEST_USER_NOT_FOUND                                                = 'BAD_REQUEST_USER_NOT_FOUND';
    const BAD_REQUEST_USER_ROLE_INVALID                                             = 'BAD_REQUEST_USER_ROLE_INVALID';

    const BAD_REQUEST_INVITATION_USER_ALREADY_INVITED                               = 'BAD_REQUEST_INVITATION_USER_ALREADY_INVITED';
    const BAD_REQUEST_INVITATION_USER_ALREADY_MEMBER                                = 'BAD_REQUEST_INVITATION_USER_ALREADY_MEMBER';

    const BAD_REQUEST_AUTH_VALIDATION_FAILED                                        = 'BAD_REQUEST_AUTH_VALIDATION_FAILED';
    const BAD_REQUEST_ADMIN_SELF_EDIT_PROHIBITED                                    = 'BAD_REQUEST_ADMIN_SELF_EDIT_PROHIBITED';
    const BAD_REQUEST_ADMIN_SELF_INVITE_PROHIBITED                                  = 'BAD_REQUEST_ADMIN_SELF_INVITE_PROHIBITED';
    const BAD_REQUEST_SUPERADMIN_ROLE_NOT_EDITABLE                                  = 'BAD_REQUEST_SUPERADMIN_ROLE_NOT_EDITABLE';
    const BAD_REQUEST_INVALID_PERMISSIONS_USAGE                                     = 'BAD_REQUEST_INVALID_PERMISSIONS_USAGE';
    const BAD_REQUEST_WORKFLOW_PERMISSIONS_CANNOT_BE_REMOVED                        = 'BAD_REQUEST_WORKFLOW_PERMISSIONS_CANNOT_BE_REMOVED';
    const BAD_REQUEST_WORKFLOW_PERMISSION_EXISTS                                    = 'BAD_REQUEST_WORKFLOW_PERMISSION_EXISTS';
    const BAD_REQUEST_PERMISSION_DISABLED_FOR_WORKFLOW                              = 'BAD_REQUEST_PERMISSION_DISABLED_FOR_WORKFLOW';
    const BAD_REQUEST_WORKFLOW_STEP_OP_MISMATCH                                     = 'BAD_REQUEST_WORKFLOW_STEP_OP_MISMATCH';
    const BAD_REQUEST_WORKFLOW_DUTY_TYPE_INVALID                                    = 'BAD_REQUEST_WORKFLOW_DUTY_TYPE_INVALID';

    const BAD_REQUEST_SUPERADMIN_ACCESS_REQUIRED                                    = 'BAD_REQUEST_SUPERADMIN_ACCESS_REQUIRED';

    const BAD_REQUEST_CASHBACK_CRITERIA_MISSING                                     = 'BAD_REQUEST_CASHBACK_CRITERIA_MISSING';
    const BAD_REQUEST_INVALID_OFFER_DURATION                                        = 'BAD_REQUEST_INVALID_OFFER_DURATION';
    const BAD_REQUEST_OFFER_ALREADY_EXISTS                                          = 'BAD_REQUEST_OFFER_ALREADY_EXISTS';
    const BAD_REQUEST_FLAT_CASHBACK_WITH_PERCENT_RATE_OR_MAX_CASHBACK               = 'BAD_REQUEST_FLAT_CASHBACK_WITH_PERCENT_RATE_OR_MAX_CASHBACK';
    const BAD_REQUEST_IINS_EDITABLE_FOR_CARD_OFFER                                  = 'BAD_REQUEST_IINS_EDITABLE_FOR_CARD_OFFER';
    const BAD_REQUEST_OFFER_ALREADY_DEACTIVATED                                     = 'BAD_REQUEST_OFFER_ALREADY_DEACTIVATED';

    const BAD_REQUEST_FEE_BREAKUP_CREATION_FAILED                                   = 'BAD_REQUEST_FEE_BREAKUP_CREATION_FAILED';

    const BAD_REQUEST_API_CAPTURE_FAILED                                            = 'BAD_REQUEST_API_CAPTURE_FAILED';

    // Workflow Related ErrorCodes
    const BAD_REQUEST_WORKFLOW_INVALID_ACTION_STATE                                 = 'BAD_REQUEST_WORKFLOW_INVALID_ACTION_STATE';
    const BAD_REQUEST_WORKFLOW_INVALID_CHECKER                                      = 'BAD_REQUEST_WORKFLOW_INVLID_CHECKER';
    const BAD_REQUEST_WORKFLOW_ACTION_NOT_FOUND                                     = 'BAD_REQUEST_WORKFLOW_ACTION_NOT_FOUND';
    const BAD_REQUEST_WORKFLOW_ACTION_CLOSE_NOT_AUTHORIZED                          = 'BAD_REQUEST_WORKFLOW_ACTION_CLOSE_NOT_AUTHORIZED';
    const BAD_REQUEST_ACTION_INVALID_TYPE                                           = 'BAD_REQUEST_ACTION_INVALID_TYPE';
    const BAD_REQUEST_ACTION_INVALID_METHOD                                         = 'BAD_REQUEST_ACTION_INVALID_METHOD';
    const BAD_REQUEST_ACTION_NOT_APPROVED                                           = 'BAD_REQUEST_ACTION_NOT_APPROVED';
    const BAD_REQUEST_ACTION_ALREADY_EXECUTED                                       = 'BAD_REQUEST_ACTION_ALREADY_EXECUTED';
    const BAD_REQUEST_WORKFLOW_DELETE_NOT_ALLOWED                                   = 'BAD_REQUEST_WORKFLOW_DELETE_NOT_ALLOWED';
    const BAD_REQUEST_WORKFLOW_STEP_LEVEL_SEQUENCE                                  = 'BAD_REQUEST_WORKFLOW_STEP_LEVEL_SEQUENCE';
    const BAD_REQUEST_WORKFLOW_STEP_ROLE_LEVEL_UNIQUE                               = 'BAD_REQUEST_WORKFLOW_STEP_ROLE_LEVEL_UNIQUE';
    const BAD_REQUEST_WORKFLOW_ENTITY_NOT_FOUND                                     = 'BAD_REQUEST_WORKFLOW_ENTITY_NOT_FOUND';
    const BAD_REQUEST_WORKFLOW_ENTITY_ID_NOT_FOUND                                  = 'BAD_REQUEST_WORKFLOW_ENTITY_ID_NOT_FOUND';
    const BAD_REQUEST_WORKFLOW_ANOTHER_ACTION_IN_PROGRESS                           = 'BAD_REQUEST_WORKFLOW_ANOTHER_ACTION_IN_PROGRESS';
    const BAD_REQUEST_CHECK_NOT_REQUIRED_IN_CURRENT_LEVEL                           = 'BAD_REQUEST_CHECK_NOT_REQUIRED_IN_CURRENT_LEVEL';
    const BAD_REQUEST_ACTION_NOT_IN_OPEN_STATES                                     = 'BAD_REQUEST_ACTION_NOT_IN_OPEN_STATES';
    const BAD_REQUEST_WORKFLOW_ACTION_CLOSE_UNAUTHORIZED                            = 'BAD_REQUEST_WORKFLOW_ACTION_CLOSE_UNAUTHORIZED';
    const BAD_REQUEST_WORKFLOW_ACTION_CLOSED                                        = 'BAD_REQUEST_WORKFLOW_ACTION_CLOSED';
    const BAD_REQUEST_WORKFLOW_STEPS_CANNOT_BE_EDITED                               = 'BAD_REQUEST_WORKFLOW_STEPS_CANNOT_BE_EDITED';

    // Gateway Priority API error codes
    const BAD_REQUEST_INVALID_PAYMENT_METHOD                                        = 'BAD_REQUEST_INVALID_PAYMENT_METHOD';
    const BAD_REQUEST_INVALID_GATEWAY_FOR_METHOD                                    = 'BAD_REQUEST_INVALID_GATEWAY_FOR_METHOD';

    // ES related error codes
    const BAD_REQUEST_ES_DEBUG_METHOD_NOT_VALID                                     = 'BAD_REQUEST_ES_DEBUG_METHOD_NOT_VALID';

    // Error code for data missing during force authorize flow
    const BAD_REQUEST_PAYMENT_AUTH_DATA_MISSING                                     = 'BAD_REQUEST_PAYMENT_AUTH_DATA_MISSING';

    // File store
    const BAD_REQUEST_FILE_NOT_FOUND                                                = 'BAD_REQUEST_FILE_NOT_FOUND';

    const BAD_REQUEST_MERCHANT_USER_ACTION_NOT_SUPPORTED                            = 'BAD_REQUEST_MERCHANT_USER_ACTION_NOT_SUPPORTED';

    const BAD_REQUEST_TOTAL_LOAD_EXCEEDS_MAX_LOAD                                   = 'BAD_REQUEST_TOTAL_LOAD_EXCEEDS_MAX_LOAD';

    const BAD_REQUEST_INVALID_OAUTH_MAIL_TYPE                                       = 'BAD_REQUEST_INVALID_OAUTH_MAIL_TYPE';
    const BAD_REQUEST_AUTH_SERVICE_ERROR                                            = 'BAD_REQUEST_AUTH_SERVICE_ERROR';

    const BAD_REQUEST_COUPON_LIMIT_REACHED                                          = 'BAD_REQUEST_COUPON_LIMIT_REACHED';
    const BAD_REQUEST_COUPON_ALREADY_USED                                           = 'BAD_REQUEST_COUPON_ALREADY_USED';
    const BAD_REQUEST_COUPON_NOT_VALID_FOR_MERCHANT                                 = 'BAD_REQUEST_COUPON_NOT_VALID_FOR_MERCHANT';
    const BAD_REQUEST_COUPON_NOT_APPLICABLE                                         = 'BAD_REQUEST_COUPON_NOT_APPLICABLE';
    const BAD_REQUEST_COUPON_EXPIRED                                                = 'BAD_REQUEST_COUPON_EXPIRED';
    const BAD_REQUEST_INVALID_COUPON_CODE                                           = 'BAD_REQUEST_INVALID_COUPON_CODE';

    const BAD_REQUEST_SNS_PUBLISH_FAILED                                            = 'BAD_REQUEST_SNS_PUBLISH_FAILED';

    const BAD_REQUEST_ADMIN_TOKEN_MISMATCH                                          = 'BAD_REQUEST_ADMIN_TOKEN_MISMATCH';
    const BAD_REQUEST_GATEWAY_FILE_NON_RETRIABLE                                    = 'BAD_REQUEST_GATEWAY_FILE_NON_RETRIABLE';
}
