<?php

namespace RZP\Error;

class ErrorCode
{
    /**
     * The error codes are named such that the first and the second word
     * tells the error category.
     */

    /**
     * All internal un-explained and sudden errors are encapsulated
     * by the following error code.
     */
    const SERVER_ERROR                                                              = 'SERVER_ERROR';

    /**
     * General gateway specific error codes
     * Isn't specific to one particular gateway and
     * should be generally valid for gateways that
     * are added in future
     */
    const GATEWAY_ERROR_FATAL_ERROR                                                 = 'GATEWAY_ERROR_FATAL_ERROR';
    const GATEWAY_ERROR_REQUEST_ERROR                                               = 'GATEWAY_ERROR_REQUEST_ERROR';

    const GATEWAY_ERROR_REQUEST_TIMEOUT                                             = 'GATEWAY_ERROR_REQUEST_TIMEOUT';
    const GATEWAY_ERROR_DENIED_BY_RISK                                              = 'GATEWAY_ERROR_DENIED_BY_RISK';
    const GATEWAY_ERROR_PROCESSING_DECLINED                                         = 'GATEWAY_ERROR_PROCESSING_DECLINED';
    const GATEWAY_ERROR_AUTHENTICATION_NOT_AVAILABLE                                = 'GATEWAY_ERROR_AUTHENTICATION_NOT_AVAILABLE';
    const GATEWAY_ERROR_INVALID_TERMINAL_ID                                         = 'GATEWAY_ERROR_INVALID_TERMINAL_ID';
    const GATEWAY_ERROR_INVALID_TERMINAL_SECRET                                     = 'GATEWAY_ERROR_INVALID_TERMINAL_SECRET';
    const GATEWAY_ERROR_CERTIFICATE_VALIDATION_FAILED                               = 'GATEWAY_ERROR_CERTIFICATE_VALIDATION_FAILED';
    const GATEWAY_ERROR_SIGNATURE_VALIDATION_FAILED                                 = 'GATEWAY_ERROR_SIGNATURE_VALIDATION_FAILED';
    const GATEWAY_ERROR_INVALID_SUBSEQUENT_PAYMENT                                  = 'GATEWAY_ERROR_INVALID_SUBSEQUENT_PAYMENT';
    const GATEWAY_ERROR_SUPPORT_FAILED                                              = 'GATEWAY_ERROR_SUPPORT_FAILED';
    const GATEWAY_ERROR_SUPPORT_AUTH_NOT_FOUND                                      = 'GATEWAY_ERROR_SUPPORT_AUTH_NOT_FOUND';
    const GATEWAY_ERROR_CAPTURE_GREATER_THAN_AUTH                                   = 'GATEWAY_ERROR_CAPTURE_GREATER_THAN_AUTH';
    const GATEWAY_ERROR_PAYMENT_CAPTURE_FAILED                                      = 'GATEWAY_ERROR_PAYMENT_CAPTURE_FAILED';
    const GATEWAY_ERROR_PARES_NOT_SUCCESSFUL                                        = 'GATEWAY_ERROR_PARES_NOT_SUCCESSFUL';
    const GATEWAY_ERROR_NOT_UNDERSTOOD_ERROR                                        = 'GATEWAY_ERROR_NOT_UNDERSTOOD_ERROR';
    const GATEWAY_ERROR_CHECKSUM_MATCH_FAILED                                       = 'GATEWAY_ERROR_CHECKSUM_MATCH_FAILED';
    const GATEWAY_ERROR_TRANSACTION_TYPE_NOT_SUPPORTED                              = 'GATEWAY_ERROR_TRANSACTION_TYPE_NOT_SUPPORTED';
    const GATEWAY_ERROR_PAYMENT_VERIFICATION_ERROR                                  = 'GATEWAY_ERROR_PAYMENT_VERIFICATION_ERROR';
    const GATEWAY_ERROR_UNSUPPORTED_CARD_NETWORK                                    = 'GATEWAY_ERROR_UNSUPPORTED_CARD_NETWORK';
    const GATEWAY_ERROR_UNKNOWN_ERROR                                               = 'GATEWAY_ERROR_UNKNOWN_ERROR';
    const GATEWAY_ERROR_INVALID_TERMINAL                                            = 'GATEWAY_ERROR_INVALID_TERMINAL';
    const GATEWAY_ERROR_PAYMENT_ALREADY_SETTLED                                     = 'GATEWAY_ERROR_PAYMENT_ALREADY_SETTLED';
    const GATEWAY_ERROR_PAYMENT_VOID_FAILED                                         = 'GATEWAY_ERROR_PAYMENT_VOID_FAILED';
    const GATEWAY_ERROR_PAYMENT_REFUND_FAILED                                       = 'GATEWAY_ERROR_PAYMENT_REFUND_FAILED';
    const GATEWAY_ERROR_TIMED_OUT                                                   = 'GATEWAY_ERROR_TIMED_OUT';
    const GATEWAY_ERROR_INVALID_DATE_FORMAT                                         = 'GATEWAY_ERROR_INVALID_DATE_FORMAT';

    const GATEWAY_ERROR_SUPPORT_GREATER_THAN_AUTH                                   = 'GATEWAY_ERROR_SUPPORT_GREATER_THAN_AUTH';

    const GATEWAY_ERROR_PAYMENT_DUPLICATE_REQUEST                                   = 'GATEWAY_ERROR_PAYMENT_DUPLICATE_REQUEST';
    const GATEWAY_ERROR_PAYMENT_INVALID_REFERENCE_NO                                = 'GATEWAY_ERROR_PAYMENT_INVALID_REFERENCE_NO';
    const GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT                                      = 'GATEWAY_ERROR_PAYMENT_INVALID_AMOUNT';
    const GATEWAY_ERROR_PAYMENT_INVALID_ACTION                                      = 'GATEWAY_ERROR_PAYMENT_INVALID_ACTION';
    const GATEWAY_ERROR_PAYMENT_INVALID_ID                                          = 'GATEWAY_ERROR_PAYMENT_INVALID_ID';
    const GATEWAY_ERROR_PAYMENT_CANNOT_BE_RETRIEVED                                 = 'GATEWAY_ERROR_PAYMENT_CANNOT_BE_RETRIEVED';
    const GATEWAY_ERROR_PAYMENT_DENIED_NEGATIVE_BIN                                 = 'GATEWAY_ERROR_PAYMENT_DENIED_NEGATIVE_BIN';
    const GATEWAY_ERROR_PAYMENT_INVALID_CURRENCY                                    = 'GATEWAY_ERROR_PAYMENT_INVALID_CURRENCY';
    const GATEWAY_ERROR_PAYMENT_INVALID_UDF                                         = 'GATEWAY_ERROR_PAYMENT_INVALID_UDF';
    const GATEWAY_ERROR_PAYMENT_CREDIT_LESS_THAN_DEBIT                              = 'GATEWAY_ERROR_PAYMENT_CREDIT_LESS_THAN_DEBIT';
    const GATEWAY_ERROR_PAYMENT_SUPPORT_FAILED                                      = 'GATEWAY_ERROR_PAYMENT_SUPPORT_FAILED';
    const GATEWAY_ERROR_PAYMENT_SUPPORT_AUTH_NOT_FOUND                              = 'GATEWAY_ERROR_PAYMENT_SUPPORT_AUTH_NOT_FOUND';
    const GATEWAY_ERROR_PAYMENT_INVALID_MOBILE                                      = 'GATEWAY_ERROR_PAYMENT_INVALID_MOBILE';
    const GATEWAY_ERROR_PAYMENT_INVALID_EMAIL                                       = 'GATEWAY_ERROR_PAYMENT_INVALID_EMAIL';

    const GATEWAY_ERROR_CARD_INVALID_NAME                                           = 'GATEWAY_ERROR_CARD_INVALID_NAME';
    const GATEWAY_ERROR_CARD_INVALID_NUMBER                                         = 'GATEWAY_ERROR_CARD_INVALID_NUMBER';
    const GATEWAY_ERROR_CARD_INVALID_EXPIRY_DATE                                    = 'GATEWAY_ERROR_CARD_INVALID_EXPIRY_DATE';
    const GATEWAY_ERROR_CARD_INVALID_BRAND                                          = 'GATEWAY_ERROR_CARD_INVALID_BRAND';
    const GATEWAY_ERROR_CARD_INVALID_AMOUNT                                         = 'GATEWAY_ERROR_CARD_INVALID_AMOUNT';
    const GATEWAY_ERROR_CARD_INVALID_ADDRESS                                        = 'GATEWAY_ERROR_CARD_INVALID_ADDRESS';
    const GATEWAY_ERROR_CARD_INVALID_ZIP                                            = 'GATEWAY_ERROR_CARD_INVALID_ZIP';
    const GATEWAY_ERROR_CARD_INVALID_CVV                                            = 'GATEWAY_ERROR_CARD_INVALID_CVV';
    const GATEWAY_ERROR_CARD_MISSING_CVV                                            = 'GATEWAY_ERROR_CARD_MISSING_CVV';

    const GATEWAY_ERROR_PAYMENT_MISSING_DATA                                        = 'GATEWAY_ERROR_PAYMENT_MISSING_DATA';
    const GATEWAY_ERROR_INVALID_PARAMETERS                                          = 'GATEWAY_ERROR_INVALID_PARAMETERS';
    const GATEWAY_ERROR_INVALID_CALLBACK_URL                                        = 'GATEWAY_ERROR_INVALID_CALLBACK_URL';
// Generic bad requests
    const BAD_REQUEST_INVALID_ID                                                    = 'BAD_REQUEST_INVALID_ID';
    const BAD_REQUEST_NO_RECORDS_FOUND                                              = 'BAD_REQUEST_NO_RECORDS_FOUND';
    const BAD_REQUEST_ONLY_HTTPS_ALLOWED                                            = 'BAD_REQUEST_ONLY_HTTPS_ALLOWED';
    const BAD_REQUEST_HTTP_METHOD_NOT_ALLOWED                                       = 'BAD_REQUEST_HTTP_METHOD_NOT_ALLOWED';
    const BAD_REQUEST_ERROR                                                         = 'BAD_REQUEST_ERROR';
    const BAD_REQUEST_EXTRA_FIELDS_PROVIDED                                         = 'BAD_REQUEST_EXTRA_FIELDS_PROVIDED';
    const BAD_REQUEST_VALIDATION_FAILURE                                            = 'BAD_REQUEST_VALIDATION_FAILURE';

// Unauthorized bad requests
    const BAD_REQUEST_UNAUTHORIZED_BASICAUTH_EXPECTED                               = 'BAD_REQUEST_UNAUTHORIZED_BASICAUTH_EXPECTED';
    const BAD_REQUEST_UNAUTHORIZED_INVALID_API_KEY                                  = 'BAD_REQUEST_UNAUTHORIZED_INVALID_API_KEY';
    const BAD_REQUEST_UNAUTHORIZED_INVALID_API_SECRET                               = 'BAD_REQUEST_UNAUTHORIZED_INVALID_API_SECRET';
    const BAD_REQUEST_UNAUTHORIZED_SECRET_NOT_PROVIDED                              = 'BAD_REQUEST_UNAUTHORIZED_SECRET_NOT_PROVIDED';
    const BAD_REQUEST_UNAUTHORIZED_SECRET_SENT_ON_PUBLIC_ROUTE                      = 'BAD_REQUEST_UNAUTHORIZED_SECRET_SENT_ON_PUBLIC_ROUTE';
    const BAD_REQUEST_UNAUTHORIZED_API_KEY_NOT_PROVIDED                             = 'BAD_REQUEST_UNAUTHORIZED_API_KEY_NOT_PROVIDED';

// Payment bad requests
    const BAD_REQUEST_PAYMENT_FAILED                                                = 'BAD_REQUEST_PAYMENT_FAILED';
    const BAD_REQUEST_PAYMENT_CANCELLED_BY_USER                                     = 'BAD_REQUEST_PAYMENT_CANCELLED_BY_USER';
    const BAD_REQUEST_PAYMENT_CANCELLED_BY_PRESSING_BACK_ON_ANDROID                 = 'BAD_REQUEST_PAYMENT_CANCELLED_BY_PRESSING_BACK_ON_ANDROID';
    const BAD_REQUEST_PAYMENT_CANCELLED_AT_LOGIN_SCREEN                             = 'BAD_REQUEST_PAYMENT_CANCELLED_AT_LOGIN_SCREEN';
    const BAD_REQUEST_PAYMENT_CANCELLED_AT_WALLET_PAYMENT_PAGE                      = 'BAD_REQUEST_PAYMENT_CANCELLED_AT_WALLET_PAYMENT_PAGE';
    const BAD_REQUEST_PAYMENT_ALREADY_PROCCESSED                                    = 'BAD_REQUEST_PAYMENT_ALREADY_PROCCESSED';
    const BAD_REQUEST_PAYMENT_ALREADY_CAPTURED                                      = 'BAD_REQUEST_PAYMENT_ALREADY_CAPTURED';
    const BAD_REQUEST_PAYMENT_ALREADY_REFUNDED                                      = 'BAD_REQUEST_PAYMENT_ALREADY_REFUNDED';
    const BAD_REQUEST_PAYMENT_ALREADY_REFUND_INITIATED                              = 'BAD_REQUEST_PAYMENT_ALREADY_REFUND_INITIATED';
    const BAD_REQUEST_PAYMENT_ANOTHER_OPERATION_IN_PROGRESS                         = 'BAD_REQUEST_PAYMENT_ANOTHER_OPERATION_IN_PROGRESS';
    const BAD_REQUEST_PAYMENT_CURRENCY_NOT_SUPPORTED                                = 'BAD_REQUEST_PAYMENT_CURRENCY_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_CARD_IS_NOT_ARRAY                                     = 'BAD_REQUEST_PAYMENT_CARD_IS_NOT_ARRAY';
    const BAD_REQUEST_PAYMENT_CAPTURE_ONLY_AUTHORIZED                               = 'BAD_REQUEST_PAYMENT_CAPTURE_ONLY_AUTHORIZED';
    const BAD_REQUEST_PAYMENT_CANCEL_ONLY_CREATED                                   = 'BAD_REQUEST_PAYMENT_CANCEL_ONLY_CREATED';
    const BAD_REQUEST_PAYMENT_CARD_NOT_PROVIDED                                     = 'BAD_REQUEST_PAYMENT_CARD_NOT_PROVIDED';
    const BAD_REQUEST_PAYMENT_CARD_CVV_NOT_PROVIDED                                 = 'BAD_REQUEST_PAYMENT_CARD_CVV_NOT_PROVIDED';
    const BAD_REQUEST_PAYMENT_CARD_INVALID_CVV                                      = 'BAD_REQUEST_PAYMENT_CARD_INVALID_CVV';
    const BAD_REQUEST_PAYMENT_STATUS_NOT_CAPTURED                                   = 'BAD_REQUEST_PAYMENT_STATUS_NOT_CAPTURED';
    const BAD_REQUEST_PAYMENT_STATUS_CAPTURE_NOT_PROCESSED                          = 'BAD_REQUEST_PAYMENT_STATUS_CAPTURE_NOT_PROCESSED';
    const BAD_REQUEST_PAYMENT_FULLY_REFUNDED                                        = 'BAD_REQUEST_PAYMENT_FULLY_REFUNDED';
    const BAD_REQUEST_PAYMENT_REFUND_NOT_SUPPORTED                                  = 'BAD_REQUEST_PAYMENT_REFUND_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_CAPTURED                   = 'BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_CAPTURED';
    const BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_UNREFUNDED                 = 'BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_UNREFUNDED';
    const BAD_REQUEST_PAYMENT_CAPTURE_AMOUNT_NOT_EQUAL_TO_AUTH                      = 'BAD_REQUEST_PAYMENT_CAPTURE_AMOUNT_NOT_EQUAL_TO_AUTH';
    const BAD_REQUEST_PAYMENT_NET_BANKING_NOT_ENABLED                               = 'BAD_REQUEST_PAYMENT_NET_BANKING_NOT_ENABLED';
    const BAD_REQUEST_PAYMENT_RECURRING_NOT_ENABLED                                 = 'BAD_REQUEST_PAYMENT_RECURRING_NOT_ENABLED';
    const BAD_REQUEST_PAYMENT_RECURRING_AUTH_NOT_SUPPORTED                          = 'BAD_REQUEST_PAYMENT_RECURRING_AUTH_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_UPI_NOT_ENABLED_FOR_MERCHANT                          = 'BAD_REQUEST_PAYMENT_UPI_NOT_ENABLED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_UPI_INVALID_VPA                                       = 'BAD_REQUEST_PAYMENT_UPI_INVALID_VPA';
    const BAD_REQUEST_PAYMENT_UPI_APP_NOT_SUPPORTED                                 = 'BAD_REQUEST_PAYMENT_UPI_APP_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_BANK_NOT_PROVIDED                                     = 'BAD_REQUEST_PAYMENT_BANK_NOT_PROVIDED';
    const BAD_REQUEST_PAYMENT_INVALID_BANK_CODE                                     = 'BAD_REQUEST_PAYMENT_INVALID_BANK_CODE';
    const BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_MIN_AMOUNT                           = 'BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_MIN_AMOUNT';
    const BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_10_MIN_AMOUNT                        = 'BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_10_MIN_AMOUNT';
    const BAD_REQUEST_PAYMENT_ATOM_NET_BANKING_MIN_AMOUNT_FIFTY                     = 'BAD_REQUEST_PAYMENT_ATOM_NET_BANKING_MIN_AMOUNT_FIFTY';
    const BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_MIN_AMOUNT_FOR_EMI                   = 'BAD_REQUEST_PAYMENT_AMOUNT_LESS_THAN_MIN_AMOUNT_FOR_EMI';
    const BAD_REQUEST_PAYMENT_AMOUNT_TOO_HIGH                                       = 'BAD_REQUEST_PAYMENT_AMOUNT_TOO_HIGH';
    const BAD_REQUEST_PAYMENT_CONTACT_INCORRECT_FORMAT                              = 'BAD_REQUEST_PAYMENT_CONTACT_INCORRECT_FORMAT';
    const BAD_REQUEST_PAYMENT_CONTACT_INVALID_COUNTRY_CODE                          = 'BAD_REQUEST_PAYMENT_CONTACT_INVALID_COUNTRY_CODE';
    const BAD_REQUEST_PAYMENT_CONTACT_TOO_SHORT                                     = 'BAD_REQUEST_PAYMENT_CONTACT_TOO_SHORT';
    const BAD_REQUEST_PAYMENT_CONTACT_TOO_LONG                                      = 'BAD_REQUEST_PAYMENT_CONTACT_TOO_LONG';
    const BAD_REQUEST_PAYMENT_CONTACT_ONLY_INDIAN_ALLOWED                           = 'BAD_REQUEST_PAYMENT_CONTACT_ONLY_INDIAN_ALLOWED';
    const BAD_REQUEST_PAYMENT_CARD_NETWORK_NOT_SUPPORTED                            = 'BAD_REQUEST_PAYMENT_CARD_NETWORK_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_CARD_INSUFFICIENT_BALANCE                             = 'BAD_REQUEST_PAYMENT_CARD_INSUFFICIENT_BALANCE';
    const BAD_REQUEST_PAYMENT_CARD_DECLINED                                         = 'BAD_REQUEST_PAYMENT_CARD_DECLINED';
    const BAD_REQUEST_PAYMENT_CARD_EXPIRED                                          = 'BAD_REQUEST_PAYMENT_CARD_EXPIRED';
    const BAD_REQUEST_PAYMENT_CARD_INVALID_EXPIRY_DATE                              = 'BAD_REQUEST_PAYMENT_CARD_INVALID_EXPIRY_DATE';
    const BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID                                  = 'BAD_REQUEST_PAYMENT_CARD_DETAILS_INVALID';
    const BAD_REQUEST_PAYMENT_CARD_ISSUING_BANK_PREVENTED_AUTHORIZATION             = 'BAD_REQUEST_PAYMENT_CARD_ISSUING_BANK_PREVENTED_AUTHORIZATION';
    const BAD_REQUEST_PAYMENT_CARD_NUMBER_NOT_LEGITIMATE                            = 'BAD_REQUEST_PAYMENT_CARD_NUMBER_NOT_LEGITIMATE';
    const BAD_REQUEST_PAYMENT_CARD_NUMBER_POSSIBLY_INVALID                          = 'BAD_REQUEST_PAYMENT_CARD_NUMBER_POSSIBLY_INVALID';
    const BAD_REQUEST_PAYMENT_CARD_WITHDRAWAL_LIMITS_EXCEEDED                       = 'BAD_REQUEST_PAYMENT_CARD_WITHDRAWAL_LIMITS_EXCEEDED';
    const BAD_REQUEST_PAYMENT_CARD_ISSUING_BANK_NOT_PERMITTING_PAYMENT              = 'BAD_REQUEST_PAYMENT_CARD_ISSUING_BANK_NOT_PERMITTING_PAYMENT';
    const BAD_REQUEST_PAYMENT_CARD_CVV_LENGTH_MUST_BE_THREE                         = 'BAD_REQUEST_PAYMENT_CARD_CVV_LENGTH_MUST_BE_THREE';
    const BAD_REQUEST_PAYMENT_CARD_AMEX_CVV_LENGTH_MUST_BE_FOUR                     = 'BAD_REQUEST_PAYMENT_CARD_AMEX_CVV_LENGTH_MUST_BE_FOUR';
    const BAD_REQUEST_PAYMENT_CARD_INTERNATIONAL_NOT_ALLOWED                        = 'BAD_REQUEST_PAYMENT_CARD_INTERNATIONAL_NOT_ALLOWED';
    const BAD_REQUEST_PAYMENT_CARD_RECURRING_NOT_SUPPORTED                          = 'BAD_REQUEST_PAYMENT_CARD_RECURRING_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_BLOCKED_BY_BANK_DUE_TO_RISK_CHECKS_FAILURE            = 'BAD_REQUEST_PAYMENT_BLOCKED_BY_BANK_DUE_TO_RISK_CHECKS_FAILURE';
    const BAD_REQUEST_PAYMENT_BLOCKED_DUE_TO_FRAUD                                  = 'BAD_REQUEST_PAYMENT_BLOCKED_DUE_TO_FRAUD';
    const BAD_REQUEST_PAYMENT_TIMED_OUT                                             = 'BAD_REQUEST_PAYMENT_TIMED_OUT';
    const BAD_REQUEST_PAYMENT_BANK_NOT_ENABLED_FOR_MERCHANT                         = 'BAD_REQUEST_PAYMENT_BANK_NOT_ENABLED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_WALLET_NOT_SUPPORTED                                  = 'BAD_REQUEST_PAYMENT_WALLET_NOT_SUPPORTED';
    const BAD_REQUEST_PAYMENT_WALLET_NOT_PROVIDED                                   = 'BAD_REQUEST_PAYMENT_WALLET_NOT_PROVIDED';
    const BAD_REQUEST_PAYMENT_WALLET_NOT_ENALBED_FOR_MERCHANT                       = 'BAD_REQUEST_PAYMENT_WALLET_NOT_ENALBED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_CARD_NOT_ENALBED_FOR_MERCHANT                         = 'BAD_REQUEST_PAYMENT_CARD_NOT_ENALBED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_EMI_NOT_ENALBED_FOR_MERCHANT                          = 'BAD_REQUEST_PAYMENT_EMI_NOT_ENALBED_FOR_MERCHANT';
    const BAD_REQUEST_PAYMENT_EMI_NOT_AVAILABLE_ON_CARD                             = 'BAD_REQUEST_PAYMENT_EMI_NOT_AVAILABLE_ON_CARD';
    const BAD_REQUEST_PAYMENT_DECLINED_BY_CLICKING_CANCEL                           = 'BAD_REQUEST_PAYMENT_DECLINED_BY_CLICKING_CANCEL';
    const BAD_REQUEST_PAYMENT_DECLINED_BY_GATEWAY                                   = 'BAD_REQUEST_PAYMENT_DECLINED_BY_GATEWAY';
    const BAD_REQUEST_PAYMENT_DECLINED_BY_BANK                                      = 'BAD_REQUEST_PAYMENT_DECLINED_BY_BANK';
    const BAD_REQUEST_PAYMENT_NO_RESPONSE_RECEIVED_FROM_BANK                        = 'BAD_REQUEST_PAYMENT_NO_RESPONSE_RECEIVED_FROM_BANK';
    const BAD_REQUEST_PAYMENT_BANK_SYSTEM_ERROR                                     = 'BAD_REQUEST_PAYMENT_BANK_SYSTEM_ERROR';
    const BAD_REQUEST_PAYMENT_FAILED_MAYBE_DUE_TO_INVALID_INPUT                     = 'BAD_REQUEST_PAYMENT_FAILED_MAYBE_DUE_TO_INVALID_INPUT';
    const BAD_REQUEST_PAYMENT_FAILED_BECAUSE_SESSION_EXPIRED                        = 'BAD_REQUEST_PAYMENT_FAILED_BECAUSE_SESSION_EXPIRED';
    const BAD_REQUEST_PAYMENT_CANCELLED                                             = 'BAD_REQUEST_PAYMENT_CANCELLED';
    const BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK                         = 'BAD_REQUEST_PAYMENT_DECLINED_CONTACT_ISSUING_BANK';
    const BAD_REQUEST_PAYMENT_DECLINED_3DSECURE_AUTH_FAILED                         = 'BAD_REQUEST_PAYMENT_DECLINED_3DSECURE_AUTH_FAILED';
    const BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK                          = 'BAD_REQUEST_PAYMENT_DECLINED_BY_BANK_DUE_TO_RISK';
    const BAD_REQUEST_PAYMENT_CARD_NOT_ENROLLED_FOR_3DSECURE                        = 'BAD_REQUEST_PAYMENT_CARDHOLDER_NOT_ENROLLED_IN_3DSECURE_AUTH';
    const BAD_REQUEST_PAYMENT_INVALID_MOBILE                                        = 'BAD_REQUEST_PAYMENT_INVALID_MOBILE';
    const BAD_REQUEST_PAYMENT_INVALID_EMAIL                                         = 'BAD_REQUEST_PAYMENT_INVALID_EMAIL';
    const BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED                         = 'BAD_REQUEST_PAYMENT_WALLET_PER_DAY_LIMIT_EXCEEDED';
    const BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED                        = 'BAD_REQUEST_PAYMENT_WALLET_PER_WEEK_LIMIT_EXCEEDED';
    const BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED                       = 'BAD_REQUEST_PAYMENT_WALLET_PER_MONTH_LIMIT_EXCEEDED';
    const BAD_REQUEST_PAYMENT_WALLET_PER_PAYMENT_AMOUNT_CROSSED                     = 'BAD_REQUEST_PAYMENT_WALLET_PER_PAYMENT_AMOUNT_CROSSED';
    const BAD_REQUEST_PAYMENT_WALLET_BLOCKED_CARD                                   = 'BAD_REQUEST_PAYMENT_WALLET_BLOCKED_CARD';
    const BAD_REQUEST_PAYMENT_WALLET_BLOCKED_MOBILE_NUMBER                          = 'BAD_REQUEST_PAYMENT_WALLET_BLOCKED_MOBILE_NUMBER';
    const BAD_REQUEST_PAYMENT_WALLET_BLOCKED_IP_ADDRESS                             = 'BAD_REQUEST_PAYMENT_WALLET_BLOCKED_IP_ADDRESS';
    const BAD_REQUEST_PAYMENT_WALLET_BLOCKED_CUSTOMER                               = 'BAD_REQUEST_PAYMENT_WALLET_BLOCKED_CUSTOMER';
    const BAD_REQUEST_PAYMENT_WALLET_MAX_WRONG_ATTEMPT_LIMIT_CROSSED                = 'BAD_REQUEST_PAYMENT_WALLET_MAX_WRONG_ATTEMPT_LIMIT_CROSSED';
    const BAD_REQUEST_PAYMENT_WALLET_MAX_AMOUNT_LIMIT_CROSSED_FOR_CUSTOMER          = 'BAD_REQUEST_PAYMENT_WALLET_MAX_AMOUNT_LIMIT_CROSSED';
    const BAD_REQUEST_PAYMENT_WALLET_NOT_ACTIVATED                                  = 'BAD_REQUEST_PAYMENT_WALLET_NOT_ACTIVATED';
    const BAD_REQUEST_PAYMENT_WALLET_USER_DOES_NOT_EXIST                            = 'BAD_REQUEST_PAYMENT_WALLET_USER_DOES_NOT_EXIST';
    const BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_INVALID_MOBILE                         = 'BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_INVALID_MOBILE';
    const BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_INVALID_CREDENTIALS                    = 'BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_INVALID_CREDENTIALS';
    const BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_ALREADY_EXIST_WITH_EMAIL               = 'BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_ALREADY_EXIST_WITH_EMAIL';
    const BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_ALREADY_EXIST_WITH_CONTACT             = 'BAD_REQUEST_PAYMENT_WALLET_ACCOUNT_ALREADY_EXIST_WITH_CONTACT';
    const BAD_REQUEST_PAYMENT_WALLET_NO_USER_WITH_CELL                              = 'BAD_REQUEST_PAYMENT_WALLET_NO_USER_WITH_CELL';
    const BAD_REQUEST_PAYMENT_WALLET_AUTHENTICATION_FAILED                          = 'BAD_REQUEST_PAYMENT_WALLET_AUTHENTICATION_FAILED';
    const BAD_REQUEST_PAYMENT_WALLET_INSUFFICIENT_BALANCE                           = 'BAD_REQUEST_PAYMENT_WALLET_INSUFFICIENT_BALANCE';
    const BAD_REQUEST_PAYMENT_WALLET_CONTACT_PAYUMONEY                              = 'BAD_REQUEST_PAYMENT_WALLET_CONTACT_PAYUMONEY';
    const BAD_REQUEST_PAYMENT_OTP_VALIDATION_ATTEMPT_LIMIT_EXCEEDED                 = 'BAD_REQUEST_PAYMENT_OTP_VALIDATION_ATTEMPT_LIMIT_EXCEEDED';
    const BAD_REQUEST_PAYMENT_OTP_INCORRECT                                         = 'BAD_REQUEST_PAYMENT_OTP_INCORRECT';
    const BAD_REQUEST_PAYMENT_OTP_EXPIRED                                           = 'BAD_REQUEST_PAYMENT_OTP_EXPIRED';
    const BAD_REQUEST_PAYMENT_ORDER_AMOUNT_MISMATCH                                 = 'BAD_REQUEST_PAYMENT_ORDER_AMOUNT_MISMATCH';
    const BAD_REQUEST_PAYMENT_ORDER_ALREADY_PAID                                    = 'BAD_REQUEST_PAYMENT_ORDER_ALREADY_PAID';
    const BAD_REQUEST_PAYMENT_ABORTED                                               = 'BAD_REQUEST_PAYMENT_ABORTED';
    const BAD_REQUEST_PAYMENT_FEES_OR_SERVICE_TAX_TAMPERED                          = 'BAD_REQUEST_PAYMENT_FEES_OR_SERVICE_TAX_TAMPERED';
    const BAD_REQUEST_PAYMENT_MISSING_DATA                                          = 'BAD_REQUEST_PAYMENT_MISSING_DATA';
    const BAD_REQUEST_PAYMENT_PARTIAL_AMOUNT_APPROVED                               = 'BAD_REQUEST_PAYMENT_PARTIAL_AMOUNT_APPROVED';
    const BAD_REQUEST_PAYMENT_PROBLEM_IN_UPDATING                                   = 'BAD_REQUEST_PAYMENT_PROBLEM_IN_UPDATING';
    const BAD_REQUEST_PAYMENT_FEES_GREATER_THAN_AMOUNT                              = 'BAD_REQUEST_PAYMENT_FEES_GREATER_THAN_AMOUNT';
    const BAD_REQUEST_PAYMENT_CANNOT_BE_CANCELLED                                   = 'BAD_REQUEST_PAYMENT_CANNOT_BE_CANCELLED';


    const BAD_REQUEST_PAYMENT_POSSIBLE_FRAUD                                        = 'BAD_REQUEST_PAYMENT_POSSIBLE_FRAUD';
    const BAD_REQUEST_CARD_AVS_FAILED                                               = 'BAD_REQUEST_CARD_AVS_FAILED';
    const BAD_REQUEST_CARD_STOLEN_OR_LOST                                           = 'BAD_REQUEST_CARD_STOLEN_OR_LOST';
    const BAD_REQUEST_CARD_ISSUING_BANK_UNAVAILABLE                                 = 'BAD_REQUEST_CARD_ISSUING_BANK_UNAVAILABLE';
    const BAD_REQUEST_CARD_INACTIVE                                                 = 'BAD_REQUEST_CARD_INACTIVE';
    const BAD_REQUEST_CARD_CREDIT_LIMIT_REACHED                                     = 'BAD_REQUEST_CARD_CREDIT_LIMIT_REACHED';
    const BAD_REQUEST_CARD_FROZEN                                                   = 'BAD_REQUEST_CARD_FROZEN';
    const BAD_REQUEST_CARD_DAILY_LIMIT_REACHED                                      = 'BAD_REQUEST_CARD_DAILY_LIMIT_REACHED';
    const BAD_REQUEST_CARD_BILL_SHIP_MISMATCH                                       = 'BAD_REQUEST_CARD_BILL_SHIP_MISMATCH';
    const BAD_REQUEST_INVALID_PARAMETERS                                            = 'BAD_REQUEST_INVALID_PARAMETERS';

    const BAD_REQUEST_UNSUPPORTED_CHARACTER_SET                                     = 'BAD_REQUEST_UNSUPPORTED_CHARACTER_SET';

    const BAD_REQUEST_PAYMENT_ORDER_ID_REQUIRED                                     = 'BAD_REQUEST_PAYMENT_ORDER_ID_REQUIRED';
    const BAD_REQUEST_ORDER_METHOD_REQUIRED_FOR_MERCHANT                            = 'BAD_REQUEST_ORDER_METHOD_REQUIRED_FOR_MERCHANT';
    const BAD_REQUEST_ORDER_ACCOUNT_NUMBER_REQUIRED_FOR_MERCHANT                    = 'BAD_REQUEST_ORDER_ACCOUNT_NUMBER_REQUIRED_FOR_MERCHANT';

    const BAD_REQUEST_PAYMENT_NETBANKING_CANCELLED_BY_USER                          = 'BAD_REQUEST_PAYMENT_NETBANKING_CANCELLED_BY_USER';

    const BAD_REQUEST_REFUND_FAILED                                                 = 'BAD_REQUEST_REFUND_FAILED';
    const BAD_REQUEST_REFUND_NOT_ENOUGH_BALANCE                                     = 'BAD_REQUEST_REFUND_NOT_ENOUGH_BALANCE';

    const BAD_REQUEST_BATCH_FILE_EXCEED_LIMIT                                       = 'BAD_REQUEST_BATCH_FILE_EXCEED_LIMIT';
    const BAD_REQUEST_BATCH_FILE_INVALID_TYPE                                       = 'BAD_REQUEST_BATCH_FILE_INVALID_TYPE';
    const BAD_REQUEST_BATCH_FILE_INVALID_PAYMENT_ID                                 = 'BAD_REQUEST_BATCH_FILE_INVALID_PAYMENT_ID';
    const BAD_REQUEST_BATCH_FILE_INVALID_AMOUNT                                     = 'BAD_REQUEST_BATCH_FILE_INVALID_AMOUNT';
    const BAD_REQUEST_BATCH_FILE_DUPLICATE_PAYMENT_ID                               = 'BAD_REQUEST_BATCH_FILE_DUPLICATE_PAYMENT_ID';
    const BAD_REQUEST_BATCH_FILE_VALIDATION                                         = 'BAD_REQUEST_BATCH_FILE_VALIDATION';
    const BAD_REQUEST_BATCH_FILE_ALREADY_PROCESSED                                  = 'BAD_REQUEST_BATCH_FILE_ALREADY_PROCESSED';
    const BAD_REQUEST_BATCH_ANOTHER_OPERATION_IN_PROGRESS                           = 'BAD_REQUEST_BATCH_ANOTHER_OPERATION_IN_PROGRESS';

    const BAD_REQUEST_URL_NOT_FOUND                                                 = 'BAD_REQUEST_URL_NOT_FOUND';
    const BAD_REQUEST_NOTES_SHOULD_BE_ARRAY                                         = 'BAD_REQUEST_NOTES_SHOULD_BE_ARRAY';
    const BAD_REQUEST_NOTES_TOO_MANY_KEYS                                           = 'BAD_REQUEST_NOTES_TOO_MANY_KEYS';
    const BAD_REQUEST_NOTES_VALUE_CANNOT_BE_ARRAY                                   = 'BAD_REQUEST_NOTES_VALUE_CANNOT_BE_ARRAY';
    const BAD_REQUEST_NOTES_KEY_CANNOT_BE_ARRAY                                     = 'BAD_REQUEST_NOTES_KEY_CANNOT_BE_ARRAY';
    const BAD_REQUEST_NOTES_KEY_TOO_LARGE                                           = 'BAD_REQUEST_NOTES_KEY_TOO_LARGE';
    const BAD_REQUEST_NOTES_VALUE_TOO_LARGE                                         = 'BAD_REQUEST_NOTES_VALUE_TOO_LARGE';
    const BAD_REQUEST_DESCRIPTION_SHOULD_BE_STRING                                  = 'BAD_REQUEST_DESCRIPTION_SHOULD_BE_STRING';
    const BAD_REQUEST_DESCRIPTION_TOO_LARGE                                         = 'BAD_REQUEST_DESCRIPTION_TOO_LARGE';

    const BAD_REQUEST_PRICING_ID_REQURED                                            = 'BAD_REQUEST_PRICING_ID_REQURED';
    const BAD_REQUEST_PRICING_PLAN_ALREADY_EXISTS                                   = 'BAD_REQUEST_PRICING_PLAN_ALREADY_EXISTS';
    const BAD_REQUEST_PRICING_RATE_NOT_DEFINED                                      = 'BAD_REQUEST_PRICING_RATE_NOT_DEFINED';
    const BAD_REQUEST_PRICING_GATEWAY_REQUIRED                                      = 'BAD_REQUEST_PRICING_GATEWAY_REQUIRED';
    const BAD_REQUEST_PRICING_RULE_ALREADY_DEFINED                                  = 'BAD_REQUEST_PRICING_RULE_ALREADY_DEFINED';
    const BAD_REQUEST_PRICING_PLAN_WITH_SAME_NAME_EXISTS                            = 'BAD_REQUEST_PRICING_PLAN_WITH_SAME_NAME_EXISTS';
    const BAD_REQUEST_PRICING_NOT_DEFINED_FOR_MERCHANT                              = 'BAD_REQUEST_PRICING_NOT_DEFINED_FOR_MERCHANT';
    const BAD_REQUEST_PRICING_FIELD_NOT_REQUIRED_FOR_NB                             = 'BAD_REQUEST_PRICING_FIELD_NOT_REQUIRED_FOR_NB';
    const BAD_REQUEST_PRICING_RULE_FOR_AMEX_NOT_PRESENT                             = 'BAD_REQUEST_PRICING_RULE_FOR_AMEX_NOT_PRESENT';
    const BAD_REQUEST_PRICING_RULE_FOR_AMOUNT_RANGE_OVERLAP                         = 'BAD_REQUEST_PRICING_RULE_FOR_AMOUNT_RANGE_OVERLAP';

    const BAD_REQUEST_MERCHANT_ALREADY_ACTIVATED                                    = 'BAD_REQUEST_MERCHANT_ALREADY_ACTIVATED';
    const BAD_REQUEST_MERCHANT_NOT_ACTIVATED                                        = 'BAD_REQUEST_MERCHANT_NOT_ACTIVATED';
    const BAD_REQUEST_MERCHANT_NO_TERMINAL_ASSIGNED                                 = 'BAD_REQUEST_MERCHANT_NO_TERMINAL_ASSIGNED';
    const BAD_REQUEST_MERCHANT_KEY_ALREADY_CREATED                                  = 'BAD_REQUEST_MERCHANT_KEY_ALREADY_CREATED';
    const BAD_REQUEST_MERCHANT_NOT_ACTIVATED_KEY_CREATE_FAILED                      = 'BAD_REQUEST_MERCHANT_NOT_ACTIVATED_KEY_CREATE_FAILED';
    const BAD_REQUEST_MERCHANT_ALREADY_LIVE                                         = 'BAD_REQUEST_MERCHANT_ALREADY_LIVE';
    const BAD_REQUEST_MERCHANT_NOT_LIVE                                             = 'BAD_REQUEST_MERCHANT_NOT_LIVE';
    const BAD_REQUEST_MERCHANT_NOT_LIVE_ACTION_DENIED                               = 'BAD_REQUEST_MERCHANT_NOT_LIVE_ACTION_DENIED';
    const BAD_REQUEST_MERCHANT_TERMINAL_EXISTS_FOR_GATEWAY                          = 'BAD_REQUEST_MERCHANT_TERMINAL_EXISTS_FOR_GATEWAY';
    const BAD_REQUEST_MERCHANT_NO_BANK_ACCOUNT_FOUND                                = 'BAD_REQUEST_MERCHANT_NO_BANK_ACCOUNT_FOUND';
    const BAD_REQUEST_MERCHANT_BANK_ACCOUNT_ALREADY_PROVIDED                        = 'BAD_REQUEST_MERCHANT_BANK_ACCOUNT_ALREADY_PROVIDED';
    const BAD_REQUEST_MERCHANT_LOGO_TOO_BIG                                         = 'BAD_REQUEST_MERCHANT_LOGO_TOO_BIG';
    const BAD_REQUEST_MERCHANT_LOGO_NOT_SQUARE                                      = 'BAD_REQUEST_MERCHANT_LOGO_NOT_SQUARE';
    const BAD_REQUEST_MERCHANT_LOGO_NOT_IMAGE                                       = 'BAD_REQUEST_MERCHANT_LOGO_NOT_IMAGE';
    const BAD_REQUEST_LOGO_NOT_PRESENT                                              = 'BAD_REQUEST_LOGO_NOT_PRESENT';
    const BAD_REQUEST_MERCHANT_LOGO_TOO_SMALL                                       = 'BAD_REQUEST_MERCHANT_LOGO_TOO_SMALL';

    const BAD_REQUEST_GATEWAY_TERMINAL_MAX_LIMIT_REACHED                            = 'BAD_REQUEST_GATEWAY_TERMINAL_MAX_LIMIT_REACHED';
    const BAD_REQUEST_GATEWAY_MERCHANT_ID_EXISTS                                    = 'BAD_REQUEST_GATEWAY_MERCHANT_ID_EXISTS';
    const BAD_REQUEST_GATEWAY_CANNOT_TOPUP                                          = 'BAD_REQUEST_GATEWAY_CANNOT_TOPUP';

    const BAD_REQUEST_KEY_EXPIRED                                                   = 'BAD_REQUEST_KEY_EXPIRED';
    const BAD_REQUEST_KEY_EXPIRING_SOON                                             = 'BAD_REQUEST_KEY_EXPIRING_SOON';
    const BAD_REQUEST_KEY_OF_DEMO_ACCOUNT                                           = 'BAD_REQUEST_KEY_OF_DEMO_ACCOUNT';

    const BAD_REQUEST_PAYMENT_VERIFICATION_FAILED                                   = 'BAD_REQUEST_PAYMENT_VERIFICATION_FAILED';

    const BAD_REQUEST_INVALID_CHECKOUT_ID                                           = 'BAD_REQUEST_INVALID_CHECKOUT_ID';
    const BAD_REQUEST_INVALID_PLATFORM                                              = 'BAD_REQUEST_INVALID_PLATFORM';
    const BAD_REQUEST_INVALID_LIBRARY                                               = 'BAD_REQUEST_INVALID_LIBRARY';
    const BAD_REQUEST_INVALID_BROWSER                                               = 'BAD_REQUEST_INVALID_BROWSER';
    const BAD_REQUEST_INVALID_OS                                                    = 'BAD_REQUEST_INVALID_OS';
    const BAD_REQUEST_INVALID_DEVICE                                                = 'BAD_REQUEST_INVALID_DEVICE';
    const BAD_REQUEST_INVALID_INTEGRATION                                           = 'BAD_REQUEST_INVALID_INTEGRATION';

    const SERVER_ERROR_INVALID_ARGUMENT                                             = 'SERVER_ERROR_INVALID_ARGUMENT';
    const SERVER_ERROR_DB_QUERY_FAILED                                              = 'SERVER_ERROR_DB_QUERY_FAILED';
    const SERVER_ERROR_LOGICAL_ERROR                                                = 'SERVER_ERROR_LOGICAL_ERROR';
    const SERVER_ERROR_INTEGRATION_ERROR                                            = 'SERVER_ERROR_INTEGRATION_ERROR';
    const SERVER_ERROR_SETTLEMENTS_FAILED                                           = 'SERVER_ERROR_SETTLEMENTS_FAILED';
    const SERVER_ERROR_RUNTIME_ERROR                                                = 'SERVER_ERROR_RUNTIME_ERROR';
    const SERVER_ERROR_ASSERTION_ERROR                                              = 'SERVER_ERROR_ASSERTION_ERROR';
    const SERVER_ERROR_PAYMENT_ABORTED                                              = 'SERVER_ERROR_PAYMENT_ABORTED';
    const SERVER_ERROR_TO_STRING_EXCEPTION                                          = 'SERVER_ERROR_TO_STRING_EXCEPTION';
    const SERVER_ERROR_MYSQL_ENTRY_NOT_FOUND                                        = 'SERVER_ERROR_MYSQL_ENTRY_NOT_FOUND';
    const SERVER_ERROR_AWS_FAILURE                                                  = 'SERVER_ERROR_AWS_FAILURE';
    const SERVER_ERROR_PRICING_RULE_ABSENT                                          = 'SERVER_ERROR_PRICING_RULE_ABSENT';
    const SERVER_ERROR_CARD_NUMBER_LOGGED                                           = 'SERVER_ERROR_CARD_NUMBER_LOGGED';

    const BAD_REQUEST_CUSTOMER_ALREADY_EXISTS                                       = 'BAD_REQUEST_CUSTOMER_ALREADY_EXISTS';
    const BAD_REQUEST_CUSTOMER_CARD_ALREADY_EXISTS                                  = 'BAD_REQUEST_CUSTOMER_CARD_ALREADY_EXISTS';
    const BAD_REQUEST_CUSTOMER_BANK_ALREADY_EXISTS                                  = 'BAD_REQUEST_CUSTOMER_BANK_ALREADY_EXISTS';
    const BAD_REQUEST_CUSTOMER_WALLET_ALREADY_EXISTS                                = 'BAD_REQUEST_CUSTOMER_WALLET_ALREADY_EXISTS';

    const BAD_REQUEST_RECONCILIATION                                                = 'BAD_REQUEST_RECONCILIATION';
    const BAD_REQUEST_PAYMENT_ACCOUNT_INSUFFICIENT_BALANCE                          = 'BAD_REQUEST_PAYMENT_ACCOUNT_INSUFFICIENT_BALANCE';

    const BAD_REQUEST_MAXIMUM_SMS_LIMIT_REACHED                                     = 'BAD_REQUEST_MAXIMUM_SMS_LIMIT_REACHED';
    const BAD_REQUEST_OTP_MAXIMUM_ATTEMPTS_REACHED                                  = 'BAD_REQUEST_OTP_MAXIMUM_ATTEMPTS_REACHED';
    const BAD_REQUEST_INCORRECT_OTP                                                 = 'BAD_REQUEST_INCORRECT_OTP';
    const BAD_REQUEST_SMS_FAILED                                                    = 'BAD_REQUEST_SMS_FAILED';
    const BAD_REQUEST_INVALID_COUNTRY                                               = 'BAD_REQUEST_INVALID_COUNTRY';
}
