<?php

namespace Exceptions;

class Status
{
	const SUCCESS = 0;

	/**
	 * HDFC gateway specific error codes
	 */
	
	/**
	 * General gateway specific error codes
	 * Isn't specific to hdfc gateway and 
	 * should be generally valid for gateways that
	 * are added in future
	 */
	const GATEWAY_AUTHENTICATION_NOT_AVAILABLE = 1000;

	const GATEWAY_TRANSACTION_MISSING_DATA = 1010;
	const GATEWAY_TRANSACTION_INVALID_ACTION = 1011;
	const GATEWAY_TRANSACTION_INVALID_ID = 1012;
	const GATEWAY_TRASACTION_DENIED_NEGATIVE_BIN = 1013;
	const GATEWAY_TRANSACTION_INVALID_CURRENCY = 1014;
	const GATEWAY_TRANSACTION_INVALID_UDF = 1015;
	const GATEWAY_TRANSACTION_CREDIT_LESS_THAN_DEBIT = 1016;

	const GATEWAY_GATEWAY_INVALID_TERMINAL_ID = 1030;
	const GATEWAY_GATEWAY_CERTIFICATE_VALIDATION_FAILED = 1031;
	const GATEWAY_SIGNATURE_VALIDATION_FAILED = 1032;
	const GATEWAY_GATEWAY_SUBSEQUENT_TRANSACTION = 1033;

	const GATEWAY_CARD_MISSING_CVC = 1060;
	const GATEWAY_CARD_INVALID_NUMBER = 1061;
	const GATEWAY_CARD_INVALID_EXPIRY_DATE = 1062;
	const GATEWAY_CARD_INVALID_BRAND = 1063;
	const GATEWAY_CARD_INVALID_AMOUNT = 1064;
	const GATEWAY_CARD_INVALID_NAME = 1065;
	const GATEWAY_CARD_INVALID_ADDRESS = 1066;
	const GATEWAY_CARD_INVALID_ZIP = 1067;
	const GATEWAY_CARD_DECLINED = 1068;

	const GATEWAY_SUPPORT_FAILED = 1075;
	const GATEWAY_SUPPORT_AUTH_NOT_FOUND = 1076;

	const GATEWAY_PARES_NOT_SUCCESFUL = 1090;
	const GATEWAY_NOT_UNDERSTOOD_ERROR = 1091;
	const GATEWAY_UNKNOWN_ERROR = 1092;

	/**
	 * Card errors catchable in the app
	 */
	const APP_CARD_INVALID_NAME = 1120;
	const APP_CARD_INVALID_EXPIRY_MONTH = 1121;
	const APP_CARD_INVALID_EXPIRY_YEAR = 1122;
	const APP_CARD_INVALID_CVC = 1123;
	const APP_CARD_INVALID_BRAND = 1124;
	const APP_CARD_INVALID_CURRENCY =1125;
	const APP_CARD_INVALID_AMOUNT = 1126;
	const APP_CARD_INVALID_UDF = 1127;
	const APP_CARD_INVALID_NUMBER = 1128;
	const APP_CARD_EXPIRED = 1129;

	/**
	 * 
	 */
	const RZP_TXN_INVALID_CURRENCY = 1150;


	/**
	 * Server errors
	 */
	const SERVER_DB_ERROR = 2001;

	public static $gatewayUncatchableErrors = array(
		self::GATEWAY_CARD_INVALID_AMOUNT,
		self::GATEWAY_CARD_INVALID_ADDRESS,
		self::GATEWAY_CARD_INVALID_ZIP_CODE,
		self::GATEWAY_CARD_DECLINED,
		self::GATEWAY_TXN_DENIED_NEGATIVE_BIN);

	public static function isGatewayError($error)
	{
		return true;
	}

	public static function isCardError($error)
	{
		return true;
	}
}