import { DASHBOARD_TEAMS } from '@libs/shared-types';

export const DASHBOARD_ROUTES = {
  '/': DASHBOARD_TEAMS.COMMON,
  '/dashboard': DASHBOARD_TEAMS.COMMON,

  '/account-settings': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/addfunds': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/affordability/widget': DASHBOARD_TEAMS.AFFORDABILITY,
  '/affordability/widget/platforms': DASHBOARD_TEAMS.AFFORDABILITY,
  '/announcements': DASHBOARD_TEAMS.PLATFORM_GROWTH,
  '/api-keys': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/applications': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/assisted-financing': DASHBOARD_TEAMS.AFFORDABILITY,
  '/bank-accounts-settlements': DASHBOARD_TEAMS.BANKING,
  '/bank-accounts-settlements/bank-account-details': DASHBOARD_TEAMS.BANKING,
  '/bank-accounts-settlements/firs': DASHBOARD_TEAMS.BANKING,
  '/bank-accounts-settlements/settlement-details': DASHBOARD_TEAMS.BANKING,
  '/bbps': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/billme-settings/brands-and-terminals': DASHBOARD_TEAMS.BILLME,
  '/business-settings': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/business-settings/account-activation-details': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/business-settings/business': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/business-settings/contact': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/business-settings/customer-support': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/business-settings/gst': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/business-settings/invitations': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/business-settings/team': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/business-settings/ticket-support/tickets': DASHBOARD_TEAMS.CARE,
  '/business-settings/ticket-support/tickets/agent': DASHBOARD_TEAMS.CARE,
  '/business-settings/ticket-support/tickets/merchant': DASHBOARD_TEAMS.CARE,
  '/capital': DASHBOARD_TEAMS.CAPITAL,
  '/capital/cash-advance': DASHBOARD_TEAMS.CAPITAL,
  '/capital/cash-advance/repayments-schedule': DASHBOARD_TEAMS.CAPITAL,
  '/capital/corporate-cards': DASHBOARD_TEAMS.CAPITAL,
  '/capital/line-of-credit': DASHBOARD_TEAMS.CAPITAL,
  '/capital/loans': DASHBOARD_TEAMS.CAPITAL,
  '/capital/non-fldg-loans': DASHBOARD_TEAMS.CAPITAL,

  '/checkout-rewards': DASHBOARD_TEAMS.CHECKOUT,
  '/checkout-settings': DASHBOARD_TEAMS.CHECKOUT,
  '/checkout-settings/branding': DASHBOARD_TEAMS.CHECKOUT,
  '/checkout-settings/flash-checkout': DASHBOARD_TEAMS.CHECKOUT,
  '/checkout-settings/skip-mandatory-summary-page': DASHBOARD_TEAMS.CHECKOUT,
  '/checkout-settings/trustedbadge': DASHBOARD_TEAMS.CHECKOUT,
  '/config': DASHBOARD_TEAMS.PG_DASHBOARD,

  '/connected-banking': DASHBOARD_TEAMS.PLATFORM_GROWTH,
  '/credits': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/customers': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/developers': DASHBOARD_TEAMS.DEV_EXP,
  '/developers/apis': DASHBOARD_TEAMS.DEV_EXP,
  '/developers/webhooks': DASHBOARD_TEAMS.DEV_EXP,
  '/disputes': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/insight-x': DASHBOARD_TEAMS.DATAHUB,
  '/instantsettlement_details': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/instantsettlements': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/invoices': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/invoices/new': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/items': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/keys': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/magic': DASHBOARD_TEAMS.MAGIC_CHECKOUT,
  '/magic-konnect': DASHBOARD_TEAMS.MAGIC_KONNECT,
  '/notification-settings': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/notification-settings/email': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/notification-settings/sms': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/notification-settings/whatsapp': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/offers': DASHBOARD_TEAMS.CHECKOUT,

  '/optimizer': DASHBOARD_TEAMS.ROUTING,
  '/optimizer/add-provider': DASHBOARD_TEAMS.ROUTING,
  '/optimizer/create-rule': DASHBOARD_TEAMS.ROUTING,
  '/optimizer/update-rule': DASHBOARD_TEAMS.ROUTING,
  '/optimizer/rules': DASHBOARD_TEAMS.ROUTING,
  '/optimizer/onboarding': DASHBOARD_TEAMS.ROUTING,
  '/optimizer/update-provider': DASHBOARD_TEAMS.ROUTING,
  '/orders': DASHBOARD_TEAMS.PG_DASHBOARD,

  '/partners': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/applications': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/applications/new': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/applications/configuration': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/config': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/earnings': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/earnings/daily': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/earnings/invoices': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/earnings/transactional': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/playbook': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/manage-team': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/reports': DASHBOARD_TEAMS.MERCHANT_REPORTING,
  '/partners/settings': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/submerchants': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/submerchants/all': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/submerchants/pos': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/subventions': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/subventions/daily': DASHBOARD_TEAMS.PARTNERSHIP,
  '/partners/subventions/transactional': DASHBOARD_TEAMS.PARTNERSHIP,
  // Merchant pages under partnerships team
  '/partner-pricing-plans': DASHBOARD_TEAMS.PARTNERSHIP,

  '/payment-methods': DASHBOARD_TEAMS.TERMINAL,
  '/payment-methods/cards': DASHBOARD_TEAMS.TERMINAL,
  '/payment-methods/emi': DASHBOARD_TEAMS.TERMINAL,
  '/payment-methods/international-payments': DASHBOARD_TEAMS.TERMINAL,
  '/payment-methods/netbanking': DASHBOARD_TEAMS.TERMINAL,
  '/payment-methods/pay-later': DASHBOARD_TEAMS.TERMINAL,
  '/payment-methods/upi-qr': DASHBOARD_TEAMS.TERMINAL,
  '/payment-methods/wallet': DASHBOARD_TEAMS.TERMINAL,
  '/paymentbuttons': DASHBOARD_TEAMS.APPS,
  '/paymenthandle': DASHBOARD_TEAMS.APPS,
  '/payment-handle': DASHBOARD_TEAMS.APPS,
  '/paymentlinks': DASHBOARD_TEAMS.APPS,
  '/paymentlinks/batchuploads': DASHBOARD_TEAMS.APPS,
  '/paymentpages': DASHBOARD_TEAMS.APPS,
  '/paymentpages/products': DASHBOARD_TEAMS.APPS,

  '/payments-and-refunds-settings': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/payments-and-refunds-settings/balances': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/payments-and-refunds-settings/capture-refund-settings': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/payments-and-refunds-settings/credits': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/payments-and-refunds-settings/failed-payments-recovery': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/payments-and-refunds-settings/fee-bearer': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/payments-and-refunds-settings/reminders': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/payments-and-refunds-settings/transaction-limits': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/payments': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/payments/batchuploads': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/paypal_onboard_redirect': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/payroll': DASHBOARD_TEAMS.XPAYROLL,
  '/plans': DASHBOARD_TEAMS.APPS,
  '/plans/new': DASHBOARD_TEAMS.APPS,
  '/payment-metrics': DASHBOARD_TEAMS.CHECKOUT,

  '/profile': DASHBOARD_TEAMS.PG_DASHBOARD,

  '/qr_codes': DASHBOARD_TEAMS.APPS,
  '/qr_codes/new': DASHBOARD_TEAMS.APPS,
  '/qr_codes/payments': DASHBOARD_TEAMS.APPS,
  '/razorpayx': DASHBOARD_TEAMS.RAZORPAY_X,
  '/recurring_payments': DASHBOARD_TEAMS.APPS,

  '/referrals': DASHBOARD_TEAMS.PG_DASHBOARD,

  '/refunds': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/refunds/batchupload': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/refunds/batchuploads': DASHBOARD_TEAMS.PG_DASHBOARD,

  '/registration_links': DASHBOARD_TEAMS.APPS,

  '/reminders': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/reports': DASHBOARD_TEAMS.MERCHANT_REPORTING,
  '/reversals': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/reversals/batchreversals': DASHBOARD_TEAMS.PG_DASHBOARD,

  '/rize-marketplace': DASHBOARD_TEAMS.RIZE,

  '/route': DASHBOARD_TEAMS.APPS,
  '/route/accounts': DASHBOARD_TEAMS.APPS,
  '/route/batchuploads': DASHBOARD_TEAMS.APPS,
  '/route/payments': DASHBOARD_TEAMS.APPS,
  '/route/reversals': DASHBOARD_TEAMS.APPS,
  '/route/transfers': DASHBOARD_TEAMS.APPS,
  '/routeinstantsettlements': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/settlements': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/smartcollect': DASHBOARD_TEAMS.APPS,
  '/smartcollect/batchuploads': DASHBOARD_TEAMS.APPS,
  '/smartcollect/payments': DASHBOARD_TEAMS.APPS,
  '/smartcollect/virtualaccounts': DASHBOARD_TEAMS.APPS,

  '/store-settings/stores-list': DASHBOARD_TEAMS.BILLME,
  '/store-settings/store-create': DASHBOARD_TEAMS.BILLME,

  '/stores': DASHBOARD_TEAMS.APPS,
  '/stores/orders': DASHBOARD_TEAMS.APPS,
  '/stores/products': DASHBOARD_TEAMS.APPS,

  '/subscription_buttons': DASHBOARD_TEAMS.APPS,
  '/subscriptions': DASHBOARD_TEAMS.APPS,
  '/subscriptions/batchuploads': DASHBOARD_TEAMS.APPS,
  '/subscriptions/settings': DASHBOARD_TEAMS.APPS,
  '/success-rate': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/super-checkout': DASHBOARD_TEAMS.CHECKOUT,

  '/team': DASHBOARD_TEAMS.PG_DASHBOARD,

  '/ticket-support': DASHBOARD_TEAMS.CARE,
  '/ticket-support/tickets': DASHBOARD_TEAMS.CARE,

  '/tokens': DASHBOARD_TEAMS.APPS,

  '/transfers': DASHBOARD_TEAMS.PG_DASHBOARD,

  '/trustedbadge': DASHBOARD_TEAMS.CHECKOUT,
  '/virtualaccounts': DASHBOARD_TEAMS.APPS,
  '/wallet/accounts': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/webhooks': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/website-app-details': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/website-app-settings': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/website-app-settings/api-keys': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/website-app-settings/applications': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/website-app-settings/business-website-details': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/website-app-settings/webhooks': DASHBOARD_TEAMS.PG_DASHBOARD,
  '/website-app-settings/website-app': DASHBOARD_TEAMS.PG_DASHBOARD,

  '/pos/catalog': DASHBOARD_TEAMS.OMNI_CHANNEL,
  '/payments/b2b-exports': DASHBOARD_TEAMS.CROSS_BORDER,
  '/international-settings/firs': DASHBOARD_TEAMS.CROSS_BORDER,
  '/international-settings/international-payment-codes': DASHBOARD_TEAMS.CROSS_BORDER,
  '/payments/invoices': DASHBOARD_TEAMS.CROSS_BORDER,

  '/gcms/programs': DASHBOARD_TEAMS.RAZORPAY_WALLET,
  '/gcms/resellers': DASHBOARD_TEAMS.RAZORPAY_WALLET,
  '/gcms/orders': DASHBOARD_TEAMS.RAZORPAY_WALLET,
  '/gcms/funds': DASHBOARD_TEAMS.RAZORPAY_WALLET,
  '/gcms/reports': DASHBOARD_TEAMS.RAZORPAY_WALLET,
} as const;

export const ROUTE_REG = {
  accountsettings:
    /^\/(account-settings|payment-methods|checkout-settings|notification-settings|website-app-settings|payments-and-refunds-settings|business-settings|bank-accounts-settlements|international-settings|billme-settings|store-settings)/,
  riskAndFraud: /^\/(risk-and-fraud|risk-analytics)/,
  transactions: /^\/(payments|refunds|orders|batch-refunds|disputes|success-rate)/,
  // eslint-disable-next-line prettier/prettier
  settlements:
    /^\/(settlements|routeinstantsettlements|instantsettlement_details|instantsettlements)/,
  // eslint-disable-next-line prettier/prettier
  my_account:
    /^\/(trustedbadge|profile|credits|addfunds|referrals|website-app-details|ticket-support|team)/,
  settings: /^\/(config|webhooks|keys|applications|reminders|payment-methods)/,
  invoices: /^\/(invoices|items)/,
  route: /^\/route(\/(payments|transfers|reversals|accounts|batchuploads))?/,
  payment_links: /^\/paymentlinks(\/batchuploads)?/,
  payment_button: /^\/(paymentbuttons|subscription_buttons)/,
  payment_pages: /^\/(paymentpages)/,
  payment_handle: /^\/(payment-handle)/,
  // eslint-disable-next-line prettier/prettier
  subscriptions:
    /^\/(subscriptions(\/batchuploads)?|plans|addons|recurring_payments|tokens|authlinks|registration_links)/,
  // TODD: check why was partners not added here before and if adding this here will cause any issues?
  partner: /^\/(submerchants(\/(applications|settings))?|commissions)/,
  magic_checkout: /^\/magic(\/|$)/,
  magic_konnect: /^\/magic-konnect(\/|$)/,
  optimizer: /^\/optimizer(\/(add-provider|create-rule|update-rule|rules))?/,
  smart_collect: /^\/(smartcollect|virtualaccounts)/,
  qr_codes: /^\/qr_codes(\/(payments))?/,
  offers: /^\/offers(\/(new))?/,
  stores: /^\/stores(\/(products|orders))?/,
  cash_advance: /^\/capital\/cash-advance/,
  line_of_credit: /^\/capital\/line-of-credit/,
  working_capital_loans: /^\/capital\/non-fldg-loans/,
  x_corporate_cards: /^\/capital\/corporate-cards/,
  capital_loans: /^\/capital\/loans/,
  affordability: /^\/affordability(\/(widget))?/,
  developers: /^\/developers(\/(api|webhooks))?/,
  wallet: /^\/(wallet)/,
  internationalPaymentsBtn: /^\/(international)/,
  payment_metrics: /^\/(payment-metrics)/,
  pos: /^\/pos(\/(catalog|dashboard))*/,
  gcms_programs: /^\/gcms\/programs/,
  gcms_resellers: /^\/gcms\/resellers/,
  gcms_orders: /^\/gcms\/orders/,
  gcms_funds: /^\/gcms\/funds/,
  gcms_reports: /^\/gcms\/reports/,
  reconciliations: /^\/reconciliations/,
  assisted_financing: /^\/(assisted-financing)/,
  bill_me: /^\/billme/,
  reports: /^\/reports(\/(downloads|schedules))?/,
  insight_x: /^\/insight-x/,
};

export const BASE_ROUTES = {
  home: '/dashboard',
  transactions: '/payments',
  settlements: '/settlements',
  settings: '/config',
  developers: '/developers/apis',
  my_account: '/profile',
  reports: '/reports',
  x_corporate_cards: '/capital/corporate-cards/',
  working_capital_loans: '/capital/non-fldg-loans/',
  checkout_rewards: '/checkout-rewards',
  offers: '/offers',
  customers: '/customers',
  optimizer: '/optimizer',
  bbps: '/bbps',
  magic_checkout: '/magic',
  magic_konnect: '/magic-konnect',
  smart_collect: '/smartcollect/virtualaccounts',
  qr_codes: '/qr_codes',
  subscriptions: '/subscriptions',
  x_payroll: '/payroll',
  x_banking: '/razorpayx',
  route: '/route/payments',
  payment_button: '/paymentbuttons',
  api_keys: '/api-keys',
  stores: '/stores/products',
  payment_pages: '/paymentpages',
  payment_links: '/paymentlinks',
  cash_advance: '/capital/cash-advance',
  line_of_credit: '/capital/line-of-credit',
  capital_loans: '/capital/loans',
  invoices: '/invoices',
  app_store: '/app-store',
  subscription_buttons: '/subscription_buttons',
  chargeAtWill: '/recurring_payments',
  partner: '/submerchants',
  accountsettings: '/account-settings',
  affordability: '/affordability/widget',
  payment_handle: '/payment-handle',
  wallet: '/wallet',
  internationalPaymentsBtn: '/payment-methods/international-payments',
  payment_metrics: '/payment-metrics',
  pos: '/pos',
  bill_me: '/billme',
  gcms_programs: '/gcms/programs',
  gcms_resellers: '/gcms/resellers',
  gcms_orders: '/gcms/orders',
  gcms_funds: '/gcms/funds',
  gcms_reports: '/gcms/reports',
  riskAndFraud: '/risk-and-fraud',
  reconciliations: '/reconciliations/dashboard/processes',
  assisted_financing: '/assisted-financing',
  insight_x: '/insight-x',
  trustedbadge: '/checkout-settings/trustedbadge',
};
