<?php

namespace RZP\Models\Admin\Permission;

use RZP\Models\Merchant;

class Name
{
    const VIEW_HOMEPAGE                       = 'view_homepage';
    const VIEW_ALL_MERCHANTS                  = 'view_all_merchants';
    const VIEW_MERCHANT                       = 'view_merchant';
    const VIEW_MERCHANT_BALANCE               = 'view_merchant_balance';
    const VIEW_MERCHANT_FEATURES              = 'view_merchant_features';
    const VIEW_MERCHANT_BANKS                 = 'view_merchant_banks';
    const VIEW_NETWORKS                       = 'view_networks';
    const VIEW_MERCHANT_BANK_ACCOUNTS         = 'view_merchant_bank_accounts';
    const VIEW_MERCHANT_LOGIN                 = 'view_merchant_login';
    const VIEW_ACTIVITY                       = 'view_activity';
    const VIEW_PRICING_LIST                   = 'view_pricing_list';
    const VIEW_MERCHANT_HDFC_EXCEL            = 'view_merchant_hdfc_excel';
    const VIEW_BENEFICIARY_FILE               = 'view_beneficiary_file';
    const VIEW_MERCHANT_SCREENSHOT            = 'view_merchant_screenshot';
    const VIEW_ALL_MERCHANT_AGGREGATIONS      = 'view_all_merchant_aggregations';
    const VIEW_MERCHANT_AGGREGATIONS          = 'view_merchant_aggregations';
    const VIEW_MERCHANT_TAGS                  = 'view_merchant_tags';
    const CREATE_PRICING_PLAN                 = 'create_pricing_plan';
    const SET_PRICING_RULES                   = 'set_pricing_rules';
    const DELETE_PRICING_PLAN_RULES           = 'delete_pricing_plan_rules';
    const DELETE_EMI_PLAN                     = 'delete_emi_plan';
    const CREATE_EMI_PLAN                     = 'create_emi_plan';
    const CREATE_MERCHANT_LOCK                = 'create_merchant_lock';
    const CREATE_MERCHANT_UNLOCK              = 'create_merchant_unlock';
    const EDIT_MERCHANT                       = 'edit_merchant';
    const EDIT_MERCHANT_TAGS                  = 'edit_merchant_tags';
    const EDIT_MERCHANT_FEATURES              = 'edit_merchant_features';
    const EDIT_MERCHANT_COMMENTS              = 'edit_merchant_comments';
    const EDIT_MERCHANT_BANK_DETAIL           = 'edit_merchant_bank_detail';
    const EDIT_IIN_RULE                       = 'edit_iin_rule';
    const EDIT_ACTIVATE_MERCHANT              = 'edit_activate_merchant';
    const EDIT_MERCHANT_ENABLE_LIVE           = 'edit_merchant_enable_live';
    const EDIT_MERCHANT_DISABLE_LIVE          = 'edit_merchant_disable_live';
    const EDIT_MERCHANT_ENABLE_INTERNATIONAL  = 'edit_merchant_enable_international';
    const EDIT_MERCHANT_DISABLE_INTERNATIONAL = 'edit_merchant_disable_international';
    const EDIT_MERCHANT_ARCHIVE               = 'edit_merchant_archive';
    const EDIT_MERCHANT_UNARCHIVE             = 'edit_merchant_unarchive';
    const EDIT_MERCHANT_SUSPEND               = 'edit_merchant_suspend';
    const EDIT_MERCHANT_UNSUSPEND             = 'edit_merchant_unsuspend';
    const EDIT_MERCHANT_METHODS               = 'edit_merchant_methods';
    const EDIT_MERCHANT_TERMINAL              = 'edit_merchant_terminal';
    const EDIT_MERCHANT_PRICING               = 'edit_merchant_pricing';
    const VIEW_MERCHANT_COMPANY_INFO          = 'view_merchant_company_info';
    const VIEW_MERCHANT_CREDITS_LOG           = 'view_merchant_credits_log';
    const ADD_MERCHANT_CREDITS                = 'add_merchant_credits';
    const DELETE_MERCHANT_CREDITS             = 'delete_merchant_credits';
    const EDIT_MERCHANT_SCREENSHOT            = 'edit_merchant_screenshot';
    const VIEW_PAYMENT_VERIFY                 = 'view_payment_verify';
    const EDIT_VERIFY_PAYMENTS                = 'edit_verify_payments';
    const EDIT_AUTHORIZED_FAILED_PAYMENT      = 'edit_authorized_failed_payment';
    const VIEW_REFUND_PAYMENTS                = 'view_refund_payments';
    const EDIT_AUTHORIZED_REFUND_PAYMENT      = 'edit_authorized_refund_payment';
    const RETRY_REFUND_FAILED                 = 'retry_refund_failed';
    const EDIT_PAYMENT_REFUND                 = 'edit_payment_refund';
    const EDIT_PAYMENT_CAPTURE                = 'edit_payment_capture';
    const EDIT_MERCHANT_CONFIRM               = 'edit_merchant_confirm';
    const CREATE_BENEFICIARY_FILE             = 'create_beneficiary_file';
    const CREATE_NETBANKING_REFUND            = 'create_netbanking_refund';
    const CREATE_EMI_FILES                    = 'create_emi_files';
    const CREATE_SETTLEMENT_INITIATE          = 'create_settlement_initiate';
    const DELETE_TERMINAL                     = 'delete_terminal';
    const EDIT_TERMINAL                       = 'edit_terminal';
    const CREATE_SETTLEMENTS_RECONCILE        = 'create_settlements_reconcile';
    const RETRY_SETTLEMENT                    = 'retry_settlement';
    const EDIT_MERCHANT_INVOICE_GSTIN         = 'edit_merchant_invoice_gstin';
    const CREATE_RECONCILIATE                 = 'create_reconciliate';
    const VIEW_ACTIVATION_FORM                = 'view_activation_form';
    const EDIT_MERCHANT_LOCK_ACTIVATION       = 'edit_merchant_lock_activation';
    const EDIT_MERCHANT_UNLOCK_ACTIVATION     = 'edit_merchant_unlock_activation';
    const EDIT_MERCHANT_HOLD_FUNDS            = 'edit_merchant_hold_funds';
    const EDIT_MERCHANT_RELEASE_FUNDS         = 'edit_merchant_release_funds';
    const EDIT_MERCHANT_ENABLE_RECEIPT        = 'edit_merchant_enable_receipt';
    const EDIT_MERCHANT_DISABLE_RECEIPT       = 'edit_merchant_disable_receipt';
    const EDIT_BULK_MERCHANT_HOLD_FUNDS       = 'edit_bulk_merchant_hold_funds';
    const ASSIGN_MERCHANT_TERMINAL            = 'assign_merchant_terminal';
    const ASSIGN_MERCHANT_BANKS               = 'assign_merchant_banks';
    const ADD_MERCHANT_ADJUSTMENT             = 'add_merchant_adjustment';
    const EDIT_MERCHANT_EMAIL                 = 'edit_merchant_email';
    const MERCHANT_AUTOFILL_FORM              = 'merchant_autofill_form';
    const EDIT_MERCHANT_MARK_REFERRED         = 'edit_merchant_mark_referred';
    const VIEW_AS_ENTITY                      = 'view_as_entity';
    const VIEW_MERCHANT_REFERRER              = 'view_merchant_referrer';
    const VIEW_MERCHANT_BALANCE_TEST          = 'view_merchant_balance_test';
    const VIEW_MERCHANT_BALANCE_LIVE          = 'view_merchant_balance_live';
    const ADD_RECONCILIATION_FILE             = 'add_reconciliation_file';
    const ADD_SETTLEMENT_RECONCILIATION       = 'add_settlement_reconciliation';
    const SEND_NEWSLETTER                     = 'send_newsletter';
    const TRIGGER_DUMMY_ERROR                 = 'trigger_dummy_error';
    const MAKE_API_CALL                       = 'make_api_call';
    const SCHEDULE_CREATE                     = 'schedule_create';
    const SCHEDULE_FETCH                      = 'schedule_fetch';
    const SCHEDULE_FETCH_MULTIPLE             = 'schedule_fetch_multiple';
    const SCHEDULE_DELETE                     = 'schedule_delete';
    const SCHEDULE_UPDATE                     = 'schedule_update';
    const SCHEDULE_ASSIGN                     = 'schedule_assign';
    const SCHEDULE_MIGRATION                  = 'schedule_migration';
    const VIEW_ACTIONS                        = 'view_actions';
    const VIEW_MERCHANT_STATS                 = 'view_merchant_stats';
    const VIEW_ALL_ENTITY                     = 'view_all_entity';
    const VIEW_ALL_ORG                        = 'view_all_org';
    const VIEW_ORG                            = 'view_org';
    const CREATE_ORG                          = 'create_org';
    const EDIT_ORG                            = 'edit_org';
    const DELETE_ORG                          = 'delete_org';
    const VIEW_ALL_ROLE                       = 'view_all_role';
    const VIEW_ROLE                           = 'view_role';
    const CREATE_ROLE                         = 'create_role';
    const EDIT_ROLE                           = 'edit_role';
    const DELETE_ROLE                         = 'delete_role';
    const VIEW_ALL_GROUP                      = 'view_all_group';
    const VIEW_GROUP                          = 'view_group';
    const CREATE_GROUP                        = 'create_group';
    const EDIT_GROUP                          = 'edit_group';
    const DELETE_GROUP                        = 'delete_group';
    const GROUP_GET_ALLOWED_GROUPS            = 'group_get_allowed_groups';
    const VIEW_ALL_ADMIN                      = 'view_all_admin';
    const VIEW_ADMIN                          = 'view_admin';
    const CREATE_ADMIN                        = 'create_admin';
    const EDIT_ADMIN                          = 'edit_admin';
    const DELETE_ADMIN                        = 'delete_admin';
    const VIEW_AUDITLOG                       = 'view_auditlog';
    const VIEW_ALL_PERMISSION                 = 'view_all_permission';
    const GET_PERMISSION                      = 'get_permission';
    const DELETE_PERMISSION                   = 'delete_permission';
    const CREATE_PERMISSION                   = 'create_permission';
    const EDIT_PERMISSION                     = 'edit_permission';
    const DELETE_MERCHANT_FEATURES            = 'delete_merchant_features';
    const CREATE_MERCHANT_INVITE              = 'create_merchant_invite';
    const EDIT_MERCHANT_INVITE                = 'edit_merchant_invite';
    const VIEW_MERCHANT_INVITE                = 'view_merchant_invite';
    const VIEW_WORKFLOW                       = 'view_workflow';
    const CREATE_WORKFLOW                     = 'create_workflow';
    const VIEW_ALL_WORKFLOW                   = 'view_all_workflow';
    const EDIT_WORKFLOW                       = 'edit_workflow';
    const DELETE_WORKFLOW                     = 'delete_workflow';
    const VIEW_WORKFLOW_REQUESTS              = 'view_workflow_requests';
    const CREATE_GATEWAY_RULE                 = 'create_gateway_rule';
    const EDIT_GATEWAY_RULE                   = 'edit_gateway_rule';
    const DELETE_GATEWAY_RULE                 = 'delete_gateway_rule';
    const VIEW_GATEWAY_RULE                   = 'view_gateway_rule';
    const VIEW_MERCHANT_REPORT                = 'view_merchant_report';
    const CREATE_MERCHANT_OFFER               = 'create_merchant_offer';
    const EDIT_MERCHANT_OFFER                 = 'edit_merchant_offer';
    const ASSIGN_MERCHANT_HANDLE              = 'assign_merchant_handle';
    const VIEW_MERCHANT_PRICING               = 'view_merchant_pricing';
    const CREATE_DISPUTE                      = 'create_dispute';
    const EDIT_DISPUTE                        = 'edit_dispute';
    const VIEW_WALLET_CONFIG                  = 'view_wallet_config';
    const CREATE_WALLET_CONFIG                = 'create_wallet_config';
    const EDIT_WALLET_CONFIG                  = 'edit_wallet_config';
    const MERCHANT_BATCH_UPLOAD               = 'merchant_batch_upload';
    const CREATE_DISPUTE_REASON               = 'create_dispute_reason';
    const MANAGE_ONBOARDING_SUBMISSIONS       = 'manage_onboarding_submissions';

    public static $actionMap = [
        Merchant\Action::ARCHIVE                => self::EDIT_MERCHANT_ARCHIVE,
        Merchant\Action::UNARCHIVE              => self::EDIT_MERCHANT_UNARCHIVE,
        Merchant\Action::SUSPEND                => self::EDIT_MERCHANT_SUSPEND,
        Merchant\Action::UNSUSPEND              => self::EDIT_MERCHANT_UNSUSPEND,
        Merchant\Action::LOCK                   => self::EDIT_MERCHANT_LOCK_ACTIVATION,
        Merchant\Action::UNLOCK                 => self::EDIT_MERCHANT_UNLOCK_ACTIVATION,
        Merchant\Action::EDIT_COMMENT           => self::EDIT_MERCHANT_COMMENTS,
        Merchant\Action::HOLD_FUNDS             => self::EDIT_MERCHANT_HOLD_FUNDS,
        Merchant\Action::RELEASE_FUNDS          => self::EDIT_MERCHANT_RELEASE_FUNDS,
        Merchant\Action::ENABLE_RECEIPT_EMAILS  => self::EDIT_MERCHANT_ENABLE_RECEIPT,
        Merchant\Action::DISABLE_RECEIPT_EMAILS => self::EDIT_MERCHANT_DISABLE_RECEIPT,
        Merchant\Action::ENABLE_INTERNATIONAL   => self::EDIT_MERCHANT_ENABLE_INTERNATIONAL,
        Merchant\Action::DISABLE_INTERNATIONAL  => self::EDIT_MERCHANT_DISABLE_INTERNATIONAL,
    ];
}
