<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important;"><head style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important;"><meta http-equiv="Content-Type" content="text/html; charset=utf-8" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important;"><meta name="viewport" content="width=device-width" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important;"></head><body class="body" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; margin: 0; min-width: 100%; padding: 0; width: 100% !important; color: #222222; font-weight: normal; line-height: 19px; text-align: left; font-size: 14px; background: #EBECEE;">
    <table class="container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px; background: #EBECEE;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
          <!-- Text Header -->
          <table class="container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row bluebg" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; background: #39ACE5; position: relative; width: 100%; display: block;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper offset-by-two" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative; padding-left: 100px;">
                      <table class="eight columns " style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 380px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                            <center style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; min-width: 380px; width: 100%;">
                              <h2 class="center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; font-weight: bold; line-height: 1.3; margin: 0; padding: 0; text-align: center; word-break: normal; font-size: 20px; color: white;">
                                Daily Transaction Report
                              </h2>
                            </center>
                            <center class="whitetext" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; min-width: 380px; width: 100%; color: #f2f2f2; text-align: center;">
                            for {{$date}}
                            </center>
                          </td>
                          <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                        </tr></table></td>
                  </tr></table></td>
            </tr></table><!-- Header Subtext --><table class="container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row bluebg" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; background: #39ACE5; position: relative; width: 100%; display: block;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper offset-by-two" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative; padding-left: 100px; background: #39ACE5;">
                      <table class="eight columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 380px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                            <center style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; min-width: 380px; width: 100%;">
                            <h2 class="center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; font-weight: bold; line-height: 1.3; margin: 0; padding: 0; text-align: center; word-break: normal; font-size: 20px; color: white;">
                              {{{$merchant['billing_label']}}}
                            </h2>
                            </center>
                          </td>
                          <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                        </tr></table></td>
                  </tr></table></td>
            </tr></table><table class="container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row bluebg" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; background: #39ACE5; position: relative; width: 100%; display: block;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper whitetext" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; color: #f2f2f2; position: relative;">
                      <table class="four columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;"><center style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; min-width: 180px; width: 100%;">
                            Captured: {{{$captured['payments']['count']}}}<br style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important;">
                            INR {{{number_format($captured['sum']/100, 2)}}}
                          </center></td>
                        </tr></table></td>
                    <td class="wrapper whitetext" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; color: #f2f2f2; position: relative;">
                      <table class="four columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;"><center style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; min-width: 180px; width: 100%;">
                            Authorized: {{{$authorized['payments']['count']}}}<br style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important;">
                            INR {{{number_format($authorized['sum']/100, 2)}}}
                          </center></td>
                        </tr></table></td>
                    <td class="wrapper last whitetext" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; color: #f2f2f2; position: relative; padding-right: 0px;">
                      <table class="four columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;"><center style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; min-width: 180px; width: 100%;">
                            Refunds: {{{$refunds['refunds']['count']}}}<br style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important;">
                            INR {{{number_format($refunds['sum']/100, 2)}}}
                          </center></td>
                        </tr></table></td>
                    <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                  </tr></table></td>
            </tr></table><!-- Header Subtext --><table class="container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row bluebg" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; background: #39ACE5; position: relative; width: 100%; display: block;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper offset-by-four" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative; padding-left: 200px;">
                      <table class="four columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                            <table class="small-button" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; overflow: hidden; width: 100%;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 8px 0 7px; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #2F87C7; border-bottom: 2px solid #2C7CAF; color: #f2f2f2; display: block; margin-bottom: 1em; width: auto !important;">
                                  <a title="Open Dashboard" href="https://dashboard.razorpay.com" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; color: #f2f2f2; text-decoration: none; font-size: 12px;">Open Dashboard</a>
                                </td>
                              </tr></table></td>
                        </tr></table></td>
                  </tr></table></td>
            </tr></table>
@if($captured['payments']['count'] > 0)
          <table class="white container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; background: #ffffff; background-color: #ffffff; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><td class="shortwrapper last" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative; padding-right: 0px;">
                    <table class="twelve columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="white left-text-pad right-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; padding-left: 45px; padding-right: 45px;">
                          <h3 style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; font-weight: bold; line-height: 1.3; margin: 0; padding: 0; text-align: left; word-break: normal; font-size: 16px; color: #39ACE5; margin-top: 10px;">Captured Payments</h3>
                        </td>
                        <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                      </tr></table></td>
                </table></td>
            </tr></table><table class="white container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; background: #ffffff; background-color: #ffffff; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><td class="shortwrapper" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative;">
                    <table class="five columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 230px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="lighttext left-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2; text-decoration: none; padding-left: 45px;">Payment ID</td>
                      </tr></table></td>
                  <td class="shortwrapper" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative;">
                    <table class="three columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 130px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="lighttext center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2; text-decoration: none;">Time</td>
                      </tr></table></td>
                  <td class="shortwrapper last" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative; padding-right: 0px;">
                    <table class="four columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="lighttext right-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2; text-decoration: none; padding-right: 45px;">Amount</td>
                        <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                      </tr></table></td>
                </table></td>
            </tr>
          @foreach ($captured['payments']['items'] as $payment)
          <table class="white container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; background: #ffffff; background-color: #ffffff; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><td class="shortwrapper" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative;">
                    <table class="five columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 230px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="darktext left-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C; padding-left: 45px;">
                          <a href="https://dashboard.razorpay.com/#/app/payments/{{{$payment['public_id']}}}" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; color: #39ACE5; text-decoration: none;">
                          {{{$payment['public_id']}}}
                          </a>
                        </td>
                      </tr></table></td>
                  <td class="shortwrapper" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative;">
                    <table class="three columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 130px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="darktext center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C;">
                          {{{\Carbon\Carbon::createFromTimeStamp($payment['captured_at'], "Asia/Kolkata")->format('h:i a')}}}
                        </td>
                      </tr></table></td>
                  <td class="shortwrapper last" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative; padding-right: 0px;">
                    <table class="four columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="darktext right-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C; padding-right: 45px;">INR {{{number_format($payment['amount']/100, 2)}}}</td>
                        <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                      </tr></table></td>
                </table></td>
            </tr></table>
          @endforeach
          <!-- Note that separator is part of captured section -->
@endif
@if ($authorized['payments']['count'] > 0)
          <table class="white container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; background: #ffffff; background-color: #ffffff; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><td class="shortwrapper last" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative; padding-right: 0px;">
                    <table class="twelve columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="white left-text-pad right-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; padding-left: 45px; padding-right: 45px;">
                          <h3 style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; font-weight: bold; line-height: 1.3; margin: 0; padding: 0; text-align: left; word-break: normal; font-size: 16px; color: #39ACE5; margin-top: 10px;">Authorized Payments</h3>
                        </td>
                        <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                      </tr></table></td>
                </table></td>
            </tr></table><table class="white container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; background: #ffffff; background-color: #ffffff; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><td class="shortwrapper" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative;">
                    <table class="five columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 230px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="lighttext left-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2; text-decoration: none; padding-left: 45px;">Payment ID</td>
                      </tr></table></td>
                  <td class="shortwrapper" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative;">
                    <table class="three columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 130px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="lighttext center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2; text-decoration: none;">Time</td>
                      </tr></table></td>
                  <td class="shortwrapper last" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative; padding-right: 0px;">
                    <table class="four columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="lighttext right-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2; text-decoration: none; padding-right: 45px;">Amount</td>
                        <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                      </tr></table></td>
                </table></td>
            </tr>
          @foreach ($authorized['payments']['items'] as $payment)
          <table class="white container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; background: #ffffff; background-color: #ffffff; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><td class="shortwrapper" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative;">
                    <table class="five columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 230px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="darktext left-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C; padding-left: 45px;">
                          <a href="https://dashboard.razorpay.com/#/app/payments/{{{$payment['public_id']}}}" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; color: #39ACE5; text-decoration: none;">
                          {{{$payment['public_id']}}}
                          </a>
                        </td>
                      </tr></table></td>
                  <td class="shortwrapper" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative;">
                    <table class="three columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 130px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="darktext center" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: center; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C;">
                          {{{\Carbon\Carbon::createFromTimeStamp($payment['authorized_at'], "Asia/Kolkata")->format('j M h:i a')}}}
                        </td>
                      </tr></table></td>
                  <td class="shortwrapper last" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 1em; margin: 0; font-size: 12px; position: relative; padding-right: 0px;">
                    <table class="four columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="darktext right-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C; padding-right: 45px;">INR {{{number_format($payment['amount']/100, 2)}}}</td>
                        <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                      </tr></table></td>
                </table></td>
            </tr></table>
          @endforeach
          <!-- Note that separator is part of authorized section -->

@endif
@if($settlement)
<!-- Settlement Section -->
          <table class="white container" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; background: #ffffff; background-color: #ffffff; margin: 0 auto; width: 580px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <table class="row" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative;">
                      <table class="ten columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 480px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="white left-text-pad right-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; padding-left: 45px; padding-right: 45px;">
                            <a href="https://dashboard.razorpay.com/#/app/settlements/list" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; color: #39ACE5; text-decoration: none;"><h3 style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; font-weight: bold; line-height: 1.3; margin: 0; padding: 0; text-align: left; word-break: normal; font-size: 16px; color: #39ACE5; margin-top: 10px;">Settlements</h3></a>
                          </td>
                          <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                        </tr></table></td>
                  </tr></table><table class="row" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative;">
                      <table class="four columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                            <p class="left-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; margin: 0; font-weight: normal; line-height: 19px; padding: 0; text-align: left; font-size: 14px; margin-bottom: 10px; padding-left: 45px;">
                              Settled Amount
                            </p>
                            <p class="left-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; margin: 0; font-weight: normal; line-height: 19px; padding: 0; text-align: left; font-size: 14px; margin-bottom: 10px; padding-left: 45px;">
                              Account Number
                            </p>
                          </td>
                          <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                        </tr></table></td>
                    <td class="wrapper last" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative; padding-right: 0px;">

                      <table class="eight columns" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 380px;"><tr style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; padding: 0; text-align: left; vertical-align: top;"><td class="lighttext" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2; text-decoration: none;">
                            <p class="right-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; margin: 0; font-weight: normal; line-height: 19px; padding: 0; text-align: right; font-size: 14px; margin-bottom: 10px; padding-right: 45px;">
                              INR {{{number_format($settlement['amount']/100, 2)}}}
                            </p>
                            <p class="right-text-pad" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; margin: 0; font-weight: normal; line-height: 19px; padding: 0; text-align: right; font-size: 14px; margin-bottom: 10px; padding-right: 45px;">
                              {{{$account_number}}}
                            </p>
                          </td>
                          <td class="expander" style="font-family: Geneva, 'Lucida', 'Lucida Sans', 'Lucida Grande', Arial, Tahoma, Verdana, sans-serif !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                        </tr></table></td>
                  </tr></table></td>
            </tr></table><!-- There is no separator after settlements -->
@endif


        
      
    </table></table></td></tr></table></body></html>
