<?php

namespace RZP\Models\Merchant\Detail\BusinessCategoriesV2;

class BusinessSubcategory
{
    const OTHERS = 'others';

    // Business Subcategory Codes
    const ACCOMMODATION                   = 'accommodation';
    const ACCOUNTING                      = 'accounting';
    const AD_AND_MARKETING                = 'ad_and_marketing';
    const AGRICULTURE                     = 'agriculture';
    const ALCOHOL                         = 'alcohol';
    const ARTS_AND_COLLECTIBLES           = 'arts_and_collectibles';
    const AVIATION                        = 'aviation';

    const BABY_PRODUCTS                   = 'baby_products';
    const BETTING                         = 'betting';
    const BILL_AND_RECHARGE_AGGREGATORS   = 'bill_and_recharge_aggregators';
    const BOOKS                           = 'books';
    const BROADBAND                       = 'broadband';
    const BUS                             = 'bus';

    const CABLE                           = 'cable';
    const CAB_HAILING                     = 'cab_hailing';
    const CATERING                        = 'catering';
    const CENTRAL                         = 'central';
    const CHARITY                         = 'charity';
    const CLINIC                          = 'clinic';
    const COACHING                        = 'coaching';
    const COLLEGE                         = 'college';
    const COMMODITIES                     = 'commodities';
    const CONSULTING                      = 'consulting';
    const CONSULTING_AND_OUTSOURCING      = 'consulting_and_outsourcing';
    const CONTENT_AND_PUBLISHING          = 'content_and_publishing';
    const COOPERATIVES                    = 'cooperatives';
    const COUPONS                         = 'coupons';
    const COURIER                         = 'courier';
    const COWORKING                       = 'coworking';
    const CROWDFUNDING                    = 'crowdfunding';
    const CRYPTOCURRENCY                  = 'cryptocurrency';
    const CRYPTO_MACHINERY                = 'crypto_machinery';

    const DAY_CARE                        = 'day_care';
    const DEVELOPER                       = 'developer';
    const DIETICIAN                       = 'dietician';
    const DISTANCE_LEARNING               = 'distance_learning';
    const DISTRIBUTION                    = 'distribution';
    const DROP_SHIPPING                   = 'drop_shipping';
    const DTH                             = 'dth';

    const ECOMMERCE_MARKETPLACE           = 'ecommerce_marketplace';
    const EDUCATIONAL                     = 'educational';
    const ELEARNING                       = 'elearning';
    const ELECTRICITY                     = 'electricity';
    const ELECTRONICS_AND_FURNITURE       = 'electronics_and_furniture';
    const END_TO_END_LOGISTICS            = 'end_to_end_logistics';
    const ESPORTS                         = 'esports';
    const EVENT_PLANNING                  = 'event_planning';

    const FACILITY_MANAGEMENT             = 'facility_management';
    const FANTASY_SPORTS                  = 'fantasy_sports';
    const FASHION_AND_LIFESTYLE           = 'fashion_and_lifestyle';
    const FINANCIAL_ADVISOR               = 'financial_advisor';
    const FITNESS                         = 'fitness';
    const FOOD_COURT                      = 'food_court';
    const FOREX                           = 'forex';
    const FREIGHT                         = 'freight';

    const GAME_DEVELOPER                  = 'game_developer';
    const GAMING_MARKETPLACE              = 'gaming_marketplace';
    const GAS                             = 'gas';
    const GET_RICH_SCHEMES                = 'get_rich_schemes';
    const GIFTING                         = 'gifting';
    const GROCERY                         = 'grocery';

    const HEALTH_COACHING                 = 'health_coaching';
    const HEALTH_PRODUCTS                 = 'health_products';
    const HEALTHCARE_MARKETPLACE          = 'healthcare_marketplace';
    const HOSPITAL                        = 'hospital';

    const IAAS                            = 'iaas';
    const INSURANCE                       = 'insurance';
    const INTERIOR_DESIGN_AND_ARCHITECT   = 'interior_design_and_architect';
    const INTERNET_PROVIDER               = 'internet_provider';

    const LAB                             = 'lab';
    const LEGAL                           = 'legal';
    const LENDING                         = 'lending';

    const MATCHMAKING                     = 'matchmaking';
    const MESSAGING                       = 'messaging';
    const MOVERS_AND_PACKERS              = 'movers_and_packers';
    const MULTI_LEVEL_MARKETING           = 'multi_level_marketing';
    const MULTIPLEX                       = 'multiplex';
    const MUSIC_STREAMING                 = 'music_streaming';
    const MUTUAL_FUND                     = 'mutual_fund';

    const NBFC                            = 'nbfc';
    const NEIGHBOURHOOD_NETWORK           = 'neighbourhood_network';
    const NEWS                            = 'news';

    const OFFICE_SUPPLIES                 = 'office_supplies';
    const ONLINE_CASINO                   = 'online_casino';
    const ONLINE_FOOD_ORDERING            = 'online_food_ordering';
    const OTA                             = 'ota';

    const PAAS                            = 'paas';
    const PENSION_FUND                    = 'pension_fund';
    const PERSONAL                        = 'personal';
    const PET_PRODUCTS                    = 'pet_products';
    const PHARMACY                        = 'pharmacy';
    const PROFESSIONAL_COURSES            = 'professional_courses';
    const PROFESSIONAL_NETWORK            = 'professional_network';

    const REALESTATE_CLASSIFIEDS          = 'realestate_classifieds';
    const RELIGIOUS                       = 'religious';
    const RELIGIOUS_PRODUCTS              = 'religious_products';
    const RENTAL                          = 'rental';
    const REPAIR_AND_CLEANING             = 'repair_and_cleaning';
    const RESTAURANT                      = 'restaurant';
    const RESTAURANT_SEARCH_AND_BOOKING   = 'restaurant_search_and_booking';
    const RWA                             = 'rwa';

    const SAAS                            = 'saas';
    const SCHOOLS                         = 'schools';
    const SECURITIES                      = 'securities';
    const SERVICE_CENTRE                  = 'service_centre';
    const SERVICES_CLASSIFIEDS            = 'services_classifieds';
    const SEXUAL_WELLNESS_PRODUCTS        = 'sexual_wellness_products';
    const SOCIAL_NETWORK                  = 'social_network';
    const SPACE_RENTAL                    = 'space_rental';
    const SPORTS_PRODUCTS                 = 'sports_products';
    const STATE                           = 'state';

    const TECHNICAL_SUPPORT               = 'technical_support';
    const TELECOM                         = 'telecom';
    const TICKETING                       = 'ticketing';
    const TOBACCO                         = 'tobacco';
    const TRADING                         = 'trading';
    const TRAIN_AND_METRO                 = 'train_and_metro';
    const TRAVEL_AGENCY                   = 'travel_agency';

    const UNIVERSITY                      = 'university';

    const VIDEO_ON_DEMAND                 = 'video_on_demand';

    const WAREHOUSING                     = 'warehousing';
    const WATER                           = 'water';
    const WEAPONS_AND_AMMUNITIONS         = 'weapons_and_ammunitions';
    const WEB_DEVELOPMENT                 = 'web_development';
    const WHOLESALE                       = 'wholesale';

    const COMPUTER_PROGRAMMING_DATA_PROCESSING = 'computer_programming_data_processing';
    const UTILITIES_ELECTRIC_GAS_OIL_WATER     = 'utilities_electric_gas_oil_water';

    const  AUTOMOBILE_PARTS_AND_EQUIPEMENTS                   = 'automobile_parts_and_equipements';
    const  COMPUTERS_PERIPHERAL_EQUIPMENT_SOFTWARE            = 'computers_peripheral_equipment_software';
    const  MEDICAL_EQUIPMENT_AND_SUPPLY_STORES                = 'medical_equipment_and_supply_stores';
    const  INDUSTRIAL_SUPPLIES                                = 'industrial_supplies';
    const  JEWELLERY_AND_WATCH_STORES                         = 'jewellery_and_watch_stores';
    const  AUTOMOBILE_AND_TRUCK_DEALERS                       = 'automobile_and_truck_dealers';
    const  SHOE_STORES_RETAIL                                 = 'shoe_stores_retail';
    const  ACCESSORY_AND_APPAREL_STORES                       = 'accessory_and_apparel_stores';
    const  FURNITURE_AND_HOME_FURNISHING_STORE                = 'furniture_and_home_furnishing_store';
    const  COSMETIC_STORES                                    = 'cosmetic_stores';
    const  RECREATIONAL_AND_SPORTING_CAMPS                    = 'recreational_and_sporting_camps';
    const  PHOTOGRAPHIC_STUDIO                                = 'photographic_studio';
    const  AUTOMOBILE_RENTALS                                 = 'automobile_rentals';
    const  HEALTH_PRACTITIONERS_MEDICAL_SERVICES              = 'health_practitioners_medical_services';
    const  DATA_PROCESSING                                    = 'data_processing';
    const  PROFESSIONAL_SERVICES                              = 'professional_services';
    const  ASSOCIATIONS_AND_MEMBERSHIP                        = 'associations_and_membership';

    //new business_subcategory
    const  AUTOMOBILE_ASSOCIATIONS_AND_CLUBS                  = 'automobile_associations_and_clubs';
    const  CONSTRUCTION_SERVICES                              = 'construction_services';
    const  STAMPS_AND_COINS_STORES                            = 'stamps_and_coins_stores';
    const  VOCATIONAL_AND_TRADE_SCHOOLS                       = 'vocational_and_trade_schools';
    const  SPORTING_CLUBS                                     = 'sporting_clubs';
    const  ARCHITECTURAL_SERVICES                             = 'architectural_services';
    const  CAR_WASHES                                         = 'car_washes';
    const  OFFICE_EQUIPMENT                                   = 'office_equipment';
    const  MOTOR_HOME_RENTALS                                 = 'motor_home_rentals';
    const  GARDEN_SUPPLY_STORES                               = 'garden_supply_stores';
    const  HOUSEHOLD_APPLIANCE_STORES                         = 'household_appliance_stores';
    const  DAIRY_PRODUCTS                                     = 'dairy_products';
    const  NON_DURABLE_GOODS                                  = 'non_durable_goods';
    const  ELECTRICAL_PARTS_AND_EQUIPMENT                     = 'electrical_parts_and_equipment';
    const  BAKERIES                                           = 'bakeries';
    const  STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES      = 'stenographic_and_secretarial_support_services';
    const  CHIROPRACTORS                                      = 'chiropractors';
    const  WIG_AND_TOUPEE_SHOPS                               = 'wig_and_toupee_shops';
    const  GIFT_NOVELTY_AND_SOUVENIR_SHOPS                    = 'gift_novelty_and_souvenir_shops';
    const  AUTOMOTIVE_SERVICE_SHOPS                           = 'automotive_service_shops';
    const  SHOE_REPAIR_SHOPS                                  = 'shoe_repair_shops';
    const  TELECOMMUNICATION_SERVICE                          = 'telecommunication_service';
    const  DUTY_FREE_STORES                                   = 'duty_free_stores';
    const  FINES                                              = 'fines';
    const  CRUISE_LINES                                       = 'cruise_lines';
    const  OFFICE_AND_COMMERCIAL_FURNITURE                    = 'office_and_commercial_furniture';
    const  DANCE_HALLS_STUDIOS_AND_SCHOOLS                    = 'dance_halls_studios_and_schools';
    const  SECURITY_AGENCIES                                  = 'security_agencies';
    const  TYPE_SETTING_AND_ENGRAVING_SERVICES                = 'type_setting_and_engraving_services';
    const  DRY_GOODS                                          = 'dry_goods';
    const  BOOKS_AND_PUBLICATIONS                             = 'books_and_publications';
    const  SMALL_APPLIANCE_REPAIR_SHOPS                       = 'small_appliance_repair_shops';
    const  PHOTOGRAPHY_LABS                                   = 'photography_labs';
    const  CAMERA_AND_PHOTOGRAPHIC_STORES                     = 'camera_and_photographic_stores';
    const  DRY_CLEANERS                                       = 'dry_cleaners';
    const  ELECTRONIC_REPAIR_SHOPS                            = 'electronic_repair_shops';
    const  VIDEO_GAME_ARCADES                                 = 'video_game_arcades';
    const  MEAT_SUPPLY_STORES                                 = 'meat_supply_stores';
    const  LEATHER_GOODS_AND_LUGGAGE                          = 'leather_goods_and_luggage';
    const  CLEANING_AND_SANITATION_SERVICES                   = 'cleaning_and_sanitation_services';
    const  SNOWMOBILE_DEALERS                                 = 'snowmobile_dealers';
    const  VIDEO_TAPE_PRODUCTION_AND_DISTRIBUTION             = 'video_tape_production_and_distribution';
    const  OSTEOPATHS                                         = 'osteopaths';
    const  MEN_AND_BOYS_CLOTHING_STORES                       = 'men_and_boys_clothing_stores';
    const  NURSING_CARE_FACILITIES                            = 'nursing_care_facilities';
    const  DIRECT_MARKETING                                   = 'direct_marketing';
    const  VETERINARY_SERVICES                                = 'veterinary_services';
    const  PAINT_SUPPLY_STORES                                = 'paint_supply_stores';
    const  AFFLIATED_AUTO_RENTAL                              = 'affliated_auto_rental';
    const  ALIMONY_AND_CHILD_SUPPORT                          = 'alimony_and_child_support';
    const  AIRPORT_FLYING_FIELDS                              = 'airport_flying_fields';
    const  TIRE_RETREADING_AND_REPAIR_SHOPS                   = 'tire_retreading_and_repair_shops';
    const  TELEVISION_CABLE_SERVICES                          = 'television_cable_services';
    const  AUTOMOTIVE_PARTS                                   = 'automotive_parts';
    const  AUTO_STORE_HOME_SUPPLY_STORES                      = 'auto_store_home_supply_stores';
    const  TENT_STORES                                        = 'tent_stores';
    const  AGRICULTURAL_COOPERATIVES                          = 'agricultural_cooperatives';
    const  PETROLEUM_AND_PETROLEUM_PRODUCTS                   = 'petroleum_and_petroleum_products';
    const  DEPARTMENT_STORES                                  = 'department_stores';
    const  CARPENTRY_CONTRACTORS                              = 'carpentry_contractors';
    const  MONEYSEND_FUNDING                                  = 'moneysend_funding';
    const  WRECKING_AND_SALVAGING_SERVICES                    = 'wrecking_and_salvaging_services';
    const  AUTOMOBILE_TOWING_SERVICES                         = 'automobile_towing_services';
    const  POLITICAL_ORGANIZATIONS                            = 'political_organizations';
    const  AUTOMOTIVE_TIRE_STORES                             = 'automotive_tire_stores';
    const  BARBER_AND_BEAUTY_SHOPS                            = 'barber_and_beauty_shops';
    const  SPORT_APPAREL_STORES                               = 'sport_apparel_stores';
    const  VIDEO_TAPE_RENTAL_STORES                           = 'video_tape_rental_stores';
    const  DRUG_STORES                                        = 'drug_stores';
    const  GOLF_COURSES                                       = 'golf_courses';
    const  MISCELLANEOUS_REPAIR_SHOPS                         = 'miscellaneous_repair_shops';
    const  MOTOR_HOMES_AND_PARTS                              = 'motor_homes_and_parts';
    const  DEBT_MARRIAGE_PERSONAL_COUNSELING_SERVICE          = 'debt_marriage_personal_counseling_service';
    const  CHEMICALS_AND_ALLIED_PRODUCTS                      = 'chemicals_and_allied_products';
    const  FIREPLACE_PARTS_AND_ACCESSORIES                    = 'fireplace_parts_and_accessories';
    const  COMMERCIAL_EQUIPMENTS                              = 'commercial_equipments';
    const  AIR_CONDITIONING_AND_REFRIGERATION_REPAIR_SHOPS    = 'air_conditioning_and_refrigeration_repair_shops';
    const  FAMILY_CLOTHING_STORES                             = 'family_clothing_stores';
    const  TAILORS                                            = 'tailors';
    const  FABRIC_AND_SEWING_STORES                           = 'fabric_and_sewing_stores';
    const  CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS    = 'camper_recreational_and_utility_trailer_dealers';
    const  TOURIST_ATTRACTIONS_AND_EXHIBITS                   = 'tourist_attractions_and_exhibits';
    const  RECORD_SHOPS                                       = 'record_shops';
    const  HOME_SUPPLY_WAREHOUSE                              = 'home_supply_warehouse';
    const  CLOCKS_AND_SILVERWARE_STORES                       = 'clocks_and_silverware_stores';
    const  ART_SUPPLY_STORES                                  = 'art_supply_stores';
    const  MASSAGE_PARLORS                                    = 'massage_parlors';
    const  HORSE_OR_DOG_RACING                                = 'horse_or_dog_racing';
    const  CREDIT_REPORTING_AGENCIES                          = 'credit_reporting_agencies';
    const  PAWN_SHOPS                                         = 'pawn_shops';
    const  PARKING_LOTS_AND_GARAGES                           = 'parking_lots_and_garages';
    const  SCHOOL_SUPPLIES_AND_STATIONERY                     = 'school_supplies_and_stationery';
    const  HEATING_AND_PLUMBING_CONTRACTORS                   = 'heating_and_plumbing_contractors';
    const  AQUARIUMS_DOLPHINARIUMS_AND_SEAQUARIUMS            = 'aquariums_dolphinariums_and_seaquariums';
    const  ELECTRICAL_CONTRACTORS                             = 'electrical_contractors';
    const  WIRE_TRANSFERS_AND_MONEY_ORDERS                    = 'wire_transfers_and_money_orders';
    const  CARPET_AND_UPHOLSTERY_CLEANING_SERVICES            = 'carpet_and_upholstery_cleaning_services';
    const  OPTICIANS_OPTICAL_GOODS_AND_EYEGLASSE_STORES       = 'opticians_optical_goods_and_eyeglasse_stores';
    const  WATCH_AND_JEWELLERY_REPAIR_STORES                  = 'watch_and_jewellery_repair_stores';
    const  WHOLESALE_FOOTWEAR_STORES                          = 'wholesale_footwear_stores';
    const  ANTIQUE_STORES                                     = 'antique_stores';
    const  ROOFING_AND_METAL_WORK_CONTRACTORS                 = 'roofing_and_metal_work_contractors';
    const  INTERNET_SERVICE_PROVIDERS                         = 'internet_service_providers';
    const  PLUMBING_AND_HEATING_EQUIPMENT                     = 'plumbing_and_heating_equipment';
    const  VARIETY_STORES                                     = 'variety_stores';
    const  LIQUOR_STORES                                      = 'liquor_stores';
    const  BOAT_DEALERS                                       = 'boat_dealers';
    const  RECREATIONAL_CAMPS                                 = 'recreational_camps';
    const  PODIATRISTS_AND_CHIROPODISTS                       = 'podiatrists_and_chiropodists';
    const  TAX_PREPARATION_SERVICES                           = 'tax_preparation_services';
    const  HOME_FURNISHING_STORES                             = 'home_furnishing_stores';
    const  BRIDGE_AND_ROAD_TOLLS                              = 'bridge_and_road_tolls';
    const  TELECOMMUNICATION_EQUIPMENT_STORES                 = 'telecommunication_equipment_stores';
    const  WOMEN_CLOTHING                                     = 'women_clothing';
    const  FLORISTS                                           = 'florists';
    const  COMMERCIAL_PHOTOGRAPHY_AND_GRAPHIC_DESIGN_SERVICES = 'commercial_photography_and_graphic_design_services';
    const  BUILDING_MATRIAL_STORES                            = 'building_matrial_stores';
    const  CANDY_NUT_CONFECTIONERY_SHOPS                      = 'candy_nut_confectionery_shops';
    const  TIMESHARES                                         = 'timeshares';
    const  MASONRY_CONTRACTORS                                = 'masonry_contractors';
    const  EXTERMINATING_AND_DISINFECTING_SERVICES            = 'exterminating_and_disinfecting_services';
    const  GLASS_AND_WALLPAPER_STORES                         = 'glass_and_wallpaper_stores';
    const  VIDEO_GAME_SUPPLY_STORES                           = 'video_game_supply_stores';
    const  AMBULANCE_SERVICES                                 = 'ambulance_services';
    const  FUNERAL_SERVICES_AND_CREMATORIES                   = 'funeral_services_and_crematories';
    const  BOWLING_ALLEYS                                     = 'bowling_alleys';
    const  METAL_SERVICE_CENTRES                              = 'metal_service_centres';
    const  COPYING_AND_BLUEPRINTING_SERVICES                  = 'copying_and_blueprinting_services';
    const  DRAPERY_AND_WINDOW_COVERINGS_STORES                = 'drapery_and_window_coverings_stores';
    const  UNIFORMS_AND_COMMERCIAL_CLOTHING_STORES            = 'uniforms_and_commercial_clothing_stores';
    const  AUTOMOTIVE_PAINT_SHOPS                             = 'automotive_paint_shops';
    const  DURABLE_GOODS_STORES                               = 'durable_goods_stores';
    const  FUR_SHOPS                                          = 'fur_shops';
    const  MOTORCYCLE_SHOPS_AND_DEALERS                       = 'motorcycle_shops_and_dealers';
    const  CHILDREN_AND_INFANTS_WEAR_STORES                   = 'children_and_infants_wear_stores';
    const  CORRESPONDENCE_SCHOOLS                             = 'correspondence_schools';
    const  FREIGHT_TRANSPORT                                  = 'freight_transport';
    const  FUEL_DISPENSERS                                    = 'fuel_dispensers';
    const  TRUCK_AND_UTILITY_TRAILER_RENTALS                  = 'truck_and_utility_trailer_rentals';
    const  BILLIARD_AND_POOL_ESTABLISHMENTS                   = 'billiard_and_pool_establishments';
    const  LOTTERY                                            = 'lottery';
    const  WELDING_REPAIR                                     = 'welding_repair';
    const  COMPUTER_SOFTWARE_STORES                           = 'computer_software_stores';
    const  AMUSEMENT_PARKS_AND_CIRCUSES                       = 'amusement_parks_and_circuses';
    const  MOBILE_HOME_DEALERS                                = 'mobile_home_dealers';
    const  WOMEN_ACCESSORY_STORES                             = 'women_accessory_stores';
    const  BOOKS_PERIODICALS_AND_NEWSPAPER                    = 'books_periodicals_and_newspaper';
    const  FLOOR_COVERING_STORES                              = 'floor_covering_stores';
    const  TAX_PAYMENTS                                       = 'tax_payments';
    const  CRYSTAL_AND_GLASSWARE_STORES                       = 'crystal_and_glassware_stores';
    const  DENTISTS_AND_ORTHODONTISTS                         = 'dentists_and_orthodontists';
    const  HARDWARE_STORES                                    = 'hardware_stores';
    const  HARDWARE_EQUIPMENT_AND_SUPPLY_STORES               = 'hardware_equipment_and_supply_stores';
    const  CONCRETE_WORK_CONTRACTORS                          = 'concrete_work_contractors';
    const  DISCOUNT_STORES                                    = 'discount_stores';
    const  OPHTHALMOLOGISTS                                   = 'ophthalmologists';
    const  BOAT_RENTALS                                       = 'boat_rentals';
    const  PERSONAL_SHOPPERS_AND_SHOPPING_CLUBS               = 'personal_shoppers_and_shopping_clubs';
    const  DOOR_TO_DOOR_SALES                                 = 'door_to_door_sales';
    const  TRAVEL_RELATED_DIRECT_MARKETING                    = 'travel_related_direct_marketing';
    const  LOTTERY_AND_BETTING                                = 'lottery_and_betting';
    const  DIGITAL_GOODS                                      = 'digital_goods';
    const  INTRA_GOVERNMENT_PURCHASES                         = 'intra_government_purchases';
    const  COUNTRY_AND_ATHLETIC_CLUBS                         = 'country_and_athletic_clubs';
    const  BANDS_ORCHESTRAS_AND_MISCELLANEOUS_ENTERTAINERS    = 'bands_orchestras_and_miscellaneous_entertainers';
    const  FURNITURE_REPAIR_AND_REFINISHING                   = 'furniture_repair_and_refinishing';
    const  ORTHOPEDIC_GOODS_STORES                            = 'orthopedic_goods_stores';
    const  DIRECT_MARKETING_AND_SUBSCRIPTION_MERCHANTS        = 'direct_marketing_and_subscription_merchants';
    const  TYPEWRITER_STORES_SALES_SERVICE_AND_RENTALS        = 'typewriter_stores_sales_service_and_rentals';
    const  DIRECT_MARKETING_INSURANCE_SERVICES                = 'direct_marketing_insurance_services';
    const  BUSINESS_SERVICES                                  = 'business_services';
    const  TICKET_AGENCIES                                    = 'ticket_agencies';
    const  AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS                = 'aircraft_and_farm_equipment_dealers';
    const  ANTIQUE_SHOPS_SALES_AND_REPAIRS                    = 'antique_shops_sales_and_repairs';
    const  COURIER_SERVICES                                   = 'courier_services';
    const  BICYCLE_STORES                                     = 'bicycle_stores';
    const  INBOUND_TELEMARKETING_MERCHANTS                    = 'inbound_telemarketing_merchants';
    const  LAUNDRY_SERVICES                                   = 'laundry_services';
    const  HEARING_AIDS_STORES                                = 'hearing_aids_stores';
    const  RECREATION_SERVICES                                = 'recreation_services';
    const  MUSIC_STORES                                       = 'music_stores';
    const  SWIMMING_POOLS                                     = 'swimming_pools';
    const  OUTBOUND_TELEMARKETING_MERCHANTS                   = 'outbound_telemarketing_merchants';
    const  PUBLIC_WAREHOUSING                                 = 'public_warehousing';
    const  CLOTHING_RENTAL_STORES                             = 'clothing_rental_stores';
    const  TRANSPORTATION                                     = 'transportation';
    const  GOVERMENT_POSTAL_SERVICES                          = 'goverment_postal_services';
    const  CONSTRUCTION_MATERIALS                             = 'construction_materials';
    const  TESTING_LABORATORIES                               = 'testing_laboratories';
    const  DOCTORS                                            = 'doctors';
    const  CONTRACTORS                                        = 'contractors';
    const  TRANSPORTATION_SERVICES                            = 'transportation_services';
    const  ATMS                                               = 'atms';
    const  SECOND_HAND_STORES                                 = 'second_hand_stores';
    const  ELECTRIC_RAZOR_STORES                              = 'electric_razor_stores';
    const  FUEL_DEALERS                                       = 'fuel_dealers';
    const  SERVICE_STATIONS                                   = 'service_stations';


    // Business Subcategory Descriptions
    const DESCRIPTIONS = [
        self::ACCOMMODATION                   => 'Hotel or lodging',
        self::ACCOUNTING                      => 'Accounting and taxes',
        self::AD_AND_MARKETING                => 'Ad or marketing agency',
        self::AGRICULTURE                     => 'Agricultural products',
        self::ALCOHOL                         => 'Alcoholic beverages',
        self::ARTS_AND_COLLECTIBLES           => 'Arts, crafts, or collectibles',
        self::AVIATION                        => 'Flights',
        self::BABY_PRODUCTS                   => 'Baby care or toys',
        self::BETTING                         => 'Betting',
        self::BILL_AND_RECHARGE_AGGREGATORS   => 'Bill payment and recharge',
        self::BOOKS                           => 'Bookstore or publication',
        self::BROADBAND                       => 'Broadband',
        self::BUS                             => 'Bus ticketing',
        self::CABLE                           => 'Cable TV',
        self::CAB_HAILING                     => 'Ride hailing',
        self::CATERING                        => 'Caterers',
        self::CENTRAL                         => 'Central govt. body',
        self::CHARITY                         => 'Charity',
        self::CLINIC                          => 'Clinic',
        self::COACHING                        => 'Coaching institute',
        self::COLLEGE                         => 'College(s)',
        self::COMMODITIES                     => 'Commodities',
        self::CONSULTING                      => 'Consulting',
        self::CONSULTING_AND_OUTSOURCING      => 'Consulting or outsourcing',
        self::CONTENT_AND_PUBLISHING          => 'Content or publishing platform',
        self::COOPERATIVES                    => 'Cooperatives',
        self::COUPONS                         => 'Coupons, deals, discounts',
        self::COURIER                         => 'Courier',
        self::COWORKING                       => 'Coworking space(s)',
        self::CROWDFUNDING                    => 'Crowdfunding platform',
        self::CRYPTOCURRENCY                  => 'Cryptocurrency',
        self::CRYPTO_MACHINERY                => 'Cryptocurrency',
        self::DAY_CARE                        => 'Pre-school or day care',
        self::DEVELOPER                       => 'Developer',
        self::DIETICIAN                       => 'Nutritionist or dietitian',
        self::DISTANCE_LEARNING               => 'Distance learning',
        self::DISTRIBUTION                    => 'Distribution management',
        self::DROP_SHIPPING                   => 'Dropshipping',
        self::DTH                             => 'DTH',
        self::ECOMMERCE_MARKETPLACE           => 'Marketplace',
        self::EDUCATIONAL                     => 'Educational',
        self::ELEARNING                       => 'Elearning',
        self::ELECTRICITY                     => 'Electricity',
        self::ELECTRONICS_AND_FURNITURE       => 'Electronics, furniture',
        self::END_TO_END_LOGISTICS            => 'End-to-end logistics',
        self::ESPORTS                         => 'Esports',
        self::EVENT_PLANNING                  => 'Event planning',
        self::FACILITY_MANAGEMENT             => 'Facility management',
        self::FANTASY_SPORTS                  => 'Fantasy sports',
        self::FASHION_AND_LIFESTYLE           => 'Fashion and lifestyle',
        self::FINANCIAL_ADVISOR               => 'Advisory service',
        self::FITNESS                         => 'Gym',
        self::FOOD_COURT                      => 'Food court or corporate cafeteria',
        self::FOREX                           => 'Forex',
        self::FREIGHT                         => 'Freight consolidation, management',
        self::GAME_DEVELOPER                  => 'Game development',
        self::GAMING_MARKETPLACE              => 'Game marketplace',
        self::GAS                             => 'Gas',
        self::GET_RICH_SCHEMES                => 'Money-making scheme',
        self::GIFTING                         => 'Flowers or gifting',
        self::GROCERY                         => 'Groceries',
        self::HEALTH_COACHING                 => 'Health and Lifestyle Coaching',
        self::HEALTH_PRODUCTS                 => 'Healthcare products',
        self::HEALTHCARE_MARKETPLACE          => 'Marketplace',
        self::HOSPITAL                        => 'Hospital',
        self::IAAS                            => 'Infrastructure as a service (IaaS)',
        self::INSURANCE                       => 'Insurance',
        self::INTERIOR_DESIGN_AND_ARCHITECT   => 'Interior design or architect',
        self::INTERNET_PROVIDER               => 'Internet',
        self::LAB                             => 'Diagnostic centre',
        self::LEGAL                           => 'Legal',
        self::LENDING                         => 'Lending',
        self::MATCHMAKING                     => 'Dating or matrimonial platform',
        self::MESSAGING                       => 'Messaging platform',
        self::MOVERS_AND_PACKERS              => 'Packers and movers',
        self::MULTI_LEVEL_MARKETING           => 'Multi-level marketing',
        self::MULTIPLEX                       => 'Multiplex chain',
        self::MUSIC_STREAMING                 => 'Music streaming',
        self::MUTUAL_FUND                     => 'Mutual fund',
        self::NBFC                            => 'NBFC',
        self::NEIGHBOURHOOD_NETWORK           => 'Local or neighbourhood group',
        self::NEWS                            => 'News platform',
        self::OFFICE_SUPPLIES                 => 'Office supplies',
        self::ONLINE_CASINO                   => 'Online casino',
        self::ONLINE_FOOD_ORDERING            => 'Online food ordering',
        self::OTA                             => 'Online travel agency',
        self::OTHERS                          => 'Other',
        self::PAAS                            => 'Platform as a service (PaaS)',
        self::PENSION_FUND                    => 'Pension fund',
        self::PERSONAL                        => 'Personal',
        self::PROFESSIONAL_COURSES            => 'Professional course',
        self::PET_PRODUCTS                    => 'Pet Care and Supplies',
        self::PHARMACY                        => 'Pharmacy',
        self::PROFESSIONAL_NETWORK            => 'Professional group',
        self::REALESTATE_CLASSIFIEDS          => 'Real estate classifieds',
        self::RELIGIOUS                       => 'Religious',
        self::RELIGIOUS_PRODUCTS              => 'Religious products',
        self::RENTAL                          => 'Product rentals',
        self::REPAIR_AND_CLEANING             => 'Repair or cleaning',
        self::RESTAURANT                      => 'Restaurants',
        self::RESTAURANT_SEARCH_AND_BOOKING   => 'Restaurant search and reservations',
        self::RWA                             => 'Resident Welfare Association (RWA)',
        self::SAAS                            => 'Software as a service (SaaS)',
        self::SCHOOLS                         => 'School(s)',
        self::SECURITIES                      => 'Securities',
        self::SERVICE_CENTRE                  => 'Service centre',
        self::SERVICES_CLASSIFIEDS            => 'Services classifieds',
        self::SEXUAL_WELLNESS_PRODUCTS        => 'Intimate products',
        self::SOCIAL_NETWORK                  => 'Social networking platform',
        self::SPACE_RENTAL                    => 'Home or office rentals',
        self::SPORTS_PRODUCTS                 => 'Sports and fitness',
        self::STATE                           => 'State govt. body',
        self::TECHNICAL_SUPPORT               => 'Technical support',
        self::TELECOM                         => 'Telecom',
        self::TICKETING                       => 'Movie or event ticketing',
        self::TOBACCO                         => 'Tobacco',
        self::TRADING                         => 'Stock brokerage and trading',
        self::TRAIN_AND_METRO                 => 'Train or metro ticketing',
        self::TRAVEL_AGENCY                   => 'Tours and travel agency',
        self::UNIVERSITY                      => 'University',
        self::VIDEO_ON_DEMAND                 => 'Video on demand',
        self::WATER                           => 'Water',
        self::WAREHOUSING                     => 'Warehousing',
        self::WEAPONS_AND_AMMUNITIONS         => 'Weapons, ammunitions',
        self::WEB_DEVELOPMENT                 => 'Web design, development, hosting',
        self::WHOLESALE                       => 'Wholesale',

        //new business_subcategory
        self::CONSTRUCTION_SERVICES                              => 'GENERAL CONTRACTORS',
        self::STAMPS_AND_COINS_STORES                            => 'Stamps & Coins Stores',
        self::AUTOMOBILE_PARTS_AND_EQUIPEMENTS                   => 'MOTOR VEHICLE SUPPLIES',
        self::VOCATIONAL_AND_TRADE_SCHOOLS                       => 'SCHOOLS, TRADE AND VOCATIONAL',
        self::SPORTING_CLUBS                                     => 'ATHLETIC FEES',
        self::ARCHITECTURAL_SERVICES                             => 'Horticultural and Landscaping Services',
        self::CAR_WASHES                                         => 'CAR WASHES',
        self::OFFICE_EQUIPMENT                                   => 'Office, Photographic, Photocopy, and Microfilm Equipment',
        self::MOTOR_HOME_RENTALS                                 => 'A MOTOR HOME AND RECREATIONAL',
        self::GARDEN_SUPPLY_STORES                               => 'Lawn and Garden Supply Stores',
        self::HOUSEHOLD_APPLIANCE_STORES                         => 'Household Appliance Stores',
        self::DAIRY_PRODUCTS                                     => 'Dairy Products Stores',
        self::NON_DURABLE_GOODS                                  => 'NONDURABLE GOODS',
        self::ELECTRICAL_PARTS_AND_EQUIPMENT                     => 'Electrical Parts and Equipment',
        self::BAKERIES                                           => 'Bakeries',
        self::STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES      => 'Stenographic and Secretarial Support Services',
        self::CHIROPRACTORS                                      => 'Chiropractors',
        self::WIG_AND_TOUPEE_SHOPS                               => 'Wig and Toupee Shops',
        self::GIFT_NOVELTY_AND_SOUVENIR_SHOPS                    => 'Card, Gift, Novelty, and Souvenir Shops',
        self::AUTOMOTIVE_SERVICE_SHOPS                           => 'Automotive Service Shops',
        self::SHOE_REPAIR_SHOPS                                  => 'Hat Cleaning Shops, Shoe Repair Shops, Shoe Shine Parlors',
        self::TELECOMMUNICATION_SERVICE                          => 'Telecommunication',
        self::DUTY_FREE_STORES                                   => 'Duty Free Stores',
        self::FINES                                              => 'FINES',
        self::CRUISE_LINES                                       => 'CRUISE LINES',
        self::OFFICE_AND_COMMERCIAL_FURNITURE                    => 'Office and Commercial Furniture',
        self::DANCE_HALLS_STUDIOS_AND_SCHOOLS                    => 'Dance Halls, Studios and Schools',
        self::SECURITY_AGENCIES                                  => 'Agencies – Security Services',
        self::TYPE_SETTING_AND_ENGRAVING_SERVICES                => 'Typesetting, Plate Making, Related Services',
        self::DRY_GOODS                                          => 'Piece Goods, Notions, and Other Dry Goods',
        self::BOOKS_AND_PUBLICATIONS                             => 'Book Stores',
        self::SMALL_APPLIANCE_REPAIR_SHOPS                       => 'Appliance Repair Shops, Electrical and Small',
        self::PHOTOGRAPHY_LABS                                   => 'Photo Developing, Photofinishing Laboratories',
        self::CAMERA_AND_PHOTOGRAPHIC_STORES                     => 'Camera and Photographic Supply Stores',
        self::DRY_CLEANERS                                       => 'Dry Cleaners',
        self::ELECTRONIC_REPAIR_SHOPS                            => 'Electronic Repair Shops',
        self::VIDEO_GAME_ARCADES                                 => 'Video Game Arcades/Establishments',
        self::MEAT_SUPPLY_STORES                                 => 'Freezer, Locker Meat Provisioners',
        self::LEATHER_GOODS_AND_LUGGAGE                          => 'Leather Goods and Luggage Stores',
        self::CLEANING_AND_SANITATION_SERVICES                   => 'Specialty Cleaning, Polishing, and Sanitation Preparations',
        self::SNOWMOBILE_DEALERS                                 => 'Snowmobile Dealers',
        self::VIDEO_TAPE_PRODUCTION_AND_DISTRIBUTION             => 'Motion Pictures and Video Tape Production and Distribution',
        self::OSTEOPATHS                                         => 'Osteopaths',
        self::MEN_AND_BOYS_CLOTHING_STORES                       => 'Men’s and Boy’s Clothing and Furnishings Store',
        self::NURSING_CARE_FACILITIES                            => 'Nursing and Personal Care Facilities',
        self::DIRECT_MARKETING                                   => 'Direct Marketing Other Direct Marketers not elsewhere classified',
        self::AUTOMOBILE_ASSOCIATIONS_AND_CLUBS                  => 'Automobile Associations',
        self::VETERINARY_SERVICES                                => 'Veterinary Services',
        self::PAINT_SUPPLY_STORES                                => 'Varnishes, Paints, Supplies',
        self::AFFLIATED_AUTO_RENTAL                              => 'AFFILIATED AUTO RENTAL',
        self::ALIMONY_AND_CHILD_SUPPORT                          => 'COURT COST INCLUDING ALIMONY AND CHILD SUPPORT',
        self::AIRPORT_FLYING_FIELDS                              => 'AIRPORT FLYING FIELDS',
        self::TIRE_RETREADING_AND_REPAIR_SHOPS                   => 'Tire Retreading and Repair Shops',
        self::TELEVISION_CABLE_SERVICES                          => 'Cable and other Pay Television Services',
        self::RECREATIONAL_AND_SPORTING_CAMPS                    => 'Recreational or sport camp',
        self::AUTOMOTIVE_PARTS                                   => 'Automotive Parts, Accessories Stores',
        self::JEWELLERY_AND_WATCH_STORES                         => 'Gems, metals, watches, jewellery',
        self::AUTO_STORE_HOME_SUPPLY_STORES                      => 'Auto Store, Home Supply Stores',
        self::TENT_STORES                                        => 'Tent and Awning Shops',
        self::MEDICAL_EQUIPMENT_AND_SUPPLY_STORES                => 'Medical equipment supplies',
        self::AGRICULTURAL_COOPERATIVES                          => 'AGRICLUTRAL COPERATIVES',
        self::PETROLEUM_AND_PETROLEUM_PRODUCTS                   => 'Petroleum and Petroleum Products',
        self::DEPARTMENT_STORES                                  => 'Department Stores',
        self::SHOE_STORES_RETAIL                                 => 'Footwear',
        self::CARPENTRY_CONTRACTORS                              => 'Carpentry Contractors',
        self::MONEYSEND_FUNDING                                  => 'MoneySend Funding',
        self::WRECKING_AND_SALVAGING_SERVICES                    => 'Wrecking and Salvage Yards',
        self::AUTOMOBILE_TOWING_SERVICES                         => 'Towing Services',
        self::POLITICAL_ORGANIZATIONS                            => 'Political Organizations',
        self::AUTOMOTIVE_TIRE_STORES                             => 'Automotive Tire Stores',
        self::BARBER_AND_BEAUTY_SHOPS                            => 'Barber and Beauty Shops',
        self::SPORT_APPAREL_STORES                               => 'Sports Apparel, Riding Apparel Stores',
        self::VIDEO_TAPE_RENTAL_STORES                           => 'Video Tape Rental Stores',
        self::DRUG_STORES                                        => 'DRUGS, DRUG PROPRIETARIES',
        self::GOLF_COURSES                                       => 'Golf Courses, Public',
        self::MISCELLANEOUS_REPAIR_SHOPS                         => 'Miscellaneous Repair Shops and Related Services',
        self::MOTOR_HOMES_AND_PARTS                              => 'MOTOR HOME DEALERS',
        self::DEBT_MARRIAGE_PERSONAL_COUNSELING_SERVICE          => 'Debt, Marriage, Personal Counseling Service',
        self::CHEMICALS_AND_ALLIED_PRODUCTS                      => 'Chemicals and Allied Products',
        self::FIREPLACE_PARTS_AND_ACCESSORIES                    => 'FIREPLACE FIREPLACE SCREENS AND ACCESSORIES STORES',
        self::COMMERCIAL_EQUIPMENTS                              => 'COMMERCIAL EQUIPMENTS',
        self::AIR_CONDITIONING_AND_REFRIGERATION_REPAIR_SHOPS    => 'Air Conditioning and Refrigeration Repair Shops',
        self::FAMILY_CLOTHING_STORES                             => 'Family Clothing Stores',
        self::TAILORS                                            => 'Alterations, Mending, Seamstresses, Tailors',
        self::FABRIC_AND_SEWING_STORES                           => 'Fabric, Needlework, Piece Goods, and Sewing Stores',
        self::CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS    => 'Camper, Recreational and utility trailer dealers',
        self::TOURIST_ATTRACTIONS_AND_EXHIBITS                   => 'Tourist Attractions and Exhibits',
        self::RECORD_SHOPS                                       => 'Record Shops',
        self::HOME_SUPPLY_WAREHOUSE                              => 'Home Supply Warehouse',
        self::CLOCKS_AND_SILVERWARE_STORES                       => 'Clock, Jewelry, Watch, and Silverware Store',
        self::ART_SUPPLY_STORES                                  => 'Artist Supply Stores, Craft Shops',
        self::MASSAGE_PARLORS                                    => 'Massage Parlors',
        self::HORSE_OR_DOG_RACING                                => 'Government Licensed Horse/Dog Racing',
        self::CREDIT_REPORTING_AGENCIES                          => 'Consumer Credit Reporting Agencies',
        self::PAWN_SHOPS                                         => 'Pawn Shops',
        self::PARKING_LOTS_AND_GARAGES                           => 'Automobile Parking Lots and Garages',
        self::SCHOOL_SUPPLIES_AND_STATIONERY                     => 'Office, School Supply, and Stationery Stores',
        self::HEATING_AND_PLUMBING_CONTRACTORS                   => 'Air Conditioning, Heating, and Plumbing Contractors',
        self::AQUARIUMS_DOLPHINARIUMS_AND_SEAQUARIUMS            => 'Aquariums, Dolphinariums, and Seaquariums',
        self::ELECTRICAL_CONTRACTORS                             => 'ELECTRICAL CONTRACTORS',
        self::WIRE_TRANSFERS_AND_MONEY_ORDERS                    => 'WIRE TRANSFER MONEY ORDER',
        self::CARPET_AND_UPHOLSTERY_CLEANING_SERVICES            => 'Carpet and Upholstery Cleaning',
        self::OPTICIANS_OPTICAL_GOODS_AND_EYEGLASSE_STORES       => 'Opticians, Optical Goods, and Eyeglasses',
        self::WATCH_AND_JEWELLERY_REPAIR_STORES                  => 'Clock, Jewelry, and Watch Repair Shops',
        self::WHOLESALE_FOOTWEAR_STORES                          => 'Commercial Footwear',
        self::ANTIQUE_STORES                                     => 'Antique Reproduction Stores',
        self::ROOFING_AND_METAL_WORK_CONTRACTORS                 => 'Roofing and Siding, Sheet Metal Work Contractors',
        self::INTERNET_SERVICE_PROVIDERS                         => 'Computer Network/Information Services',
        self::PLUMBING_AND_HEATING_EQUIPMENT                     => 'Plumbing and Heating Equipment',
        self::VARIETY_STORES                                     => 'Variety Stores',
        self::LIQUOR_STORES                                      => 'Package Stores, Beer, Wine, Liquor',
        self::BOAT_DEALERS                                       => 'Boat Dealers',
        self::LAUNDRY_SERVICES                                   => 'Cleaning, Garment, and Laundry Services',
        self::RECREATIONAL_CAMPS                                 => 'Trailer Parks and Campgrounds',
        self::PODIATRISTS_AND_CHIROPODISTS                       => 'Podiatrists and Chiropodists',
        self::TAX_PREPARATION_SERVICES                           => 'Tax Preparation Service',
        self::COSMETIC_STORES                                    => 'Cosmetics',
        self::HOME_FURNISHING_STORES                             => 'Miscellaneous House Furnishing Specialty Shops',
        self::BRIDGE_AND_ROAD_TOLLS                              => 'BRIDGE &amp, ROAD FEES, TOLLS',
        self::TELECOMMUNICATION_EQUIPMENT_STORES                 => 'Telecommunication Equipment Including Telephone Sales',
        self::WOMEN_CLOTHING                                     => 'Womens Ready to Wear Stores',
        self::FLORISTS                                           => 'Florists',
        self::COMMERCIAL_PHOTOGRAPHY_AND_GRAPHIC_DESIGN_SERVICES => 'Commercial Art, Graphics, Photography',
        self::BUILDING_MATRIAL_STORES                            => 'Building Materials, Lumber Stores',
        self::CANDY_NUT_CONFECTIONERY_SHOPS                      => 'Candy, Nut, Confectionery Stores',
        self::TIMESHARES                                         => 'Timeshares',
        self::MASONRY_CONTRACTORS                                => 'Insulation, Masonry, Plastering, Stonework, and Tile Setting Contractors',
        self::EXTERMINATING_AND_DISINFECTING_SERVICES            => 'Exterminating and Disinfecting Services',
        self::GLASS_AND_WALLPAPER_STORES                         => 'Glass, Paint, Wallpaper Stores',
        self::VIDEO_GAME_SUPPLY_STORES                           => 'Video Amusement Game Supplies',
        self::AMBULANCE_SERVICES                                 => 'Ambulance Services',
        self::FUNERAL_SERVICES_AND_CREMATORIES                   => 'Funeral Services and Crematories',
        self::BOWLING_ALLEYS                                     => 'Bowling Alleys',
        self::METAL_SERVICE_CENTRES                              => 'Metal Service Centers and Offices',
        self::COPYING_AND_BLUEPRINTING_SERVICES                  => 'Quick Copy, Reproduction, and Blueprinting Services',
        self::DRAPERY_AND_WINDOW_COVERINGS_STORES                => 'Drapery, Upholstery, and Window Coverings Stores',
        self::UNIFORMS_AND_COMMERCIAL_CLOTHING_STORES            => 'Men’s, Women’s, and Children’s Uniforms and Commercial Clothing',
        self::AUTOMOTIVE_PAINT_SHOPS                             => 'Automotive Paint Shops',
        self::DURABLE_GOODS_STORES                               => 'Durable Goods not elsewhere classified',
        self::FUR_SHOPS                                          => 'Furriers and Fur Shops',
        self::INDUSTRIAL_SUPPLIES                                => 'Industrial Supplies',
        self::MOTORCYCLE_SHOPS_AND_DEALERS                       => 'Motorcycle Shops and Dealers',
        self::CHILDREN_AND_INFANTS_WEAR_STORES                   => 'Children’s and Infants’ Wear Stores',
        self::CORRESPONDENCE_SCHOOLS                             => 'Schools, Correspondence',
        self::FREIGHT_TRANSPORT                                  => 'Railroads and Freight',
        self::FUEL_DISPENSERS                                    => 'Fuel Dispenser, Automated',
        self::TRUCK_AND_UTILITY_TRAILER_RENTALS                  => 'Truck and Utility Trailer Rentals',
        self::BILLIARD_AND_POOL_ESTABLISHMENTS                   => 'Billiard and Pool Establishments',
        self::LOTTERY                                            => 'Government Owned Lottery,Government Owned Lottery',
        self::WELDING_REPAIR                                     => 'WELDING REPAIR',
        self::COMPUTER_SOFTWARE_STORES                           => 'Computer Software Stores',
        self::AMUSEMENT_PARKS_AND_CIRCUSES                       => 'Amusement Parks, Carnivals, Circuses, Fortune Tellers',
        self::MOBILE_HOME_DEALERS                                => 'Mobile Home Dealers',
        self::WOMEN_ACCESSORY_STORES                             => 'Women Accessory and Specialty Stores',
        self::BOOKS_PERIODICALS_AND_NEWSPAPER                    => 'Books, Periodicals and Newspapers',
        self::FLOOR_COVERING_STORES                              => 'Floor Covering Stores',
        self::TAX_PAYMENTS                                       => 'Tax Payments',
        self::CRYSTAL_AND_GLASSWARE_STORES                       => 'Crystal and Glassware Stores',
        self::DENTISTS_AND_ORTHODONTISTS                         => 'Dentists, Orthodontists',
        self::HARDWARE_STORES                                    => 'Hardware Stores',
        self::HARDWARE_EQUIPMENT_AND_SUPPLY_STORES               => 'Hardware Equipement and Supplies',
        self::CONCRETE_WORK_CONTRACTORS                          => 'CONCRETE WORK CONTRACTORS',
        self::DISCOUNT_STORES                                    => 'Discount stores',
        self::OPHTHALMOLOGISTS                                   => 'Optometrists, Ophthalmologists',
        self::BOAT_RENTALS                                       => 'Boat Leases and Boat Rentals',
        self::PERSONAL_SHOPPERS_AND_SHOPPING_CLUBS               => 'Buying/Shopping Clubs, Services',
        self::COMPUTERS_PERIPHERAL_EQUIPMENT_SOFTWARE            => 'Computer equipment',
        self::DOOR_TO_DOOR_SALES                                 => 'DOOR-TO-DOOR SALES',
        self::AUTOMOBILE_AND_TRUCK_DEALERS                       => 'Automobile and Truck Dealers-Used Only-Sales',
        self::AUTOMOBILE_RENTALS                                 => 'Car rental',
        self::TRAVEL_RELATED_DIRECT_MARKETING                    => 'Direct Marketing-Travel-Related Arrangement Services',
        self::LOTTERY_AND_BETTING                                => 'Betting -including Lottery Tickets, Chips at Gaming Casinos, Off-Track Betting and Wagers at Race Tracks',
        self::DIGITAL_GOODS                                      => 'Digital Goods-Multi-Category',
        self::INTRA_GOVERNMENT_PURCHASES                         => 'Intra-Government Purchases -Government Only',
        self::COUNTRY_AND_ATHLETIC_CLUBS                         => 'Clubs-Country Clubs, Membership-Athletic, Recreation, Sports, Private Golf Courses',
        self::BANDS_ORCHESTRAS_AND_MISCELLANEOUS_ENTERTAINERS    => 'Bands, Orchestras, and Miscellaneous Entertainers-not elsewhere classified',
        self::FURNITURE_REPAIR_AND_REFINISHING                   => 'Furniture-Reupholstery and Repair, Refinishing',
        self::ORTHOPEDIC_GOODS_STORES                            => 'Orthopedic Goods-Artificial Limb Stores',
        self::DIRECT_MARKETING_AND_SUBSCRIPTION_MERCHANTS        => 'Direct Marketing-Continuity/Subscription Merchants',
        self::TYPEWRITER_STORES_SALES_SERVICE_AND_RENTALS        => 'Typewriter Stores-Sales, Service, and Rentals',
        self::DIRECT_MARKETING_INSURANCE_SERVICES                => 'Direct Marketing-Insurance Services',
        self::BUSINESS_SERVICES                                  => 'Business Services-not elsewhere classified',
        self::TICKET_AGENCIES                                    => 'Theatrical Producers-except Motion Pictures, Ticket Agencies',
        self::AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS                => 'Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers-not elsewhere classified',
        self::ANTIQUE_SHOPS_SALES_AND_REPAIRS                    => 'Antique Shops-Sales, Repairs, and Restoration Services',
        self::COURIER_SERVICES                                   => 'Courier Services-Air &amp, Ground, Freight Forwarders',
        self::BICYCLE_STORES                                     => 'Bicycle Shops-Sales and Service',
        self::INBOUND_TELEMARKETING_MERCHANTS                    => 'Direct Marketing-Inbound Telemarketing Merchants',
        self::HEARING_AIDS_STORES                                => 'Hearing Aids-Sales, Service, Supply Stores',
        self::RECREATION_SERVICES                                => 'Recreation Services-not elsewhere classified',
        self::MUSIC_STORES                                       => 'Music Stores-Musical Instruments, Pianos, Sheet Music',
        self::SWIMMING_POOLS                                     => 'Swimming Pools-Sales and Supplies',
        self::OUTBOUND_TELEMARKETING_MERCHANTS                   => 'Direct Marketing-Outbound Telemarketing Merchants',
        self::PUBLIC_WAREHOUSING                                 => 'Public Warehousing-Farm Products, Refrigerated Goods,',
        self::CLOTHING_RENTAL_STORES                             => 'Clothing Rental-Costumes, Uniforms, and Formal Wear',
        self::TRANSPORTATION                                     => 'Transportation—Suburban and Local Commuter Passenger, including Ferries',
        self::GOVERMENT_POSTAL_SERVICES                          => 'Postal Services -Government Only',
        self::HEALTH_PRACTITIONERS_MEDICAL_SERVICES              => 'Health practitioner or medical service',
        self::CONSTRUCTION_MATERIALS                             => 'Construction Materials-not elsewhere classified',
        self::ACCESSORY_AND_APPAREL_STORES                       => 'Clothing and accessories',
        self::TESTING_LABORATORIES                               => 'Testing Laboratories-Non medical',
        self::DOCTORS                                            => 'Doctors-not elsewhere classified',
        self::CONTRACTORS                                        => 'Contractors, Special Trade-not elsewhere classified',
        self::TRANSPORTATION_SERVICES                            => 'Transportation Services-not elsewhere classified',
        self::ATMS                                               => 'Financial Institutions-Automated Cash Disbursements',
        self::SECOND_HAND_STORES                                 => 'SECOND HAND STORES-USED MERCHANDISE STORES',
        self::ELECTRIC_RAZOR_STORES                              => 'Electric Razor Stores-Sales and Service',
        self::FUEL_DEALERS                                       => 'Fuel Dealers-Coal, Fuel Oil, Liquefied Petroleum, Wood',
        self::SERVICE_STATIONS                                   => 'Service Stations with or without Ancillary Services',
        self::FURNITURE_AND_HOME_FURNISHING_STORE                => 'Home furnishing or furniture',
        self::PHOTOGRAPHIC_STUDIO                                => 'Photography or videography',
        self::DATA_PROCESSING                                    => 'Data processing',
        self::PROFESSIONAL_SERVICES                              => 'Professional services',
        self::ASSOCIATIONS_AND_MEMBERSHIP                        => 'Membership association',
        self::COMPUTER_PROGRAMMING_DATA_PROCESSING               => 'Programming',
        self::UTILITIES_ELECTRIC_GAS_OIL_WATER                   => 'Utilities–Electric, Gas, Water, Oil',
    ];

    /**
     * This function checks if the given subcategory is valid
     *
     * @param string $subcategory
     *
     * @return boolean true/false
     */
    public static function isValidSubcategory(string $subcategory) : bool
    {
        // return false if subcategory is `descriptions`
        if (strtolower($subcategory) === 'descriptions')
        {
            return false;
        }

        $key = __CLASS__ . '::' . strtoupper($subcategory);

        return ((defined($key) === true) and (constant($key) === $subcategory));
    }
}
