import {
  SearchableEntitiesType,
  entityAttributesTypes,
  defaultEntityParamTypes,
  statusKeywordsStoreType,
} from 'merchant/components/HeaderNav/UniversalSearch/typings';
import { PRODUCTS_DATA } from 'merchant/components/SidebarV2/utils/Products';

const {
  transactions,
  settlements,
  payment_links,
  payment_pages,
  payment_button,
  route,
  subscriptions,
  qr_codes,
  smart_collect,
  customers,
  offers,
} = PRODUCTS_DATA;

export const searchableEntities: SearchableEntitiesType = {
  Payments: {
    id: 'Payments',
    route: '/payments',
    icon: transactions.icon,
    attributes: {
      PaymentId: 'id',
      OrderId: 'order_id',
      Email: 'email',
      PhoneNumber: 'contact',
      PaymentStatus: 'status',
    },
  },
  Settlements: {
    id: 'Settlements',
    route: '/settlements',
    icon: settlements.icon,
    attributes: {
      SettlementId: 'id',
      SettlementStatus: 'status',
    },
  },
  Refunds: {
    id: 'Refunds',
    route: '/refunds',
    icon: transactions.icon,
    attributes: {
      RefundId: 'id',
      PaymentId: 'payment_id',
      RefundStatus: 'public_status',
    },
  },
  Orders: {
    id: 'Orders',
    route: '/orders',
    icon: transactions.icon,
    attributes: {
      OrderId: 'id',
      OrderStatus: 'status',
    },
  },
  Disputes: {
    id: 'Disputes',
    route: '/disputes',
    icon: transactions.icon,
    attributes: {
      DisputeId: 'id',
      PaymentId: 'payment_id',
      DisputeType: 'phase',
      DisputeState: 'status',
    },
  },
  Invoices: {
    id: 'Invoices',
    route: '/invoices',
    icon: transactions.icon,
    attributes: {
      InvoiceId: 'id',
    },
  },
  PaymentLinks: {
    id: 'PaymentLinks',
    route: '/paymentlinks',
    icon: payment_links.icon,
    attributes: {
      PaymentLinkId: 'id',
      PaymentLinkUrl: 'short_url',
      PaymentLinkStatus: 'status',
      Email: 'customer_email',
      PhoneNumber: 'customer_contact',
      PaymentLinkBatchId: 'batch_id',
    },
  },
  PaymentPages: {
    id: 'PaymentPages',
    route: '/paymentpages',
    icon: payment_pages.icon,
    attributes: {
      PaymentPageUrl: 'short_url',
      PaymentPageStatus: 'status',
    },
  },
  PaymentButtons: {
    id: 'PaymentButtons',
    route: '/paymentbuttons',
    icon: payment_button.icon,
    attributes: {
      PaymentButtonStatus: 'status',
    },
  },
  Transfers: {
    id: 'Transfers',
    route: '/route/transfers',
    icon: route.icon,
    attributes: {
      TransferId: 'id',
      TransferStatus: 'status',
      TransferSettlementStatus: 'settlement_status',
    },
  },
  Reversals: {
    id: 'Reversals',
    route: '/route/reversals',
    icon: route.icon,
    attributes: {
      ReversalId: 'id',
      TransferId: 'transfer_id',
    },
  },
  Accounts: {
    id: 'Accounts',
    route: '/route/accounts',
    icon: route.icon,
    attributes: {
      AccountId: 'id',
      Email: 'email',
    },
  },
  Subscriptions: {
    id: 'Subscriptions',
    route: '/subscriptions',
    icon: subscriptions.icon,
    attributes: {
      SubscriptionId: 'id',
      PlanId: 'plan_id',
      CustomerId: 'customer_id',
    },
  },
  Plans: {
    id: 'Plans',
    route: '/plans',
    icon: subscriptions.icon,
    attributes: {
      PlanId: 'id',
    },
  },
  QRcode: {
    id: 'QRcode',
    route: '/qr_codes',
    icon: qr_codes.icon,
    attributes: {
      QRCodeId: 'id',
      QRCodeStatus: 'status',
    },
  },
  SmartCollect: {
    id: 'SmartCollect',
    route: '/smartcollect/virtualaccounts',
    icon: smart_collect.icon,
    attributes: {
      CustomerIdentifierId: 'id',
      Email: 'email',
      PhoneNumber: 'contact',
    },
  },
  Customer: {
    id: 'Customer',
    route: '/customers',
    icon: customers.icon,
    attributes: {
      CustomerId: 'id',
      Email: 'email',
      PhoneNumber: 'contact',
    },
  },
  Offers: {
    id: 'Offers',
    route: '/offers',
    icon: offers.icon,
    attributes: {
      OfferId: 'id',
    },
  },
};

export const entityAttributes: entityAttributesTypes = {
  PaymentId: {
    attributeId: 'PaymentId',
    attributeType: 'entity_id',
    matchWith: /^pay_[a-zA-Z0-9]{0,14}/,
    entities: ['Payments', 'Refunds', 'Disputes'],
  },
  OrderId: {
    attributeId: 'OrderId',
    attributeType: 'entity_id',
    matchWith: /^order_[a-zA-Z0-9]{0,14}/,
    entities: ['Payments', 'Orders'],
  },
  SettlementId: {
    attributeId: 'SettlementId',
    attributeType: 'entity_id',
    matchWith: /^setl_[a-zA-Z0-9]{0,14}/,
    entities: ['Settlements'],
  },
  RefundId: {
    attributeId: 'RefundId',
    attributeType: 'entity_id',
    matchWith: /^rfnd_[a-zA-Z0-9]{0,14}/,
    entities: ['Refunds'],
  },
  DisputeId: {
    attributeId: 'DisputeId',
    attributeType: 'entity_id',
    matchWith: /^disp_[a-zA-Z0-9]{0,14}/,
    entities: ['Disputes'],
  },
  InvoiceId: {
    attributeId: 'InvoiceId',
    attributeType: 'entity_id',
    matchWith: /^inv_[a-zA-Z0-9]{0,14}/,
    entities: ['Invoices'],
  },
  PaymentLinkId: {
    attributeId: 'PaymentLinkId',
    attributeType: 'entity_id',
    matchWith: /^plink_[a-zA-Z0-9]{0,14}/,
    entities: ['PaymentLinks'],
  },
  PaymentLinkUrl: {
    attributeId: 'PaymentLinkUrl',
    attributeType: 'entity_url',
    matchWith: /^https:\/\/rzp\.io\/i\/[a-zA-Z0-9]+$/,
    entities: ['PaymentLinks'],
  },
  PaymentLinkBatchId: {
    attributeId: 'PaymentLinkBatchId',
    attributeType: 'entity_secondary_id',
    matchWith: /^batch_[a-zA-Z0-9]{14}$/,
    entities: ['PaymentLinks'],
  },
  SubscriptionId: {
    attributeId: 'SubscriptionId',
    attributeType: 'entity_id',
    matchWith: /^sub_[a-zA-Z0-9]{14}$/,
    entities: ['Subscriptions'],
  },
  PlanId: {
    attributeId: 'PlanId',
    attributeType: 'entity_id',
    matchWith: /^plan_[a-zA-Z0-9]{14}$/,
    entities: ['Subscriptions', 'Plans'],
  },
  CustomerId: {
    attributeId: 'CustomerId',
    attributeType: 'entity_id',
    matchWith: /^cust_[a-zA-Z0-9]{14}$/,
    entities: ['Subscriptions', 'Customer'],
  },
  OfferId: {
    attributeId: 'OfferId',
    attributeType: 'entity_id',
    matchWith: /^offer_[a-zA-Z0-9]{14}$/,
    entities: ['Offers'],
  },
  PaymentPageUrl: {
    attributeId: 'PaymentPageUrl',
    attributeType: 'entity_url',
    matchWith: /^https:\/\/rzp\.io\/i\/[a-zA-Z0-9]+$/,
    entities: ['PaymentPages'],
  },
  Email: {
    attributeId: 'Email',
    attributeType: 'entity_email',
    matchWith: /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$/,
    entities: ['Payments', 'PaymentLinks', 'Accounts', 'SmartCollect', 'Customer', 'QRcode'],
  },
  PhoneNumber: {
    attributeId: 'PhoneNumber',
    attributeType: 'entity_contact_number',
    matchWith: /^(?:\+91|0)?[6-9]\d{9}$/,
    entities: ['Payments', 'PaymentLinks', 'SmartCollect', 'Customer', 'QRcode'],
  },
  TransferId: {
    attributeId: 'TransferId',
    attributeType: 'entity_id',
    matchWith: /^trf_[a-zA-Z0-9]{0,14}/,
    entities: ['Transfers', 'Reversals'],
  },
  ReversalId: {
    attributeId: 'ReversalId',
    attributeType: 'entity_id',
    matchWith: /^rvrsl_[a-zA-Z0-9]{0,14}/,
    entities: ['Reversals'],
  },
  AccountId: {
    attributeId: 'AccountId',
    attributeType: 'entity_id',
    matchWith: /^acc_[a-zA-Z0-9]{0,14}/,
    entities: ['Accounts'],
  },
  QRCodeId: {
    attributeId: 'QRCodeId',
    attributeType: 'entity_id',
    matchWith: /^qr_[a-zA-Z0-9]{0,14}/,
    entities: ['QRcode'],
  },
  CustomerIdentifierId: {
    attributeId: 'CustomerIdentifierId',
    attributeType: 'entity_id',
    matchWith: /^va_[a-zA-Z0-9]{0,14}/,
    entities: ['SmartCollect', 'QRcode'],
  },
  TransferStatus: {
    attributeId: 'TransferStatus',
    attributeType: 'entity_state',
    matchWith: ['created', 'pending', 'processed', 'failed', 'reversed', 'partially_reversed'],
    entities: ['Transfers'],
  },
  TransferSettlementStatus: {
    attributeId: 'TransferSettlementStatus',
    attributeType: 'entity_state',
    matchWith: ['pending', 'on hold', 'hold', 'settled'],
    entities: ['Transfers'],
  },
  PaymentStatus: {
    attributeId: 'PaymentStatus',
    attributeType: 'entity_state',
    matchWith: ['captured', 'authorized', 'failed', 'refunded', 'authorised'],
    entities: ['Payments'],
  },
  SettlementStatus: {
    attributeId: 'SettlementStatus',
    attributeType: 'entity_state',
    matchWith: ['created', 'processed', 'failed', 'initiated'],
    entities: ['Settlements'],
  },
  RefundStatus: {
    attributeId: 'RefundStatus',
    attributeType: 'entity_state',
    matchWith: ['processed', 'processing', 'paid'],
    entities: ['Refunds'],
  },
  OrderStatus: {
    attributeId: 'OrderStatus',
    attributeType: 'entity_state',
    matchWith: ['created', 'attempted', 'paid'],
    entities: ['Orders'],
  },
  DisputeType: {
    attributeId: 'DisputeType',
    attributeType: 'entity_state',
    matchWith: [
      'retrieval',
      'chargeback',
      'pre_arbitration',
      'pre arbitration',
      'arbitration',
      'fraud',
    ],
    entities: ['Disputes'],
  },
  DisputeState: {
    attributeId: 'DisputeState',
    attributeType: 'entity_state',
    matchWith: ['open', 'under_review', 'lost', 'won', 'closed', 'review', 'under review'],
    entities: ['Disputes'],
  },
  PaymentLinkStatus: {
    attributeId: 'PaymentLinkStatus',
    attributeType: 'entity_state',
    matchWith: ['created', 'partially_paid', 'partially', 'paid', 'cancelled', 'expired'],
    entities: ['PaymentLinks'],
  },
  PaymentPageStatus: {
    attributeId: 'PaymentPageStatus',
    attributeType: 'entity_state',
    matchWith: ['active', 'inactive', 'in active'],
    entities: ['PaymentPages'],
  },
  PaymentButtonStatus: {
    attributeId: 'PaymentButtonStatus',
    attributeType: 'entity_state',
    matchWith: ['active', 'inactive', 'in active'],
    entities: ['PaymentButtons'],
  },
  QRCodeStatus: {
    attributeId: 'QRCodeStatus',
    attributeType: 'entity_state',
    matchWith: ['active', 'closed'],
    entities: ['QRcode'],
  },
};

export const defaultQueryParamsPerEntity: defaultEntityParamTypes = {
  Payments: 'q',
  Settlements: 'utr',
  Invoices: 'q',
  Orders: 'q',
  PaymentButtons: 'title',
  PaymentLinks: 'q',
  Refunds: 'q',
  PaymentPages: 'title',
  Disputes: 'q',
  Transfers: 'q',
  Reversals: 'q',
  Accounts: 'q',
  Subscriptions: 'q',
  Plans: 'q',
  QRcode: 'q',
  SmartCollect: 'q',
  Customer: 'q',
  Offers: 'q',
};

export const statusKeywordsStore: statusKeywordsStoreType = {
  Payments: {
    captured: 'captured',
    failed: 'failed',
    refunded: 'refunded',
    authorised: 'authorized',
    authorized: 'authorized',
  },
  Settlements: {
    created: 'created',
    processed: 'processed',
    failed: 'failed',
    initiated: 'initiated',
  },
  Refunds: {
    processed: 'processed',
    processing: 'processing',
    paid: 'paid',
  },
  Orders: {
    created: 'created',
    attempted: 'attempted',
    paid: 'paid',
  },
  Disputes: {
    retrieval: 'retrieval',
    chargeback: 'chargeback',
    arbitration: 'arbitration',
    'pre arbitration': 'pre_arbitration',
    fraud: 'fraud',
    open: 'open',
    lost: 'lost',
    won: 'won',
    closed: 'closed',
    'under review': 'under_review',
    review: 'under_review',
  },
  PaymentLinks: {
    created: 'created',
    paid: 'paid',
    cancelled: 'cancelled',
    expired: 'expired',
    'partially paid': 'partially_paid',
  },
  PaymentPages: {
    active: 'active',
    inactive: 'inactive',
    'in active': 'inactive',
  },
  PaymentButtons: {
    active: 'active',
    inactive: 'inactive',
    'in active': 'inactive',
  },
  Transfers: {
    created: 'created',
    pending: 'pending',
    failed: 'failed',
    processed: 'processed',
    reversed: 'reversed',
    'partially reversed': 'partially_reversed',
    settled: 'settled',
    hold: 'on_hold',
    'on hold': 'on_hold',
  },
  QRcode: {
    active: 'active',
    closed: 'closed',
  },
};
