name: Smart Linter Action

inputs:
  dangerjs_args:
    required: true
  github_access_token:
    required: true

outputs:
  hardcoding_found:
    description: "Whether an error was found"
    value: ${{ steps.output_values.outputs.hardcoding_found }}
  i18n_errors_metrics:
    description: "i18n linter metrics"
    value: ${{ steps.output_values.outputs.i18n_errors_metrics }}

runs:
  using: composite
  steps:
    - name: Use Node v18.12.1
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1

    - name: Filter I18n Errors
      run: ./scripts/linter/filter-errors.sh
      shell: bash

    - name: Check ESLint Report for i18n Errors
      id: linter-check
      run: ./scripts/linter/check-errors.sh
      shell: bash

    - name: Calculate i18n Linter Metrics
      id: linter-metrics
      run: ./scripts/linter/error-metrics.sh
      shell: bash

    - name: Run DangerJS for I18n Linter
      id: i18n_linter_dangerjs
      uses: danger/danger-js@11.3.0
      with:
        args: "--id i18n_linter_dangerjs --dangerfile dangerfile-i18nlinter.js ${{ inputs.dangerjs_args }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github_access_token }}
        DANGER_DISABLE_TRANSPILATION: true

    - name: Set outputs
      id: output_values
      run: |
        echo "hardcoding_found=${{ steps.linter-check.outputs.hardcoding_found }}" >> $GITHUB_OUTPUT
        echo "i18n_errors_metrics=${{ steps.linter-metrics.outputs.i18n_errors_metrics }}" >> $GITHUB_OUTPUT
      shell: bash
