<?php

use RZP\Reconciliator\Base;

class PaymentReconciliate extends Base\PaymentReconciliate
{
    protected function getPaymentId(array $row)
    {
        return parent::getPaymentId($row); // TODO: Change the autogenerated stub
    }

    protected function getReferenceNumber($row)
    {
        return parent::getReferenceNumber($row); // TODO: Change the autogenerated stub
    }

    protected function getGatewayPaymentDate($row)
    {
        return parent::getGatewayPaymentDate($row); // TODO: Change the autogenerated stub
    }

    protected function getCustomerDetails($row)
    {
        return parent::getCustomerDetails($row); // TODO: Change the autogenerated stub
    }

    protected function getAuthCode($row)
    {
        return parent::getAuthCode($row); // TODO: Change the autogenerated stub
    }

    protected function getArn($row)
    {
        return parent::getArn($row); // TODO: Change the autogenerated stub
    }


}