<?php

$responseContent = [
    'AED' => [
        'code'           => '784',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'د.إ',
        'name'           => 'Emirati Dirham',
    ],
    'ALL' => [
        'code'           => '008',
        'min_value'      => 221,
        'min_auth_value' => 221,
        'denomination'   => 100,
        'symbol'         => 'Lek',
        'name'           => 'Albanian Lek',
    ],
    'AMD' => [
        'code'           => '051',
        'min_value'      => 975,
        'min_auth_value' => 975,
        'denomination'   => 100,
        'symbol'         => '֏',
        'name'           => 'Armenian Dram',
    ],
    'ARS' => [
        'code'           => '032',
        'min_value'      => 80,
        'min_auth_value' => 80,
        'denomination'   => 100,
        'symbol'         => 'ARS',
        'name'           => 'Argentine Peso',
    ],
    'AUD' => [
        'code'           => '036',
        'min_value'      => 50,
        'min_auth_value' => 50,
        'denomination'   => 100,
        'symbol'         => 'A$',
        'name'           => 'Australian Dollar',
    ],
    'AWG' => [
        'code'           => '533',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'Afl.',
        'name'           => 'Aruban or Dutch Guilder',
    ],
    'BBD' => [
        'code'           => '052',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => '$',
        'name'           => 'Barbadian or Bajan Dollar',
    ],
    'BDT' => [
        'code'           => '050',
        'min_value'      => 168,
        'min_auth_value' => 168,
        'denomination'   => 100,
        'symbol'         => '৳',
        'name'           => 'Bangladeshi Taka',
    ],
    'BMD' => [
        'code'           => '060',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => '$',
        'name'           => 'Bermudian Dollar',
    ],
    'BND' => [
        'code'           => '096',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'BND',
        'name'           => 'Bruneian Dollar',
    ],
    'BOB' => [
        'code'           => '068',
        'min_value'      => 14,
        'min_auth_value' => 14,
        'denomination'   => 100,
        'symbol'         => 'Bs',
        'name'           => 'Bolivian Bolíviano',
    ],
    'BSD' => [
        'code'           => '044',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'B$',
        'name'           => 'Bahamian Dollar',
    ],
    'BWP' => [
        'code'           => '072',
        'min_value'      => 22,
        'min_auth_value' => 22,
        'denomination'   => 100,
        'symbol'         => 'P',
        'name'           => 'Botswana Pula',
    ],
    'BZD' => [
        'code'           => '084',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'BZ$',
        'name'           => 'Belizean Dollar',
    ],
    'CAD' => [
        'code'           => '124',
        'min_value'      => 50,
        'min_auth_value' => 50,
        'denomination'   => 100,
        'symbol'         => 'C$',
        'name'           => 'Canadian Dollar',
    ],
    'CHF' => [
        'code'           => '756',
        'min_value'      => 50,
        'min_auth_value' => 50,
        'denomination'   => 100,
        'symbol'         => 'CHf',
        'name'           => 'Swiss Franc',
    ],
    'CNY' => [
        'code'           => '156',
        'min_value'      => 14,
        'min_auth_value' => 14,
        'denomination'   => 100,
        'symbol'         => '¥',
        'name'           => 'Chinese Yuan Renminbi',
    ],
    'COP' => [
        'code'           => '170',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => 'COL$',
        'name'           => 'Colombian Peso',
    ],
    'CRC' => [
        'code'           => '188',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => '₡',
        'name'           => 'Costa Rican Colon',
    ],
    'CUP' => [
        'code'           => '192',
        'min_value'      => 53,
        'min_auth_value' => 53,
        'denomination'   => 100,
        'symbol'         => '$MN',
        'name'           => 'Cuban Peso',
    ],
    'CZK' => [
        'code'           => '203',
        'min_value'      => 46,
        'min_auth_value' => 46,
        'denomination'   => 100,
        'symbol'         => 'Kč',
        'name'           => 'Czech Koruna',
    ],
    'DKK' => [
        'code'           => '208',
        'min_value'      => 250,
        'min_auth_value' => 250,
        'denomination'   => 100,
        'symbol'         => 'DKK',
        'name'           => 'Danish Krone',
    ],
    'DOP' => [
        'code'           => '214',
        'min_value'      => 102,
        'min_auth_value' => 102,
        'denomination'   => 100,
        'symbol'         => 'RD$',
        'name'           => 'Dominican Peso',
    ],
    'DZD' => [
        'code'           => '012',
        'min_value'      => 239,
        'min_auth_value' => 239,
        'denomination'   => 100,
        'symbol'         => 'د.ج',
        'name'           => 'Algerian Dinar',
    ],
    'EGP' => [
        'code'           => '818',
        'min_value'      => 35,
        'min_auth_value' => 35,
        'denomination'   => 100,
        'symbol'         => 'E£',
        'name'           => 'Egyptian Pound',
    ],
    'ETB' => [
        'code'           => '230',
        'min_value'      => 57,
        'min_auth_value' => 57,
        'denomination'   => 100,
        'symbol'         => 'ብር',
        'name'           => 'Ethiopian Birr',
    ],
    'EUR' => [
        'code'           => '978',
        'min_value'      => 50,
        'min_auth_value' => 50,
        'denomination'   => 100,
        'symbol'         => '€',
        'name'           => 'Euro',
    ],
    'FJD' => [
        'code'           => '242',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'FJ$',
        'name'           => 'Fijian Dollar',
    ],
    'GBP' => [
        'code'           => '826',
        'min_value'      => 30,
        'min_auth_value' => 30,
        'denomination'   => 100,
        'symbol'         => '£',
        'name'           => 'British Pound',
    ],
    'GIP' => [
        'code'           => '292',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'GIP',
        'name'           => 'Gibraltar Pound',
    ],
    'GMD' => [
        'code'           => '270',
        'min_value'      => 100,
        'min_auth_value' => 100,
        'denomination'   => 100,
        'symbol'         => 'D',
        'name'           => 'Gambian Dalasi',
    ],
    'GTQ' => [
        'code'           => '320',
        'min_value'      => 16,
        'min_auth_value' => 16,
        'denomination'   => 100,
        'symbol'         => 'Q',
        'name'           => 'Guatemalan Quetzal',
    ],
    'GYD' => [
        'code'           => '328',
        'min_value'      => 418,
        'min_auth_value' => 418,
        'denomination'   => 100,
        'symbol'         => 'G$',
        'name'           => 'Guyanese Dollar',
    ],
    'HKD' => [
        'code'           => '344',
        'min_value'      => 400,
        'min_auth_value' => 400,
        'denomination'   => 100,
        'symbol'         => 'HK$',
        'name'           => 'Hong Kong Dollar',
    ],
    'HNL' => [
        'code'           => '340',
        'min_value'      => 49,
        'min_auth_value' => 49,
        'denomination'   => 100,
        'symbol'         => 'HNL',
        'name'           => 'Honduran Lempira',
    ],
    'HRK' => [
        'code'           => '191',
        'min_value'      => 14,
        'min_auth_value' => 14,
        'denomination'   => 100,
        'symbol'         => 'kn',
        'name'           => 'Croatian Kuna',
    ],
    'HTG' => [
        'code'           => '332',
        'min_value'      => 167,
        'min_auth_value' => 167,
        'denomination'   => 100,
        'symbol'         => 'G',
        'name'           => 'Haitian Gourde',
    ],
    'HUF' => [
        'code'           => '348',
        'min_value'      => 555,
        'min_auth_value' => 555,
        'denomination'   => 100,
        'symbol'         => 'Ft',
        'name'           => 'Hungarian Forint',
    ],
    'IDR' => [
        'code'           => '360',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => 'Rp',
        'name'           => 'Indonesian Rupiah',
    ],
    'ILS' => [
        'code'           => '376',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => '₪',
        'name'           => 'Israeli Shekel',
    ],
    'INR' => [
        'code'           => '356',
        'min_value'      => 100,
        'min_auth_value' => 100,
        'denomination'   => 100,
        'symbol'         => '₹',
        'name'           => 'Indian Rupee',
    ],
    'JMD' => [
        'code'           => '388',
        'min_value'      => 250,
        'min_auth_value' => 250,
        'denomination'   => 100,
        'symbol'         => 'J$',
        'name'           => 'Jamaican Dollar',
    ],
    'KES' => [
        'code'           => '404',
        'min_value'      => 201,
        'min_auth_value' => 201,
        'denomination'   => 100,
        'symbol'         => 'Ksh',
        'name'           => 'Kenyan Shilling',
    ],
    'KGS' => [
        'code'           => '417',
        'min_value'      => 140,
        'min_auth_value' => 140,
        'denomination'   => 100,
        'symbol'         => 'Лв',
        'name'           => 'Kyrgyzstani Som',
    ],
    'KHR' => [
        'code'           => '116',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => '៛',
        'name'           => 'Cambodian Riel',
    ],
    'KYD' => [
        'code'           => '136',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'CI$',
        'name'           => 'Caymanian Dollar',
    ],
    'KZT' => [
        'code'           => '398',
        'min_value'      => 759,
        'min_auth_value' => 759,
        'denomination'   => 100,
        'symbol'         => '₸',
        'name'           => 'Kazakhstani Tenge',
    ],
    'LAK' => [
        'code'           => '418',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => '₭',
        'name'           => 'Lao Kip',
    ],
    'LKR' => [
        'code'           => '144',
        'min_value'      => 358,
        'min_auth_value' => 358,
        'denomination'   => 100,
        'symbol'         => 'රු',
        'name'           => 'Sri Lankan Rupee',
    ],
    'LRD' => [
        'code'           => '430',
        'min_value'      => 325,
        'min_auth_value' => 325,
        'denomination'   => 100,
        'symbol'         => 'L$',
        'name'           => 'Liberian Dollar',
    ],
    'LSL' => [
        'code'           => '426',
        'min_value'      => 29,
        'min_auth_value' => 29,
        'denomination'   => 100,
        'symbol'         => 'LSL',
        'name'           => 'Basotho Loti',
    ],
    'MAD' => [
        'code'           => '504',
        'min_value'      => 20,
        'min_auth_value' => 20,
        'denomination'   => 100,
        'symbol'         => 'د.م.',
        'name'           => 'Moroccan Dirham',
    ],
    'MDL' => [
        'code'           => '498',
        'min_value'      => 35,
        'min_auth_value' => 35,
        'denomination'   => 100,
        'symbol'         => 'MDL',
        'name'           => 'Moldovan Leu',
    ],
    'MKD' => [
        'code'           => '807',
        'min_value'      => 109,
        'min_auth_value' => 109,
        'denomination'   => 100,
        'symbol'         => 'ден',
        'name'           => 'Macedonian Denar',
    ],
    'MMK' => [
        'code'           => '104',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => 'MMK',
        'name'           => 'Burmese Kyat',
    ],
    'MNT' => [
        'code'           => '496',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => '₮',
        'name'           => 'Mongolian Tughrik',
    ],
    'MOP' => [
        'code'           => '446',
        'min_value'      => 17,
        'min_auth_value' => 17,
        'denomination'   => 100,
        'symbol'         => 'MOP$',
        'name'           => 'Macau Pataca',
    ],
    'MUR' => [
        'code'           => '480',
        'min_value'      => 70,
        'min_auth_value' => 70,
        'denomination'   => 100,
        'symbol'         => '₨',
        'name'           => 'Mauritian Rupee',
    ],
    'MVR' => [
        'code'           => '462',
        'min_value'      => 31,
        'min_auth_value' => 31,
        'denomination'   => 100,
        'symbol'         => 'Rf',
        'name'           => 'Maldivian Rufiyaa',
    ],
    'MWK' => [
        'code'           => '454',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => 'MK',
        'name'           => 'Malawian Kwacha',
    ],
    'MXN' => [
        'code'           => '484',
        'min_value'      => 39,
        'min_auth_value' => 39,
        'denomination'   => 100,
        'symbol'         => 'Mex$',
        'name'           => 'Mexican Peso',
    ],
    'MYR' => [
        'code'           => '458',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'RM',
        'name'           => 'Malaysian Ringgit',
    ],
    'NAD' => [
        'code'           => '516',
        'min_value'      => 29,
        'min_auth_value' => 29,
        'denomination'   => 100,
        'symbol'         => 'N$',
        'name'           => 'Namibian Dollar',
    ],
    'NGN' => [
        'code'           => '566',
        'min_value'      => 723,
        'min_auth_value' => 723,
        'denomination'   => 100,
        'symbol'         => '₦',
        'name'           => 'Nigerian Naira',
    ],
    'NIO' => [
        'code'           => '558',
        'min_value'      => 66,
        'min_auth_value' => 66,
        'denomination'   => 100,
        'symbol'         => 'NIO',
        'name'           => 'Nicaraguan Cordoba',
    ],
    'NOK' => [
        'code'           => '578',
        'min_value'      => 300,
        'min_auth_value' => 300,
        'denomination'   => 100,
        'symbol'         => 'NOK',
        'name'           => 'Norwegian Krone',
    ],
    'NPR' => [
        'code'           => '524',
        'min_value'      => 221,
        'min_auth_value' => 221,
        'denomination'   => 100,
        'symbol'         => 'रू',
        'name'           => 'Nepalese Rupee',
    ],
    'NZD' => [
        'code'           => '554',
        'min_value'      => 50,
        'min_auth_value' => 50,
        'denomination'   => 100,
        'symbol'         => 'NZ$',
        'name'           => 'New Zealand Dollar',
    ],
    'PEN' => [
        'code'           => '604',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'S/',
        'name'           => 'Peruvian Sol',
    ],
    'PGK' => [
        'code'           => '598',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'PGK',
        'name'           => 'Papua New Guinean Kina',
    ],
    'PHP' => [
        'code'           => '608',
        'min_value'      => 106,
        'min_auth_value' => 106,
        'denomination'   => 100,
        'symbol'         => '₱',
        'name'           => 'Philippine Peso',
    ],
    'PKR' => [
        'code'           => '586',
        'min_value'      => 227,
        'min_auth_value' => 227,
        'denomination'   => 100,
        'symbol'         => '₨',
        'name'           => 'Pakistani Rupee',
    ],
    'QAR' => [
        'code'           => '634',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'QR',
        'name'           => 'Qatari Riyal',
    ],
    'RUB' => [
        'code'           => '643',
        'min_value'      => 130,
        'min_auth_value' => 130,
        'denomination'   => 100,
        'symbol'         => '₽',
        'name'           => 'Russian Ruble',
    ],
    'SAR' => [
        'code'           => '682',
        'min_value'      => 10,
        'min_auth_value' => 10,
        'denomination'   => 100,
        'symbol'         => 'SR',
        'name'           => 'Saudi Arabian Riyal',
    ],
    'SCR' => [
        'code'           => '690',
        'min_value'      => 28,
        'min_auth_value' => 28,
        'denomination'   => 100,
        'symbol'         => 'SRe',
        'name'           => 'Seychellois Rupee',
    ],
    'SEK' => [
        'code'           => '752',
        'min_value'      => 300,
        'min_auth_value' => 300,
        'denomination'   => 100,
        'symbol'         => 'SEK',
        'name'           => 'Swedish Krona',
    ],
    'SGD' => [
        'code'           => '702',
        'min_value'      => 50,
        'min_auth_value' => 50,
        'denomination'   => 100,
        'symbol'         => 'S$',
        'name'           => 'Singapore Dollar',
    ],
    'SLL' => [
        'code'           => '694',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => 'Le',
        'name'           => 'Sierra Leonean Leone',
    ],
    'SOS' => [
        'code'           => '706',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => 'Sh.so.',
        'name'           => 'Somali Shilling',
    ],
    'SSP' => [
        'code'           => '728',
        'min_value'      => 100,
        'min_auth_value' => 100,
        'denomination'   => 100,
        'symbol'         => 'SS£',
        'name'           => 'South Sudanese Pound',
    ],
    'SVC' => [
        'code'           => '222',
        'min_value'      => 18,
        'min_auth_value' => 18,
        'denomination'   => 100,
        'symbol'         => '₡',
        'name'           => 'Salvadoran Colon',
    ],
    'SZL' => [
        'code'           => '748',
        'min_value'      => 29,
        'min_auth_value' => 29,
        'denomination'   => 100,
        'symbol'         => 'E',
        'name'           => 'Swazi Lilangeni',
    ],
    'THB' => [
        'code'           => '764',
        'min_value'      => 64,
        'min_auth_value' => 64,
        'denomination'   => 100,
        'symbol'         => '฿',
        'name'           => 'Thai Baht',
    ],
    'TRY' => [
        'code'           => '949',
        'min_value'      => 100,
        'min_auth_value' => 100,
        'denomination'   => 100,
        'symbol'         => '₺',
        'name'           => 'Turkish Lira',
    ],
    'TTD' => [
        'code'           => '780',
        'min_value'      => 14,
        'min_auth_value' => 14,
        'denomination'   => 100,
        'symbol'         => 'TT$',
        'name'           => 'Trinidadian Dollar',
    ],
    'TZS' => [
        'code'           => '834',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => 'Sh',
        'name'           => 'Tanzanian Shilling',
    ],
    'USD' => [
        'code'           => '840',
        'min_value'      => 10,
        'min_auth_value' => 50,
        'denomination'   => 100,
        'symbol'         => '$',
        'name'           => 'US Dollar',
    ],
    'UYU' => [
        'code'           => '858',
        'min_value'      => 67,
        'min_auth_value' => 67,
        'denomination'   => 100,
        'symbol'         => '$U',
        'name'           => 'Uruguayan Peso',
    ],
    'UZS' => [
        'code'           => '860',
        'min_value'      => 1000,
        'min_auth_value' => 1000,
        'denomination'   => 100,
        'symbol'         => 'so\'m',
        'name'           => 'Uzbekistani Som',
    ],
    'YER' => [
        'code'           => '886',
        'min_value'      => 501,
        'min_auth_value' => 501,
        'denomination'   => 100,
        'symbol'         => '﷼',
        'name'           => 'Yemeni Rial',
    ],
    'ZAR' => [
        'code'           => '710',
        'min_value'      => 29,
        'min_auth_value' => 29,
        'denomination'   => 100,
        'symbol'         => 'R',
        'name'           => 'South African Rand',
    ],
];

return $responseContent;
