<?php

namespace Gateway\Billdesk;

use Models\Bank\IFSC;

class BankCodes
{
    public static $bankCodeMap = array(
        IFSC::ALLA => 'ALB',
        IFSC::BKID => 'BOI',
        IFSC::CIUB => 'CUB',
        IFSC::UTIB => 'UTI',
        IFSC::ICIC => 'ICI',
        IFSC::ANDB => 'ADB',
        IFSC::BBKM => 'BBK',
        IFSC::MAHB => 'BOM',
        IFSC::CBIN => 'CBI',
        IFSC::CNRB => 'CNB',
        IFSC::COSB => 'COB',
        IFSC::CSBK => 'CSB',
        IFSC::DEUT => 'DBK',
        IFSC::DCBL => 'DCB',
        IFSC::BKDN => 'DEN',
        IFSC::DLXB => 'DLB',
        IFSC::FDRL => 'FBK',
        IFSC::IBKL => 'IDB',
        IFSC::INDB => 'IDS',
        IFSC::IDIB => 'INB',
        IFSC::VYSA => 'ING',
        IFSC::IOBA => 'IOB',
        IFSC::JAKA => 'JKB',
        IFSC::KARB => 'KBL',
        IFSC::KVBL => 'KVB',
        IFSC::ORBC => 'OBC',
        IFSC::PMCB => 'PMC',
        IFSC::PSIB => 'PSB',
        IFSC::ABNA => 'RBS',
        IFSC::RATN => 'RTN',
        IFSC::SIBL => 'SIB',
        IFSC::SVCB => 'SVC',
        IFSC::SRCB => 'SWB',
        IFSC::SYNB => 'SYD',
        IFSC::TMBL => 'TMB',
        IFSC::TNSC => 'TNC',
        IFSC::UBIN => 'UBI',
        IFSC::UCBA => 'UCO',
        IFSC::UTBI => 'UNI',
        IFSC::VIJB => 'VJB',
        IFSC::YESB => 'YBK',
        IFSC::DCBL => 'DC2',
        IFSC::JSBP => 'JSB',
        IFSC::NKGS => 'NKB',
     // IFSC::BARB => 'BBC',
     // IFSC::BARB => 'BBR',
     // IFSC::PUNB => 'CPN',
     // IFSC::PUNB => 'PNB',
     // IFSC::LAVB => 'LVC',
     // IFSC::LAVB => 'LVR',
    );
}