# name: Sonar Code Coverage PR Analysis for POS app

# on:
#   pull_request:
#     branches:
#       - master
#     paths:
#       - apps/pos/**

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# env:
#   GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
#   APP_NAME: dashboard
#   HOME: /actions-runner/_work

# jobs:
#   coverage:
#     name: Sonar analysis on coverage - POS app
#     runs-on: self-hosted
#     if: "!contains(github.event.head_commit.message, '[skip ci]')"
#     steps:
#       - name: Checkout Codebase
#         uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.CI_BOT_TOKEN }}

#       - name: Install dependencies with caching
#         uses: ./.github/actions/package-installer
#         with:
#           github_access_token: ${{ secrets.CI_BOT_TOKEN }}

#       - name: Test POS micro app
#         working-directory: ./apps/pos
#         run: |
#           pnpm test:jest
#         env:
#           GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
#           DISABLE_REPORT_PORTAL_INTEGRATION: true

# - name: Run SonarQube PR analysis on Dev Project
#   id: pr_sonarqube_analysis
#   uses: sonarsource/sonarcloud-github-action@v4.0.0
#   env:
#     SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
#     SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
#   with:
#     projectBaseDir: ./apps/pos
#     args: >
#       -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
#       -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
#       -Dsonar.projectKey=DashboardPOSMicroAppDev
#       -Dsonar.projectName=DashboardPOSMicroAppDev
#       -Dsonar.projectVersion=${{ github.sha }}

# # Perform code coverage check on PR changes vs master
# - name: PR code coverage check
#   id: pr-code-coverage-check
#   working-directory: ./apps/pos
#   run: ./sonar-analysis.sh
#   env:
#     SONAR_HOST: ${{ secrets.SONARQUBE_HOST }}
#     SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
#     PROJECT_KEY_DEV: DashboardPOSMicroAppDev
#     PROJECT_KEY_PROD: DashboardPOSMicroApp
#     FILE_NAME: comment.txt
#     FILE_HEADING: "Sonar Analysis Report"

# - name: Update Sonar Analysis Comment
#   uses: marocchino/sticky-pull-request-comment@v2
#   with:
#     recreate: true
#     header: POSApp - Code Coverage
#     path: ./apps/pos/comment.txt

# # Perform new code coverage check on PR changes
# - name: PR new code coverage check
#   id: pr-new-code-coverage-check
#   working-directory: ./apps/pos
#   run: node ./new-coverage.js
#   env:
#     SONAR_HOST: ${{ secrets.SONARQUBE_HOST }}
#     SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
#     PROJECT_KEY_DEV: DashboardPOSMicroAppDev
#     PROJECT_KEY_PROD: DashboardPOSMicroApp
#     FILE_NAME: quality-gate.txt
#     FILE_HEADING: "Sonar Analysis Quality Gate Report"

# - name: Update Sonar Analysis Comment
#   uses: marocchino/sticky-pull-request-comment@v2
#   with:
#     recreate: true
#     header: POSApp - Quality Gate
#     path: ./apps/pos/quality-gate.txt
