<?php

use RZP\Models\Merchant\Detail\Constants as C;
use RZP\Models\Merchant\Detail\Entity as E;
use RZP\Models\Admin\Permission\Name as N;
use RZP\Models\Workflow\Action\MakerType as MT;

return [
    "testValidateInternalWebsiteUpdateValidations" => [
        "valid case should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "null permission should pass" => [
            [
                C::PERMISSION           => null,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "invalid permission should fail" => [
            [
                C::PERMISSION           => "UPDATE_MERCHANT_WEBSITE",
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_PERMISSION,
        ],
        "invalid route name should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "random_route_that_does_not_exist",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_ROUTE_NAME,
        ],
        "null route name should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => null,
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "invalid controller should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantsController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_CONTROLLER,
        ],
        "random string as controlle should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController\internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_CONTROLLER,
        ],
        "null controller should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => null,
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "invalid maker type should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => "asdadad",
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_WORKFLOW_MAKER_TYPE,
        ],
        "imitate proxy auth as int should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => 1,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_BOOL,
        ],
        "imitate proxy auth as string int should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => "1",
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_BOOL,
        ],
        "imitate proxy auth as random string should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => "asdad",
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_BOOL,
        ],
        "maker from auth as int should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => 1,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_BOOL,
        ],
        "maker from auth as string int should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => "1",
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_BOOL,
        ],
        "maker from auth as random string should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => "asdadsad",
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
            C::INVALID_BOOL,
        ],
        "null imitiate proxy auth and maker from auth should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => null,
                C::MAKER_FROM_AUTH      => null,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "null tag should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => null,
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "tags with array of int should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => [1, 2, 3],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
        ],
        "route params without associative array should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
        ],
        "tags with string should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => "tag1",
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
        ],
        "null route params should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => null,
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "route params as string should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => "10000000000000",
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
        ],
        "null entity should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => null,
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "null entity id should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => null,
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "null uri should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => null,
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "null method should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => null,
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "null original should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => null,
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "null dirty pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => null,
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "null admin email should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => null,
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "null orgid should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => null,
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
        ],
        "null comments should pass" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => null,
            ],
        ],
        "entity length less then 3 should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "as",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class,
        ],
        "random string as entity id should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "asdadad",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestException::class
        ],
        "original as string should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000asdsad",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => "asdsadasd",
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "original as array of string should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => ["https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "dirty as random string should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => "https://razorpay.in",
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "dirty as array of string should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => ["https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "invalid admin email format should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "adminrazorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "random string as orgid should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "asdadad",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestException::class
        ],
        "comments as random string should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => "asdsadsad"
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "comments as array of string should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [C::WEBSITE_UPDATE ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],

        "admin email required when maker type is admin" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::ADMIN,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => null,
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "org id is required when maker type is admin" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::ADMIN,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => null,
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "entity is required for website update comment" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "entity id is required for workflow comment" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "invalid entity id in workflow comment should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "asdasd",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestException::class
        ],
        "permission is required for workflow comment" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "invalid permission for workflow comment should fail" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => "asdadad",
                        C::COMMENT      => "test comment",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "comment is required for workflow comment" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
        "workflow comment length should be minimum 4" => [
            [
                C::PERMISSION           => N::UPDATE_MERCHANT_WEBSITE,
                C::ROUTE_NAME           => "internal_post_website_update",
                C::CONTROLLER           => "RZP\Http\Controllers\MerchantController@internalUpdateWebsite",
                C::WORKFLOW_MAKER_TYPE  => MT::MERCHANT,
                C::IMITATE_PROXY_AUTH   => true,
                C::MAKER_FROM_AUTH      => false,
                C::TAGS                 => ["tag1"],
                C::ROUTE_PARAMS         => ["id" => "10000000000000"],
                C::ENTITY               => "merchant_details",
                C::ENTITY_ID            => "10000000000000",
                C::URI                  => "/v1/api/merchants/10000000000000/details",
                C::METHOD               => "POST",
                C::ORIGINAL             => [E::BUSINESS_WEBSITE => "https://razorpay.com"],
                C::DIRTY                => [E::BUSINESS_WEBSITE => "https://razorpay.in"],
                C::ADMIN_EMAIL          => "admin@razorpay.com",
                C::ORG_ID               => "100000razorpay",
                C::COMMENTS             => [
                    [
                        C::IDENTIFIER   => C::WEBSITE_UPDATE,
                        C::ENTITY       => "merchant_details",
                        C::ENTITY_ID    => "10000000000000",
                        C::PERMISSION   => N::UPDATE_MERCHANT_WEBSITE,
                        C::COMMENT      => "asd",
                    ],
                ]
            ],
            \RZP\Exception\BadRequestValidationFailureException::class
        ],
    ],
];
