export enum DEVICE_DEPLOYMENT_FIELDS {
  DEVICE_DEPLOYMENT_STEP = 'device_deployment_step',
  DEVICE_TESTING_COMPONENT = 'device_testing_component',
  LANGUAGE_CONFIGURATION_COMPONENT = 'device_language_settings_component',
  WIFI_CONFIGURATION_COMPONENT = 'device_wifi_configuration_component',
  DEVICE_CONFIGURATION_COMPONENT = 'device_configuration_step',
  DEVICE_DEPLOYMENT_DETAILS_LIST_FIELD = 'device_deployment_details_list_field',
  ALL_DEVICES_FIELD = 'all_devices_field',
  DEPLOYED_DEVICES_FIELD = 'deployed_devices_field',
  DEVICE_TYPE_FIELD = 'device_type_field',
  DEVICE_STATUS_FIELD = 'device_status_field',
  DEVICE_NAME_OR_SERIAL_NUM_FIELD = 'device_name_or_serial_num_field',
  DEVICES_LIST_FIELD = 'devices_list_field',
  CURRENT_DEVICE_ID_FIELD = 'current_device_id_field',
  DEVICE_SERIAL_NUMBER_FIELD = 'device_serial_number_field',
  DEVICES_QR_FIELD = 'device_qr_field',
  ALL_DEVICES_DEPLOYED_FIELD = 'all_devices_deployed_field',
  DEVICES_CONFIGS_SUMMARY_FIELD = 'device_configs_summary_field',
  MODULAR_CALLBACK = 'modular_callback',
  DEVICE_WIFI_CONFIGURATION_STATUS_FIELD = 'device_wifi_configuration_status_field',
  DEVICE_MAPPING_STATUS_FIELD = 'device_mapping_status_field',
  DEVICE_VPA_FIELD = 'device_vpa_field',
  DEVICE_QR_STRING_FIELD = 'device_qr_string_field',
  DEVICE_DEPLOYMENT_ACTION_FIELD = 'device_deployment_action_field',

  DEVICE_DEPLOYMENT_COMPONENT = 'device_deployment_component',
  DEVICE_LANGUAGE_FIELD = 'device_language_field',
  DEVICE_TESTING_AMOUNT_FIELD = 'device_testing_amount_field',
  DEVICE_TESTING_SEND_AMOUNT_FIELD = 'device_testing_send_amount_field',
  DEVICE_TESTING_RESEND_ANOUNT_FIELD = 'device_testing_resend_amount_field',
  DEVICE_TESTING_AMOUNT_RECEIVED_FIELD = 'device_testing_amount_received_field',
  DEVICE_WIFI_CONFIGURATION_FIELD = 'device_wifi_configuration_field',
  DEVICE_CONFIGS_SUMMARY_FIELD = 'device_configs_summary_field',

  DEVICE_MAPPING_BY_SCANNING_COMPONENT = 'device_mapping_by_scanning_component',
  DEVICE_MAPPING_SCANNER_FIELD = 'device_mapping_scanner_field',
  DEVICE_MAPPING_BY_BARCODE_FIELD = 'device_mapping_by_barcode_field',
  DEVICE_MAPPING_BY_QR_FIELD = 'device_mapping_by_qr_field',
  DEVICE_MAPPING_BY_MANUAL_FIELD = 'device_mapping_by_manual_field',

  DEVICE_MAPPING_BY_MANUAL_COMPONENT = 'device_mapping_by_manual_component',
  REFRESH_DEVICE_DEPLOYMENT_LIST = 'refresh_device_deployment_list',
}
