CREATE DATABASE IF NOT EXISTS api_live;
CREATE DATABASE IF NOT EXISTS api_test;
CREATE DATABASE IF NOT EXISTS api_testing_live;
CREATE DATABASE IF NOT EXISTS api_testing_test;
CREATE DATABASE IF NOT EXISTS auth;
CREATE DATABASE IF NOT EXISTS auth_test;
DROP USER IF EXISTS 'api_user'@'%';
FLUSH PRIVILEGES;
CREATE USER 'api_user'@'%' identified by '123';
CREATE USER 'migration_user_name'@'%' identified by '123';
GRANT ALL PRIVILEGES ON api_live.* TO 'api_user'@'%';
GRANT ALL PRIVILEGES ON api_test.* TO 'api_user'@'%';
GRANT ALL PRIVILEGES ON api_testing_live.* TO 'api_user'@'%';
GRANT ALL PRIVILEGES ON api_testing_test.* TO 'api_user'@'%';
GRANT ALL PRIVILEGES ON auth.* TO 'api_user'@'%';
GRANT ALL PRIVILEGES ON auth_test.* TO 'api_user'@'%';
GRANT CREATE,INSERT,SELECT,UPDATE,ALTER,REFERENCES,CREATE VIEW ON api_live.* to 'migration_user_name'@'%';
GRANT CREATE,INSERT,SELECT,UPDATE,ALTER,REFERENCES,CREATE VIEW ON api_test.* to 'migration_user_name'@'%';
GRANT CREATE,INSERT,SELECT,UPDATE,ALTER,REFERENCES,CREATE VIEW ON api_testing_live.* to 'migration_user_name'@'%';
GRANT CREATE,INSERT,SELECT,UPDATE,ALTER,REFERENCES,CREATE VIEW ON api_testing_test.* to 'migration_user_name'@'%';
GRANT CREATE,INSERT,SELECT,UPDATE,ALTER,REFERENCES,CREATE VIEW ON auth.* to 'migration_user_name'@'%';
GRANT CREATE,INSERT,SELECT,UPDATE,ALTER,REFERENCES,CREATE VIEW ON auth_test.* to 'migration_user_name'@'%';