<?php

use RZP\Error\ErrorCode;
use RZP\Error\PublicErrorCode;
use RZP\Error\PublicErrorDescription;

return [
    'testPayment' => [
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'method' => 'netbanking',
        'status' => 'captured',
        'amount_authorized' => 50000,
        'amount_refunded' => 0,
        'refund_status' => null,
        'currency' => 'INR',
        'description' => 'random description',
        'bank' => 'ICIC',
        'error_code' => null,
        'error_description' => null,
        'email' => 'a@b.com',
        'contact' => '+919918899029',
        'notes' => [
            'merchant_order_id' => 'random order id',
        ],
        'gateway' => 'billdesk',
        'terminal_id' => '1000BdeskTrmnl',
        'signed' => false,
        'verified' => null,
        'fee' => 1438,
        'service_tax' => 188,
        'entity' => 'payment',
    ],

    'testTransactionAfterAuthorize' => [
        'type' => 'payment',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 1438,
        'service_tax' => 188,
        'pricing_rule_id' => '1zD0BXpeOyaqpB',
        'debit' => 0,
        'credit' => 48562,
        'currency' => 'INR',
        'balance' => 0,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'escrow_balance' => 1048562,
        'channel' => 'kotak',
        'settled' => false,
        'settled_at' => null,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testTransactionAfterCapture' => [
        'type' => 'payment',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 1438,
        'debit' => 0,
        'credit' => 48562,
        'currency' => 'INR',
        'balance' => 1048562,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'escrow_balance' => 1048562,
        'channel' => 'kotak',
        'settled' => false,
//        'settled_at' => 1437589800,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testPaymentBilldeskEntity' => [
        'action' => 'authorize',
        'received' => true,
        'BankID'=> 'ICI',
        'CurrencyType'=> 'INR',
        'ItemCode'=> 'DIRECT',
        'TypeField1'=> 'R',
        'TypeField2'=> 'F',
        'RefAmount'=> null,
        'RefDateTime'=> null,
        'RefStatus'=> null,
        'RefundId'=> null,
        'ErrorCode'=> null,
        'ErrorReason'=> null,
        'ProcessStatus'=> null,
        'refund_id'=> null,
        'entity'=> 'billdesk',
    ],

    'testPaymentRefund' => [
//        'id'=> '76',
//        'payment_id'=> '3PgPULSRMSgExV',
        'action'=> 'refund',
        'received' => true,
//        'MerchantID'=> 'random',
//        'CustomerID'=> '3PgPULSRMSgExV',
        'TxnAmount'=> '5.00',
        'BankID'=> null,
        'CurrencyType'=> 'INR',
        'ItemCode'=> null,
        'TypeField1'=> null,
        'TypeField2'=> null,
        'AdditionalInfo1'=> null,
//        'TxnReferenceNo'=> 'trbqkfizxs',
        'BankReferenceNo'=> null,
        'BankMerchantID'=> null,
        'SecurityType'=> null,
//        'TxnDate'=> '20-06-2015 00:00:00',
        'AuthStatus'=> null,
        'SettlementType'=> null,
        'ErrorStatus'=> null,
        'ErrorDescription'=> null,
        'RequestType'=> '0410',
        'RefAmount'=> '500.00',
//        'RefDateTime'=> '201506200040838',
        'RefStatus'=> '0799',
//        'RefundId'=> 'hlbdtgwnofsxmcj',
        'ErrorCode'=> 'NA',
        'ErrorReason'=> 'NA',
        'ProcessStatus'=> 'Y',
        // 'refund_id'=> '3PgPUT2YOO6htv',
        // 'created_at'=> 1434753518,
        // 'updated_at'=> 1434753518,
        'entity'=> 'billdesk',
    ],

    'testPaymentMultiplePartialRefund' => [
        'action'=> 'refund',
        'received' => true,
        'TxnAmount'=> '5.00',
        'BankID'=> null,
        'CurrencyType'=> 'INR',
        'ItemCode'=> null,
        'TypeField1'=> null,
        'TypeField2'=> null,
        'AdditionalInfo1'=> null,
        'BankReferenceNo'=> null,
        'BankMerchantID'=> null,
        'SecurityType'=> null,
        'AuthStatus'=> null,
        'SettlementType'=> null,
        'ErrorStatus'=> null,
        'ErrorDescription'=> null,
        'RequestType'=> '0410',
        'RefAmount'=> '100.00',
        'RefStatus'=> '0799',
        'ErrorCode'=> 'NA',
        'ErrorReason'=> 'NA',
        'ProcessStatus'=> 'Y',
        'entity'=> 'billdesk',
    ],

    'testPaymentPartialRefund' => [
        'action'=> 'refund',
        'received' => true,
        'TxnAmount'=> '5.00',
        'BankID'=> null,
        'CurrencyType'=> 'INR',
        'ItemCode'=> null,
        'TypeField1'=> null,
        'TypeField2'=> null,
        'AdditionalInfo1'=> null,
        'BankReferenceNo'=> null,
        'BankMerchantID'=> null,
        'SecurityType'=> null,
        'AuthStatus'=> null,
        'SettlementType'=> null,
        'ErrorStatus'=> null,
        'ErrorDescription'=> null,
        'RequestType'=> '0410',
        'RefAmount'=> '400.00',
        'RefStatus'=> '0799',
        'ErrorCode'=> 'NA',
        'ErrorReason'=> 'NA',
        'ProcessStatus'=> 'Y',
        'entity'=> 'billdesk',
    ],

    'testTransactionAfterRefundingAuthorizedPayment' => [
        'type' => 'refund',
        'merchant_id' => '10000000000000',
        'amount' => 50000,
        'fee' => 0,
        'pricing_rule_id' => null,
        'debit' => 50000,
        'credit' => 0,
        'currency' => 'INR',
        'balance' => 0,
        'gateway_fee' => 0,
        'api_fee' => 0,
        'fee' => 0,
        'service_tax' => 0,
        'escrow_balance' => 998562,
        'channel' => 'kotak',
        'settled' => false,
        'settled_at' => null,
        'settlement_id' => null,
        'reconciled_at' => null,
        'entity' => 'transaction',
        'admin' => true,
    ],

    'testGetPaymentMethodsRoute' => [
        'request' => [
            'url' => '/methods',
            'method' => 'get',
        ],
        'response' => [
            'content' => [
                'entity' => 'methods',
                'card' => true,
                'netbanking' => [
                    'UTIB' => 'Axis Bank',
//                    'BARB' => 'Bank of Baroda',
                    'YESB' => 'Yes Bank',
                ],
                'wallet' => [],
            ],
        ],
    ],

    'testPaymentMultipleInvalidPartialRefund' => [
        'response'  => [
            'content'     => [
                'error' => [
                    'code'          => PublicErrorCode::BAD_REQUEST_ERROR,
                    'description'   => PublicErrorDescription::BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_UNREFUNDED,
                ],
            ],
            'status_code' => 400,
        ],
        'exception' => [
            'class'                 => 'RZP\Exception\BadRequestException',
            'internal_error_code'   => ErrorCode::BAD_REQUEST_PAYMENT_REFUND_AMOUNT_GREATER_THAN_UNREFUNDED,
        ],
    ],
];
