<?php

namespace RZP\Models\Merchant\Detail;

use RZP\Models\Merchant\Detail\BusinessSubcategory as Sub;
use RZP\Models\Merchant\Entity as Merchant;


class BusinessSubCategoryMetaData
{
    const DESCRIPTION                     = 'description';

    const SUB_CATEGORY_METADATA = [
        Sub::ACCOMMODATION => [
            Merchant::CATEGORY                           => 7011,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ACCOMMODATION],
            Merchant::CATEGORY2                          => Category2::HOSPITALITY,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::ACCOUNTING => [
            Merchant::CATEGORY                           => 8931,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ACCOUNTING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::AD_AND_MARKETING => [
            Merchant::CATEGORY                           => 7311,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::AD_AND_MARKETING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::AGRICULTURE => [
            Merchant::CATEGORY                           => 5193,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::AGRICULTURE],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::ALCOHOL => [
            Merchant::CATEGORY                           => 5813,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ALCOHOL],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::BLACKLISTED,
        ],
        Sub::ARTS_AND_COLLECTIBLES => [
            Merchant::CATEGORY                           => 5971,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ARTS_AND_COLLECTIBLES],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::AVIATION => [
            Merchant::CATEGORY                           => 4511,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::AVIATION],
            Merchant::CATEGORY2                          => Category2::TRAVEL_AGENCY,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::BABY_PRODUCTS => [
            Merchant::CATEGORY                           => 5945,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::BABY_PRODUCTS],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::BETTING => [
            Merchant::CATEGORY                           => 7801,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::BETTING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::BLACKLISTED,
        ],
        Sub::BILL_AND_RECHARGE_AGGREGATORS => [
            Merchant::CATEGORY                           => 4814,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::BILL_AND_RECHARGE_AGGREGATORS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::BOOKS => [
            Merchant::CATEGORY                           => 5942,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::BOOKS],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::BROADBAND => [
            Merchant::CATEGORY                           => 4899,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::BROADBAND],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::BUS => [
            Merchant::CATEGORY                           => 4131,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::BUS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::CABLE => [
            Merchant::CATEGORY                           => 4899,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CABLE],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::CAB_HAILING => [
            Merchant::CATEGORY                           => 4121,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CAB_HAILING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::CATERING => [
            Merchant::CATEGORY                           => 5811,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CATERING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::CENTRAL => [
            Merchant::CATEGORY                           => 9399,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CENTRAL],
            Merchant::CATEGORY2                          => Category2::GOVERNMENT,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::CHARITY => [
            Merchant::CATEGORY                           => 8398,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CHARITY],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::CLINIC => [
            Merchant::CATEGORY                           => 8062,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CLINIC],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::COACHING => [
            Merchant::CATEGORY                           => 8299,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::COACHING],
            Merchant::CATEGORY2                          => Category2::PVT_EDUCATION,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::COLLEGE => [
            Merchant::CATEGORY                           => 8220,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::COLLEGE],
            Merchant::CATEGORY2                          => Category2::PVT_EDUCATION,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::COMMODITIES => [
            Merchant::CATEGORY                           => 6211,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::COMMODITIES],
            Merchant::CATEGORY2                          => Category2::SECURITIES,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::CONSULTING => [
            Merchant::CATEGORY                           => 7392,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CONSULTING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::CONSULTING_AND_OUTSOURCING => [
            Merchant::CATEGORY                           => 7392,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CONSULTING_AND_OUTSOURCING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::CONTENT_AND_PUBLISHING => [
            Merchant::CATEGORY                           => 2741,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CONTENT_AND_PUBLISHING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::COOPERATIVES => [
            Merchant::CATEGORY                           => 6012,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::COOPERATIVES],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::COUPONS => [
            Merchant::CATEGORY                           => 7311,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::COUPONS],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::COURIER => [
            Merchant::CATEGORY                           => 4215,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::COURIER],
            Merchant::CATEGORY2                          => Category2::LOGISTICS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::COWORKING => [
            Merchant::CATEGORY                           => 6513,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::COWORKING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::CROWDFUNDING => [
            Merchant::CATEGORY                           => 6050,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CROWDFUNDING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::CRYPTOCURRENCY => [
            Merchant::CATEGORY                           => 6051,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CRYPTOCURRENCY],
            Merchant::CATEGORY2                          => Category2::CRYPTOCURRENCY,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::BLACKLISTED,
        ],
        Sub::CRYPTO_MACHINERY => [
            Merchant::CATEGORY                           => 5999,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::CRYPTO_MACHINERY],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::BLACKLISTED,
        ],
        Sub::DEVELOPER => [
            Merchant::CATEGORY                           => 6513,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::DEVELOPER],
            Merchant::CATEGORY2                          => Category2::HOUSING,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::DIETICIAN => [
            Merchant::CATEGORY                           => 7298,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::DIETICIAN],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::DISTANCE_LEARNING => [
            Merchant::CATEGORY                           => 8299,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::DISTANCE_LEARNING],
            Merchant::CATEGORY2                          => Category2::PVT_EDUCATION,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::DISTRIBUTION_MANAGEMENT => [
            Merchant::CATEGORY                           => 4214,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::DISTRIBUTION_MANAGEMENT],
            Merchant::CATEGORY2                          => Category2::LOGISTICS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::DROP_SHIPPING => [
            Merchant::CATEGORY                           => 5399,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::DROP_SHIPPING],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::DTH => [
            Merchant::CATEGORY                           => 4899,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::DTH],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::ECOMMERCE_MARKETPLACE => [
            Merchant::CATEGORY                           => 5399,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ECOMMERCE_MARKETPLACE],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::EDUCATIONAL => [
            Merchant::CATEGORY                           => 8398,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::EDUCATIONAL],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::ELEARNING => [
            Merchant::CATEGORY                           => 8299,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ELEARNING],
            Merchant::CATEGORY2                          => Category2::PVT_EDUCATION,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::ELECTRICITY => [
            Merchant::CATEGORY                           => 4900,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ELECTRICITY],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::ELECTRONICS_AND_FURNITURE => [
            Merchant::CATEGORY                           => 5732,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ELECTRONICS_AND_FURNITURE],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::END_TO_END_LOGISTICS => [
            Merchant::CATEGORY                           => 4214,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::END_TO_END_LOGISTICS],
            Merchant::CATEGORY2                          => Category2::LOGISTICS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::ESPORTS => [
            Merchant::CATEGORY                           => 5816,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ESPORTS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::EVENT_PLANNING => [
            Merchant::CATEGORY                           => 8999,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::EVENT_PLANNING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::FACILITY_MANAGEMENT => [
            Merchant::CATEGORY                           => 7349,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::FACILITY_MANAGEMENT],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::FANTASY_SPORTS => [
            Merchant::CATEGORY                           => 5816,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::FANTASY_SPORTS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::FASHION_AND_LIFESTYLE => [
            Merchant::CATEGORY                           => 5691,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::FASHION_AND_LIFESTYLE],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::FINANCIAL_ADVISOR => [
            Merchant::CATEGORY                           => 8931,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::FINANCIAL_ADVISOR],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::FITNESS => [
            Merchant::CATEGORY                           => 7298,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::FITNESS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::FOOD_COURT => [
            Merchant::CATEGORY                           => 5814,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::FOOD_COURT],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::FOREX => [
            Merchant::CATEGORY                           => 6010,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::FOREX],
            Merchant::CATEGORY2                          => Category2::FOREX,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::FREIGHT => [
            Merchant::CATEGORY                           => 4214,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::FREIGHT],
            Merchant::CATEGORY2                          => Category2::LOGISTICS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::GAME_DEVELOPER => [
            Merchant::CATEGORY                           => 5816,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::GAME_DEVELOPER],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::GAMING_MARKETPLACE => [
            Merchant::CATEGORY                           => 5816,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::GAMING_MARKETPLACE],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::GAS => [
            Merchant::CATEGORY                           => 4900,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::GAS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::GET_RICH_SCHEMES => [
            Merchant::CATEGORY                           => 7361,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::GET_RICH_SCHEMES],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::BLACKLISTED,
        ],
        Sub::GIFTING => [
            Merchant::CATEGORY                           => 5193,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::GIFTING],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::GROCERY => [
            Merchant::CATEGORY                           => 5411,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::GROCERY],
            Merchant::CATEGORY2                          => Category2::GROCERY,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::HEALTH_COACHING => [
            Merchant::CATEGORY                           => 7298,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::HEALTH_COACHING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::HEALTH_PRODUCTS => [
            Merchant::CATEGORY                           => 5499,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::HEALTH_PRODUCTS],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::HEALTHCARE_MARKETPLACE => [
            Merchant::CATEGORY                           => 5399,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::HEALTHCARE_MARKETPLACE],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::HOSPITAL => [
            Merchant::CATEGORY                           => 8062,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::HOSPITAL],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::IAAS => [
            Merchant::CATEGORY                           => 5817,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::IAAS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::INSURANCE => [
            Merchant::CATEGORY                           => 6300,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::INSURANCE],
            Merchant::CATEGORY2                          => Category2::INSURANCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::INTERIOR_DESIGN_AND_ARCHITECT => [
            Merchant::CATEGORY                           => 8911,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::INTERIOR_DESIGN_AND_ARCHITECT],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::INTERNET_PROVIDER => [
            Merchant::CATEGORY                           => 4816,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::INTERNET_PROVIDER],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::LAB => [
            Merchant::CATEGORY                           => 8071,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::LAB],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::LEGAL => [
            Merchant::CATEGORY                           => 8111,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::LEGAL],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::LENDING => [
            Merchant::CATEGORY                           => 6012,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::LENDING],
            Merchant::CATEGORY2                          => Category2::LENDING,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::MATCHMAKING => [
            Merchant::CATEGORY                           => 7273,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::MATCHMAKING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::MESSAGING => [
            Merchant::CATEGORY                           => 4821,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::MESSAGING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::MOVERS_AND_PACKERS => [
            Merchant::CATEGORY                           => 4214,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::MOVERS_AND_PACKERS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::MULTI_LEVEL_MARKETING => [
            Merchant::CATEGORY                           => 5964,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::MULTI_LEVEL_MARKETING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::BLACKLISTED,
        ],
        Sub::MULTIPLEX => [
            Merchant::CATEGORY                           => 7832,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::MULTIPLEX],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::MUSIC_STREAMING => [
            Merchant::CATEGORY                           => 5815,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::MUSIC_STREAMING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::MUTUAL_FUND => [
            Merchant::CATEGORY                           => 6211,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::MUTUAL_FUND],
            Merchant::CATEGORY2                          => Category2::MUTUAL_FUNDS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::NBFC => [
            Merchant::CATEGORY                           => 6012,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::NBFC],
            Merchant::CATEGORY2                          => Category2::LENDING,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::NEIGHBOURHOOD_NETWORK => [
            Merchant::CATEGORY                           => 8699,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::NEIGHBOURHOOD_NETWORK],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::NEWS => [
            Merchant::CATEGORY                           => 5994,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::NEWS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::OFFICE_SUPPLIES => [
            Merchant::CATEGORY                           => 5111,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::OFFICE_SUPPLIES],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::ONLINE_CASINO => [
            Merchant::CATEGORY                           => 7801,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ONLINE_CASINO],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::BLACKLISTED,
        ],
        Sub::ONLINE_FOOD_ORDERING => [
            Merchant::CATEGORY                           => 5811,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::ONLINE_FOOD_ORDERING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::OTA => [
            Merchant::CATEGORY                           => 4722,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::OTA],
            Merchant::CATEGORY2                          => Category2::TRAVEL_AGENCY,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::PAAS => [
            Merchant::CATEGORY                           => 5817,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::PAAS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::PENSION_FUND => [
            Merchant::CATEGORY                           => 6012,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::PENSION_FUND],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::PERSONAL => [
            Merchant::CATEGORY                               => 8398,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::PERSONAL],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::PROFESSIONAL_COURSES => [
            Merchant::CATEGORY                           => 8299,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::PROFESSIONAL_COURSES],
            Merchant::CATEGORY2                          => Category2::PVT_EDUCATION,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::PET_PRODUCTS => [
            Merchant::CATEGORY                           => 5995,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::PET_PRODUCTS],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::PHARMACY => [
            Merchant::CATEGORY                           => 5912,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::PHARMACY],
            Merchant::CATEGORY2                          => Category2::PHARMA,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::PROFESSIONAL_NETWORK => [
            Merchant::CATEGORY                           => 8699,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::PROFESSIONAL_NETWORK],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::REALESTATE_CLASSIFIEDS => [
            Merchant::CATEGORY                           => 6513,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::REALESTATE_CLASSIFIEDS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::RELIGIOUS => [
            Merchant::CATEGORY                           => 8661,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::RELIGIOUS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::RELIGIOUS_PRODUCTS => [
            Merchant::CATEGORY                           => 5973,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::RELIGIOUS_PRODUCTS],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::RENTAL => [
            Merchant::CATEGORY                           => 7394,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::RENTAL],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::REPAIR_AND_CLEANING => [
            Merchant::CATEGORY                           => 7531,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::REPAIR_AND_CLEANING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::RESTAURANT => [
            Merchant::CATEGORY                           => 5812,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::RESTAURANT],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::RESTAURANT_SEARCH_AND_BOOKING => [
            Merchant::CATEGORY                           => 7299,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::RESTAURANT_SEARCH_AND_BOOKING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::RWA => [
            Merchant::CATEGORY                           => 7349,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::RWA],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::SAAS => [
            Merchant::CATEGORY                           => 5817,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::SAAS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::SCHOOLS => [
            Merchant::CATEGORY                           => 8211,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::SCHOOLS],
            Merchant::CATEGORY2                          => Category2::PVT_EDUCATION,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::SECURITIES => [
            Merchant::CATEGORY                           => 6211,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::SECURITIES],
            Merchant::CATEGORY2                          => Category2::SECURITIES,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::SERVICE_CENTRE => [
            Merchant::CATEGORY                           => 5511,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::SERVICE_CENTRE],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::SERVICES_CLASSIFIEDS => [
            Merchant::CATEGORY                           => 7311,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::SERVICES_CLASSIFIEDS],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::SEXUAL_WELLNESS_PRODUCT =>[
            Merchant::CATEGORY                           => 5999,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::SEXUAL_WELLNESS_PRODUCT],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::SOCIAL_NETWORK => [
            Merchant::CATEGORY                           => 8641,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::SOCIAL_NETWORK],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::SPACE_RENTAL => [
            Merchant::CATEGORY                           => 6513,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::SPACE_RENTAL],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::SPORTS_PRODUCTS => [
            Merchant::CATEGORY                           => 5941,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::SPORTS_PRODUCTS],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::STATE => [
            Merchant::CATEGORY                           => 9399,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::STATE],
            Merchant::CATEGORY2                          => Category2::GOVERNMENT,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::TECHNICAL_SUPPORT => [
            Merchant::CATEGORY                           => 7379,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::TECHNICAL_SUPPORT],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::BLACKLISTED,
        ],
        Sub::TELECOM => [
            Merchant::CATEGORY                           => 4814,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::TELECOM],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::TICKETING => [
            Merchant::CATEGORY                           => 7832,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::TICKETING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::TOBACCO => [
            Merchant::CATEGORY                           => 5993,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::TOBACCO],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::BLACKLISTED,
        ],
        Sub::TRADING => [
            Merchant::CATEGORY                           => 6211,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::TRADING],
            Merchant::CATEGORY2                          => Category2::SECURITIES,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::TRAIN_AND_METRO => [
            Merchant::CATEGORY                           => 4112,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::TRAIN_AND_METRO],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::TRAVEL_AGENCY => [
            Merchant::CATEGORY                           => 4722,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::TRAVEL_AGENCY],
            Merchant::CATEGORY2                          => Category2::TRAVEL_AGENCY,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::UNIVERSITY => [
            Merchant::CATEGORY                           => 8220,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::UNIVERSITY],
            Merchant::CATEGORY2                          => Category2::PVT_EDUCATION,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::VIDEO_ON_DEMAND => [
            Merchant::CATEGORY                           => 5815,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::VIDEO_ON_DEMAND],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::WATER => [
            Merchant::CATEGORY                           => 4900,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::WATER],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::WAREHOUSING => [
            Merchant::CATEGORY                           => 4225,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::WAREHOUSING],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
        Sub::WEAPONS_AND_AMMUNITIONS => [
            Merchant::CATEGORY                           => 5999,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::WEAPONS_AND_AMMUNITIONS],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::BLACKLISTED,
        ],
        Sub::WEB_DEVELOPMENT => [
            Merchant::CATEGORY                           => 7372,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::WEB_DEVELOPMENT],
            Merchant::CATEGORY2                          => Category2::OTHERS,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::GREYLISTED,
        ],
        Sub::WHOLESALE => [
            Merchant::CATEGORY                           => 5300,
            self::DESCRIPTION                            => Sub::DESCRIPTIONS[Sub::WHOLESALE],
            Merchant::CATEGORY2                          => Category2::ECOMMERCE,
            Entity::ACTIVATION_CATEGORY                  => ActivationCategory::WHITELISTED,
        ],
    ];
}
