<?php

namespace RZP\Models\Merchant\Detail;

use RZP\Error\ErrorCode;
use RZP\Models\Terminal\Category;
use RZP\Exception\BadRequestException;
use RZP\Models\Merchant\Entity as Merchant;
use RZP\Models\Merchant\Detail\BusinessSubcategory as Sub;

class BusinessSubCategoryMetaData
{
    const DESCRIPTION               = 'description';
    const NORMAL_AUTH_FIELDS        = [self::DESCRIPTION];
    const EMI_ACTIVATION            = 'emi_activation';
    const INTERNATIONAL_ACTIVATION  = 'international_activation';

    // @TODO add metadata for others
    const SUB_CATEGORY_METADATA = [
        Sub::ACCOMMODATION                 => [
            Merchant::CATEGORY             => 7011,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ACCOMMODATION],
            Merchant::CATEGORY2            => Category::HOSPITALITY,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::ACCOUNTING                    => [
            Merchant::CATEGORY             => 8931,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ACCOUNTING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::AD_AND_MARKETING              => [
            Merchant::CATEGORY             => 7311,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::AD_AND_MARKETING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::AGRICULTURE                   => [
            Merchant::CATEGORY             => 5193,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::AGRICULTURE],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::ALCOHOL                       => [
            Merchant::CATEGORY             => 5813,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ALCOHOL],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::BLACKLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::ARTS_AND_COLLECTIBLES         => [
            Merchant::CATEGORY             => 5971,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ARTS_AND_COLLECTIBLES],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::AVIATION                      => [
            Merchant::CATEGORY             => 4511,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::AVIATION],
            Merchant::CATEGORY2            => Category::TRAVEL_AGENCY,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::BABY_PRODUCTS                 => [
            Merchant::CATEGORY             => 5945,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::BABY_PRODUCTS],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::BETTING                       => [
            Merchant::CATEGORY             => 7801,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::BETTING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::BLACKLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::BILL_AND_RECHARGE_AGGREGATORS => [
            Merchant::CATEGORY             => 4814,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::BILL_AND_RECHARGE_AGGREGATORS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::BOOKS                         => [
            Merchant::CATEGORY             => 5942,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::BOOKS],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::BROADBAND                     => [
            Merchant::CATEGORY             => 4899,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::BROADBAND],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::BUS                           => [
            Merchant::CATEGORY             => 4131,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::BUS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::CABLE                         => [
            Merchant::CATEGORY             => 4899,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CABLE],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::CAB_HAILING                   => [
            Merchant::CATEGORY             => 4121,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CAB_HAILING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::CATERING                      => [
            Merchant::CATEGORY             => 5811,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CATERING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::CENTRAL                       => [
            Merchant::CATEGORY             => 9399,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CENTRAL],
            Merchant::CATEGORY2            => Category::GOVERNMENT,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::CHARITY                       => [
            Merchant::CATEGORY             => 8398,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CHARITY],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::CLINIC                        => [
            Merchant::CATEGORY             => 8062,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CLINIC],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::COACHING                      => [
            Merchant::CATEGORY             => 8299,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::COACHING],
            Merchant::CATEGORY2            => Category::PVT_EDUCATION,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::COLLEGE                       => [
            Merchant::CATEGORY             => 8220,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::COLLEGE],
            Merchant::CATEGORY2            => Category::PVT_EDUCATION,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::COMMODITIES                   => [
            Merchant::CATEGORY             => 6211,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::COMMODITIES],
            Merchant::CATEGORY2            => Category::SECURITIES,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::CONSULTING                    => [
            Merchant::CATEGORY             => 7392,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CONSULTING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::CONSULTING_AND_OUTSOURCING    => [
            Merchant::CATEGORY             => 7392,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CONSULTING_AND_OUTSOURCING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::CONTENT_AND_PUBLISHING        => [
            Merchant::CATEGORY             => 2741,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CONTENT_AND_PUBLISHING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::COOPERATIVES                  => [
            Merchant::CATEGORY             => 6012,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::COOPERATIVES],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::COUPONS                       => [
            Merchant::CATEGORY             => 7311,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::COUPONS],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::COURIER                       => [
            Merchant::CATEGORY             => 4215,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::COURIER],
            Merchant::CATEGORY2            => Category::LOGISTICS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::COWORKING                     => [
            Merchant::CATEGORY             => 6513,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::COWORKING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::CROWDFUNDING                  => [
            Merchant::CATEGORY             => 6050,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CROWDFUNDING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::CRYPTOCURRENCY                => [
            Merchant::CATEGORY             => 6051,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CRYPTOCURRENCY],
            Merchant::CATEGORY2            => Category::CRYPTOCURRENCY,
            Entity::ACTIVATION_FLOW        => ActivationFlow::BLACKLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::CRYPTO_MACHINERY              => [
            Merchant::CATEGORY             => 5999,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::CRYPTO_MACHINERY],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::BLACKLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::DAY_CARE                      => [
            Merchant::CATEGORY             => 8351,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::DAY_CARE],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::DEVELOPER                     => [
            Merchant::CATEGORY             => 6513,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::DEVELOPER],
            Merchant::CATEGORY2            => Category::HOUSING,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::DIETICIAN                     => [
            Merchant::CATEGORY             => 7298,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::DIETICIAN],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::DISTANCE_LEARNING             => [
            Merchant::CATEGORY             => 8299,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::DISTANCE_LEARNING],
            Merchant::CATEGORY2            => Category::PVT_EDUCATION,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::DISTRIBUTION_MANAGEMENT       => [
            Merchant::CATEGORY             => 4214,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::DISTRIBUTION_MANAGEMENT],
            Merchant::CATEGORY2            => Category::LOGISTICS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::DROP_SHIPPING                 => [
            Merchant::CATEGORY             => 5399,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::DROP_SHIPPING],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::DTH                           => [
            Merchant::CATEGORY             => 4899,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::DTH],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::ECOMMERCE_MARKETPLACE         => [
            Merchant::CATEGORY             => 5399,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ECOMMERCE_MARKETPLACE],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::EDUCATIONAL                   => [
            Merchant::CATEGORY             => 8398,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::EDUCATIONAL],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::ELEARNING                     => [
            Merchant::CATEGORY             => 8299,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ELEARNING],
            Merchant::CATEGORY2            => Category::PVT_EDUCATION,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::ELECTRICITY                   => [
            Merchant::CATEGORY             => 4900,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ELECTRICITY],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::ELECTRONICS_AND_FURNITURE     => [
            Merchant::CATEGORY             => 5732,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ELECTRONICS_AND_FURNITURE],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::END_TO_END_LOGISTICS          => [
            Merchant::CATEGORY             => 4214,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::END_TO_END_LOGISTICS],
            Merchant::CATEGORY2            => Category::LOGISTICS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::ESPORTS                       => [
            Merchant::CATEGORY             => 5816,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ESPORTS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::EVENT_PLANNING                => [
            Merchant::CATEGORY             => 8999,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::EVENT_PLANNING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::FACILITY_MANAGEMENT           => [
            Merchant::CATEGORY             => 7349,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::FACILITY_MANAGEMENT],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::FANTASY_SPORTS                => [
            Merchant::CATEGORY             => 5816,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::FANTASY_SPORTS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::FASHION_AND_LIFESTYLE         => [
            Merchant::CATEGORY             => 5691,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::FASHION_AND_LIFESTYLE],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::FINANCIAL_ADVISOR             => [
            Merchant::CATEGORY             => 8931,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::FINANCIAL_ADVISOR],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::FITNESS                       => [
            Merchant::CATEGORY             => 7298,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::FITNESS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::FOOD_COURT                    => [
            Merchant::CATEGORY             => 5814,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::FOOD_COURT],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::FOREX                         => [
            Merchant::CATEGORY             => 6010,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::FOREX],
            Merchant::CATEGORY2            => Category::FOREX,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::FREIGHT                       => [
            Merchant::CATEGORY             => 4214,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::FREIGHT],
            Merchant::CATEGORY2            => Category::LOGISTICS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::GAME_DEVELOPER                => [
            Merchant::CATEGORY             => 5816,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::GAME_DEVELOPER],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::GAMING_MARKETPLACE            => [
            Merchant::CATEGORY             => 5816,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::GAMING_MARKETPLACE],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::GAS                           => [
            Merchant::CATEGORY             => 4900,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::GAS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::GET_RICH_SCHEMES              => [
            Merchant::CATEGORY             => 7361,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::GET_RICH_SCHEMES],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::BLACKLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::GIFTING                       => [
            Merchant::CATEGORY             => 5193,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::GIFTING],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::GROCERY                       => [
            Merchant::CATEGORY             => 5411,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::GROCERY],
            Merchant::CATEGORY2            => Category::GROCERY,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::HEALTH_COACHING               => [
            Merchant::CATEGORY             => 7298,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::HEALTH_COACHING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::HEALTH_PRODUCTS               => [
            Merchant::CATEGORY             => 5499,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::HEALTH_PRODUCTS],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::HEALTHCARE_MARKETPLACE        => [
            Merchant::CATEGORY             => 5399,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::HEALTHCARE_MARKETPLACE],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::HOSPITAL                      => [
            Merchant::CATEGORY             => 8062,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::HOSPITAL],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::IAAS                          => [
            Merchant::CATEGORY             => 5817,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::IAAS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::INSURANCE                     => [
            Merchant::CATEGORY             => 6300,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::INSURANCE],
            Merchant::CATEGORY2            => Category::INSURANCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::INTERIOR_DESIGN_AND_ARCHITECT => [
            Merchant::CATEGORY             => 8911,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::INTERIOR_DESIGN_AND_ARCHITECT],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::INTERNET_PROVIDER             => [
            Merchant::CATEGORY             => 4816,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::INTERNET_PROVIDER],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::LAB                           => [
            Merchant::CATEGORY             => 8071,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::LAB],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::LEGAL                         => [
            Merchant::CATEGORY             => 8111,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::LEGAL],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::LENDING                       => [
            Merchant::CATEGORY             => 6012,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::LENDING],
            Merchant::CATEGORY2            => Category::LENDING,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::MATCHMAKING                   => [
            Merchant::CATEGORY             => 7273,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::MATCHMAKING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::MESSAGING                     => [
            Merchant::CATEGORY             => 4821,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::MESSAGING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::MOVERS_AND_PACKERS            => [
            Merchant::CATEGORY             => 4214,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::MOVERS_AND_PACKERS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::MULTI_LEVEL_MARKETING         => [
            Merchant::CATEGORY             => 5964,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::MULTI_LEVEL_MARKETING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::BLACKLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::MULTIPLEX                     => [
            Merchant::CATEGORY             => 7832,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::MULTIPLEX],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::MUSIC_STREAMING               => [
            Merchant::CATEGORY             => 5815,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::MUSIC_STREAMING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::MUTUAL_FUND                   => [
            Merchant::CATEGORY             => 6211,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::MUTUAL_FUND],
            Merchant::CATEGORY2            => Category::MUTUAL_FUNDS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::NBFC                          => [
            Merchant::CATEGORY             => 6012,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::NBFC],
            Merchant::CATEGORY2            => Category::LENDING,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::NEIGHBOURHOOD_NETWORK         => [
            Merchant::CATEGORY             => 8699,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::NEIGHBOURHOOD_NETWORK],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::NEWS                          => [
            Merchant::CATEGORY             => 5994,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::NEWS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::OFFICE_SUPPLIES               => [
            Merchant::CATEGORY             => 5111,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::OFFICE_SUPPLIES],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::ONLINE_CASINO                 => [
            Merchant::CATEGORY             => 7801,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ONLINE_CASINO],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::BLACKLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::ONLINE_FOOD_ORDERING          => [
            Merchant::CATEGORY             => 5811,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::ONLINE_FOOD_ORDERING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::OTA                           => [
            Merchant::CATEGORY             => 4722,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::OTA],
            Merchant::CATEGORY2            => Category::TRAVEL_AGENCY,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::PAAS                          => [
            Merchant::CATEGORY             => 5817,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::PAAS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::PENSION_FUND                  => [
            Merchant::CATEGORY             => 6012,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::PENSION_FUND],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::PERSONAL                      => [
            Merchant::CATEGORY             => 8398,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::PERSONAL],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::PROFESSIONAL_COURSES          => [
            Merchant::CATEGORY             => 8299,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::PROFESSIONAL_COURSES],
            Merchant::CATEGORY2            => Category::PVT_EDUCATION,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::PET_PRODUCTS                  => [
            Merchant::CATEGORY             => 5995,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::PET_PRODUCTS],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::PHARMACY                      => [
            Merchant::CATEGORY             => 5912,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::PHARMACY],
            Merchant::CATEGORY2            => Category::PHARMA,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::PROFESSIONAL_NETWORK          => [
            Merchant::CATEGORY             => 8699,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::PROFESSIONAL_NETWORK],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::REALESTATE_CLASSIFIEDS        => [
            Merchant::CATEGORY             => 6513,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::REALESTATE_CLASSIFIEDS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::RELIGIOUS                     => [
            Merchant::CATEGORY             => 8661,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::RELIGIOUS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::RELIGIOUS_PRODUCTS            => [
            Merchant::CATEGORY             => 5973,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::RELIGIOUS_PRODUCTS],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::RENTAL                        => [
            Merchant::CATEGORY             => 7394,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::RENTAL],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::REPAIR_AND_CLEANING           => [
            Merchant::CATEGORY             => 7531,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::REPAIR_AND_CLEANING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::RESTAURANT                    => [
            Merchant::CATEGORY             => 5812,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::RESTAURANT],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::RESTAURANT_SEARCH_AND_BOOKING => [
            Merchant::CATEGORY             => 7299,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::RESTAURANT_SEARCH_AND_BOOKING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::RWA                           => [
            Merchant::CATEGORY             => 7349,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::RWA],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::SAAS                          => [
            Merchant::CATEGORY             => 5817,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::SAAS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::SCHOOLS                       => [
            Merchant::CATEGORY             => 8211,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::SCHOOLS],
            Merchant::CATEGORY2            => Category::PVT_EDUCATION,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::SECURITIES                    => [
            Merchant::CATEGORY             => 6211,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::SECURITIES],
            Merchant::CATEGORY2            => Category::SECURITIES,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::SERVICE_CENTRE                => [
            Merchant::CATEGORY             => 5511,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::SERVICE_CENTRE],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::SERVICES_CLASSIFIEDS          => [
            Merchant::CATEGORY             => 7311,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::SERVICES_CLASSIFIEDS],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::SEXUAL_WELLNESS_PRODUCTS      => [
            Merchant::CATEGORY             => 5999,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::SEXUAL_WELLNESS_PRODUCTS],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::SOCIAL_NETWORK                => [
            Merchant::CATEGORY             => 8641,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::SOCIAL_NETWORK],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::SPACE_RENTAL                  => [
            Merchant::CATEGORY             => 6513,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::SPACE_RENTAL],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::SPORTS_PRODUCTS               => [
            Merchant::CATEGORY             => 5941,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::SPORTS_PRODUCTS],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::STATE                         => [
            Merchant::CATEGORY             => 9399,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::STATE],
            Merchant::CATEGORY2            => Category::GOVERNMENT,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::TECHNICAL_SUPPORT             => [
            Merchant::CATEGORY             => 7379,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::TECHNICAL_SUPPORT],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::BLACKLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::TELECOM                       => [
            Merchant::CATEGORY             => 4814,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::TELECOM],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::TICKETING                     => [
            Merchant::CATEGORY             => 7832,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::TICKETING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::TOBACCO                       => [
            Merchant::CATEGORY             => 5993,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::TOBACCO],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::BLACKLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::TRADING                       => [
            Merchant::CATEGORY             => 6211,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::TRADING],
            Merchant::CATEGORY2            => Category::SECURITIES,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::TRAIN_AND_METRO               => [
            Merchant::CATEGORY             => 4112,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::TRAIN_AND_METRO],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::TRAVEL_AGENCY                 => [
            Merchant::CATEGORY             => 4722,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::TRAVEL_AGENCY],
            Merchant::CATEGORY2            => Category::TRAVEL_AGENCY,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::UNIVERSITY                    => [
            Merchant::CATEGORY             => 8220,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::UNIVERSITY],
            Merchant::CATEGORY2            => Category::PVT_EDUCATION,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::VIDEO_ON_DEMAND               => [
            Merchant::CATEGORY             => 5815,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::VIDEO_ON_DEMAND],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::WATER                         => [
            Merchant::CATEGORY             => 4900,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::WATER],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::WAREHOUSING                   => [
            Merchant::CATEGORY             => 4225,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::WAREHOUSING],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::WHITELIST,
        ],
        Sub::WEAPONS_AND_AMMUNITIONS       => [
            Merchant::CATEGORY             => 5999,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::WEAPONS_AND_AMMUNITIONS],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::BLACKLIST,
            self::EMI_ACTIVATION           => ActivationFlow::BLACKLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::BLACKLIST,
        ],
        Sub::WEB_DEVELOPMENT               => [
            Merchant::CATEGORY             => 7372,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::WEB_DEVELOPMENT],
            Merchant::CATEGORY2            => Category::OTHERS,
            Entity::ACTIVATION_FLOW        => ActivationFlow::GREYLIST,
            self::EMI_ACTIVATION           => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
        Sub::WHOLESALE                     => [
            Merchant::CATEGORY             => 5300,
            self::DESCRIPTION              => Sub::DESCRIPTIONS[Sub::WHOLESALE],
            Merchant::CATEGORY2            => Category::ECOMMERCE,
            Entity::ACTIVATION_FLOW        => ActivationFlow::WHITELIST,
            self::EMI_ACTIVATION           => ActivationFlow::WHITELIST,
            self::INTERNATIONAL_ACTIVATION => ActivationFlow::GREYLIST,
        ],
    ];

    /**
     * returns metadata for others category
     * others business category does not have any subcategory associated with it
     *
     * @return array
     */
    private static function getMetaDataForOthersCategory(): array
    {
        return [
            Merchant::CATEGORY              => 5399,
            Merchant::CATEGORY2             => Category::OTHERS,
            Entity::ACTIVATION_FLOW         => ActivationFlow::GREYLIST,
            self::INTERNATIONAL_ACTIVATION  => ActivationFlow::GREYLIST,
        ];
    }

    /**
     * returns metadata for given category , subcategory
     * throws BadRequestException if metadata is not defined for subcategory
     *
     * @param string      $category
     * @param null|string $subcategory
     *
     * @return array
     * @throws \RZP\Exception\BadRequestException
     */
    public static function getSubCategoryMetaData(string $category, string $subcategory = null): array
    {
        if ($category === BusinessCategory::OTHERS)
        {
            return self::getMetaDataForOthersCategory();
        }

        if (isset(self::SUB_CATEGORY_METADATA[$subcategory]) === true)
        {
            return self::SUB_CATEGORY_METADATA[$subcategory];
        }

        throw new BadRequestException(
            ErrorCode::BAD_REQUEST_INVALID_SUBCATEGORY,
            [Entity::BUSINESS_SUBCATEGORY => $subcategory]);
    }

    /**
     * returns true if category or sub-category can have international enabled
     * used in L1 Activation form
     * @param string $category
     * @param string|null $subcategory
     *
     * @return bool
     */
    public static function isFeatureCategoryOrSubcategoryWhitelisted(
        string $feature,
        string $category,
        string $subCategory = null): bool
    {
        $subCategoryMetaData = self::getSubCategoryMetaData($category, $subCategory);

        if (isset($subCategoryMetaData[$feature]) === true)
        {
            return $subCategoryMetaData[$feature] === ActivationFlow::WHITELIST;
        }

        return false;
    }
}
