<?php

namespace RZP\Models\Merchant\Detail;

class BusinessPickerMetaData
{
    const MCC_DESCRIPTOR_MAP = [
        BusinessSubcategory::LIQUOR_STORES                                      => ["Package Stores, Beer, Wine, Liquor"],
        BusinessSubcategory::ACCESSORY_AND_APPAREL_STORES                       => ["Accessory and Apparel Stores-Miscellaneous"],
        BusinessSubcategory::AGRICULTURE                                        => ["Florists Supplies Nursery Stock and Flowers"],
        BusinessSubcategory::AIRCRAFT_AND_FARM_EQUIPMENT_DEALERS                => ["Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers-not elsewhere classified"],
        BusinessSubcategory::ANTIQUE_SHOPS_SALES_AND_REPAIRS                    => ["Antique Shops-Sales, Repairs, and Restoration Services"],
        BusinessSubcategory::ANTIQUE_STORES                                     => ["Antique Reproduction Stores"],
        BusinessSubcategory::ART_SUPPLY_STORES                                  => ["Artist Supply Stores, Craft Shops"],
        BusinessSubcategory::ARTS_AND_COLLECTIBLES                              => ["Art Dealers and Galleries"],
        BusinessSubcategory::AUTO_STORE_HOME_SUPPLY_STORES                      => ["Auto Store, Home Supply Stores"],
        BusinessSubcategory::AUTOMOBILE_AND_TRUCK_DEALERS                       => ["Automobile and Truck Dealers-Used Only-Sales"],
        BusinessSubcategory::AUTOMOBILE_PARTS_AND_EQUIPEMENTS                   => ["MOTOR VEHICLE SUPPLIES"],
        BusinessSubcategory::AUTOMOTIVE_PAINT_SHOPS                             => ["Automotive Paint Shops"],
        BusinessSubcategory::AUTOMOTIVE_PARTS                                   => ["Automotive Parts, Accessories Stores"],
        BusinessSubcategory::AUTOMOTIVE_TIRE_STORES                             => ["Automotive Tire Stores"],
        BusinessSubcategory::BABY_PRODUCTS                                      => ["Game, Toy, and Hobby Shops"],
        BusinessSubcategory::BICYCLE_STORES                                     => ["Bicycle Shops-Sales and Service"],
        BusinessSubcategory::BOAT_DEALERS                                       => ["Boat Dealers"],
        BusinessSubcategory::BOOKS                                              => ["Book Stores"],
        BusinessSubcategory::BOOKS_PERIODICALS_AND_NEWSPAPER                    => ["Books, Periodicals and Newspapers"],
        BusinessSubcategory::BUILDING_MATRIAL_STORES                            => ["Building Materials, Lumber Stores"],
        BusinessSubcategory::CAMERA_AND_PHOTOGRAPHIC_STORES                     => ["Camera and Photographic Supply Stores"],
        BusinessSubcategory::CAMPER_RECREATIONAL_AND_UTILITY_TRAILER_DEALERS    => ["Camper, Recreational and utility trailer dealers"],
        BusinessSubcategory::CANDY_NUT_CONFECTIONERY_SHOPS                      => ["Candy, Nut, Confectionery Stores"],
        BusinessSubcategory::CHEMICALS_AND_ALLIED_PRODUCTS                      => ["Chemicals and Allied Products"],
        BusinessSubcategory::CLOCKS_AND_SILVERWARE_STORES                       => ["Clock, Jewelry, Watch, and Silverware Store"],
        BusinessSubcategory::COMMERCIAL_EQUIPMENTS                              => ["COMMERCIAL EQUIPMENTS"],
        BusinessSubcategory::COMMERCIAL_PHOTOGRAPHY_AND_GRAPHIC_DESIGN_SERVICES => ["Commercial Art, Graphics, Photography"],
        BusinessSubcategory::COMPUTER_SOFTWARE_STORES                           => ["Computer Software Stores"],
        BusinessSubcategory::COMPUTERS_PERIPHERAL_EQUIPMENT_SOFTWARE            => ["Computers, Computer Peripheral Equipment, Software"],
        BusinessSubcategory::CONSTRUCTION_MATERIALS                             => ["Construction Materials-not elsewhere classified"],
        BusinessSubcategory::COSMETIC_STORES                                    => ["Cosmetic Stores"],
        BusinessSubcategory::COUPONS                                            => ["Advertising Services"],
        BusinessSubcategory::CRYPTO_MACHINERY                                   => ["Miscellaneous and Specialty Retail Stores"],
        BusinessSubcategory::CRYSTAL_AND_GLASSWARE_STORES                       => ["Crystal and Glassware Stores"],
        BusinessSubcategory::DEPARTMENT_STORES                                  => ["Department Stores"],
        BusinessSubcategory::DISCOUNT_STORES                                    => ["Discount stores"],
        BusinessSubcategory::DRAPERY_AND_WINDOW_COVERINGS_STORES                => ["Drapery, Upholstery, and Window Coverings Stores"],
        BusinessSubcategory::DROP_SHIPPING                                      => ["Miscellaneous General Merchandise"],
        BusinessSubcategory::DRY_GOODS                                          => ["Piece Goods, Notions, and Other Dry Goods"],
        BusinessSubcategory::DURABLE_GOODS_STORES                               => ["Durable Goods not elsewhere classified"],
        BusinessSubcategory::DUTY_FREE_STORES                                   => ["Duty Free Stores"],
        BusinessSubcategory::ELECTRICAL_PARTS_AND_EQUIPMENT                     => ["Electrical Parts and Equipment"],
        BusinessSubcategory::ELECTRONICS_AND_FURNITURE                          => ["Electronic Sales"],
        BusinessSubcategory::FABRIC_AND_SEWING_STORES                           => ["Fabric, Needlework, Piece Goods, and Sewing Stores"],
        BusinessSubcategory::FAMILY_CLOTHING_STORES                             => ["Family Clothing Stores"],
        BusinessSubcategory::FASHION_AND_LIFESTYLE                              => ["Mens and Womens Clothing Stores"],
        BusinessSubcategory::FIREPLACE_PARTS_AND_ACCESSORIES                    => ["FIREPLACE FIREPLACE SCREENS AND ACCESSORIES STORES"],
        BusinessSubcategory::FLOOR_COVERING_STORES                              => ["Floor Covering Stores"],
        BusinessSubcategory::FLORISTS                                           => ["Florists"],
        BusinessSubcategory::GIFTING                                            => ["Florists Supplies Nursery Stock and Flowers"],
        BusinessSubcategory::FUEL_DEALERS                                       => ["Fuel Dealers-Coal, Fuel Oil, Liquefied Petroleum, Wood"],
        BusinessSubcategory::FUR_SHOPS                                          => ["Furriers and Fur Shops"],
        BusinessSubcategory::GARDEN_SUPPLY_STORES                               => ["Lawn and Garden Supply Stores"],
        BusinessSubcategory::GIFT_NOVELTY_AND_SOUVENIR_SHOPS                    => ["Card, Gift, Novelty, and Souvenir Shops"],
        BusinessSubcategory::GLASS_AND_WALLPAPER_STORES                         => ["Glass, Paint, Wallpaper Stores"],
        BusinessSubcategory::GROCERY                                            => ["Grocery Stores, Supermarkets"],
        BusinessSubcategory::HARDWARE_EQUIPMENT_AND_SUPPLY_STORES               => ["Hardware Equipement and Supplies"],
        BusinessSubcategory::HEARING_AIDS_STORES                                => ["Hearing Aids-Sales, Service, Supply Stores"],
        BusinessSubcategory::HOME_FURNISHING_STORES                             => ["Miscellaneous House Furnishing Specialty Shops"],
        BusinessSubcategory::HOME_SUPPLY_WAREHOUSE                              => ["Home Supply Warehouse"],
        BusinessSubcategory::HOUSEHOLD_APPLIANCE_STORES                         => ["Household Appliance Stores"],
        BusinessSubcategory::INDUSTRIAL_SUPPLIES                                => ["Industrial Supplies"],
        BusinessSubcategory::JEWELLERY_AND_WATCH_STORES                         => ["Precious Stones and Metals,Watches and Jewelry"],
        BusinessSubcategory::MEAT_SUPPLY_STORES                                 => ["Freezer, Locker Meat Provisioners"],
        BusinessSubcategory::MOTORCYCLE_SHOPS_AND_DEALERS                       => ["Motorcycle Shops and Dealers"],
        BusinessSubcategory::MUSIC_STORES                                       => ["Music Stores-Musical Instruments, Pianos, Sheet Music"],
        BusinessSubcategory::NON_DURABLE_GOODS                                  => ["NONDURABLE GOODS"],
        BusinessSubcategory::OFFICE_AND_COMMERCIAL_FURNITURE                    => ["Office and Commercial Furniture "],
        BusinessSubcategory::OFFICE_EQUIPMENT                                   => ["Office, Photographic, Photocopy, and Microfilm Equipment"],
        BusinessSubcategory::OPTICIANS_OPTICAL_GOODS_AND_EYEGLASSE_STORES       => ["Opticians, Optical Goods, and Eyeglasses"],
        BusinessSubcategory::PAINT_SUPPLY_STORES                                => ["Varnishes, Paints, Supplies"],
        BusinessSubcategory::PAWN_SHOPS                                         => ["Pawn Shops"],
        BusinessSubcategory::PET_PRODUCTS                                       => ["Pet Shops-Pet Food and Supplies"],
        BusinessSubcategory::PETROLEUM_AND_PETROLEUM_PRODUCTS                   => ["Petroleum and Petroleum Products"],
        BusinessSubcategory::PLUMBING_AND_HEATING_EQUIPMENT                     => ["Plumbing and Heating Equipment"],
        BusinessSubcategory::RENTAL                                             => ["Equipment Rental and Leasing Services, Furniture Rental, Too"],
        BusinessSubcategory::RECORD_SHOPS                                       => ["Record Shops"],
        BusinessSubcategory::SECOND_HAND_STORES                                 => ["SECOND HAND STORES-USED MERCHANDISE STORES"],
        BusinessSubcategory::SEXUAL_WELLNESS_PRODUCTS                           => ["Miscellaneous and Specialty Retail Stores"],
        BusinessSubcategory::SHOE_STORES_RETAIL                                 => ["Shoe Stores"],
        BusinessSubcategory::SNOWMOBILE_DEALERS                                 => ["Snowmobile Dealers"],
        BusinessSubcategory::SPORT_APPAREL_STORES                               => ["Sports Apparel, Riding Apparel Stores"],
        BusinessSubcategory::SPORTS_PRODUCTS                                    => ["Sporting Goods Stores"],
        BusinessSubcategory::STAMPS_AND_COINS_STORES                            => ["Stamps & Coins Stores"],
        BusinessSubcategory::TELECOMMUNICATION_EQUIPMENT_STORES                 => ["Telecommunication Equipment Including Telephone Sales"],
        BusinessSubcategory::TENT_STORES                                        => ["Tent and Awning Shops"],
        BusinessSubcategory::TOBACCO                                            => ["CIGAR STORES &amp; STAND"],
        BusinessSubcategory::UNIFORMS_AND_COMMERCIAL_CLOTHING_STORES            => ["Men’s, Women’s, and Children’s Uniforms and Commercial Clothing"],
        BusinessSubcategory::VARIETY_STORES                                     => ["Variety Stores"],
        BusinessSubcategory::VIDEO_GAME_SUPPLY_STORES                           => ["Video Amusement Game Supplies"],
        BusinessSubcategory::WATCH_AND_JEWELLERY_REPAIR_STORES                  => ["Clock, Jewelry, and Watch Repair Shops"],
        BusinessSubcategory::WEAPONS_AND_AMMUNITIONS                            => ["Miscellaneous and Specialty Retail Stores"],
        BusinessSubcategory::WHOLESALE_FOOTWEAR_STORES                          => ["Commercial Footwear"],
        BusinessSubcategory::WIG_AND_TOUPEE_SHOPS                               => ["Wig and Toupee Shops"],
        BusinessSubcategory::WOMEN_CLOTHING                                     => ["Womens Ready to Wear Stores"],
        BusinessSubcategory::COACHING                                           => ["Schools and Educational Services-not elsewhere classified"],
        BusinessSubcategory::COLLEGE                                            => ["Colleges, Universities, Professional Schools, and Junior Colleges"],
        BusinessSubcategory::CORRESPONDENCE_SCHOOLS                             => ["Schools, Correspondence"],
        BusinessSubcategory::DANCE_HALLS_STUDIOS_AND_SCHOOLS                    => ["Dance Halls, Studios and Schools"],
        BusinessSubcategory::DISTANCE_LEARNING                                  => ["Schools and Educational Services-not elsewhere classified"],
        BusinessSubcategory::ELEARNING                                          => ["Schools and Educational Services-not elsewhere classified"],
        BusinessSubcategory::DAY_CARE                                           => ["CHILD CARE SERVICES"],
        BusinessSubcategory::PROFESSIONAL_COURSES                               => ["Schools and Educational Services-not elsewhere classified"],
        BusinessSubcategory::SPORTING_CLUBS                                     => ["ATHLETIC FEES"],
        BusinessSubcategory::UNIVERSITY                                         => ["Colleges, Universities, Professional Schools, and Junior Colleges"],
        BusinessSubcategory::VOCATIONAL_AND_TRADE_SCHOOLS                       => ["SCHOOLS, TRADE AND VOCATIONAL"],
        BusinessSubcategory::ACCOUNTING                                         => ["Accounting, Auditing, and Bookkeeping Services"],
        BusinessSubcategory::ATMS                                               => ["Financial Institutions-Automated Cash Disbursements"],
        BusinessSubcategory::BETTING                                            => ["Internet Gambling"],
        BusinessSubcategory::COMMODITIES                                        => ["Securities-Brokers/Dealers"],
        BusinessSubcategory::COOPERATIVES                                       => ["Financial Institutions-Merchandise and Services"],
        BusinessSubcategory::CRYPTOCURRENCY                                     => ["Non Financial Institutions-Foreign Currency, Money Orders-Not Wire Transfer"],
        BusinessSubcategory::DIGITAL_GOODS                                      => ["Digital Goods-Multi-Category"],
        BusinessSubcategory::FOREX                                              => ["Financial Institutions-Manual Cash Disbursements "],
        BusinessSubcategory::GET_RICH_SCHEMES                                   => ["EMPLOYMENT AGENCIES TEMPORARY HELP SERVICES"],
        BusinessSubcategory::INSURANCE                                          => ["Insurance Sales, Underwriting, and Premiums"],
        BusinessSubcategory::LENDING                                            => ["Financial Institutions-Merchandise and Services"],
        BusinessSubcategory::MONEYSEND_FUNDING                                  => ["MoneySend Funding"],
        BusinessSubcategory::MUTUAL_FUND                                        => ["Securities-Brokers/Dealers"],
        BusinessSubcategory::NBFC                                               => ["Financial Institutions-Merchandise and Services"],
        BusinessSubcategory::PENSION_FUND                                       => ["Financial Institutions-Merchandise and Services"],
        BusinessSubcategory::SECURITIES                                         => ["Securities-Brokers/Dealers"],
        BusinessSubcategory::TRADING                                            => ["Securities-Brokers/Dealers"],
        BusinessSubcategory::TAX_PAYMENTS                                       => ["Tax Payments"],
        BusinessSubcategory::TAX_PREPARATION_SERVICES                           => ["Tax Preparation Service"],
        BusinessSubcategory::WIRE_TRANSFERS_AND_MONEY_ORDERS                    => ["WIRE TRANSFER MONEY ORDER"],
        BusinessSubcategory::ALCOHOL                                            => ["Bars, Cocktail Lounges, Discotheques, Nightclubs, and Taverns-Drinking Places-Alcoholic Beverages"],
        BusinessSubcategory::BAKERIES                                           => ["Bakeries"],
        BusinessSubcategory::DAIRY_PRODUCTS                                     => ["Dairy Products Stores"],
        BusinessSubcategory::ONLINE_FOOD_ORDERING                               => ["Caterers"],
        BusinessSubcategory::RESTAURANT_SEARCH_AND_BOOKING                      => ["Other Services-not elsewhere classified"],
        BusinessSubcategory::RESTAURANT                                         => ["Eating Places, Restaurants"],
        BusinessSubcategory::ESPORTS                                            => ["Digital Goods-Games"],
        BusinessSubcategory::FANTASY_SPORTS                                     => ["Digital Goods-Games"],
        BusinessSubcategory::GAME_DEVELOPER                                     => ["Digital Goods-Games"],
        BusinessSubcategory::GOVERMENT_POSTAL_SERVICES                          => ["Postal Services -Government Only"],
        BusinessSubcategory::INTRA_GOVERNMENT_PURCHASES                         => ["Intra-Government Purchases -Government Only"],
        BusinessSubcategory::CENTRAL                                            => ["Government services not else where classified"],
        BusinessSubcategory::CLINIC                                             => ["Hospitals"],
        BusinessSubcategory::DENTISTS_AND_ORTHODONTISTS                         => ["Dentists, Orthodontists"],
        BusinessSubcategory::DOCTORS                                            => ["Doctors-not elsewhere classified"],
        BusinessSubcategory::DRUG_STORES                                        => ["DRUGS, DRUG PROPRIETARIES"],
        BusinessSubcategory::FITNESS                                            => ["Health and Beauty Spas"],
        BusinessSubcategory::HARDWARE_STORES                                    => ["Hardware Stores"],
        BusinessSubcategory::HEALTH_COACHING                                    => ["Health and Beauty Spas"],
        BusinessSubcategory::HEALTH_PRACTITIONERS_MEDICAL_SERVICES              => ["Health Practitioners, Medical Services-not elsewhere classified"],
        BusinessSubcategory::HEALTH_PRODUCTS                                    => ["Miscellaneous Food Stores-Convenience Stores, Markets, Specialty Stores, and Vending Machines"],
        BusinessSubcategory::HOSPITAL                                           => ["Hospitals"],
        BusinessSubcategory::LAB                                                => ["Dental and Medical Laboratories"],
        BusinessSubcategory::MEDICAL_EQUIPMENT_AND_SUPPLY_STORES                => ["Dental/Laboratory/Medical/Ophthalmic Hospital Equipment and Supplies"],
        BusinessSubcategory::OPHTHALMOLOGISTS                                   => ["Optometrists, Ophthalmologists"],
        BusinessSubcategory::ORTHOPEDIC_GOODS_STORES                            => ["Orthopedic Goods-Artificial Limb Stores"],
        BusinessSubcategory::OSTEOPATHS                                         => ["Osteopaths"],
        BusinessSubcategory::PHARMACY                                           => ["Drug Stores, Pharmacies"],
        BusinessSubcategory::PODIATRISTS_AND_CHIROPODISTS                       => ["Podiatrists and Chiropodists"],
        BusinessSubcategory::TESTING_LABORATORIES                               => ["Testing Laboratories-Non medical"],
        BusinessSubcategory::COWORKING                                          => ["Real Estate Agents and Managers-Rentals"],
        BusinessSubcategory::DEVELOPER                                          => ["Real Estate Agents and Managers-Rentals"],
        BusinessSubcategory::FACILITY_MANAGEMENT                                => ["CLEANING AND MAINTENANCE, JANITORIAL SERVICES"],
        BusinessSubcategory::SPACE_RENTAL                                       => ["Real Estate Agents and Managers-Rentals"],
        BusinessSubcategory::REALESTATE_CLASSIFIEDS                             => ["Real Estate Agents and Managers-Rentals"],
        BusinessSubcategory::RWA                                                => ["CLEANING AND MAINTENANCE, JANITORIAL SERVICES"],
        BusinessSubcategory::CONSULTING_AND_OUTSOURCING                         => ["Consulting, Management, and Public Relations Services"],
        BusinessSubcategory::IAAS                                               => ["Digital Goods-Software Applications (Excluding Games)"],
        BusinessSubcategory::PAAS                                               => ["Digital Goods-Software Applications (Excluding Games)"],
        BusinessSubcategory::TECHNICAL_SUPPORT                                  => ["Computer Maintenance, Repair, and Services-not elsewhere classified"],
        BusinessSubcategory::COURIER_SERVICES                                   => ["Courier Services-Air &amp; Ground, Freight Forwarders"],
        BusinessSubcategory::DISTRIBUTION                                       => ["MOTOR FREIGHT CARRIERS, TRUCKING-LOCAL/LONG DISTANCE, MOVING"],
        BusinessSubcategory::END_TO_END_LOGISTICS                               => ["MOTOR FREIGHT CARRIERS, TRUCKING-LOCAL/LONG DISTANCE, MOVING"],
        BusinessSubcategory::AMUSEMENT_PARKS_AND_CIRCUSES                       => ["Amusement Parks, Carnivals, Circuses, Fortune Tellers"],
        BusinessSubcategory::BILLIARD_AND_POOL_ESTABLISHMENTS                   => ["Billiard and Pool Establishments"],
        BusinessSubcategory::BOWLING_ALLEYS                                     => ["Bowling Alleys"],
        BusinessSubcategory::CONTENT_AND_PUBLISHING                             => ["Miscellaneous Publishing and Printing"],
        BusinessSubcategory::TICKETING                                          => ["Motion Picture Theatres"],
        BusinessSubcategory::MULTIPLEX                                          => ["Motion Picture Theatres"],
        BusinessSubcategory::MUSIC_STREAMING                                    => ["Digital Goods-Audiovisual Media Including Books, Movies, and Music"],
        BusinessSubcategory::NEWS                                               => ["News Dealers and Newsstands"],
        BusinessSubcategory::TICKET_AGENCIES                                    => ["Theatrical Producers-except Motion Pictures, Ticket Agencies"],
        BusinessSubcategory::VIDEO_GAME_ARCADES                                 => ["Video Game Arcades/Establishments"],
        BusinessSubcategory::VIDEO_ON_DEMAND                                    => ["Digital Goods-Audiovisual Media Including Books, Movies, and Music"],
        BusinessSubcategory::VIDEO_TAPE_PRODUCTION_AND_DISTRIBUTION             => ["Motion Pictures and Video Tape Production and Distribution"],
        BusinessSubcategory::CHARITY                                            => ["Organizations, Charitable and Social Service"],
        BusinessSubcategory::EDUCATIONAL                                        => ["Organizations, Charitable and Social Service"],
        BusinessSubcategory::PERSONAL                                           => ["Organizations, Charitable and Social Service"],
        BusinessSubcategory::RELIGIOUS                                          => ["Organizations, Religious"],
        BusinessSubcategory::AD_AND_MARKETING                                   => ["Advertising Services"],
        BusinessSubcategory::AFFLIATED_AUTO_RENTAL                              => ["AFFILIATED AUTO RENTAL"],
        BusinessSubcategory::AGRICULTURAL_COOPERATIVES                          => ["AGRICLUTRAL COPERATIVES"],
        BusinessSubcategory::AIR_CONDITIONING_AND_REFRIGERATION_REPAIR_SHOPS    => ["Air Conditioning and Refrigeration Repair Shops"],
        BusinessSubcategory::AIRPORT_FLYING_FIELDS                              => ["AIRPORT FLYING FIELDS"],
        BusinessSubcategory::ALIMONY_AND_CHILD_SUPPORT                          => ["COURT COST INCLUDING ALIMONY AND CHILD SUPPORT"],
        BusinessSubcategory::AMBULANCE_SERVICES                                 => ["Ambulance Services"],
        BusinessSubcategory::ARCHITECTURAL_SERVICES                             => ["Horticultural and Landscaping Services"],
        BusinessSubcategory::AUTOMOBILE_TOWING_SERVICES                         => ["Towing Services"],
        BusinessSubcategory::AUTOMOTIVE_SERVICE_SHOPS                           => ["Automotive Service Shops"],
        BusinessSubcategory::BANDS_ORCHESTRAS_AND_MISCELLANEOUS_ENTERTAINERS    => ["Bands, Orchestras, and Miscellaneous Entertainers-not elsewhere classified"],
        BusinessSubcategory::BARBER_AND_BEAUTY_SHOPS                            => ["Barber and Beauty Shops"],
        BusinessSubcategory::BOAT_RENTALS                                       => ["Boat Leases and Boat Rentals"],
        BusinessSubcategory::BUSINESS_SERVICES                                  => ["Business Services-not elsewhere classified"],
        BusinessSubcategory::CAR_WASHES                                         => ["CAR WASHES"],
        BusinessSubcategory::CARPENTRY_CONTRACTORS                              => ["Carpentry Contractors"],
        BusinessSubcategory::CARPET_AND_UPHOLSTERY_CLEANING_SERVICES            => ["Carpet and Upholstery Cleaning"],
        BusinessSubcategory::CHIROPRACTORS                                      => ["Chiropractors"],
        BusinessSubcategory::CLEANING_AND_SANITATION_SERVICES                   => ["Specialty Cleaning, Polishing, and Sanitation Preparations"],
        BusinessSubcategory::CLOTHING_RENTAL_STORES                             => ["Clothing Rental-Costumes, Uniforms, and Formal Wear"],
        BusinessSubcategory::CONCRETE_WORK_CONTRACTORS                          => ["CONCRETE WORK CONTRACTORS"],
        BusinessSubcategory::CONSTRUCTION_SERVICES                              => ["GENERAL CONTRACTORS"],
        BusinessSubcategory::CONSULTING                                         => ["Consulting, Management, and Public Relations Services"],
        BusinessSubcategory::CONTRACTORS                                        => ["Contractors, Special Trade-not elsewhere classified"],
        BusinessSubcategory::COPYING_AND_BLUEPRINTING_SERVICES                  => ["Quick Copy, Reproduction, and Blueprinting Services"],
        BusinessSubcategory::CREDIT_REPORTING_AGENCIES                          => ["Consumer Credit Reporting Agencies"],
        BusinessSubcategory::DEBT_MARRIAGE_PERSONAL_COUNSELING_SERVICE          => ["Debt, Marriage, Personal Counseling Service"],
        BusinessSubcategory::DIRECT_MARKETING                                   => ["Direct Marketing Other Direct Marketers not elsewhere classified"],
        BusinessSubcategory::DIRECT_MARKETING_AND_SUBSCRIPTION_MERCHANTS        => ["Direct Marketing-Continuity/Subscription Merchants"],
        BusinessSubcategory::DIRECT_MARKETING_INSURANCE_SERVICES                => ["Direct Marketing-Insurance Services"],
        BusinessSubcategory::DOOR_TO_DOOR_SALES                                 => ["DOOR-TO-DOOR SALES"],
        BusinessSubcategory::DRY_CLEANERS                                       => ["Dry Cleaners"],
        BusinessSubcategory::ELECTRIC_RAZOR_STORES                              => ["Electric Razor Stores-Sales and Service"],
        BusinessSubcategory::ELECTRICAL_CONTRACTORS                             => ["ELECTRICAL CONTRACTORS"],
        BusinessSubcategory::ELECTRONIC_REPAIR_SHOPS                            => ["Electronic Repair Shops"],
        BusinessSubcategory::EVENT_PLANNING                                     => ["Professional Services-not elsewhere classified"],
        BusinessSubcategory::EXTERMINATING_AND_DISINFECTING_SERVICES            => ["Exterminating and Disinfecting Services"],
        BusinessSubcategory::FINES                                              => ["FINES"],
        BusinessSubcategory::FUEL_DISPENSERS                                    => ["Fuel Dispenser, Automated"],
        BusinessSubcategory::FUNERAL_SERVICES_AND_CREMATORIES                   => ["Funeral Services and Crematories"],
        BusinessSubcategory::FURNITURE_REPAIR_AND_REFINISHING                   => ["Furniture-Reupholstery and Repair, Refinishing"],
        BusinessSubcategory::GOLF_COURSES                                       => ["Golf Courses, Public"],
        BusinessSubcategory::HEATING_AND_PLUMBING_CONTRACTORS                   => ["Air Conditioning, Heating, and Plumbing Contractors"],
        BusinessSubcategory::INBOUND_TELEMARKETING_MERCHANTS                    => ["Direct Marketing-Inbound Telemarketing Merchants"],
        BusinessSubcategory::INTERIOR_DESIGN_AND_ARCHITECT                      => ["Architectural, Engineering, and Surveying Services"],
        BusinessSubcategory::INTERNET_SERVICE_PROVIDERS                         => ["Computer Network/Information Services"],
        BusinessSubcategory::LAUNDRY_SERVICES                                   => ["Cleaning, Garment, and Laundry Services", "Laundry Services - Family"],
        BusinessSubcategory::LOTTERY                                            => ["Government Owned Lottery,Government Owned Lottery"],
        BusinessSubcategory::LOTTERY_AND_BETTING                                => ["Betting -including Lottery Tickets, Chips at Gaming Casinos",
                                                                                    "Off-Track Betting and Wagers at Race Tracks"],
        BusinessSubcategory::MASONRY_CONTRACTORS                                => ["Insulation, Masonry, Plastering, Stonework, and Tile Setting Contractors"],
        BusinessSubcategory::MASSAGE_PARLORS                                    => ["Massage Parlors"],
        BusinessSubcategory::METAL_SERVICE_CENTRES                              => ["Metal Service Centers and Offices"],
        BusinessSubcategory::MISCELLANEOUS_REPAIR_SHOPS                         => ["Miscellaneous Repair Shops and Related Services"],
        BusinessSubcategory::MOBILE_HOME_DEALERS                                => ["Mobile Home Dealers"],
        BusinessSubcategory::MOTOR_HOME_RENTALS                                 => ["A MOTOR HOME AND RECREATIONAL"],
        BusinessSubcategory::MOTOR_HOMES_AND_PARTS                              => ["MOTOR HOME DEALERS"],
        BusinessSubcategory::MOVERS_AND_PACKERS                                 => ["MOTOR FREIGHT CARRIERS, TRUCKING-LOCAL/LONG DISTANCE, MOVING"],
        BusinessSubcategory::MULTI_LEVEL_MARKETING                              => ["Direct Marketing-Catalog Merchants"],
        BusinessSubcategory::NURSING_CARE_FACILITIES                            => ["Nursing and Personal Care Facilities"],
        BusinessSubcategory::OUTBOUND_TELEMARKETING_MERCHANTS                   => ["Direct Marketing-Outbound Telemarketing Merchants"],
        BusinessSubcategory::PERSONAL_SHOPPERS_AND_SHOPPING_CLUBS               => ["Buying/Shopping Clubs, Services"],
        BusinessSubcategory::PHOTOGRAPHY_LABS                                   => ["Photo Developing, Photofinishing Laboratories"],
        BusinessSubcategory::PUBLIC_WAREHOUSING                                 => ["Public Warehousing-Farm Products, Refrigerated Goods,"],
        BusinessSubcategory::RECREATION_SERVICES                                => ["Recreation Services-not elsewhere classified"],
        BusinessSubcategory::RECREATIONAL_AND_SPORTING_CAMPS                    => ["Recreational and Sporting Camps"],
        BusinessSubcategory::RECREATIONAL_CAMPS                                 => ["Trailer Parks and Campgrounds"],
        BusinessSubcategory::REPAIR_AND_CLEANING                                => ["AUTOMOTIVE BODY REPAIR SHOP"],
        BusinessSubcategory::ROOFING_AND_METAL_WORK_CONTRACTORS                 => ["Roofing and Siding, Sheet Metal Work Contractors"],
        BusinessSubcategory::SECURITY_AGENCIES                                  => ["Agencies – Security Services"],
        BusinessSubcategory::SERVICE_CENTRE                                     => ["Automobile and Truck Dealers-Sales, Service, Repairs, Parts, and Leasing"],
        BusinessSubcategory::SERVICE_STATIONS                                   => ["Service Stations with or without Ancillary Services"],
        BusinessSubcategory::SERVICES_CLASSIFIEDS                               => ["Advertising Services"],
        BusinessSubcategory::SHOE_REPAIR_SHOPS                                  => ["Hat Cleaning Shops, Shoe Repair Shops, Shoe Shine Parlors"],
        BusinessSubcategory::SMALL_APPLIANCE_REPAIR_SHOPS                       => ["Appliance Repair Shops, Electrical and Small"],
        BusinessSubcategory::STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES      => ["Stenographic and Secretarial Support Services"],
        BusinessSubcategory::SWIMMING_POOLS                                     => ["Swimming Pools-Sales and Supplies"],
        BusinessSubcategory::TAILORS                                            => ["Alterations, Mending, Seamstresses, Tailors"],
        BusinessSubcategory::TELECOMMUNICATION_SERVICE                          => ["Telecom Servc including but not ltd to prepaid phone serv"],
        BusinessSubcategory::TELEVISION_CABLE_SERVICES                          => ["Cable and other Pay Television Services"],
        BusinessSubcategory::TIRE_RETREADING_AND_REPAIR_SHOPS                   => ["Tire Retreading and Repair Shops"],
        BusinessSubcategory::TRANSPORTATION_SERVICES                            => ["Transportation Services-not elsewhere classified"],
        BusinessSubcategory::TRAVEL_RELATED_DIRECT_MARKETING                    => ["Direct Marketing-Travel-Related Arrangement Services"],
        BusinessSubcategory::TYPE_SETTING_AND_ENGRAVING_SERVICES                => ["Typesetting, Plate Making, Related Services"],
        BusinessSubcategory::TYPEWRITER_STORES_SALES_SERVICE_AND_RENTALS        => ["Typewriter Stores-Sales, Service, and Rentals"],
        BusinessSubcategory::VETERINARY_SERVICES                                => ["Veterinary Services"],
        BusinessSubcategory::VIDEO_TAPE_RENTAL_STORES                           => ["Video Tape Rental Stores"],
        BusinessSubcategory::WELDING_REPAIR                                     => ["WELDING REPAIR"],
        BusinessSubcategory::WRECKING_AND_SALVAGING_SERVICES                    => ["Wrecking and Salvage Yards"],
        BusinessSubcategory::AUTOMOBILE_ASSOCIATIONS_AND_CLUBS                  => ["Automobile Associations"],
        BusinessSubcategory::COUNTRY_AND_ATHLETIC_CLUBS                         => ["Clubs-Country Clubs, Membership-Athletic, Recreation, Sports, Private Golf Courses"],
        BusinessSubcategory::MATCHMAKING                                        => ["Dating and Escort Services"],
        BusinessSubcategory::NEIGHBOURHOOD_NETWORK                              => ["Organizations, Membership-not elsewhere classified"],
        BusinessSubcategory::MESSAGING                                          => ["TELEGRAPH SERVICES"],
        BusinessSubcategory::POLITICAL_ORGANIZATIONS                            => ["Political Organizations"],
        BusinessSubcategory::PROFESSIONAL_NETWORK                               => ["Organizations, Membership-not elsewhere classified"],
        BusinessSubcategory::SOCIAL_NETWORK                                     => ["Associations-Civic, Social, and Fraternal"],
        BusinessSubcategory::AQUARIUMS_DOLPHINARIUMS_AND_SEAQUARIUMS            => ["Aquariums, Dolphinariums, and Seaquariums"],
        BusinessSubcategory::AVIATION                                           => ["Air Carriers, Airlines-not elsewhere classified",
                                                                                    "AIR ARABIA AIR ARABIA", "AIR CHINA AIR CHINA",
                                                                                    "AIR FRANCE AIR FRANCE", "AEROFLOT AEROFLOT",
                                                                                    "AIR BERLIN AIR BERLIN", "PAKISTAN INTERNATIONAL",
                                                                                    "AIR ASTANA AIR ASTANA", "AIR AFRIQUE AIR AFRIQUE",
                                                                                    "AIR JAMAICA AIR JAMAICA", "AEROLINEAS NICARAGUENSIS AERONICARAG",
                                                                                    "Qatar Airways", "AIR CANADA AIR CANADA", "ADRIA AIRWAYS ADRIA AIR",
                                                                                    "AEROMEXICO AEROMEXICO", "AERO SERVICO CARABOBO ASC AIRLINE", "AEROPERU AEROPERU",
                                                                                    "British Airways", "AIR ALGERIE AIR ALGERIE", "AEROLINEAS ARGENTINAS AERO ARGENT",
                                                                                    "AIR BRITISH COLUMBIA AIR BC", "AIR DJIBOUTI AIR DJIBOUTI", "SAUDI ARABIAN AIRLINES",
                                                                                    "AEROCONTINENTE AEROCONTINEN", "Japan Airways", "Hapag-Lloyd Express-HLX",
                                                                                    "LOT -Polish Airlines-LOT", "Balkan-Bulgarian Airlines-BALKAN",
                                                                                    "Air Littoral, S.A.-LITTORAL,Air Littoral, S.A.-LITTORAL", "Provincetown-Boston Airways-PBA",
                                                                                    "Air India-AIR-INDI", "Lufthansa-LUFTHAN", "China Airlines-CHINAAIR", "Mesa Air-MESA AIR",
                                                                                    "LIAT-LIAT", "LACSA (Costa Rica)-LACSA", "Island Airlines-ISLANDAI", "Havasu Airlines-HAVASUAI",
                                                                                    "Bahamasair-BAHAMASA", "Kenya Airways-KENYAAIR", "Korean Airlines-KOREAN", "Zambia Airways-ZAMBIA A",
                                                                                    "Asiana Airlines-ASIANA", "Windward Island-WINDWARD", "Venezolana International de Aviacion-VIASA",
                                                                                    "Eurofly-EUROFLY", "South African Airways-SAFRICAN", "SNBrussels Airlines-SNBRU AIR", "LADECO (Chile)-LADECO",
                                                                                    "Jetstar Airways-JETSTAR", "Air Zaire-AIRZAIRE", "AirTran Airways-AIRTRAN A", "Virgin Express-VIR EXP",
                                                                                    "Guyana Airways-GUYANA A", "Malmo Aviation-MALMO AV", "SAHSA (Servicio Aero de Honduras)-SAHSA",
                                                                                    "Austrian Air Service-AUSTRAIR", "EasyJet-EASYJET", "Ryanair-RYANAIR", "Gol Airlines-GOL",
                                                                                    "Tam Airlines-TAM", "Spirit Airlines-SPIRIT", "Cyprus Airways-CYPRUSA", "Ethiopian Airlines-ETHIOPIA",
                                                                                    "Azul Brazilian Airlines-AZUL AIR", "Eva Airways-EVA AIR", "Transaero-TRANSAERO", "Uni Airways-UNIAIR",
                                                                                    "Cathay Pacific-CATHAYPA", "Garuda (Indonesia)-GARUDA", "British Midland-BRITISH M", "Tap (Portugal)-TAP",
                                                                                    "Nigeria Airways-NIGERIA", "Indian Airlines-INDIAN A", "Direct Marketing-Combination Catalog and Retail Merchants",
                                                                                    "Continental-CONTINEN", "Southwest Airlines-SOUTHWES", "Sunworld International Airways-SUNWORLD",
                                                                                    "LAV Linea Aeropostal Venezolana-LAV", "Jugoslav Air-JUGOSLAV", "Hawaiian Air-HAWAIIAN",
                                                                                    "Transportes Aeros Militares Ecuatorianos-TAME AIR", "Alaska Airlines Inc.-ALASKA A", "Air Seychelles-AIR SEYC",
                                                                                    "Air Panama International-AIR PANA", "Varig (Brazil)-VARIG", "Philippine Airlines-PAL AIR", "Ansett Airlines-ANSETT",
                                                                                    "Icelandair-ICELANDA", "LAN Airlines-LAN AIR", "Virgin America-VIR AMER", "Jet Airways-JET AIR", "Air Lanka-AIR LANKA",
                                                                                    "Luxair-LUXAIR", "Nation Air-NATIONAI", "Norwegian Air Shuttle-NORWEGIAN", "Compania Faucett-COMPANIA", "Comair-COMAIR",
                                                                                    "Skyways-SKYWAYS", "Cayman Airways-CAYMANAIR", "Caribbean Airlines-CARIBBEAN", "Bar Harbor Airlines-BARHARBO", "Ecuatoriana-ECUATORI",
                                                                                    "Tan Airlines-TAN AIR", "Olympic Airways-OLYMPICA", "ElAl-EL AL", "Royal Air Maroc-AIRMARO", "Tunis Air-TUNIS AI", "AVIACO (Spain)-AVIACO",
                                                                                    "U.S. Airways-USAIRWYS", "Vanguard Airlines-VANGUARD", "Surinam Airways-SURINAM", "All Nippon Airways-ANAAIR", "JetBlue Airways-JETBLUE",
                                                                                    "Middle East Air-MIDEASTA", "Oman Aviation Services-OMAN AIR", "Tarom Romanian Air Transport-TAROM AIR", "Air Mauritius-AIRMAURI",
                                                                                    "American Airlines-AMERICAN", "Croatia Air-CROATIA", "Iberia-IBERIA", "Scandinavian Airline System (SAS)-SAS", "Mexicana-MEXICANA",
                                                                                    "Union de Transports Aeriens-UTAAIR", "Etihad Airways-ETIHADAIR", "EgyptAir-EGYPTAIR", "Gulf Air (Bahrain)-GULF AIR", "Delta-DELTA",
                                                                                    "Air Inter-AIRINTER", "Cebu Pacific-CEBU PAC", "Singapore Airlines-SINGAPOR", "Virgin Atlantic-VIR ATL", "GOFLY Ltd.-GOFLY",
                                                                                    "Canadian Airlines-CANADIAN", "Westjet Airlines-WESTJET", "Freedom Airlines-FREEDOM", "Dominicana de Aviacion-DOMINICA",
                                                                                    "Wideroes Flyveselskap-WIDEROES", "Metro Airlines-METROAI", "Spanair-SPANAIR", "Braathens S.A.F.E. (Norway)-BRAATHEN", "Alitalia-ALITALIA",
                                                                                    "Air New Zealand Limited International-AIR NZ", "Air Malta-AIRMALTA", "Cruzeiro do Sul (Brazil)-CRUZEIRO", "LAB (Bolivia)-LAB", "DBA Airlines-DBA AIR",
                                                                                    "Malaysian Airline System-MALAY AI", "Sun Country Airlines-SUNCNTRY", "Thai Airways-THAIAIRW", "LAP Lineas Aereas Paraguayas-LAP", "China Eastern Airlines-CHINAEAST",
                                                                                    "SAETA (Sociedad Ecuatorianas De Transportes Aereo)-SAETAAIR", "Avensa-AVENSA", "ALM Antilean Airlines-ALM", "Taca International-TACA INT", "Swiss International Air Lines-SWISS",
                                                                                    "Emirates Airlines-EMIRATES", "Kuwait Airways-KUWAIT", "Avianca-AVIANCA", "Austrian Airlines-AUSTRIAN", "VLM Airlines-VLM", "Frontier Airlines-FRONTIER", "Norontair-NORONTAI",
                                                                                    "Malev Hungarian Airlines-MALEV", "CSA Ceskoslovenske Aerolinie-CSA", "Compania Panamena de Aviacion (Copa)-COPA", "Command Airways-COMMAND", "Aviateca (Guatemala)-AVIATECA",
                                                                                    "America West-AMERWEST", "Midwest Express Airlines-MIDWEST", "Air Zimbabwe-AIRZIMBA", "Dragonair-DRAGONAIR", "Royal Dutch Airlines (KLM)-KLM", "Qantas-QANTAS", "VASP (Brazil)-VASP",
                                                                                    "Finnair-FINNAIR", "THY (Turkey)-THY", "Northwest Airlines-NWA AIR"],
        BusinessSubcategory::ACCOMMODATION                                      => ["Lodging-Hotels, Motels, Resorts-not elsewhere classified",
                                                                                    "Hyatt Hotels", "WelcomGroup Hotels", "HILTON HOTELS",
                                                                                    "Quality Inns", "Swissotel", "Howard Johnson", "Sofitel Hotels",
                                                                                    "DeVera Hotels", "Penta Hotels", "Circus Circus Hotel and Casino",
                                                                                    "Eldorado Hotel and Casino", "Cumulus Hotels", "Bradbury Suites", "Amerisuites",
                                                                                    "Dunfey Hotels", "Kauai Coconut Beach Resort", "Concorde Hotels",
                                                                                    "Manhattan East Suite Hotels", "Cunard Hotels", "Compri Hotels", "Excel Inn",
                                                                                    "Fairfield Hotels", "Motel 6", "Shilo Inn", "Shoney's Inn",
                                                                                    "Virgin River Hotel and Casino", "Protea Hotels", "Club Med", "Biltmore Hotel and Suites",
                                                                                    "Beau Rivage Hotel and Casino", "Bellagio Hotel and Casino", "Sands Resort", "Mandalay Bay Resort",
                                                                                    "WHotels", "Town and Country Resort  Center", "Premier Inn", "Holiday Inn Nickelodeon",
                                                                                    "Caribe Royale", "Grand Sierra Resort", "Canopy Hotels", "WELCOME GROUP", "ECONOLODGES",
                                                                                    "Taj Hotels International", "HILTON INTERNATIONAL", "Days Inns", "Hermitage Hotel",
                                                                                    "Hilton Garden Inn", "Imperial London Hotels", "Scandic Hotels", "IBUSZ Hotels",
                                                                                    "Silver Legacy Hotel and Casino", "Rio Suites", "Red Lion Inns", "Hotel Okura", "Coast Hotel",
                                                                                    "Jolly Hotels", "Journey's End Motels", "Soho Grand Hotel", "Ladbroke Hotels", "Grand Wailea Resort",
                                                                                    "LaQuinta Resort", "Westin Hotels", "Doubletree Hotels", "Omni Hotels", "Arizona Biltmore", "OTANI HOTELS",
                                                                                    "CARLTON HOTELS", "SAS HOTEL", "Drury Inn", "Harley Hotels", "Registry Hotels", "Residence Inn", "Fairfield Inn",
                                                                                    "Southern Sun Hotels", "Harrahs Hotels and Casinos", "Millennium Hotels", "Crowne Plaza Hotels",
                                                                                    "Main Street Hotel and Casino", "Disney Resorts", "Patricia Grand Resort Hotels", "Ohana Hotels of Hawaii",
                                                                                    "Staybridge Suites", "The Atlantic", "Princeville Resort", "Vdara (Vdara Hotel and Spa)", "FOUR SEASONS HOTELS", "Forte Hotels", "RAMADA INNS", "Microtel Inn and Suites", "AmericInn", "PENINSULA HOTELS", "Lady Luck Hotel and Casino", "Hotel Universale", "Sleep Inns", "Husa Hotels", "Red Roof Inns", "Stakis Hotels", "Sahara Hotel and Casino", "Sol Hotels", "Prince Hotels", "Summerfield Suites Hotel", "Iberotel Hotels", "Hotel Sierra", "Auberge des Governeures", "Miyako Hotel", "Frankenmuth Bavarian", "RENAISSANCE HOTELS", "COMFORT INNS", "CITY LODGE HOTELS", "Delta Hotels", "Wynn Las Vegas", "Jurys Doyle Hotel Group", "Gaylord Palms", "Gaylord Texan", "CMON INN", "Economy Inns of America", "Sandman Inn", "Conrad Hotels", "Riviera Hotel and Casino", "Amelia Island Plantation", "Stratosphere Hotel and Casino", "Nemacolin Woodlands", "New York, New York Hotel and Casino", "Smugglers' Notch Resort", "Grand Casino Hotels", "Atlantic City Hilton", "The Diplomat Country Club and Spa", "Element", "The Roosevelt Hotel NY", "Galt House", "Waldorf", "Meridien Hotels", "Holiday Inns", "CLUB CORP/CLUB RESORTS", "Ballys Hotel and Casino", "America's Best Value Inn", "Great Wolf", "Rank Hotels", "Sarova Hotels", "Mount Charlotte Thistle", "Knights Inn", "Adams Mark Hotels", "WOODSIDE HOTELS AND RESORTS", "LaQuinta Inns", "Americana Hotels", "Royal Kona Resort", "AMFAC Hotels", "ANA Hotels", "Treasure Island Hotel and Casino", "Sam's Town Hotel and Casino", "Tribeca Grand Hotel", "INFORMATION RETRIVAL SER", "BEST WESTERN HOTELS", "Doral Hotels", "Riverside Resort and Casino", "Gaylord Opryland", "Marinas, Marine Service, and Supplies", "The Homestead", "Dillon Inn", "Midway Motor Lodge", "Super 8 Motels", "Rica Hotels", "Colorado Belle Edgewater Resort", "Beverly Hills Hotel", "Nevele Grande Resort and Country Club", "Rosen Hotels and Resorts", "Raffles Hotels", "Claridge Casino Hotel", "Wilderness Hotel and Golf Resort", "The Palace Hotel", "Country Inn by Carlson", "Royal Hotels", "Fairmont Hotels", "Hotel Mercure", "Extended Stay Deluxe", "Queens Moat Houses", "Swallow Hotels", "Hoteles El Presidente", "Luxor Hotel and Casino", "Maritim Hotels", "Boca Raton Resort", "Rodeway Inns", "Royal Lahaina Resort", "Ciga Hotels", "Mirage Hotel and Casino", "Barton Creek Resort", "Aladdin Resort and Casino", "Golden Nugget", "Garden Place Hotel", "Venture Inn", "Radisson Hotels", "Princess Hotels International", "Hudson Hotel", "RESO HOTEL", "HOTEL IBIS", "PARK INNS INTERNATIONAL", "Flag Inns (Australia)", "Wyndham", "Masters Economy Inns", "Carefree Resorts", "Canyon Ranch", "Silver Star Hotel and Casino", "Peppermill Hotel Casino", "Settle Inn", "LaCosta Resort", "Hyatt Place", "Jumeirah Essex House", "Aria (Aria Resort and Casino)", "Cosmopolitan of Las Vegas", "Oberoi Hotels", "NOVOTEL HOTELS", "Golden Tulip Hotels", "Showcase Rental Cars", "Binion's Horseshoe Club", "Extended Stay", "Dorint Hotels", "Studio Plus", "Extended Stay America", "Metropole Hotels", "Arcade Hotels", "Monte Carlo Hotel and Casino", "Breakers Resort", "Forum Hotels", "Sandman Hotels", "AER LINGUS AER LINGUS", "Business and Secretarial Schools", "Pannonia Hotels", "TradeWinds Resorts", "Jefferson Hotel", "Fontainebleau Resort", "Moevenpick Hotels", "Photographic Studios", "Clarion Hotels", "Consort Hotels", "LaMansion Del Rio", "Royce Hotels", "Quality Pacific Hotel", "Four Seasons (Australia) Hotels", "Sea Pines Resort", "Broadmoor Hotel", "St. Regis Hotel", "Peabody Hotels", "Orchid at Mauna Lani", "Whiskey Pete's Hotel and Casino", "Outrigger Hotels", "The Flamingo Hotels", "Hale Koa Hotel", "The Wigwam Golf Resort and Spa", "LXR (Luxury Resorts)", "Affinia", "Autograph", "TRAVELODGE", "Religious Goods Stores", "RITZ CARLTON THE", "Friendship Inns", "COURTYARD INNS", "Merlin Hotel Group", "Hoteis Othan", "Excalibur Hotel and Casino", "Dan Hotels", "The Phoenician", "Steigenberger Hotels", "Loews Hotels", "Hampton Inn Hotels", "Campanile Hotels", "Rantasipi Hotels", "Climat de France Hotels", "Budget Hosts Inns", "Pullman International Hotels", "CP(Canadian Pacific) Hotels", "REGAL 8 INNS", "California Hotel and Casino", "Sokos Hotel", "Doral Golf Resort", "Sonesta Hotels", "Embassy Suites", "Buffalo Bill's Hotel and Casino", "Karos Hotels", "Opryland Hotel", "Harvey Bristol Hotels", "TownePlace Suites", "Halekulani Hotel/Waikiki Parc", "Primadonna Hotel and Casino", "Chateau Elan Winery and Resort", "SpringHill Suites", "Caesars Hotel and Casino", "First Hospitality Hotels", "Embassy Vacation Resort", "Hotel Indigo", "Home2 Suites by Hilton", "Oxford Suites", "Curio Hotels", "MARRIOTT HOTELS", "REGENT INTERNATIONAL HOTELS", "Arabella Hotels", "aloft (aloft hotels)", "Embassy Hotels", "Sara Hotels", "Flag Inns", "Arctia Hotels", "Interhotel CEDOK", "Budgetel Inns", "Tokyo Hotel", "Downtowner Passport", "Southern Pacific Hotel", "Hotels Melia", "Pinehurst Resort", "Candlewood Suites", "Relax Inns", "Vagabond Hotels", "Mandarin Oriental Hotels", "Hotel Del Coronado", "AERO COACH AVIATION AEROCOACH AV", "Bail and Bond Payments", "HOSPITALITY INTERNATIONAL", "Hungar Hotels", "Helmsley Hotels", "Noah's Hotel", "Susse Chalet", "Inter Nor Hotels", "John Ascuagas Nugget", "MGM Grand Hotel", "Tropicana Resort and Casino", "Eliot Hotels", "Wellesley Inns", "Homewood Suites", "Greenbriar Resorts", "Kahala Mandarin Oriental Hotel", "Fremont Hotel and Casino", "Venetian Resort Hotel and Casino", "Four Points Hotels", "Caribe Royale Resort Suites", "Ala Moana Hotel", "Paris Las Vegas Hotel", "Homestead Suites", "MainStay Suites", "Park Plaza Hotel", "Saddlebrook Resort-Tampa", "INTER-CONTINENTAL HOTELS", "Shangri-La International"],
        BusinessSubcategory::OTA                                                => ["Travel Agencies and Tour Operators"],
        BusinessSubcategory::TIMESHARES                                         => ["Timeshares"],
        BusinessSubcategory::TOURIST_ATTRACTIONS_AND_EXHIBITS                   => ["Tourist Attractions and Exhibits"],
        BusinessSubcategory::TRAVEL_AGENCY                                      => ["Travel Agencies and Tour Operators"],
        BusinessSubcategory::AUTOMOBILE_RENTALS                                 => ["Automobile Rental Agency-not elsewhere classified", "National Car Rental", "ANSA International", "Action Auto Rental", "SIXT Car Rental", "Snappy Car Rental", "HOLIDAY RENT A CAR", "Europe By Car", "Auto Host Car Rental", "A BUDGET RENT A CAR", "THRIFTY CAR RENTAL", "Hertz", "Payless Car Rental", "Rent A Wreck", "Europcar", "Triangle Rent A Car", "AUTOMATE RENT A CAR", "American International", "Altra Auto Rental", "Avis Rent-A-Car", "Reserve Rent-A-Car", "USA Rent-A-Car", "General Rent-A-Car", "Allstate Rent-A-Car", "Insurance Rent-A-Car", "Value Rent-A-Car", "Milleville Rent-A-Car", "Kemwell Group Rent-A-Car", "A1Rent-A-Car", "Automate Rent-A-Car", "Autohansa Rent-A-Car", "Interent Rent-A-Car", "Budget Rent-A-Car", "Tropical Rent-A-Car", "Avcar Rent-A-Car", "Carey Rent-A-Car", "Advantage Rent-A-Car", "Accent Rent-A-Car", "Merchants Rent-A-Car", "Dollar Rent-A-Car", "Econo Car Rent-A-Car", "Airways Rent-A-Car", "Alamo Rent-A-Car", "Tilden Rent-A-Car", "Enterprise Rent-A-Car", "Ugly Duckling Rent-A-Car", "Brooks Rent-A-Car", "Avon Rent-A-Car", "Major Rent-A-Car", "Replacement Rent-A-Car", "Ajax Rent-A-Car"],
        BusinessSubcategory::FREIGHT_TRANSPORT                                  => ["Railroads and Freight"],
        BusinessSubcategory::BRIDGE_AND_ROAD_TOLLS                              => ["BRIDGE &amp; ROAD FEES, TOLLS"],
        BusinessSubcategory::BUS                                                => ["Bus Lines"],
        BusinessSubcategory::CAB_HAILING                                        => ["Limousines and Taxicabs"],
        BusinessSubcategory::CRUISE_LINES                                       => ["CRUISE LINES"],
        BusinessSubcategory::PARKING_LOTS_AND_GARAGES                           => ["Automobile Parking Lots and Garages"],
        BusinessSubcategory::TRANSPORTATION                                     => ["Transportation—Suburban and Local Commuter Passenger, including Ferries"],
        BusinessSubcategory::TRUCK_AND_UTILITY_TRAILER_RENTALS                  => ["Truck and Utility Trailer Rentals"],
        BusinessSubcategory::BILL_AND_RECHARGE_AGGREGATORS                      => ["Calls Through Use of Magnetic Stripe–Reading Telephones"],
        BusinessSubcategory::ELECTRICITY                                        => ["Utilities-Electric, Gas, Sanitary, Water"],
        BusinessSubcategory::GAS                                                => ["Utilities-Electric, Gas, Sanitary, Water"],
        BusinessSubcategory::TELECOM                                            => ["Calls Through Use of Magnetic Stripe–Reading Telephones"],
        BusinessSubcategory::WATER                                              => ["Utilities-Electric, Gas, Sanitary, Water"],
    ];
}
