<?php

namespace RZP\Gateway\Upi\Yesbank;

class ResponseCodes
{
    const CODES = [
        'MT01' => 'Debit Transaction Failed',
        'MT02' => 'Credit Transaction Failed',
        'MT03' => 'Insufficient Balance in Account',
        'MT04' => 'Transaction Limit Exceeded',
        'MT05' => 'Transaction Amount Exceeded',
        'MT06' => 'Closed Account',
        'MT07' => 'Inactive/Dormant account (Remitter)',
        'MT08' => 'Invalid UPI PIN entered',
        'MT09' => 'Inactive/Dormant account (Beneficiary)',
        'MT10' => 'No Credit Account',
        'MT11' => 'Credit decline reversal',
        'MT12' => 'Partial Decline',
        'MT13' => 'Invalid amount (Remitter)',
        'MT14' => 'Incorrect/Invalid Payer Virtual Address',
        'MT15' => 'Incorrect/Invalid Payee Virtual Address',
        'MT16' => 'Collect rejected successfully',
        'MT17' => 'Number of PIN tries exceeded.',
        'MT18' => 'Account does not exist (Remitter)',
        'MT19' => 'Account does not exist (Beneficiary)',
        'MT20' => 'Account not whitelisted',
        'MT21' => 'Cutoff is in process(Remitter)',
        'MT22' => 'Cutoff is in process(Beneficiary)',
        'MT23' => 'Remitter CBS offline',
        'MT24' => 'Beneficiary CBS offline',
        'MT25' => 'Invalid transaction (Remitter)',
        'MT26' => 'Invalid transaction (Beneficiary)',
        'MT27' => 'Transaction not permitted to account',
        'MT28' => 'Requested function not supported (Remitter)',
        'MT29' => 'Requested function not supported (Beneficiary)',
        'MT30' => 'Beneficiary account blocked / Frozen',
        'MT31' => 'Remitter account blocked / Frozen',

        // below error codes are Applicable for Transaction Status Enquiry and Callback API
        'Z9' => 'INSUFFICIENT FUNDS IN CUSTOMER (REMITTER) ACCOUNT',
        'RM' => 'Invalid UPI PIN (Violation of policies while setting/changing UPI PIN )',
        'RN' => 'Registration is temporary blocked due to maximum no of attempts exceeded',
        'RZ' => 'Account is already registered with MBEBA flag as \'Y\'',
        'BR' => 'Mobile number registered with multiple customer IDs',
        'B2' => 'Account linked with multiple names',
        'SP' => 'Invalid/Incorrect ATM PIN',
        'AJ' => 'Customer has never created/activated an ATM PIN',
        'K1' => 'SUSPECTED FRAUD, DECLINE / TRANSACTIONS DECLINED BASED ON RISK SCORE BY REMITTER',
        'ZI' => 'SUSPECTED FRAUD, DECLINE / TRANSACTIONS DECLINED BASED ON RISK SCORE BY BENEFICIARY',
        'Z8' => 'PER TRANSACTION LIMIT EXCEEDED AS SET BY REMITTING MEMBER',
        'Z7' => 'TRANSACTION FREQUENCY LIMIT EXCEEDED AS SET BY REMITTING MEMBER',
        'Z6' => 'NUMBER OF PIN TRIES EXCEED',
        'ZM' => 'INVALID UPI PIN',
        'ZD' => 'VALIDATION ERROR',
        'ZR' => 'INVALID / INCORRECT OTP',
        'ZS' => 'OTP EXPIRED',
        'ZT' => 'OTP TRANSACTION LIMIT EXCEEDED',
        'ZX' => 'INACTIVE OR DORMANT ACCOUNT (REMITTER)',
        'XD' => 'INVALID AMOUNT (REMITTER)',
        'XF' => 'FORMAT ERROR (INVALID FORMAT) (REMITTER)',
        'XH' => 'ACCOUNT DOES NOT EXIST (REMITTER)',
        'XJ' => 'REQUESTED FUNCTION NOT SUPPORTED',
        'XL' => 'EXPIRED CARD, DECLINE (REMITTER)',
        'XN' => 'NO CARD RECORD (REMITTER)',
        'XP' => 'TRANSACTION NOT PERMITTED TO CARDHOLDER (REMITTER)',
        'XR' => 'RESTRICTED CARD, DECLINE (REMITTER)',
        'XT' => 'CUT-OFF IS IN PROCESS (REMITTER)',
        'XV' => 'TRANSACTION CANNOT BE COMPLETED. COMPLIANCE VIOLATION(REMITTER)',
        'XY' => 'REMITTER CBS OFFLINE',
        'YA' => 'LOST OR STOLEN CARD (REMITTER)',
        'YC' => 'DO NOT HONOUR (REMITTER)',
        'YE' => 'REMITTING ACCOUNT BLOCKED/FROZEN',
        'Z5' => 'INVALID BENEFICIARY CREDENTIALS',
        'ZP' => 'BANKS AS BENEFICIARY NOT LIVE ON PARTICULAR TXN TYPE',
        'ZY' => 'INACTIVE OR DORMANT ACCOUNT (BENEFICIARY)',
        'XE' => 'INVALID AMOUNT (BENEFICIARY)',
        'XG' => 'FORMAT ERROR (INVALID FORMAT) (BENEFICIARY)',
        'XI' => 'ACCOUNT DOES NOT EXIST (BENEFICIARY)',
        'XK' => 'REQUESTED FUNCTION NOT SUPPORTED',
        'XM' => 'EXPIRED CARD, DECLINE (BENEFICIARY)',
        'XO' => 'NO CARD RECORD (BENEFICIARY)',
        'XQ' => 'TRANSACTION NOT PERMITTED TO CARDHOLDER (BENEFICIARY)',
        'XS' => 'RESTRICTED CARD, DECLINE (BENEFICIARY)',
        'XU' => 'CUT-OFF IS IN PROCESS (BENEFICIARY)',
        'XW' => 'TRANSACTION CANNOT BE COMPLETED. COMPLIANCE VIOLATION(BENEFICIARY)',
        'Y1' => 'BENEFICIARY CBS OFFLINE',
        'YB' => 'LOST OR STOLEN CARD (BENEFICIARY)',
        'YD' => 'DO NOT HONOUR (BENEFICIARY)',
        'YF' => 'BENEFICIARY ACCOUNT BLOCKED/FROZEN',
        'X6' => 'INVALID MERCHANT (ACQURIER)',
        'X7' => 'MERCHANT not reachable (ACQURIER)',
        'XB' => 'INVALID TRANSACTION OR IF MEMBER IS NOT ABLE TO FIND ANY APROPRIATE RESPONSE CODE (REMITTER)',
        'XC' => 'INVALID TRANSACTION OR IF MEMBER IS NOT ABLE TO FIND ANY ',
        'AM' => 'UPI PIN not set by customer',
        'B1' => 'Registered Mobile number linked to the account has been changed/removed',
        'B3' => 'Transaction not permitted to the account',
        '0'  => 'APPROVED OR COMPLETED SUCCESSFULLY',
        'ZA' => 'TRANSACTION DECLINED BY CUSTOMER',
        'ZH' => 'INVALID VIRTUAL ADDRESS',
        'UX' => 'EXPIRED VIRTUAL ADDRESS',
        'ZG' => 'VPA RESTRICTED BY CUSTOMER',
        'ZE' => 'TRANSACTION NOT PERMITTED TO VPA by the PSP',
        'ZB' => 'INVALID MERCHANT (PAYEE PSP)',
        'YG' => 'MERCHANT ERROR (PAYEE PSP)',
        'X1' => 'RESPONSE NOT RECEIVED WITHIN TAT AS SET BY PAYEE',
        'UT' => 'REMITTER/ISSUER UNAVAILABLE (TIMEOUT)',
        'BT' => 'ACQUIRER/BENEFICIARY UNAVAILABLE(TIMEOUT)',
        'RB' => 'CREDIT REVERSAL TIMEOUT(REVERSAL)',
        'RP' => 'PARTIAL DEBIT REVERSAL TIMEOUT',
        '32' => 'PARTIAL REVERSAL',
        '21' => 'NO ACTION TAKEN (FULL REVERSAL)',
        'U01' => 'The request is duplicate',
        'U02' => 'Amount CAP is exceeded',
        'U03' => 'Net debit CAP is exceeded',
        'U04' => 'Request is not found',
        'U05' => 'Formation is not proper',
        'U06' => 'Transaction ID is mismatched',
        'U07' => 'Validation error',
        'U08' => 'System exception',
        'U09' => 'ReqAuth Time out for PAY',
        'U10' => 'Illegal operation',
        'U11' => 'Credentials is not present',
        'U12' => 'Amount or currency mismatch',
        'U13' => 'External error',
        'U14' => 'Encryption error',
        'U15' => 'Checksum failed',
        'U16' => 'Risk threshold exceeded',
        'U17' => 'PSP is not registered',
        'U18' => 'Request authorization acknowledgement is not received',
        'U19' => 'Request authorization is declined',
        'U20' => 'Request authorization timeout',
        'U21' => 'Request authorization is not found',
        'U22' => 'CM request is declined',
        'U23' => 'CM request timeout',
        'U24' => 'CM request acknowledgement is not received',
        'U25' => 'CM URL is not found',
        'U26' => 'PSP request credit pay acknowledgement is not received',
        'U27' => 'No response from PSP',
        'U28' => 'PSP not available',
        'U29' => 'Address resolution is failed',
        'U30' => 'Debit has been failed',
        'U31' => 'Credit has been failed',
        'U32' => 'Credit revert has been failed',
        'U33' => 'Debit revert has been failed',
        'U34' => 'Reverted',
        'U35' => 'Response is already been received',
        'U36' => 'Request is already been sent',
        'U37' => 'Reversal has been sent',
        'U38' => 'Response is already been sent',
        'U39' => 'Transaction is already been failed',
        'U40' => 'IMPS processing failed in UPI',
        'U41' => 'IMPS is signed off',
        'U42' => 'IMPS transaction is already been processed',
        'U43' => 'IMPS is declined',
        'U44' => 'Form has been signed off',
        'U45' => 'Form processing has been failed in UPI',
        'U46' => 'Request credit is not found',
        'U47' => 'Request debit is not found',
        'U48' => 'Transaction id not present',
        'U49' => 'Request message id is not present',
        'U50' => 'IFSC is not present',
        'U51' => 'Request refund is not found',
        'U52' => 'PSP orgId not found',
        'U53' => 'PSP Request Pay Debit Acknowledgement not received',
        'U54' => 'Transaction Id or Amount in credential block does not match with that in ReqPay',
        'U66' => 'Device Fingerprint mismatch',
        'U67' => 'Debit Time Out',
        'U68' => 'Credit Time Out',
        'U69' => 'Collect Expired',
        'U70' => 'Received Late Response',
        'U77' => 'Merchant blocked',
        'U78' => 'Beneficiary bank offline',
        'OC'  => 'Original Credit Not Found',
        'OD'  => 'Original Debit Not Found',
        'NC'  => 'Credit Not Done',
        'ND'  => 'Debit Not Done',
        'DT'  => 'Duplicate reference received',


        'EXT_RSP9001' => 'Account does not exist.',
        'EXT_RSP9002' => 'Account Closed.',
        'EXT_RSP9003' => 'Account Blocked.',
        'EXT_RSP9004' => 'No debits allowed on Account.',
        'EXT_RSP9005' => 'No credits allowed on Account.',
        'EXT_RSP9006' => 'Account Closed Today.',
        'EXT_RSP9007' => 'Account is Dormant.',
        'EXT_RSP9010' => 'Account details have been changed since last request. Please reinitiate',
        'EXT_RSP9011' => 'There is a memo present on the Debit account.',
        'EXT_RSP9018' => 'Hold Funds Present - Refer to Drawer ( Account would Overdraw )',
        'EXT_RSP9029' => 'Internal OLTP Error.',
        'EXT_RSP9031' => 'Insufficient funds in the debit account.',
        'EXT_RSP9035' => 'There is a memo present on the Credit account.',
        'EXT_RSP9037' => 'Transaction Amt is exceeding the limit Amt. Account is going to Overline.',
        'EXT_RSP9039' => 'All Installments have been paid for the account/Value date beyond maturity date',
        'EXT_RSP9042' => 'Hold Funds Present - Account is going to Overline.',
        'EXT_RSP9045' => 'Transaction Amt is exceeding the limit Amt. Account is going to Overline.',
        'EXT_RSP9086' => 'Insufficient Balance.',
        'EXT_RSP9088' => 'Account has Credit Override status.',
        '7'           => 'No record in Endpoint Calender',
        '10'          => 'No Status Change Of Customer',
        '11'          => 'Invalid Account No',
        '18'          => 'Invalid destination bank',
        '92'          => 'Invalid LO code',
        '1001'        => 'Error {0} {1} {2}',
        '1206'        => 'Fatal Error has occurred.Please Exit and Contact System Administrator {0} {1} {2}',
        '1210'        => 'Database Error : {0} {1} {2}',
        '1282'        => 'Duplicate {0} {1}',
        '2075'        => 'A database error occurred during the execution of a stored procedure',
        '2435'        => 'Invalid Input {0} {1} {2}.',
        '2988'        => 'Invalid Account Status',
        '3934'        => 'Debit and Credit accounts cannot be same',
        '3403'        => 'Called function has had a Fatal Error {1} {2}',
        '3573'        => 'Invalid input {0} {1} {2}',
        '2778'        => 'Account not found',
        '2853'        => 'Account not found {1} {2}',
        '3611'        => 'Invalid transaction',
        '3769'        => 'Invalid Account Number',
        '3915'        => 'Non-existent reference transaction number',
        '4388'        => 'No Rows Found',
        '4470'        => 'Batch number not found',
        '5281'        => 'Invalid Product Type',
        '8024'        => 'card number in use',
        '8037'        => 'Account is linked to Aadhar no, cannot close the account.',
        '8080'        => 'Mandate has Expired',
        '8086'        => 'Cutoff start time not in range defined',
        '8087'        => 'Could not save payment data',
        '8088'        => 'Float details could not be resolved.',
        '9007'        => 'Disbursement date cannot be less than CASA a/c opening date..',
        '9008'        => 'Limit attached to the account is frozen.Cannot Modify Account Status.',
        '9015'        => 'Value date should be greater than process date',
        '9030'        => 'Maximum limit of Date Fields is over',
        '9093'        => 'FROM and TO account products are marked for IB transfer block.',
        '80002'       => 'Error {0} cannot be null or blank',
        '80004'       => 'Error {0} Invalid field length.',
        '80016'       => 'Transaction found with this  external reference number {0}',
        '90152'       => 'Invalid FromAccountID',
        '90185'       => 'Transaction Amount is invalid.',
        '90290'       => 'Funds Transfer Not Allowed from NRE product.',
        '90296'       => 'To Account Number is Invalid',
        '90188'       => 'Voucher entry not allowed for this GL account.',

        // razorpay custom error codes for transfer request
        'RZP_DUPLICATE_PAYOUT'              => 'RZP: A payout with given reference Id already exists',
        'RZP_FTA_REQUEST_INVALID'           => 'RZP: payout fta request is invalid',
        'RZP_REQUEST_ENCRYPTION_FAILURE'    => 'RZP: request encryption failure',
        'RZP_PAYOUT_TIMED_OUT'              => 'RZP: payout request timed out',
        'RZP_PAYOUT_REQUEST_FAILURE'        => 'RZP: payout request failed',
        'RZP_REQUEST_DECRYPTION_FAILED'     => 'RZP: response decryption failed',
        'RZP_PAYOUT_UNKNOWN_ERROR'          => 'RZP: fatal error, please contact gateway',

        // razorpay custom error codes for verify request
        'RZP_REF_ID_MISMATCH'               => 'RZP: Validation error, ref id mismatch',
        'RZP_AMOUNT_MISMATCH'               => 'RZP: amount mismatch',
        'RZP_PAYOUT_VERIFY_TIMED_OUT'       => 'RZP: verify payout timed out',
        'RZP_PAYOUT_VERIFY_REQUEST_FAILURE' => 'RZP: verify payout request failed',

    ];

    public static function getResponseMessage(
        $responseCode,
        $errorCode = null,
        $responseErrorCode = null,
        $desc = null)
    {
        return self::CODES[$responseCode] ??
               self::CODES[$errorCode] ??
               self::CODES[$responseErrorCode] ??
               $desc ??
               'Unknown Gateway Response Code';
    }
}
