const LS_LABELS = {
  NOT_INTERESTED: 'NOT_INTERESTED',
  IMPRESSION_COUNT: 'IMPRESSION_COUNT',
  LAST_IMPRESSION_WITHIN_INTERVAL: 'LAST_IMPRESSION_WITHIN_INTERVAL',
};

/** Time interval wihtin which the asset should'nt be shown */
const IMPRESSION_TIME_INTERVAL = 24 * 60 * 60 * 1000;

export { LS_LABELS, IMPRESSION_TIME_INTERVAL };
