<?php

namespace App\Trace;

use EE\Exception\InvalidArgumentException;

class TraceCode
{
    const AWS_INSTANCE_DATA_RECORD_FAILURE          = 'AWS_INSTANCE_DATA_RECORD_FAILURE';
    const AWS_INSTANCE_DATA_WRITE_FAILURE           = 'AWS_INSTANCE_DATA_WRITE_FAILURE';
    const AWS_INSTANCE_DATA_READ_FAILURE            = 'AWS_INSTANCE_DATA_READ_FAILURE';
    const USER_CONTEXT_LOG                          = 'USER_CONTEXT_LOG';
    const GET_SPLITZ_EXPERIMENTS_ROUTE_INFO_V2   = 'GET_SPLITZ_EXPERIMENTS_ROUTE_INFO_V2';
    const GET_USER_ID_FAILED                        = 'GET_USER_ID_FAILED';
    const SAML_LOGIN                                = 'SAML_LOGIN';
    const SAML_LOGIN_EXCEPTION                      = 'SAML_LOGIN_EXCEPTION';
    const SAML_CALLBACK                             = 'SAML_CALLBACK';

    const DASHBOARD_INTEGRATION_ERROR               = 'DASHBOARD_INTEGRATION_ERROR';
    const QUEUE_JOB_FAILURE                         = 'QUEUE_JOB_FAILURE';
    const USER_REGISTER_LOGIN_ATTEMPT               = 'USER_REGISTER_LOGIN_ATTEMPT';
    const ERROR_EXCEPTION                           = 'ERROR_EXCEPTION';
    const MISC_TRACE_CODE                           = 'MISC_TRACE_CODE';
    const EZETAP_VOID_ACTION                        = 'EZETAP_VOID_ACTION';
    const EZETAP_SET_APP_KEY                        = 'EZETAP_SET_APP_KEY';
    const EZETAP_API_RESPONSE                       = 'EZETAP_API_RESPONSE';
    const EZETAP_REFUND_ACTION                      = 'EZETAP_REFUND_ACTION';
    const EZETAP_RECEIPT_CALL                       = 'EZETAP_RECEIPT_CALL';
    const EZETAP_FETCH_APP_KEY                      = 'EZETAP_FETCH_APP_KEY';
    const SLACK_QUERY_RESPONSE                      = 'SLACK_QUERY_RESPONSE';
    const USER_REGISTER_OAUTH_PROVIDER_ERROR        = 'USER_REGISTER_OAUTH_PROVIDER_ERROR';
    const CAPTCHA_DISABLE_INVALID_PAYLOAD_ERROR     = 'CAPTCHA_DISABLE_INVALID_PAYLOAD_ERROR';
    const USER_LOGIN_OAUTH_PROVIDER_ERROR           = 'USER_LOGIN_OAUTH_PROVIDER_ERROR';
    const INVALID_EMAIL_CANNOT_MASK                 = 'INVALID_EMAIL_CANNOT_MASK';
    const MAILGUN_GET_EMAIL_LOGS                    = 'MAILGUN_GET_EMAIL_LOGS';

    const ADMIN_ACTION_SLACK_LOG                    = 'ADMIN_ACTION_SLACK_LOG';
    const SLACK_QUERY_LOG                           = 'SLACK_QUERY_LOG';
    const SLACK_DATA_EXPORT_LOG                     = 'SLACK_DATA_EXPORT_LOG';

    // Request made to API has failed
    const API_REQUEST_FAILURE                       = 'API_REQUEST_FAILURE';
    const API_CONNECTION_EXCEPTION                  = 'API_CONNECTION_EXCEPTION';
    const API_GUZZLE_EXCEPTION                      = 'API_GUZZLE_EXCEPTION';
    const API_CLIENT_EXCEPTION                      = 'API_CLIENT_EXCEPTION';
    const API_SERVER_EXCEPTION                      = 'API_SERVER_EXCEPTION';
    const API_RZP_EXCEPTION                         = 'API_RZP_EXCEPTION';


    const API_SLOW_RESPONSE_CALL                    = 'API_SLOW_RESPONSE_CALL';
    const REFINED_URL_REQUEST                       = 'REFINED_URL_REQUEST';
    const API_RESPONSE_METRIC                       = 'API_RESPONSE_METRIC';
    const API_ERROR_RESPONSE                        = 'API_ERROR_RESPONSE';
    const API_HEALTH_STATUS_CHECK_FAIL              = 'API_HEALTH_STATUS_CHECK_FAIL';

    const REDIS_CONNECTION_ERROR                    = 'REDIS_CONNECTION_ERROR';

    const API_GRACEFUL_SHUTDOWN_HAPPENING           = 'API_GRACEFUL_SHUTDOWN_HAPPENING';
    const ADMIN_LOGIN_DEBUG                         = 'ADMIN_LOGIN_DEBUG';
    const ADMIN_ROUTE_DEBUG                         = 'ADMIN_ROUTE_DEBUG';

    const USER_LOGIN                                = 'USER_LOGIN';
    const USER_LOGIN_DURATION                       = 'USER_LOGIN_DURATION';
    const SEND_LOGIN_OTP_DURATION                   = 'SEND_LOGIN_OTP_DURATION';
    const SEND_USER_VERIFY_OTP_DURATION             = 'SEND_USER_VERIFY_OTP_DURATION';
    const VERIFY_LOGIN_OTP_DURATION                 = 'VERIFY_LOGIN_OTP_DURATION';
    const VERIFY_VERIFICATION_OTP_DURATION          = 'VERIFY_VERIFICATION_OTP_DURATION';
    const LOGIN_ATTEMPT_ON_SIGNUP_FAILED            = 'LOGIN_ATTEMPT_ON_SIGNUP_FAILED';
    const SEND_LOGIN_OTP_TRIGGERED                  = 'SEND_LOGIN_OTP_TRIGGERED';
    const VERIFY_LOGIN_OTP_TRIGGERED                = 'VERIFY_LOGIN_OTP_TRIGGERED';
    const SEND_LOGIN_OTP_FAILED                     = 'SEND_LOGIN_OTP_FAILED';
    const SEND_LOGIN_OTP_SUCCESS                    = 'SEND_LOGIN_OTP_SUCCESS';
    const VERIFY_LOGIN_OTP_SUCCESS                  = 'VERIFY_LOGIN_OTP_SUCCESS';
    const VERIFY_LOGIN_OTP_FAILED                   = 'VERIFY_LOGIN_OTP_FAILED';
    const OTP_LOGIN_2FA_PASSWORD_DURATION           = 'OTP_LOGIN_2FA_PASSWORD_DURATION';
    const OTP_LOGIN_2FA_PASSWORD_SUCCESS            = 'OTP_LOGIN_2FA_PASSWORD_SUCCESS';
    const OTP_LOGIN_2FA_PASSWORD_FAILED             = 'OTP_LOGIN_2FA_PASSWORD_FAILED';
    const USER_ORG_ALLOWED_IN_SEPARATED_LOGIN_SIGNUP = 'USER_ORG_ALLOWED_IN_SEPARATED_LOGIN_SIGNUP';
    const USER_ORG_NOT_ALLOWED_IN_SEPARATED_LOGIN_SIGNUP = 'USER_ORG_NOT_ALLOWED_IN_SEPARATED_LOGIN_SIGNUP';
    const USER_CLIENT_ALLOWED_IN_SEPARATED_LOGIN_SIGNUP = 'USER_CLIENT_ALLOWED_IN_SEPARATED_LOGIN_SIGNUP';
    const USER_CLIENT_NOT_ALLOWED_IN_SEPARATED_LOGIN_SIGNUP = 'USER_CLIENT_NOT_ALLOWED_IN_SEPARATED_LOGIN_SIGNUP';
    const USER_CREATE_MERCHANT                      = 'USER_CREATE_MERCHANT';

    const API_PROMISE_RESPONSE_TIME_TAKEN           = 'API_PROMISE_RESPONSE_TIME_TAKEN';
    const API_PROMISE_BUILT_TIME_TAKEN              = 'API_PROMISE_BUILT_TIME_TAKEN';
    const PASSWORD_LOGIN_2FA_OTP_DURATION           = 'PASSWORD_LOGIN_2FA_OTP_DURATION';
    const PASSWORD_LOGIN_2FA_OTP_SUCCESS            = 'PASSWORD_LOGIN_2FA_OTP_SUCCESS';
    const PASSWORD_LOGIN_2FA_OTP_FAILED             = 'PASSWORD_LOGIN_2FA_OTP_FAILED';
    const USER_OAUTH_LOGIN_DURATION                 = 'USER_OAUTH_LOGIN_DURATION';
    const USER_OAUTH_LOGIN_SUCCESS                  = 'USER_OAUTH_LOGIN_SUCCESS';
    const USER_OAUTH_LOGIN_FAILED                   = 'USER_OAUTH_LOGIN_FAILED';
    const USER_OAUTH_SIGNUP_DURATION                = 'USER_OAUTH_SIGNUP_DURATION';
    const USER_OAUTH_SIGNUP_FAILED                  = 'USER_OAUTH_SIGNUP_FAILED';
    const USER_OAUTH_SIGNUP_SUCCESS                 = 'USER_OAUTH_SIGNUP_SUCCESS';

    const SEND_SIGNUP_OTP_DURATION                  = 'SEND_SIGNUP_OTP_DURATION';
    const VERIFY_SIGNUP_OTP_DURATION                = 'VERIFY_SIGNUP_OTP_DURATION';
    const USER_SIGNUP_DURATION                      = 'USER_SIGNUP_DURATION';
    const USER_SIGNUP_FAILED                        = 'USER_SIGNUP_FAILED';
    const USER_SIGNUP_SUCCESS                       = 'USER_SIGNUP_SUCCESS';
    const SEND_SIGNUP_OTP_TRIGGERED                 = 'SEND_SIGNUP_OTP_TRIGGERED';
    const SEND_SIGNUP_OTP_SUCCESS                   = 'SEND_SIGNUP_OTP_SUCCESS';
    const SEND_SIGNUP_OTP_FAILED                    = 'SEND_SIGNUP_OTP_FAILED';
    const VERIFY_SIGNUP_OTP_TRIGGERED               = 'VERIFY_SIGNUP_OTP_TRIGGERED';
    const VERIFY_SIGNUP_OTP_SUCCESS                 = 'VERIFY_SIGNUP_OTP_SUCCESS';
    const VERIFY_SIGNUP_OTP_FAILED                  = 'VERIFY_SIGNUP_OTP_FAILED';
    const USER_LOGIN_TRIGGERED                      = 'USER_LOGIN_TRIGGERED';
    const USER_LOGIN_SUCCESS                        = 'USER_LOGIN_SUCCESS';
    const USER_LOGIN_FAILED                         = 'USER_LOGIN_FAILED';
    const USER_SIGNUP_TRIGGERED                     = 'USER_SIGNUP_TRIGGERED';

    const LOGIN_SIGNUP_METRIC_TRACE_PUSH_FAILED     = 'LOGIN_SIGNUP_METRIC_TRACE_PUSH_FAILED';

    const USER_LOGIN_KEYS                           = 'USER_LOGIN_KEYS';
    const USER_OAUTH_LOGIN                          = 'USER_OAUTH_LOGIN';
    const USER_LOGIN_FAILURE                        = 'USER_LOGIN_FAILURE';
    const USER_VERIFICATION_FAILURE                 = 'USER_VERIFICATION_FAILURE';
    const SWITCH_MERCHANT                           = 'SWITCH_MERCHANT';
    const USER_LOGOUT                               = 'USER_LOGOUT';
    const USER_RETRIEVE_CREDS                       = 'USER_RETRIEVE_CREDS';
    const ENABLE_INSTANT_ACTIVATIONS                = 'ENABLE_INSTANT_ACTIVATIONS';

    const USERS_LOGOUT_BY_ROUTE                     = 'USERS_LOGOUT_BY_ROUTE';
    const USER_SESSION_LOGOUT_FAIL                  = 'USER_SESSION_LOGOUT_FAIL';
    const USER_FETCH_BROWSER_DETAILS_FAILURE        = 'USER_FETCH_BROWSER_DETAILS_FAILURE';
    const GET_USER_SESSION_DATA                     = 'GET_USER_SESSION_DATA';
    const INVALIDATE_OTHER_ACTIVE_SESSIONS          = 'INVALIDATE_OTHER_ACTIVE_SESSIONS';

    const USER_UNAUTHORIZED                         = 'USER_UNAUTHORIZED';
    const USER_UNAUTHORIZED_EXCEPTION               = 'USER_UNAUTHORIZED_EXCEPTION';

    const USER_UNAUTHORIZED_GENERIC_EXCEPTION       = 'USER_UNAUTHORIZED_GENERIC_EXCEPTION';

    const GENERIC_ROUTE_PATH                        = 'GENERIC_ROUTE_PATH';

    const CAPITAL_CARDS_GENERATE_TOKEN              =  'CAPITAL_CARDS_GENERATE_TOKEN';

    const ADMIN_LOGGED_IN_AS_MERCHANT               = 'ADMIN_LOGGED_IN_AS_MERCHANT';

    const BULK_RAZORX_CALL_FAILED                   = 'BULK_RAZORX_CALL_FAILED';

    const ADMIN_LOGIN                               = 'ADMIN_LOGIN';
    const ADMIN_LOGOUT                              = 'ADMIN_LOGOUT';
    const ADMIN_AS_MERCHANT                         = 'ADMIN_AS_MERCHANT';

    const ORG_LOGO_UPLOAD                           = 'ORG_LOGO_UPLOAD';

    const S3_BUCKET_DETAILS                         = 'S3_BUCKET_DETAILS';

    const MISMATCHED_VERIFY_TOKEN                   = 'MISMATCHED_VERIFY_TOKEN';

    const TOKEN_MATCH_TRACE                         = 'TOKEN_MATCH_TRACE';

    const UNAUTHORISED_BACKTRACE                    = 'UNAUTHORISED_BACKTRACE';

    const ERROR_PARSING_GRAPH_PAYLOAD_DATA          = 'ERROR_PARSING_GRAPH_PAYLOAD_DATA';

    const DEBUG_MERCHANT_TRUTHY_VALUE               = 'DEBUG_MERCHANT_TRUTHY_VALUE';

    const SPLITZ_EVALUATE_FAILED                    = 'SPLITZ_EVALUATE_FAILED';

    const SPLITZ_BULK_EVALUATE_FAILED               = 'SPLITZ_BULK_EVALUATE_FAILED';

    const PUSH_METRICS_FAILED                       = 'PUSH_METRICS_FAILED';

    const RECORD_SESSION_MISMATCH_FAILED            = 'RECORD_SESSION_MISMATCH_FAILED';

    const SESSION_MISMATCH                          = 'SESSION_MISMATCH';

    const SESSION_MISMATCH_NEW_DATA_SKIPPED         = 'SESSION_MISMATCH_NEW_DATA_SKIPPED';
    const SESSION_MISMATCH_OLD_DATA_SKIPPED         = 'SESSION_MISMATCH_OLD_DATA_SKIPPED';

    const ORG_FEATURES_CACHE_MISS                   = 'ORG_FEATURES_CACHE_MISS';

    const ADMIN_LOGOUT_ON_INACTIVITY                = 'ADMIN_LOGOUT_ON_INACTIVITY';
    const MERCHANT_LOGOUT_ON_INACTIVITY             = 'MERCHANT_LOGOUT_ON_INACTIVITY';
    const APP_NAME                                  = 'APP_NAME';
    const TIMEOUT_VALUE                             = 'TIMEOUT_VALUE';

    const ADMIN_RAW_API_CALL                        = 'ADMIN_RAW_API_CALL';
    const BLOCKED_DUE_TO_SBB_622                    = 'BLOCKED_DUE_TO_SBB_622';

    const GET_USER_FROM_API                         = 'GET_USER_FROM_API';
    const GET_USER_DURATION                         = 'GET_USER_DURATION';

    const PUSHED_HUBSPOT_EVENT_TO_API               = 'PUSHED_HUBSPOT_EVENT_TO_API';

    const PUSHED_HUBSPOT_EVENT_TO_API_FAILED        = 'PUSHED_HUBSPOT_EVENT_TO_API_FAILED';

    const PUSHED_SALESFORCE_LEAD_TO_API_FAILED      = 'PUSHED_SALESFORCE_LEAD_TO_API_FAILED';

    const PUSHED_SALESFORCE_LEAD_TO_API             = 'PUSHED_SALESFORCE_LEAD_TO_API';

    const GRAPH_REQUEST_OPERATION_WITH_USER_ID      = 'GRAPH_REQUEST_OPERATION_WITH_USER_ID';

    const EASY_DASHBOARD_URL_REDIRECTION            = 'EASY_DASHBOARD_URL_REDIRECTION';

    const FTUX_DASHBOARD_REDIRECTION_FAILED         = 'FTUX_DASHBOARD_REDIRECTION_FAILED';

    const PARTNER_AGENT_SWITCH_FAILED               = 'PARTNER_AGENT_SWITCH_FAILED';

    const PARTNER_AGENT_SWITCH_SUCCESS              = 'PARTNER_AGENT_SWITCH_SUCCESS';

    // User API tracecodes
    const GET_USER_ROUTE_INFO                    = 'GET_USER_ROUTE_INFO';
    const GET_MERCHANT_DETAILS_ROUTE_INFO        = 'GET_MERCHANT_DETAILS_ROUTE_INFO';
    const GET_TAGS_ROUTE_INFO                    = 'GET_TAGS_ROUTE_INFO';
    const GET_FEATURES_ROUTE_INFO                = 'GET_FEATURES_ROUTE_INFO';
    const GET_RAZORX_EXPERIMENTS_BULK_ROUTE_INFO = 'GET_RAZORX_EXPERIMENTS_BULK_ROUTE_INFO';
    const GET_RAZORX_EXPERIMENTS_ROUTE_INFO      = 'GET_RAZORX_EXPERIMENTS_ROUTE_INFO';
    const RAZORX_API_CALL_DISABLED               = 'RAZORX_API_CALL_DISABLED';
    const GET_SPLITZ_EXPERIMENTS_ROUTE_INFO      = 'GET_SPLITZ_EXPERIMENTS_ROUTE_INFO';
    const GET_CAMPAIGNS_ROUTE_INFO               = 'GET_CAMPAIGNS_ROUTE_INFO';
    const GET_TNC_POPUP_INFO                     = 'GET_TNC_POPUP_INFO';
    const GET_TNC_POPUP_ERROR                    = 'GET_TNC_POPUP_ERROR';

    const GET_PARTNER_CONFIGS_ROUTE_INFO         = 'GET_PARTNER_CONFIGS_ROUTE_INFO';
    const GET_PARTNER_CONFIG_GUEST               = 'GET_PARTNER_CONFIG_GUEST';
    const GET_PARTNER_ACTIVATION_ROUTE_INFO      = 'GET_PARTNER_ACTIVATION_ROUTE_INFO';
    const GET_PARTNER_ACTIVATION_ROUTE_ERROR     = 'GET_PARTNER_ACTIVATION_ROUTE_ERROR';
    const LEAD_TO_SALESFORCE_ROUTE_INFO          = 'LEAD_TO_SALESFORCE_ROUTE_INFO';
    const GET_PARTNER_INTENT_ROUTE_INFO          = 'GET_PARTNER_INTENT_ROUTE_INFO';
    const GET_PAYOUT_ROUTE_INFO                  = 'GET_PAYOUT_ROUTE_INFO';
    const PRODUCT_SWITCH_ROUTE_INFO              = 'PRODUCT_SWITCH_ROUTE_INFO';
    const FIRE_EVENT_TO_HUBSPOT_ROUTE_INFO       = 'FIRE_EVENT_TO_HUBSPOT_ROUTE_INFO';
    const SESSION_LAST_USED_AT                   = 'SESSION_LAST_USED_AT';

    const OPENCENSUS_ERROR                       = 'OPENCENSUS_ERROR';
    const JAEGER_SPAN_EXCEPTION                  = 'JAEGER_SPAN_EXCEPTION';
    const JAEGER_INFO                            = 'JAEGER_INFO';

    const EDGE_PRE_AUTHENTICATE_ERROR_PASSPORT_MISSING     = 'EDGE_PRE_AUTHENTICATE_ERROR_PASSPORT_MISSING';
    const EDGE_PRE_AUTHENTICATE_ERROR_INVALID_PASSPORT     = 'EDGE_PRE_AUTHENTICATE_ERROR_INVALID_PASSPORT';
    const EDGE_PRE_AUTHENTICATE_INVALID_OAUTH_PASSPORT     = 'EDGE_PRE_AUTHENTICATE_INVALID_OAUTH_PASSPORT';

    const EDGE_USER_AUTH_MISC_CODE                         = 'EDGE_USER_AUTH_MISC_CODE';
    const EDGE_COOKIE_PARSING_FAILED                       = 'EDGE_COOKIE_PARSING_FAILED';
    const EDGE_SETTING_HEADERS_FROM_API_FAILED              = 'EDGE_SETTING_HEADERS_FROM_API_FAILED';
    const MERCHANT_EXPERIMENTS                   = 'MERCHANT_EXPERIMENTS';

    const GENERATE_JWT_DASHBOARD                 = 'GENERATE_JWT_DASHBOARD';
    const VERIFY_JWT_DASHBOARD                   = 'VERIFY_JWT_DASHBOARD';
    const VALIDATE_JWT_USER_DASHBOARD            = 'VALIDATE_JWT_USER_DASHBOARD';
    const VERIFY_JWT_EXTENSION_AUTH_HEADER       = 'VERIFY_JWT_EXTENSION_AUTH_HEADER';

    // Graph Request Trace codes
    const GRAPH_REQUEST_AUTH_VALIDATION_TIME          = 'GRAPH_REQUEST_AUTH_VALIDATION_TIME';
    const GRAPH_REQUEST_X_DASHBOARD_UID_MID           = 'GRAPH_REQUEST_X_DASHBOARD_UID_MID';

    // Api route circuit breaker traces
    const API_CIRCUIT_BREAKER_MARK_FAILURE                 = 'API_CIRCUIT_BREAKER_MARK_FAILURE';
    const API_CIRCUIT_BREAKER_EXCEPTION                    = 'API_CIRCUIT_BREAKER_EXCEPTION';
    const API_CIRCUIT_BREAKER_MARK_SUCCESS                 = 'API_CIRCUIT_BREAKER_MARK_SUCCESS';
    const API_CIRCUIT_BREAKER_MARK_FAILURE_UNKNOWN_ROUTE   = 'API_CIRCUIT_BREAKER_MARK_FAILURE_UNKNOWN_ROUTE';
    const API_CIRCUIT_BREAKER_MARK_SUCCESS_UNKNOWN_ROUTE   = 'API_CIRCUIT_BREAKER_MARK_SUCCESS_UNKNOWN_ROUTE';
    const API_CIRCUIT_BREAKER_DECISION                     = 'API_CIRCUIT_BREAKER_DECISION';
    const API_CIRCUIT_BREAKER_UPDATING_ROUTE_NAME          = 'API_CIRCUIT_BREAKER_UPDATING_ROUTE_NAME';
    const API_CIRCUIT_BREAKER_UPDATING_PATH_PATTERN        = 'API_CIRCUIT_BREAKER_UPDATING_PATH_PATTERN';
    const API_CIRCUIT_BREAKER_ADDING_ROUTE                 = 'API_CIRCUIT_BREAKER_ADDING_ROUTE';
    const API_CIRCUIT_BREAKER_ROUTE_DETAIL_HEADERS_MISSING = 'API_CIRCUIT_BREAKER_ROUTE_DETAIL_HEADERS_MISSING';
    const API_CIRCUIT_BREAKER_PATH_MATCHED                 = 'API_CIRCUIT_BREAKER_PATH_MATCHED';
    const API_CIRCUIT_BREAKER_PATH_NOT_MATCHED             = 'API_CIRCUIT_BREAKER_PATH_NOT_MATCHED';

    const API_CONCURRENT_PROCESS_RESPONSE_FAILURE          = 'API_CONCURRENT_PROCESS_RESPONSE_FAILURE';

    const FORCE_SESSION_CLEAR_BEFORE_X_DEMO_LOGIN     = 'FORCE_SESSION_CLEAR_BEFORE_X_DEMO_LOGIN';
    const AES_LOGIN                                   = 'AES_LOGIN';
    const FORCE_SESSION_CLEAR_AFTER_X_DEMO_LOGOUT     = 'FORCE_SESSION_CLEAR_AFTER_X_DEMO_LOGOUT';

    const USER_SET_PASSWORD                         = 'USER_SET_PASSWORD';
    const RAZORX_CALL_FAILED                        = 'RAZORX_CALL_FAILED';
    const USER_VERIFY_LOGIN_VIA_2FA                 = 'USER_VERIFY_LOGIN_VIA_2FA';
    const USER_LOGIN_ADD_IN_SESSION                 = 'USER_LOGIN_ADD_IN_SESSION';
    const USER_VERIFY_2FA_RESEND_OTP                = 'USER_VERIFY_2FA_RESEND_OTP';
    const MAKE_RECONCILIATION_REQUEST               = 'MAKE_RECONCILIATION_REQUEST';

    const LOGIN_BLOCKED_EPOS_APP                    = 'LOGIN_BLOCKED_EPOS_APP';
    const ROUTE_BLOCKED_EPOS_APP                    = 'ROUTE_BLOCKED_EPOS_APP';

    const OPTIONS_ROUTE_ERROR_MODE_NULL             = 'OPTIONS_ROUTE_ERROR_MODE_NULL';
    const OPTIONS_ROUTE_ERROR_MODE_ERROR            = 'OPTIONS_ROUTE_ERROR_MODE_ERROR';
    const OPTIONS_ROUTE_MODE_AS_NULL_ERROR          = 'OPTIONS_ROUTE_MODE_AS_NULL_ERROR';
    const FETCH_ORG_DETAILS_ERROR                   = 'FETCH_ORG_DETAILS_ERROR';
    const FETCH_USER_DETAILS_ERROR                  = 'FETCH_USER_DETAILS_ERROR';
    const SHELL_REDIRECT                            = 'SHELL_REDIRECT';
    const SHELL_REDIRECT_ERROR                      = 'SHELL_REDIRECT_ERROR';
    const PRE_SIGNUP_DETAILS_FETCH_ERROR            = 'PRE_SIGNUP_DETAILS_FETCH_ERROR';
    const GET_REDIRECTION_URL_ERROR                 = 'GET_REDIRECTION_URL_ERROR';
    const MERCHANT_FEATURES_FETCH_ERROR             = 'MERCHANT_FEATURES_FETCH_ERROR';
    const MERCHANT_TAGS_FETCH_ERROR                 = 'MERCHANT_TAGS_FETCH_ERROR';
    const MERCHANT_ACTIVE_CAMPAIGNS_FETCH_ERROR     = 'MERCHANT_ACTIVE_CAMPAIGNS_FETCH_ERROR';
    const PARTNER_INTENT_FETCH_ERROR                = 'PARTNER_INTENT_FETCH_ERROR';
    const MERCHANT_DETAILS_FETCH_ERROR              = 'MERCHANT_DETAILS_FETCH_ERROR';
    const CHUNKED_DETAILS                           = 'CHUNKED_DETAILS';
    const CHUNKED_DETAILS_LOGIN_CACHED              = 'CHUNKED_DETAILS_LOGIN_CACHED';
    const VIEW_MERCHANT_INDEX_FILE                  = 'VIEW_MERCHANT_INDEX_FILE';
    const VIEW_MERCHANT_INDEX_SECOND_FILE           = 'VIEW_MERCHANT_INDEX_SECOND_FILE';
    const VIEW_MERCHANT_LA_INDEX_FILE               = 'VIEW_MERCHANT_LA_INDEX_FILE';

    const UNIFIED_SIGNUP_REDIRECTION                = 'UNIFIED_SIGNUP_REDIRECTION';
    const UNIFIED_LOGIN_REDIRECTION                 = 'UNIFIED_LOGIN_REDIRECTION';
    // Different from the above entries as they also have intent, this doesn't
    const USL_REDIRECTION                           = 'USL_REDIRECTION';
    const GET_CONFIG_STORE_KEYS_FAILED              = 'GET_CONFIG_STORE_KEYS_FAILED';

    const FETCH_OAUTH_ACTION_FOR_MERCHANT           = 'FETCH_OAUTH_ACTION_FOR_MERCHANT';
    const OAUTH_MERCHANT_ACTIVATION_DETAILS         = 'OAUTH_MERCHANT_ACTIVATION_DETAILS';

    const USL_REDIRECTION_EXCEPTION                 = 'USL_REDIRECTION_EXCEPTION';

    const USER_RENDER_DATA                          = 'USER_RENDER_DATA';

    const MAGIC_ANALYTICS_OAUTH_CALLBACK_FAILED               = 'MAGIC_ANALYTICS_OAUTH_CALLBACK_FAILED';

    const INVALIDATE_ORG_CACHE                      = 'INVALIDATE_ORG_CACHE';

    const PROMISE_BUILT_TIME                        = 'PROMISE_BUILT_TIME';

    const ERROR_FETCHING_MERCHANT_DETAILS           = 'ERROR_FETCHING_MERCHANT_DETAILS';

    const INFO_USES_X_SIGNUP_FLOW_V2_HEADER         = 'INFO_USES_X_SIGNUP_FLOW_V2_HEADER';

    const EDGE_TOKEN_REVOKE_FAILED                  = 'EDGE_TOKEN_REVOKE_FAILED';
    const EDGE_TOKEN_REVOKE_SUCCESS                 = 'EDGE_TOKEN_REVOKE_SUCCESS';

    const EDGE_TOKEN_REISSUE_FAILED                 = 'EDGE_TOKEN_REISSUE_FAILED';
    const EDGE_TOKEN_REISSUE_SUCCESS                = 'EDGE_TOKEN_REISSUE_SUCCESS';

    const TOKEN_REVOKED_AT_EDGE_RETURNING_UNAUTHORISED = 'TOKEN_REVOKED_AT_EDGE_RETURNING_UNAUTHORISED';

    const AZURE_BOT_DIRECT_LINE_TOKEN_GENERATE_FAIL  = 'AZURE_BOT_DIRECT_LINE_TOKEN_GENERATE_FAIL';

    const AUTHENTICATED_DASHBOARD_FORCED_REDIRECT_ERROR = "AUTHENTICATED_DASHBOARD_FORCED_REDIRECT_ERROR";
    const RAZORASSIST_REQUEST_FAiLED                 = 'RAZORASSIST_REQUEST_FAiLED';

    const INSIGHTX_SUPERSET_GUEST_TOKEN_FAIL = 'INSIGHTX_SUPERSET_GUEST_TOKEN_FAIL';

    const USER_MERCHANT_REGION_MISMATCH = 'USER_MERCHANT_REGION_MISMATCH';

    const UCS_ADMIN_GENERIC_REQUEST_RECIEVED = 'UCS_ADMIN_GENERIC_REQUEST_RECIEVED';

    const UCS_CALL_FAILED = 'UCS_CALL_FAILED';

    const UCS_CALL_SUCCESSFUL = 'UCS_CALL_SUCCESSFUL';

    const MES_CALL_FAILED       = 'MES_CALL_FAILED';
    const MES_CALL_SUCCESSFUL   = 'MES_CALL_SUCCESSFUL';
    const OLD_DASHBOARD_REDIRECT = 'OLD_DASHBOARD_REDIRECT';

    const BOUNCE_MEMO_REQUEST_FAILED = 'BOUNCE_MEMO_REQUEST_FAILED';

    const EASY_REDIRECTION_EXPERIMENT = 'EASY_REDIRECTION_EXPERIMENT';
    const EASY_REDIRECTION_EXPERIMENT_NULL_USER_ID = 'EASY_REDIRECTION_EXPERIMENT_NULL_USER_ID';
    const BANKING_ORIGIN_REQUEST_V2 = 'BANKING_ORIGIN_REQUEST_V2';
    const EASY_REDIRECTION_SPLTIZ_EXPERIMENT_CALL = 'EASY_REDIRECTION_SPLTIZ_EXPERIMENT_CALL';
    const SHOULD_USE_BANKING_ORIGIN_REQUEST_V2 = 'SHOULD_USE_BANKING_ORIGIN_REQUEST_V2';
    const ORIGIN_DOMAIN_AND_HOST = 'ORIGIN_DOMAIN_AND_HOST';
    const BANKING_ORIGIN_REQUEST_V1 = 'BANKING_ORIGIN_REQUEST_V1';
    const RETURN_FALSE_IS_REDIRECT_APPLICABLE = 'RETURN_FALSE_IS_REDIRECT_APPLICABLE';
    const BANKING_ORIGIN_REQUEST_V2_INSIDE_LOOP = 'BANKING_ORIGIN_REQUEST_V2_INSIDE_LOOP';

    const NEW_AUTH_REARCH_ENABLED = 'NEW_AUTH_REARCH_ENABLED';
    const ORG_FETCH_ERROR = 'ORG_FETCH_ERROR';
    const GET_CURRENT_MERCHANT_ORG_ID_START = 'GET_CURRENT_MERCHANT_ORG_ID_START';
    const GET_CURRENT_MERCHANT_ORG_ID_END   = 'GET_CURRENT_MERCHANT_ORG_ID_END';
    const GET_CURRENT_MERCHANT_DETAILS_NULL  = 'GET_CURRENT_MERCHANT_DETAILS_NULL';
    const GET_CURRENT_MERCHANT_ORG_ID_NULL   = 'GET_CURRENT_MERCHANT_ORG_ID_NULL';
    const ACCESS_DENIED_FOR_CROSS_ORG       = 'ACCESS_DENIED_FOR_CROSS_ORG';

    protected static $messages = array(
        self::ERROR_EXCEPTION                       => 'Unhandled critical exception occured',
        self::MISC_TRACE_CODE                       => 'Miscellaneous trace code',
        self::SLACK_QUERY_RESPONSE                  => 'Slack Query Response Log'
    );

    //pg3.0 tracing
    const PG3_REDIRECTION = 'PG3_REDIRECTION';

    /**
     * Translate event code to message
     *
     * @param  string $code
     *
     * @return string
     */
    public static function getMessage($code)
    {
        if (isset(self::$messages[$code]) === false)
        {
            // throw new InvalidArgumentException('Message for $code not defined');
            return null;
        }

        return self::$messages[$code];
    }

    public static function checkCode($code)
    {
        if (! defined(__NAMESPACE__."\TraceCode::$code"))
        {
            throw new InvalidArgumentException(
                __NAMESPACE__.'\TraceCode::'.$code.'not defined');
        }
    }
}
