<?php

use Carbon\Carbon;

return [
    'testTwidSuccessRecon' => [
        'Sr. No'                        => '1',
        'Transaction ID'                => '667788',
        'Merchant Transaction Id'       => 'rzp_p1p23344',
        'Date'                          => Carbon::today()->format("Y-m-d h:m:s"),
        'Brand'                         => 'Demo',
        'Bill Value'                    => '1000',
        'Commission'                    => '50',
        'GST On Commission'             => '10',
        'Total Commission'              => '60',
        'Total Payable'                 => '940',
        'Status'                        => 'Capture',
    ],
    'testEmerchantpayPaymentSuccessRecon' => [
        'Transaction Date & Time' => Carbon::today()->format("Y-m-d h:m:s"),
        'Merchant Name' => 'Merchant1',
        'Merchant Transaction Id'       => 'rzp_p1p23344',
        'Transaction Type' => 'Sale Approved',
        'Transaction Currency' => 'EUR',
        'Transaction Amount' => '106.00',
        'Billing Currency' => '',
        'Billing Amount' => '',
        'Processing To Billing Currency Exchange Rate' => '',
        'Payment Type' => '',
        'Card Type' => '',
        'Card Sub-Type' => '',
        'Region Class' => '',
        'Authcode' => '',
        'Standard Debit Card Rate' => '',
        'Transaction Fee Currency' => '',
        'Transaction Fee Amount' => '',
        'Commission Percent' => '',
        'Interchange Fee' => '',
        'Interchange Currency' => '',
        'Scheme Fee' => '',
        'Scheme Fee Currency' => '',
        'Commission Amount' => '',
        'Unique ID' => '3f74e6160a3c509ec40677e716689233',
        'ARN' => '',
        'Gateway' => '',
        'Business Data' => '',
    ],
    'testEmerchantpayRefundSuccessRecon' => [
        'Transaction Date & Time' => Carbon::today()->format("Y-m-d h:m:s"),
        'Merchant Name' => 'Merchant1',
        'Merchant Transaction Id'       => 'rzp_p1p23344',
        'Transaction Type' => 'Refund Approved',
        'Transaction Currency' => 'EUR',
        'Transaction Amount' => '106.00',
        'Billing Currency' => '',
        'Billing Amount' => '',
        'Processing To Billing Currency Exchange Rate' => '',
        'Payment Type' => '',
        'Card Type' => '',
        'Card Sub-Type' => '',
        'Region Class' => '',
        'Authcode' => '',
        'Standard Debit Card Rate' => '',
        'Transaction Fee Currency' => '',
        'Transaction Fee Amount' => '',
        'Commission Percent' => '',
        'Interchange Fee' => '',
        'Interchange Currency' => '',
        'Scheme Fee' => '',
        'Scheme Fee Currency' => '',
        'Commission Amount' => '',
        'Unique ID' => '3f74e6160a3c509ec40677e716689233',
        'ARN' => '',
        'Gateway' => '',
        'Business Data' => '',
    ],
];
