<?php

return [
    'facades' => [
        'virtual_yes_bank' => [
            'cust_code'          => '111222',
            'remitter_code'      => '123',
            'customer_subcode'   => null,
            'invoice_no'         => null,
            'bene_account_no'    => '11122200123',
            'amount'             => 100,
            'rmtr_account_no'    => null,
            'rmtr_account_ifsc'  => 'HDFC0000240',
            'transaction_ref_no' => '81231231232',
            'trans_received_at'  => '1/25/2018 7:16:25 PM',
            'trans_status'       => 'CREDITED',
            'validation_status'  => 'VALIDATED: OK',
            'transfer_type'      => 'NEFT',
            'credit_ref'         => '004331798',
            'notify_status'      => 'NOTIFIED: OK',
            'notify_result'      => null,
            'return_ref'         => null,
            'returned_at'        => null,
            'rmtr_full_name'     => 'TECNOTREE CONVERGENCE PVT LTD',
            'rmtr_add'           => 'BANGALORE',
            'udf11'              => null,
            'udf12'              => null,
            'udf13'              => null,
            'udf14'              => null,
        ],

        'card_fss_refund' => [
            'Merchant ID'            => '1000013',
            'Merchant Legal Name'    => 'Razorpay software pvt ltd',
            'Store ID'               => '1000013',
            'Store Trading Name'     => 'Razorpay software pvt ltd',
            'Terminal ID'            => '1000013',
            'Terminal Name'          => 'Razorpaysoftwarepvtltd',
            'Transaction IP Address' => '1.1.1.1',
            'Transaction Currency'   => 'INR',
            'Payment Method'         => 'Debit With PIN',
            'result_code'            => 'CAPTURED',
            'response_description'   => 'Success',
            'Bank ID'                => '1113',
            'Bank Name'              => 'Axis Bank Debit Card with ATM PIN',
            'Transaction Status'     => 'PROCESSED',
        ],

        'card_fss_payment' => [
            'Transaction Source'                     => 'Super Merchant PG',
            'Transaction Id'                         => '1234567812345678',
            'Mid'                                    => '10000013',
            'merchant legal name'                    => 'Razorpay software pvt ltd',
            'sid'                                    => '10000013',
            'store trading name'                     => 'Razorpay software pvt ltd',
            'tid'                                    => '1000013',
            'settlement date'                        => '01/05/2018',
            'transaction date'                       => '01/05/2018',
            'transaction type'                       => 'Purchase',
            'transaction currency'                   => 'INR',
            'additional amount'                      => '0.00',
            'merchant category code'                 => '7399',
            'Payment Method'                         => 'Debit With Pin',
            'transaction category'                   => 'NORMAL',
            'MSF %'                                  => '0',
        ],

        'first_data' => [
            'super_mid'            => '78541547',
            'mid'                  => '87001081',
            'mid_type'             => 'ECOMM',
            'trade_name'           => 'RENTOMOJO',
            'legal_name'           => 'RAZORPAY SOFTWARE PRIVATE LTD',
            'location'             => 'JAIPUR',
            'mcc'                  => '7394',
            'merchant_tariff'      => 'STANDARD ST',
            'merchant_grade'       => 'EO',
            'funding_type'         => 'NET DAILY',
            'batch_no'             => null,
            'batchdate'            => '10/22/2017',
            'transaction_date'     => '10/22/2017 7:58:41 PM',
            'post_date'            => '10/22/2017',
            'card_number'          => '607909******3564',
            'future_fund_date'     => null,
            'card_category'        => 'Rupay Card',
            'card_type'            => 'Rupay SMS',
            'area_of_event'        => 'Rupay SMS',
            'tid'                  => '87001081',
            'terminal_capture'     => null,
            'auth_code'            => '195841',
            'orig_msg_type'        => 'TX',
            'transaction_type'     => 'PURCHASE',
            'transaction_amt'      => 12940,
            'transaction_currency' => 'INR',
            'amount'               => 12940,
            'comm_amount'          => 129.40000000000001,
            'net_amt'              => 12940,
            'creditdebit'          => 'CREDIT',
            'transaction_status'   => 'CLEARED',
            'ft_no'                => '000065640855853',
            'session_id_aspd'      => '8sHKxcggFRPqbO',
            'flight_no'            => null,
            'ticketnumber'         => null,
            'trvlagencycode'       => null,
            'travel_agency_name'   => null,
            'arn_no'               => '729519152578',
            'ret_ref_num'          => null,
            'dcc_indicator'        => null,
            'mc_conv_fee'          => '0',
            'recurr_tran'          => null,
            'custom_data'          => null,
            'se_no'                => null,
        ],
        
        'hdfc' => [
            'merchant_code'    => 'T69801',
            'terminal_number'  => 70011863,
            'rec_fmt'          => 'BAT ',
            'bat_nbr'          => 15,
            'card_type'        => 'VISA SIGN SUPERIA CHIP CR.CARD',
            'card_number'      => '485499XXXXXX9495',
            'trans_date'       => 43031,
            'settle_date'      => 43032,
            'approv_code'      => '\'006479',
            'intnl_amt'        => 0,
            'domestic_amt'     => 35,
            'tran_id'          => '\'2325281332072961',
            'upvalue'          => '\'2',
            'merchant_trackid' => '\'8sgT9BJLSH4tHO',
            'msf'              => 0.65000000000000002,
            'serv_tax'         => 0,
            'sb_cess'          => 0,
            'kk_cess'          => 0,
            'cgst_amt'         => 0,
            'sgst_amt'         => 0,
            'igst_amt'         => 0,
            'utgst_amt'        => 0,
            'net_amount'       => 34.350000000000001,
            'debitcredit_type' => 'DC',
            'udf1'             => '\' ',
            'udf2'             => '\' ',
            'udf3'             => '\' ',
            'udf4'             => '\' ',
            'udf5'             => '\' PaymentID',
            'sequence_number'  => '\'729670245587',
            'arn_no'           => '\'74332747297729603604154',
            'invoice_number'   => '\'0',
            'transaction_id'   => '\'9780002136',
        ],

        'hdfc_cybersource' => [
            'merchant_code'    => 'T69801',
            'terminal_number'  => 89050055,
            'rec_fmt'          => 'CVD ',
            'bat_nbr'          => 999,
            'card_type'        => 'VISA SIGN SUPERIA CHIP CR.CARD',
            'card_number'      => '485499XXXXXX9495',
            'trans_date'       => 43031,
            'settle_date'      => 43032,
            'approv_code'      => '\'006479',
            'intnl_amt'        => 0,
            'domestic_amt'     => 35,
            'stan_id'          => '\'2325281332072961',
            'upvalue'          => '\'2',
            'merchant_trackid' => '\'8sgT9BJLSH4tHO',
            'msf'              => 0.65000000000000002,
            'serv_tax'         => 0,
            'sb_cess'          => 0,
            'kk_cess'          => 0,
            'cgst_amt'         => 0,
            'sgst_amt'         => 0,
            'igst_amt'         => 0,
            'utgst_amt'        => 0,
            'net_amount'       => 34.350000000000001,
            'debitcredit_type' => 'DC',
            'udf5'             => '\' PaymentID',
            'sequence_number'  => '\'729670245587',
            'arn_no'           => '\'(Onus transaction)',
        ],

        'axis' => [
            'settlement_date'      => '24-OCT-17',
            'mename'               => 'RAZORPAY SOFTWARE PVT LTD',
            'msg_type'             => 'CAPTURE',
            'card_no'              => '534680XXXXXX3881',
            'card_type'            => 'D',
            'lofo'                 => 'L',
            'merchant_type'        => 'RazorPay',
            'card_category'        => 'PREMIUM',
            'mer_comm'             => '0.25',
            'txn_amount'           => 192.06,
            'dcc_amount'           => 0,
            'commission'           => 0,
            'agg_comm_amt'         => 0,
            'gst'                  => 0,
            'agg_gst'              => 0,
            'payment'              => 192.06,
            'txn_date'             => '2017-10-23 16:51:33',
            'mcc'                  => '8299',
            'mcc_description'      => 'Schools and Educational Services-not elsewhere classified',
            'rrn_no'               => '729622438628',
            'appr_code'            => '028084',
            'account_no'           => '100012910528',
            'curr_code'            => '356',
            'eci'                  => '212',
            'mid'                  => 'RAZORPAYADD',
            'sol_id'               => null,
            'network'              => 'MASTER',
            'zone'                 => 'North',
            'transaction_category' => 'ONUS',
            'merchant_trans_ref'   => '8scgTNQTnntA67',
            'order_id'             => '2001504881',
            'order_info'           => null,
            'curr_exp'             => '2',
            'arn'                  => '75105177297000905183277',
        ],

        'billdesk' => [
            'refund_id'                 => 'uibpgthqndxmwcf',
            'ref_1'                     => '9LRjiRNokiZ3Ww',
            'refund_amount_rs_ps'       => 500
        ],

        'atom' => [
            'Merchant Name'         => 'RAZORPAY SOFTWARE PVT LTD',
            'Merchant ID'           => '58809',
            'Txn State'             => 'Sale',
            'Client Code'           => '007',
            'Product'               => 'Razorpay',
            'Discriminator'         => 'NB',
            'Payment Status'        => 'Payment Given',
            'Refund Status'         => '',
            'SB Cess'               => 0,
            'Krishi Kalyan Cess'    => 0,
            'Txn Charges'           => 0,
            'GST (18%)'             => 0,
            'Net Amount to be Paid' => 0,
        ],

        'hitachi' => [
            'terminal_id'           => '38R00001',
            'amount'                => 500,
            'retr_ref_nr'           => '123456789012',
            'auth_id'               => 108418,
            'interchange_type'      => 'VISA',
            'fee_amount'            => 0.00,
            'credit_debit'          => 'C',
            'cardcountry'           => 'IN',
            'arn'                   => 74110757361008597807228,
            'issettled'             => 'S',
            'message_type'          => '0200',
            'datetime'              => '2018-03-05 23:50:00',
            'tran_currency_code'    => '356',
        ],

        // Freecharge reconciliate has config of skipping 3 lines from bottom
        // Only first row will be read
        'freecharge' => [
            [
                'Order Id'                  => 'pay_9LEuURhlBPVCxk',
                'Total Transaction Amount'  => 500,
                'Transaction Type'          => 'Payment',
                'GST/Service Tax'           => 1.06272,
                'Net Deduction'             => 4.5
            ],
            [
                'Order Id' => str_random(14)
            ],
            [
                'Order Id' => str_random(14)
            ],
            [
                'Order Id' => str_random(14)
            ]
        ],

        'olamoney' => [
            'Tdr deducted in Rs'        => '9.67',
            'Unique Bill Id'            => '9LRjiRNokiZ3Ww',
            'Bill Amount in Rs'         => '500',
            'Goods And Services Tax'    => '1.7406',
            'Date of Settlement'        => '2018-06-07 02:22:32.0',
            'Transaction Type'          => 'debit'
        ],

        'mobikwik' => [
            'Fee'                   => '9.67',
            'OrderId'               => '9LRjiRNokiZ3Ww',
            'TxnAmount'             => '500',
            'ServiceTax'            => 'NA',
            'IGST'                  => '2.02',
            'RefundAdjustedDate'    => 'None'
        ]
    ],

    'reconciliate' => [
        'request' => [
            'url'     => '/reconciliate',
            'method'  => 'post',
            'content' => [
                'manual'            => 1,
                'attachment-count'  => 1,
                'gateway'           => null,
            ]
        ],
        'response' => [
            'content' => [],
        ]
    ],
];
