<?php

namespace RZP\Models\Merchant\Methods;

class Metric
{
    const PAYMENT_METHODS_READ_METRIC            =   'PAYMENT_METHODS_READ_METRIC';
    const PAYMENT_METHODS_UPDATE_METRIC          =   'PAYMENT_METHODS_UPDATE_METRIC';
    const SET_DEFAULT_METHODS_LATERNCY_METRIC  =   'SET_DEFAULT_METHODS_LATERNCY_METRIC';
    const PAYMENT_METHOD_DIFF_METRIC = 'PAYMENT_METHOD_DIFF_METRIC';
    const PAYMENT_METHOD_UPDATE_FAILED_METRIC = 'PAYMENT_METHOD_UPDATE_FAILED_METRIC';
    const PAYMENT_METHOD_SERVICE_CALL_FAILED_METRIC = 'PAYMENT_METHOD_SERVICE_CALL_FAILED_METRIC';
    const PAYMENT_METHOD_SERVICE_CALL_SUCCESS_METRIC = 'PAYMENT_METHOD_SERVICE_CALL_SUCCESS_METRIC';
    const PAYMENT_METHOD_DIFF_COUNT = 'PAYMENT_METHOD_DIFF_COUNT';
    const PAYMENT_METHOD_SERVICE_UPDATE_SUCCESS = 'PAYMENT_METHOD_SERVICE_UPDATE_SUCCESS';
    const PAYMENT_METHOD_SERVICE_UPDATE_FAILURE = 'PAYMENT_METHOD_SERVICE_UPDATE_FAILURE';
    const PAYMENT_METHOD_SERVICE_UPDATE_ATTEMPT = 'PAYMENT_METHOD_SERVICE_UPDATE_ATTEMPT';
    const PAYMENT_METHODS_SERVICE_FETCH_LATENCY = 'PAYMENT_METHODS_SERVICE_FETCH_LATENCY';
}
