<?php

namespace RZP\Models\Merchant\Methods;

class Metric
{

    const PAYMENT_METHODS_READ_METRIC            =   'PAYMENT_METHODS_READ_METRIC';
    const PAYMENT_METHODS_UPDATE_METRIC          =   'PAYMENT_METHODS_UPDATE_METRIC';

    const SET_DEFAULT_METHODS_LATERNCY_METRIC  =   'SET_DEFAULT_METHODS_LATERNCY_METRIC';
}
