<?php

namespace RZP\Models\Merchant\Methods;

class Metric
{

    const PAYMENT_METHODS_READ_METRIC            =   'PAYMENT_METHODS_READ_METRIC';
    const PAYMENT_METHODS_UPDATE_METRIC          =   'PAYMENT_METHODS_UPDATE_METRIC';
    const SET_DEFAULT_METHODS_LATERNCY_METRIC  =   'SET_DEFAULT_METHODS_LATERNCY_METRIC';
    const PAYMENT_METHOD_DIFF_METRIC = 'PAYMENT_METHOD_DIFF_METRIC';
    const PAYMENT_METHOD_UPDATE_FAILED_METRIC = 'PAYMENT_METHOD_UPDATE_FAILED_METRIC';
}
