<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important;"><head style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important;"><meta http-equiv="Content-Type" content="text/html; charset=utf-8" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important;"><meta name="viewport" content="width=device-width" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important;"></head><body class="body" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; margin: 0; min-width: 100%; padding: 0; width: 100% !important; color: #222222; font-weight: normal; line-height: 19px; text-align: left; font-size: 14px; background: #EBECEE;">
    <table class="container" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px; background: #EBECEE;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
          <!-- EMail Header with date -->
          <table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative;">
                <table class="three columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 130px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="left-text-pad" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; padding-left: 45px;">
                      <img src="<?php echo $message->embed(public_path().'/img/razorpay_grey.png'); ?>" alt="Razorpay Logo" title="Razorpay Logo" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -ms-interpolation-mode: bicubic; clear: both; display: block; float: left; max-width: 100%; outline: none; text-decoration: none; width: auto;"></td>
                    <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                  </tr></table></td>
              <td class="wrapper offset-by-six last" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative; padding-left: 300px; padding-right: 0px;">
                <table class="three columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 130px; margin-top: 6px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="lighttext right-text-pad" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2; padding-right: 45px;">
                      {{date('jS F Y', $payment['timestamp'])}}
                    </td>
                    <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                  </tr></table></td>
            </tr></table><!-- Payment Successfull Header --><table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" align="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 580px; width: 100%;">

                  <table class="container" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper center last" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative; padding-right: 0px;">
                        <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 580px; width: 100%;">
                        <table class="twelve columns bluebg" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; background: #39ACE5; margin: 0 auto; width: 580px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                              <h1 style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; font-weight: bold; line-height: 1.3; margin: 0; padding: 0; text-align: center; word-break: normal; font-size: 32px; color: #f2f2f2; margin-top: 40px;">
                              <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 580px; width: 100%;">
                                Payment Successful
                              </center>
                              </h1>
                            </td>
                            <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                          </tr></table></center>
                      </td>
                    </tr></table></center>
              </td>
            </tr></table><!-- Money Image --><table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" align="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 580px; width: 100%;">
                  <table class="container" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper last bluebg" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #39ACE5; position: relative; padding-right: 0px;">
                        <table class="four columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                              <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 180px; width: 100%;">
                                <img src="<?php echo $message->embed(public_path().'/img/payment_green.png'); ?>" alt="Payment Confirmation" title="Payment Confirmation" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -ms-interpolation-mode: bicubic; clear: both; display: block; float: left; max-width: 100%; outline: none; text-decoration: none; width: auto;"></center>
                            </td>
                            <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                          </tr></table></td>
                    </tr></table></center>
              </td>
            </tr></table><!-- Merchant Name --><table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" align="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 580px; width: 100%;">
                  <table class="container" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper last bluebg" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #39ACE5; position: relative; padding-right: 0px;">
                        <table class="six columns bluebg" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; background: #39ACE5; margin: 0 auto; width: 280px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                              <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 280px; width: 100%;">
                                <h3 style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; font-weight: normal; line-height: 1.3; margin: 0; padding: 0; text-align: center; word-break: normal; font-size: 22px; color: #f2f2f2;">
                                <a href="{{$merchant['website']}}" title="{{$merchant['billing_label']}} Website" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; color: #f2f2f2; text-decoration: none; font-size: 22px; text-align: center;">{{$merchant['billing_label']}}</a>
                                </h3>
                              </center>
                            </td>
                            <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                          </tr></table></td>
                    </tr></table></center>
              </td>
            </tr></table><!-- Customer Information --><table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper white" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; position: relative;">
                <table class="eight columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 380px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="lighttext left-text-pad" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2; padding-left: 45px;">
                      <a class="email" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; color: inherit; text-decoration: none;">{{$customer['email']}}</a>
                    </td>
                    <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                  </tr></table></td>
              <td class="wrapper white last" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; position: relative; padding-right: 0px;">
                <table class="four columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="right-text-pad lighttext" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2; padding-right: 45px;">
                      {{$customer['phone']}}
                    </td>
                    <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                  </tr></table></td>
            </tr></table><!-- Payment Id --><table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" align="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 580px; width: 100%;">
                  <table class="container" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper last white" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; position: relative; padding-right: 0px;">
                        <table class="six columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 280px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center darktext" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C;">
                              <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 280px; width: 100%;">
                                Payment Id: {{$payment['id']}}
                              </center>
                              <hr class="small" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; background-color: #d9d9d9; border: none; color: #E5E5E5; height: 2px; width: 40%;"></td>
                            <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                          </tr></table></td>
                    </tr></table></center>
              </td>
            </tr></table><!-- Payment Details --><table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper white" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; position: relative;">
                <table class="four columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="darktext left-text-pad" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C; padding-left: 45px;">
                      Amount
                    </td>
                    <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                  </tr></table></td>
              <td class="wrapper white offset-by-five last" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; position: relative; padding-left: 250px; padding-right: 0px;">
                <table class="three columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 130px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="right-text-pad darktext" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C; padding-right: 45px;">
                      {{$payment['amount']}}
                    </td>
                    <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                  </tr></table></td>
            </tr></table><!-- Payment Method --><table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper white" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; position: relative;">
                <table class="four columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="darktext left-text-pad" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: left; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C; padding-left: 45px;">
                      Payment Method
                    </td>
                    <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                  </tr></table></td>
              <td class="wrapper white last" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; position: relative; padding-right: 0px;">
                <table class="eight columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 380px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="right-text-pad darktext" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 25px; margin: 0; font-size: 14px; color: #484B4C; padding-right: 45px;">
                      {{$payment['method'][0]}}<br style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important;"><span class="subtext" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; color: #7C8082; font-size: 16px; line-height: 10px;">
                      {{$payment['method'][1]}}
                      </span>
                    </td>
                    <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                  </tr></table></td>
            </tr></table><!-- Contact Us --><table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" align="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 580px; width: 100%;">
                  <table class="container" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper last white" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; position: relative; padding-right: 0px;">
                        <table class="twelve columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center lighttext" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2;">
                              <hr class="wide" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; background-color: #d9d9d9; border: none; color: #E5E5E5; height: 2px; width: 490px;"><center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 580px; width: 100%;">
                                If this is correct, you don't need to take any further action.<br style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important;">
                                Please <a title="Click to send us a mail" href="mailto:contact@razorpay.com" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; color: #2ba6cb; text-decoration: none;">contact us</a> in case of any discrepancy.
                              </center>
                            </td>
                            <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                          </tr></table></td>
                    </tr></table></center>
              </td>
            </tr></table><!-- Money Image --><table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" align="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 580px; width: 100%;">
                  <table class="container" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper last white" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; background: #ffffff; background-color: #ffffff; position: relative; padding-right: 0px;">
                        <table class="four columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 180px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                              <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 180px; width: 100%;">
                                <img src="<?php echo $message->embed(public_path().'/img/razorpay_color.png'); ?>" alt="Razorpay Logo" title="Razorpay Logo" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -ms-interpolation-mode: bicubic; clear: both; display: block; float: left; max-width: 100%; outline: none; text-decoration: none; width: auto;"></center>
                            </td>
                            <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                          </tr></table></td>
                    </tr></table></center>
              </td>
            </tr></table><!-- First Footer --><table class="row" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0px; text-align: left; vertical-align: top; position: relative; width: 100%; display: block;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center" align="center" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0; text-align: center; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px;">
                <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 580px; width: 100%;">
                  <table class="container" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: inherit; vertical-align: top; margin: 0 auto; width: 580px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="wrapper last" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 10px 20px 0px 0px; text-align: left; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; position: relative; padding-right: 0px;">
                        <table class="three columns" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; border-collapse: collapse; border-spacing: 0; padding: 0; text-align: left; vertical-align: top; margin: 0 auto; width: 130px;"><tr style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; padding: 0; text-align: left; vertical-align: top;"><td class="center lighttext" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0px 0px 10px; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 12px; color: #B2B2B2;">
                              <center style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; min-width: 130px; width: 100%;">
                                <a href="https://facebook.com/razorpay" class="logo" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; color: #2ba6cb; text-decoration: none; display: inline; float: none; height: 22px; padding: 0px 5px 0px 5px; width: 22px;">
                                  <img height="22" width="22" src="<?php echo $message->embed(public_path().'/img/facebook.png'); ?>" alt="Facebook Icon" title="Razorpay on Facebook" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -ms-interpolation-mode: bicubic; clear: both; display: block; float: none; max-width: 100%; outline: none; text-decoration: none; width: auto; border: none;"></a>
                                <a href="https://twitter.com/razorpay" class="logo" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; color: #2ba6cb; text-decoration: none; display: inline; float: none; height: 22px; padding: 0px 5px 0px 5px; width: 22px;">
                                  <img height="22" width="22" src="<?php echo $message->embed(public_path().'/img/twitter.png'); ?>" alt="Twitter Icon" title="Razorpay on Twitter" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -ms-interpolation-mode: bicubic; clear: both; display: block; float: none; max-width: 100%; outline: none; text-decoration: none; width: auto; border: none;"></a>
                                <a href="https://github.com/razorpay" class="logo" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; color: #2ba6cb; text-decoration: none; display: inline; float: none; height: 22px; padding: 0px 5px 0px 5px; width: 22px;">
                                  <img height="22" width="22" src="<?php echo $message->embed(public_path().'/img/github.png'); ?>" alt="GitHub Icon" title="Razorpay on GitHub" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -ms-interpolation-mode: bicubic; clear: both; display: block; float: none; max-width: 100%; outline: none; text-decoration: none; width: auto; border: none;"></a>
                              </center>
                            </td>
                            <td class="expander" style="font-family: 'Century Gothic', 'Lucida Sans', 'Tahoma', 'Arial' !important; -moz-hyphens: auto; -webkit-hyphens: auto; border-collapse: collapse !important; hyphens: auto; word-break: break-word; padding: 0 !important; text-align: right; vertical-align: top; font-weight: normal; line-height: 19px; margin: 0; font-size: 14px; visibility: hidden; width: 0px;"></td>
                          </tr></table></td>
                    </tr></table></center>
              </td>
            </tr></table></td>
      </tr></table></body></html>
