export const businessTypeMapping = {
  1: 'PROPRIETORSHIP',
  2: 'INDIVIDUAL',
  3: 'PARTNERSHIP',
  4: 'PRIVATE_LIMITED',
  5: 'PUBLIC_LIMITED',
  6: 'LLP',
  7: 'NGO',
  8: 'EDUCATIONAL',
  9: 'TRUST',
  10: 'SOCIETY',
  11: 'UNREGISTERED',
  12: 'ONE_PERSON_COMPANY',
  13: 'HUF',
};
