// Todo: delete this file, it's available in @dashboard/shared-utils
import { CURRENCY_FORMATTERS } from 'merchant/helpers/currency/helper';

const currencies = {
  default: {
    denomination: 100,
    format: CURRENCY_FORMATTERS.three,
  },
  AED: {
    code: '784',
    denomination: 100,
    symbol: 'د.إ',
    name: 'Emirati Dirham',
  },
  ALL: {
    code: '008',
    denomination: 100,
    symbol: 'Lek',
    name: 'Albanian Lek',
  },
  AMD: {
    code: '051',
    denomination: 100,
    symbol: '֏',
    name: 'Armenian Dram',
  },
  ARS: {
    code: '032',
    denomination: 100,
    symbol: 'ARS',
    name: 'Argentine Peso',
    format: CURRENCY_FORMATTERS.threecommadecimal,
  },
  AUD: {
    code: '036',
    denomination: 100,
    symbol: 'A$',
    name: 'Australian Dollar',
    format: CURRENCY_FORMATTERS.threespaceseparator,
  },
  AWG: {
    code: '533',
    denomination: 100,
    symbol: 'Afl.',
    name: 'Aruban or Dutch Guilder',
  },
  BBD: {
    code: '052',
    denomination: 100,
    symbol: '$',
    name: 'Barbadian or Bajan Dollar',
  },
  BDT: {
    code: '050',
    denomination: 100,
    symbol: '৳',
    name: 'Bangladeshi Taka',
  },
  BMD: {
    code: '060',
    denomination: 100,
    symbol: '$',
    name: 'Bermudian Dollar',
  },
  BND: {
    code: '096',
    denomination: 100,
    symbol: 'BND',
    name: 'Bruneian Dollar',
  },
  BOB: {
    code: '068',
    denomination: 100,
    symbol: 'Bs',
    name: 'Bolivian Bolíviano',
  },
  BSD: {
    code: '044',
    denomination: 100,
    symbol: 'B$',
    name: 'Bahamian Dollar',
  },
  BWP: {
    code: '072',
    denomination: 100,
    symbol: 'P',
    name: 'Botswana Pula',
  },
  BZD: {
    code: '084',
    denomination: 100,
    symbol: 'BZ$',
    name: 'Belizean Dollar',
  },
  CAD: {
    code: '124',
    denomination: 100,
    symbol: 'C$',
    name: 'Canadian Dollar',
  },
  CHF: {
    code: '756',
    denomination: 100,
    symbol: 'CHf',
    name: 'Swiss Franc',
    format: CURRENCY_FORMATTERS.chf,
  },
  CNY: {
    code: '156',
    denomination: 100,
    symbol: '¥',
    name: 'Chinese Yuan Renminbi',
  },
  COP: {
    code: '170',
    denomination: 100,
    symbol: 'COL$',
    name: 'Colombian Peso',
    format: CURRENCY_FORMATTERS.threecommadecimal,
  },
  CRC: {
    code: '188',
    denomination: 100,
    symbol: '₡',
    name: 'Costa Rican Colon',
    format: CURRENCY_FORMATTERS.threecommadecimal,
  },
  CUP: {
    code: '192',
    denomination: 100,
    symbol: '$MN',
    name: 'Cuban Peso',
  },
  CZK: {
    code: '203',
    denomination: 100,
    symbol: 'Kč',
    name: 'Czech Koruna',
    format: CURRENCY_FORMATTERS.threecommadecimal,
  },
  DKK: {
    code: '208',
    denomination: 100,
    symbol: 'DKK',
    name: 'Danish Krone',
  },
  DOP: {
    code: '214',
    denomination: 100,
    symbol: 'RD$',
    name: 'Dominican Peso',
  },
  DZD: {
    code: '012',
    denomination: 100,
    symbol: 'د.ج',
    name: 'Algerian Dinar',
  },
  EGP: {
    code: '818',
    denomination: 100,
    symbol: 'E£',
    name: 'Egyptian Pound',
  },
  ETB: {
    code: '230',
    denomination: 100,
    symbol: 'ብር',
    name: 'Ethiopian Birr',
  },
  EUR: {
    code: '978',
    denomination: 100,
    symbol: '€',
    name: 'Euro',
  },
  FJD: {
    code: '242',
    denomination: 100,
    symbol: 'FJ$',
    name: 'Fijian Dollar',
  },
  GBP: {
    code: '826',
    denomination: 100,
    symbol: '£',
    name: 'British Pound',
  },
  GHS: {
    code: '936',
    denomination: 100,
    symbol: 'GH₵',
    name: 'Ghanaian Cedi',
  },
  GIP: {
    code: '292',
    denomination: 100,
    symbol: 'GIP',
    name: 'Gibraltar Pound',
  },
  GMD: {
    code: '270',
    denomination: 100,
    symbol: 'D',
    name: 'Gambian Dalasi',
  },
  GTQ: {
    code: '320',
    denomination: 100,
    symbol: 'Q',
    name: 'Guatemalan Quetzal',
  },
  GYD: {
    code: '328',
    denomination: 100,
    symbol: 'G$',
    name: 'Guyanese Dollar',
  },
  HKD: {
    code: '344',
    denomination: 100,
    symbol: 'HK$',
    name: 'Hong Kong Dollar',
  },
  HNL: {
    code: '340',
    denomination: 100,
    symbol: 'HNL',
    name: 'Honduran Lempira',
  },
  HRK: {
    code: '191',
    denomination: 100,
    symbol: 'kn',
    name: 'Croatian Kuna',
    format: CURRENCY_FORMATTERS.threecommadecimal,
  },
  HTG: {
    code: '332',
    denomination: 100,
    symbol: 'G',
    name: 'Haitian Gourde',
  },
  HUF: {
    code: '348',
    denomination: 100,
    symbol: 'Ft',
    name: 'Hungarian Forint',
    format: CURRENCY_FORMATTERS.none,
  },
  IDR: {
    code: '360',
    denomination: 100,
    symbol: 'Rp',
    name: 'Indonesian Rupiah',
    format: CURRENCY_FORMATTERS.threecommadecimal,
  },
  ILS: {
    code: '376',
    denomination: 100,
    symbol: '₪',
    name: 'Israeli Shekel',
  },
  INR: {
    code: '356',
    denomination: 100,
    symbol: '₹',
    name: 'Indian Rupee',
    format: CURRENCY_FORMATTERS.inr,
  },
  JMD: {
    code: '388',
    denomination: 100,
    symbol: 'J$',
    name: 'Jamaican Dollar',
  },
  KES: {
    code: '404',
    denomination: 100,
    symbol: 'Ksh',
    name: 'Kenyan Shilling',
  },
  KGS: {
    code: '417',
    denomination: 100,
    symbol: 'Лв',
    name: 'Kyrgyzstani Som',
  },
  KHR: {
    code: '116',
    denomination: 100,
    symbol: '៛',
    name: 'Cambodian Riel',
  },
  KYD: {
    code: '136',
    denomination: 100,
    symbol: 'CI$',
    name: 'Caymanian Dollar',
  },
  KZT: {
    code: '398',
    denomination: 100,
    symbol: '₸',
    name: 'Kazakhstani Tenge',
  },
  LAK: {
    code: '418',
    denomination: 100,
    symbol: '₭',
    name: 'Lao Kip',
  },
  LKR: {
    code: '144',
    denomination: 100,
    symbol: 'රු',
    name: 'Sri Lankan Rupee',
  },
  LRD: {
    code: '430',
    denomination: 100,
    symbol: 'L$',
    name: 'Liberian Dollar',
  },
  LSL: {
    code: '426',
    denomination: 100,
    symbol: 'LSL',
    name: 'Basotho Loti',
  },
  MAD: {
    code: '504',
    denomination: 100,
    symbol: 'د.م.',
    name: 'Moroccan Dirham',
  },
  MDL: {
    code: '498',
    denomination: 100,
    symbol: 'MDL',
    name: 'Moldovan Leu',
  },
  MKD: {
    code: '807',
    denomination: 100,
    symbol: 'ден',
    name: 'Macedonian Denar',
  },
  MMK: {
    code: '104',
    denomination: 100,
    symbol: 'MMK',
    name: 'Burmese Kyat',
  },
  MNT: {
    code: '496',
    denomination: 100,
    symbol: '₮',
    name: 'Mongolian Tughrik',
  },
  MOP: {
    code: '446',
    denomination: 100,
    symbol: 'MOP$',
    name: 'Macau Pataca',
  },
  MUR: {
    code: '480',
    denomination: 100,
    symbol: '₨',
    name: 'Mauritian Rupee',
  },
  MVR: {
    code: '462',
    denomination: 100,
    symbol: 'Rf',
    name: 'Maldivian Rufiyaa',
  },
  MWK: {
    code: '454',
    denomination: 100,
    symbol: 'MK',
    name: 'Malawian Kwacha',
  },
  MXN: {
    code: '484',
    denomination: 100,
    symbol: 'Mex$',
    name: 'Mexican Peso',
  },
  MYR: {
    code: '458',
    denomination: 100,
    symbol: 'RM',
    name: 'Malaysian Ringgit',
    format: CURRENCY_FORMATTERS.myr,
  },
  NAD: {
    code: '516',
    denomination: 100,
    symbol: 'N$',
    name: 'Namibian Dollar',
  },
  NGN: {
    code: '566',
    denomination: 100,
    symbol: '₦',
    name: 'Nigerian Naira',
  },
  NIO: {
    code: '558',
    denomination: 100,
    symbol: 'NIO',
    name: 'Nicaraguan Cordoba',
  },
  NOK: {
    code: '578',
    denomination: 100,
    symbol: 'NOK',
    name: 'Norwegian Krone',
    format: CURRENCY_FORMATTERS.threecommadecimal,
  },
  NPR: {
    code: '524',
    denomination: 100,
    symbol: 'रू',
    name: 'Nepalese Rupee',
  },
  NZD: {
    code: '554',
    denomination: 100,
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
  },
  PEN: {
    code: '604',
    denomination: 100,
    symbol: 'S/',
    name: 'Peruvian Sol',
  },
  PGK: {
    code: '598',
    denomination: 100,
    symbol: 'PGK',
    name: 'Papua New Guinean Kina',
  },
  PHP: {
    code: '608',
    denomination: 100,
    symbol: '₱',
    name: 'Philippine Peso',
  },
  PKR: {
    code: '586',
    denomination: 100,
    symbol: '₨',
    name: 'Pakistani Rupee',
  },
  QAR: {
    code: '634',
    denomination: 100,
    symbol: 'QR',
    name: 'Qatari Riyal',
  },
  RUB: {
    code: '643',
    denomination: 100,
    symbol: '₽',
    name: 'Russian Ruble',
    format: CURRENCY_FORMATTERS.threecommadecimal,
  },
  SAR: {
    code: '682',
    denomination: 100,
    symbol: 'SR',
    name: 'Saudi Arabian Riyal',
  },
  SCR: {
    code: '690',
    denomination: 100,
    symbol: 'SRe',
    name: 'Seychellois Rupee',
  },
  SEK: {
    code: '752',
    denomination: 100,
    symbol: 'SEK',
    name: 'Swedish Krona',
    format: CURRENCY_FORMATTERS.threespacecommadecimal,
  },
  SGD: {
    code: '702',
    denomination: 100,
    symbol: 'S$',
    name: 'Singapore Dollar',
  },
  SLL: {
    code: '694',
    denomination: 100,
    symbol: 'Le',
    name: 'Sierra Leonean Leone',
  },
  SOS: {
    code: '706',
    denomination: 100,
    symbol: 'Sh.so.',
    name: 'Somali Shilling',
  },
  SSP: {
    code: '728',
    denomination: 100,
    symbol: 'SS£',
    name: 'South Sudanese Pound',
  },
  SVC: {
    code: '222',
    denomination: 100,
    symbol: '₡',
    name: 'Salvadoran Colon',
  },
  SZL: {
    code: '748',
    denomination: 100,
    symbol: 'E',
    name: 'Swazi Lilangeni',
    format: CURRENCY_FORMATTERS.szl,
  },
  THB: {
    code: '764',
    denomination: 100,
    symbol: '฿',
    name: 'Thai Baht',
  },
  TTD: {
    code: '780',
    denomination: 100,
    symbol: 'TT$',
    name: 'Trinidadian Dollar',
  },
  TZS: {
    code: '834',
    denomination: 100,
    symbol: 'Sh',
    name: 'Tanzanian Shilling',
  },
  USD: {
    code: '840',
    denomination: 100,
    symbol: '$',
    name: 'US Dollar',
  },
  UYU: {
    code: '858',
    denomination: 100,
    symbol: '$U',
    name: 'Uruguayan Peso',
    format: CURRENCY_FORMATTERS.threecommadecimal,
  },
  UZS: {
    code: '860',
    denomination: 100,
    symbol: "so'm",
    name: 'Uzbekistani Som',
  },
  YER: {
    code: '886',
    denomination: 100,
    symbol: '﷼',
    name: 'Yemeni Rial',
  },
  ZAR: {
    code: '710',
    denomination: 100,
    symbol: 'R',
    name: 'South African Rand',
    format: CURRENCY_FORMATTERS.threespaceseparator,
  },
  KWD: {
    code: '414',
    denomination: 1000,
    symbol: 'د.ك',
    name: 'Kuwaiti Dinar',
  },
  BHD: {
    code: '415',
    denomination: 1000,
    symbol: 'د.ب.',
    name: 'Bahraini Dinar',
  },
  OMR: {
    code: '416',
    denomination: 1000,
    symbol: 'ر.ع.',
    name: 'Omani Rial',
  },
};

export default currencies;
