// By using these tags we are hiding the products for malaysian merchants
export const HIDDEN_INTERNATIONAL_FEATURES_TAGS = {
  PaymentTransfers: 'i18_hide_payment.transfers',
  ProductRecommendationsKyc: 'i18_hide_product_recommendations_kyc',
  Refunds: 'i18_hide_refunds',
  Settlements: 'i18_hide_settlements',
  Disputes: 'i18_hide_disputes',
  Invoices: 'i18_hide_invoices',
  PaymentLinks: 'i18_hide_payment_links',
  PaymentPages: 'i18_hide_payment_pages',
  PaymentButtons: 'i18_hide_payment_buttons',
  Subscriptions: 'i18_hide_subscription',
  Marketplace: 'i18_hide_marketplace',
  QrCodes: 'i18_hide_qr_codes',
  Offers: 'i18_hide_offers',
  Stores: 'i18_hide_stores',
  Checkoutrewards: 'i18_hide_checkoutrewards',
  Customers: 'i18_hide_customers',
  AppStore: 'i18_hide_app_store',
  Partnership: 'i18_hide_partnership',
  Onboarding: 'i18_hide_onboarding',
  Announcements: 'i18_hide_announcements',
  BankReferenceId: 'i18_hide_payment.bank_reference_id',
  TrustedBadge: 'i18_hide_myaccount.trusted_badge',
  Credits: 'i18_hide_myaccount.credits',
  Balances: 'i18_hide_myaccount.balances',
  BankAccount: 'i18_hide_myaccount.bank_account',
  WebsiteAppDetails: 'i18_hide_myaccount.website_app_details',
  SupportHistory: 'i18_hide_myaccount.support_history',
  Reminders: 'i18_hide_reminders',
  TwoFactorVerification: 'i18_hide_2fa_verification',
  Gst: 'i18_hide_gst',
  AppSwitcher: 'i18_hide_app_switcher',
  Transactions: 'i18_hide_reports.transactions',
  RawSQL: 'i18_hide_reports.raw_sql',
  OnDemandSettlements: 'i18_hide_reports.on_demand_settlements',
  Contacts: 'i18_hide_reports.contacts',
  CheckoutInfo: 'i18_hide_settings.checkout_info',
  FlashCheckout: 'i18_hide_settings.flash_checkout',
  PaymentCapture: 'i18_hide_settings.payment_capture',
  International: 'i18_hide_international',
  WhatsappNotification: 'i18_hide_whatsapp_notification',
  MandateSummary: 'i18_hide_subscription.mandate_summary',
  Documentation: 'i18_hide_documentation',
  SmartCollect: 'i18_hide_virtual_accounts',
  PaymentHandle: 'i18_hide_payment_handle',
  PartnershipProgram: 'i18_hide_partnership_program',
  ReferalLinks: 'i18_hide_referal_links',
  PartnerCommission: 'i18_hide_partner_commission',
  AddNewRazorpayXMerchant: 'i18_hide_add_new_razorpay_x_merchant',
  RazorpayXAffiliateAccount: 'i18_hide_razorpay_x_affiliate_account',
  SubcriptionOffers: 'i18_hide_subscription_offers',
  InstantRefunds: 'i18_hide_instant_refunds',
  PAYMENT_LINKS: {
    UPIPaymentLink: 'i18_hide_upi_payment_link',
  },
  HolidayList: 'i18_hide_holiday_list',
  EMandate: 'i18_hide_emandate',
  SettlementGuide: 'i18_hide_settlement_guide',
  DowntimePaymentEvents: 'i18_hide_downtime_payment_events',
  PaymentReportWithOffers: 'i18_hide_payment_report_with_offers',
  PaymentBtnReport: 'i18_hide_payment_btn_report',
  QRCodeReportWithPayID: 'i18_hide_qr_code_report_with_pay_id',
  RazorpayMe: 'i18_hide_razorpay_me',
  SupportedBankLinks: 'i18_hide_supported_bank_links',
  SubscriptionSettings: 'i18_hide_subscription_settings',
  InvoiceFooterAddress: 'i18_hide_invoice_footer_address',
  OtherIntegrationMethods: 'i18_hide_other_integation_methods',
  SubscriptionPaymentButton: 'i18_hide_subscription_payment_button',
  FundAccount: 'i18_hide_fund_account',
  Order: 'i18_hide_order',
  Payment: 'i18_hide_payment',
  Custom: 'i18_hide_custom',
  HideRzpAppPopup: 'i18_hide_rzp_app_popup',
  GettingStarted: 'i18_hide_getting_started',
};

export enum CONFIG_TAGS_ENUM {
  'account.balances' = 'account.balances',
  'account.bank_account' = 'account.bank_account',
  'account.credits' = 'account.credits',
  'account.gst' = 'account.gst',
  'account.hide_2fa_verification' = 'account.hide_2fa_verification',
  'account.mandate_summary' = 'account.mandate_summary',
  'account.payment_capture' = 'account.payment_capture',
  'account.support_history' = 'account.support_history',
  'account.trusted_badge' = 'account.trusted_badge',
  'account.whatsapp_notification' = 'account.whatsapp_notification',
  'account.mobile_app' = 'account.mobile_app',
  'account.customer_support_details' = 'account.customer_support_details',
  'announcements.announcements' = 'announcements.announcements',
  'app_store.app_store' = 'app_store.app_store',
  'app_switcher.app_switcher' = 'app_switcher.app_switcher',
  'checkout_rewards.checkout_rewards' = 'checkout_rewards.checkout_rewards',
  'contact.website_app_details' = 'contact.website_app_details',
  'customers.customers' = 'customers.customers',
  'disputes.disputes' = 'disputes.disputes',
  'documentation.documentation' = 'documentation.documentation',
  'flash_checkout.flash_checkout' = 'flash_checkout.flash_checkout',
  'invoices.footer_address' = 'invoices.footer_address',
  'invoices.invoice' = 'invoices.invoice',
  'offers.offers' = 'offers.offers',
  'onboarding.onboarding' = 'onboarding.onboarding',
  'onboarding.getting_started' = 'onboarding.getting_started',
  'partnership.add_new_razorpay_x_merchant' = 'partnership.add_new_razorpay_x_merchant',
  'partnership.partner_commission' = 'partnership.partner_commission',
  'partnership.partnership_program' = 'partnership.partnership_program',
  'partnership.razorpay_x_affiliate_account' = 'partnership.razorpay_x_affiliate_account',
  'partnership.referral_links' = 'partnership.referral_links',
  'payment_buttons.other_integration_methods' = 'payment_buttons.other_integration_methods',
  'payment_buttons.payment_buttons' = 'payment_buttons.payment_buttons',
  'payment_links.payment_link' = 'payment_links.payment_link',
  'payment_links.upi_payment_link' = 'payment_links.upi_payment_link',
  'payment_list_filter.bank_reference_id' = 'payment_list_filter.bank_reference_id',
  'payment_pages.payment_pages' = 'payment_pages.payment_pages',
  'payments.payment_handle' = 'payments.payment_handle',
  'payment_transfer.transfers' = 'payment_transfer.transfers',
  'product_recommendations_kyc.product_recommendation_kyc' = 'product_recommendations_kyc.product_recommendation_kyc',
  'profile.razorpay_me' = 'profile.razorpay_me',
  'qr_code.qr_code' = 'qr_code.qr_code',
  'refunds.instant_refunds' = 'refunds.instant_refunds',
  'refunds.refund' = 'refunds.refund',
  'reminders.reminder' = 'reminders.reminder',
  'reports.reports' = 'reports.reports',
  'reports.contacts' = 'reports.contacts',
  'reports.custom' = 'reports.custom',
  'reports.on_demand_settlements' = 'reports.on_demand_settlements',
  'reports.payment_btn_report' = 'reports.payment_btn_report',
  'reports.payment_links' = 'reports.payment_links',
  'reports.payment_pages' = 'reports.payment_pages',
  'reports.payment_report_with_offers' = 'reports.payment_report_with_offers',
  'reports.qr_code_report_with_pay_id' = 'reports.qr_code_report_with_pay_id',
  'reports.qr_codes' = 'reports.qr_codes',
  'reports.raw_sql' = 'reports.raw_sql',
  'reports.refunds' = 'reports.refunds',
  'reports.subscriptions' = 'reports.subscriptions',
  'reports.transactions' = 'reports.transactions',
  'route.marketplace' = 'route.marketplace',
  'settings.checkout_info' = 'settings.checkout_info',
  'settings.international' = 'settings.international',
  'settlements.holiday_list' = 'settlements.holiday_list',
  'settlements.settlement' = 'settlements.settlement',
  'settlements.settlement_guide' = 'settlements.settlement_guide',
  'smart_collect.virtual_accounts' = 'smart_collect.virtual_accounts',
  'stores.stores' = 'stores.stores',
  'subscriptions.emandate' = 'subscriptions.emandate',
  'subscriptions.subscription_offers' = 'subscriptions.subscription_offers',
  'subscriptions.subscription_settings' = 'subscriptions.subscription_settings',
  'subscriptions.subscription' = 'subscriptions.subscription',
  'subscriptions.subscription_payment_button' = 'subscriptions.subscription_payment_button',
  'subscriptions.supported_bank_links' = 'subscriptions.supported_bank_links',
  'webhooks.downtime_payment_events' = 'webhooks.downtime_payment_events',
  'webhooks.fund_account' = 'webhooks.fund_account',
  'webhooks.invoice' = 'webhooks.invoice',
  'webhooks.order' = 'webhooks.order',
  'webhooks.payment' = 'webhooks.payment',
  'webhooks.payment_link' = 'webhooks.payment_link',
  'webhooks.refund' = 'webhooks.refund',
  'webhooks.subscription' = 'webhooks.subscription',
  'transactions.upload_invoices' = 'transactions.upload_invoices',
}

export type ConfigTagType = keyof typeof CONFIG_TAGS_ENUM;

/**
 * Mapping is added to fallback safely to
 * tags approach. The config based solution
 * will be behind experiment flag and will be
 * rolled out incrementally. Once fully released
 * this mapping would become obsolete and will be removed.
 */
export const CONFIG_TO_TAG_MAPPING = {
  [CONFIG_TAGS_ENUM['account.balances']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Balances,
  [CONFIG_TAGS_ENUM['account.bank_account']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.BankAccount,
  [CONFIG_TAGS_ENUM['account.credits']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Credits,
  [CONFIG_TAGS_ENUM['account.gst']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Gst,
  [CONFIG_TAGS_ENUM['account.hide_2fa_verification']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.TwoFactorVerification,
  [CONFIG_TAGS_ENUM['account.mandate_summary']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.MandateSummary,
  [CONFIG_TAGS_ENUM['account.payment_capture']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentCapture,
  [CONFIG_TAGS_ENUM['account.support_history']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.SupportHistory,
  [CONFIG_TAGS_ENUM['account.trusted_badge']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.TrustedBadge,
  [CONFIG_TAGS_ENUM['account.whatsapp_notification']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.WhatsappNotification,
  [CONFIG_TAGS_ENUM['account.mobile_app']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.HideRzpAppPopup,
  [CONFIG_TAGS_ENUM['announcements.announcements']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.Announcements,
  [CONFIG_TAGS_ENUM['app_store.app_store']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.AppStore,
  [CONFIG_TAGS_ENUM['app_switcher.app_switcher']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.AppSwitcher,
  [CONFIG_TAGS_ENUM['checkout_rewards.checkout_rewards']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.Checkoutrewards,
  [CONFIG_TAGS_ENUM['contact.website_app_details']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.WebsiteAppDetails,
  [CONFIG_TAGS_ENUM['customers.customers']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Customers,
  [CONFIG_TAGS_ENUM['disputes.disputes']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Disputes,
  [CONFIG_TAGS_ENUM['documentation.documentation']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.Documentation,
  [CONFIG_TAGS_ENUM['flash_checkout.flash_checkout']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.FlashCheckout,
  [CONFIG_TAGS_ENUM['invoices.footer_address']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.InvoiceFooterAddress,
  [CONFIG_TAGS_ENUM['invoices.invoice']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Invoices,
  [CONFIG_TAGS_ENUM['offers.offers']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Offers,
  [CONFIG_TAGS_ENUM['onboarding.onboarding']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Onboarding,
  [CONFIG_TAGS_ENUM['onboarding.getting_started']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.GettingStarted,
  [CONFIG_TAGS_ENUM['partnership.add_new_razorpay_x_merchant']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.AddNewRazorpayXMerchant,
  [CONFIG_TAGS_ENUM['partnership.partner_commission']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.PartnerCommission,
  [CONFIG_TAGS_ENUM['partnership.partnership_program']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.PartnershipProgram,
  [CONFIG_TAGS_ENUM['partnership.razorpay_x_affiliate_account']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.RazorpayXAffiliateAccount,
  [CONFIG_TAGS_ENUM['partnership.referral_links']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.ReferalLinks,
  [CONFIG_TAGS_ENUM['payment_buttons.other_integration_methods']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.OtherIntegrationMethods,
  [CONFIG_TAGS_ENUM['payment_buttons.payment_buttons']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentButtons,
  [CONFIG_TAGS_ENUM['payment_links.payment_link']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentLinks,
  [CONFIG_TAGS_ENUM['payment_links.upi_payment_link']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.PAYMENT_LINKS.UPIPaymentLink,
  [CONFIG_TAGS_ENUM['payment_list_filter.bank_reference_id']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.BankReferenceId,
  [CONFIG_TAGS_ENUM['payment_pages.payment_pages']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentPages,
  [CONFIG_TAGS_ENUM['payments.payment_handle']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentHandle,
  [CONFIG_TAGS_ENUM['payment_transfer.transfers']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentTransfers,
  [CONFIG_TAGS_ENUM['product_recommendations_kyc.product_recommendation_kyc']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.ProductRecommendationsKyc,
  [CONFIG_TAGS_ENUM['profile.razorpay_me']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.RazorpayMe,
  [CONFIG_TAGS_ENUM['qr_code.qr_code']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.QrCodes,
  [CONFIG_TAGS_ENUM['refunds.instant_refunds']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.InstantRefunds,
  [CONFIG_TAGS_ENUM['refunds.refund']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Refunds,
  [CONFIG_TAGS_ENUM['reminders.reminder']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Reminders,
  [CONFIG_TAGS_ENUM['reports.contacts']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Contacts,
  [CONFIG_TAGS_ENUM['reports.custom']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Custom,
  [CONFIG_TAGS_ENUM['reports.on_demand_settlements']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.OnDemandSettlements,
  [CONFIG_TAGS_ENUM['reports.payment_btn_report']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentBtnReport,
  [CONFIG_TAGS_ENUM['reports.payment_links']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentLinks,
  [CONFIG_TAGS_ENUM['reports.payment_pages']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentPages,
  [CONFIG_TAGS_ENUM['reports.payment_report_with_offers']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentReportWithOffers,
  [CONFIG_TAGS_ENUM['reports.qr_code_report_with_pay_id']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.QRCodeReportWithPayID,
  [CONFIG_TAGS_ENUM['reports.qr_codes']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.QrCodes,
  [CONFIG_TAGS_ENUM['reports.raw_sql']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.RawSQL,
  [CONFIG_TAGS_ENUM['reports.refunds']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Refunds,
  [CONFIG_TAGS_ENUM['reports.subscriptions']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Subscriptions,
  [CONFIG_TAGS_ENUM['reports.transactions']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Transactions,
  [CONFIG_TAGS_ENUM['route.marketplace']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Marketplace,
  [CONFIG_TAGS_ENUM['settings.checkout_info']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.CheckoutInfo,
  [CONFIG_TAGS_ENUM['settings.international']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.International,
  [CONFIG_TAGS_ENUM['settlements.holiday_list']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.HolidayList,
  [CONFIG_TAGS_ENUM['settlements.settlement']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Settlements,
  [CONFIG_TAGS_ENUM['settlements.settlement_guide']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.SettlementGuide,
  [CONFIG_TAGS_ENUM['smart_collect.virtual_accounts']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.SmartCollect,
  [CONFIG_TAGS_ENUM['stores.stores']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Stores,
  [CONFIG_TAGS_ENUM['subscriptions.emandate']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.EMandate,
  [CONFIG_TAGS_ENUM['subscriptions.subcription_offers']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.SubcriptionOffers,
  [CONFIG_TAGS_ENUM['subscriptions.subcription_settings']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.SubscriptionSettings,
  [CONFIG_TAGS_ENUM['subscriptions.subscription']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.Subscriptions,
  [CONFIG_TAGS_ENUM['subscriptions.subscription_payment_button']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.SubscriptionPaymentButton,
  [CONFIG_TAGS_ENUM['subscriptions.supported_bank_links']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.SupportedBankLinks,
  [CONFIG_TAGS_ENUM['webhooks.downtime_payment_events']]:
    HIDDEN_INTERNATIONAL_FEATURES_TAGS.DowntimePaymentEvents,
  [CONFIG_TAGS_ENUM['webhooks.fund_account']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.FundAccount,
  [CONFIG_TAGS_ENUM['webhooks.invoice']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Invoices,
  [CONFIG_TAGS_ENUM['webhooks.order']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Order,
  [CONFIG_TAGS_ENUM['webhooks.payment']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Payment,
  [CONFIG_TAGS_ENUM['webhooks.payment_link']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.PaymentLinks,
  [CONFIG_TAGS_ENUM['webhooks.refund']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Refunds,
  [CONFIG_TAGS_ENUM['webhooks.subscription']]: HIDDEN_INTERNATIONAL_FEATURES_TAGS.Subscriptions,
};
