<?php

namespace RZP\Models\SalesForce;

class Constants
{
    const RX_WEBSITE_SF_EVENTS            = 'RX_WEBSITE_SF_EVENTS';
    const CURRENT_ACCOUNT_CLARITY_CONTEXT = 'CURRENT_ACCOUNT_CLARITY_CONTEXT';
    const CURRENT_ACCOUNT_INTEREST        = 'CURRENT_ACCOUNT_INTEREST';
    const LOS_NEW_APPLICATION             = 'LOS_NEW_APPLICATION';
    const SHOPIFY_MIGRATION_REQUEST       = 'SHOPIFY_MIGRATION_REQUEST';
    const VENDOR_PAYMENT_EVENT            = 'VENDOR_PAYMENT_EVENT';
}
