name: Trigger UTs 11-20 Common Job

on:
  workflow_dispatch:
    inputs:
      t11:
        type: boolean
        description: "Features 6 UT"
      t12:
        type: boolean
        description: "Features 7 UT"
      t13:
        type: boolean
        description: "Features UT"
      t14:
        type: boolean
        description: "Gateway 1 UT"
      t15:
        type: boolean
        description: "Gateway 2 UT"
      t16:
        type: boolean
        description: "NoCode UT"
      t17:
        type: boolean
        description: "Payment UT"
      t18:
        type: boolean
        description: "Platform UT"
      t19:
        type: boolean
        description: "Post Payment UT"
      t20:
        type: boolean
        description: "Razorpay X UT"

jobs:
  features_6_test_suite:
    if: ${{ inputs.t11 }}
    uses: ./.github/workflows/features_6_test_suite.yml
    secrets: inherit

  features_7_test_suite:
    if: ${{ inputs.t12 }}
    uses: ./.github/workflows/features_7_test_suite.yml
    secrets: inherit

  features_test_suite:
    if: ${{ inputs.t13 }}
    uses: ./.github/workflows/features_test_suite.yml
    secrets: inherit

  gateway_1_test_suite:
    if: ${{ inputs.t14 }}
    uses: ./.github/workflows/gateway_1_test_suite.yml
    secrets: inherit

  gateway_2_test_suite:
    if: ${{ inputs.t15 }}
    uses: ./.github/workflows/gateway_2_test_suite.yml
    secrets: inherit

  nocode_test_suite:
    if: ${{ inputs.t16 }}
    uses: ./.github/workflows/nocode_test_suite.yml
    secrets: inherit

  payment_test_suite:
    if: ${{ inputs.t17 }}
    uses: ./.github/workflows/payment_test_suite.yml
    secrets: inherit

  platform_test_suite:
    if: ${{ inputs.t18 }}
    uses: ./.github/workflows/platform_test_suite.yml
    secrets: inherit

  post_payment_test_suite:
    if: ${{ inputs.t19 }}
    uses: ./.github/workflows/post_payment_test_suite.yml
    secrets: inherit

  razorpayx_test_suite:
    if: ${{ inputs.t20 }}
    uses: ./.github/workflows/razorpayx_test_suite.yml
    secrets: inherit
