name: Trigger UTs 21-30 Common Job

on:
  workflow_dispatch:
    inputs:
      t21:
        type: boolean
        description: "Route UT"
      t22:
        type: boolean
        description: "RX Payout UT"
      t23:
        type: boolean
        description: "Smart Collect UT"
      t24:
        type: boolean
        description: "UPI Suite UT"
      t25:
        type: boolean
        description: "Card Tests UT"
      t26:
        type: boolean
        description: "NB Plus Suite UT"
      t27:
        type: boolean
        description: "BVT Run"

jobs:
  route_ut_suite:
    if: ${{ inputs.t21 }}
    uses: ./.github/workflows/route_ut_suite.yml
    secrets: inherit

  rx_test_suite_payouts:
    if: ${{ inputs.t22 }}
    uses: ./.github/workflows/rx_test_suite_payouts.yml
    secrets: inherit

  smart_collect_ut_suite:
    if: ${{ inputs.t23 }}
    uses: ./.github/workflows/smart_collect_ut_suite.yml
    secrets: inherit

  upi_suite_test_suite:
    if: ${{ inputs.t24 }}
    uses: ./.github/workflows/upi_suite_test_suite.yml
    secrets: inherit

  ut_cards_test_suite:
    if: ${{ inputs.t25 }}
    uses: ./.github/workflows/UT_Cards_Test_Suite.yml
    secrets: inherit

  ut_nbplus_suite:
    if: ${{ inputs.t26 }}
    uses: ./.github/workflows/UT_NBplus_suite.yml
    secrets: inherit

  bvt_run:
    if: ${{ inputs.t27 }}
    uses: ./.github/workflows/bvt.yml
    secrets: inherit
