name: circuit_breaker_tests
on: [push]
jobs:
  cancel:
    runs-on: [self-hosted]
    name: Cancel Previous Runs
    if: always()
    timeout-minutes: 1
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        if: github.ref != 'refs/heads/master'
        name: cancel old workflows
        id: cancel
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - if: github.ref == 'refs/heads/master'
        name: Don't cancel old workflows
        id: dont_cancel
        run: |
          echo "Don't cancel old workflow"
  test:
    runs-on: [ self-hosted ]
    needs: [ cancel ]
    name: Unit Test Check
    if: always()
    container:
      image: c.rzp.io/razorpay/onggi:php-8.1-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    steps:
      - name: checkout
        id: checkout
        uses: razorpay/checkout-action@08eef2bd6ada50786812e7351457a762856a532f
      - name: prepare_test_permission
        run: chmod +x ci-assets/prepare_and_run_test.sh
      - uses: razorpay/create-github-app-token@v1
        name: Generate Github Token
        id: app-token
        with:
          app-id: ${{ secrets.WORKFLOWGATEKEEPER_APP_ID }}
          private-key: ${{ secrets.WORKFLOWGATEKEEPER_PRIVATEKEY }}
          repositories: "dashboard,razorpay,trace,slack-laravel,spine,oauth-5-laravel,metrics-php,edge-passport-php"
      - name: preparing and running test
        id: running_test
        run: ci-assets/prepare_and_run_test.sh
        env:
          GIT_TOKEN: ${{ steps.app-token.outputs.token }}
          REDIS_HOST: redis
          QUERY_CACHE_REDIS_HOST: redis
          QUERY_CACHE_REDIS_PORT: 6379
          MUTEX_REDIS_HOST: redis
          MUTEX_REDIS_PORT: 6379
          THROTTLE_REDIS_HOST: redis
          THROTTLE_REDIS_PORT: 6379
    services:
      redis:
        credentials:
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
        image: c.rzp.io/proxy_dockerhub/library/redis:alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
