on: [push]
jobs:
  cancel:
    runs-on: [self-hosted]
    name: Cancel Previous Runs
    if: always()
    timeout-minutes: 1
    steps:
    - uses: styfle/cancel-workflow-action@0.9.0
      if: github.ref != 'refs/heads/master'
      name: cancel old workflows
      id: cancel
      with:
        all_but_latest: true
        workflow_id: "build_images.yml"
        access_token: ${{ github.token }}
    - if: github.ref == 'refs/heads/master'
      name: Don't cancel old workflows
      id: dont_cancel
      run: |
        echo "Don't cancel old workflow"
  validate_php_syntax:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web-v3
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Validate PHP Syntax
    steps:
    - name: checkout
      id: checkout
      uses: razorpay/checkout-action@08eef2bd6ada50786812e7351457a762856a532f
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    - name: validate_php_syntax
      run: ci-assets/validate_php_syntax.sh
  build-web:
    runs-on: [self-hosted]
    needs: [cancel]
    continue-on-error: false
    name: Build Web Harbor
    steps:
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: build
        uses: docker/build-push-action@v2
        with:
          tags: c.rzp.io/razorpay/api:${{ github.sha }}
          push: true
          file: ./Dockerfile.web
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            GIT_TOKEN=${{ secrets.GIT_TOKEN }}
            GIT_USERNAME=rzp
            ONGGI_IMAGE=c.rzp.io/razorpay/onggi:php-7.2-api-web-v3
            ARMORY_IMAGE=c.rzp.io/razorpay/armory:wkhtmltopdf-v182
            OPENCENSUS_IMAGE=c.rzp.io/razorpay/onggi:opencensus-php-v2020.10.28

  build-worker:
     runs-on: [self-hosted]
     needs: [ cancel ]
     continue-on-error: false
     name: Build Worker Harbor
     steps:
       - name: Login to Harbor
         uses: docker/login-action@v1
         with:
           registry: c.rzp.io
           username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
           password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
       - name: Set up Docker Buildx
         id: buildx
         uses: docker/setup-buildx-action@v1
       - name: build
         uses: docker/build-push-action@v2
         with:
           tags: c.rzp.io/razorpay/api:worker-${{ github.sha }}
           push: true
           file: ./Dockerfile.worker
           build-args: |
             GIT_COMMIT_HASH=${{ github.sha }}
             GIT_TOKEN=${{ secrets.GIT_TOKEN }}
             GIT_USERNAME=rzp
             ONGGI_IMAGE=c.rzp.io/razorpay/onggi:php-7.2-api-web-v3
             ARMORY_IMAGE=c.rzp.io/razorpay/armory:wkhtmltopdf-v182
             OPENRESTY_IMAGE=c.rzp.io/razorpay/onggi:openresty-1.17.8.2-0-alpine-fat-nosse42

  build-checkout:
     runs-on: [self-hosted]
     needs: [cancel]
     continue-on-error: false
     name: Build Checkout Harbor
     steps:
       - name: Login to Harbor
         uses: docker/login-action@v1
         with:
           registry: c.rzp.io
           username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
           password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
       - name: Set up Docker Buildx
         id: buildx
         uses: docker/setup-buildx-action@v1
       - name: build
         uses: docker/build-push-action@v2
         with:
           tags: c.rzp.io/razorpay/api:checkout-${{ github.sha }}
           push: true
           file: ./Dockerfile.checkout
           build-args: |
             GIT_COMMIT_HASH=${{ github.sha }}
             GIT_TOKEN=${{ secrets.GIT_TOKEN }}
             GIT_USERNAME=rzp
             NGINX_IMAGE=c.rzp.io/razorpay/onggi:nginx-alpine-3.12

  build-openresty:
     runs-on: [self-hosted]
     needs: [cancel]
     continue-on-error: false
     name: Build Openresty Harbor
     steps:
       - name: Login to Harbor
         uses: docker/login-action@v1
         with:
           registry: c.rzp.io
           username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
           password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
       - name: Set up Docker Buildx
         id: buildx
         uses: docker/setup-buildx-action@v1
       - name: build
         uses: docker/build-push-action@v2
         with:
           tags: c.rzp.io/razorpay/api:openresty-${{ github.sha }}
           push: true
           file: ./Dockerfile.openresty
           build-args: |
             GIT_COMMIT_HASH=${{ github.sha }}
             GIT_TOKEN=${{ secrets.GIT_TOKEN }}
             GIT_USERNAME=rzp
             ONGGI_IMAGE=c.rzp.io/razorpay/onggi:php-7.2-api-web-v3
             OPENRESTY_IMAGE=c.rzp.io/razorpay/onggi:openresty-1.17.8.2-0-alpine-fat-nosse42

  build-e2e:
    name: E2E test build
    runs-on: [ self-hosted ]
    needs: [build-web, build-worker, build-checkout, build-openresty]
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          dockerfile: ./e2e/Dockerfile
          path: e2e
          build_args: GIT_TOKEN=${{ secrets.GIT_TOKEN }}
          push: true
          tags: e2e_${{ github.sha }}

  e2e-test-webhook:
    name: E2E test webhook
    runs-on: [ self-hosted ]
    needs: [ build-e2e ]
    steps:
      - uses: actions/checkout@v2
      - name: Find current pr
      # Find the PR associated with this push, if there is one.
        uses: jwalton/gh-find-current-pr@v1.3.0
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - name: Triggers rundeck's webhook to execute e2e tests
        if: ${{ steps.findPr.outputs.pr != '' }}
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://rundeck.dev.razorpay.in/api/40/webhook/hPvwyx4HOyR8M8C1EYKsYYAyGr5tCGPZ#E2E_Test_Execution_V2'
          method: 'POST'
          data: >
            {
               "self": {
                   "name": "api",
                   "commit_id": "${{ github.sha }}",
                   "chart_values": {
                      "replicas": 2,
                      "web_requests_cpu": "150m",
                      "web_requests_memory": "500Mi"
                   }
               },
               "dependencies": []
            }

  trigger_regression_suite:
   runs-on: [self-hosted]
   name: Regression Suite
   needs: [ validate_php_syntax, build-web, build-worker, build-checkout, build-openresty]
   if: github.ref == 'refs/heads/master'
   steps:
   - name: Webhook
     run: |
       curl -X POST -H "Content-Type: application/json" \
       -d '{ "branch" : "master" , "commit" : "${{ github.sha }}" , "repo" : "api" }' \
       https://${{ secrets.SPINNAKER_BASIC_AUTH }}@deploy-github-actions.razorpay.com/webhooks/webhook/x-regression
