name: Build
on: push

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  HOME: /actions-runner/_work
  AWS_STAGE_BETA_CDN_BUCKET: 'rzp-1018-nonprod-betacdn'
  AWS_STAGE_DASHBOARD_ASSETS_CDN_BUCKET: 'rzp-1018-nonprod-dashboard-assets'
  AWS_STAGE_COMMON_CACHE_BUCKET: 'rzp-1018-nonprod-actions-cache'
  AWS_PROD_COMMON_CACHE_BUCKET: 'rzp-actions-cache'
  BUILD_PATH: build/browser
  VERSION: ${{ github.sha }}

jobs:
  evaluate:
    name: Identify Affected Projects
    runs-on: [non-api-premium]
    outputs:
      affected: ${{ steps.set-output.outputs.affected }}
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Use Node v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install libraries for webp conversion
        run: |
          apt-get update && apt-get install -y libjpeg-dev libpng-dev libtiff-dev libgif-dev

      - name: Fetch base branch
        run: |
          git fetch origin master
      
      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies with caching
        uses: ./.github/actions/package-installer
        with:
          npm_razorpay_token: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Identify Affected Projects
        id: affected
        run: |
          echo "AFFECTED=$(npx nx show projects --affected --json --base=origin/master --head=${{ steps.extract_branch.outputs.branch }} | jq -r 'join(" ")')" >> $GITHUB_ENV

      - name: Check output
        run: echo ${{ env.AFFECTED }}

      - name: Set affected projects as output
        id: set-output
        run: echo "::set-output name=affected::${{ env.AFFECTED }}"

  build-web:
    name: Build Dashboard
    runs-on: [non-api-premium]
    needs: [evaluate]
    if: contains(needs.evaluate.outputs.affected, 'web')
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Use Node v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install libraries for webp conversion
        run: |
          apt-get update && apt-get install -y libjpeg-dev libpng-dev libtiff-dev libgif-dev

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies with caching
        uses: ./.github/actions/package-installer
        with:
          npm_razorpay_token: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Build All
        #Runs in parellel
        run: npx nx run web:production:build
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          VERSION: ${{ github.sha }}
      
      - name: Remove files
        run: rm -rf .git

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACTIONS_CACHE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACTIONS_CACHE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.ACTIONS_CACHE_AWS_REGION}}
        env:
          AWS_ACCESS_KEY: ${{ secrets.ACTIONS_CACHE_AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET: ${{ secrets.ACTIONS_CACHE_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{secrets.ACTIONS_CACHE_AWS_REGION}}

      - name: Web - Push build to Actions Cache
        run: |
          tar czf public.tar.gz public
          aws s3 cp public.tar.gz s3://rzp-actions-cache/dashboard-${{ github.sha }}.tar.gz
        env:
          AWS_ACCESS_KEY: ${{ secrets.ACTIONS_CACHE_AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET: ${{ secrets.ACTIONS_CACHE_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{secrets.ACTIONS_CACHE_AWS_REGION}}

      - name: Web - Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}

      - name: Web - Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Web - PHP Server Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: c.rzp.io/razorpay/dashboard:${{ github.sha }}
          push: true
          file: ./Dockerfile.ci
          secrets: |
            git_token=${{ secrets.GIT_TOKEN }}
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
            GIT_USERNAME=rzp

  build-micro-apps-devstack:
    name: Build Dashboard - MFEs - Devstack
    runs-on: [non-api-premium]
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Use Node v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install libraries for webp conversion
        run: |
          apt-get update && apt-get install -y libjpeg-dev libpng-dev libtiff-dev libgif-dev

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies with caching
        uses: ./.github/actions/package-installer
        with:
          npm_razorpay_token: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Build micro apps
        run: |
          git fetch origin master
          yarn nx affected -t devstack:build --base=origin/master --head=${{ steps.extract_branch.outputs.branch }} --exclude=web,dashboard
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: Remove files
        run: rm -rf .git

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGE_AWS_ACCESS_SECRET }}
          aws-region: ${{secrets.ACTIONS_CACHE_AWS_REGION}}
        env:
          AWS_ACCESS_KEY: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET: ${{ secrets.STAGE_AWS_ACCESS_SECRET }}
          AWS_REGION: ${{secrets.ACTIONS_CACHE_AWS_REGION}}

        # Run based on output of affected 
      - name: Micro Apps - Push Artifacts for Devstack
        run: |-
          aws s3 cp \
          --metadata-directive REPLACE \
          --cache-control "max-age=0,no-cache,no-store,must-revalidate" \
          apps/self-serve/$BUILD_PATH/selfserve.remoteEntry.js s3://$AWS_STAGE_DASHBOARD_ASSETS_CDN_BUCKET/dashboard/federated-bundles/selfserve/devstack/$VERSION/$BUILD_PATH/selfserve.remoteEntry.js

          aws s3 sync --cache-control "public,max-age=31536000" apps/self-serve/$BUILD_PATH s3://$AWS_STAGE_DASHBOARD_ASSETS_CDN_BUCKET/dashboard/federated-bundles/selfserve/devstack/$VERSION/$BUILD_PATH --exclude $BUILD_PATH/selfserve.remoteEntry.js

  build-micro-apps-automation:
    name: Build Dashboard - MFEs - Automation
    runs-on: [non-api-premium]
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Use Node v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install libraries for webp conversion
        run: |
          apt-get update && apt-get install -y libjpeg-dev libpng-dev libtiff-dev libgif-dev

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies with caching
        uses: ./.github/actions/package-installer
        with:
          npm_razorpay_token: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Build micro apps
        run: |
          git fetch origin master
          yarn nx affected -t automation:build --base=origin/master --head=${{ steps.extract_branch.outputs.branch }} --exclude=web,dashboard
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: Remove files
        run: rm -rf .git
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGE_AWS_ACCESS_SECRET }}
          aws-region: ${{secrets.ACTIONS_CACHE_AWS_REGION}}
        env:
          AWS_ACCESS_KEY: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET: ${{ secrets.STAGE_AWS_ACCESS_SECRET }}
          AWS_REGION: ${{secrets.ACTIONS_CACHE_AWS_REGION}}

        # Run based on output of affected 
      - name: Micro Apps - Push Artifacts for Automation
        run: |-
          aws s3 cp \
          --metadata-directive REPLACE \
          --cache-control "max-age=0,no-cache,no-store,must-revalidate" \
          apps/self-serve/$BUILD_PATH/selfserve.remoteEntry.js s3://$AWS_STAGE_COMMON_CACHE_BUCKET/dashboard/federated-bundles/selfserve/automation/$VERSION/$BUILD_PATH/selfserve.remoteEntry.js

          aws s3 sync --cache-control "public,max-age=31536000" apps/self-serve/$BUILD_PATH s3://$AWS_STAGE_COMMON_CACHE_BUCKET/dashboard/federated-bundles/selfserve/automation/$VERSION/$BUILD_PATH --exclude $BUILD_PATH/selfserve.remoteEntry.js

  build-micro-apps-production:
    name: Build Prod Dashboard - MFEs - Production
    runs-on: [non-api-premium]
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Use Node v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install libraries for webp conversion
        run: |
          apt-get update && apt-get install -y libjpeg-dev libpng-dev libtiff-dev libgif-dev

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies with caching
        uses: ./.github/actions/package-installer
        with:
          npm_razorpay_token: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Build micro apps
        run: |
          git fetch origin master
          yarn nx affected -t production:build --base=origin/master --head=${{ steps.extract_branch.outputs.branch }} --exclude=web,dashboard
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: Remove files
        run: rm -rf .git
 
      - name: Configure AWS Credentials - Actions Cache
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACTIONS_CACHE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACTIONS_CACHE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.ACTIONS_CACHE_AWS_REGION}}

      # TODO: move to shell script and run sync based on affected output
      - name: Micro Apps - Push Artifacts for Production
        run: |-
          aws s3 cp \
          --metadata-directive REPLACE \
          --cache-control "max-age=0,no-cache,no-store,must-revalidate" \
          apps/self-serve/$BUILD_PATH/selfserve.remoteEntry.js s3://$AWS_PROD_COMMON_CACHE_BUCKET/dashboard/federated-bundles/selfserve/production/$VERSION/$BUILD_PATH/selfserve.remoteEntry.js

          aws s3 sync --cache-control "public,max-age=31536000" apps/self-serve/$BUILD_PATH s3://$AWS_PROD_COMMON_CACHE_BUCKET/dashboard/federated-bundles/selfserve/production/$VERSION/$BUILD_PATH --exclude $BUILD_PATH/selfserve.remoteEntry.js

  workflow_status:
    runs-on: [self-hosted]
    name: Update Status Check
    needs: [build-web]
    continue-on-error: false
    if: always()
    steps:
      - name: Failed
        id: failed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: |
          echo 'Failing the workflow for github status check.'
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "failure" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
          exit 1
      - name: Success
        if: ${{ steps.failed.conclusion == 'skipped' }}
        run: |
          echo "Status check has passed!"
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "success" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
          exit 0

  build-e2e:
    name: E2E test build
    runs-on: [self-hosted]
    needs: [build-web]
    steps:
      - uses: actions/checkout@v2

      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./e2e
          file: ./e2e/Dockerfile
          push: true
          tags: c.rzp.io/razorpay/dashboard:e2e_${{ github.sha }}
          secrets: |
            git_token=${{ secrets.CI_BOT_TOKEN }}
          build-args: |
            GIT_USERNAME=rzp

  e2e-test-webhook:
    name: E2E test webhook
    runs-on: [self-hosted]
    needs: [build-e2e]
    steps:
      - name: Get Prod API commit
        uses: fjogeleit/http-request-action@52ba495021567f279f4a6577ac8fb73672197af8
        id: prodApiCommitId
        with:
          url: "https://api.razorpay.com/commit.txt"

      - name: Triggers argo workflows webhook to execute e2e tests
        uses: fjogeleit/http-request-action@52ba495021567f279f4a6577ac8fb73672197af8
        with:
          url: "https://argo.dev.razorpay.in/api/v1/events/argo-workflows/dashboard"
          method: "POST"
          bearerToken: ${{ secrets.ARGO_TOKEN }}
          # TODO: Remove empty line in api response
          data: >
            {
              "kube_manifests_ref": "master",
              "self": {
                  "name": "dashboard",
                  "commit_id": "${{ github.sha }}",
                  "repository_name": "${{ github.repository }}",
                  "node_selector":"node.kubernetes.io/worker-tests-app"
              },
              "dependencies": [
                {
                  "name": "api",
                  "commit_id": ${{ steps.prodApiCommitId.outputs.response }},
                  "node_selector":"node.kubernetes.io/worker-tests-app",
                  "chart_values": {
                    "enable_edge_base": true
                  }
                }
              ]
            }

