name: Build Image - API
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master  
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
jobs:
  validate-php-syntax-app:
    runs-on:
      - api-public
      - X64
    container:
      image: c.rzp.io/razorpay/onggi:php-8.1
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      volumes:
        - /etc/hosts:/etc/hosts
    continue-on-error: false
    name: Validate PHP Syntax
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v3.0.0"
        with:
          path: "/github/home/.composer/cache"
          key: "api-composer-${{ hashFiles('composer.lock') }}"
      - name: prepare_test
        run: ci-assets/prepare_test.sh
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: validate-php-syntax-app
        run: ci-assets/validate_php_syntax.sh app

  validate-php-syntax-misc:
    runs-on:
      - api-public
      - X64
    container:
      image: c.rzp.io/razorpay/onggi:php-8.1
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      volumes:
        - /etc/hosts:/etc/hosts
    continue-on-error: false
    name: Validate PHP Syntax - Misc
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v3.0.0"
        with:
          path: "/github/home/.composer/cache"
          key: "api-composer-${{ hashFiles('composer.lock') }}"
      - name: prepare_test
        run: ci-assets/prepare_test.sh
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: validate-php-syntax-misc
        run: ci-assets/validate_php_syntax.sh misc

  ######## Build Fetch Credstash Multi-Arch Docker Image Natively Without Using Emulation ########
  build-fetch-credstash-native:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-amd64
          - linux-arm64
    runs-on:
      - api-public
      - ${{ matrix.platform }}
    continue-on-error: false
    name: Build Credstash Native
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: build
        uses: docker/build-push-action@v3
        with:
          add-hosts: github.com:172.20.36.152
          tags: c.rzp.io/razorpay/api:fetch-credstash-${{ github.event.pull_request.head.sha || github.sha }}-${{ matrix.platform }}
          push: true
          context: .
          file: ./Dockerfile.fetchCredstash
          build-args: |
            API_BASE_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:php-8.1-api-web-v2
            CURL_CLI_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:curl-7.82
          secrets: |
            git_token=${{ secrets.GIT_TOKEN }}

  build-fetch-credstash-multiarch:
    # This action combines the amd64 & arm64 docker images from the previous job (build-fetch-credstash-native) & form a multi-arch docker image
    needs:
      - build-fetch-credstash-native
    name: Build Fetch Credstash Harbor
    runs-on:
      - api-public
      - linux-arm64
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: c.rzp.io/${{ github.repository }}
          flavor: suffix=fetch-credstash-${{ github.event.pull_request.head.sha || github.sha }}
      - uses: int128/docker-manifest-create-action@v1
        with:
          tags: c.rzp.io/razorpay/api:fetch-credstash-${{ github.event.pull_request.head.sha || github.sha }}
          suffixes: |
            -linux-amd64
            -linux-arm64

  ######## Build Web Multi-Arch Docker Image Natively Without Using Emulation ########
  build-web-native:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-amd64
          - linux-arm64
    runs-on:
      - api-public
      - ${{ matrix.platform }}
    continue-on-error: false
    name: Build Web Native
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: build
        uses: docker/build-push-action@v3
        with:
          add-hosts: github.com:172.20.36.152
          tags: c.rzp.io/razorpay/api:${{ github.event.pull_request.head.sha || github.sha }}-${{ matrix.platform }}
          push: true
          context: .
          file: ./Dockerfile.web
          build-args: |
            GIT_COMMIT_HASH=${{ github.event.pull_request.head.sha || github.sha }}
            CACHEBUST=${{ github.event.pull_request.head.sha || github.sha }}
            GIT_USERNAME=rzp
            API_BASE_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:php-8.1-api-web-v2
            CURL_CLI_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:curl-7.82
            OPENCENSUS_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:php-8.1-opencensus
          secrets: |
            git_token=${{ secrets.GIT_TOKEN }}

  build-web-multiarch:
  # This action combines the amd64 & arm64 docker images from the previous job (build-web-native) & form a multi-arch docker image
    needs:
      - build-web-native
    name: Build Web Harbor
    runs-on:
      - api-public
      - linux-arm64
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: c.rzp.io/${{ github.repository }}
          flavor: suffix=-${{ github.event.pull_request.head.sha || github.sha }}
      - uses: int128/docker-manifest-create-action@v1
        with:
          tags: c.rzp.io/razorpay/api:${{ github.event.pull_request.head.sha || github.sha }}
          suffixes: |
            -linux-amd64
            -linux-arm64

  ######## Build Worker Multi-Arch Docker Image Natively Without Using Emulation ########
  build-worker-native:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-amd64
          - linux-arm64
    runs-on:
      - api-public
      - ${{ matrix.platform }}
    continue-on-error: false
    name: Build Worker Native
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: build
        uses: docker/build-push-action@v3
        with:
          add-hosts: github.com:172.20.36.152
          tags: c.rzp.io/razorpay/api:worker-${{ github.event.pull_request.head.sha || github.sha }}-${{ matrix.platform }}
          push: true
          context: .
          file: ./Dockerfile.worker
          build-args: |
            GIT_COMMIT_HASH=${{ github.event.pull_request.head.sha || github.sha }}
            GIT_USERNAME=rzp
            CACHEBUST=${{ github.event.pull_request.head.sha || github.sha }}
            API_BASE_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:php-8.1-api-worker-v2
          secrets: |
            git_token=${{ secrets.GIT_TOKEN }}

  build-worker-multiarch:
  # This action combines the amd64 & arm64 docker images from the previous job (build-worker-native) & form a multi-arch docker image
    needs:
      - build-worker-native
    name: Build Worker Harbor
    runs-on:
      - api-public
      - linux-arm64
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: c.rzp.io/${{ github.repository }}
          flavor: suffix=worker-${{ github.event.pull_request.head.sha || github.sha }}
      - uses: int128/docker-manifest-create-action@v1
        with:
          tags: c.rzp.io/razorpay/api:worker-${{ github.event.pull_request.head.sha || github.sha }}
          suffixes: |
            -linux-amd64
            -linux-arm64

  ######## Build CheckOut Multi-Arch Docker Image Natively Without Using Emulation ########
  build-checkout-native:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-amd64
          - linux-arm64
    runs-on:
      - api-public
      - ${{ matrix.platform }}
    continue-on-error: false
    name: Build Checkout Native
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: build
        uses: docker/build-push-action@v3
        with:
          add-hosts: github.com:172.20.36.152
          tags: c.rzp.io/razorpay/api:checkout-${{ github.event.pull_request.head.sha || github.sha }}-${{ matrix.platform }}
          push: true
          context: .
          file: ./Dockerfile.checkout
          build-args: |
            GIT_COMMIT_HASH=${{ github.event.pull_request.head.sha || github.sha }}
            GIT_USERNAME=rzp
            NGINX_IMAGE=c.rzp.io/razorpay/onggi-multi-arch:nginx-alpine-3.12
          secrets: |
            git_token=${{ secrets.GIT_TOKEN }}

  build-checkout-multiarch:
  # This action combines the amd64 & arm64 docker images from the previous job (build-checkout-native) & form a multi-arch docker image
    needs:
      - build-checkout-native
    name: Build Checkout Harbor
    runs-on:
      - api-public
      - linux-arm64
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: c.rzp.io/${{ github.repository }}
          flavor: suffix=checkout-${{ github.event.pull_request.head.sha || github.sha }}
      - uses: int128/docker-manifest-create-action@v1
        with:
          tags: c.rzp.io/razorpay/api:checkout-${{ github.event.pull_request.head.sha || github.sha }}
          suffixes: |
            -linux-amd64
            -linux-arm64

  build-e2e:
    name: E2E test build
    runs-on:
      - api-public
      - X64
    needs: [ build-web-multiarch, build-worker-multiarch, build-checkout-multiarch, validate-php-syntax-app, validate-php-syntax-misc ]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          add-hosts: github.com:172.20.36.152
          file: ./e2e/Dockerfile
          context: e2e
          secrets: git_token=${{ secrets.GIT_TOKEN }}
          build-args: GIT_USERNAME=rzp
          push: true
          tags: c.rzp.io/razorpay/api:e2e_${{ github.event.pull_request.head.sha || github.sha }}

  # Triggers end-to-end test execution with argo workflow as executor
  #disabling this the E2E tests are migrated to orchestrator
  # e2e-test-webhook:
  #   name: E2E test webhook
  #   runs-on:
  #     - self-hosted
  #     - api
  #     - X64
  #   needs: [ build-e2e ]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Find current pr
  #       # Find the PR associated with this push, if there is one.
  #       uses: jwalton/gh-find-current-pr@v1.3.0
  #       id: findPr
  #       with:
  #         # Can be "open", "closed", or "all".  Defaults to "open".
  #         state: open
  #     - name: Triggers argo workflows webhook to execute e2e tests
  #       if: ${{ steps.findPr.outputs.pr != '' }}
  #       uses: fjogeleit/http-request-action@master
  #       with:
  #         url: 'https://argo.dev.razorpay.in/api/v1/events/argo-workflows/api'
  #         method: 'POST'
  #         bearerToken: ${{ secrets.ARGO_TOKEN }}
  #         data: >
  #           {
  #              "kube_manifests_ref": "master",
  #              "self": {
  #                  "name": "api",
  #                  "commit_id": "${{ github.event.pull_request.head.sha || github.sha }}",
  #                  "chart_values": {
  #                     "replicas": 2,
  #                     "web_requests_cpu": "150m",
  #                     "web_requests_memory": "200Mi"
  #                  }
  #              },
  #              "dependencies": [
  #                     {
  #                         "name": "pg-router",
  #                         "commit_id": "",
  #                         "chart_values": {
  #                             "ephemeral_db": false,
  #                             "replicas": 1
  #                         }
  #                     },
  #                     {
  #                         "name": "terminals",
  #                         "commit_id": "",
  #                         "chart_values": {
  #                             "ephemeral_db": false,
  #                             "replicas": 1
  #                         }
  #                     },
  #                     {
  #                         "name": "payment-links",
  #                         "commit_id": "",
  #                         "chart_values": {
  #                             "ephemeral_db": false,
  #                             "replicas": 1
  #                         }
  #                     }
  #                 ]
  #           }

  build-slit:
    name: SLIT test build
    runs-on:
      - api-public
      - X64
    needs: [ build-web-multiarch, build-worker-multiarch, build-checkout-multiarch, validate-php-syntax-app, validate-php-syntax-misc ]
    steps:
      - uses: actions/checkout@v2
      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          add-hosts: github.com:172.20.36.152
          file: ./slit/Dockerfile
          context: slit
          build-args: |
            GIT_COMMIT_HASH=${{ github.event.pull_request.head.sha }}
            GIT_USERNAME=rzp
          secrets: |
            git_token=${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN=${{ secrets.SONARQUBE_TOKEN }}
          push: true
          tags: c.rzp.io/razorpay/api:slit_${{ github.event.pull_request.head.sha || github.sha }}

  # Triggers end-to-end test execution with argo workflow as executor
  slit-test-webhook:
    name: SLIT test webhook
    runs-on:
      - self-hosted
      - api
      - X64
    needs: [ build-slit ]
    steps:
      - uses: actions/checkout@v2
      - name: Find current pr
        # Find the PR associated with this push, if there is one.
        uses: jwalton/gh-find-current-pr@v1.3.0
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - name: Triggers argo workflows webhook to execute slit tests
        if: ${{ steps.findPr.outputs.pr != '' }}
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://argo.dev.razorpay.in/api/v1/events/argo-workflows/api-slit'
          method: 'POST'
          bearerToken: ${{ secrets.ARGO_TOKEN }}
          data: >
            {
               "kube_manifests_ref": "master",
               "self": {
                   "name": "api",
                   "commit_id": "${{ github.event.pull_request.head.sha || github.sha }}",
                   "chart_values": {
                      "replicas": 2,
                      "web_requests_cpu": "150m",
                      "web_requests_memory": "200Mi"
                   }
               },
               "dependencies": []
            }

  trigger_regression_suite:
    runs-on:
      - api-public
      - X64
    name: Regression Suite
    needs: [ build-web-multiarch, build-worker-multiarch, build-checkout-multiarch, validate-php-syntax-app, validate-php-syntax-misc ]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{ "branch" : "master" , "commit" : "${{ github.event.pull_request.head.sha || github.sha }}" , "repo" : "api" }' \
          https://${{ secrets.SPINNAKER_BASIC_AUTH }}@deploy-github-actions.razorpay.com/webhooks/webhook/x-regression

  trigger-e2e-execution-master:
    name: Trigger E2E Execution on Master
    runs-on:
      - self-hosted
      - api
      - X64
    needs: [ build-web-multiarch, build-worker-multiarch, build-checkout-multiarch, validate-php-syntax-app, validate-php-syntax-misc ]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Run ITF E2E Tests - Master
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://e2e-test-orchestrator.dev.razorpay.in/twirp/rzp.e2e_test_orchestrator.suite_execution.v1.SuiteExecutionAPI/Create"
          username: ${{ secrets.E2E_ORCHESTRATOR_USERNAME }}
          password: ${{ secrets.E2E_ORCHESTRATOR_PASSWORD }}
          method: "POST"
          data: >
            {
              "service_under_test": "api",
              "commit_id": "${{ github.event.pull_request.head.sha || github.sha }}",
              "end_to_end_tests_ref": "master",
              "status": "Pending",
              "config_overrides": "{}"
            }
