name: Bundle Asset Checker

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  DASHBOARD_SLACK_WEBHOOK_URL: ${{ secrets.DASHBOARD_SLACK_WEBHOOK_URL }}

jobs:
  asset-checker:
    name: Bundle Asset Checker
    runs-on: [non-api-premium]
    continue-on-error: true
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install libraries for webp conversion
        run: |
          apt-get update && apt-get install -y libjpeg-dev libpng-dev libtiff-dev libgif-dev
      - run: npm install -g yarn
      - name: Install dependencies with caching
        uses: ./.github/actions/package-installer
        with:
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Build All
        run: npx lerna run --scope=web test:build:merchant
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          VERSION: ${{ github.sha }}

      - name: Size Limit Action - DangerJS
        id: sizelimit_dangerjs
        uses: danger/danger-js@11.3.0
        with:
          args: "--id sizelimit_dangerjs --dangerfile dangerfile-bundlelimit.js"
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: "true"

      - name: Print PR Report
        run: echo "PR Report - ${{ steps.sizelimit_dangerjs.outputs.bundleSizeReport }}"
