name: Bundle Size Diff

on:
    pull_request:
        paths:
            - 'web/**'

jobs:
  bundle-anlayzer:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node v16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - run: npm install -g yarn

      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          strip-hash: '\.(\w{8})\.js$'
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
