name: Publish Build To Chromatic

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [self-hosted]

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Chromatic for some reason needs git history

      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: |
          yarn --frozen-lockfile
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      - name: Push Build To Chromatic
        # Storybook builds inside web folder, Chromatic references that
        run: |
          cd web
          CHROMATIC_TOKEN=$CHROMATIC_TOKEN yarn chromatic
        env:
          CHROMATIC_TOKEN: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
