name: Dashboard Core | CI

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && format('master-{0}', github.sha) || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  HOME: /actions-runner/_work
  AWS_STAGE_DASHBOARD_ASSETS_CDN_BUCKET: "rzp-1018-nonprod-dashboard-assets"
  AWS_PROD_COMMON_CACHE_BUCKET: "rzp-actions-cache"
  NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  VERSION: ${{ github.sha }}

jobs:
  debug-workflow:
    name: Debug Workflow Settings
    runs-on: [ubuntu-latest]
    steps:
      - name: Debug Info
        run: |
          echo "Workflow: ${{ github.workflow }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Is Master?: ${{ github.ref == 'refs/heads/master' }}"
          echo "Cancel in Progress?: ${{ github.ref != 'refs/heads/master' }}"
          echo "Concurrency Group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && format('master-{0}', github.sha) || github.ref }}"

  initialize:
    name: Initialize CI
    secrets: inherit
    uses: ./.github/workflows/initialize-ci.yml
    with:
      branch_name: ${{ github.ref_name }}

  build-php:
    name: Build PHP
    secrets: inherit
    uses: ./.github/workflows/build-php.yml
    with:
      base_ref: ${{ github.base_ref }}

  build-main:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: [initialize]
    secrets: inherit
    with:
      target_envs: ${{ needs.initialize.outputs.target_envs }}
      affected_all: ${{ needs.initialize.outputs.affected_all }}
      affected_libs: ${{ needs.initialize.outputs.affected_libs }}
      affected_apps_p0: ${{ needs.initialize.outputs.affected_apps_p0 }}
      affected_apps_p1: ${{ needs.initialize.outputs.affected_apps_p1 }}
      affected_apps_p2: ${{ needs.initialize.outputs.affected_apps_p2 }}
      onboarded_microapps: ${{ needs.initialize.outputs.onboarded_microapps }}

  build-canary:
    name: Build Canary
    uses: ./.github/workflows/build-canary.yml
    needs: [initialize]
    secrets: inherit
    if: ${{ needs.initialize.outputs.run_canary_build == 'true' }}
    with:
      run_canary_build: ${{ needs.initialize.outputs.run_canary_build == 'true' }}
      affected_all: ${{ needs.initialize.outputs.affected_all }}
      affected_libs: ${{ needs.initialize.outputs.affected_libs }}
      affected_apps_p0: ${{ needs.initialize.outputs.affected_apps_p0 }}
      affected_apps_p1: ${{ needs.initialize.outputs.affected_apps_p1 }}
      affected_apps_p2: ${{ needs.initialize.outputs.affected_apps_p2 }}
      onboarded_microapps: ${{ needs.initialize.outputs.onboarded_microapps }}

  code-integrity-suite:
    name: Code Integrity Suite
    uses: ./.github/workflows/code-integrity-suite.yml
    needs: [initialize, build-main, build-php, build-canary]
    if: ${{ always() && needs.build-main.result == 'success' && needs.build-php.result == 'success' && (needs.build-canary.result == 'success' || needs.build-canary.result == 'skipped') }}
    secrets: inherit
    with:
      affected_all: ${{ needs.initialize.outputs.affected_all }}
      memory_intensive_ut_configured_apps: ${{ needs.initialize.outputs.memory_intensive_ut_configured_apps }}
      memory_intensive_ut_configured_apps_shards_array: ${{ needs.initialize.outputs.memory_intensive_ut_configured_apps_shards_array }}
      memory_intensive_ut_configured_apps_shards_total: ${{ needs.initialize.outputs.memory_intensive_ut_configured_apps_shards_total }}
      default_ut_configured_apps_matrix: ${{ needs.initialize.outputs.default_ut_configured_apps_matrix }}

  fe-e2e:
    name: Run E2E Tests
    uses: ./.github/workflows/fe-e2e.yml
    needs: [initialize, build-main, build-php, build-canary]
    if: ${{ always() && needs.build-main.result == 'success' && needs.build-php.result == 'success' && (needs.build-canary.result == 'success' || needs.build-canary.result == 'skipped') }}
    secrets: inherit
    with:
      run_e2e: true
      affected_apps: ${{ needs.initialize.outputs.affected_apps }}
      playwright_configured_affected_apps_array: ${{ needs.initialize.outputs.playwright_configured_affected_apps_array }}
      playwright_configured_affected_apps_comma_sep: ${{ needs.initialize.outputs.playwright_configured_affected_apps_comma_sep }}

  workflow-final-status:
    name: Workflow Status
    needs: [initialize, build-main, build-php, build-canary, code-integrity-suite, fe-e2e]
    runs-on: [ubuntu-latest]
    if: ${{ always() }}
    steps:
      - name: Evaluate Overall Workflow Status
        id: evaluate-status
        run: |
          status="success"
          if [ "${{ needs.build-main.result }}" != "success" ]; then
            status="failure"
          fi
          if [ "${{ needs.build-php.result }}" != "success" ]; then
            status="failure"
          fi
          if [ "${{ needs.build-canary.result }}" != "success" ] && [ "${{ needs.build-canary.result }}" != "skipped" ]; then
            status="failure"
          fi
          if [ "${{ needs.code-integrity-suite.result }}" != "success" ]; then
            status="failure"
          fi
          if [ "${{ needs.fe-e2e.result }}" != "success" ]; then
            status="failure"
          fi
          echo "status=${status}" >> $GITHUB_OUTPUT

      - name: Set Overall Workflow Status
        run: |
          if [ "${{ steps.evaluate-status.outputs.status }}" = "failure" ]; then
            echo "Dashboard Core | CI Failed"
            exit 1
          else
            echo "Dashboard Core | CI Completed"
          fi
