name: Dark branch jira check

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  dark-branch-jira:
    name: Dark branch jira check
    runs-on:
      - api-public
      - X64
    continue-on-error: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract Ticket IDs from PR title
        id: extract_tickets
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"

          JIRA_ID=$(echo "$PR_TITLE" | grep -ioE 'LIG-[0-9]+' | head -n1)
          DEVREV_ID=$(echo "$PR_TITLE" | grep -ioE 'TKT-[0-9]+' | head -n1)

          echo "jira_id=$JIRA_ID" >> $GITHUB_ENV
          echo "devrev_id=$DEVREV_ID" >> $GITHUB_ENV

          if [[ -n "$JIRA_ID" ]]; then
            echo "jira_found=true" >> $GITHUB_ENV
          else
            echo "jira_found=false" >> $GITHUB_ENV
          fi

          if [[ -n "$DEVREV_ID" ]]; then
            echo "devrev_found=true" >> $GITHUB_ENV
          else
            echo "devrev_found=false" >> $GITHUB_ENV
          fi

          if [[ -z "$JIRA_ID" && -z "$DEVREV_ID" ]]; then
            echo "No valid Jira or DevRev IDs found"
            exit 1
          fi

      - name: Check Ticket Status (Jira or DevRev)
        if: env.jira_found == 'true' || env.devrev_found == 'true'
        env:
          JIRA_ISSUE_ID: ${{ env.jira_id }}
          DEVREV_ISSUE_ID: ${{ env.devrev_id }}
          BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          DEVREV_API_TOKEN: ${{ secrets.DEVREV_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash ./.github/actions/checkLightJira.sh
