name: Generate Preview URL
on:
  pull_request:
    branches:
      - '**'
      - '!changeset-release/master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
env:
  ImageOS: ubuntu20
jobs:
  deploy-to-devstack:
    name: Deploy To Devstack for Preview URL
    runs-on: [ self-hosted ]
    if: ${{ github.event_name == 'pull_request' && github.event.head_commit.author.name != 'rzpcibot' }}
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
      # Wait for build to finish
      - name: Wait for dashboard's docker image to be built
        uses: ./.github/actions/waiting-build
        with:
          commit_id: ${{ github.event.pull_request.head.sha }}
          workflow_name: "Deploy To Devstack for Preview URL"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Triggers argo workflows webhook to create preview URL
        uses: fjogeleit/http-request-action@52ba495021567f279f4a6577ac8fb73672197af8
        with:
          url: 'https://argo.dev.razorpay.in/api/v1/events/argo-workflows/dashboard-devstack-deployment'
          method: 'POST'
          bearerToken: ${{ secrets.ARGO_TOKEN }}
          data: >
            {
              "kube_manifests_ref": "master",
              "repository": "razorpay/dashboard",
              "pull_request_number": "${{ github.event.number }}",
              "self": {
                  "name": "dashboard",
                  "commit_id": "${{ github.event.pull_request.head.sha }}",
                  "repository_name": "${{ github.repository }}",
                  "node_selector":"node.kubernetes.io/worker-tests-app"
              },
              "dependencies": []
            }