name: Deploy - Dashboard MFEs

on: deployment

concurrency:
  group: ${{ github.workflow }}-${{ github.event.deployment.environment }}-${{ github.event.deployment.payload.deploymentModule }}
  cancel-in-progress: true

env:
  HOME: /actions-runner/_work
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
  VERSION: ${{ github.event.deployment.ref }}
  STAGE: ${{ github.event.deployment.environment }}
  BUILD_PATH: build/browser
  AWS_STAGE_COMMON_CACHE_BUCKET: 'rzp-1018-nonprod-actions-cache'
  AWS_PROD_COMMON_CACHE_BUCKET: 'rzp-actions-cache'
  AWS_STAGE_DASHBOARD_ASSETS_CDN_BUCKET: 'rzp-1018-nonprod-dashboard-assets'
  AWS_PROD_DASHBOARD_ASSETS_CDN_BUCKET: 'rzp-1415-prod-dashboard-assets'
  AWS_DEFAULT_REGION: ap-south-1
  APP_NAME: ${{ github.event.deployment.payload.microfrontend }}
  AWS_S3_PROD_ROLE: arn:aws:iam::141592612890:role/gha-prod-dashboard_action

jobs:
  automation-dashboard-mfes-deploy:
    name: Automation Deploy - Dashboard MFEs
    runs-on: self-hosted
    timeout-minutes: 30
    if: |
      github.event.deployment.environment == 'automation' &&
      github.event.deployment.payload.deploymentModule == 'mfe'
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGE_AWS_ACCESS_SECRET }}
          aws-region: ${{secrets.ACTIONS_CACHE_AWS_REGION}}
        env:
          AWS_ACCESS_KEY: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET: ${{ secrets.STAGE_AWS_ACCESS_SECRET }}
          AWS_REGION: ${{secrets.ACTIONS_CACHE_AWS_REGION}}
      
      - name: Download Automation Build from S3 Cache
        run: |
          aws s3 cp s3://${AWS_STAGE_COMMON_CACHE_BUCKET}/dashboard/federated-bundles/${APP_NAME}/automation/${VERSION} ./ --recursive

      - name: Deploy to Automation
        run: |
          # Sync entry remote files which need to be deployed without caching
          aws s3 cp --metadata-directive REPLACE --cache-control "max-age=0,no-cache,no-store,must-revalidate" ${BUILD_PATH}/${APP_NAME}.remoteEntry.js s3://$AWS_STAGE_DASHBOARD_ASSETS_CDN_BUCKET/dashboard/federated-bundles/${APP_NAME}/${BUILD_PATH}/${APP_NAME}.remoteEntry.js
          aws s3 cp --metadata-directive REPLACE --cache-control "max-age=0,no-cache,no-store,must-revalidate" ${BUILD_PATH}/${APP_NAME}.remoteEntry.js.map s3://$AWS_STAGE_DASHBOARD_ASSETS_CDN_BUCKET/dashboard/federated-bundles/${APP_NAME}/${BUILD_PATH}/${APP_NAME}.remoteEntry.js.map
          aws s3 cp --metadata-directive REPLACE --cache-control "max-age=0,no-cache,no-store,must-revalidate" ${BUILD_PATH}/${APP_NAME}.remoteEntry.js.gz s3://$AWS_STAGE_DASHBOARD_ASSETS_CDN_BUCKET/dashboard/federated-bundles/${APP_NAME}/${BUILD_PATH}/${APP_NAME}.remoteEntry.js.gz

          # Sync whole folder to S3 excluding above assets
          aws s3 sync --cache-control "public,max-age=31536000" ${BUILD_PATH} s3://$AWS_STAGE_DASHBOARD_ASSETS_CDN_BUCKET/dashboard/federated-bundles/${APP_NAME}/$BUILD_PATH --exclude ${BUILD_PATH}/${APP_NAME}.remoteEntry.js --exclude ${BUILD_PATH}/${APP_NAME}.remoteEntry.js.map --exclude ${BUILD_PATH}/${APP_NAME}.remoteEntry.js.gz
  
  production-dashboard-mfes-deploy:
    name: Production Deploy - Dashboard MFEs
    runs-on: self-hosted
    timeout-minutes: 30
    if: |
      github.event.deployment.environment == 'production' &&
      github.event.deployment.payload.deploymentModule == 'mfe'
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.AWS_S3_PROD_ROLE }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Download Automation Build from S3 Cache
        run: |
          aws s3 cp s3://${AWS_PROD_COMMON_CACHE_BUCKET}/dashboard/federated-bundles/${APP_NAME}/production/${VERSION} ./ --recursive

      - name: Deploy to Production
        run: |
          # Sync entry remote files which need to be deployed without caching
          aws s3 cp --metadata-directive REPLACE --cache-control "max-age=0,no-cache,no-store,must-revalidate" ${BUILD_PATH}/${APP_NAME}.remoteEntry.js s3://$AWS_PROD_DASHBOARD_ASSETS_CDN_BUCKET/dashboard/federated-bundles/${APP_NAME}/${BUILD_PATH}/${APP_NAME}.remoteEntry.js
          aws s3 cp --metadata-directive REPLACE --cache-control "max-age=0,no-cache,no-store,must-revalidate" ${BUILD_PATH}/${APP_NAME}.remoteEntry.js.map s3://$AWS_PROD_DASHBOARD_ASSETS_CDN_BUCKET/dashboard/federated-bundles/${APP_NAME}/${BUILD_PATH}/${APP_NAME}.remoteEntry.js.map
          aws s3 cp --metadata-directive REPLACE --cache-control "max-age=0,no-cache,no-store,must-revalidate" ${BUILD_PATH}/${APP_NAME}.remoteEntry.js.gz s3://$AWS_PROD_DASHBOARD_ASSETS_CDN_BUCKET/dashboard/federated-bundles/${APP_NAME}/${BUILD_PATH}/${APP_NAME}.remoteEntry.js.gz

          # Sync whole folder to S3 excluding above assets
          aws s3 sync --cache-control "public,max-age=31536000" ${BUILD_PATH} s3://$AWS_PROD_DASHBOARD_ASSETS_CDN_BUCKET/dashboard/federated-bundles/${APP_NAME}/$BUILD_PATH --exclude ${BUILD_PATH}/${APP_NAME}.remoteEntry.js --exclude ${BUILD_PATH}/${APP_NAME}.remoteEntry.js.map --exclude ${BUILD_PATH}/${APP_NAME}.remoteEntry.js.gz
