name: E2E Tests
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  push:
    branches:
      - master

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  APP_NAME: dashboard
  HOME: /actions-runner/_work
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.HARBOR_DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
  DOCKER_REGISTRY: c.rzp.io
  ARGO_TOKEN: ${{ secrets.ARGO_TOKEN }}
  ImageOS: ubuntu20

jobs:
  build-fe-e2e:
    name: Run E2E Tests on PR Comment or on master merge
    if: |
      (!!(github.event.pull_request) && contains(github.event.pull_request.labels.*.name, 'pr-ready-for-e2e')) ||
      (github.ref == 'refs/heads/master')
    timeout-minutes: 60
    runs-on: [non-api-premium]
    outputs:
      affected: ${{ steps.set-affected-output.outputs.affected }}
      commit_id: ${{ steps.set-commit-id.outputs.commit_id }}
    steps:
      - name: Set Commit ID on PR
        if: ${{ !!(github.event.pull_request) && contains(github.event.pull_request.labels.*.name, 'pr-ready-for-e2e') }}
        run: |
          echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
        env:
          COMMIT_ID: ${{ github.event.pull_request.head.sha }}

      - name: Set Commit ID if its on master
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
        env:
          COMMIT_ID: ${{ github.sha }}

      - name: Echo COMMIT_ID for changes
        run: |
          echo "COMMIT_ID: ${{ env.COMMIT_ID }}"

      - name: Set COMMIT_ID in Output
        id: set-commit-id
        run: echo "::set-output name=commit_id::${{ env.COMMIT_ID }}"

      - name: Preparing Workflow Link
        id: e2e_github_workflow_action
        run: |
          echo "::set-output name=workflow_link::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Post workflow initiation notification
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          message: |
            `Frontend E2E Workflow docker build started` [Visit ongoing action](${{ steps.e2e_github_workflow_action.outputs.workflow_link }})
          allow-repeats: true

      # fetching with depth 0 to find detached head ref
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          ref: ${{ env.COMMIT_ID }}
          fetch-depth: 0

      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Fetch base branch
        run: |
          git fetch origin master

      - name: Setup pnpm and yarn
        run: |
          npm install -g pnpm@~9.0
          npm install -g yarn

      - name: Install dependencies
        run: |
          pnpm config set unsafe-perm true
          HUSKY=0 pnpm i --ignore-scripts
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      # TODO: optimize the below step to install depecndencies which are required for nx
      # - name: Install dependencies with caching
      #   uses: ./.github/actions/package-installer
      #   with:
      #     github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Extract current branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Validating branch existance
        run: git fetch origin ${{ steps.extract_branch.outputs.branch }}

      - name: Identify Affected Projects
        id: affected
        run: |
          echo "AFFECTED=$(npx nx show projects --affected --json --base=origin/master --head=origin/${{ steps.extract_branch.outputs.branch }} | jq -r 'join(",")')" >> $GITHUB_ENV

      - name: Echo Affected Projects
        run: echo ${{ env.AFFECTED }}

      - name: Check for changes in specified directories
        id: check_changes
        if: ${{ !contains(env.AFFECTED, 'web') }}
        run: |
          # Get Base commit
          base_commit=$(git merge-base origin/master origin/${{ steps.extract_branch.outputs.branch }})

          # Get a list of changed files
          changed_files=$(git diff --name-only $base_commit origin/${{ steps.extract_branch.outputs.branch }})

          # Check if any of the changed files are in the directories you're interested in
          if echo "$changed_files" | grep -qE "^app/|^config/|^environment/|^[^/]*$"
          then
            echo "There are changes in the specified files and directories."
            echo "::set-output name=changes::true"
          else
            echo "There are no changes in the specified files and directories."
            echo "::set-output name=changes::false"
          fi

      - name: Set Affected Projects Output
        id: set-affected-output
        run: |
          if [ "${{ steps.check_changes.outputs.changes }}" == "true" ]; then
            echo "::set-output name=affected::${{ env.AFFECTED }},web"
          else
            echo "::set-output name=affected::${{ env.AFFECTED }}"
          fi

      - name: Echo Affected Projects after final changes
        run: |
          echo "Affected projects: ${{ steps.set-affected-output.outputs.affected }}"

      # - name: Update package dependencies for docker build
      #   id: update-config
      #   run: pnpm run updateE2EDependencies

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{env.DOCKER_REGISTRY}}/razorpay/${{env.APP_NAME}}_fe_e2e:${{ env.COMMIT_ID }}
          push: true
          file: ./Dockerfile.e2e
          secrets: |
            github_access_token=${{env.GITHUB_ACCESS_TOKEN}}
          build-args: |
            APP_NAME=${{env.APP_NAME}}
            AFFFECTED_PROJECTS=${{ steps.set-affected-output.outputs.affected }}
            #  TODO: Add project level INCLUDE_GROUPS and EXCLUDE_GROUPS as key value pairs and extract them to pass in playwright getproject config
            INCLUDE_GROUPS=@project=payments|@project=partner-dashboard|@project=no-code-stable|@project=offers
            EXCLUDE_GROUPS=
            CI=true

  trigger-fe-e2e-webhook:
    name: Fire FE E2E Webhook
    runs-on: [self-hosted]
    needs: [build-fe-e2e]
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Setup pnpm and yarn
        run: |
          npm install -g pnpm@~9.0
          npm install -g yarn

      - name: Echo Commit ID
        run: echo "Commit ID is ${{ needs.build-fe-e2e.outputs.commit_id }}"

      - name: Echo Affected Projects
        run: echo "Affected projects => ${{ needs.build-fe-e2e.outputs.affected }}"

      # TODO: optimize the below step to install depecndencies which are required for nx
      # - name: Install dependencies with caching
      #   uses: ./.github/actions/package-installer
      #   with:
      #     github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Wait for dashboard's docker image to be built
        uses: ./.github/actions/waiting-build
        with:
          commit_id: ${{ needs.build-fe-e2e.outputs.commit_id }}
          workflow_name: "Run E2E Tests on PR Comment or on master merge"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update downstream dependencies' commits in devstack.json
        # If this steps fails, it's because one of the endpoints in addProdCommits.js threw an error.
        timeout-minutes: 2
        run: npm run add-prod-commits

      - name: Initiate E2E Tests via an argo webhook
        run: npm run test:e2e-infra
        env:
          COMMIT_ID: ${{ needs.build-fe-e2e.outputs.commit_id }}
          PR_NUMBER: ${{ github.event.issue.number }}
          REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_HEAD_REF: ${{ steps.extract_branch.outputs.branch }}
          AFFECTED_PROJECTS: ${{ needs.build-fe-e2e.outputs.affected }}
          # Required DEVSTACK_CONFIG_PATH, After upgarding universe test version which supports devstack config path
          # DEVSTACK_CONFIG_PATH: ./e2e/devstackConfig/devstack.json
          JOB_URL: "https://argo.dev.razorpay.in/api/v1/events/argo-workflows/dashboard-fe-e2e"
