# This workflow will run tests playwright

name: End to End testing

on:
  push:
    branches: feature/e2e

jobs:
  build:
    runs-on: [self-hosted]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.18.2"
    # Set up GitHub Actions to run cross-browser tests on Chromium, WebKit and Firefox with Playwright
    #   - uses: microsoft/playwright-github-action@v1
    # This action allows caching dependencies and build outputs to improve workflow execution time
    #   - uses: actions/cache@v1
    #     with:
    #       path: ~/.npm
    #       key: $\{{ runner.os }}-node-$\{{ hashFiles('**/package-lock.json') }}
    #       restore-keys: |
    #           $\{{ runner.os }}-node-
      - run: npm install -g yarn
      - run: npm config set unsafe-perm true && npm config set cache npm_cache && npm ci --verbose # Automatically installs npm ci in web
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      - run: npm run build:e2e
        continue-on-error: true
        env:
            NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
            GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      - run: npm run test:e2e
        continue-on-error: true
        env:
            NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
            GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
