name: Format Checker Workflow
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  validate:
    runs-on: [non-api, linux-amd64]
    continue-on-error: false
    name: Format Checker
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Setup pnpm and yarn
        run: |
          npm install -g pnpm@~9.0
          npm install -g yarn

      - name: Install dependencies
        run: |
          pnpm config set unsafe-perm true
          HUSKY=0 pnpm i --ignore-scripts
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: Get changed Stylus files
        id: changed-stylus-files
        uses: tj-actions/changed-files@v44.5.5
        with:
          files: |
            **/*.styl
          path: web
          diff_relative: true

      - name: Stylelint PR Check
        id: stylelint-check
        continue-on-error: true
        # Don't run check on revert PRs
        if: |
          !(
            startsWith(steps.branch-name.outputs.current_branch, 'revert-') ||
            startsWith(steps.branch-name.outputs.current_branch, 'skiplint-')
          ) &&
          steps.changed-stylus-files.outputs.all_changed_files != ''
        run: |
          echo 'PR Branch: ${{ steps.branch-name.outputs.current_branch }}'
          pnpm lint:stylelint \
          --custom-formatter ../stylelint-formatter.js \
          -o ../stylelint-report.json \
          ${{ steps.changed-stylus-files.outputs.all_changed_files }}
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: Annotate Stylus Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        id: stylus-annotator
        # Don't run check on revert PRs
        if: |
          !(
            startsWith(steps.branch-name.outputs.current_branch, 'revert-') ||
            startsWith(steps.branch-name.outputs.current_branch, 'skiplint-')
          ) &&
          steps.changed-stylus-files.outputs.all_changed_files != ''
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "stylelint-report.json"
          check-name: "Stylelint Analysis"

      - name: Comment Stylus document link
        uses: marocchino/sticky-pull-request-comment@v2
        if: always() && failure() && steps.stylus-annotator.conclusion == 'failure'
        with:
          recreate: true
          message: Found Stylelint CSS Errors - Refer to [Stylelint Document](https://docs.google.com/document/d/1IC_vWC9EePW6Tnilufg6jQvYgOOs0FyccXM4NmZuEHg/edit)
