name: Format Checker Workflow

on: pull_request

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  validate:
    runs-on: [self-hosted]
    continue-on-error: false
    name: Format Checker
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: |
          npm config set unsafe-perm true
          npm ci # Automatically installs npm ci in web too
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: DangerJS
        uses: danger/danger-js@10.6.6
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: 'true'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v9.3
        with:
          files: |
            .(js|json|jsx|ts|tsx)$

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: ESLint PR Check
        # Don't run check on revert PRs
        if: ${{ !startsWith(steps.branch-name.outputs.current_branch, 'revert-') }}
        run: |
          echo 'PR Branch: ${{ steps.branch-name.outputs.current_branch }}'
          npm ci
          base=$base npm run validate-lint
          npx eslint \
          --ext .js,.jsx,.ts,.tsx \
          ${{ steps.changed-files.outputs.all_modified_files }}
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          base: origin/${{ github.base_ref }}
