name: Format Checker Workflow

on:
  pull_request:
    types:
      [
        edited,
        opened,
        synchronize,
        reopened,
        assigned,
        labeled,
        review_requested,
      ]

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  validate:
    runs-on: [self-hosted]
    continue-on-error: false
    name: Format Checker
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: |
          yarn config set unsafe-perm true
          yarn --frozen-lockfile # Automatically installs modules in web too
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: DangerJS
        uses: danger/danger-js@10.6.6
        with:
          args: "--id formatchecker_dangerjs"
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: "true"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v9.3
        with:
          files: |
            .(js|json|jsx|ts|tsx)$

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: ESLint PR Check
        # Don't run check on revert PRs
        if: |
          !(
            startsWith(steps.branch-name.outputs.current_branch, 'revert-') ||
            startsWith(steps.branch-name.outputs.current_branch, 'skiplint-')
          )
        run: |
          echo 'PR Branch: ${{ steps.branch-name.outputs.current_branch }}'
          base=$base yarn validate-lint
          npx eslint \
          --output-file eslint_report.json \
          --no-error-on-unmatched-pattern \
          --format json \
          --ext .js,.jsx,.ts,.tsx \
          ${{ steps.changed-files.outputs.all_modified_files }}
        continue-on-error: true
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          base: origin/${{ github.base_ref }}

      - name: Annotate ES lint issues
        uses: ataylorme/eslint-annotate-action@v2
        id: eslint-annotator
        # skip test for revert pr's
        if: |
          !(
            startsWith(steps.branch-name.outputs.current_branch, 'revert-') ||
            startsWith(steps.branch-name.outputs.current_branch, 'skiplint-')
          )
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
          check-name: "Eslint Report"

      - name: Get changed Stylus files
        id: changed-stylus-files
        uses: tj-actions/changed-files@v9.3
        with:
          files: |
            .(styl)$

      - name: Stylelint PR Check
        id: stylelint-check
        continue-on-error: true
        # Don't run check on revert PRs
        if: |
          !(
            startsWith(steps.branch-name.outputs.current_branch, 'revert-') ||
            startsWith(steps.branch-name.outputs.current_branch, 'skiplint-')
          ) &&
          steps.changed-stylus-files.outputs.all_modified_files != ''
        run: |
          echo 'PR Branch: ${{ steps.branch-name.outputs.current_branch }}'
          npx stylelint \
          --custom-formatter stylelint-formatter.js \
          --config .stylelintrc-stylus.js \
          -o stylelint-report.json \
          ${{ steps.changed-stylus-files.outputs.all_modified_files }}
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: Annotate Stylus Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        id: stylus-annotator
        # Don't run check on revert PRs
        if: |
          !(
            startsWith(steps.branch-name.outputs.current_branch, 'revert-') ||
            startsWith(steps.branch-name.outputs.current_branch, 'skiplint-')
          ) &&
          steps.changed-stylus-files.outputs.all_modified_files != ''
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "stylelint-report.json"
          check-name: "Stylelint Analysis"

      - name: Comment Stylus document link
        uses: marocchino/sticky-pull-request-comment@v2
        if: always() && failure() && steps.stylus-annotator.conclusion == 'failure'
        with:
          recreate: true
          message: Found Stylelint CSS Errors - Refer to [Stylelint Document](https://docs.google.com/document/d/1IC_vWC9EePW6Tnilufg6jQvYgOOs0FyccXM4NmZuEHg/edit)
