name: "Jest Analysis"

on: [pull_request]

# Uncomment below code once we are ready to run coverage on master
# on:
#   pull_request:
#     branches:
#       - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  APP_NAME: dashboard
  HOME: /actions-runner/_work

jobs:
  coverage:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Install libraries for webp conversion
        run: |
          apt-get update && apt-get install -y libjpeg-dev libpng-dev libtiff-dev libgif-dev

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies with caching
        uses: ./.github/actions/package-installer
        with:
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Code coverage
        id: coverage
        uses: artiomtr/jest-coverage-report-action@v2.1.2
        env:
          DISABLE_REPORT_PORTAL_INTEGRATION: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: yarn test:jest:ci
          working-directory: web # directory where report is getting generated
          skip-step: install # skip npm install step
