name: PHP Syntax Validator
on:
  pull_request:
    branches:
      - master

jobs:
  validate_php_syntax:
    name: Validate PHP Syntax
    runs-on: [ self-hosted ]
    container:
      image: c.rzp.io/razorpay/onggi_testing:php81-fpm-nginxphp-8.1-nginx
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      volumes:
        - /etc/hosts:/etc/hosts
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Action
        run: |
          find -path /dashboard -prune -o -type f -iname '*.php' | xargs -n 1 php -l
