name: Backmerge Master and Trigger Roast On PR Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  pull_request_approved:
    env:
      commit_id: ${{ github.event.pull_request.head.sha }}
    # Trigger back-merge master when PR is approved and feature branch isn't hotfix branch
    if: github.event.review.state == 'approved' && !contains(github.event.pull_request.head.ref, 'hotfix') && !contains(github.event.pull_request.head.ref, 'revert-')
    runs-on: [self-hosted]
    steps:
    - name: checkout
      uses: razorpay/checkout-action@08eef2bd6ada50786812e7351457a762856a532f
     # Applying label approved here to use the same in other workflow - pr_workflow to run the back-merge action when
     # any commits pushed post PR approval
    - name: Apply approved label
      uses: actions/github-script@v3
      with:
        github_token: ${{ github.token }}
        script: |
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            labels: ['approved']
          })
    - name: Print Base branch
      run: echo ${{ github.event.pull_request.base.ref }}
    # Back-merge master branch into feature post PR approval check
    - name: backmerge-master
      id: backmerge
      uses: devmasx/merge-branch@a1752b9ba42bb417ec19be7dc974e2faf77d3ef2
      with:
        type: now
        from_branch: ${{ github.event.pull_request.base.ref }}
        target_branch: ${{ github.event.pull_request.head.ref }}
        github_token: ${{ secrets.CI_BOT_TOKEN }}
    # If Backmerge failed, then comment in PR to resolve manually
    - name: Comments
      if: ${{failure()}}
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        message: |
          **Conflict Error Please back-merge manually**
        allow-repeats: true
    # checkout the festure branch post back-merge of master
    - uses: razorpay/checkout-action@08eef2bd6ada50786812e7351457a762856a532f
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    # set the new commit id in Github env
    - name: Set New commit Id in Github env post backmerge
      id: new_commit
      run: echo "GIT_NEW_COMMIT_AFTER_MERGE=$(git rev-parse --verify HEAD)" >> $GITHUB_ENV
    # Get the API Instance from Spinnaker
    - name: Get API Instance from Spinnaker
      env:
        GIT_TOKEN :  ${{ secrets.CI_BOT_TOKEN }}
      id: script
      run: |
        echo "API_INSTANCE=$(sh ./.github/actions/getSpinnakerConfig.sh)" >> $GITHUB_ENV
    - name: Print Instance value
      run: echo $API_INSTANCE
    - if: contains(github.event.pull_request.head.ref, 'hotfix')
      name: Set flag
      id: hotfix
      run: echo "::set-output name=flag::true"
    - if: contains(github.event.pull_request.head.ref, 'revert-')
      name: Set flag
      id: revert
      run: echo "::set-output name=flag::true"
     # Validate existence of Roast PR NUmber Field
    - name: Validate existence of roastPRNumber Field
      uses: actions/github-script@0.9.0
      id: roast-pr-number
      with:
        result-encoding: string
        script: |
                const regex = /roastprnumber.*/i;
                roastPRNumberFlag = regex.test(context.payload.pull_request.body.toLowerCase())
                return Boolean(roastPRNumberFlag)
      # Fetch PR Number for Roast mentioned in description
    - name: Fetch PR Number for Roast
      uses: actions/github-script@0.9.0
      if: ${{steps.roast-pr-number.outputs.result == 'true'}}
      id: roastPRNumber
      with:
        result-encoding: string
        script: |
          roastPRNumberStr = context.payload.pull_request.body.toLowerCase()
          var roastPRNumberValue = (roastPRNumberStr.substring(roastPRNumberStr.indexOf("roastprnumber"))).split("\n")
          var prNumber = roastPRNumberValue[0].substring(16)
          return prNumber
    - name: Print PR Number
      run: echo ${{ steps.roastPRNumber.outputs.result }}
      # Get Roast PR State if its approved or not
    - name: Run Roast API PR flow if value is not null
      id: get_pr_state
      if: ${{steps.roastPRNumber.outputs.result != null }}
      uses: actions/github-script@v3.1.0
      with:
        result-encoding: string
        github-token: ${{ secrets.CI_BOT_TOKEN }}
        script: |
          pullnumber = parseInt(${{steps.roastPRNumber.outputs.result}})
          const result = await github.pulls.listReviews({
            owner: context.payload.repository.owner.login,
            repo: 'roast',
            pull_number: pullnumber,
            per_page: 100
          })
          const prState = result.data.filter(f => f.state.toLowerCase().includes("approved")).length > 0
          return Boolean(prState)
      # Get Target Branch for Roast Repo
    - name: Get Roast Branch for PR
      id: roast-branch
      if: |
        steps.roastPRNumber.outputs.result != null  && steps.get_pr_state.outputs.result == 'true'
      uses: actions/github-script@v2
      with:
        result-encoding: string
        github-token: ${{ secrets.CI_BOT_TOKEN }}
        script: |
          const response = await github.pulls.get({
            owner: context.payload.repository.owner.login,
            repo: 'roast',
            pull_number: ${{steps.roastPRNumber.outputs.result}},
          })
          const roastBranch = response.data.head.ref
          return String(roastBranch)
      # Rebase Master to a roast branch in Roast Repo
    - name: Rebase master to a branch
      id: rebase-branch
      if: |
        steps.roastPRNumber.outputs.result != null  && steps.get_pr_state.outputs.result == 'true'
      uses: linhbn123/rebase-pull-requests@v1.0.1
      with:
        repository: 'razorpay/roast'
        head: 'razorpay:${{ steps.roast-branch.outputs.result }}'
        base: 'master'
        token: ${{ secrets.CI_BOT_TOKEN }}
    - name: Comments
      if: ${{failure()}}
      uses: mshick/add-pr-comment@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        message: |
          **Conflict Error Please rebase manually**
          allow-repeats: true
      # Fetch the latest commit of the Roast Repo
    - name: Fetch latest Commit of the PR in Roast after rebase
      id: latest-commit
      if: |
        steps.roastPRNumber.outputs.result != null  && steps.get_pr_state.outputs.result == 'true'
      uses: actions/github-script@v3
      with:
        result-encoding: string
        github-token: ${{ secrets.CI_BOT_TOKEN }}
        script: |
          const response = await github.pulls.get({
            owner: context.payload.repository.owner.login,
            repo: 'roast',
            pull_number: ${{steps.roastPRNumber.outputs.result}},
            })
            const latestCommit = response.data.head.sha
            return String(latestCommit)
      # Fetch SkipRoastByDev mentioned in description
    - name: Fetch SkipRoastbyDev
      uses: actions/github-script@0.9.0
      id: skipRoastByDev
      with:
        result-encoding: string
        script: |
          skipRoastByDevStr = context.payload.pull_request.body.toLowerCase()
          var skipRoastByDevValueRow = (skipRoastByDevStr.substring(skipRoastByDevStr.indexOf("skiproastbydev"))).split("\n")
          var skipRoastByDevValue = skipRoastByDevValueRow[0].split("|")
          var skipRoastByDev = skipRoastByDevValue[1].split("-")
          var skipRoastByDevFlag = skipRoastByDev[0].trim()
          console.log(skipRoastByDevFlag)
          return skipRoastByDevFlag
    - name: Check For Only Ignore Files
      id: only-ignore-files
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "ONLY_IGNORE_FILES=$(sh ./.github/actions/checkIfPRHasOnlyIgnoreFiles.sh)" >> $GITHUB_ENV
    - name: Run bvt suite if PR submitted as approved
      # checking if the commit_id post backmerge is same then run BVT on it. Otherwise it invoke PR_workflow and run BVT
      if: env.GIT_NEW_COMMIT_AFTER_MERGE == env.commit_id && startsWith(github.event.pull_request.head.ref,'beta_') != true
      env:
        SPINNAKER_PASSWORD: ${{ secrets.SPINNAKER_PASSWORD }}
        WEBHOOK_TRIGGER : api-spin-sleeve
        GITHUB_TOKEN: ${{ github.token }}
        HOTFIX: ${{ steps.hotfix.outputs.flag }}
        REVERT: ${{ steps.revert.outputs.flag }}
        ONLY_IGNORE_FILES: ${{ env.ONLY_IGNORE_FILES }}
        ROAST_PR_COMMIT: ${{steps.latest-commit.outputs.result}}
        SKIP_ROAST_BY_DEV: ${{steps.skipRoastByDev.outputs.result}}
        GIT_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      run: |
        sh ./.github/actions/triggerBvtSuite.sh
