name: PR Workflow

on:
  [pull_request]

jobs:
  pull_request: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run bvt suite if PR approved
      env:
        SPINNAKER_PASSWORD: ${{ secrets.SPINNAKER_PASSWORD }}
        WEBHOOK_TRIGGER : api
        GITHUB_TOKEN:  ${{ github.token }}
      run: |
        sh ./.github/actions/triggerBvtSuite.sh