name: Release
on:
  push:
    branches:
      - master

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
  HOME: /actions-runner/_work
  CI: true

jobs:
  version:
    name: Release Packages
    runs-on: self-hosted
    timeout-minutes: 30
    if: ${{ github.event.head_commit.author.name != 'rzpcibot'}}
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Install dependencies with caching
        uses: ./.github/actions/package-installer
        with:
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Create Version Update Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
        with:
          version: pnpm version-update
          commit: "Nx build: update version"
          title: "Nx build: update version"

  create-release:
    name: Create Release
    runs-on: self-hosted
    timeout-minutes: 30
    if: "${{ contains(github.event.head_commit.message, 'Nx build: update version') && github.event.head_commit.author.name == 'rzpcibot' }}"
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Install dependencies with caching
        uses: ./.github/actions/package-installer
        with:
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Run release script
        run: pnpm exec universe release --with-changesets
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
