name: Reset Dark Branch

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # Allows manual trigger

jobs:
  reset-dark:
    runs-on:
      - api-public
      - X64

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Reset dark branch to master
        run: |
          git fetch origin
          git checkout dark
          git reset --hard origin/master
          git push origin dark --force
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

