on:
  pull_request:
    branches:
      - master
env:
  UPDATED: false

jobs:
  cancel:
    runs-on: [ api-micro-arm ]
    name: Cancel Previous Runs
    if: always()
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        if: github.ref != 'refs/heads/master'
        name: cancel old workflows
        id: cancel
        with:
          all_but_latest: true
          workflow_id: "secret_change.yml"
          access_token: ${{ github.token }}
      - if: github.ref == 'refs/heads/master'
        name: Don't cancel old workflows
        id: dont_cancel
        run: |
          echo "Don't cancel old workflow"
  # workflow if env.vault.j2 file edited and deploying it if file is altered
  changed_files:
    runs-on: [ self-hosted ]
    name: Test changed-files
    needs: [cancel]
    steps:
      - name: Retrieve  Current Workflow URL
        id: workflow_run
        run: echo "::set-output name=url::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Post Workflow Link as Comment
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          message: |
            `Verifying the recent modification of the vault/j2 file in the current branch:`  [View the progress here](${{ steps.workflow_run.outputs.url }})
          allow-repeats: true
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: change in env files
        run: |
          updated=false
          for changed_file in ${{ steps.files.outputs.all }}; do
             if [ "${changed_file}" == "environment/.env.vault.j2" ]; then
              updated=true
              echo "UPDATED=true" >> "$GITHUB_ENV"
              echo "Found change in .env.vault.j2."
             fi
          done
          if [ "$updated" != true ]; then
            echo "Found no change in .env.vault.j2."
          fi
      - name: Check UPDATED status
        run: echo $UPDATED
      - name: await-status-action
        if: env.UPDATED == 'true'
        uses: Sibz/await-status-action@v1.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          contexts: 'Build Web Harbor'
          authToken: ${{ secrets.GIT_TOKEN }}
          timeout: 1800
          notPresentTimeout: 1200
      - name: Post Workflow Comment
        if: env.UPDATED == 'true'
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          message: |
            `Detected modifications in the vault file and currently evaluating the build's stability by deploying it in devstack using Argo`
          allow-repeats: true
      - name: Triggers argo-workflow's webhook to execute start devstack deployment
        if: env.UPDATED == 'true'
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://argo.dev.razorpay.in/api/v1/events/argo-workflows/deploy-to-devstack-on-pr-api"
          bearerToken: ${{ secrets.ARGO_TOKEN }}
          method: "POST"
          data: >
            {  "kube_manifests_ref": "master",
               "self": {
                     "name": "api",
                     "commit_id": "${{ github.event.pull_request.head.sha }}",
                     "repository_name" : "razorpay/api",
                     "pr_number" : "${{ github.event.number }}",
                     "chart_values": {
                       "app_mode": "bvt",
                       "base_env": "bvt",
                       "db1_custom_seeding": false,
                       "environment": "bvt",
                       "ephemeral_db": false,
                       "node_selector": "node.kubernetes.io/worker-bvt-devstack",
                       "replicas": 1,
                        "ttl": "10m",
                       "replicas_kafka": 0,
                       "router_e2e": true,
                       "run_e2e_test_suite_on_devstack": true,
                       "serviceAccount": "api-bvt-service-account",
                       "serviceAccountName": "api-bvt-service-account",
                       "web_requests_cpu": "500m",
                       "web_requests_memory": "1000Mi"
                     }
               },
               "dependencies": []
            }
