name: "Sonar Code Coverage PR Analysis"

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  APP_NAME: dashboard
  HOME: /actions-runner/_work

jobs:
  coverage:
    runs-on: self-hosted
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Install libraries for webp conversion
        run: |
          apt-get update && apt-get install -y libjpeg-dev libpng-dev libtiff-dev libgif-dev

      - name: Setup pnpm and yarn
        run: |
          npm install -g pnpm@^9
          npm install -g yarn

      - name: Install dependencies
        run: |
          pnpm config set unsafe-perm true
          HUSKY=0 pnpm i --ignore-scripts
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      # - name: Install dependencies with caching
      #   uses: ./.github/actions/package-installer
      #   with:
      #     github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Test Codebase
        run: |
          pnpm test
          pnpm test:jest
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          DISABLE_REPORT_PORTAL_INTEGRATION: true

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v9.3
        with:
          files: |
            .(js|jsx|ts|tsx)$

      - name: Run Eslint for files
        continue-on-error: true
        run: |
          npx eslint \
            --output-file eslint_report.json \
            --no-error-on-unmatched-pattern \
            --format ./sonarqube_formatter.js \
            ${{ steps.changed-files.outputs.all_modified_files }}

      - name: Run SonarQube PR analysis on Dev Project
        id: pr_sonarqube_analysis
        uses: sonarsource/sonarcloud-github-action@v1.6
        if: ${{ github.ref != 'refs/heads/master' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARCLOUD_URL: ${{ secrets.SONARQUBE_HOST }}
        with:
          args: >
            -Dsonar.projectKey=DashboardDev
            -Dsonar.projectName=DashboardDev
            -Dsonar.projectVersion=${{ github.sha }}

      # Perform code coverage check on PR changes vs master
      - name: PR code coverage check
        id: pr-code-coverage-check
        if: ${{ github.ref != 'refs/heads/master' }}
        run: ./scripts/sonar-analysis.sh
        continue-on-error: true
        env:
          SONAR_HOST: ${{ secrets.SONARQUBE_HOST }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          PROJECT_KEY_DEV: DashboardDev
          PROJECT_KEY_PROD: dashboard
          FILE_NAME: comment-dashboard.txt
          FILE_HEADING: "Sonar Analysis Report"

      # Perform code coverage check for partner dashboard on PR changes vs master
      - name: PR code coverage check for partner dashboard
        id: pr-code-coverage-check-partner-dashboard
        if: ${{ github.ref != 'refs/heads/master' && contains( github.event.pull_request.labels.*.name, 'partnership') }}
        run: ./scripts/sonar-analysis.sh
        continue-on-error: true
        env:
          SONAR_HOST: ${{ secrets.SONARQUBE_HOST }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          PROJECT_KEY_DEV: DashboardDev:web/js/merchant/views/PartnerDashboard
          PROJECT_KEY_PROD: dashboard:web/js/merchant/views/PartnerDashboard
          FILE_NAME: comment-partner-dashboard.txt
          FILE_HEADING: Sonar Analysis Report for Partner Dashboard

      - name: Update Sonar Analysis Comment
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          header: dashboard_analysis
          path: comment-dashboard.txt

      - name: Update Sonar Analysis Comment for Partner Dashboard
        if: ${{ github.ref != 'refs/heads/master' && contains( github.event.pull_request.labels.*.name, 'partnership') }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          header: partner_dashboard_analysis
          path: comment-partner-dashboard.txt
