name: Sonar Scanner
on:
  push:
    branches:
      - master
jobs:
  sonar:
    name: Sonar Scanner
    runs-on: [self-hosted]
    continue-on-error: false
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Use Node v16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      # This action allows caching dependencies and build outputs
      # to improve workflow execution time
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}


      - name: Install Dependencies
        run: |
          npm config set unsafe-perm true
          npm ci # Automatically installs npm ci in web too
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: Test Codebase
        # Automatically installs npm ci in web too
        run: |
          npm run test
          npm run test:jest
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.1.0
        with:
          host: https://sonar.razorpay.com
          login: ${{ secrets.SONARQUBE_TOKEN }}

