name: Sonar Scanner Upload Master Code Coverage
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: merchant-dashboard
  HOME: /actions-runner/_work
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
jobs:
  sonar:
    name: Sonar Scanner
    runs-on: [self-hosted]
    continue-on-error: true
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Install libraries for webp conversion
        run: |
          apt-get update && apt-get install -y libjpeg-dev libpng-dev libtiff-dev libgif-dev

      - name: Setup pnpm and yarn
        run: |
          npm install -g pnpm@~9.0
          npm install -g yarn

      - name: Install dependencies
        run: |
          pnpm config set unsafe-perm true
          HUSKY=0 pnpm i --ignore-scripts
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      # - name: Install dependencies with caching
      #   uses: ./.github/actions/package-installer
      #   with:
      #     github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Fetch Branch Name
        id: fetch-branch-name
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Run Test Cases
        # Automatically installs npm ci in web too
        run: |
          pnpm test
          pnpm test:jest
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          REPORT_PORTAL_TOKEN: ${{ secrets.REPORT_PORTAL_TOKEN }}
          REPORT_PORTAL_HOST: ${{ secrets.REPORT_PORTAL_HOST }}
          REPORT_PORTAL_PROJECT: ${{ secrets.REPORT_PORTAL_PROJECT }}
          COMMIT_ID: ${{ github.sha }}
          REPORT_PORTAL_LAUNCH_NAME: "Dashboard UTs-${{ steps.fetch-branch-name.outputs.branch_name }}"
          DISABLE_REPORT_PORTAL_INTEGRATION: true

      - name: Run Eslint for files
        run: |
          npx eslint \
          --output-file eslint_report.json \
          --format ./sonarqube_formatter.js \
          web/js apps libs
        continue-on-error: true

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
            -Dsonar.projectVersion=${{ github.sha }}
