name: Test Workflow
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: [cache-3]
    continue-on-error: false
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies with caching
        uses: ./.github/actions
        with:
          npm_razorpay_token: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Test Codebase
        # Automatically installs npm ci in web too
        run: |
          yarn test
          yarn test:jest
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
