name: Unit Tests Workflow
on:
  push:
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  REPORT_PORTAL_TOKEN: ${{ secrets.REPORT_PORTAL_TOKEN }}
  REPORT_PORTAL_HOST: ${{ secrets.REPORT_PORTAL_HOST }}
  REPORT_PORTAL_PROJECT: ${{ secrets.REPORT_PORTAL_PROJECT }}

jobs:
  test:
    name: Test
    runs-on: [cache-3]
    continue-on-error: false
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Get Docker Info
        run: |
          docker info

      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies with caching
        uses: ./.github/actions/package-installer
        with:
          github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Fetch base branch
        run: |
          git fetch origin master

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Test Codebase
        # Automatically installs npm ci in web too
        run: |
          yarn nx affected -t test:jest --silent --base=origin/master --head=${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          REPORT_PORTAL_TOKEN: ${{ secrets.REPORT_PORTAL_TOKEN }}
          REPORT_PORTAL_HOST: ${{ secrets.REPORT_PORTAL_HOST }}
          REPORT_PORTAL_PROJECT: ${{ secrets.REPORT_PORTAL_PROJECT }}
          COMMIT_ID: ${{ github.sha }}
          REPORT_PORTAL_LAUNCH_NAME: "Dashboard UTs-${{ steps.extract_branch.outputs.branch }}"
