name: Track Bundle Limit Threshold

on:
  pull_request:
    branches:
      - master
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  asset-checker:
    if: github.event.pull_request.merged == true
    name: Track Bundle Asset Checker
    runs-on: [self-hosted]
    continue-on-error: true
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Install libraries for webp conversion
        run: |
          apt-get update && apt-get install -y libjpeg-dev libpng-dev libtiff-dev libgif-dev

      - name: Setup pnpm and yarn
        run: |
          npm install -g pnpm@^9
          npm install -g yarn

      - name: Install dependencies
        run: |
          pnpm config set unsafe-perm true
          HUSKY=0 pnpm i --ignore-scripts
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      # - name: Install dependencies with caching
      #   uses: ./.github/actions/package-installer
      #   with:
      #     github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Build All
        run: pnpm nx run web:test:build:merchant
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          VERSION: ${{ github.sha }}

      - name: Size Limit Action - DangerJS
        id: tracksizelimit_dangerjs
        uses: danger/danger-js@11.3.0
        with:
          args: "--id tracksizelimit_dangerjs --dangerfile dangerfile-tracklimit.js"
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: "true"

      - name: Print Bundle Size Report
        run: echo "Bundle Size Report - ${{ steps.tracksizelimit_dangerjs.outputs.reportTable }}"

      - name: slack Send
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
              "type": "home",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Dashboard Bundle Size Report - PR merge"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Bundle size check to restrict users to maintain bundle size within threshold limits. This Report consist of the size comparison with threshold and Percentage used of threshold"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text":" ${{ steps.tracksizelimit_dangerjs.outputs.reportTable }} "
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*PR Link to refer changes*: ${{ github.event.pull_request.html_url }}"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*PR Raised by*: "
                    },
                    {
                      "type": "image",
                      "image_url": "${{ github.event.pull_request.user.avatar_url }}",
                      "alt_text": "avatar"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "${{ github.event.pull_request.user.login }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "View Bundle size Threshold Limits path based"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Visit Link",
                      "emoji": true
                    },
                    "value": "click_me",
                    "url": "https://github.com/razorpay/dashboard/blob/master/bundlesize-budget.js",
                    "action_id": "button-action"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DASHBOARD_SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
