on: [push]
jobs:
  cancel:
    runs-on: [self-hosted]
    name: Cancel Previous Runs
    if: always()
    steps:
    - uses: styfle/cancel-workflow-action@d57d93c
      if: github.ref != 'refs/heads/master'
      name: cancel old workflows
      id: cancel
      with:
        access_token: ${{ github.token }}
    - if: github.ref == 'refs/heads/master'
      name: Don't cancel old workflows
      id: dont_cancel
      run: |
        echo "Don't cancel old workflow"
  validate_php_syntax:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Validate PHP Syntax
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: validate_php_syntax
      run: ci-assets/validate_php_syntax.sh
  build-web:
    runs-on: [self-hosted]
    needs: [cancel]
    continue-on-error: false
    name: Build Web Harbor
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: build
        uses: docker/build-push-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
          repository: razorpay/api
          tags: ${{ github.sha }}
          dockerfile: Dockerfile.web
          build_args: GIT_COMMIT_HASH=${{ github.sha }},GIT_TOKEN=${{ secrets.GIT_ACTION_TOKEN }},GIT_USERNAME=rzp,ONGGI_IMAGE=c.rzp.io/razorpay/onggi:php-7.2-api-web,ARMORY_IMAGE=c.rzp.io/razorpay/armory:wkhtmltopdf-v182,OPENCENSUS_IMAGE=razorpay/opencensus-php:v2020.10.28
  build-worker:
    runs-on: [ self-hosted ]
    needs: [ cancel ]
    continue-on-error: false
    name: Build Worker Harbor
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: build
        uses: docker/build-push-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
          repository: razorpay/api
          tags: worker-${{ github.sha }}
          dockerfile: Dockerfile.worker
          build_args: GIT_COMMIT_HASH=${{ github.sha }},GIT_TOKEN=${{ secrets.GIT_ACTION_TOKEN }},GIT_USERNAME=rzp,ONGGI_IMAGE=c.rzp.io/razorpay/onggi:php-7.2-api-worker,ARMORY_IMAGE=c.rzp.io/razorpay/armory:wkhtmltopdf-v182
  build-checkout:
    runs-on: [self-hosted]
    needs: [cancel]
    continue-on-error: false
    name: Build Checkout Harbor
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: build
        uses: docker/build-push-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
          repository: razorpay/api
          tags: checkout-${{ github.sha }}
          dockerfile: Dockerfile.checkout
          build_args: GIT_COMMIT_HASH=${{ github.sha }},GIT_TOKEN=${{ secrets.GIT_ACTION_TOKEN }},GIT_USERNAME=rzp
  build-openresty:
    runs-on: [self-hosted]
    needs: [cancel]
    continue-on-error: false
    name: Build Openresty Harbor
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: build
        uses: docker/build-push-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
          repository: razorpay/api
          tags: openresty-${{ github.sha }}
          dockerfile: Dockerfile.openresty
          build_args: GIT_COMMIT_HASH=${{ github.sha }},GIT_TOKEN=${{ secrets.GIT_ACTION_TOKEN }},GIT_USERNAME=rzp,ONGGI_IMAGE=c.rzp.io/razorpay/onggi:php-7.2-api
  build-dockerhub-web:
    runs-on: [ self-hosted ]
    needs: [ cancel ]
    continue-on-error: false
    name: Build Web Dockerhub
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: razorpay/api
          tags: ${{ github.sha }}
          dockerfile: Dockerfile.web
          build_args: GIT_COMMIT_HASH=${{ github.sha }},GIT_TOKEN=${{ secrets.GIT_ACTION_TOKEN }},GIT_USERNAME=rzp
  build-dockerhub-worker:
    runs-on: [ self-hosted ]
    needs: [ cancel ]
    continue-on-error: false
    name: Build Worker Dockerhub
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: razorpay/api
          tags: worker-${{ github.sha }}
          dockerfile: Dockerfile.worker
          build_args: GIT_COMMIT_HASH=${{ github.sha }},GIT_TOKEN=${{ secrets.GIT_ACTION_TOKEN }},GIT_USERNAME=rzp
  build-dockerhub-checkout:
    runs-on: [ self-hosted ]
    needs: [ cancel ]
    continue-on-error: false
    name: Build Checkout Dockerhub
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: razorpay/api
          tags: checkout-${{ github.sha }}
          dockerfile: Dockerfile.checkout
          build_args: GIT_COMMIT_HASH=${{ github.sha }},GIT_TOKEN=${{ secrets.GIT_ACTION_TOKEN }},GIT_USERNAME=rzp
  build-dockerhub-openresty:
    runs-on: [ self-hosted ]
    needs: [ cancel ]
    continue-on-error: false
    name: Build Openresty Dockerhub
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: build
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: razorpay/api
          tags: openresty-${{ github.sha }}
          dockerfile: Dockerfile.openresty
          build_args: GIT_COMMIT_HASH=${{ github.sha }},GIT_TOKEN=${{ secrets.GIT_ACTION_TOKEN }},GIT_USERNAME=rzp
  application_test_suite:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Application Test Suite
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
      env:
        ACTIONS_STEP_DEBUG: true
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: application_test_suite
      run: ci-assets/application_test_suite.sh
      env:
        DB_LIVE_HOST: mysql
        DB_TEST_HOST: mysql
        DB_AUTH_HOST: mysql
        DB_LIVE_DATABASE: api_live
        DB_TEST_DATABASE: api_test
        DB_AUTH_DATABASE: api_auth
        REDIS_HOST: redis
        QUERY_CACHE_REDIS_HOST: redis
        QUERY_CACHE_REDIS_PORT: 6379
        MUTEX_REDIS_HOST: redis
        MUTEX_REDIS_PORT: 6379
        THROTTLE_REDIS_HOST: redis
        THROTTLE_REDIS_PORT: 6379
        ES_HOST: elasticsearch
        ES_AUDIT_HOST: elasticsearch
        LQEXT_TESTING_TXN_SKIP_COUNT: 3
    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:5.2-alpine
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
  features_test_suite:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Features-1 Test Suite
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: features_test_suite
      run: ci-assets/features_test_suite.sh
      env:
        DB_LIVE_HOST: mysql
        DB_TEST_HOST: mysql
        DB_AUTH_HOST: mysql
        DB_LIVE_DATABASE: api_live
        DB_TEST_DATABASE: api_test
        DB_AUTH_DATABASE: api_auth
        REDIS_HOST: redis
        QUERY_CACHE_REDIS_HOST: redis
        QUERY_CACHE_REDIS_PORT: 6379
        MUTEX_REDIS_HOST: redis
        MUTEX_REDIS_PORT: 6379
        THROTTLE_REDIS_HOST: redis
        THROTTLE_REDIS_PORT: 6379
        ES_HOST: elasticsearch
        ES_AUDIT_HOST: elasticsearch
        LQEXT_TESTING_TXN_SKIP_COUNT: 3
    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:5.2-alpine
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
  features_2_test_suite:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Features-2 Test Suite
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: features_2_test_suite
      run: ci-assets/features_2_test_suite.sh
      env:
        DB_LIVE_HOST: mysql
        DB_TEST_HOST: mysql
        DB_AUTH_HOST: mysql
        DB_LIVE_DATABASE: api_live
        DB_TEST_DATABASE: api_test
        DB_AUTH_DATABASE: api_auth
        REDIS_HOST: redis
        QUERY_CACHE_REDIS_HOST: redis
        QUERY_CACHE_REDIS_PORT: 6379
        MUTEX_REDIS_HOST: redis
        MUTEX_REDIS_PORT: 6379
        THROTTLE_REDIS_HOST: redis
        THROTTLE_REDIS_PORT: 6379
        ES_HOST: elasticsearch
        ES_AUDIT_HOST: elasticsearch
        LQEXT_TESTING_TXN_SKIP_COUNT: 3
    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:5.2-alpine
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
  features_3_test_suite:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Features-3 Test Suite
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: features_3_test_suite
      run: ci-assets/features_3_test_suite.sh
      env:
        DB_LIVE_HOST: mysql
        DB_TEST_HOST: mysql
        DB_AUTH_HOST: mysql
        DB_LIVE_DATABASE: api_live
        DB_TEST_DATABASE: api_test
        DB_AUTH_DATABASE: api_auth
        REDIS_HOST: redis
        QUERY_CACHE_REDIS_HOST: redis
        QUERY_CACHE_REDIS_PORT: 6379
        MUTEX_REDIS_HOST: redis
        MUTEX_REDIS_PORT: 6379
        THROTTLE_REDIS_HOST: redis
        THROTTLE_REDIS_PORT: 6379
        ES_HOST: elasticsearch
        ES_AUDIT_HOST: elasticsearch
        LQEXT_TESTING_TXN_SKIP_COUNT: 3
    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:5.2-alpine
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
  features_4_test_suite:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Features-4 Test Suite
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: features_4_test_suite
      run: ci-assets/features_4_test_suite.sh
      env:
        DB_LIVE_HOST: mysql
        DB_TEST_HOST: mysql
        DB_AUTH_HOST: mysql
        DB_LIVE_DATABASE: api_live
        DB_TEST_DATABASE: api_test
        DB_AUTH_DATABASE: api_auth
        REDIS_HOST: redis
        QUERY_CACHE_REDIS_HOST: redis
        QUERY_CACHE_REDIS_PORT: 6379
        MUTEX_REDIS_HOST: redis
        MUTEX_REDIS_PORT: 6379
        THROTTLE_REDIS_HOST: redis
        THROTTLE_REDIS_PORT: 6379
        ES_HOST: elasticsearch
        ES_AUDIT_HOST: elasticsearch
        LQEXT_TESTING_TXN_SKIP_COUNT: 3
    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:5.2-alpine
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
  features_6_test_suite:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Features-6 Test Suite
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: features_6_test_suite
      run: ci-assets/features_6_test_suite.sh
      env:
        DB_LIVE_HOST: mysql
        DB_TEST_HOST: mysql
        DB_AUTH_HOST: mysql
        DB_LIVE_DATABASE: api_live
        DB_TEST_DATABASE: api_test
        DB_AUTH_DATABASE: api_auth
        DB_UPI_PAYMENTS_MOCKED: "false"
        DB_UPI_PAYMENTS_LIVE_HOST: mysql
        DB_UPI_PAYMENTS_TEST_HOST: mysql
        REDIS_HOST: redis
        QUERY_CACHE_REDIS_HOST: redis-cluster
        QUERY_CACHE_REDIS_PORT: 7000
        MUTEX_REDIS_HOST: redis
        MUTEX_REDIS_PORT: 6379
        THROTTLE_REDIS_HOST: redis
        THROTTLE_REDIS_PORT: 6379
        ES_HOST: elasticsearch
        ES_AUDIT_HOST: elasticsearch
        LQEXT_TESTING_TXN_SKIP_COUNT: 5
    services:
      redis:
        image: redis
      redis-cluster:
        image: grokzen/redis-cluster:5.0.9
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:5.2-alpine
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
  gateway_1_test_suite:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Gateway-1 Test Suite
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: gateway_1_test_suite
      run: ci-assets/gateway_1_test_suite.sh
      env:
        DB_LIVE_HOST: mysql
        DB_TEST_HOST: mysql
        DB_AUTH_HOST: mysql
        DB_LIVE_DATABASE: api_live
        DB_TEST_DATABASE: api_test
        DB_AUTH_DATABASE: api_auth
        DB_UPI_PAYMENTS_MOCKED: "false"
        DB_UPI_PAYMENTS_LIVE_HOST: mysql
        DB_UPI_PAYMENTS_TEST_HOST: mysql
        REDIS_HOST: redis
        QUERY_CACHE_REDIS_HOST: redis
        QUERY_CACHE_REDIS_PORT: 6379
        MUTEX_REDIS_HOST: redis
        MUTEX_REDIS_PORT: 6379
        THROTTLE_REDIS_HOST: redis
        THROTTLE_REDIS_PORT: 6379
        ES_HOST: elasticsearch
        ES_AUDIT_HOST: elasticsearch
        LQEXT_TESTING_TXN_SKIP_COUNT: 3
    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:5.2-alpine
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
  gateway_2_test_suite:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Gateway-2 Test Suite
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: gateway_2_test_suite
      run: ci-assets/gateway_2_test_suite.sh
      env:
        DB_LIVE_HOST: mysql
        DB_TEST_HOST: mysql
        DB_AUTH_HOST: mysql
        DB_LIVE_DATABASE: api_live
        DB_TEST_DATABASE: api_test
        DB_AUTH_DATABASE: api_auth
        DB_UPI_PAYMENTS_MOCKED: "false"
        DB_UPI_PAYMENTS_LIVE_HOST: mysql
        DB_UPI_PAYMENTS_TEST_HOST: mysql
        REDIS_HOST: redis
        QUERY_CACHE_REDIS_HOST: redis
        QUERY_CACHE_REDIS_PORT: 6379
        MUTEX_REDIS_HOST: redis
        MUTEX_REDIS_PORT: 6379
        THROTTLE_REDIS_HOST: redis
        THROTTLE_REDIS_PORT: 6379
        ES_HOST: elasticsearch
        ES_AUDIT_HOST: elasticsearch
        LQEXT_TESTING_TXN_SKIP_COUNT: 5
    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:5.2-alpine
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
  gateway_3_test_suite:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Gateway-3 Test Suite
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: gateway_3_test_suite
      run: ci-assets/gateway_3_test_suite.sh
      env:
        DB_LIVE_HOST: mysql
        DB_TEST_HOST: mysql
        DB_AUTH_HOST: mysql
        DB_LIVE_DATABASE: api_live
        DB_TEST_DATABASE: api_test
        DB_AUTH_DATABASE: api_auth
        DB_UPI_PAYMENTS_MOCKED: "false"
        DB_UPI_PAYMENTS_LIVE_HOST: mysql
        DB_UPI_PAYMENTS_TEST_HOST: mysql
        REDIS_HOST: redis
        QUERY_CACHE_REDIS_HOST: redis
        QUERY_CACHE_REDIS_PORT: 6379
        MUTEX_REDIS_HOST: redis
        MUTEX_REDIS_PORT: 6379
        THROTTLE_REDIS_HOST: redis
        THROTTLE_REDIS_PORT: 6379
        ES_HOST: elasticsearch
        ES_AUDIT_HOST: elasticsearch
        LQEXT_TESTING_TXN_SKIP_COUNT: 5
    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:5.2-alpine
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
  payment_test_suite:
    runs-on: [self-hosted]
    needs: [cancel]
    container:
      image: c.rzp.io/razorpay/onggi:php-7.2-api-web
      options: "--entrypoint /bin/bash"
      credentials:
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    continue-on-error: false
    name: Payment Test Suite
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - name: prepare_test
      run: ci-assets/prepare_test.sh
      env:
        GIT_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
    - name: payment_test_suite
      run: ci-assets/payment_test_suite.sh
      env:
        DB_LIVE_HOST: mysql
        DB_TEST_HOST: mysql
        DB_AUTH_HOST: mysql
        DB_LIVE_DATABASE: api_live
        DB_TEST_DATABASE: api_test
        DB_AUTH_DATABASE: api_auth
        DB_UPI_PAYMENTS_MOCKED: "false"
        DB_UPI_PAYMENTS_LIVE_HOST: mysql
        DB_UPI_PAYMENTS_TEST_HOST: mysql
        REDIS_HOST: redis
        QUERY_CACHE_REDIS_HOST: redis
        QUERY_CACHE_REDIS_PORT: 6379
        MUTEX_REDIS_HOST: redis
        MUTEX_REDIS_PORT: 6379
        THROTTLE_REDIS_HOST: redis
        THROTTLE_REDIS_PORT: 6379
        ES_HOST: elasticsearch
        ES_AUDIT_HOST: elasticsearch
        LQEXT_TESTING_TXN_SKIP_COUNT: 5
    services:
      redis:
        image: redis
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_ROOT_PASSWORD: root
      elasticsearch:
        image: elasticsearch:5.2-alpine
        env:
          ES_JAVA_OPTS: -Xms512m -Xmx512m
  workflow_status:
    runs-on: [self-hosted]
    continue-on-error: false
    name: Update Status Check
    needs: [
      validate_php_syntax,
      application_test_suite,
      features_test_suite,
      features_2_test_suite,
      features_3_test_suite,
      features_4_test_suite,
      features_6_test_suite,
      gateway_1_test_suite,
      gateway_2_test_suite,
      gateway_3_test_suite,
      payment_test_suite,
      build-web,
      build-worker,
      build-checkout,
      build-openresty,
      build-dockerhub-web,
      build-dockerhub-worker,
      build-dockerhub-checkout,
      build-dockerhub-openresty
      ]
    if: always()
    steps:
    - name: Failed
      id: failed
      if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: |
        echo 'Failing the workflow for github status check.'
        curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
        -d '{ "state" : "failure" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/razorpay/api" }' \
        https://api.github.com/repos/razorpay/api/statuses/${{ github.sha }}
        exit 1
    - name: Success
      if: steps.failed.conclusion == 'skipped'
      run: |
        echo 'Status check has passed!'
        curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
        -d '{ "state" : "success" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/razorpay/api" }' \
        https://api.github.com/repos/razorpay/api/statuses/${{ github.sha }}
        exit 0
  slack-notify:
    runs-on : [self-hosted]
    name: Notify build
    needs: [workflow_status]
    if: always()
    steps:
    - name: Sending build success notification to tech_builds (Slack)
      if: github.ref != 'refs/heads/master' && needs.workflow_status.result == 'success'
      env:
        SLACK_MESSAGE: 'Build Success.'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Github Actions # Optional. (defaults to webhook app)
        SLACK_CHANNEL: tech_builds # Optional. (defaults to webhook)
        SLACK_ICON: https://avatars3.githubusercontent.com/u/9919?s=40&v=4 # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      uses:  rtCamp/action-slack-notify@ca2febb
    - name: Sending build failed notification to tech_builds (Slack)
      if: github.ref != 'refs/heads/master' && needs.workflow_status.result != 'success'
      env:
        SLACK_MESSAGE: 'Build failed.'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#8B0000'
        SLACK_USERNAME: Github Actions # Optional. (defaults to webhook app)
        SLACK_CHANNEL: tech_builds # Optional. (defaults to webhook)
        SLACK_ICON: https://avatars3.githubusercontent.com/u/9919?s=40&v=4 # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      uses:  rtCamp/action-slack-notify@ca2febb
    - name: Sending build failed notification to tech_backend (Slack)
      if: github.ref == 'refs/heads/master' && needs.workflow_status.result != 'success'
      env:
        SLACK_MESSAGE: 'Master Build failed.'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#8B0000'
        SLACK_USERNAME: Github Actions # Optional. (defaults to webhook app)
        SLACK_CHANNEL: tech_builds # Optional. (defaults to webhook)
        SLACK_ICON: https://avatars3.githubusercontent.com/u/9919?s=40&v=4 # Optional. can be (repository, sender, an URL) (defaults to webhook app avatar)
      uses:  rtCamp/action-slack-notify@ca2febb
  trigger_regression_suite:
    runs-on: [self-hosted]
    name: Regression Suite
    needs: [workflow_status]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Webhook
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{ "branch" : "master" , "commit" : "${{ github.sha }}" , "repo" : "api" }' \
        https://${{ secrets.SPINNAKER_BASIC_AUTH }}@deploy-github-actions.razorpay.com/webhooks/webhook/x-regression
