name: Validate Workflow
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: [non-api, linux-amd64]
    continue-on-error: false
    name: Validate
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Use Node v18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Setup pnpm and yarn
        run: |
          npm install -g pnpm@^9
          npm install -g yarn

      - name: Install dependencies
        run: |
          pnpm config set unsafe-perm true
          HUSKY=0 pnpm i --ignore-scripts
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      # - name: Install dependencies with caching
      #   uses: ./.github/actions/package-installer
      #   with:
      #     github_access_token: ${{ secrets.CI_BOT_TOKEN }}

      - name: Validate
        # Automatically installs npm ci in web too
        run: |
          pnpm lint
          pnpm nx run web:tsc
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
