name: Validate Workflow
on: push
jobs:
  validate:
    runs-on: [self-hosted]
    continue-on-error: false
    name: Validate
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Use Node v16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - name: Setup yarn
        run: npm install -g yarn

      # This action allows caching dependencies and build outputs
      # to improve workflow execution time
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install Dependencies
        run: |
          npm config set unsafe-perm true
          npm ci # Automatically installs npm ci in web too
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

      - name: Validate
        # Automatically installs npm ci in web too
        run: |
          npm run lint
          cd web && npm run tsc
        env:
          NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_RAZORPAY_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
