<?php

namespace RZP\Models\BankingAccount;

class MccMappings
{
    const MCC_MAPPINGS = [
        'financial_services'	=> [
            'mutual_fund'						=> '6211',
            'lending'							=> '6012',
            'cryptocurrency'					=> '6051',
            'insurance'							=> '6300',
            'nbfc'								=> '6012',
            'cooperatives'						=> '6012',
            'pension_fund'						=> '6012',
            'forex'								=> '6010',
            'securities'						=> '6211',
            'commodities'						=> '6211',
            'accounting'						=> '8931',
            'financial_advisor'					=> '8931',
            'crowdfunding'						=> '6050',
            'trading'							=> '6211',
            'betting'							=> '7801',
            'get_rich_schemes'					=> '7361',
            'moneysend_funding'					=> '6538',
            'wire_transfers_and_money_orders'	=> '4829',
            'tax_preparation_services'			=> '7276',
            'tax_payments'						=> '9311',
            'digital_goods'						=> '5818',
            'atms'								=> '6011',
        ],
        'education' => [
            'college'							=>	'8220',
            'schools'							=>	'8211',
            'university'						=>	'8220',
            'professional_courses'				=>	'8299',
            'distance_learning'					=>	'8299',
            'day_care'							=>	'8351',
            'coaching'							=>	'8299',
            'elearning'							=>	'8299',
            'vocational_and_trade_schools'		=>	'8249',
            'sporting_clubs'					=>	'7941',
            'dance_halls_studios_and_schools'	=>	'7911',
            'correspondence_schools'			=>	'8241',
        ],
        'healthcare' => [
            'pharmacy'									=>	'5912',
            'clinic'									=>	'8062',
            'hospital'									=>	'8062',
            'lab'										=>	'8071',
            'dietician'									=>	'7298',
            'fitness'									=>	'7298',
            'health_coaching'							=>	'7298',
            'health_products'							=>	'5499',
            'healthcare_marketplace'					=>	'5399',
            'osteopaths'								=>	'8031',
            'medical_equipment_and_supply_stores'		=>	'5047',
            'drug_stores'								=>	'5122',
            'podiatrists_and_chiropodists'				=>	'8049',
            'dentists_and_orthodontists'				=>	'8021',
            'hardware_stores'							=>	'5251',
            'ophthalmologists'							=>	'8042',
            'orthopedic_goods_stores'					=>	'5976',
            'health_practitioners_medical_services'		=>	'8099',
            'testing_laboratories'						=>	'8734',
            'doctors'									=>	'8011',
        ],
        'utilities' => [
            'electricity'						=>	'4900',
            'gas'								=>	'4900',
            'telecom'							=>	'4814',
            'water'								=>	'4900',
            'cable'								=>	'4899',
            'broadband'							=>	'4899',
            'dth'								=>	'4899',
            'internet_provider'					=>	'4816',
            'bill_and_recharge_aggregators'		=>	'4814',
        ],
        'government'    => [
            'central' 							=>	'9399',
            'state' 							=>	'9399',
            'intra_government_purchases' 		=>	'9405',
            'goverment_postal_services' 		=>	'9402',
        ],
        'logistics' => [
            'freight'							=>	'4214',
            'courier'							=>	'4215',
            'warehousing'						=>	'4225',
            'distribution'						=>	'4214',
            'end_to_end_logistics'				=>	'4214',
            'courier_services'					=>	'4215',
        ],
        'tours_and_travel' => [
            'aviation'									=>	'4511',
            'accommodation'								=>	'7011',
            'ota'										=>	'4722',
            'travel_agency'								=>	'4722',
            'tourist_attractions_and_exhibits'			=>	'7991',
            'aquariums_dolphinariums_and_seaquariums'	=>	'7998',
            'timeshares'								=>	'7012',
        ],
        'transport' => [
            'cab_hailing'								=>	'4121',
            'bus'										=>	'4131',
            'train_and_metro'							=>	'4112',
            'automobile_rentals'						=>	'7512',
            'cruise_lines'								=>	'4411',
            'parking_lots_and_garages'					=>	'7523',
            'bridge_and_road_tolls'						=>	'4784',
            'freight_transport'							=>	'4011',
            'truck_and_utility_trailer_rentals'			=>	'7513',
            'transportation'							=>	'4111',
        ],
        'ecommerce' => [

            'ecommerce_marketplace'									=>	'5399',
            'agriculture'											=>	'5193',
            'books'													=>	'5942',
            'electronics_and_furniture'								=>	'5732',
            'coupons'												=>	'7311',
            'rental'												=>	'7394',
            'fashion_and_lifestyle'									=>	'5691',
            'gifting'												=>	'5193',
            'grocery'												=>	'5411',
            'baby_products'											=>	'5945',
            'office_supplies'										=>	'5111',
            'wholesale'												=>	'5300',
            'religious_products'									=>	'5973',
            'pet_products'											=>	'5995',
            'sports_products'										=>	'5941',
            'arts_and_collectibles'									=>	'5971',
            'sexual_wellness_products'								=>	'5999',
            'drop_shipping'											=>	'5399',
            'crypto_machinery'										=>	'5999',
            'tobacco'												=>	'5993',
            'weapons_and_ammunitions'								=>	'5999',
            'stamps_and_coins_stores'								=>	'5972',
            'automobile_parts_and_equipements'						=>	'5013',
            'office_equipment'										=>	'5044',
            'garden_supply_stores'									=>	'5261',
            'household_appliance_stores'							=>	'5722',
            'non_durable_goods'										=>	'5199',
            'electrical_parts_and_equipment'						=>	'5065',
            'wig_and_toupee_shops'									=>	'5698',
            'gift_novelty_and_souvenir_shops'						=>	'5947',
            'duty_free_stores'										=>	'5309',
            'office_and_commercial_furniture'						=>	'5021',
            'dry_goods'												=>	'5131',
            'books_and_publications'								=>	'5942',
            'camera_and_photographic_stores'						=>	'5946',
            'meat_supply_stores'									=>	'5422',
            'leather_goods_and_luggage'								=>	'5948',
            'snowmobile_dealers'									=>	'5598',
            'men_and_boys_clothing_stores'							=>	'5611',
            'paint_supply_stores'									=>	'5198',
            'automotive_parts'										=>	'5533',
            'jewellery_and_watch_stores'							=>	'5094',
            'auto_store_home_supply_stores'							=>	'5531',
            'tent_stores'											=>	'5998',
            'petroleum_and_petroleum_products'						=>	'5172',
            'department_stores'										=>	'5311',
            'shoe_stores_retail'									=>	'5661',
            'automotive_tire_stores'								=>	'5532',
            'sport_apparel_stores'									=>	'5655',
            'chemicals_and_allied_products'							=>	'5169',
            'fireplace_parts_and_accessories'						=>	'5718',
            'commercial_equipments'									=>	'5046',
            'family_clothing_stores'								=>	'5651',
            'fabric_and_sewing_stores'								=>	'5949',
            'camper_recreational_and_utility_trailer_dealers'		=>	'5561',
            'record_shops'											=>	'5735',
            'home_supply_warehouse'									=>	'5200',
            'clocks_and_silverware_stores'							=>	'5944',
            'art_supply_stores'										=>	'5970',
            'pawn_shops'											=>	'5933',
            'school_supplies_and_stationery'						=>	'5943',
            'opticians_optical_goods_and_eyeglasse_stores'			=>	'8043',
            'watch_and_jewellery_repair_stores'						=>	'7631',
            'wholesale_footwear_stores'								=>	'5139',
            'antique_stores'										=>	'5937',
            'plumbing_and_heating_equipment'						=>	'5074',
            'variety_stores'										=>	'5331',
            'liquor_stores'											=>	'5921',
            'boat_dealers'											=>	'5551',
            'cosmetic_stores'										=>	'5977',
            'home_furnishing_stores'								=>	'5719',
            'telecommunication_equipment_stores'					=>	'4812',
            'women_clothing'										=>	'5621',
            'florists'												=>	'5992',
            'commercial_photography_and_graphic_design_services'	=>	'7333',
            'building_matrial_stores'								=>	'5211',
            'candy_nut_confectionery_shops'							=>	'5441',
            'glass_and_wallpaper_stores'							=>	'5231',
            'video_game_supply_stores'								=>	'7993',
            'drapery_and_window_coverings_stores'					=>	'5714',
            'uniforms_and_commercial_clothing_stores'				=>	'5137',
            'automotive_paint_shops'								=>	'7535',
            'durable_goods_stores'									=>	'5099',
            'fur_shops'												=>	'5681',
            'industrial_supplies'									=>	'5085',
            'motorcycle_shops_and_dealers'							=>	'5571',
            'children_and_infants_wear_stores'						=>	'5641',
            'computer_software_stores'								=>	'5734',
            'women_accessory_stores'								=>	'5631',
            'books_periodicals_and_newspaper'						=>	'5192',
            'floor_covering_stores'									=>	'5713',
            'crystal_and_glassware_stores'							=>	'5950',
            'hardware_equipment_and_supply_stores'					=>	'5072',
            'discount_stores'										=>	'5310',
            'computers_peripheral_equipment_software'				=>	'5045',
            'automobile_and_truck_dealers'							=>	'5521',
            'aircraft_and_farm_equipment_dealers'					=>	'5599',
            'antique_shops_sales_and_repairs'						=>	'5932',
            'bicycle_stores'										=>	'5940',
            'hearing_aids_stores'									=>	'5975',
            'music_stores'											=>	'5733',
            'construction_materials'								=>	'5039',
            'accessory_and_apparel_stores'							=>	'5699',
            'second_hand_stores'									=>	'5931',
            'fuel_dealers'											=>	'5983',
            'furniture_and_home_furnishing_store'					=>	'5712',
        ],
        'food'  => [
            'online_food_ordering'				=>	'5811',
            'restaurant'						=>	'5812',
            'food_court'						=>	'5814',
            'catering'							=>	'5811',
            'alcohol'							=>	'5813',
            'restaurant_search_and_booking'		=>	'7299',
            'dairy_products'					=>	'5451',
            'bakeries'							=>	'5462',
        ],
        'it_and_software' => [
            'saas'                              =>	'5817',
            'paas'                              =>	'5817',
            'iaas'                              =>	'5817',
            'consulting_and_outsourcing'        =>	'7392',
            'web_development'                   =>	'7372',
            'technical_support'                 =>	'7379',
            'data_processing'                   =>	'7372',
        ],
        'gaming' => [

            'game_developer'       => '5816',
            'esports'              => '5816',
            'online_casino'        => '7801',
            'fantasy_sports'       => '5816',
            'gaming_marketplace'   => '5816',
        ],
        'media_and_entertainment' => [
            'video_on_demand'                         =>  '5815',
            'music_streaming'                         =>  '5815',
            'multiplex'                               =>  '7832',
            'content_and_publishing'                  =>  '2741',
            'ticketing'                               =>  '7832',
            'news'                                    =>  '5994',
            'video_game_arcades'                      =>  '7994',
            'video_tape_production_and_distribution'  =>  '7829',
            'bowling_alleys'                          =>  '7933',
            'billiard_and_pool_establishments'        =>  '7932',
            'amusement_parks_and_circuses'            =>  '7996',
            'ticket_agencies'                         =>  '7922',
        ],
        'services' => [
            'repair_and_cleaning'                               => '7531',
            'interior_design_and_architect'                     => '8911',
            'movers_and_packers'                                => '4214',
            'legal'                                             => '8111',
            'event_planning'                                    => '8999',
            'service_centre'                                    => '5511',
            'consulting'                                        => '7392',
            'ad_and_marketing'                                  => '7311',
            'services_classifieds'                              => '7311',
            'multi_level_marketing'                             => '5964',
            'construction_services'                             => '1520',
            'architectural_services'                            => '780',
            'car_washes'                                        => '7542',
            'motor_home_rentals'                                => '7519',
            'stenographic_and_secretarial_support_services'     => '7339',
            'chiropractors'                                     => '8041',
            'automotive_service_shops'                          => '7538',
            'shoe_repair_shops'                                 => '7251',
            'telecommunication_service'                         => '4813',
            'fines'                                             => '9222',
            'security_agencies'                                 => '7393',
            'type_setting_and_engraving_services'               => '2791',
            'small_appliance_repair_shops'                      => '7629',
            'photography_labs'                                  => '7395',
            'dry_cleaners'                                      => '7216',
            'electronic_repair_shops'                           => '7622',
            'cleaning_and_sanitation_services'                  => '2842',
            'nursing_care_facilities'                           => '8050',
            'direct_marketing'                                  => '5969',
            'veterinary_services'                               => '742',
            'affliated_auto_rental'                             => '3351',
            'alimony_and_child_support'                         => '9211',
            'airport_flying_fields'                             => '4582',
            'tire_retreading_and_repair_shops'                  => '7534',
            'television_cable_services'                         => '4899',
            'recreational_and_sporting_camps'                   => '7032',
            'agricultural_cooperatives'                         => '763',
            'carpentry_contractors'                             => '1750',
            'wrecking_and_salvaging_services'                   => '5935',
            'automobile_towing_services'                        => '7549',
            'barber_and_beauty_shops'                           => '7230',
            'video_tape_rental_stores'                          => '7841',
            'golf_courses'                                      => '7992',
            'miscellaneous_repair_shops'                        => '7699',
            'motor_homes_and_parts'                             => '5592',
            'debt_marriage_personal_counseling_service'         => '7277',
            'air_conditioning_and_refrigeration_repair_shops'   => '7623',
            'tailors'                                           => '5697',
            'massage_parlors'                                   => '7297',
            'horse_or_dog_racing'                               => '7802',
            'credit_reporting_agencies'                         => '7321',
            'heating_and_plumbing_contractors'                  => '1711',
            'electrical_contractors'                            => '1731',
            'carpet_and_upholstery_cleaning_services'           => '7217',
            'roofing_and_metal_work_contractors'                => '1761',
            'internet_service_providers'                        => '4816',
            'laundry_services'                                  => '7210',
            'recreational_camps'                                => '7033',
            'masonry_contractors'                               => '1740',
            'exterminating_and_disinfecting_services'           => '7342',
            'ambulance_services'                                => '4119',
            'funeral_services_and_crematories'                  => '7261',
            'metal_service_centres'                             => '5051',
            'copying_and_blueprinting_services'                 => '7338',
            'fuel_dispensers'                                   => '5542',
            'lottery'                                           => '7800',
            'welding_repair'                                    => '7692',
            'mobile_home_dealers'                               => '5271',
            'concrete_work_contractors'                         => '1771',
            'boat_rentals'                                      => '4457',
            'personal_shoppers_and_shopping_clubs'              => '7278',
            'door_to_door_sales'                                => '5963',
            'travel_related_direct_marketing'                   => '5962',
            'lottery_and_betting'                               => '7995',
            'bands_orchestras_and_miscellaneous_entertainers'   => '7929',
            'furniture_repair_and_refinishing'                  => '7641',
            'direct_marketing_and_subscription_merchants'       => '5968',
            'typewriter_stores_sales_service_and_rentals'       => '5978',
            'direct_marketing_insurance_services'               => '5960',
            'business_services'                                 => '7399',
            'inbound_telemarketing_merchants'                   => '5967',
            'recreation_services'                               => '7999',
            'swimming_pools'                                    => '5996',
            'outbound_telemarketing_merchants'                  => '5966',
            'public_warehousing'                                => '4225',
            'clothing_rental_stores'                            => '7296',
            'contractors'                                       => '1799',
            'transportation_services'                           => '4789',
            'electric_razor_stores'                             => '5997',
            'service_stations'                                  => '5541',
            'photographic_studio'                               => '7221',
            'professional_services'                             => '8999',
        ],
        'housing' => [
            'developer'               =>  '6513',
            'facility_management'     =>  '7349',
            'rwa'                     =>  '7349',
            'coworking'               =>  '6513',
            'realestate_classifieds'  =>  '6513',
            'space_rental'            =>  '6513',
        ],
        'not_for_profit' => [
            'charity'     =>  '8398',
            'educational' =>  '8398',
            'religious'   =>  '8661',
            'personal'    =>  '8398',
        ],
        'social' => [
            'matchmaking'                         => '7273',
            'social_network'                      => '8641',
            'messaging'                           => '4821',
            'professional_network'                => '8699',
            'neighbourhood_network'               => '8699',
            'automobile_associations_and_clubs'   => '8675',
            'political_organizations'             => '8651',
            'country_and_athletic_clubs'          => '7997',
            'associations_and_membership'         => '8699',
        ]
    ];

    /**
     * Get MCC Code from category and sub-category
     * 
     * As shared in the list - https://docs.google.com/spreadsheets/d/18VOT_AuxNF0azgwCDem0iqpXAB1uwjUIxoETqQFbBgM/
     */
    public static function getMCCMapping(string $category, string $subcategory)
    {
        $mcc = '';

        $category = strtolower($category);
        $subcategory = strtolower($subcategory);

        if (array_key_exists($category, self::MCC_MAPPINGS))
        {
            $categoryMappings = self::MCC_MAPPINGS[$category];

            if (array_key_exists($subcategory, $categoryMappings))
            {
                $mcc = $categoryMappings[$subcategory];
            }
        }

        return $mcc;
    }

}