<?php

namespace RZP\Models\Currency;

use RZP\Models\Card\IIN\Country;

class Currency
{
    const AED = 'AED';
    const ALL = 'ALL';
    const AMD = 'AMD';
    const ARS = 'ARS';
    const AUD = 'AUD';
    const AWG = 'AWG';
    const BBD = 'BBD';
    const BDT = 'BDT';
    const BHD = 'BHD';
    const BMD = 'BMD';
    const BND = 'BND';
    const BOB = 'BOB';
    const BSD = 'BSD';
    const BWP = 'BWP';
    const BZD = 'BZD';
    const CAD = 'CAD';
    const CHF = 'CHF';
    const CNY = 'CNY';
    const COP = 'COP';
    const CRC = 'CRC';
    const CUP = 'CUP';
    const CZK = 'CZK';
    const DKK = 'DKK';
    const DOP = 'DOP';
    const DZD = 'DZD';
    const EGP = 'EGP';
    const ETB = 'ETB';
    const EUR = 'EUR';
    const FJD = 'FJD';
    const GBP = 'GBP';
    const GHS = 'GHS';
    const GIP = 'GIP';
    const GMD = 'GMD';
    const GTQ = 'GTQ';
    const GYD = 'GYD';
    const HKD = 'HKD';
    const HNL = 'HNL';
    const HRK = 'HRK';
    const HTG = 'HTG';
    const HUF = 'HUF';
    const IDR = 'IDR';
    const ILS = 'ILS';
    const INR = 'INR';
    const JMD = 'JMD';
    const KES = 'KES';
    const KGS = 'KGS';
    const KHR = 'KHR';
    const KWD = 'KWD';
    const KYD = 'KYD';
    const KZT = 'KZT';
    const LAK = 'LAK';
    const LBP = 'LBP';
    const LKR = 'LKR';
    const LRD = 'LRD';
    const LSL = 'LSL';
    const MAD = 'MAD';
    const MDL = 'MDL';
    const MKD = 'MKD';
    const MMK = 'MMK';
    const MNT = 'MNT';
    const MOP = 'MOP';
    const MUR = 'MUR';
    const MVR = 'MVR';
    const MWK = 'MWK';
    const MXN = 'MXN';
    const MYR = 'MYR';
    const NAD = 'NAD';
    const NGN = 'NGN';
    const NIO = 'NIO';
    const NOK = 'NOK';
    const NPR = 'NPR';
    const NZD = 'NZD';
    const OMR = 'OMR';
    const PEN = 'PEN';
    const PGK = 'PGK';
    const PHP = 'PHP';
    const PKR = 'PKR';
    const QAR = 'QAR';
    const RUB = 'RUB';
    const SAR = 'SAR';
    const SCR = 'SCR';
    const SEK = 'SEK';
    const SGD = 'SGD';
    const SLL = 'SLL';
    const SOS = 'SOS';
    const SSP = 'SSP';
    const SVC = 'SVC';
    const SZL = 'SZL';
    const THB = 'THB';
    const TRY = 'TRY';
    const TTD = 'TTD';
    const TZS = 'TZS';
    const USD = 'USD';
    const UYU = 'UYU';
    const UZS = 'UZS';
    const YER = 'YER';
    const ZAR = 'ZAR';

    const SUPPORTED_CURRENCIES = [
        self::AED,
        self::ALL,
        self::AMD,
        self::ARS,
        self::AUD,
        self::AWG,
        self::BBD,
        self::BDT,
        self::BHD,
        self::BMD,
        self::BND,
        self::BOB,
        self::BSD,
        self::BWP,
        self::BZD,
        self::CAD,
        self::CHF,
        self::CNY,
        self::COP,
        self::CRC,
        self::CUP,
        self::CZK,
        self::DKK,
        self::DOP,
        self::DZD,
        self::EGP,
        self::ETB,
        self::EUR,
        self::FJD,
        self::GBP,
        self::GHS,
        self::GIP,
        self::GMD,
        self::GTQ,
        self::GYD,
        self::HKD,
        self::HNL,
        self::HRK,
        self::HTG,
        self::HUF,
        self::IDR,
        self::ILS,
        self::INR,
        self::JMD,
        self::KES,
        self::KGS,
        self::KHR,
        self::KWD,
        self::KYD,
        self::KZT,
        self::LAK,
        self::LKR,
        self::LRD,
        self::LSL,
        self::MAD,
        self::MDL,
        self::MKD,
        self::MMK,
        self::MNT,
        self::MOP,
        self::MUR,
        self::MVR,
        self::MWK,
        self::MXN,
        self::MYR,
        self::NAD,
        self::NGN,
        self::NIO,
        self::NOK,
        self::NPR,
        self::NZD,
        self::OMR,
        self::PEN,
        self::PGK,
        self::PHP,
        self::PKR,
        self::QAR,
        self::RUB,
        self::SAR,
        self::SCR,
        self::SEK,
        self::SGD,
        self::SLL,
        self::SOS,
        self::SSP,
        self::SVC,
        self::SZL,
        self::THB,
        self::TRY,
        self::TTD,
        self::TZS,
        self::USD,
        self::UYU,
        self::UZS,
        self::YER,
        self::ZAR,
    ];

    const THREE_DECIMAL_CURRENCIES = [
        self::BHD,
        self::KWD,
        self::OMR,
    ];

    const ISO_NUMERIC_CODES = [
        self::AED => '784',
        self::ALL => '008',
        self::AMD => '051',
        self::ARS => '032',
        self::AUD => '036',
        self::AWG => '533',
        self::BBD => '052',
        self::BDT => '050',
        self::BHD => '048',
        self::BMD => '060',
        self::BND => '096',
        self::BOB => '068',
        self::BSD => '044',
        self::BWP => '072',
        self::BZD => '084',
        self::CAD => '124',
        self::CHF => '756',
        self::CNY => '156',
        self::COP => '170',
        self::CRC => '188',
        self::CUP => '192',
        self::CZK => '203',
        self::DKK => '208',
        self::DOP => '214',
        self::DZD => '012',
        self::EGP => '818',
        self::ETB => '230',
        self::EUR => '978',
        self::FJD => '242',
        self::GBP => '826',
        self::GHS => '936',
        self::GIP => '292',
        self::GMD => '270',
        self::GTQ => '320',
        self::GYD => '328',
        self::HKD => '344',
        self::HNL => '340',
        self::HRK => '191',
        self::HTG => '332',
        self::HUF => '348',
        self::IDR => '360',
        self::ILS => '376',
        self::INR => '356',
        self::JMD => '388',
        self::KES => '404',
        self::KGS => '417',
        self::KHR => '116',
        self::KWD => '414',
        self::KYD => '136',
        self::KZT => '398',
        self::LAK => '418',
        self::LKR => '144',
        self::LRD => '430',
        self::LSL => '426',
        self::MAD => '504',
        self::MDL => '498',
        self::MKD => '807',
        self::MMK => '104',
        self::MNT => '496',
        self::MOP => '446',
        self::MUR => '480',
        self::MVR => '462',
        self::MWK => '454',
        self::MXN => '484',
        self::MYR => '458',
        self::NAD => '516',
        self::NGN => '566',
        self::NIO => '558',
        self::NOK => '578',
        self::NPR => '524',
        self::NZD => '554',
        self::OMR => '512',
        self::PEN => '604',
        self::PGK => '598',
        self::PHP => '608',
        self::PKR => '586',
        self::QAR => '634',
        self::RUB => '643',
        self::SAR => '682',
        self::SCR => '690',
        self::SEK => '752',
        self::SGD => '702',
        self::SLL => '694',
        self::SOS => '706',
        self::SSP => '728',
        self::SVC => '222',
        self::SZL => '748',
        self::THB => '764',
        self::TRY => '949',
        self::TTD => '780',
        self::TZS => '834',
        self::USD => '840',
        self::UYU => '858',
        self::UZS => '860',
        self::YER => '886',
        self::ZAR => '710',
    ];

    const COUNTRY_CURRENCY_CODES = [
        Country::AD => self::EUR,
        Country::AE => self::AED,
        Country::AL => self::ALL,
        Country::AM => self::AMD,
        Country::AR => self::ARS,
        Country::AT => self::EUR,
        Country::AU => self::AUD,
        Country::AW => self::AWG,
        Country::AX => self::EUR,
        Country::BB => self::BBD,
        Country::BD => self::BDT,
        Country::BE => self::EUR,
        Country::BH => self::BHD,
        Country::BL => self::EUR,
        Country::BM => self::BMD,
        Country::BN => self::BND,
        Country::BO => self::BOB,
        Country::BS => self::BSD,
        Country::BW => self::BWP,
        Country::BZ => self::BZD,
        Country::CA => self::CAD,
        Country::CH => self::CHF,
        Country::CN => self::CNY,
        Country::CO => self::COP,
        Country::CR => self::CRC,
        Country::CU => self::CUP,
        Country::CY => self::EUR,
        Country::CZ => self::CZK,
        Country::DE => self::EUR,
        Country::DK => self::DKK,
        Country::DO => self::DOP,
        Country::DZ => self::DZD,
        Country::EE => self::EUR,
        Country::EG => self::EGP,
        Country::ES => self::EUR,
        Country::ET => self::ETB,
        Country::FI => self::EUR,
        Country::FJ => self::FJD,
        Country::FR => self::EUR,
        Country::GB => self::GBP,
        Country::GF => self::EUR,
        Country::GH => self::GHS,
        Country::GI => self::GIP,
        Country::GM => self::GMD,
        Country::GP => self::EUR,
        Country::GR => self::EUR,
        Country::GT => self::GTQ,
        Country::GY => self::GYD,
        Country::HK => self::HKD,
        Country::HN => self::HNL,
        Country::HR => self::HRK,
        Country::HT => self::HTG,
        Country::HU => self::HUF,
        Country::ID => self::IDR,
        Country::IE => self::EUR,
        Country::IL => self::ILS,
        Country::IN => self::INR,
        Country::IT => self::EUR,
        Country::JM => self::JMD,
        Country::KE => self::KES,
        Country::KG => self::KGS,
        Country::KH => self::KHR,
        Country::KW => self::KWD,
        Country::KY => self::KYD,
        Country::KZ => self::KZT,
        Country::LA => self::LAK,
        Country::LK => self::LKR,
        Country::LR => self::LRD,
        Country::LS => self::LSL,
        Country::LT => self::EUR,
        Country::LU => self::EUR,
        Country::LV => self::EUR,
        Country::MA => self::MAD,
        Country::MC => self::EUR,
        Country::MD => self::MDL,
        Country::ME => self::EUR,
        Country::MF => self::EUR,
        Country::MK => self::MKD,
        Country::MM => self::MMK,
        Country::MN => self::MNT,
        Country::MO => self::MOP,
        Country::MQ => self::EUR,
        Country::MT => self::EUR,
        Country::MU => self::MUR,
        Country::MV => self::MVR,
        Country::MW => self::MWK,
        Country::MX => self::MXN,
        Country::MY => self::MYR,
        Country::NA => self::NAD,
        Country::NG => self::NGN,
        Country::NI => self::NIO,
        Country::NL => self::EUR,
        Country::NO => self::NOK,
        Country::NP => self::NPR,
        Country::NZ => self::NZD,
        Country::OM => self::OMR,
        Country::PE => self::PEN,
        Country::PG => self::PGK,
        Country::PH => self::PHP,
        Country::PK => self::PKR,
        Country::PM => self::EUR,
        Country::PT => self::EUR,
        Country::QA => self::QAR,
        Country::RE => self::EUR,
        Country::RU => self::RUB,
        Country::SA => self::SAR,
        Country::SC => self::SCR,
        Country::SE => self::SEK,
        Country::SI => self::EUR,
        Country::SG => self::SGD,
        Country::SK => self::EUR,
        Country::SL => self::SLL,
        Country::SM => self::EUR,
        Country::SO => self::SOS,
        Country::SS => self::SSP,
        Country::SV => self::SVC,
        Country::SZ => self::SZL,
        Country::TF => self::EUR,
        Country::TH => self::THB,
        Country::TR => self::TRY,
        Country::TT => self::TTD,
        Country::TZ => self::TZS,
        Country::US => self::USD,
        Country::UY => self::UYU,
        Country::UZ => self::UZS,
        Country::VA => self::EUR,
        Country::YE => self::YER,
        Country::YT => self::EUR,
        Country::ZA => self::ZAR
    ];

    // Factor by which currency's more acceptable denomination is greater
    // than currency's lowest denomination (ex: Rs and paise)
    const DENOMINATION_FACTOR = [
        self::AED => 100,
        self::ALL => 100,
        self::AMD => 100,
        self::ARS => 100,
        self::AUD => 100,
        self::AWG => 100,
        self::BBD => 100,
        self::BDT => 100,
        self::BHD => 1000,
        self::BMD => 100,
        self::BND => 100,
        self::BOB => 100,
        self::BSD => 100,
        self::BWP => 100,
        self::BZD => 100,
        self::CAD => 100,
        self::CHF => 100,
        self::CNY => 100,
        self::COP => 100,
        self::CRC => 100,
        self::CUP => 100,
        self::CZK => 100,
        self::DKK => 100,
        self::DOP => 100,
        self::DZD => 100,
        self::EGP => 100,
        self::ETB => 100,
        self::EUR => 100,
        self::FJD => 100,
        self::GBP => 100,
        self::GHS => 100,
        self::GIP => 100,
        self::GMD => 100,
        self::GTQ => 100,
        self::GYD => 100,
        self::HKD => 100,
        self::HNL => 100,
        self::HRK => 100,
        self::HTG => 100,
        self::HUF => 100,
        self::IDR => 100,
        self::ILS => 100,
        self::INR => 100,
        self::JMD => 100,
        self::KES => 100,
        self::KGS => 100,
        self::KHR => 100,
        self::KWD => 1000,
        self::KYD => 100,
        self::KZT => 100,
        self::LAK => 100,
        self::LKR => 100,
        self::LRD => 100,
        self::LSL => 100,
        self::MAD => 100,
        self::MDL => 100,
        self::MKD => 100,
        self::MMK => 100,
        self::MNT => 100,
        self::MOP => 100,
        self::MUR => 100,
        self::MVR => 100,
        self::MWK => 100,
        self::MXN => 100,
        self::MYR => 100,
        self::NAD => 100,
        self::NGN => 100,
        self::NIO => 100,
        self::NOK => 100,
        self::NPR => 100,
        self::NZD => 100,
        self::OMR => 1000,
        self::PEN => 100,
        self::PGK => 100,
        self::PHP => 100,
        self::PKR => 100,
        self::QAR => 100,
        self::RUB => 100,
        self::SAR => 100,
        self::SCR => 100,
        self::SEK => 100,
        self::SGD => 100,
        self::SLL => 100,
        self::SOS => 100,
        self::SSP => 100,
        self::SVC => 100,
        self::SZL => 100,
        self::THB => 100,
        self::TRY => 100,
        self::TTD => 100,
        self::TZS => 100,
        self::USD => 100,
        self::UYU => 100,
        self::UZS => 100,
        self::YER => 100,
        self::ZAR => 100,
    ];

    // Exponential difference between currency's more acceptable denomination
    // and it's lowest denomination to the base 10
    const EXPONENT = [
        self::AED => 2,
        self::ALL => 2,
        self::AMD => 2,
        self::ARS => 2,
        self::AUD => 2,
        self::AWG => 2,
        self::BBD => 2,
        self::BDT => 2,
        self::BHD => 3,
        self::BMD => 2,
        self::BND => 2,
        self::BOB => 2,
        self::BSD => 2,
        self::BWP => 2,
        self::BZD => 2,
        self::CAD => 2,
        self::CHF => 2,
        self::CNY => 2,
        self::COP => 2,
        self::CRC => 2,
        self::CUP => 2,
        self::CZK => 2,
        self::DKK => 2,
        self::DOP => 2,
        self::DZD => 2,
        self::EGP => 2,
        self::ETB => 2,
        self::EUR => 2,
        self::FJD => 2,
        self::GBP => 2,
        self::GHS => 2,
        self::GIP => 2,
        self::GMD => 2,
        self::GTQ => 2,
        self::GYD => 2,
        self::HKD => 2,
        self::HNL => 2,
        self::HRK => 2,
        self::HTG => 2,
        self::HUF => 2,
        self::IDR => 2,
        self::ILS => 2,
        self::INR => 2,
        self::JMD => 2,
        self::KES => 2,
        self::KGS => 2,
        self::KHR => 2,
        self::KWD => 3,
        self::KYD => 2,
        self::KZT => 2,
        self::LAK => 2,
        self::LKR => 2,
        self::LRD => 2,
        self::LSL => 2,
        self::MAD => 2,
        self::MDL => 2,
        self::MKD => 2,
        self::MMK => 2,
        self::MNT => 2,
        self::MOP => 2,
        self::MUR => 2,
        self::MVR => 2,
        self::MWK => 2,
        self::MXN => 2,
        self::MYR => 2,
        self::NAD => 2,
        self::NGN => 2,
        self::NIO => 2,
        self::NOK => 2,
        self::NPR => 2,
        self::NZD => 2,
        self::OMR => 3,
        self::PEN => 2,
        self::PGK => 2,
        self::PHP => 2,
        self::PKR => 2,
        self::QAR => 2,
        self::RUB => 2,
        self::SAR => 2,
        self::SCR => 2,
        self::SEK => 2,
        self::SGD => 2,
        self::SLL => 2,
        self::SOS => 2,
        self::SSP => 2,
        self::SVC => 2,
        self::SZL => 2,
        self::THB => 2,
        self::TRY => 2,
        self::TTD => 2,
        self::TZS => 2,
        self::USD => 2,
        self::UYU => 2,
        self::UZS => 2,
        self::YER => 2,
        self::ZAR => 2,
    ];

    // Amount below which we don't accept payments, or creation of payments links and pages
    const MIN_VALUE = [
        self::AED => 10,
        self::ALL => 221,
        self::AMD => 975,
        self::ARS => 80,
        self::AUD => 50,
        self::AWG => 10,
        self::BBD => 10,
        self::BDT => 168,
        self::BHD => 1,
        self::BMD => 10,
        self::BND => 10,
        self::BOB => 14,
        self::BSD => 10,
        self::BWP => 22,
        self::BZD => 10,
        self::CAD => 50,
        self::CHF => 50,
        self::CNY => 14,
        self::COP => 1000,
        self::CRC => 1000,
        self::CUP => 53,
        self::CZK => 46,
        self::DKK => 250,
        self::DOP => 102,
        self::DZD => 239,
        self::EGP => 35,
        self::ETB => 57,
        self::EUR => 50,
        self::FJD => 10,
        self::GBP => 30,
        self::GHS => 3,
        self::GIP => 10,
        self::GMD => 100,
        self::GTQ => 16,
        self::GYD => 418,
        self::HKD => 400,
        self::HNL => 49,
        self::HRK => 14,
        self::HTG => 167,
        self::HUF => 555,
        self::IDR => 1000,
        self::ILS => 10,
        self::INR => 100,
        self::JMD => 250,
        self::KES => 201,
        self::KGS => 140,
        self::KHR => 1000,
        self::KWD => 1,
        self::KYD => 10,
        self::KZT => 759,
        self::LAK => 1000,
        self::LKR => 358,
        self::LRD => 325,
        self::LSL => 29,
        self::MAD => 20,
        self::MDL => 35,
        self::MKD => 109,
        self::MMK => 1000,
        self::MNT => 1000,
        self::MOP => 17,
        self::MUR => 70,
        self::MVR => 31,
        self::MWK => 1000,
        self::MXN => 39,
        self::MYR => 10,
        self::NAD => 29,
        self::NGN => 723,
        self::NIO => 66,
        self::NOK => 300,
        self::NPR => 221,
        self::NZD => 50,
        self::OMR => 1,
        self::PEN => 10,
        self::PGK => 10,
        self::PHP => 106,
        self::PKR => 227,
        self::QAR => 10,
        self::RUB => 130,
        self::SAR => 10,
        self::SCR => 28,
        self::SEK => 300,
        self::SGD => 50,
        self::SLL => 1000,
        self::SOS => 1000,
        self::SSP => 100,
        self::SVC => 18,
        self::SZL => 29,
        self::THB => 64,
        self::TRY => 100,
        self::TTD => 14,
        self::TZS => 1000,
        self::USD => 10,
        self::UYU => 67,
        self::UZS => 1000,
        self::YER => 501,
        self::ZAR => 29,
    ];

    // Token amount that is deducted in the first transaction as means to provide authorization for subscription
    const MIN_AUTH_VALUE = [
        self::AED => 10,
        self::ALL => 221,
        self::AMD => 975,
        self::ARS => 80,
        self::AUD => 50,
        self::AWG => 10,
        self::BBD => 10,
        self::BDT => 168,
        self::BHD => 1,
        self::BMD => 10,
        self::BND => 10,
        self::BOB => 14,
        self::BSD => 10,
        self::BWP => 22,
        self::BZD => 10,
        self::CAD => 50,
        self::CHF => 50,
        self::CNY => 14,
        self::COP => 1000,
        self::CRC => 1000,
        self::CUP => 53,
        self::CZK => 46,
        self::DKK => 250,
        self::DOP => 102,
        self::DZD => 239,
        self::EGP => 35,
        self::ETB => 57,
        self::EUR => 50,
        self::FJD => 10,
        self::GBP => 30,
        self::GHS => 3,
        self::GIP => 10,
        self::GMD => 100,
        self::GTQ => 16,
        self::GYD => 418,
        self::HKD => 400,
        self::HNL => 49,
        self::HRK => 14,
        self::HTG => 167,
        self::HUF => 555,
        self::IDR => 1000,
        self::ILS => 10,
        self::INR => 100,
        self::JMD => 250,
        self::KES => 201,
        self::KGS => 140,
        self::KHR => 1000,
        self::KWD => 1,
        self::KYD => 10,
        self::KZT => 759,
        self::LAK => 1000,
        self::LKR => 358,
        self::LRD => 325,
        self::LSL => 29,
        self::MAD => 20,
        self::MDL => 35,
        self::MKD => 109,
        self::MMK => 1000,
        self::MNT => 1000,
        self::MOP => 17,
        self::MUR => 70,
        self::MVR => 31,
        self::MWK => 1000,
        self::MXN => 39,
        self::MYR => 10,
        self::NAD => 29,
        self::NGN => 723,
        self::NIO => 66,
        self::NOK => 300,
        self::NPR => 221,
        self::NZD => 50,
        self::OMR => 1,
        self::PEN => 10,
        self::PGK => 10,
        self::PHP => 106,
        self::PKR => 227,
        self::QAR => 10,
        self::RUB => 130,
        self::SAR => 10,
        self::SCR => 28,
        self::SEK => 300,
        self::SGD => 50,
        self::SLL => 1000,
        self::SOS => 1000,
        self::SSP => 100,
        self::SVC => 18,
        self::SZL => 29,
        self::THB => 64,
        self::TRY => 100,
        self::TTD => 14,
        self::TZS => 1000,
        self::USD => 50,
        self::UYU => 67,
        self::UZS => 1000,
        self::YER => 501,
        self::ZAR => 29,
    ];

    const SYMBOL = [
        self::AED => 'د.إ',
        self::ALL => 'Lek',
        self::AMD => '֏',
        self::ARS => 'ARS',
        self::AUD => 'A$',
        self::AWG => 'Afl.',
        self::BBD => '$',
        self::BDT => '৳',
        self::BHD => 'د.ب',
        self::BMD => '$',
        self::BND => 'BND',
        self::BOB => 'Bs',
        self::BSD => 'B$',
        self::BWP => 'P',
        self::BZD => 'BZ$',
        self::CAD => 'C$',
        self::CHF => 'CHf',
        self::CNY => '¥',
        self::COP => 'COL$',
        self::CRC => '₡',
        self::CUP => '$MN',
        self::CZK => 'Kč',
        self::DKK => 'DKK',
        self::DOP => 'RD$',
        self::DZD => 'د.ج',
        self::EGP => 'E£',
        self::ETB => 'ብር',
        self::EUR => '€',
        self::FJD => 'FJ$',
        self::GBP => '£',
        self::GHS => 'GH₵',
        self::GIP => 'GIP',
        self::GMD => 'D',
        self::GTQ => 'Q',
        self::GYD => 'G$',
        self::HKD => 'HK$',
        self::HNL => 'HNL',
        self::HRK => 'kn',
        self::HTG => 'G',
        self::HUF => 'Ft',
        self::IDR => 'Rp',
        self::ILS => '₪',
        self::INR => '₹',
        self::JMD => 'J$',
        self::KES => 'Ksh',
        self::KGS => 'Лв',
        self::KHR => '៛',
        self::KWD => 'د.ك',
        self::KYD => 'CI$',
        self::KZT => '₸',
        self::LAK => '₭',
        self::LKR => 'රු',
        self::LRD => 'L$',
        self::LSL => 'LSL',
        self::MAD => 'د.م.',
        self::MDL => 'MDL',
        self::MKD => 'ден',
        self::MMK => 'MMK',
        self::MNT => '₮',
        self::MOP => 'MOP$',
        self::MUR => '₨',
        self::MVR => 'Rf',
        self::MWK => 'MK',
        self::MXN => 'Mex$',
        self::MYR => 'RM',
        self::NAD => 'N$',
        self::NGN => '₦',
        self::NIO => 'NIO',
        self::NOK => 'NOK',
        self::NPR => 'रू',
        self::NZD => 'NZ$',
        self::OMR => 'ر.ع.',
        self::PEN => 'S/',
        self::PGK => 'PGK',
        self::PHP => '₱',
        self::PKR => '₨',
        self::QAR => 'QR',
        self::RUB => '₽',
        self::SAR => 'SR',
        self::SCR => 'SRe',
        self::SEK => 'SEK',
        self::SGD => 'S$',
        self::SLL => 'Le',
        self::SOS => 'Sh.so.',
        self::SSP => 'SS£',
        self::SVC => '₡',
        self::SZL => 'E',
        self::THB => '฿',
        self::TRY => '₺',
        self::TTD => 'TT$',
        self::TZS => 'Sh',
        self::USD => '$',
        self::UYU => '$U',
        self::UZS => 'so\'m',
        self::YER => '﷼',
        self::ZAR => 'R',
    ];

    const NAME = [
        self::AED => 'Emirati Dirham',
        self::ALL => 'Albanian Lek',
        self::AMD => 'Armenian Dram',
        self::ARS => 'Argentine Peso',
        self::AUD => 'Australian Dollar',
        self::AWG => 'Aruban or Dutch Guilder',
        self::BBD => 'Barbadian or Bajan Dollar',
        self::BDT => 'Bangladeshi Taka',
        self::BHD => 'Bahraini Dinar',
        self::BMD => 'Bermudian Dollar',
        self::BND => 'Bruneian Dollar',
        self::BOB => 'Bolivian Bolíviano',
        self::BSD => 'Bahamian Dollar',
        self::BWP => 'Botswana Pula',
        self::BZD => 'Belizean Dollar',
        self::CAD => 'Canadian Dollar',
        self::CHF => 'Swiss Franc',
        self::CNY => 'Chinese Yuan Renminbi',
        self::COP => 'Colombian Peso',
        self::CRC => 'Costa Rican Colon',
        self::CUP => 'Cuban Peso',
        self::CZK => 'Czech Koruna',
        self::DKK => 'Danish Krone',
        self::DOP => 'Dominican Peso',
        self::DZD => 'Algerian Dinar',
        self::EGP => 'Egyptian Pound',
        self::ETB => 'Ethiopian Birr',
        self::EUR => 'Euro',
        self::FJD => 'Fijian Dollar',
        self::GBP => 'British Pound',
        self::GHS => 'Ghanaian Cedi',
        self::GIP => 'Gibraltar Pound',
        self::GMD => 'Gambian Dalasi',
        self::GTQ => 'Guatemalan Quetzal',
        self::GYD => 'Guyanese Dollar',
        self::HKD => 'Hong Kong Dollar',
        self::HNL => 'Honduran Lempira',
        self::HRK => 'Croatian Kuna',
        self::HTG => 'Haitian Gourde',
        self::HUF => 'Hungarian Forint',
        self::IDR => 'Indonesian Rupiah',
        self::ILS => 'Israeli Shekel',
        self::INR => 'Indian Rupee',
        self::JMD => 'Jamaican Dollar',
        self::KES => 'Kenyan Shilling',
        self::KGS => 'Kyrgyzstani Som',
        self::KHR => 'Cambodian Riel',
        self::KWD => 'Kuwaiti Dinar',
        self::KYD => 'Caymanian Dollar',
        self::KZT => 'Kazakhstani Tenge',
        self::LAK => 'Lao Kip',
        self::LKR => 'Sri Lankan Rupee',
        self::LRD => 'Liberian Dollar',
        self::LSL => 'Basotho Loti',
        self::MAD => 'Moroccan Dirham',
        self::MDL => 'Moldovan Leu',
        self::MKD => 'Macedonian Denar',
        self::MMK => 'Burmese Kyat',
        self::MNT => 'Mongolian Tughrik',
        self::MOP => 'Macau Pataca',
        self::MUR => 'Mauritian Rupee',
        self::MVR => 'Maldivian Rufiyaa',
        self::MWK => 'Malawian Kwacha',
        self::MXN => 'Mexican Peso',
        self::MYR => 'Malaysian Ringgit',
        self::NAD => 'Namibian Dollar',
        self::NGN => 'Nigerian Naira',
        self::NIO => 'Nicaraguan Cordoba',
        self::NOK => 'Norwegian Krone',
        self::NPR => 'Nepalese Rupee',
        self::NZD => 'New Zealand Dollar',
        self::OMR => 'Rial Omani',
        self::PEN => 'Peruvian Sol',
        self::PGK => 'Papua New Guinean Kina',
        self::PHP => 'Philippine Peso',
        self::PKR => 'Pakistani Rupee',
        self::QAR => 'Qatari Riyal',
        self::RUB => 'Russian Ruble',
        self::SAR => 'Saudi Arabian Riyal',
        self::SCR => 'Seychellois Rupee',
        self::SEK => 'Swedish Krona',
        self::SGD => 'Singapore Dollar',
        self::SLL => 'Sierra Leonean Leone',
        self::SOS => 'Somali Shilling',
        self::SSP => 'South Sudanese Pound',
        self::SVC => 'Salvadoran Colon',
        self::SZL => 'Swazi Lilangeni',
        self::THB => 'Thai Baht',
        self::TRY => 'Turkish Lira',
        self::TTD => 'Trinidadian Dollar',
        self::TZS => 'Tanzanian Shilling',
        self::USD => 'US Dollar',
        self::UYU => 'Uruguayan Peso',
        self::UZS => 'Uzbekistani Som',
        self::YER => 'Yemeni Rial',
        self::ZAR => 'South African Rand',
    ];

    public static function getIsoCode(string $currency)
    {
        return self::ISO_NUMERIC_CODES[$currency] ?? null;
    }

    public static function getCurrency(string $isoCode)
    {
        $isoCurrencyCode = array_flip(self::ISO_NUMERIC_CODES);

        return $isoCurrencyCode[$isoCode] ?? null;
    }

    public static function getSymbol(string $currency)
    {
        return self::SYMBOL[$currency] ?? '';
    }

    public static function getExponent(string $currency)
    {
        return self::EXPONENT[$currency] ?? 2;
    }

    public static function getDenomination(string $currency)
    {
        return self::DENOMINATION_FACTOR[$currency] ?? 100;
    }

    public static function getMinAmount(string $currency)
    {
        return self::MIN_VALUE[$currency] ?? 100;
    }

    public static function getMinAuthValue(string $currency)
    {
        return self::MIN_AUTH_VALUE[$currency] ?? 100;
    }

    public static function getName(string $currency)
    {
        return self::NAME[$currency] ?? '';
    }

    public static function getDetails()
    {
        $currencyDetails = [];

        foreach (self::SUPPORTED_CURRENCIES as $currency)
        {
            $currencyDetails[$currency] = [
                'code'            => self::getIsoCode($currency),
                'denomination'    => self::getDenomination($currency),
                'min_value'       => self::getMinAmount($currency),
                'min_auth_value'  => self::getMinAuthValue($currency),
                'symbol'          => self::getSymbol($currency),
                'name'            => self::getName($currency),
            ];
        }

        return $currencyDetails;
    }

    public static function isSupportedCurrency($currency)
    {
        if (in_array($currency, self::SUPPORTED_CURRENCIES, true) === true)
        {
            return true;
        }

        return false;
    }

    public static function getCurrencyForCountry(string $countryCode)
    {
        return self::COUNTRY_CURRENCY_CODES[$countryCode] ?? null;
    }
}
